flow-typed/flow-typed

- package.json
- runtests.sh
- underscore/.flowconfig
- underscore/test.js
- underscore/underscore.js
Thanks for creating this repo! Let's get things rolling.
Here is [my project's][1] lame attempt to write flow declarations for underscore. We've written declarations only as we've used new functions, so it's nowhere close to complete.
Open questions:
- What should tests look like?
- What's the best way to integrate FlowTyped into a project (should it be an NPM module?)
See also https://github.com/facebook/flow/issues/946, which makes this less useful than it could be.
[1]: https://github.com/hammerlab/pileup.js/blob/d603ce88a6d0d43290faafa22bc6c4dc9d5c2dd5/lib/underscore.js
> Type definitions for (a small subset of) underscore

- npm/src/commands/runTests.js
- npm/src/lib/definitions.js
[My previous (seemingly innocuous) commit](https://github.com/flowtype/flow-typed/commit/bb576bb2501514f6d3fce0386d6f125e8e448c46) added the `.cli-metadata.json` file in the /definitions directory
which broke `flow-typed validate-defs` and `flow-typed run-tests` (they didn't
expect to see a non-directory in there).
This fixes those commands (and their respective machinery) to just ignore this file
as a special-case.
> Fix tests since the last commit

- definitions/clamp-js_v0.7.x/test_clamp-js_v0.7.x.js
- definitions/classnames_v2.x.x/flow_>=v0.23.x/classnames_v2.x.x.js
- definitions/classnames_v2.x.x/test_classnames_v2.x.x.js
- definitions/color_v0.7.x/flow_>=v0.23.x/color_v0.7.x.js
- definitions/color_v0.7.x/test_color_v0.7.x.js
- definitions/dropzone_v4.x.x/flow_>=v0.23.x/dropzone_v4.x.x.js
- definitions/dropzone_v4.x.x/test_dropzone_v4.x.x.js
- definitions/pluralize_v1.x.x/flow_>=v0.13.x/pluralize_v1.x.x.js
- definitions/pluralize_v1.x.x/test_pluralize_v1.x.x.js
- npm/src/lib/libDef.js
Per https://github.com/flowtype/flow-typed/issues/70, we'll require at least 1 test file with all libdef contributions.
This PR adds tests for all libdefs we have currently that lack them, and up next (later today or tomorrow) I'm going to make `validate-defs` error if a libdef is missing tests to help ensure we stay clean in this sense going forward.
(cc @marudor @splodingsocks )
> add tests for libdefs that lack them

- npm/src/commands/validateDefs.js
Per https://github.com/flowtype/flow-typed/issues/70, we want to be sure that all libdefs are tested.
By adding this requirement to `validate-defs`, we ensure that Travis checks this requirement for us
> Make `validate-defs` require that at least one test applies to every definition file

- definitions/highlight.js_v8.x.x/flow_>=v0.13.x/highlight.js_v8.x.x.js
- definitions/highlight.js_v8.x.x/test_highlight.js-v8.js
This adds highlight.js with tests.
the only thing which I'm not sure is the `HighlightJs$Continuation`, what I wanted to achieve is that whatever is returned in `HighlightResult.top` is valid as `continuation` argument to `highlight()`, and nothing else. The object that is returned in `HighlightResult.top` is an internal token to be passed to highlight(), but is not described in their API docs.
> Add highlight.js

- .gitignore
- .travis.yml
- definitions/yargs_v4.x.x/flow_>=v0.23.x/yargs_v4.x.x.js
- npm/.babelrc
- npm/.eslintignore
- npm/.eslintrc
- npm/.flowconfig
- npm/.npmignore
- npm/flow-typed/yargs_v4.x.x.js
- npm/package.json
- npm/src/cli.js
- npm/src/commands/__tests__/search-test.js
- npm/src/commands/install.js
- npm/src/commands/runTests.js
- npm/src/commands/search.js
- npm/src/commands/validateDefs.js
- npm/src/lib/__tests__/libDef-test.js
- npm/src/lib/__tests__/libDef-test__fixtures.js
- npm/src/lib/__tests__/semver-test.js
- npm/src/lib/fileUtils.js
- npm/src/lib/github.js
- npm/src/lib/libDef.js
- npm/src/lib/node.js
- npm/src/lib/semver.js
- runtests.sh
Thanks to both @splodingsocks and @ryyppy, this is a working version of `flow-typed install`!
It works using the same machinery as `flow-typed search`, except it will actually fetch and save the libdef to the `flow-typed/` directory. There's some extra noise in here from the addition of eslint, but hopefully not too hard to skim/scroll past...
Note: While the `install` command here works, it has certainly uncovered some more work for us. I'll make issues for each of these once this PR lands:
1. As @ryyppy pointed out somewhere already, this will hit the github API rate-limiter fairly quickly. We really need to solve this before we can "launch" the CLI. We can discuss options for this in the issue I'll create for it, but my current thoughts are that we should do something similar to …
> `install` comand

- cli/.eslintrc
- cli/flow-typed/yargs_v4.x.x.js
- cli/package.json
- cli/src/commands/install.js
- cli/src/lib/__tests__/codeSign-test.js
- cli/src/lib/codeSign.js
- cli/src/lib/fileUtils.js
- cli/src/lib/libDefs.js
- cli/src/lib/node.js
This signs libdefs with a version (their "last updated" commit sha) so that we can detect if they've been locally modified or if there is a new version available.
We don't make use of the version or signature info just yet, but we'll likely want to in the near future:
* Tell the user if any of their installed libdefs have been updated since they last installed
* Detect local modifications and encourage users to contribute their libdef improvements upstream
> Sign libdefs during `install` command

- cli/flow-typed/yargs_v4.x.x.js
- cli/src/lib/libDefs.js
* Change the code-signature logic to include the flow version (at the time of installation) for quick reference.
* Shorten the git sha version to 10chars ([more than enough to uniquely distinguish](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1))
> include flow version in signed code version string

- cli/flow-typed/yargs_v4.x.x.js
- cli/src/__mocks__/nodegit.js
- cli/src/commands/install.js
- cli/src/lib/__tests__/libDefs-test.js
- cli/src/lib/libDefs.js
This tweaks the `.flow-typed/repo/` rebase logic to be a little more robust:
* If rebasing fails (i.e. on a plane/no internet/etc), don't throw -- just emit a warning that we couldn't update. A stale cache is better than nothing.
* If someone mucks with the `.flow-typed/` repo manually somehow (i.e. deletes the `/repo` dir, or everything in it, or writes non-numbers to the `lastUpdated` file) -- try to deal with those circumstances cleanly. There are plenty of ways to muck with the repo dir that are hard to recover from, but we might as well try for the simple ones.
> Make cache rebase a little more robust

- definitions/npm/redux-form_v5.x.x/flow_>=v0.22.1/redux-form_v5.x.x.js
Ran into this flow error when implementing a form using `redux-form`...
Adding `error` as an optional field to `InputProps` fixes the issue and is consistent with the Redux Form API (http://redux-form.com/5.2.3/#/api/props?_k=dqnjtt). Also fixed a couple typos :)
> Update: Fix typos and add optional error field to InputProps

- cli/package.json
- cli/src/lib/libDefs.js
- definitions/.cli-metadata.json
`flow_all` as a flow-version directory name is just sugar for `flow_vx.x.x` and should work -- but it wasn't.
This fixes the version parser to deal with this.
https://github.com/flowtype/flow-typed/issues/105
> Fix support for `flow_all` as a flow-version directory

- definitions/npm/rxjs_v5.0.x/flow_>=v0.25.0/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
`empty`, `never`, and `ignoreElements` should be typed as "an observable of some type" rather than Observables of any. This prevents possible type degradation when they're combined with Observables of well-defined types.
> rxjs: Properly type Observables that never produce values

- definitions/npm/tape_v4.5.x/flow_>=v0.25.x/tape_v4.5.x.js
- definitions/npm/tape_v4.5.x/test_tape_v4.5.x.js
Finally got this working... I am not 100% happy with how flow infers the test-context function `(t) => { ... }`, when provided as first or second argument,.... but yeah, it's basically working with all of my (extensive) tape tests on our current projects.
> Add tape v4.5.x libdef

- cli/src/commands/install.js
- cli/src/lib/__tests__/libDefs-test.js
- cli/src/lib/libDefs.js
fizzy filter should filter on partial name for search command.
But I think, in case of install command, it should filter using correct package name.
How do you think?
```
$ flow-typed install -o -f 0.26.0 redux
* found 3 matching libdefs.
'redux-actions_v0.9.x.js' installed at /Users/noguchimasato/.ghq/github.com/joe-re/pomodo-desuka/flow-typed/npm/redux-actions_v0.9.x.js.
```
oops...installed redux-action.
```
$ flow-typed install -o -f 0.26.0 redux
* found 1 matching libdefs.
'redux_v3.x.x.js' installed at /Users/noguchimasato/.ghq/github.com/joe-re/flow-typed/cli/flow-typed/npm/redux_v3.x.x.js.
```
> add fuzzy-install to filterLibDefs's types

- definitions/npm/mocha_v2.4.x/flow_>=v0.22.x/mocha_v2.4.x.js
- definitions/npm/mocha_v2.4.x/test_mocha_v2.4.x_context.js
`context` is an alias for `describe`
> Add definition for mocha's 'context' function

- cli/src/cli.js
- cli/src/commands/update-cache.js
- cli/src/lib/__tests__/libDefs-test.js
- cli/src/lib/libDefs.js
This commit also adds another parameter to the ensureCacheRepo function,
so we can reuse the logic for updating the cache-repo without a 5-day
limit (which is still the limit by default).
Issue: #111 
@jeffmo
> Add update-cache command

- definitions/npm/rxjs_v5.0.x/flow_>=v0.25.0/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
> The [GroupBy operator][1] divides an Observable that emits items into an
Observable that emits Observables, each one of which emits some subset
of the items from the original source Observable.
Fixes #153
[1]: http://reactivex.io/documentation/operators/groupby.html
> Add RxJS `groupBy` operator

- definitions/npm/enzyme_v2.3.x/flow_>=v0.23.x/enzyme_v2.3.x.js
- definitions/npm/enzyme_v2.3.x/test_enzyme-v2.3.js
https://github.com/airbnb/enzyme/blob/master/CHANGELOG.md
Is this the right way to have a 2.x.x and 2.3.x matcher co-exist? (Actually, is that supported yet? The run-tests command seems to assume there will be only one because when added this dir it no longer picked up 2.x.x)
> support Enzyme 2.3 additions

- definitions/npm/ramda_v0.21.x/flow_>=v0.23.x/ramda_v0.21.x.js
- definitions/npm/ramda_v0.21.x/test_ramda_v0.21.x.js
Ramda sortBy only accepts two arguments:
http://ramdajs.com/docs/#sortBy
This PR fixes that problem and adds a test for the curried/total cases.
> [Ramda] Fix ramda sortBy typedef, add test

- .travis.yml
- cli/.flowconfig
- cli/flow-typed/npm/yargs_v4.x.x.js
- cli/package.json
- cli/src/cli.js
- cli/src/commands/runCITests.js
- cli/src/commands/runTests.js
- cli/src/commands/validateDefs.js
- cli/src/lib/libDefs.js
- travis.sh
Adds a `flow-typed run-ci-tests` command that looks at the diff between the current working directory and `origin/master`, extracts a list of libdefs that were changed/added, and only runs applicable tests (rather than *all* tests).
Fixes https://github.com/flowtype/flow-typed/issues/76
> Only run tests in Travis for stuff that changed 

- definitions/npm/shelljs_v0.7.x/flow_>=v0.28.x/shelljs_v0.7.x.js
- definitions/npm/shelljs_v0.7.x/test_shelljs_v0.7.x.js
This PR adds flow declarations for `shelljs`. It covers the complete API but in some cases I have restricted the interfaces for certain functions to the part that can be reasonably typed. However, this should not limit functionality.
I've added tests following some of the others as examples but I had some trouble getting the `flow-typed` CLI tool to run them.
> Add shelljs (v0.7.0) declarations

- definitions/npm/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js
I use `interface` for `Route`'s methods and `Router`'s methods, and I can improve the complexity of the tweaking codes.
> Use interface to reuse codes

- definitions/npm/bunyan_v1.x.x/flow_>=v0.21.x/bunyan_v1.x.x.js
- definitions/npm/bunyan_v1.x.x/test_bunyan_v1.x.x.js
While `process.stdout` is not only a `stream$Writable`, but also a `tty$WriteStream` (https://github.com/facebook/flow/blob/master/lib/node.js#L1483), passing it as a `bunyan` stream causes errors.
Test was corrected to include originally failing case.
> Allow use of process.stdout as one of bunyan streams

- definitions/npm/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/test_express_v4.x.x.js
[response.js#L839](https://github.com/expressjs/express/blob/master/lib/response.js#L839) shows that it can take either `string` or `number, string` as arguments, so the current definition is not correct.
> express: update res.redirect signature with overloading

- definitions/npm/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/test_express_v4.x.x.js
I wanted to fix an error that I accidentally added when I first submitted the PR. The `res.locals` is always an object, just the same as the `app.locals`. I added more to the test cases to catch this issue.
> express: Fix the Request.locals typing

- definitions/npm/ecurve_v1.x.x/flow_>=v0.17.x/ecurve_v1.x.x.js
- definitions/npm/ecurve_v1.x.x/test_ecurve_v1.x.x.js
I am adding support for ecurve - a library for elliptic curves.
https://github.com/cryptocoinjs/ecurve
The bad thing is that it is using `bigi` module classes. I don't know how to solve this ( https://github.com/flowtype/flow-typed/issues/16 ).
So I just copy-pasted the definitions, so they are both in the same file. It's not a nice solution, but I don't know how to solve it correctly. Now it works.
> Add ecurve

- definitions/npm/moment_v2.x.x/flow_>=v0.28.x/moment_v2.x.x.js
see [max](http://momentjs.com/docs/#/get-set/max/) and [min](http://momentjs.com/docs/#/get-set/min/) documentation on the MomentJS website.
> min/max also accept arrays of Moment

- definitions/npm/chai_v3.5.x/flow_>=v0.24.0/chai_v3.5.x.js
- definitions/npm/chai_v3.5.x/test_chai_v3.5.x.js
There's probably still some work to do for these to be widely usable, but I figured I'd share what I have so far.
Some annoyances:
```js
expect(1).to.eql("1");
```
This should really be a type error, but for some reason flow infers the type to be `ExpectChain<number | string>` rather than sticking with what `expect()` says. Unsure how to fix this.
*****
The plugin system
Chai's plugin system allows plugins to add extra methods and properties to the ExpectChain, the only way I can think of to manage this in flow is to add them all to the core def. This PR currently includes some methods from a couple of plugins that I'm using in the project this is sourced from.
To complicate matters more, chai has a slightly awkward API where getters have side effects that won't be changed for back-compat …
> Add initial definitions for chai

- definitions/npm/bitcoinjs-lib_v2.x.x/flow_>=v0.17.x/bitcoinjs-lib_v2.x.x.js
- definitions/npm/bitcoinjs-lib_v2.x.x/test_bitcoinjs-lib_v2.x.x.js
- definitions/npm/ecurve_v1.x.x/flow_>=v0.17.x/ecurve_v1.x.x.js
I found some errors in the bitcoinjs-lib definitions. 
The inputs to `ECPair` is not buffer, but either biginteger or ecpoint, both imported from different packages.
> Correcting bitcoinjs definitions

- definitions/npm/is-absolute-url_v2.x.x/flow_>=v0.25.x/is-absolute-url_v2.x.x.js
- definitions/npm/is-absolute-url_v2.x.x/test_is-absolute-url_v2.x.x.js
- definitions/npm/is-archive_v1.x.x/flow_>=v0.25.x/is-archive_v1.x.x.js
- definitions/npm/is-archive_v1.x.x/test_is-archive_v1.x.x.js
- definitions/npm/is-binary-path_v1.x.x/flow_>=v0.25.x/is-binary-path_v1.x.x.js
- definitions/npm/is-binary-path_v1.x.x/test_is-binary-path_v1.x.x.js
- definitions/npm/is-compressed_v1.x.x/flow_>=v0.25.x/is-compressed_v1.x.x.js
- definitions/npm/is-compressed_v1.x.x/test_is-compressed_v1.x.x.js
- definitions/npm/is-path-cwd_v1.x.x/flow_>=v0.25.x/is-path-cwd_v1.x.x.js
- definitions/npm/is-path-cwd_v1.x.x/test_is-path-cwd_v1.x.x.js
- definitions/npm/is-path-in-cwd_v1.x.x/flow_>=v0.25.x/is-path-in-cwd_v1.x.x.js
- definitions/npm/is-path-in-cwd_v1.x.x/test_is-path-in-cwd_v1.x.x.js
- definitions/npm/is-relative-url_v2.x.x/flow_>=v0.25.x/is-relative-url_v2.x.x.js
- definitions/npm/is-relative-url_v2.x.x/test_is-relative-url_v2.x.x.js
- definitions/npm/is-root-path_v1.x.x/flow_>=v0.25.x/is-root-path_v1.x.x.js
- definitions/npm/is-root-path_v1.x.x/test_is-root-path_v1.x.x.js
- definitions/npm/is-root_v1.x.x/flow_>=v0.25.x/is-root_v1.x.x.js
- definitions/npm/is-root_v1.x.x/test_is-root_v1.x.x.js
- definitions/npm/is-text-path_v1.x.x/flow_>=v0.25.x/is-text-path_v1.x.x.js
- definitions/npm/is-text-path_v1.x.x/test_is-text-path_v1.x.x.js
- [is-absolute-url](https://npmjs.com/package/is-absolute-url)
- [is-archive](https://npmjs.com/package/is-archive)
- [is-binary-path](https://npmjs.com/package/is-binary-path)
- [is-compressed](https://npmjs.com/package/is-compressed)
- [is-path-cwd](https://npmjs.com/package/is-path-cwd)
- [is-path-in-cwd](https://npmjs.com/package/is-path-in-cwd)
- [is-relative-url](https://npmjs.com/package/is-relative-url)
- [is-root](https://npmjs.com/package/is-root)
- [is-text-path](https://npmjs.com/package/is-text-path)
- [is-root-path](https://npmjs.com/package/is-root-path)
> Added type definiations for few sindre is-* modules

- definitions/npm/react-redux_v4.x.x/flow_>=v0.30.x/react-redux_v4.x.x.js
- definitions/npm/react-redux_v4.x.x/test_react-redux_v4.x.x.js
Adds types for React-redux. Properly typed higher-order function.
NOTE: somehow the tests are failing, though type definitions work correctly in practice.
> React redux

- definitions/npm/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/test_express_v4.x.x.js
Fix #261 
It was a mere operator precedence bug. I've put tests that were failing and put some parenthesis to fix it.
> #261 fix operator precedence bug for Middleware

- definitions/npm/debug_v2.x.x/flow_>=v0.28.x/debug_v2.x.x.js
- definitions/npm/debug_v2.x.x/test_debug_v2.x.x.js
As currently declared, Debugger functions can only accept a string as their first argument.
However, Debugger functions are specifically implemented to also accept an Error as their first argument (instead of a formatter)--or no formatter/error at all.
See:
https://github.com/visionmedia/debug/blob/master/debug.js#L88-L93
and 'coerce' at: https://github.com/visionmedia/debug/blob/master/debug.js#L194-L197
Note that these changes allow a debugger function to be called with any pattern of arguments--there may be value in restricting that, but I couldn't find any definitive guidance on the intended API of those functions in the project's docs/code.
> Debug v2.x.x: relax first param of Debugger declaration

- definitions/npm/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/test_express_v4.x.x.js
http://expressjs.com/en/api.html#res.render
> include html in Express render callback

- definitions/npm/react-dnd_v2.x.x/flow_>=v0.23.x/react-dnd_v2.x.x.js
- definitions/npm/react-dnd_v2.x.x/test_react-dnd-v2.js
Updated the react-dnd definitions based on existing TypeScript
definitions from DefinitelyTyped. Type definitions are now complete
based on react-dnd documents.
Added unit tests exercising this functionality.
Also fixed incorrect signatures for DragLayer.
> Improve type information for react-dnd

- definitions/npm/rxjs_v5.0.x/flow_>=v0.29.0/rxjs_v5.0.x.js
I removed code marked as not necessary for >= 0.29 and added definitions that I needed in my own projects.
I'm guessing there's not another way to do this, but I'd be happy to found out if there were.
> rxjs: add some combineLatest and withLatestFrom definitions

- cli/src/lib/libDefs.js
Per https://github.com/flowtype/flow-typed/issues/226, people seem to be having
issues when the CLI attempts to clone the flow-typed repo into local cache.
Specifically, the github seems to require authentication to do this clone.
[There are some reports](https://github.com/flowtype/flow-typed/issues/226#issuecomment-239968111) that suggest that cloning over http does not require said auth, so
this switches things to http to attempt to mitigate the problem.
> Switch from `https` to `http` for cache repo clones

- definitions/npm/tape_v4.5.x/flow_>=v0.25.x/tape_v4.5.x.js
Let tape$TestCb return a promise
If you want to use async/await with Tape you will need to prefix your test function with async, e.g.
```
test('Promise resolves true', async (assert: tape$Context) => {
const result = await promiseFunction();
assert.true(result);
assert.end();
}
```
But this will cause type checking to fail as the callback no longer returns void.
> Let tape$TestCb return a promise

- cli/src/lib/__tests__/semver-test.js
- cli/src/lib/libDefs.js
- cli/src/lib/semver.js
flow versions of packages should be satisfiable, in the sense that we should not allow bogus ranges whose lower bound and upper bound point in the wrong directions
> check version sat

- CONTRIBUTING.md
- README.md
This just tweaks the README.md and CONTRIBUTING.md docs a bit + updates them with post-launch details (This is part of https://github.com/flowtype/flow-typed/issues/254).
Note that assumes the [`flow-typed install` command (no flags)](https://github.com/flowtype/flow-typed/pull/289) feature has landed, so it shouldn't land until after that does.
> Updated Readme + Contributing docs

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.32.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
I'm using the ES6 importing syntax of rxjs and directly import from `rxjs/Observable` for example. Flowtype didn't know about this syntax and was complaining about the unknown type.
To fix this I saw no other way than using the `$` syntax to allow importing the same things from different sources w/o having to re-declare everything again and again (DRY).
Also, imo I fixed the namespace rxjs to use `rxjs$` instead of `rx$` since RxJS v5 is installed as `npm i rxjs` and not `rx`, which is the old version of the Reactive Extensions Library.
> Fixes for RxJS v5 type definitions

- cli/package.json
- cli/src/lib/npmProjectUtils.js
- cli/src/lib/stubUtils.js
Previously we'd use `resolve()` to find the path to an `npm install`ed
dependency. This usually works, but in some cases a package doesn't have
either an `index.js` file or a `main` entry in its package.json. `react-scripts`
is one such example.
This makes us resilient to this case when looking up the directory path for the installed package.
Fixes #338
> Fix `flow-typed install` for packages without a 'main'/index.js

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.32.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
Types for the following methods:
- `audit()`
- `concatAll()`
- `pairwise()`
- `forkJoin()`
> Add types for more RxJS 5 methods

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.32.x/rxjs_v5.0.x.js
Looks like this snuck through in 46017ce8a27c489ee96b7f69cf3670fb73fed97c.
> RxJS: Remove committed signature

- definitions/npm/jest_v16.x.x/flow_v0.33.x-/jest_v16.x.x.js
- definitions/npm/jest_v16.x.x/test_jest-v16.x.x.js
This adds definitions for Jest 16. I copied Jest 14's definitions and added in some missing things. (I think most of the definitions were based on Jasmine's, but Jest appears to have more functions than Jasmine did.) A bunch of missing expect() object methods were added, and I made some types more specific so that `{test,it}.{only,skip}` are typed now. (These APIs may or may not exist in older versions of Jest, dunno if anyone feels strongly about updating the older definitions too.) I re-ordered a few things not very far to match the order on [Jest's API page](https://facebook.github.io/jest/docs/api.html).
The first commit copies Jest 14's definitions as-is to new files for Jest 16, and then the second commit modifies them.
> Jest 16 definitions

- definitions/npm/pluralize_v2.x.x/flow_v0.13.x-/pluralize_v2.x.x.js
- definitions/npm/pluralize_v2.x.x/test_pluralize_v2.x.x.js
- definitions/npm/pluralize_v3.x.x/flow_v0.13.x-/pluralize_v3.x.x.js
- definitions/npm/pluralize_v3.x.x/test_pluralize_v3.x.x.js
The definitions for 1.x, 2.0 and 3.0 are completely identical as the public API hasn't changed, but as far as I could see there is no way right now to inherit or have version ranges, right? 
Maybe this would be a nice addition, although not sure how often this case really happens.
> Add definitions for pluralize 2.0 and 3.0

- definitions/npm/xstream_v6.x.x/flow_v0.33.0-/xstream_v6.x.x.js
- definitions/npm/xstream_v6.x.x/test_xstream.js
Adds typings for [xstream](https://github.com/staltz/xstream)
Combine should probably use a $TupleMap, but I don't know how that feature even works. Would appreciate it if someone could show me how it should be done, i.e. given types A, B, and C, `combine(s1: Stream<A>, s2: Stream<B>, s3: Stream<C>): Stream<[A, B, C]>`
> Add xstream typings

- definitions/npm/underscore_v1.x.x/flow_v0.13.x-/underscore_v1.x.x.js
Per the [documentation](http://underscorejs.org/#pairs), `pairs` converts an object into a list of `[key, value]` pairs. As such it is the inverse of the `object` function, as the signature alludes to.
> Add declaration for `pairs`

- definitions/npm/redux-actions_v0.9.x/flow_v0.23.x-/redux-actions_v0.9.x.js
- definitions/npm/redux-actions_v0.9.x/test_redux-actions-v0.9.js
`handleAction` and `handleActions` are defined as returning `void`. They actually [return](https://github.com/acdlite/redux-actions/blob/master/src/handleAction.js#L14-L20) [functions](https://github.com/acdlite/redux-actions/blob/master/src/handleActions.js#L9).
> Fixes for redux-actions return types

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.32.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
Heyo, I've been using flow with RxJS for a few days, and noticed that a few method definitions are missing. This adds a couple that I've been wanting to use without ignoring in flow.
It's unfortunate that the typing for `.switch()` can't assert that `T` be an `Observable` (at least I assume this is the case, backed up by what I see with `.mergeAll()`), but I'd be happy to take suggestions to make that better.
> Adding RxJS operators let, letBind, and switch

- definitions/npm/underscore_v1.x.x/flow_v0.13.x-/underscore_v1.x.x.js
- definitions/npm/underscore_v1.x.x/test_underscore-v1.js
This adds a bunch of definitions which our app was relying on.  Also, I wasn't sure that the old definition for `map` was correct:
```diff
-  declare function map<T, U>(a: T[], iteratee: (val: T, n?: number)=>U): U[];
+  declare function map<T, U>(a: T[], iteratee: (val: T, n: number)=>U): U[];
```
The old version means you can't do `_.map(['a', 'b', 'c'], function(e, i) { return i < 2 })` because flow thinks `i` may be undefined.   I've changed it to allow that, which doesn't appear to any adverse effects on use of map where you don't include the index argument (eg `_.map(['a', 'b', 'c'], function(e) { return e != 'b' })`
> Add more underscore definitions

- definitions/npm/fetch-ponyfill_v3.x.x/flow_v0.28.x-/fetch-ponyfill_v3.x.x.js
- definitions/npm/fetch-ponyfill_v3.x.x/test_fetch-ponyfill_v3.x.x.js
May find itself in more widespread use due to vendor bugs (most egregiously, Edge 14) which require that you overwrite or completely ignore `window.fetch`.
> Add fetch-ponyfill definition

- definitions/npm/ramda_v0.21.x/flow_v0.23.x-v0.27.x/ramda_v0.21.x.js
- definitions/npm/ramda_v0.21.x/flow_v0.23.x-v0.27.x/test_ramda_v0.21.x.js
- definitions/npm/ramda_v0.21.x/flow_v0.28.x-v0.29.x/ramda_v0.21.x.js
- definitions/npm/ramda_v0.21.x/flow_v0.28.x-v0.29.x/test_ramda_v0.21.x_list.js
Currently, the R.zipObj type is incorrect. If you look at the docs,
http://ramdajs.com/docs/#zipObj, you'll see that zipObj returns an
object given two arrays (hence the name zipObj). I have confirmed this
error in my own projects and thought I'd make a PR to fix it here.
> fix ramda zipObj type

- definitions/npm/aphrodite_v0.5.x/flow_v0.28.x-/aphrodite_v0.5.x.js
- definitions/npm/aphrodite_v0.5.x/test_aphrodite-v0.5.x.js
The Aphrodite conditional styles API is not currently supported by the flow-typed definition:
https://github.com/Khan/aphrodite#conditionally-applying-styles
I do think trying to accept any false-y value hurts the value of our type checking a fair bit.
However, as a compromise, we can allow consumers to pass in the boolean `false` (or an expression that might resolve to false).  This permits us to use the full power of the API.  It's fairly trivial to cast a false-y value to a boolean if need be (some would argue this is more correct!).
> Support Aphrodite conditional style API

- definitions/npm/classnames_v2.x.x/flow_v0.23.x-v0.27.x/classnames_v2.x.x.js
- definitions/npm/classnames_v2.x.x/flow_v0.28.x-/classnames_v2.x.x.js
- definitions/npm/classnames_v2.x.x/test_classnames_v2.x.x.js
`classnames(false)` should be handled too: https://github.com/JedWatson/classnames/blob/master/index.js#L18
> Fix classnames_v2.x.x

- definitions/npm/react-modal_v1.x.x/flow_v0.26.x-/react-modal_v1.x.x.js
- definitions/npm/react-modal_v1.x.x/test_react-modal-v1.js
Added `Modal.setAppElement`, see [docs](https://github.com/reactjs/react-modal/tree/3d8e5a07466ed8ad367eed1f6a6c26a7516ab183#examples); defined [here](https://github.com/reactjs/react-modal/blob/3d8e5a07466ed8ad367eed1f6a6c26a7516ab183/lib/components/Modal.js#L17-L19) and [here](https://github.com/reactjs/react-modal/blob/3d8e5a07466ed8ad367eed1f6a6c26a7516ab183/lib/helpers/ariaAppHider.js#L3-L10).
> react-modal: add setAppElement method

- definitions/npm/currency-formatter_v1.x.x/flow_v0.25.x-/currency-formatter_v1.x.x.js
- definitions/npm/currency-formatter_v1.x.x/test_currency-formatter_v1.x.x.js
[`currency-formatter`](https://www.npmjs.com/package/currency-formatter)
I was unsure how to share types between the two provided modules - `currency-formatter` and `currency-formatter/currencies`. I followed the style I saw in a few other files: `$npm$currencyFormatter$Currency`.
> Add currency-formatter

- definitions/npm/lodash_v4.x.x/flow_v0.28.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/test_lodash-v4.x.x.js
Before it faikted to get the type in a (for instance) filter function,
```js
filter({ a: 1, b: 2}, x => x)
```
Before it did not know type of x.
Now it does.
> refine loadsh Object Predicate

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
The `cache()` operator was removed by ReactiveX/rxjs#2012. Since this
is still a prerelease (and Flow doesn't yet support prerelease
versions), we'll just remove it.
> RxJS 5: Remove cache operator

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-/rxjs_v5.0.x.js
Observer isn't exported and it no longer has these methods. (Well, I think one of them was a typo anyway 😝).
> RxJS: Correct Observer definition

- definitions/npm/ramda_v0.21.x/flow_v0.28.x-v0.30.x/ramda_v0.21.x.js
Came across these issues when introducing flow-type into an existing project with ramda. Did not look to see if there are more instances where a Maybe is possible in the ramda docs.
> fix: ramda 0.21.x more cases of Maybe

- definitions/npm/bluebird_v3.x.x/flow_v0.32.x-/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/test_bluebird-v3.x.x.js
Bluebird accepts native promises pretty much everywhere, as far as I can tell.  For example:
``` js
Bluebird.resolve(Promise.resolve('hello')).then(function(a: string) { })
```
ought to behave ok, but flow-typed currently expects 'a' to be `Promise<string>`, rather than a simple `string`.
I've attempted to fix that in this PR - WDYT?
>  Improve Bluebird's interoperability with native promises

- cli/src/commands/runTests.js
- cli/src/commands/validateDefs.js
- cli/src/lib/isInFlowTypedRepo.js
If the commands run-tests and validate-libdefs commands is run outside
the flow-typed repo it will display an error message saying that the
command is meant for the flow-typed repo.
Related to #403
> Add a descriptive error message to repo commands

- definitions/npm/bunyan_v1.x.x/flow_v0.21.x-/bunyan_v1.x.x.js
- definitions/npm/bunyan_v1.x.x/test_bunyan_v1.x.x.js
See #400 for detailed description of the issue
> Allow bunyan serializers to accept object literal (#400)

- definitions/npm/jest_v17.x.x/flow_v0.33.x-/jest_v17.x.x.js
- definitions/npm/jest_v17.x.x/test_jest-v17.x.x.js
This adds definitions for Jest 17. The first commit copies Jest 16's definitions and tests, and then the second commit edits them for [Jest 17's changes](https://github.com/facebook/jest/blob/master/CHANGELOG.md).
> Jest 17 definitions

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
Following the corresponding TypeScript definitions in
https://github.com/ReactiveX/rxjs/blob/master/src/operator/switchMapTo.ts
https://github.com/ReactiveX/rxjs/blob/master/src/observable/UsingObservable.ts
> rxjs: Add Observable.switchMapTo and Observable.using

- definitions/npm/redux-saga_v0.11.x/flow_v0.28.x-/redux-saga_v0.11.x.js
- definitions/npm/redux-saga_v0.11.x/test_redux-saga_0.11.x.js
Add middleware support to run a generator that returns an array of IOEffects, as in the [redux-saga real world example](https://github.com/yelouafi/redux-saga/blob/0dc376107d24537028bd1c66e4fce81c223f2c23/examples/real-world/sagas/index.js#L123)
> feat[redux-saga] add support for yield array in middleware

- definitions/npm/underscore_v1.x.x/flow_v0.13.x-/underscore_v1.x.x.js
- definitions/npm/underscore_v1.x.x/test_underscore-v1.js
The overall diff for this probably looks a bit overwhelming, but it should have minimal 'actual' changes.
The first commit (https://github.com/flowtype/flow-typed/commit/94097e20545635022bbc2bf90394987dbfafd15c) reorders the underscore definitions to match the docs at http://underscorejs.org/, groups everything by its alias (eg _.each, _.forEach), and adds a couple of missing aliases.
The remaining two are just adding new definitions for _.partition & _.size
> Underscore updates

- definitions/npm/meow_v3.x.x/flow_v0.28.x-/meow_v3.x.x.js
- definitions/npm/meow_v3.x.x/test_meow_v3.x.x.js
- definitions/npm/minimist_v1.x.x/flow_v0.28.x-/minimist_v1.x.x.js
- definitions/npm/minimist_v1.x.x/test_minimist_v1.x.x.js
Fix minimist and meow definitions handling of `boolean` and `string` option. 
Closes #451
Please review @marudor @thejameskyle
> Correct minimist and meow definitions

- definitions/npm/mocha_v3.1.x/flow_v0.22.x-/mocha_v3.1.x.js
- definitions/npm/mocha_v3.1.x/test_mocha_v3.1.x_context.js
- definitions/npm/mocha_v3.1.x/test_mocha_v3.1.x_describe.js
- definitions/npm/mocha_v3.1.x/test_mocha_v3.1.x_hooks.js
- definitions/npm/mocha_v3.1.x/test_mocha_v3.1.x_it.js
As far as I can tell, the defs already in `flow-typed` for mocha v2.4.x continue to work fine for mocha v3.1.x, so I've just copied them and `s/2.4/3.1/` where appropriate.
> mocha_v3.1.x

- definitions/npm/express_v4.x.x/flow_v0.25.x-/express_v4.x.x.js
Imports are not currently supported in declaration files. This is helpful for typing other classes that extend Express like the Webpack Development Server.
**Context:** https://github.com/facebook/flow/issues/2847
> Adding namedspaced globals for express with backward compatibility

- README.md
This adds two badges to the readme. 1) to travis.ci and 2) npmjs.com.
> Add shields/badges to readme

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
Concatting an `Observable<T>` with an `Observable<U>` should result in an `Observable<T | U>`.
Currently this can expand the type of the first observable if it's not fixed, causing spurious errors down the line.
> Fix (non-static) Observable.concat type

- definitions/npm/react-scripts_v0.7.x/flow_v0.33.x-/react-scripts_v0.7.x.js
- definitions/npm/react-scripts_v0.7.x/test_react-scripts-v0.7.x.js
react-scripts don't expose anything to the end user except the jest api.
That's why we're just copying the jest annotations.
Coming from here: https://github.com/facebookincubator/create-react-app/issues/72
> Create react-scripts annotation from jest

- definitions/npm/tape_v4.5.x/flow_v0.25.x-/tape_v4.5.x.js
> tape v4.5.x: add missing named export 'test' to tape

- definitions/npm/jest_v17.x.x/flow_v0.33.x-/jest_v17.x.x.js
- definitions/npm/jest_v17.x.x/test_jest-v17.x.x.js
Adds comments from the documentation inline into the Flow annotations.
A rough overview of using it:
As this doesn't change any of the flow structure, I don't think there's anything to change WRT the tests.
/cc @cpojer @dmitriiabramov
> Add ESDoc support to Jest

- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
I couldn't find a small repro case to turn into a test, but I saw a case in the Nuclide codebase where the upcoming Flow v0.36 had trouble selecting the correct forkJoin variant without these changes, picked the wrong one, and issued an error.
> [rxjs] Pin down argument number for forkJoin

- .editorconfig
I noticed that I messed up the indent size and style for the editorconfig file. Oops, this should fix this.
> Fix EditorConfig for indent size / style

- definitions/npm/express_v4.x.x/flow_v0.25.x-/express_v4.x.x.js
http://expressjs.com/en/api.html#res.cookie
> maxAge	Number	Convenient option for setting the expiry time relative to the current time in milliseconds
> type cookie maxAge as number

- definitions/npm/jest_v17.x.x/flow_v0.33.x-/jest_v17.x.x.js
- definitions/npm/react-scripts_v0.7.x/flow_v0.33.x-/react-scripts_v0.7.x.js
Make the test implementation optional in the it/test function. If the test implementation function is left off, jest just treats it like a skipped test.
> Make implementation optional in jest's it/test function

- definitions/npm/react-i18next_v1.10.x/flow_v0.36.x-/react-i18next_v1.10.x.js
- definitions/npm/react-i18next_v1.10.x/test_react-i18next_v1.10.x.js
Adds libdef for react-i18next. Should be fairly robust, though there are some holes (not checking the i18n object). Special attention has been given to the `translate` HOC, which was modeled after `connect` from react-redux. I am new to flow, so please let me know if there is anything I can improve.
Usage:
```js
// @flow
import { translate } from 'react-i18next'
import type { Translator, TFunction } from 'react-i18next'
type OwnProps = { s: string }
type Props = OwnProps & { t: TFunction }
const Comp = ({ t }: Props) => <div s={}>{ t('whatever') }</div>
const translator: Translator<OwnProps, Props> = translate('whatever')
const WrappedComp = translator(Comp)
const OtherComp = () => <Comp s={ 2 } /> // TypeError
```
> Add libdef for react-i18next

- definitions/npm/jest_v17.x.x/flow_v0.33.x-/jest_v17.x.x.js
- definitions/npm/jest_v17.x.x/test_jest-v17.x.x.js
* There are many common eslint warnings that trigger on jest.js, this diff removes them.
* There are a few errors in which methods allow chaining of the jest object and this diff addresses those errors by changing the return type from void to JestObjectType.
> Remove common eslint warnings from jest.js

- definitions/npm/moment_v2.x.x/flow_v0.28.x-/moment_v2.x.x.js
- definitions/npm/moment_v2.x.x/test_moment-v2.js
`isAfter|isBefore`etc. can also be called without any parameters. From the doc: 
> If nothing is passed to `moment#isBefore`, it will default to the current time.
> Update moment queries (isAfter...) to be called without params

- cli/package.json
Bumps `jest`, adds [`mkdirp`](https://github.com/substack/node-mkdirp) and [`rimraf`](https://github.com/isaacs/rimraf).
> Makes `scripts` Windows-compatible.

- definitions/npm/redux-saga_v0.11.x/flow_v0.28.x-/redux-saga_v0.11.x.js
- definitions/npm/redux-saga_v0.13.x/flow_v0.36.x-/redux-saga_v0.13.x.js
- definitions/npm/redux-saga_v0.13.x/test_redux-saga_0.13.x.js
Closes #469 .
For redux-saga 0.11.x, I applied quick fix for `Fn` definitions to support a call of normal function.
For redux-saga 0.13.x, I added new APIs and updated some definitions based on latest redux-saga's code. In addition to that, I added lots of test cases for `call` effect to check various types of function (normal function, Promise, Generator).
> Add defs for redux-saga 0.13.x

- definitions/npm/bcrypt_v0.8.x/flow_v0.29.x-/bcrypt_v0.8.x.js
- definitions/npm/bunyan_v1.x.x/flow_v0.21.x-/bunyan_v1.x.x.js
- definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js
- definitions/npm/express_v4.x.x/flow_v0.25.x-v0.27.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.28.x-/express_v4.x.x.js
- definitions/npm/fetch-ponyfill_v3.x.x/flow_v0.28.x-/fetch-ponyfill_v3.x.x.js
- definitions/npm/js-cookie_v2.x.x/flow_v0.25.x-/js-cookie_v2.x.x.js
- definitions/npm/paths-js_v0.4.x/flow_v0.32.x-/paths-js_v0.4.x.js
- definitions/npm/ramda_v0.21.x/flow_v0.23.x-v0.27.x/ramda_v0.21.x.js
- definitions/npm/ramda_v0.21.x/flow_v0.28.x-v0.30.x/ramda_v0.21.x.js
- definitions/npm/react-highlight-words_v0.4.x/flow_v0.28.x-/react-highlight-words_v0.4.x.js
- definitions/npm/react-recaptcha_v2.x.x/flow_v0.26.x-/react-recaptcha_v2.x.x.js
- definitions/npm/redux-form_v5.x.x/flow_v0.22.1-/redux-form_v5.x.x.js
- definitions/npm/redux-saga_v0.11.x/flow_v0.28.x-/redux-saga_v0.11.x.js
- definitions/npm/redux-saga_v0.13.x/flow_v0.36.x-/redux-saga_v0.13.x.js
- definitions/npm/tape_v4.5.x/flow_v0.25.x-/tape_v4.5.x.js
- definitions/npm/webfontloader_v1.x.x/flow_v0.23.x-/webfontloader_v1.x.x.js
This keeps users' `flow` commands from re-type-checking all of their dependencies' `flow-typed` definitions.
By default Flow type-checks all files with `@flow` pragmas, including those found in `node_modules`. It doesn't know to ignore nested `flow_typed` directories, so definitions with `@flow` pragmas get type-checked along with everything else.
> Drop @flow pragma from definitions

- definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js
- definitions/npm/chai_v3.5.x/test_chai_v3.5.x.js
A couple changes were required to get rid of all Flow warnings on a 6000-line project:
1. Chai allows you to check length with a function call: `.length(4)`
2. Chai's configuration option `truncateThreshold` is a number, not a boolean
> Chai tweaks

- definitions/npm/lodash_v4.x.x/flow_v0.28.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/test_lodash-v4.x.x.js
* Fix `_.matchesProperty` iteratee shorthand (e.g. `_.find(users, ['active', false])`)
* Fix `_.property` iteratee shorthand (e.g. `_.map(users, 'age')`)
> Fix missing types in Lodash

- definitions/npm/moment_v2.x.x/flow_v0.28.x-/moment_v2.x.x.js
- definitions/npm/moment_v2.x.x/test_moment-v2.js
Fixes a simple typo in moment definition. Fixes #564.
> moment_v2.x.x.js typo, isDatE -> isDate

- definitions/npm/lodash_v4.x.x/flow_v0.28.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/test_lodash-v4.x.x.js
_.times returns an array that can be optionally mapped with the iteratee argument.
```javascript
_.times(2) // => [1, 2]
_.times(3, String) //= ['1', '2', '3']
```
> Accurate signature for lodash times

- definitions/npm/bser_v1.x.x/flow_v0.28.x-/bser_v1.x.x.js
- definitions/npm/bser_v1.x.x/test_bser_v1.x.x.js
- definitions/npm/node-int64_v0.4.x/flow_v0.25.x-/node-int64_v0.4.x.js
- definitions/npm/node-int64_v0.4.x/test_node-int64_v0.4.x.js
This is the definition for the package `bser` (https://github.com/facebook/watchman/tree/master/node/bser)
I have two questions:
* Is it valid that one of the objects extends `EventEmitter`, because flowtype.org/try says `"Could not resolve name EventEmitter"`?
* How would I use types from other definitions? Is that already possible? Because `bser` also accepts and returns instances of `Int64` (npm.im/node-int64), so assuming a type definition would exists for it how would I reference it?
Tests are still missing, but wanted to ask the questions first.
> Definition for bser and node-int64

- definitions/npm/bluebird_v3.x.x/flow_v0.32.x-/bluebird_v3.x.x.js
`Bluebird.promisifyAll` also accepts an array form as per http://bluebirdjs.com/docs/api/promise.promisifyall.html#promisifying-multiple-classes-in-one-go
> Add Bluebird.promisifyAll array form

- definitions/npm/koa_v2.x.x/flow_v0.37.x-/koa_v2.x.x.js
- definitions/npm/koa_v2.x.x/test_koa_v2.x.x.js
Currently, there is an issue [flow/issues/3009](https://github.com/facebook/flow/issues/3009).
The overload functions (`accepts`, `acceptsCharsets`, `acceptsEncodings`, `acceptsLanguages`) in `Request` type need additional annotations to disambiguate cases.
ex: [in test file L274](https://github.com/flowtype/flow-typed/pull/573/files#diff-ef19f871389577e2759a1decdff9a2c2R274)
```
const typeOrFalse3: string|false = request.accepts((['json', 'text']:Array<string>));
```
Maybe, this will be fixed later.
> Add koa@2.x definition.

- definitions/npm/bluebird-promisell_v0.5.x/flow_v0.29.x-/bluebird-promisell_v0.5.x.js
- definitions/npm/bluebird-promisell_v0.5.x/test_bluebird-promisell_v0.5.x.js
I'm adding type definitions to my library [bluebird-promisell](https://github.com/zhangchiqing/bluebird-promisell).
When I ran `./run_def_tests.sh bluebird-promisell`, I got the following error. How can I resolve the first error, which is saying `bluebird` not found? (My library depends on `bluebird`, so does the tests).
```
* bluebird-promisell_v0.5.x/flow_>=v0.29.x (flow-v0.33.0): Unexpected Flow errors(2):
0-test_bluebird-promisell_v0.5.x.js:3
3: import type { Bluebird$Promise } from 'bluebird';
^^^^^^^^^^ bluebird. Required module not found
0-test_bluebird-promisell_v0.5.x.js:11
11: // $ExpectError
^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
...
Found 14 errors
null
```
Thanks!
> Add type definitions for bluebird-promisell

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
The argument was removed prior to the 5.0.0 release. Users are now expected to compare against `Rx.TimeoutError`.
> RxJS: Add TimeoutError; remove error argument to timeout()

- definitions/npm/bluebird_v3.x.x/flow_v0.32.x-/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/test_bluebird-v3.x.x.js
Bluebird.join() is now not correct, `handler` should not have the same type as inputs for `join`. PR fixes this to correspond the [doc](http://bluebirdjs.com/docs/api/promise.join.html).
> Bluebird: fix join() signature.

- definitions/npm/bluebird_v3.x.x/flow_v0.32.x-/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/test_bluebird-v3.x.x.js
> Bluebird: ensure Bluebird.method accepts heterohenous input.

- definitions/npm/underscore_v1.x.x/flow_v0.13.x-/underscore_v1.x.x.js
- definitions/npm/underscore_v1.x.x/test_underscore-v1.js
This pull request add type definitions for [`_.partial`](http://underscorejs.org/#partial) and [`_.compose`](http://underscorejs.org/#compose).
The type definition for `compose` is very simple and I really don't know how do I describe the fact that the first function's return value is the return value of the function that is returned from `compose`:
```javascript
declare function compose(...functions: Function): Function;
// USAGE:
(
_.compose(
function (name:string):string { return name + ', hello!'; },
function (user:Object):string { return user.name; }
): (user: Object) => string
)
```
I'd be happy to provide a more stricter type definition but I really don't know how to approach that. I'd be happy to read any feedback. Thanks.
> add type definitions for partial and compose

- definitions/npm/bluebird_v3.x.x/flow_v0.32/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/test_bluebird-v3.x.x.js
The Bluebird API effectively provides the same interface as the Native Promise API (despite having a different under-the-hood implementation) with some additional functionality as well. As a result, it can be thought of as a subtype of the Promise type. By declaring Bluebird as a subclass of Native Promise (since the Native Promise is a Class), most existing code which has been constructed to operate with Promise type instances can now also operate with Bluebird type instances without having to be rewritten and made aware of the Bluebird library. The test cases I added to the Bluebird library best illustrate the benefits that come from making this sub-typing relationship.
However, in attempting this, there was an issue with the `Promise.all` declaration from Flow version v0.32 to v0.33. …
> declare Bluebird as subtype of Native Promise, add tests

- definitions/npm/lodash_v4.x.x/flow_v0.28.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/test_lodash-v4.x.x.js
Existing defs for flatMap only works for array, but it actually works for objects too ([lodash docs](https://lodash.com/docs/4.17.4#flatMap))
This pr:
- adds OFlatMapIteratee for flatMapping on objects
- adds appropriate defs for flatMap, flatMapDeep, flatMapDepth on objects
> lodash: defs for flatmap to work on objects

- definitions/npm/jest_v18.x.x/flow_v0.33.x-/jest_v18.x.x.js
Resolves #617.
Nothing major here, simply defining `createSpyObj` which was missing.
> Update Jest Jasmine type declaration

- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
I don't have an isolated test case, but these help Flow determine which option to choose. Without these, it might choose e.g. a one-argument version even though the callsite has three arguments, and it will just ignore the last two arguments, leading to type errors.
The changes to `combineLatest` are necessary to typecheck Nuclide's code with Flow master.
> [rxjs] Add dummy void arguments to overloaded methods

- definitions/npm/shortid_v2.2.x/flow_v0.27.x-/shortid_v2.2.x.js
- definitions/npm/shortid_v2.2.x/test_shortid_v2.2.x.js
This adds typedefs and tests for https://github.com/dylang/shortid, tested down to flow 0.27 not sure if supporting any lower is useful.
> Add shortid v2.2.x  def

- definitions/npm/enzyme_v2.3.x/flow_v0.23.x-v0.27.x/enzyme_v2.3.x.js
- definitions/npm/enzyme_v2.3.x/flow_v0.28.x-/enzyme_v2.3.x.js
Adding missing `exists()` method. 
- https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/exists.md
- https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/exists.md
> enzyme: add exists method

- cli/src/lib/libDefs.js
For all flow-typed commands get error with http request on github:
`• flow-typed cache not found, fetching from GitHub...ERROR: Unable to clone the local cache repo.
UNCAUGHT ERROR: Error: Error cloning repo: undefined`
> http => https for  REMOTE_REPO_URL

- definitions/npm/react-i18next_v2.x.x/flow_v0.36.x-v0.39.x/react-i18next_v2.x.x.js
- definitions/npm/react-i18next_v2.x.x/test_react-i18next_v2.x.x.js
Copied this from v1.10.x. The API didn't change (major version was due to a new major version of the i18next dependency).
> Add react-18next v2.x.x libdef

- cli/src/commands/create-stub.js
- cli/src/commands/install.js
- cli/src/commands/runTests.js
- cli/src/commands/search.js
- cli/src/commands/update-cache.js
- cli/src/commands/validateDefs.js
- cli/src/commands/version.js
- Remove periods to have standard lines (it is usually the case for other CLIs help text I've looked, e.g. git)
- Change the tense to imperative, to match with `yargs` text `"Show help"` and other CLI tools
- Clarify a few cases
Hope it helps, just starting to review the codebase of the project.
> Improve CLI commands texts

- definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.38.x-/lodash_v4.x.x.js
[`_.keyBy`](https://lodash.com/docs/4.17.4#keyBy) returns an object with a finite set of values, which means that sometimes accessing an attribute will result in `undefined` instead of the result you may have expected.
Thanks for this project, it's been fantastic for us so far. Please let me know if there's anything I can do to make this PR better! :)
> Lodash: Fix issue in type of result of _.keyBy

- definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js
- definitions/npm/chai_v3.5.x/test_chai_v3.5.x.js
I noticed that the `chai` types don't support `chai-as-promised` plugin (http://chaijs.com/plugins/chai-as-promised/) which we use.
So I went ahead and just created the declarations for `chai-as-promised` in the `chai` module, the same as was already done for `chai-sinon` and others.
Feel free to comment and request changes
> Support chai-as-promised plugin for chai_v3.5.x

- definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-/react-router-dom_v4.x.x.js
- definitions/npm/react-router_v4.x.x/flow_v0.38.x-/react-router_v4.x.x.js
- definitions/npm/react-router_v4.x.x/test_react-router.js
Return a string to show a prompt to the user or true to allow the transition. [reference](https://reacttraining.com/react-router/#prompt.message-func)
> Allowed react-routerv4 Prompt.message to return true

- cli/src/commands/install.js
This is an attempt to resolve #554.
This would allow you to run e.g. `flow-typed install --overwrite --skipStubs` to update existing libdefs, install new ones, and leave (potentially modified) stubs untouched.
> Add an option to skip stubs when installing

- definitions/npm/react-dnd_v2.x.x/flow_v0.23.x-/react-dnd_v2.x.x.js
- definitions/npm/react-dnd_v2.x.x/test_react-dnd-v2.js
This pull request makes three main improvements to react-dnd's definitions. Each improvement is in its own commit.
The definitions of react-dnd prohibits legal code like this because `monitor` in the callback type is incorrectly typed as optional:
```js
import {DragSource} from 'react-dnd';
const ManageItemDragSource = {
beginDrag(props: Props) {
return {
item: props.item,
index: props.index
};
},
endDrag(props, monitor){
if(!monitor.didDrop()){
props.onSetIndex(monitor.getItem().index, monitor.getItem().item);
}
},
isDragging(props, monitor){
return props.item.guid === monitor.getItem().item.guid;
}
}
export default DragSource(..., ManageItemDragSource, ...);
```
The user of react-dnd has to pass some callback functions into the library. react-dnd calls these callbacks with a bunch of …
> react-dnd definition improvements

- cli/src/lib/stubUtils.js
Avoids upsetting consumer projects' lint tools by default.
> Generates stubs without trailing whitespace

- definitions/npm/underscore_v1.x.x/flow_v0.13.x-v0.37.x/underscore_v1.x.x.js
- definitions/npm/underscore_v1.x.x/flow_v0.38.x-/underscore_v1.x.x.js
- definitions/npm/underscore_v1.x.x/test_underscore-v1.js
Adds in a definition for the underscore `delay` function. Mirrored off of the existing `defer` and `throttle` definitions.
- I attempted to add an $ExpectedError line to the underscore test with the following call:
```
_.delay(() => {}); // No delay specified
```
But I was getting an 'Unused suppression error. Not certain what I was doing wrong there.
- I would prefer to not use the `Array<any>` function here, and figure out a way to match the arguments to the function passed in, but that requires a little more thought.
> Add definition for undescore.js delay

- definitions/npm/moment_v2.x.x/flow_v0.34.x-/moment_v2.x.x.js
- definitions/npm/moment_v2.x.x/test_moment-v2.js
This PR introduces proper typing for `moment().calendar` changes introduced in moment v2.14.0 ([see note here](http://momentjs.com/docs/#/displaying/calendar-time/).
This also bumps flow minimum version to 0.34 (which is now 6 months old) to support function signature typing.
> Add proper typings for moment().calendar (moment >= v2.14.x)

- definitions/npm/out_v1.x.x/flow_v0.28.x-/out_v1.x.x.js
- definitions/npm/out_v1.x.x/test_out_v1.x.x.js
This is far from being the world's most popular package (see: https://github.com/DamonOehlman/out) , but I've used it a lot of my projects for writing `stderr` output (default setting).  I'm currently converting a couple of older projects to use flow annotations so would would be grateful if this was available in the definition repo.
> package definition for the npm out package

- README.md
I seemed that there was no way to [specify the package](https://github.com/kjirou/flow-typed/blob/master/cli/src/commands/install.js#L128-L144) in the document, so I added it.
> Add documentation about `flow install`

- definitions/npm/react-css-modules_v3.x.x/flow_v0.42.x-/react-css-modules_v3.x.x.js
- definitions/npm/react-css-modules_v3.x.x/test_react-css-modules-v3.js
Adds a definition for [React CSS Modules](https://github.com/gajus/react-css-modules) v3.x.x. Almost certainly works with v4.x.x as well-- Will test in a subsequent commit later next week.
> react-css-modules: Add initial definitions

- definitions/npm/js-beautify_v1.6.x/flow_v0.25.x-/js-beautify_v1.6.x.js
- definitions/npm/js-beautify_v1.6.x/test_js-beautify_v1.6.x.js
https://github.com/beautify-web/js-beautify
I only set the range to 1.6.x for now as I didn't want to go through the changelog and see how the options changed in the different versions, although it seems they also consider adding new options as bugfix versions (1.6.10/1.6.11).
> Add definitions for js-beautify 1.6

- definitions/npm/lodash_v4.x.x/flow_v0.38.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.38.x-/test_lodash-v4.x.x.js
There are two changes in this commit:
1. Updated iteratees for a number of functions to accept only the collection value as a parameter, matching the lodash docs.
These include:
* differenceBy
* pullAllBy
* sortedIndexBy
* sortedLastIndexBy
* unionBy
* uniqBy
* xorBy
* countBy
* groupBy
* keyBy
2. Update the return values of groupBy and keyBy to be typed objects with the same value type as the input collection’s type.
NOTE: To make the second change, I needed to add parameters to the `groupBy` and `keyBy` types. I'm not completely sure I did this correctly, but I followed existing patterns and added some tests that should exercise this. Please review this area in particular.
cc @marudor
> Update typings for lodash v4

- definitions/npm/bluebird_v3.x.x/flow_v0.32.x-v0.32.x/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/test_bluebird-v3.x.x.js
Also for Bluebird.mapSeries().
As per http://bluebirdjs.com/docs/api/promise.map.html: "Promises returned by the mapper function are awaited for and the returned promise doesn't fulfill until all mapped promises have fulfilled as well."
> Allow Bluebird.map() mapper function to return U or Promise<U>.

- definitions/npm/moment_v2.x.x/flow_v0.34.x-/moment_v2.x.x.js
- definitions/npm/moment_v2.x.x/test_moment-v2.js
Fixes `utcOffset()` typedef for moment_v2.x.x.js.  This was already started in #519, but this adds the correct definition and a test case for it.
> Fix moment_v2.x.x.js typedef for utcOffset()

- definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js
Without this change I get a type error complaining about Array<object> vs Array<mixed> similar to described @ https://github.com/facebook/flow/issues/1644
> parameterize array include/notInclude

- definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-/react-router-dom_v4.x.x.js
- definitions/npm/react-router-dom_v4.x.x/test_react-router-dom.js
c&p `matchPath` from `react-router`, it was missing from the [original PR](https://github.com/flowtype/flow-typed/pull/638).
> Add matchPath to react-router-dom

- definitions/npm/yargs_v7.x.x/flow_v0.42.x-/yargs_v7.x.x.js
- definitions/npm/yargs_v7.x.x/test_yargs.js
Adding new libdefs for [yargs 7](https://github.com/yargs/yargs). Builds on the libdefs for 4 and 5, and adds a much better test.
> Libdefs for yargs 7

- definitions/npm/yargs_v7.x.x/flow_v0.42.x-/yargs_v7.x.x.js
- definitions/npm/yargs_v7.x.x/test_yargs.js
Added missing `coerce` to yargs `options` object, including a test (http://yargs.js.org/docs/#methods-optionskey-opt)
> Add missing coerce to yargs

- definitions/npm/knex_v0.12.x/flow_v0.33.x-/knex_v0.12.x.js
Exports the $QueryBuilder type. I found it useful to pass around partially constructed queries. Not sure if this is the right way to do this.
> Knex: Export query builder type

- definitions/npm/pg_v6.x.x/flow_v0.32.x-/pg_v6.x.x.js
According to pg's implementation, application_name and fallback_application_name aren't actually required, they will provide a default to be used if nothing is passed in. The person who wrote the pg definition even put a comment in the definition file stating as much. Because of this, I've changed the types of those 2 keys to string|void instead of string.
https://github.com/brianc/node-postgres/blob/83a946f61cb9e74c7f499e44d03a268c399bd623/lib/connection-parameters.js#L63
> Updating pg's ClientConfig type to follow specs

- definitions/npm/lodash_v4.x.x/flow_v0.38.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.38.x-/test_lodash-v4.x.x.js
As per [the lodash docs](https://lodash.com/docs/4.17.4#find): `_.find ... Returns the matched element, else undefined.`
The type signature of the declaration didn't match that, causing potential `undefined` errors to be ignored. Same applies for the lesser-known `findLast`.
If this is merged, I guess a lot of people's code will have new errors once they get the updated libdefs. But correctness is obviously more important.
> _.find may return void

- definitions/npm/eventemitter3_v2.x.x/flow_v0.38.x-/eventemitter3_v2.x.x.js
- definitions/npm/eventemitter3_v2.x.x/test_eventemitter3-v2.js
https://github.com/primus/eventemitter3
The definitions are essentially the same as the [TypeScript definitions](https://github.com/primus/eventemitter3/blob/master/index.d.ts)
> eventemitter3_v2.x.x: Add flow definitions

- definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js
- definitions/npm/chai_v3.5.x/test_chai_v3.5.x.js
This adds the missing definitions for the chai plugin [`chai-subset`](https://www.npmjs.com/package/chai-subset). It only adds a single `containSubset()` assertion.
Note: ESLint warned about the weak type `Object` I used
However, it was used in the definitions thoroughly anyway and I believe it to be correct (**any** instance of `Object` can be put into `containSubset()`)
> Add type definitions for `chai-subset`

- definitions/npm/underscore_v1.x.x/flow_v0.38.x-/test_underscore.js
- definitions/npm/underscore_v1.x.x/flow_v0.38.x-/underscore_v1.x.x.js
Adds type signature, and associated tests for the `identity` function in underscore.js.
Let me know if there's a better way to structure my test!
> Add type definition for `_.identity`

- definitions/npm/reselect_v3.x.x/flow_v0.37.x-/reselect_v3.x.x.js
- definitions/npm/reselect_v3.x.x/test_reselect_3.x.x.js
This resolves #740 by adding support for Reselect v3. As I mentioned in that issue, the only major change here has to do with a change to internal behaviour, so all the old types still work. I slightly reformatted the Reselect v2 typings and have been using them on my own projects for a week or so without issue.
> Added support for Reselect v3.x.x

- definitions/npm/enzyme_v2.3.x/flow_v0.23.x-v0.27.x/enzyme_v2.3.x.js
- definitions/npm/enzyme_v2.3.x/flow_v0.28.x-/enzyme_v2.3.x.js
https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/getNode.md
https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/getNodes.md
I'm not sure if I should use `getNodes(): Array<React$Element<any>>;` instead of `getNodes(): NodeOrNodes;`
> Missing getNode() and getNodes() definitions

- definitions/npm/leven_v2.x.x/flow_v0.25.x-/leven_v2.x.x.js
- definitions/npm/leven_v2.x.x/flow_v0.25.x-/test_leven-v2.x.x.js
leven is a module that exports a function that takes two strings and returns a number representing how different the strings are (lower numbers are more similar strings).
It is very useful for suggesting corrections in error messages.
> Add leven type definition

- definitions/npm/deep-freeze_v0.0.1/flow_v0.25.x-/deep-freeze_v0.0.1.js
- definitions/npm/deep-freeze_v0.0.1/flow_v0.25.x-/test_deep-freeze-v0.0.1.js
Deep freeze recursively freezes all properties of an object/items in an array.  It does nothing to any other types.  It also returns the value you pass into it.
> Add deep-freeze type definition

- cli/src/commands/install.js
I tried to install libdef for axios library (0.15.3) but flow-typed could find anything to install despite existing definition in repositiory (0.15.x). My flow version (0.40.0) also matches. So I started to inspect the code and saw that the name of the package is passed as "undefinedaxios" into search library. I tried to find the source of the bug and here is it.
> fixed bug with invalid npm scope in install script

- definitions/npm/express_v4.x.x/flow_v0.25.x-v0.27.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.28.x-v0.31.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
See http://expressjs.com/en/4x/api.html#app.get
> You can provide multiple callback functions that behave just like middleware, except that these callbacks can invoke next('route') to bypass the remaining route callback(s). You can use this mechanism to impose pre-conditions on a route, then pass control to subsequent routes if there is no reason to proceed with the current route.
> accept 'route' as express$NextFunction argument

- CONTRIBUTING.md
``>=`` wasn't working when writing a test, so I figured I'd update the CONTRIBUTING docs to be consistent with the README docs.
> Updating CONTRIBUTING.md to correct versioning information

- definitions/npm/backbone_v1.x.x/flow_v0.25.x-/backbone_v1.x.x.js
Events: once, listenToOnce
Model: save, destroy, validate, parse
Collection: comparator
Removed duplicate `unshift` under Collection
Reordered Model to match order in docs
> Add missing Backbone definitions

- definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-/react-router-dom_v4.x.x.js
- definitions/npm/react-router-dom_v4.x.x/test_react-router-dom.js
matchPath signature now matches react-router-dom 4.1.1
see [here](https://github.com/ReactTraining/react-router/blob/dc2149ec0c63bfc95b71e40c81431e34cfbfeda9/packages/react-router-dom/modules/matchPath.js#L1) and [here](https://github.com/ReactTraining/react-router/blob/dc2149ec0c63bfc95b71e40c81431e34cfbfeda9/packages/react-router/modules/matchPath.js#L29).
> correct signature of react-router-dom matchPath function

- definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-/react-router-dom_v4.x.x.js
ContextRouter should be an object containing `{ history: RouterHistory, location: Location, match: Match }`, not `RouterHistory & { match: Match }`
> Fix type ContextRouter

- cli/src/commands/__tests__/install-test.js
- cli/src/commands/install.js
When `--skip` is passed, untyped dependencies won't be stubbed. This
adds back the functionality from #686 that was lost.
> install.js: add option to skip stub generation

- definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
I know we want to avoid the any type when possible.  However using the mixed type consistently throws errors when attempting to pull values out of req.body.
> change req.body to any

- definitions/npm/mysql_v2.x.x/flow_v0.44.x/mysql_v2.x.x.js
- definitions/npm/mysql_v2.x.x/test_mysql_v2.x.x.js
First approach - specs are done mostly for public, documented interfaces.
Many of the internal types, like `PoolNamespace` and various protocol
packets classes are not exposed for now, since they are not often used and
not even documented.
> node-mysql libdef

- definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js
- definitions/npm/jest_v20.x.x/test_jest-v20.x.x.js
Comparing to the Jest v19 it adds "resolves" and "rejects" modifiers as well as "hasAssertions".
See: https://facebook.github.io/jest/blog/2017/05/06/jest-20-delightful-testing-multi-project-runner.html
> Add definition for Jest v20

- definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-/react-router-dom_v4.x.x.js
- definitions/npm/react-router_v4.x.x/flow_v0.38.x-/react-router_v4.x.x.js
- definitions/npm/react-router_v4.x.x/test_react-router.js
React-router v4 will inject specific props in components. My understanding of these definitions is that these props were defined as `ContextRouter`.
The definition of `ContextRouter` wasn't correct. This PR replaces `ContextRouter` with a definition that follows [React-router docs](https://reacttraining.com/react-router/web/api/Route/Route-props).
Rel: #341
> Correct react-router ContextRouter definition

- definitions/npm/lodash_v4.x.x/flow_v0.38.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.38.x-/test_lodash-v4.x.x.js
This changes the type of `_.noop` from `() => void` to `(...args: Array<mixed>) => void`.
This allows us to pass arguments to `_.noop`, which is useful for default values in handlers. For example:
```
type Handler = (SyntheticEvent) => void;
(_.noop: Handler);
```
I added tests:
- It should take arguments
- It should take many arguments of varying types
- It should be able to be cast to any function that returns void
- It should fail when casting to a function that returns non-void
> [lodash] Update _.noop type

- definitions/npm/body-parser_v1.x.x/flow_v0.30.x-/body-parser_v1.x.x.js
- definitions/npm/body-parser_v1.x.x/flow_v0.30.x-/test_body-parser.js
I tried to add express to the test:
```flow
import express from 'express'
import { json } from 'body-parser';
const app = express()
app.use(json())
```
but the test throws "express. Required module not found".
Is there any way to do this?
> Add body-parser

- definitions/npm/radium_v0.19.x/flow_v0.30.x-/radium_v0.19.x.js
- definitions/npm/radium_v0.19.x/test_radium-v0.19.x.js
Added Radium 0.19.x definitions, including prop checking.
Test cases were based off the radium_v0.17.x tests as well as react-redux_v5.x.x
Addresses #445 if we copy these definitions for 0.18.x, or rename the definitions to 0.x.x
> Definitions for Radium 0.19.x

- definitions/npm/styled-components_v1.4.x/flow_v0.25.x-/styled-components_v1.4.x.js
- definitions/npm/styled-components_v1.4.x/test_styled-components_v1.4.x.js
The original type definition omitted support for the React Native version of styled-components. This adds support for that module.
Fixes https://github.com/styled-components/styled-components/issues/708
> Add support for styled-components/native

- definitions/npm/express-subdomain_v1.x.x/flow_v0.25.x-/express-subdomain_v1.x.x.js
- definitions/npm/express-subdomain_v1.x.x/test_express-subdomain_v1.x.x.js
I wanted to import middleware types from the "express" module definition, but I couldn't figure it out after reading up here: https://github.com/flowtype/flow-typed/issues/16
@jeffmo 
It originally looked like this, but couldn't figure out why it wasn't working...
```js
import type {
$npm$express$Response,
$npm$express$Request,
$npm$express$NextFunction,
} from 'express'
declare module 'express-subdomain' {
declare type Request = $npm$express$Request
declare type Response = $npm$express$Response
declare type NextFunction = $npm$express$NextFunction
declare type Middleware = (
req: Request,
res: Response,
next: NextFunction,
) => mixed
declare module.exports: (subdomain: string, middleware: Middleware) => Middleware
}
```
```js
// @flow
import subdomain from 'express-subdomain'
import type …
```
> Adding support for express-subdomain

- definitions/npm/react-addons-perf_v15.x.x/flow_v0.23.x-/react-addons-perf_v15.x.x.js
- definitions/npm/react-addons-perf_v15.x.x/test_react-addons-perf.js
First ever commit to here so I expect to have probably missed a step.
I first configured `flow_all`, and then just bumped the `flow-v0.x` version until it didn’t fail anymore.
```
./run_def_tests.sh react-addons-perf
```
> react-addons-perf

- definitions/npm/jest_v19.x.x/flow_v0.33.x-/jest_v19.x.x.js
- definitions/npm/jest_v19.x.x/test_jest-v19.x.x.js
Add types for `toHaveBeenLastCalledWith` method in `Jest's` expect.
https://jest-bot.github.io/jest/docs/expect.html#tohavebeenlastcalledwitharg1-arg2-
> Jest. Add expect().toHaveBeenLastCalledWith

- definitions/npm/parse_v1.9.x/flow_v0.37.x-/parse_v1.9.x.js
* As per [docs](https://github.com/ParsePlatform/Parse-SDK-JS#using-parse-on-different-platforms), no longer import `parse/browser`
* Add definition for Cloud code callback
> Change module parse/browser to parse

- definitions/npm/radium_v0.19.x/flow_v0.30.x-/radium_v0.19.x.js
Hi, the Radium objects Style and StyleRoot were incorrectly labelled as React$Element instead of React Components
This is a PR to fix that issue
> Radium 0.19 – Fixed Style and StyleRoot being incorrectly labelled as React$Element

- definitions/npm/chalk_v1.x.x/flow_v0.21.x-/chalk_v1.x.x.js
Chalk colour methods [coerce all arguments to string](https://github.com/chalk/chalk/blob/9b60021fa605a6ebf62fbfd42d02c45597b10e6e/index.js#L65-L70), so the libdef should accept `any`.
> Allow non-string arguments in chalk libdef

- definitions/npm/slug_v0.9.x/flow_v0.28.x-/slug_v0.9.x.js
- definitions/npm/slug_v0.9.x/test_slug_v0.9.x.js
All the keys of the option don't have to be set, we can for instance see in the package's tests such an example: `slug("foo bar baz", {charmap})`.
> Update node-slug options configuration

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.33.x/rxjs_v5.0.x.js
These were only in the 0.34 defs, though they don't seem to include any version-specific syntax.
> RxJS: Backport changes only made to the 0.34 def

- definitions/npm/redux-mock-store_v1.2.x/flow_v0.34.x-/redux-mock-store_v1.2.x.js
Fixes #842 as the previous amendment didn't fix it the way I was expecting.
> Fix getActions() method in redux-mock-store libdef

- definitions/npm/jest_v18.x.x/flow_v0.33.x-/jest_v18.x.x.js
- definitions/npm/jest_v19.x.x/flow_v0.33.x-/jest_v19.x.x.js
- definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js
With added function arity check in 0.46+ we need to set type of the third argument of jest.mock function explicitly.
> Fix jest on flow 0.46+

- definitions/npm/expect_v1.x.x/flow_v0.43.x-/expect_v1.x.x.js
Updating libdefs broke some tests of mine which were passing an Array to `toMatch`.
This assertion uses [tmatch](https://github.com/tapjs/tmatch), which accepts just about everything.
> Update expect's toMatch assertion to accept any pattern

- definitions/npm/jasmine_v2.4.x/flow_all/jasmine_v2.4.x.js
- definitions/npm/jest_v14.x.x/flow_v0.23.x-/jest_v14.x.x.js
- definitions/npm/jest_v16.x.x/flow_v0.33.x-/jest_v16.x.x.js
- definitions/npm/jest_v17.x.x/flow_v0.33.x-/jest_v17.x.x.js
- definitions/npm/jest_v18.x.x/flow_v0.33.x-/jest_v18.x.x.js
- definitions/npm/jest_v19.x.x/flow_v0.33.x-/jest_v19.x.x.js
- definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js
- definitions/npm/react-scripts_v0.7.x/flow_v0.33.x-/react-scripts_v0.7.x.js
Jasmine clock `tick()` takes the number of milliseconds to tick
https://github.com/jasmine/jasmine/blob/9cb2f06aa665870dbd5df5fd58a35863738961b3/src/core/Clock.js#L117
> include milliseconds argument of Jasmine tick()

- definitions/npm/swagger-schema-official_v2.x.x/flow_v0.34.x-/swagger-schema-official_v2.x.x.js
- definitions/npm/swagger-schema-official_v2.x.x/test_swagger-schema-official_v2.x.x.js
Added libdef for [swagger-schema-official](https://www.npmjs.com/package/swagger-schema-official) [v2](http://swagger.io/specification)
A kind of porting of [DefinitelyTyped/swagger-schema-official](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/swagger-schema-official)
> libdef for swagger-schema-official v2

- definitions/npm/moment_v2.x.x/flow_v0.34.x-/moment_v2.x.x.js
As per this documentation: https://momentjs.com/docs/#/parsing/ moment() 2.3.0 now supports additional parameters in its main initialize function. This PR adds support for them.
> Update main moment() function for new arguments

- definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js
Add missing `.calledTwice()` and `.calledThrice()` definitions for `sinon-chai`.
> Add `calledTwice` and `calledThrice` definitions for `sinon-chai`

- definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js
- definitions/npm/jest_v20.x.x/test_jest-v20.x.x.js
Jest v20 made `.toThrow` and `.toThrowError` aliases.
See jest documentation : https://facebook.github.io/jest/docs/expect.html#tothrowerror
> Fix jest v20 toThrow / toThrowError

- definitions/npm/koa_v2.x.x/flow_v0.47.x-/koa_v2.x.x.js
Since it isn't required. See [docs](http://koajs.com/#ctx-cookies-get-name-options-).
> [koa] Made second argument in cookies.get optional

- definitions/npm/bluebird_v3.x.x/flow_v0.32.x-v0.32.x/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/test_bluebird-v3.x.x.js
This PR adds initial support for Bluebird disposer and using. See http://bluebirdjs.com/docs/api/promise.using.html and http://bluebirdjs.com/docs/api/disposer.html. This PR does not support multiple disposables being passed to `using` or Promises. However, this is enough for basic usage.
> Add support for bluebird disposer and using.

- definitions/npm/bunyan_v1.x.x/flow_v0.21.x-/bunyan_v1.x.x.js
This fixes two minor things:
- options passed to the child function are optional, as seen [here](https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L689)
- a type is also considered writable if it has a function property 'write', as seen [here](https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L312)
> Bunyan: make child options optional and add writable function

- definitions/npm/bluebird_v3.x.x/flow_v0.32.x-v0.32.x/bluebird_v3.x.x.js
- definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js
This PR reverts bluebird to a commonjs module (it was changed as part of #901). This allows bluebird to still be used using `require`. Note that this will also solve #907.
> Revert bluebird to a commonjs module.

- definitions/npm/lodash_v4.x.x/flow_v0.47.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.47.x-/test_lodash-v4.x.x.js
Currently it is only possible to pass a map of objects to `keyBy`  where each object's key is a string:
`T: {[id: string]: A}`
I think we should be able to send in maps of objects that are mapped by other types though:
`T: {[id: number]: A}` should be a valid input? See: https://flow.org/en/docs/types/objects/#toc-objects-as-maps.
> keyBy accepts object map of any type

- definitions/npm/knex_v0.12.x/flow_v0.38.x-/knex_v0.12.x.js
- definitions/npm/knex_v0.12.x/test_knex-v0.12.js
Knex *raw methods can be passed parameter bindings as a second argument.
Documentation about this feature : http://knexjs.org/#Raw-Bindings
This PR introduces a `Knex$RawBindings` type to cover those cases.
Tests also attached.
> Fix knex *raw methods for flow v0.47.0

- definitions/npm/backbone_v1.x.x/flow_v0.25.x-/backbone_v1.x.x.js
History: 
- navigate
- loadUrl
- route
- decodeFragment
- getFragment
- fragment
> add missing Backbone.history methods and properties

- definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/lodash_v4.x.x.js
Noticed while running `prettier` through our typedefs that this definition produced an error:
```
flow-typed/npm/lodash_v4.x.x.js
flow-typed/npm/lodash_v4.x.x.js: SyntaxError: default is a reserved word (466:55)
464 |     conforms(source: Object): Function;
465 |     constant<T>(value: T): () => T;
> 466 |     defaultTo<T1:string|boolean|Object,T2>(value: T1, default: T2): T1;
|                                                       ^
467 |     // NaN is a number instead of its own type, otherwise it would behave like null/void
468 |     defaultTo<T1:number,T2>(value: T1, default: T2): T1|T2;
469 |     defaultTo<T1:void|null,T2>(value: T1, default: T2): T2;
```
> switch from using the reserved word default

- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
Hi there!
With the advent of Flow 0.47.0's arity-based checking, it's more important than ever to account for optional arguments. It would also be useful to type out some of rxjs's testing suite.
> Update rxjs.Observable/sampleTime with optional scheduler argument, and add the TestScheduler to typed exports

- definitions/npm/morgan_v1.x.x/flow_v0.30.x-/morgan_v1.x.x.js
- definitions/npm/morgan_v1.x.x/test_morgan.js
I tried to add express into the test:
```js
import type { $Request, $Response } from 'express';
```
but the test throws "express. Required module not found".
Is there any way to do this?
> Add morgan definition

- definitions/npm/react-jss_v6.1.x/flow_v0.30.x-/react-jss_v6.1.x.js
- definitions/npm/react-jss_v6.1.x/test_react-jss_v6.1.x.js
Add typedefs for `react-jss`. This implementation covers the most "useful" parts of the API. 
I would ask @kof to review if the typedefs are correct from the library author perspective.
> add react-jss_v6.1.x type declaration

- definitions/npm/styled-components_v2.x.x/flow_v0.25.x-/styled-components_v2.x.x.js
- definitions/npm/styled-components_v2.x.x/test_styled-components_v2.x.x.js
expects Reactclass | stateless not React$Component (<ReactComponent />)
> fix definition for styled-components

- definitions/npm/firebase_v4.x.x/flow_v0.46.x-/firebase_v4.x.x.js
I think the FirebaseValue type makes it hard to work with the firebase API with flow. I looked at how typescript has their firebase value and its type any. See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/firebase/index.d.ts#L20
Also I don't think projectId is used in firebase anymore. In the docs the projectId isn't mentioned 
in https://firebase.google.com/docs/web/setup
> Update FirebaseValue type

- definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
retry function can have no paramaeters. See https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/retry.md
> Fix RxJS retry parameter type

- definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js
Hi,
after quite some searching I couldn’t find a "proper" way to extend the already declared jest `expect` definition. 
If I refer to facebook/flow/issues/396, and especially [how it's done for other frameworks, plugins](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js#L75-L106) this is somehow acceptable for now?
Looking for directions. Thanks.
> Add jest-enzyme plugin to jest definition

- definitions/npm/firebase_v4.x.x/flow_v0.34.x-v0.45.x/firebase_v4.x.x.js
- definitions/npm/firebase_v4.x.x/flow_v0.34.x-v0.45.x/test_firebase.js
- definitions/npm/firebase_v4.x.x/flow_v0.46.x-/firebase_v4.x.x.js
- definitions/npm/firebase_v4.x.x/flow_v0.46.x-/test_firebase.js
Breaking change:
- User is renamed to FirebaseUser
- UserCredential is renamed to FirebaseUserCredential
- AdditionalUserInfo is renamed to FirebaseAdditionalUserIno
- UserInfo is renamed to FirebaseUserInfo
Changes made:
- Formatted using Prettier
- projectId & databaseURL of FirebaseConfig is now optional
- Refactor class Query (extracted #FirebaseDatabaseCallback)
- Reference#push() returns a Promise or ThenableReference
> Rename FirebaseUser and various fixes for Firebase v4

- definitions/npm/styled-components_v1.4.x/flow_v0.25.x-/styled-components_v1.4.x.js
- definitions/npm/styled-components_v1.4.x/test_styled-components_v1.4.x.js
- definitions/npm/styled-components_v2.x.x/flow_v0.25.x-/styled-components_v2.x.x.js
- definitions/npm/styled-components_v2.x.x/test_styled-components_v2.x.x.js
Without this change you get:
```
* styled-components_v1.4.x/flow_v0.25.x- (flow-v0.48.0): Unexpected Flow errors(2):
0-test_styled-components_v1.4.x.js:40
40:   <ThemeProvider theme={outerTheme => outerTheme}>
^^^^^^^^^^^^^^^^^^^^^^^^ function. Could not decide which case to select
14:   theme: ((outerTheme: $npm$styledComponents$Theme) => void) | $npm$styledComponents$Theme
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union type. See lib: styled-components_v1.4.x.js:14
Case 1 may work:
14:   theme: ((outerTheme: $npm$styledComponents$Theme) => void) | $npm$styledComponents$Theme
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: styled-components_v1.4.x.js:14
But if it doesn't, case 2 looks promising too:
14:   theme: …
```
> Fix for styled-components case select

- definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-/react-router-dom_v4.x.x.js
- definitions/npm/react-router_v4.x.x/flow_v0.38.x-/react-router_v4.x.x.js
Currently react-router’s `Match` type uses `Object` for its `params` attribute. `params` is [explained in the docs](https://reacttraining.com/react-router/web/api/match) as
> params - (object) Key/value pairs parsed from the URL corresponding to the dynamic segments of the path
It seems to me that, since we’re talking about substrings of the url, the type of the values of any params key will always be `string` if that param exists. Does anyone see a reason not to type `Match` like this instead?
```
declare export type Match = {
params: { [key: string]: ?string },
isExact: boolean,
path: string,
url: string,
}
```
> react-router: type the values of Match.params as ?string

- definitions/npm/react-intl_v2.x.x/flow_v0.48.x-/react-intl_v2.x.x.js
- definitions/npm/react-intl_v2.x.x/test_react-intl_v2.x.x.js
- Make defaultMessage required.
- Improve defineMessages to detect wrong message name.
- Prettier ftw.
> Improve react-intl

- definitions/npm/flyd_v0.x.x/flow_v0.34.x-/flyd_v0.x.x.js
I goofed with the initial definition (#951) - this sub-module has two exports and
no default.
> Adjust flyd module `dropRepeats`

- definitions/npm/ramda_v0.x.x/flow_v0.34.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.34.x-/test_ramda_v0.x.x_misc.js
- definitions/npm/ramda_v0.x.x/flow_v0.34.x-/test_ramda_v0.x.x_object.js
Makes `isNil` understandable to flow, `either` reflects reality a bit
better (simple ||, not a boolean cast), and `path` is now more robust and
provides better guarantees on a return value.
> Improve Typing for Ramda Utils (path/either/isNil)

- definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js
- definitions/npm/jest_v20.x.x/test_jest-v20.x.x.js
Jest's `toMatch` matcher is able [to match on regexp or string](https://facebook.github.io/jest/docs/expect.html#tomatchregexporstring). This change updates the Jest definitions to support this, and adds a couple of tests to enforce it.
> Jest toMatch can match on string

- definitions/npm/socket.io_v1.x.x/flow_v0.47.x-/socket.io_v1.x.x.js
- definitions/npm/socket.io_v1.x.x/flow_v0.47.x-/test_socket.io_v1.x.x.js
Addresses #973 
Adds definitions for socket.io server API. Definitions for the client are coming... *soon*.
Note: These were generated from the typescript definitions for socket.io, with `flowgen`. Is there something to be added to the files, or the commit, to make a note of it?
> Add socket.io server definitions

- definitions/npm/enzyme_v2.3.x/flow_v0.23.x-v0.27.x/enzyme_v2.3.x.js
- definitions/npm/enzyme_v2.3.x/flow_v0.28.x-/enzyme_v2.3.x.js
According to [this](http://airbnb.io/enzyme/docs/api/ReactWrapper/not.html) (also true for [ShallowWrapper](http://airbnb.io/enzyme/docs/api/ShallowWrapper/not.html)), not should return `this` instead of something of boolean type. I've made the changes in both the newer and older versions of flow.
> [enzyme_2.3.x] Not function returns reference to self instead of boolean

- definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js
- definitions/npm/chai_v3.5.x/test_chai_v3.5.x.js
- definitions/npm/chai_v4.x.x/flow_v0.48.0-/chai_v4.x.x.js
- definitions/npm/chai_v4.x.x/test_chai_v4.x.x.js
It is possible to call `.throw` without any error http://chaijs.com/api/bdd/#method_throw
> Setting error as optional for the chai `throw` function

- cli/src/commands/__tests__/install-test.js
- cli/src/commands/install.js
Addressed #676 
Stops situations where installing a (newly available) libdef will keep the stub around, causing the new definition to be ignored. It does so by removing the stub if the `--overwrite` flag is passed to `install`, or if `update` is used.
> Install with --overwrite removes stub if typedef becomes available

- definitions/npm/react-dnd_v2.x.x/flow_v0.23.x-/react-dnd_v2.x.x.js
Exports the `Connect*` (e.g. `ConnectDropTarget`) function types so they can be properly typed as props injected to a React component. Example usage:
```js
class SortableItem extends PureComponent {
props: {
/* ... other props... */
connectDragSource: ConnectDragSource<*>,
connectDragPreview: ConnectDragPreview<*>,
connectDropTarget: ConnectDropTarget<*>,
}
```
> Export connector function types.

- definitions/npm/styled-components_v2.x.x/flow_v0.25.x-/styled-components_v2.x.x.js
I was receiving a warning when using the `withTheme` HOC that read, "Expected React component instead of React$Component." So I just replaced React$Component with ReactClass and everything worked ✨
The caveat of this change is that we're no longer providing the prop types provided by the theme. I couldn't find a way around this, so hopefully someone else can.
> Suppress error with `withTheme` of styled-components

- cli/src/commands/__tests__/install-test.js
- cli/src/commands/install.js
Addresses #999 
Adds a flag for `flow-typed install` called `packageDir`, which allows the user to specify the location of the `package.json` that contains an installation of `flow-bin`.
Use: `flow-typed install --packageDir '../../parent_project/`
> Specify flowbin package.json directory on install

- definitions/npm/flyd_v0.x.x/flow_v0.34.x-/flyd_v0.x.x.js
The point of `scanMerge` is to combine multiple streams via a `[Stream,
ScanFn]` tuple set.  This def was just wrong.  Again, that's on me. 😄
> Fix Flyd `scanMerge` module def

- definitions/npm/reselect_v2.x.x/flow_v0.37.x-/reselect_v2.x.x.js
- definitions/npm/reselect_v3.x.x/flow_v0.37.x-/reselect_v3.x.x.js
Realized I made this mistake in my change yesterday, doesn't seem to affect anything (works fine both ways locally and passes all tests) but it looks inconsistent.
> Fixed mistake in T16 struct in reselect defs that used , instead of ;

- definitions/npm/react-intl_v2.x.x/flow_v0.48.x-/react-intl_v2.x.x.js
According to the docs and source code of the react-intl project, the `defaultMessage` in the `messageDescriptorPropTypes` is not required and therefore optional.
https://github.com/yahoo/react-intl/blob/master/src/types.js#L42-L46
> Set defaultMessages to optional in react-intl typedefs

- definitions/npm/underscore_v1.x.x/flow_v0.38.x-/test_underscore.js
- definitions/npm/underscore_v1.x.x/flow_v0.38.x-/underscore_v1.x.x.js
The `findKey` annotation used to afford no arguments to its predicate. Now it does.
Included a valid test that used to fail, but now passes.
Thanks to @lewisf.
> Entered arguments for the predicate of findKey

- README.md
After reading [#438](https://github.com/flowtype/flow-typed/issues/438), it feels like to README does a great job of explaining the project, but a poor job of teaching people how to use `flow-typed` once they've installed it. This PR hopes to address those issues, and links to the New & Improved™ [Wiki](https://github.com/flowtype/flow-typed/wiki).
An entry on Getting Started was added, which links to the wiki page for it.
_How Do I Contribute Library Definitions?_ was moved to the wiki. A link to CONTRIBUTING.md was added in the README, since it outlines good practices and steps for contributing libdefs.
The FAQ was moved into the wiki, taking _Why do I need to commit the libdefs that `flow-typed` installs for my project?_ with it.
> Overhaul of the README to use new wiki pages

- definitions/npm/koa_v2.x.x/flow_v0.47.x-/koa_v2.x.x.js
`any` type can be cast to any strict type, therefore allowing covariant customization of Context. Useful when writing custom middleware.
With this change developer can customize Context as per below:
```
type CustomContext = Context & {
reqId: string
};
app.use(requestId);
app.use(logRequests);
async function logRequests(ctx: CustomContext, next: *) {
log('got request', ctx.reqId, ctx.request.url);
await next();
}
```
When type is mixed it will conflict with the above customization.
> koa_v2.x.x.js: make Context middleware params customizable

- cli/src/commands/__tests__/install-test.js
- cli/src/commands/install.js
- cli/src/lib/npm/npmProjectUtils.js
- cli/src/lib/stubUtils.js
Fixes #379 
Fixes #453 
Fixes #528 
Fixes #599
This has been requested so many time, I think it's about time we address it.
Pass the `--ignoreDeps` flag with a list of dependency categories to ignore to `flow-typed install`. Permitted values are `dev`, `bundle`, `peer` and `optional`. For instance, running what's below will only install regular and `optional` dependencies:
```
flow-typed install --ignoreDeps dev bundle peer
```
Still didn't want to mess with the `.flowconfig` file, though seeing as this is the 4th flag I've created, it may be time to talk about integrating with the config file.
> Ability to Ignore Categories of Dependencies when Installing TypeDefs

- definitions/npm/next_v2.x.x/flow_v0.37.x-/next_v2.x.x.js
Note: this is the same URLObject as the [`format` call in node accepts](https://github.com/facebook/flow/blob/68dd89ecdf1ddcdca7fe04ca24ad7c0731e4c7e7/lib/node.js#L1450).
> next links can take a URLObject

- definitions/npm/express_v4.x.x/flow_v0.25.x-v0.27.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.28.x-v0.31.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
- definitions/npm/express_v4.x.x/test_express_v4.x.x.js
After checking the API documentation for the Express library, I updated the return type for the .enable() method on express$Application to allow chaining without error.
> Update express$Application.enable() return type

- definitions/npm/prismic.io_v3.x.x/flow_v0.25.x-/prismic.io_v3.x.x.js
- definitions/npm/prismic.io_v3.x.x/test_prismic.io_v3.x.x.js
Certain predicates support more than just strings. [Docs](https://prismic.io/docs/rest-api/query-the-api/predicates-reference#15_0-predicate-reference-in-the-rest-api).
> Add number support to Prismic query predicates

- .travis.yml
Closes #1055 
This addresses the first problem in the linked issue. Setting the global git info stops the (pointless and confusing) error message below from appearing:
```
console.error src/lib/git.js:126
{ stderr: '\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email "you@example.com"\n  git config --global user.name "Your Name"\n\nto set your account\'s default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <travis@testing-docker-860d44b1-130f-449f-8d40-65c325a11273.(none)>) not allowed\n',
stdout: '',
exitCode: 128 }
console.error src/commands/install.js:463
!! Failed to install underscore at /tmp/install-cmd-test-dir-839512/flowProj/flow-typed/npm/underscore_v1.x.x.js
console.error …
```
> Sets the global git info before running specs in Travis

- definitions/npm/koa_v2.x.x/flow_v0.47.x-/koa_v2.x.x.js
For running tests against `koa` apps it's common to not pass in a `port` argument to `listen` as in this example: https://github.com/koajs/examples/blob/master/hello-world/test.js
This will make `koa` let the OS assign a random port. This is important during testing so that concurrent tests don't create port clashes.
> koa: make `port` argument to `app.listen` optional

- cli/src/commands/install.js
Closes #317 (sorta)
It seems when the install command was build, running `flow-typed install` always overwrote the stubs, whether or not they were modified, and even if `--overwrite` was not used. This patch passes the `overwrite` flag into `createStub` from the `install` command.
I'm curious if there was a reason for this in the original implementation...
> Fixes install overwriting modified stubs

- definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
Previously not covered & threw warnings. This should have been ``typeof serveStatic`` originally, but in-lining it instead.
> Express: Fixing static function

- definitions/npm/node-fetch_v1.x.x/flow_v0.25.x-/node-fetch_v1.x.x.js
- definitions/npm/node-fetch_v1.x.x/test_node-fetch_v1.js
Both of these share the same interface so I suspect this is okay.
In fact, isomorphic-fetch defers to node-fetch when it is being used
in a node environment.
Adding this libdef makes it so node-fetch is properly downloaded by flow-typed
when bootstrapping a repository.
> Copy node-fetch definition over from isomorphic-fetch

- definitions/npm/discord.js_v11.1.x/flow_all/discord.js_v11.1.x.js
- definitions/npm/discord.js_v11.1.x/test_discord.js_v11.1.js
Hi! I'd like to add these definitions for [discord.js](https://github.com/hydrabolt/discord.js).
This library is kind of large, but thankfully there are [TypeScript definitions for it](https://github.com/zajrik/discord.js-typings), which I piped into `flowgen` to produce 99% of these flow definitions. I hand-fixed some things, but the styling in some places is still not quite how I'd like it.
Tests are... difficult because of how many exports there are. For now, I've added a slightly modified version of the test file from the Typescript defs repo. Beyond this, all I can say is that these defs work great for my own, admittedly small discord bot. I'll continue to work on them before and after the hopeful merge as I discover any issues.
> Add discord.js defs

- definitions/npm/redux_v3.x.x/flow_v0.33.x-/redux_v3.x.x.js
- definitions/npm/redux_v3.x.x/flow_v0.33.x-/test_custom_dispatch.js
Redux `Dispatch` is hardwired to accept only `{ type: $Subtype<string> }`. This makes it particularly hard to use redux with redux-thunk or other middlewares without rolling out your own flow annotations.
This PR adds additional parameter `D` which defaults to original `Dispatch<A>` when not provided by consumer, giving backward compatibility for existing consumers and providing flexibility.
The number of examples on how to use custom Dispatch are available at:
https://flow.org/en/docs/frameworks/redux/#toc-typing-redux-thunk-actions
```
// @flow
import type { Store } from 'redux';
type Dispatch = (action: Action | ThunkAction | PromiseAction) => any;
type GetState = () => State;
type ThunkAction = (dispatch: Dispatch, getState: GetState) => any;
type PromiseAction = Promise<Action>;
// …
```
> Add Dispatch override for redux

- definitions/npm/knex_v0.12.x/flow_v0.38.x-/knex_v0.12.x.js
- definitions/npm/knex_v0.12.x/test_knex-v0.12.js
According to the [official documentation](http://knexjs.org/#Builder-wheres):
**where** — .where(mixed)
Object Syntax:
```js
knex('users').where({
first_name: 'Test',
last_name:  'User'
}).select('id')
```
```
Outputs:
select `id` from `users` where `first_name` = 'Test' and `last_name` = 'User'
```
I may be doing something wrong that would cause the [tests to never fail](https://github.com/flowtype/flow-typed/issues/1093). Could someone run the tests with these changes in their environment to make sure they are not breaking anything?
> [knex_v0.12.x] Add a new definition for knex.where()

- definitions/npm/isomorphic-fetch_v2.x.x/flow_v0.25.x-/isomorphic-fetch_v2.x.x.js
The fetch spec allows passing a `URL`-type object as the first argument to `fetch`, and this feature was added to the `fetch` polyfill (and therefore also `isomorphic-fetch`) in January.
> isomorphic-fetch: Enable passing URL objects as first argument

- definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.47.x-/lodash_v4.x.x.js
The return type for the `groupBy` method was changed in #713 into `{[key: V]: ?Array<T>};`. Logically speaking, if a value is not present in the array, it will never be a key in the return value, hence all values in the return object is definitely an array of minimum length 1, and should not be a maybe type. TypeScript's Lodash definition also does not use a maybe type: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/index.d.ts#L7872
cc @ahutchings
> Lodash groupBy array return value should not be maybe

- cli/src/commands/runTests.js
Addresses #1083 
The Regex used to create test groups (when running tests with `--onlyChanged`) did not account for scoped module names. This fix allows for definitions of the type:
`definitions/npm/@turf/destination_v4.x.x/...`
> Fixes test groups not accounting for scoped (@) definitions

- definitions/npm/knex_v0.12.x/flow_v0.38.x-/knex_v0.12.x.js
From the docs: http://knexjs.org/
The connection options are passed directly to the appropriate database client to create the connection, and may be either an object, or a connection string:
var pg = require('knex')({
client: 'pg',
connection: process.env.PG_CONNECTION_STRING,
searchPath: 'knex,public'
});
> knex: allow postgres connection string

- definitions/npm/node-fetch_v1.x.x/flow_v0.25.x-/node-fetch_v1.x.x.js
- definitions/npm/node-fetch_v1.x.x/flow_v0.44.x-/node-fetch_v1.x.x.js
- definitions/npm/node-fetch_v1.x.x/test_node-fetch_v1.js
`node-fetch@1` implements some non-spec methods, [such as `Body#buffer()`](https://github.com/bitinn/node-fetch/blob/1.x/lib/body.js#L67-L76). Furthermore, methods like `entries()`, `keys()`, and `values()` are **not** available in `node-fetch@1` (but they will be in `node-fetch@2`). This patch fixes these issues, using a new libdef inspired by the TypeScript equivalent. I raised the required `flow` version to `@0.44` since that's the first version to support [`http.Agent`](https://nodejs.org/api/http.html#http_class_http_agent).
> Add node-fetch's non-spec API

- definitions/npm/styled-components_v2.x.x/flow_v0.34.x-/styled-components_v2.x.x.js
- definitions/npm/styled-components_v2.x.x/flow_v0.34.x-/test_styled-components_native_v2.x.x.js
- definitions/npm/styled-components_v2.x.x/flow_v0.34.x-/test_styled-components_v2.x.x.js
Previously the following would work:
```js
const NeedsFoo3ErrorClass: ReactComponentClass<{ foo: string, theme: Theme }> = withTheme(NeedsFoo1Class);
```
...but ``withTheme`` actually provides the ``{ theme: Theme }`` & the function should not require it as an input. I implemented the inverse.
With these changes, the following works as expected:
```js
const NeedsFoo1Class: ReactComponentClass<{ foo: string }> = withTheme(NeedsThemeReactClass);
```
> Styled-Components: Fixing withTheme implementation + tests

- definitions/package-lock.json
- definitions/package.json
Add dependencies:
- prettier
- prettier-package-json
- husky
- lint-staged
Add:
- pre-commit script (a call to lint-staged)
- lint-staged rules for `package.json` and `*.js`
I tried to run prettier on the definition files, but ran into a number of errors. Specifically `@@` and use of reserved words (`default`) and redefinition of builtins (`bool`).
Strategies for proceeding might include blacklisting the (few) offending definitions.
> Add prettier toolchain

- definitions/npm/moment_v2.x.x/flow_v0.28.x-/moment_v2.x.x.js
In version 2.18.0, durations gained validity: https://gist.github.com/ichernev/78920c5a1e419fb28c6e4546d1b7235c
More info: https://github.com/moment/moment/pull/3611
> Added isValid() method to moment.js duration class

- definitions/npm/lodash_v4.x.x/flow_v0.47.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.47.x-/test_lodash-v4.x.x.js
- Fixes `unused argument` error when using `_.attempt`
<https://lodash.com/docs/4.17.4#attempt>
> fix(lodash): Fix type def for `attempt`

- definitions/npm/react-router_v4.x.x/flow_v0.30.x-v0.52.x/test_react-router.js
- definitions/npm/react-router_v4.x.x/flow_v0.53.x/react-router_v4.x.x.js
- definitions/npm/react-router_v4.x.x/flow_v0.53.x/test_react-router.js
Added separate definitions that work with Flow v 0.53 for the basic `react-router` package
> A react-router_v4.x.x fix for the Flow version 0.53

- definitions/npm/react-redux_v5.x.x/flow_v0.30.x-v0.52.x/react-redux_v5.x.x.js
- definitions/npm/react-redux_v5.x.x/flow_v0.30.x-v0.52.x/test_connect.js
- definitions/npm/react-redux_v5.x.x/flow_v0.53.x-/react-redux_v5.x.x.js
- definitions/npm/react-redux_v5.x.x/flow_v0.53.x-/test_connect.js
[![Sponsored by Immowelt](https://img.shields.io/badge/sponsored%20by-immowelt-yellow.svg?colorB=ffb200)](https://stackshare.io/immowelt-group/)
This commit fixes an issue with the typings of React-Redux's mapStateToProps function which was reported in #979. The official docs state that the mapStateToProps fn can in fact return another mapStateToProps fn to get a per-instance based memoization.
See the 'Note' on the mapStateToProps documentation block.
https://github.com/reactjs/react-redux/blob/master/docs/api.md\#arguments
/cc @marudor 
resolves #979
> Fix the react-redux mapStateToProps annotations (per-instance memoization)

- definitions/npm/jasmine_v2.4.x/flow_all/jasmine_v2.4.x.js
I also added a eslint disable rule since you're using weak type "Function" here. I tested this on my project it works fine.
The official Jasmine doc is here: https://jasmine.github.io/api/2.7/global.html#xit
> Add timeout param to jasmine definition

- definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.39.x-/test_ramda_v0.x.x_object.js
Ramda support "placeholder currying" (not sure if there's a better word for it) when the argument order doesn't naturally support the kind of partial application you'd like to do:
```js
ramda.prop('x', {x: 100}); // 100
ramda.prop('x')({x: 100}); // 100
ramda.prop(ramda.__, {x: 100})('x'); // 100
```
This is tricky to type, but not impossible. This PR currently does it for `.prop()`. If this looks good, I'll extend it to other functions. It takes bit of brute forcing to type out all the typedefs, but I'm pretty sure that's the only way to get Flow to understand it.
> [ramda] Support placeholder currying

- definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js
- definitions/npm/mongoose_v4.x.x/test_mongoose-v4.js
This libdef covers almost all regular use cases for mongoose models.
Fill free to extend or fix unregular methods and props.
**PLEASE do not add callbacks args (for `.save()`, `.find()` and other methods). 
Promises all the things!!!**
Related #1140
Related https://github.com/entria/flow-typed-wip/issues/1
> Add lib defs for mongoose@4.x.x

- definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.39.x-/test_ramda_v0.x.x_object.js
Looks like this was just a copy-paste blunder from `assoc()`/`assocPath()`.
> [ramda] Fix ramda.dissoc() and ramda.dissocPath() types

- definitions/npm/marked_v0.3.x/flow_v0.28.x-/marked_v0.3.x.js
Fixed an issue with the `marked_v03.x` definitions when running against Flow 0.53.1.
The constructors in these definitions were defined as properties. Here's the error:
```
Classes may not have properties named 'constructor'
```
Changed the constructors to 'methods' that return `this`.
> Fixed marked_v03.x constructor error when using Flow 0.53.1.

- definitions/npm/knex_v0.12.x/flow_v0.38.x-/knex_v0.12.x.js
- definitions/npm/knex_v0.12.x/test_knex-v0.12.js
From Flow v0.54.0 release notes:
> Extending a polymorphic class must now explicitly specify the parent
> class's type args. That is, `class A<T> {}; class B extends A {}` is now
> an error, but class `C extends A<string> {}` or `class D<T> extends A<T> {}` is ok.
> [knex] Update knex.js for Flow v0.54

- definitions/npm/node-uuid_v1.4.x/flow_v0.28.x-/node-uuid_v1.4.x.js
`Buffer<number>` is invalid for all flow versions, but becomes an error in flow 0.53. Fixes #1170
> Fix Buffer usage in node-uuid for flow 0.53

- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/test_rxjs.js
This adds Subscriber, AnonymousSubject, Operator exports as well as
`_subscribe`, `_isScalar`, `source`, and `operator` properties to
Observable.
Derived from the rxjs TypeScript source.
> [rxjs] Add Subscriber, AnonymousSubject, Operator; other Observable props

- definitions/npm/joi-browser_v10.x.x/flow_v0.28.x-/joi-browser_v10.x.x.js
- definitions/npm/joi-browser_v10.x.x/flow_v0.28.x-/test_joi-browser.js
This just duplicates `joi` to `joi-browser` since `joi-browser` is the
browserified version of `joi` and has the same API.
> Add `joi-browser`

- definitions/npm/joi_v10.x.x/flow_v0.28.x-/joi_v10.x.x.js
Declared interfaces were named `<package>$<interfaceName>` when the
standard is `npm$<package>$<interfaceName>` so this just updates all
`joi$<interfaceName>` to be `npm$joi$<interfaceName>` to conform to the
standard.
> Standardize `joi` naming

- definitions/npm/uuid_v3.x.x/flow_v0.32.x-/uuid_v3.x.x.js
- definitions/npm/uuid_v3.x.x/test_uuid_v3.x.x.js
The current definition leaves off the default export which, while deprecated is
valid still. https://github.com/kelektiv/node-uuid#deprecated-api
This is currently used in react-native, so using this definition breaks flow
types in RN >= 0.48.
https://github.com/facebook/react-native/blob/7d4a5b67d497ecc9a07447a95f73d8e2ee84573d/Libraries/Blob/Blob.js#L93
> Fix uuid definition

- definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
This makes the `expand` method from the rxjs TypeScript sources visible in Flow as well.
> [rxjs] Add Observable.expand

- definitions/npm/react-router-dom_v4.x.x/flow_v0.53.x-/react-router-dom_v4.x.x.js
- definitions/npm/react-router-dom_v4.x.x/flow_v0.53.x-/test_react-router-dom.js
- definitions/npm/react-router_v4.x.x/flow_v0.53.x-/react-router_v4.x.x.js
- definitions/npm/react-router_v4.x.x/flow_v0.53.x-/test_react-router.js
- definitions/package-lock.json
- definitions/package.json
These are a couple minor bugfixes to the react-router_v4 and react-router-dom_v4 typedefs.
Currently the props shape for the HOC `withRouter` constructs its internal prop shape with type intersection of inexact object.  This works, but only if the inner component's props signature is an inexact object.
We can improve on this, by using an exact object type for `ContextRouter` and using type spread notation.
See also:
https://github.com/facebook/flow/issues/2626
> React router flow@0.53.x fixes

- definitions/npm/joi-browser_v10.x.x/flow_v0.28.x-/joi-browser_v10.x.x.js
- definitions/npm/joi_v10.x.x/flow_v0.28.x-/joi_v10.x.x.js
In the Joi docs there's an [example that passes an array to Joi.compile](https://github.com/hapijs/joi/blob/v10.6.0/API.md#compileschema). I've tried it and it works fine
> Improve joi and joi-browser compile definition

- definitions/npm/moment_v2.3.x/flow_v0.34.x-/moment_v2.3.x.js
- definitions/npm/moment_v2.3.x/test_moment-v2.js
This will work for `2.4.x`, `2.5.x`, etc. right?
> fix defs for moment.parseZone in v2.3.x+

- definitions/npm/moment_v2.3.x/flow_v0.34.x-/moment_v2.3.x.js
- definitions/npm/moment_v2.3.x/test_moment-v2.js
Couldn't find any other pull requests that were addressing this issue with moment v2.3.x
> Fix definitions for moment isBefore, isAfter etc.

- definitions/npm/enzyme_v2.3.x/flow_v0.53.x-/enzyme_v2.3.x.js
Here is the corresponding constructor definition: https://github.com/airbnb/enzyme/blob/35df18a0835cc7892b155172a500c87c127f153a/packages/enzyme/src/ShallowWrapper.js#L111
```jsx
/**
* @class ShallowWrapper
*/
class ShallowWrapper {
constructor(nodes, root, options = {}) {
```
> enzyme add missing constructor definition

- definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.39.x-/test_ramda_v0.x.x_relation.js
`sortBy` was disabled due to failing tests after v0.38. This was because 
flow started to correctly infer a type error in the test.
The test was using the `nth` function which expects an Array but the
output of the `sortBy` test was expecting a Tuple. Flow does not
consider Tuples and Array equal and threw a type check error even though
this is completely valid at runtime.
Since Flow favors soundness, this is a valid type error. The fix is
re-enabling `sortBy` and fixing the test to not use `nth`.
> Reenable Ramda's `sortBy`

- definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
- definitions/npm/express_v4.x.x/test_express_v4.x.x.js
This is #989, but adds extra type annotations to the failing test case in order to help flow decide which case to select.
> Allow middleware callback to accept refinement of express$Request

- definitions/npm/pg_v6.x.x/flow_v0.28.x-/pg_v6.x.x.js
This adds two missing helper functions `Client#escapeLiteral` and `Client#escapeIdentifier` as well as updates the `ClientConfig` to use optional parameters following the official [node-postgres docs](https://node-postgres.com/api/client).
> pg_v6.x.x.js - Missing functions and fix for ClientConfig

- definitions/npm/express_v4.x.x/flow_v0.25.x-v0.27.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.28.x-v0.31.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
- definitions/npm/express_v4.x.x/test_express_v4.x.x.js
The express v4 libdef has express's `req.query` has being an object with string values, but the values can also be arrays of string. The [express docs](http://expressjs.com/en/api.html#app.set) claim that:
> The simple query parser is based on Node’s native query parser, [querystring](https://nodejs.org/api/querystring.html).
> The extended query parser is based on [qs](https://www.npmjs.com/package/qs).
Both modules support query string array syntax:
```
> querystring.parse('foos=one&foos=two')
{ foos: [ 'one', 'two' ] }
> qs.parse('foos=one&foos=two')
{ foos: [ 'one', 'two' ] }
```
It's unclear to me how to write a good test for this. The one I wrote doesn't seem great, and appears to pass before my change, so I must be doing something wrong. Little help?
Thanks.
> Express req.query values can be arrays.

- definitions/npm/react-intl_v2.x.x/flow_v0.53.x-/react-intl_v2.x.x.js
- definitions/npm/react-intl_v2.x.x/flow_v0.53.x-/test_react-intl_v2.x.x.js
I think `MessageDescriptor` type should be publicly available, for better type annotating.
> Added missing MessageDescriptor type in react-intl

- definitions/npm/react-i18next_v6.x.x/flow_v0.53.x-/react-i18next_v6.x.x.js
- definitions/npm/react-i18next_v6.x.x/test_react-i18next_v6.x.x.js
- definitions/package-lock.json
Copied over the v2.x.x libdef, added the additional exports that have been added to match the latest release of react-i18next, and made modifications to be 0.53.x- compatible.
> Add libdef for react-i18next v6.x.x for flow v0.53.x- (#1279)

- definitions/npm/raven-js_v3.17.x/flow_v0.38.x-/raven-js_v3.17.x.js
- definitions/npm/raven-js_v3.17.x/test_raven-js.js
Connected to https://github.com/getsentry/raven-js/issues/717
This basically takes the existing Typescript definitions and translates them into flow definitions. I am trusting that the TS defs are accurate.
Also, it is possible these types work for 3.x.x, but I don't know know enough history of the project to say for sure.
The tests could be more extensive, but I covered the basics.
> Add libdef for raven-js at v3.17.x

- definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
We are missing a typedef for [`Observable.combineLatest(a)`](
http://reactivex.io/rxjs/test-file/spec-js/observables/combineLatest-spec.js.html#lineNumber448).
While the usage seems odd, it is valid and makes sense when you expect new observables to be added later to the list of arguments.
> [rxjs] Add support for combineLatest with a single argument

- definitions/npm/moment_v2.3.x/flow_v0.34.x-/moment_v2.3.x.js
Added missing constructor that is available since moment.js version 2.3
> Added missing constuctor

- definitions/npm/moment_v2.3.x/flow_v0.34.x-/moment_v2.3.x.js
As of moment 2.13.0 isBetween not supports many more arguments. See documentation here: https://momentjs.com/docs/#/query/is-between/
This PR updates the types for the `moment.isBetween` function to support all supported arguments.
Fixes #891
> Update to moment to fix isBetween method

- cli/src/commands/runTests.js
From NodeJS' docs:
> path.sep provides the platform-specific path segment separator:
> - \ on Windows
> - / on POSIX
> Note: On Windows, both the forward slash (/) and backward slash (\) are accepted as path segment separators; however, the path methods only add backward slashes (\).
Backward slashes resulted in breaking flow-typed for Windows. This PR fixes it.
> Closes #1313

- definitions/npm/react-i18next_v6.x.x/flow_v0.53.x-/react-i18next_v6.x.x.js
- definitions/npm/react-i18next_v6.x.x/test_react-i18next_v6.x.x.js
`translate` can have no parameters. 
As discussed in https://github.com/flowtype/flow-typed/pull/1298#issuecomment-335154361
@TLadd please review
> fix translate in react-i18next_v6.x.x

- definitions/npm/jasmine_v2.4.x/flow_all/jasmine_v2.4.x.js
- definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x_addMatchers.js
The `addMatchers` function in Jasmine 2.4.x was missing; this adds it.
> Adding `addMatchers` for Jasmine

- definitions/npm/react-addons-css-transition-group_v15.x.x/flow_v0.26.x-v0.52.x/react-addons-css-transition-group_v15.x.x.js
- definitions/npm/react-addons-css-transition-group_v15.x.x/flow_v0.53.x-/react-addons-css-transition-group_v15.x.x.js
- definitions/npm/react-addons-css-transition-group_v15.x.x/test_react-addons-css-transition-group.js
The `enter`, `leave` and `appear` keys of the `ReactCSSTransitionGroupNames` object are actually all totally optional.
See: https://github.com/reactjs/react-transition-group/blob/v1-stable/src/utils/PropTypes.js#L38 (all properties are missing `.isRequired`)
> Update to `react-addons-css-transition-group`

- definitions/npm/react-immutable-pure-component_v1.x.x/flow_v0.53.x-/react-immutable-pure-component_v1.x.x.js
- definitions/npm/react-immutable-pure-component_v1.x.x/test_react-immutable-pure-component_v1.x.x.js
I've been using [react-immutable-pure-component](https://github.com/Monar/react-immutable-pure-component) with flow, which doesn't have an entry in flow-typed. I made a type definition which I've been using successfully on my own project and now I'd like to push it upstream to flow-typed.
react-immutable-pure-component is a simple wrapper for React$Component that adds better support for [immutable.js](https://github.com/facebook/immutable-js/) props. My type definition should just reproduce the flow typing of React$Component, which is the parent class of `ImmutablePureComponent`.
> Added type definitions for react-immutable-pure-component

- definitions/npm/moment_v2.3.x/flow_v0.34.x-/moment_v2.3.x.js
- definitions/npm/moment_v2.3.x/test_moment-v2.js
This regression got introduced with #1242, when a seemingly older version of moment_v2.x.x was forked into moment_v2.3.x.  This definition was previously fixed by me in #890 (for moment_v2.x.x back then), and this now re-introduces the same fix for the forked v2.3.x version, which requires the same method signature for `.utcOffset()`.
When committing the changes, a local precommit hook reformatted my code, so I suppose that's the preferred format.  Anyway, that's why this PR consists of 2 commits:
1. 523f2d3c8c388cce2d5b9bb520e5eb4ad2d46445 with purely the auto-reformatting change
2. 9f4c78fe4030818898bfdf271cc2323c269d1d99 with the actual change that fixes the regression
> Fix regression in moment_v2.3.x

- cli/src/lib/npm/npmLibDefs.js
Addresses spec failures in #937
> Fix npm check for packages of type @<parent>/<package>

- definitions/npm/classnames_v2.x.x/flow_v0.22.x-v0.24.x/classnames_v2.x.x.js
- definitions/npm/classnames_v2.x.x/flow_v0.25.x-/classnames_v2.x.x.js
- definitions/npm/classnames_v2.x.x/test_classnames_v2.x.x.js
Other than strings, array arguments can contain objects and falsy values. Arrays are just flattened.
> Fully support array arguments in classnames

- cli/src/commands/runTests.js
Fixes #1335 
/cc @HyperBrain @ebrearley
> Escapes backslashes when on windows for path regex

- definitions/npm/knex_v0.13.x/flow_v0.38.x-/knex_v0.13.x.js
- definitions/npm/knex_v0.13.x/test_knex-v0.13.js
This is another one of these: https://github.com/flowtype/flow-typed/issues/374
Unfortunately it seems that package version directories cannot contain a semver range, so I've resubmitted the existing v0.12.x definitions.
> Copy typedefs from knex_v0.12.x to knex_v0.13.x

- cli/src/commands/__tests__/install-test.js
- cli/src/commands/install.js
Just prints to `console.error`
Fixes #995
> A valid package.json with no dependencies should not fail.

- definitions/npm/query-string_v5.x.x/flow_v0.32.x-/query-string_v5.x.x.js
The function looks like this 
```js
exports.extract = function (str) {
return str.split('?')[1] || '';
};
```
https://github.com/sindresorhus/query-string/blob/master/index.js#L116
It's plainly obvious that this will never return `null` or `undefined`.
> query-string's extract() method will never return null

- definitions/npm/redux-oidc_v3.x.x/flow_v0.55.x-/redux-oidc_v3.x.x.js
- definitions/npm/redux-oidc_v3.x.x/flow_v0.55.x-/test_redux-oidc.js
This PR adds types for [redux-oidc](https://github.com/maxmantz/redux-oidc) (v3). I converted this from the libdefs in a private repository that uses `redux-oidc`. I'm not positive this is 100% API complete, but it should be very close.
> add redux-oidc v3 types

- definitions/npm/firebase_v4.x.x/flow_v0.34.x-/firebase_v4.x.x.js
- definitions/npm/firebase_v4.x.x/flow_v0.34.x-/test_firebase.js
Typings for firebase v4 were missing storage type. This PR is primarily to address this issue. 
Additionally, the following changes were necessary:
- Tests were fixed starting at the current master. The failure is probably due to a change in the treatment of suppression comments in a recent flow release.
- Namespaces were added to avoid conflicts between `storage` and `database`. All global declarations are now prefixed with `$npm$firebase$`.
Tagging @PCreations and @stevenyap.
> Add typings for storage in firebase_v4.x.x

- definitions/npm/express_v4.x.x/flow_v0.32.x-/test_response.js
This commit fixes the following error when running the `./run_def_tests.sh` command:
`\flow-typed\definitions\npm\express_v4.x.x\flow_v0.32.x-\test_response.js`
` 1:1  error  Test has to include at least 1 negative Tests`
According to the Flow-Typed documentation, this is a requirement.  See also:
[https://github.com/flowtype/flow-typed/wiki/Contributing-Library-Definitions#writing-libdef-tests](https://github.com/flowtype/flow-typed/wiki/Contributing-Library-Definitions#writing-libdef-tests)
> Add Negative Test for Express Flow-Typed Test

- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/test_rxjs.js
This PR adds a bunch of updates:
1. Made the projection operators (switchMap, mergeMap, concatMap) more consistent - defined a common `ObservableInput` type to mirror the docs and made the `resultSelection` argument consistent (`switchMap` actually incorrectly took a numerical index as the second argument).
2. Adds the `exhaustMap` operator, following the patterns above.
3. Adds `Observable.range` and the member operators `bufferTime`, `defaultIfEmpty`, and `timeoutWith`. These are pretty straightforward.
4. Updates the `groupBy` operator to be more precise, along with a `rxjs$GroupedObservable` type (which has an additional 'key' member). The third argument is actually a duration selector rather than a comparison function.
I've added tests for most of the changes where appropriate.
As …
> Batch of rxjs definition updates

- definitions/package.json
`npm run precommit` currently errors out: https://gist.github.com/Ashoat/1969bf63b407696d835ef397ebb4acd7
This PR fixes it.
> Fix lint-staged precommit bug

- definitions/npm/express_v4.x.x/flow_v0.25.x-v0.27.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.28.x-v0.31.x/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.28.x-v0.31.x/test_overrideUseMethodClassExtension.js
- definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
- definitions/npm/express_v4.x.x/flow_v0.32.x-/test_overrideUseMethodClassExtension.js
- definitions/npm/express_v4.x.x/test_express_v4.x.x.js
In [express docs](http://expressjs.com/en/4x/api.html#path-examples) mixed paths (containing `RegExp` along with `string`) are allowed for `get()`, `use()`, etc. but current flow typings restrict them.
Here is the fix providing a new `express$Path` type and using it in `express$RouteMethodType` interface.
> [express@4.x.x] Allow mixed paths

- definitions/npm/log4js_v2.x.x/flow_v0.38.x-/log4js_v2.x.x.js
- definitions/npm/log4js_v2.x.x/flow_v0.38.x-/test_log4js.js
log4js v2 has TypeScript definitions, so I adapted the Flow types from https://raw.githubusercontent.com/nomiddlename/log4js-node/master/types/log4js.d.ts.
A list of (minor) modifications needed, for reference:
- Moved all the functions to the end, since they need to be defined after the types.
- Replaced various instances of `interface` with `type` due to the subtle behavior differences (especially when used with unions).
- `s/export type/declare export type`.
- Had to manually declare `module.exports` rather than using `declare export function`.
> Add types for log4js v2.x.x

- definitions/npm/chalk_v2.x.x/flow_v0.19.x-/chalk_v2.x.x.js
This PR adds all missing bright color variations to the v2 typings of chalk, seems like they where somehow forgotten.
> Add missing chalk bright color variations to the v2 typings

- definitions/npm/log4js_v2.x.x/flow_v0.38.x-/log4js_v2.x.x.js
`setLevel` and `new` don't actually exist. (`new` is a TypeScript-specific syntax, and it doesn't really make sense to port over anyway).
See also: https://github.com/log4js-node/log4js-node/pull/574
> Minor correction to log4js@2.x.x types

- cli/src/lib/libDefs.js
- cli/src/lib/npm/__tests__/npmLibDefs-test.js
- cli/src/lib/npm/npmLibDefs.js
Trying to install definitions with `flow-typed install` I faced an `Invalid comparator` error due to GitHub repo dependency in my _package.json_ file.
This solution avoids `Invalid comparator` errors by ignoring non-semver packages and and installing stubs for them.
Closes #1127
> Do not fail on 'Invalid comparator' error

- definitions/npm/axios_v0.16.x/flow_v0.25.x-/axios_v0.16.x.js
Hi.  Sorry if I am misunderstanding this however I think that this property should be optional.
https://github.com/axios/axios#request-config
> [axios] Headers should be optional in a request config

- cli/src/commands/runTests.js
This is naive solution for the https://github.com/flowtype/flow-typed/issues/1385 . Flow returns errCode 0 if it only detects warnings so it can't be used unless someone makes changes to Flow it self.
Failing on all the warnings might not be bad idea either as type definitions should follow as good practices as possible imo.
Testing the type definitions would benefit a lot of tests too. This bug could perhaps have been caught by them.
Fixing this might reveal quite a lot of broken type definitions.
> fixes: 1385 fail test if not valid success message

- definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/test_ramda_v0.x.x_object.js
There were some issues with the current definition for Ramda's `#pick`:
- Would not correctly detect invalid keys, so the following would not fail
```js
const pck2: Object = _.pick([ 'a', 'b' ], { a: 1 })
```
- Did not allow passing in typed object literals (a very common use case), so something like this would fail when the keys had different types:
```js
const pickedObj: { a: string, b: number, c: boolean } = { a: 'hello', b: 1, c: true }
const pck3: { a: string, b: number } = pick(['a', 'b'], pickedObj)
```
This PR addresses both issues.
> Improve typing for Ramda #pick.

- definitions/npm/mousetrap_v1.x.x/flow_v0.21.x-/mousetrap_v1.x.x.js
- definitions/npm/mousetrap_v1.x.x/test_moustrap-v1.js
Moustrap's `unbind` function can accept either a string or an array of strings. This PR updates the definition to permit Array<string>.
> Mousetrap update: Enable unbinding Array<string>

- README.md
- :books: Document the CLI's `--ignoreDeps` flag
Most of the time people don't want to install the `devDependancies`,  I faced the problem myself and found a lead at https://github.com/flowtype/flow-typed/issues/599 I think it's a good addition to the `README`; by intuition, I checked there first.
> Document cli's --ignoreDeps flag

- definitions/npm/redux-act_v1.x.x/flow_v0.34.x-/redux-act_v1.x.x.js
- definitions/npm/redux-act_v1.x.x/flow_v0.34.x-/test_redux-act_v1.x.x.js
Adding flow types and tests for the two commonly used functions in `redux-act`:
- `createAction`
- `createReducer`
> Adding initial types for redux-act

- definitions/npm/normalize.css_v7.x.x/flow_v0.34.x-/normalize.css_v7.x.x.js
- definitions/npm/normalize.css_v7.x.x/flow_v0.34.x-/test_normalize.css-v7.x.x.js
Normalize.css may be imported for side-effects, e.g. to force webpack's `css-loader` to bundle it with other CSS modules.
> Add library definition for normalize.css_v7.x.x

- definitions/npm/axios_v0.17.x/flow_v0.25.x-/axios_v0.17.x.js
- definitions/npm/axios_v0.17.x/test_axios-v0.17.js
The only type change I could see from [v0.16.2](https://github.com/axios/axios/compare/v0.16.2...v0.17.0) was in the `proxy` configuration, which now accepts `false` or a `ProxyConfig` object.
> Adding axios v0.17.x

- definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.55.x-/test_lodash-v4.x.x.js
This change solves part of an issue #1099. It doesn't touch functions other than find. Other immutable functions should be changed separately.
Change was straightforward, I just replaced `Array`  with `$ReadOnlyArray` on `find*` functions and added a single test case, but then `prettier` decided to convert every single quote to a double quote. Please let me know if I should submit these changes differently.
> lodash: Use $ReadOnlyArray as an input to `find*` functions

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
The module exports `RedisClient`, not `Client`:
```js
> require('redis')
{ debug_mode: false,
createClient: [Function],
RedisClient: 
{ [Function: RedisClient]
super_: 
{ [Function: EventEmitter]
EventEmitter: [Circular],
usingDomains: true,
defaultMaxListeners: [Getter/Setter],
init: [Function],
listenerCount: [Function] },
connection_id: 0 },
print: [Function: print],
Multi: [Function: Multi],
AbortError: { [Function: AbortError] super_: { [Function: RedisError] super_: [Object] } },
RedisError: 
{ [Function: RedisError]
super_: 
{ [Function: Error]
captureStackTrace: [Function: captureStackTrace],
stackTraceLimit: 10 } },
ParserError: 
{ [Function: RedisError]
super_: 
{ [Function: Error]
captureStackTrace: [Function: captureStackTrace],
stackTraceLimit: 10 } },
ReplyError: { …
```
> fix bugs and extend coverage of redis package

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_list.js
http://ramdajs.com/docs/#reduceRight
> The iterator function receives two values: (value, acc), while the arguments' order of reduce's iterator function is (acc, value).
> ramda#reduceRight, fixes incorrect argument order

- definitions/npm/formik_v0.9.x/test_formik.js
PR https://github.com/flowtype/flow-typed/pull/1395 introduced a definition test file that fails an eslint rule requiring a negative test. To be honest, I'm not sure how the travis build was successful for it. Is there something missing in the travis config?
Clone master to reproduce:
```
cd definitions
yarn install
yarn test
/Users/patrick.winters/projects/hack/flow-typed/definitions/npm/formik_v0.9.x/test_formik.js
1:1  error  Test has to include at least 1 negative Tests  flow-typed/negative-tests
```
> formik, installs dummy expected error to fix eslint error

- definitions/npm/pify_v3.x.x/flow_v0.25.x-/pify_v3.x.x.js
- definitions/npm/pify_v3.x.x/test_pify_v3.x.x.js
Definition for [sindresorhus/pify](https://github.com/sindresorhus/pify) module.
`pify()` accepts either a promisifiable function **or** an object with promisifiable methods. For the latter case I'm not sure how I can make the typing more specific, as the passed object might also contain miscellaneous non-function properties which pify just passes through unmodified. So I've just used the weak `Object` type for this case. Let me know if there's a better way to do this.
> Add definition for pify

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_relation.js
`propEq` now requires the key to be on the object supplied, and the comparison value must be the same type as the value of the property on that key.
> use stricter typing on ramda's propEq

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_misc.js
The Ramda `isNil` function is a useful predicate that should refine the type of a variable. The test added in the diff did not pass originally, but does not with the updated definition.
It's not possible to provide the type refinement while still specifying a boolean literal, so something like this isn't possible:
```js
declare function isNil(x: void | null): true %checks (x === undefined || x === null);
//1:   declare function isNil(x: void | null): true %checks (x === undefined || x === null);
//                                                                              ^ boolean. Expected boolean literal `true`
//1:   declare function isNil(x: void | null): true %checks (x === undefined || x === null);
//                                             ^ boolean literal `true`
```
Having …
> Add type refinement to Ramda #isNil.

- travis.sh
Recently I found that I was unable to successfully run `./run_def_tests.sh` after updating a ramda defintion because another definition test was committed without a negative test (in violation of the "flow-typed/negative-tests" rule in `definitions/.eslintrc`. https://github.com/flowtype/flow-typed/pull/1479
FWIW, this commit [https://github.com/flowtype/flow-typed/commit/fb7612683c8a2546d95bfe58f91f50c654ecd066](https://github.com/flowtype/flow-typed/commit/fb7612683c8a2546d95bfe58f91f50c654ecd066), a year ago, commented out `yarn test` in `/definitions`, which enforces the rule and is also run by `./run_def_tests.sh`.
> run 'yarn test' in defintions, which enforces eslint rules

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_relation.js
This is a followup to #1499. Per a discussion with @AndrewSouthpaw and (out of band) @forticulous, the usage of `$ElementType` needs a [workaround](https://github.com/facebook/flow/issues/4804) applied. Use of the workaround is already documented in the libdef here but I had not applied the workaround to all versions of `propEq` - just the 3 param version.
This PR adds additional negative test cases for the other arities of `propEq` and applies the workaround to the remaining versions of `propEq`.
> apply $ElementType workaround to other ramda propEq arities

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js
I used flowgen to convert https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sequelize and then did a **lot** of manual revision and shortened some type names.
Note: there are TypeScript defs straight from the horse's mouth at https://github.com/types/sequelize, but I didn't find them until after I had put a lot of work into converting the DefinitelyTyped defs, and I'm about tuckered out so `¯\_(ツ)_/¯`
There are definitely various issues (esp. lack of flow support for symbol properties, flow union type bugs) but I think this is a pretty good start.  If someone wants to try to blow these away and convert https://github.com/types/sequelize instead, be my guest.
Meanwhile, I'm going to go get my eyeballs replaced... 🙈
> create defs for sequelize v4

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_relation.js
I ran into some problems with the `$ElementType` utility type. `$Keys<T>` is a union of property names. I added some test cases to include objects with multiple names and the typedef we had broke.  
After exploring with a repl I've found `propEq` is totally fine with comparing values of varied types. The behavior of `propEq` is that of `===` ([example](http://ramdajs.com/repl/#?const%20foo%20%3D%20%7B%20bar%3A%20%27string%27%7D%0AR.propEq%28%27bar%27%2C%205%2C%20foo%29)), and in Flow you can compare using `===` with anything and that type checks ok ([example](https://flow.org/try/#0KwAgvBIOTFBQcDGB7AdgZwC4lQVwLbggCMSaWIWATkVAEzxkbZUCm6uANtmDgeJGpMKyTAAtWNXnkKDMVOEA)). This means we can treat the comparison value as `mixed` and we can drop the use of `$ElementType`. No more workaround …
> support ramda's propEq's === nature

- definitions/npm/jest_v21.x.x/flow_v0.22.x-v0.38.x/jest_v21.x.x.js
- definitions/npm/jest_v21.x.x/flow_v0.39.x-/jest_v21.x.x.js
Per [the docs](https://facebook.github.io/jest/docs/en/expect.html#tomatchobjectobject):
> You can also pass an array of objects, in which case the method will return true only if each object in the received array matches (in the `toMatchObject` sense described above) the corresponding object in the expected array.
> Allow Jest's toMatchObject to receive an array of objects

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0..x.x_partial.js
According to Ramda's [docs on partial](http://ramdajs.com/docs/#partial), and a [quick example](http://ramdajs.com/repl/?v=0.25.0#?const%20add3%20%3D%20%28a%2C%20b%2C%20c%29%20%3D%3E%20a%20%2B%20b%20%2B%20c%0AR.partial%28add3%2C%20%5B1%5D%29%282%29%284%29) both point to Ramda not returning an auto-curried function (this is [curry](http://ramdajs.com/docs/#curry)'s job).
Producing a proper implementation for `partial` is rather tedious and error prone. I built a generator for it which can be found on this [typedef-gen](https://github.com/LoganBarnett/typedef-gen) repository I put together. The current variation supports up to 10 arguments in a function, but supporting more is a simple means of running the generator with a higher number and pasting the results in the Ramda libdef. I believe …
> stop declaring that ramda's partial returns curried functions

- definitions/npm/jest_v21.x.x/flow_v0.39.x-/jest_v21.x.x.js
These two methods also accept a class as argument. See https://github.com/facebook/jest/blob/master/packages/expect/src/to_throw_matchers.js#L53
> Fix toThrow and toThrowError type definitions

- definitions/npm/koa-router_v7.2.x/flow_v0.25.x-/koa-router_v7.2.x.js
- definitions/npm/koa-router_v7.2.x/test_koa-router_v7.2.x.js
The middleware function for `.param()` is slightly different from the usual koa middleware.
See [the readme](https://github.com/alexmingoia/koa-router#module_koa-router--Router+param).
> patch(koa-router): fix param middleware

- definitions/npm/node-fetch_v1.x.x/flow_v0.44.x-/node-fetch_v1.x.x.js
- definitions/npm/node-fetch_v1.x.x/test_node-fetch_v1.js
Consider the following code using `node-fetch`:
```
// @flow
import fetch from "node-fetch"
fetch("https://requestb.in/xzxek2xz", {
headers: {
Authorization: "Bearer foo",
},
})
.then(function (res) {
console.log(res)
})
```
This works fine as it should. Yet checking the flow types returns the following error:
```
example.js:6
v
6:   headers: {
7:     Authorization: "Bearer foo",
8:   },
^ object literal. This type is incompatible with an argument type of
28:     headers?: HeaderInit | {
^^^^^^^^^^ array type. See lib: flow-typed/npm/node-fetch_v1.x.x.js:28
example.js:6
v
6:   headers: {
7:     Authorization: "Bearer foo",
8:   },
^ property `Authorization`. Property not found in
28:     headers?: HeaderInit | {
^^^^^^^^^^ Headers. See lib: flow-typed/npm/node-fetch_v1.x.x.js:28
Found 2 …
```
> Headers issue in node-fetch.

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_object.js
The definition for the [evolve](http://ramdajs.com/docs/#evolve) method was missing.
> feat(ramda): add def for evolve

- definitions/npm/recompose_v0.24.x/flow_v0.55.x-v0.56.x/recompose_v0.24.x.js
- definitions/npm/recompose_v0.24.x/flow_v0.57.x-/recompose_v0.24.x.js
I noticed in my project that type inference doesn't work when I'm using `compose` from recompose imported directly as single module:
```
import compose from 'recompose/compose';
```
This works as supposed:
```
import { compose } from 'recompose';
```
> Add direct recompose/compose export

- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
`Observable.pipe()` is not a very commonly used (or well documented) method, but it's crucial for users of Flow, because with Observable.pipe, it's possible to define your own custom Rx operators as functions. This way (unlike adding custom methods to Observable prototype), the whole chain can remain strongly typed.
The purpose of `rxjs$OperatorFunctionLast` is so that functional operators returning e.g. ConnectableObservable can be used with pipe without losing return type information.
> [rxjs] Adds types to Observable.pipe()

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
As noted in issue #1581 - the `Sequelize.condition` method is exactly equal to `Sequelize.where` as of Sequelize 4.8.2. So the function signatures should be identical.
> fixing issue 1581 - Sequelize.condition accepts 3 arguments

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_list.js
Ramda's documentation for [find](http://ramdajs.com/docs/#find) as well as a [quick example](http://ramdajs.com/repl/#?R.find%28o%20%3D%3E%20o%20%3D%3D%20%27bar%27%2C%20%7Bfoo%3A%20%27bar%27%7D%29) shows that it cannot meaningfully perform a search over an object. This corrects the type and adds an assertion in the test that expects an error when trying to call `find` with an object.
Ramda handles these situations gracefully but in a Flow ecosystem I don't believe it will be desired to pass objects into `find` and expect that to type check successfully.
> prevent ramda's find from searching an object

- definitions/npm/bson_v1.x.x/flow_v0.50.x-/bson_v1.x.x.js
- definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js
- definitions/npm/mongoose_v4.x.x/test_mongoose-v4.js
Rebase #1557 without merge commit.
---
For now `mongoose` package contains a workaround for using `bson$ObjectId` class. (Cause tests for `flow-typed` does not import globals from `bson` package.) 
Module imports like in #16 ...
```js
declare module 'mongoose' {
import type { BsonObjectId } from 'bson';
...
};
```
...does not meet my needs, cause `Mongoose$Document` should be global class which uses `bson$ObjectId`. 
So, for now, working solution is to copy-paste needed classes from `bson`  package inside `mongoose` defs.
> small fixes in `mongoose`, renamed global vars in `bson`

- cli/src/commands/runTests.js
Fix error
```
PS C:\Users\andrey.vassilyev\projects\flow-typed\cli> node dist/cli.js run-tests redux_v3
Running definition tests in C:\Users\andrey.vassilyev\projects\flow-typed\definitions\npm...
Fetching all Flow binaries...
Finished fetching Flow binaries.
UNCAUGHT ERROR: TypeError: Invalid Version: undefined
at new SemVer (C:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\semver\semver.js:279:11)
at SemVer.compare (C:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\semver\semver.js:342:13)
at compare (C:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\semver\semver.js:566:31)
at Object.lt (C:\Users\andrey.vassilyev\projects\flow-typed\cli\node_modules\semver\semver.js:600:10)
at C:\Users\andrey.vassilyev\projects\flow-typed\cli\dist\commands\runTest …
```
> skip test if flow version is unavaliable for platform

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
There was a missing UnaryFn argument that prevented types to flow correctly.
> (Ramda) Add missing `UnaryFn<C, D>` in `Pipe` definition

- definitions/npm/ramda_v0.x.x/flow_v0.28.x-v0.30.x/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.28.x-v0.30.x/test_ramda_v0.x.x_object.js
- definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/test_ramda_v0.x.x_object.js
- definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/test_ramda_v0.x.x_object.js
- definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/test_ramda_v0.x.x_object.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_object.js
The `where` declaration originally expected every predicate unary function to only except the same
type. I've tried to remedy that with the new utility type `$ObjMap` (where possible).
There's also the usual "prettier" changes.
> fix(ramda): fix where function declaration

- definitions/npm/aphrodite_v0.5.x/flow_v0.28.x-/aphrodite_v0.5.x.js
Make the `StyleDefinition` type an export from the Aphrodite definitions.
I needed to use `StyleDefinition` in order for a component to receive custom classes:
```JSX
<MyComponent
classes={[styles.class1, styles.class2]}
/>
```
```JSX
import * as React from 'react';
import { css } from 'aphrodite';
import type { StyleDefinition } from 'aphrodite';
type Props = {
classes: Array<StyleDefinition>,
};
class MyComponent extends React.PureComponent<Props> {
render () {
return (
<p className={css(styles.mainClass, ...this.props.classes)}>
Hello, world!
</p>
);
}
}
```
> Export `StyleDefinition` type from aphrodite

- definitions/npm/express_v4.16.x/flow_v0.32.x-/express_v4.16.x.js
- definitions/npm/express_v4.16.x/flow_v0.32.x-/test_overrideUseMethodClassExtension.js
- definitions/npm/express_v4.16.x/flow_v0.32.x-/test_response.js
- definitions/npm/express_v4.16.x/test_express_v4.16.x.js
This adds the ability to use `express.json()` per the [documentation](http://expressjs.com/en/4x/api.html#express.json). This was introduced in 4.16.0 so there's a new version section for express that covers 4.16.x and above.
> add express.json() middleware support (requires 4.16.x)

- definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
This PR adds some missing `forkJoin` RxJS signatures and adds tests for them.
Signatures added:
```
static forkJoin<A>(
a: Array<rxjs$Observable<A>>,
_: void
): rxjs$Observable<Array<A>>;
static forkJoin<A>(
a: Array<rxjs$Observable<any>>,
_: void
): rxjs$Observable<A>;
static forkJoin<A, B>(
a: Array<rxjs$Observable<A>>,
resultSelector: (...values: Array<A>) => B
): rxjs$Observable<B>;
static forkJoin<A>(
a: Array<rxjs$Observable<any>>,
resultSelector: (...values: Array<any>) => A
): rxjs$Observable<A>;
```
Related documentation:
https://github.com/ReactiveX/rxjs/blob/master/src/observable/ForkJoinObservable.ts#L34
https://github.com/ReactiveX/rxjs/blob/master/src/observable/ForkJoinObservable.ts#L35
https://github.com/ReactiveX/rxjs/blob/master/src/observable/ForkJoinObservable.ts#L36 …
> RxJS: Add missing type signatures for forkJoin.

- definitions/npm/awilix_v2.x.x/flow_v0.56.x-/awilix_v2.x.x.js
- definitions/npm/awilix_v2.x.x/test_awilix_v2.x.x.js
Hey there!
I made a typedef for Awilix v2 (latest).   It's more useful than the current TS file because it actually captures parameters passed to registration functions and forwards type information into the cradle, but you have to modify the type signature of the reference yourself because it doesn't seem to be possible to change `this` inside a libdef.  So `container = createContainer().register(...)` is type-aware but `container = createContainer(); container.register(...)` is not :(
It's tested as well and the tests pass.
Let me know if there's anything I need to do to get this bad boy merged!
> Add awilix v2.x type definition

- definitions/npm/joi-to-json-schema_v3.2.x/flow_v0.34.x-/joi-to-json-schema_v3.2.x.js
- definitions/npm/joi-to-json-schema_v3.2.x/test_joi-to-json-schema_v3.2.x.js
Hey there!
I'm back with another lib def, this one is real small.
I couldn't type hint the first arg which should be `npm$joi$ObjectSchema` but the joi libdef is not in scope and it doesn't seem there's any way to get it added to the test that I can find.  Let me know if there's something I can do to get the Joi type definition in scope in this libdef.
Thanks!
> Add type definition for joi-to-json-schema v3.2.x

- definitions/npm/koa-router_v7.2.x/flow_v0.25.x-/koa-router_v7.2.x.js
- definitions/npm/koa-router_v7.2.x/test_koa-router_v7.2.x.js
`koa-router` allows passing multiple middleware to verb methods:
```javascript
router.get('/route', middleware(), (ctx) => {})
```
Additionally, `next` in a middleware should always return a `Promise<void>`.
> koa-router: Allow multiple middlewares for verb methods, fix middleware definition

- cli/src/commands/install.js
Many projects might have enhanced libdefs which they are jsut too lazy to contribute back, or then they don't exactly know how to do it. Suggest contributing changed libdefs back to flow-typed when flow detected that libdef is changed.
precommit-pretteir did it's thing, I just changed the message.
> make changed libdef message welcoming to contribute changes back

- cli/src/lib/npm/npmLibDefs.js
I discovered while working on another PR that the logic in filterLibDefs filters out all valid matches for a scoped package.
> fix(filterLibDefs): fix scoped packages bug

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_list.js
Prompted by a discussion [here](https://github.com/facebook/flow/issues/5457), I came across some issues with feeding `$ReadOnlyArray` to `reduce`. Since Ramda assumes immutability, I've added support of `$ReadOnlyArray` to `reduce`.
Side effects of this PR include:
1. Renaming output variables of `reduceRight` and `scan` to not overlap with `reduce`'s output variables.
2. Adding a negative test for `reduce`.
3. Using an example from the documentation for `reduce`.
4. Using the `declare type Foo = curried1_1_1 & curried1_2 & curried2_1 & curried_3 ...` form over `declare function`.
5. Removing the rest args as a means of ignoring unused arguments in `reduce`.
CC @AndrewSouthpaw due to recent work with Ramda's libdefs.
> include $ReadOnlyArray in the array types that reduce accepts

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js
adds the `getAssociations` and `getAssociationForAlias` methods to `Model`
> fix(sequelize): add missing Model methods

- definitions/npm/angular_v1.4.7/flow_v0.47.x-/angular_v1.4.7.js
- definitions/npm/angular_v1.4.7/flow_v0.47.x-/test_angular_timeout_v1.4.7.js
- definitions/npm/angular_v1.4.7/flow_v0.47.x-/test_angular_v1.4.7.js
- definitions/npm/angular_v1.4.7/flow_v0.47.x-/test_utility_functions_v1.4.7.js
Plenty of enhancements for angular 1.x libdefs. These are the types we currently use at Smartly for angular. So not perfect, but better. Some utility function types missing etc.
Some of the commits have link to appropriate angular documentation to make reviewing slightly easier.
ping @LoganBarnett
> Better angular 1.4.7 types

- definitions/npm/formik_v0.9.x/flow_v0.53.x-/formik_v0.9.x.js
It appears that destructuring types into new ones is not supported by flow, so I replaced this with the intersection type (which appears to be made exactly for this type of use case). 😄
> Replace destructuring with type intersection

- definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/test_lodash-v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/test_lodash-v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.47.x-v0.54.x/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.47.x-v0.54.x/test_lodash-v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.55.x-/test_lodash-v4.x.x.js
Fixes #656 
Replaces #1629 
`_.toPairs` takes an object and returns an array of key-value tuples ([docs](https://lodash.com/docs/4.17.4#toPairs)). 
The old libdef defined the return value as `NestedArray<T> = Array<Array<T>>`, which is too strict because an object can have non-string values (the key will always be string type). 
``` js 
var o = {
a: 12, 
b: 100,
};
// This fails, because Flow expects pairs to be [string][]
var pairs: [string, number][] = _.toPairs(o); // => [['a', 12], ['b', 100]]
```
All credit to @ZhangYiJiang
> Fix lodash toPairs/toPairsIn/entries/entriesIn

- definitions/npm/mysql_v2.x.x/flow_v0.28.x-/mysql_v2.x.x.js
- definitions/npm/mysql_v2.x.x/test_mysql_v2.x.x.js
Libdef for `mysql` was not correct, it gave an error for one of the documented examples in the README.md:
https://github.com/mysqljs/mysql#escaping-query-values
The diff for the test file is mostly prettier noise, but I'll leave a comment highlighting the two lines I added testing the exact example from the readme.
> Mysql: query values can be object

- definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-partition
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-window
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-windowCount
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-windowToggle
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-windowWhen
> Rxjs add missing definitions 'partition' and 'window*'

- definitions/npm/react-router-dom_v4.x.x/flow_v0.53.x-/react-router-dom_v4.x.x.js
since `history` version 4.0.0-1 not only true but also false is allowed as a parameter for `block()`
see release note https://github.com/ReactTraining/history/blob/master/CHANGES.md#v400-1
therefore it is also allowed as the message parameter for the Prompt Component
> correct react routers Prompt component type

- definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/jest_v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/test_jest-v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
This PR adds definitions for jest v22. I did not found any relevant changes of the [release to the definition](https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-2200), so I blatantly  copied the jest 21 definition.
> Add definitions for jest v22.x.x

- definitions/npm/reselect_v3.x.x/flow_v0.34.x-v0.46.x/reselect_v3.x.x.js
- definitions/npm/reselect_v3.x.x/flow_v0.47.x-/reselect_v3.x.x.js
fix #824 
using a callable object type that doesn't have any other props on it is pointless and sometimes flow complains that an argument to one of my functions, which is supposed to be a `Selector`, should be an object.
> fix problems caused by callable object type in reselect

- definitions/npm/yamljs_v0.x.x/flow_v0.28.0-/yamljs_v0.x.x.js
Using "load" is a very common use-case and at the very least is needed in here to stop compile errors.
> Add load method to yamljs

- definitions/npm/material-ui_v1.x.x/flow_v0.61.x-/material-ui_v1.x.x.js
The original types were adopted from an older version of MUI. Since they removed Flow from the source, some type defs have also changed. This updates those changes.
> Fix incorrect MUI definitions

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
From the [documentation](https://github.com/NodeRedis/node_redis/tree/009479537eb920d2c34045026a55d31febd1edd7):
> Note that the API is entirely asynchronous. To get data back from the server, you'll need to use a callback.
Demonstration:
```js
'use strict';
const client = redis.createClient({
host: '127.0.0.1',
port: 6379
});
client.on('error', (error) => {
process.exit(1);
});
client.lpush('key', 'value', (error, listLength) => {
console.log(`1. error: ${error}`);
console.log(`1. listLength: ${listLength}`);
});
client.lpush('key', (error, listLength) => {
console.log(`2. error: ${error}`);
console.log(`2. listLength: ${listLength}`);
});
```
The code above outputs the following:
```
1. error: null
1. listLength: 1
2. error: …
```
> Fix redis' lpush() type definition

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_list.js
Although undocumented, `R.indexOf` accepts `null` and `undefined` as search terms. It is actually useful to check for a void type inside an array, so I think loosening the definition in this case makes sense.
@LoganBarnett
> R.indexOf accepts void type.

- definitions/npm/redux-devtools-extension_v2.x.x/flow_v0.47.x-/redux-devtools-extension_v2.x.x.js
- definitions/npm/redux-devtools-extension_v2.x.x/test_redux-devtools-extension_v2.x.x.js
`devToolsEnhancer`'s options argument is optional. See here for reference: https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm
> Fix redux-devtools-extension_v2.x.x.js

- definitions/npm/bson_v1.x.x/flow_v0.50.x-/bson_v1.x.x.js
- definitions/npm/bson_v1.x.x/test_bson-v1.js
Add the BSON function as a default export (as suggested in [this advice](https://github.com/facebook/flow/issues/2840#issuecomment-293413293)).
> Add missing default export for bson

- definitions/npm/react-test-renderer_v16.x.x/flow_v0.53.x-/react-test-renderer_v16.x.x.js
- definitions/npm/react-test-renderer_v16.x.x/test_react-test-renderer-v16.x.x.js
Type definitions for react-test-renderer v16.x.x
I ported it from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-test-renderer/index.d.ts
> React-test-renderer definitions added.

- definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
`size` function allows argument to be `string`: https://lodash.com/docs/4.17.4#size
> Fix size function arguments

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
- The second argument must be a string (it used to be `any`)
- There is an option third argument which is a callback invoked when Redis is done saving the provided data
Example:
```js
const client = redis.createClient({ host: '127.0.0.1', port: 6379 });
client.set('some-key', 'Some value!', (error) => {
console.log('Operation terminated!');
console.log('Error?', error);
});
// Outputs:
// Operation terminated!
// Error? null
```
> Fix type of redisClient.set()

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
The second argument is expected to be a string (it used to be `any`).
> Enhance the type of redisClient.lpush()

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
Demonstration:
```js
const client = redis.createClient({ host: '127.0.0.1', port: 6379 });
client.set('key1', 'one', (error) => {
if (error !== null) {
return;
}
client.set('key2', 'two', (error) => {
if (error !== null) {
return;
}
client.mget(['key1', 'key2', 'unexisting-key'], console.log); // outputs "null [ 'one', 'two', null ]"
});
});
```
Official reference: https://redis.io/commands/mget
> Add redisClient.mget() type for Redis

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
Demonstration:
```js
const client = redis.createClient({ host: '127.0.0.1', port: 6379 });
client.mset(['key1', 'value1', 'key2', 'value2'], (error) => {
console.log('Done. Error?', error); // Outputs "Done. Error? null"
client.get('key1', console.log); // Outputs "null 'value1'"
client.get('key2', console.log);  // Outputs "null 'value2'"
});
```
Official reference: https://redis.io/commands/mset
> Add redisClient.mset() type for Redis

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
Demonstration:
```js
const client = redis.createClient();
client.set('foo', 1, (error) => {
if (error !== null) {
return;
}
console.log(client.get('foo')); // outputs "true"
client.get('foo', (error, value) => {
console.log(error, value, typeof(value)); // outputs "null '1' 'string'"
});
});
```
> Fix the redis.get() type

- definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.55.x-/test_lodash-v4.x.x.js
This fixes part of the issue of #1099, making `_.difference`, `_.differenceBy`, and `_.differenceWith` accept `$ReadOnlyArray`.
Because `Array<T> <: $ReadOnlyArray<T>`, this allows immutable arrays to be used in non-mutating lodash functions.
> [lodash] Update difference* methods to accept $ReadOnlyArray<T>

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
Demonstration:
```js
const client = redis.createClient();
client.set('foo', 'bar', (error) => {
if (error) {
return;
}
client.flushall((error) => {
if (error) {
return;
}
client.get('foo', (error, value) => {
if (error) {
return;
}
console.log(value); // Outputs "null"
});
});
});
```
Reference: https://redis.io/commands/flushall
> Add the type for redis.flushall()

- definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-withLatestFrom
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-combineLatest
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-combineLatest
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-zipProto
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-zip
These operators receive a projection function as the last argument, and it is optional.
Under the previous signature, It's not optional in case of 2 or more Observables are given as arguments.
Actual behavior is described in document of `withLatestFrom`:
> Projection function for combining values together. Receives all values in order of …
> Rxjs fix signatures(withLatestFrom, combineLatest, zip)

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
`redisClient.del()` can be used in two ways:
```js
redisClient.del('key1', 'key2', 'key3', optionalCallback);
```
and
```js
redisClient.del(['key1', 'key2', 'key3'], optionalCallback);
```
The way it is currently typed allows the first form only, but doesn't allow the optional callback. I could not think of a way to type it so it would allow both forms while providing decent safety.
I decided to update the current type definition so it allows the second form, since I think it is the strictest and therefore the safest one. With these changes, we won't be able to use the first form anymore but we will be able to use the optional callback, which is something much more important in my opinion.
*Please note that suggestions are definitely welcome!*
Demonstration:
```js
const redis = …
```
> Update the type for redis.del()

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- add `ttl(key, cb)` method https://redis.io/commands/ttl
- add `setex(key, timeout, value, cb)` method https://redis.io/commands/setex
> redis_v2 .x.x - add ttl and setex definitions

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
`seconds` in `SETEX key seconds value` is expected to be a number and not a string.
See https://redis.io/commands/setex
In `setex('my-key', '5', 'my-value')`, the Redis client for JavaScript will apparently parse `5` as a number, but allowing both string and number for the `seconds` argument may not be the best thing to do if we want to limit side-effects/unexpected behaviors through using strict types.
> Fix type of redis.setex

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
Demonstration:
```js
'use strict';
const client = redis.createClient();
const returned = client.lrange('key', 0, 5, (error, entries) => {
console.log('error', error);
console.log('entries', entries);
});
console.log('returned', returned);
```
Output:
```
returned false
error null
entries []
```
> Fix the type for redis.lrange()

- definitions/npm/selenium-webdriver_v3.x.x/flow_v0.28.x-/selenium-webdriver_v3.x.x.js
[The WebElementPromise definition](https://github.com/SeleniumHQ/selenium/blob/e79a6e7d83d10c2308761c06977337744c825974/javascript/node/selenium-webdriver/lib/webdriver.js#L2184) extends WebElement but also provides the same interfaces as a Promise<WebElement>.
getId() returns a Promise<string> [according to the documentation](https://github.com/SeleniumHQ/selenium/blob/e79a6e7d83d10c2308761c06977337744c825974/javascript/node/selenium-webdriver/lib/webdriver.js#L1808)
I've also added some types from selenium-webdriver/remote
> Define WebElementPromise, fix getId, and add selenium-webdriver/remote

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
Reference: https://redis.io/commands/llen
Demonstration:
```js
'use strict';
const client = redis.createClient();
const returned = client.llen('key', (error, length) => {
console.log('error', error);
console.log('length', length);
});
console.log('returned', returned);
```
Outputs
```
returned false
error null
length 0
```
> Add type for redis.llen()

- definitions/npm/temp_v0.8.x/flow_v0.58.x-/temp_v0.8.x.js
Because the current return type is declared as `void`, Flow complains
when an `async` function is used in the callback because it returns a
`Promise`.
> [temp] Change return type of callback to mixed for async functions.

- definitions/npm/react-helmet_v5.x.x/flow_v0.53.x-/react-helmet_v5.x.x.js
- definitions/npm/react-helmet_v5.x.x/test_react-helmet.js
`react-helmet` supports the static method `renderStatic` as alias for `rewind` on the `Helmet` object. This is documented in their v5 release notes (https://github.com/nfl/react-helmet/releases/tag/5.0.0) and is used as the new default in their documentation as well (https://github.com/nfl/react-helmet).
The Flow definition, however, did not include this static method.
- Added `renderStatic` as a static method on the `Helmet` object
- Updated tests; all tests that were previously only run on `Helmet.rewind()` are now run on both `Helmet.rewind()` and `Helmet.renderStatic()`
> Add renderStatic method to react-helmet-v5 lib def + update tests

- definitions/npm/nock_v9.x.x/flow_v0.31.x-/nock_v9.x.x.js
Nock will match a JSON array:
```javascript
nock("http://example.com").post("/foo", [{ some: "thing" }, {some: "thing else"}]);
```
However, the type for the second parameter is currently limited to `string | RegExp | Object | (Object => boolean)`, so this isn't being allowed by Flow.
> Nock: Allow array for matching request body

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
There were some pretty low quality method definitions for `redis` in here, hopefully mainly because the node `redis` package doesn't document many commands itself, and defers to the official Redis documentation.
Primarily, someone mistakenly thought that a number of methods return results.  As the `redis` package docs say, "Note that the API is entirely asynchronous. To get data back from the server, you’ll need to use a callback."
The `hgetall` method def also had an extra argument that shouldn't be there.
Although I'm pretty sure no methods of `RedisClient` require a callback, I marked the callbacks for getter-type methods as required since forgetting to include a callback would almost certainly be a mistake.
> fix numerous faulty definitions for redis

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
Argh, I didn't notice the section in the docs about how the client's `hgetall` builds an object out of the returned key-value pair array
> fix(redis): fix hgetall result type

- definitions/npm/express_v4.16.x/flow_v0.32.x-/express_v4.16.x.js
- definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
This is a temporary fix for express typedefs to a known issue when declaring a class with overloaded methods (see more info here: https://github.com/facebook/flow/issues/4198). 
Since this issue has no fix in sight and causes coverage to fail reaching 100%, perhaps this seems an acceptable workaround?
> fix(express): add optional Server return to listen method

- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
Adding `hostNodes` method to enzyme v3 `ReactWrapper` and `ShallowWrapper`.
- https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/hostNodes.md
- https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/hostNodes.md
> fix(enzyme): add hostNodes to wrappers

- definitions/npm/express_v4.16.x/flow_v0.32.x-/express_v4.16.x.js
- definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
Using `any` will effectively disable the type checker anywhere you use the `req.body` property, which is dangerous. By declaring it as a `mixed` type, it allows you to use it, but you'll have to make sure that any assumptions you make about its contents are checked first, which is the way to go.
> Replace `any` by `mixed` in express_v4.x.x.js

- definitions/npm/react-custom-scrollbars_v4.2.x/flow_v0.54.x-/react-custom-scrollbars_v4.2.x.js
- definitions/npm/react-custom-scrollbars_v4.2.x/test_react-custom-scrollbars_v4.2.x.js
`autoHeightMin` and `autoHeightMax` now accept both `number` and `string` values, to reflect the actual library definitions (https://github.com/malte-wessel/react-custom-scrollbars/blob/b353cc4956d6154d6a100f34c3a6202c75434186/src/Scrollbars/index.js#L617-L624).
> Update Props definitions for react-custom-scrollbars to reflect the library's definitions more closely

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
Original motivation: https://github.com/flowtype/flow-typed/pull/1262#issuecomment-331303944
Initially, I've just copypasted `lodash/*` module declarations, but found that `lodash` and `lodash/fp` exports are actually different :C. So all new `lodash/fp/*` module declarations were generated based on `Lodash` class defined in `lodash/fp` module export. Also, I've reworked `lodash/fp` tests using per-file imports.
> Generate lodash/fp per file exports

- definitions/npm/react-relay_v1.x.x/flow_v0.47.x-/react-relay_v1.x.x.js
Fix `void` typo introduced in #1796
> Fix `void` typo

- definitions/npm/chai_v4.x.x/flow_v0.25.0-/chai_v4.x.x.js
`.gt`, `.greaterThan`, `.lt`, `.lessThan`
> fix(chai_v4.x.x): add missing aliases to ExpectChain

- definitions/npm/chai_v3.5.x/flow_v0.25.0-/chai_v3.5.x.js
`.gt`, `.greaterThan`, `.lt`, and `.lessThan`
> fix(chai_v3.5.x.x): add missing aliases to ExpectChain

- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
Just like String.prototype.replace, Ramda's replace can take either a string or a function that returns a string as the second argument.
Example:
```js
import { toLower, replace, compose } from 'ramda';
// point-free version
const camelize = compose(
replace(/_(\w)/g, (_, x) => x.toUpperCase()),
toLower,
);
// vanillajs version
const camelize2 = s => s.toLowerCase().replace(/_(\w)/g, (_, x) => x.toUpperCase())
const input = 'MY_UPPERCASE_STRING';
console.log(
camelize(input), // => myUpperCaseString
camelize2(input), // => myUpperCaseString
)
```
> Ramda: allows R.replace's 2nd argument to be a function

- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
Added startsWith function as it was missing from the type definition. Here is the documentation.
Here is the reference within the ramda docs
http://ramdajs.com/docs/#startsWith
Here is the actual implementation within the Ramda Library
https://github.com/ramda/ramda/blob/v0.25.0/source/startsWith.js
> Add Ramda startsWith function

- definitions/npm/enzyme_v2.3.x/flow_v0.25.x-v0.27.x/enzyme_v2.3.x.js
- definitions/npm/enzyme_v2.3.x/flow_v0.28.x-v0.52.x/enzyme_v2.3.x.js
- definitions/npm/enzyme_v2.3.x/flow_v0.53.x-/enzyme_v2.3.x.js
- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
Hi,
although the [documentation](http://airbnb.io/enzyme/docs/api/ShallowWrapper/debug.html) does not showcase it the `debug` method actually accept an [optional `options` parameter](https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/ShallowWrapper.js#L1141).
This is causing errors in libs like [enzyme-matchers](https://github.com/FormidableLabs/enzyme-matchers/blob/master/packages/enzyme-matchers/src/assertions/toMatchElement.js#L26-L27).
```
Error: node_modules/enzyme-matchers/lib/assertions/toMatchElement.js.flow:27
27:   const expected = expectedWrapper.debug(options);
^^^^^^^ unused function argument
56:     debug(): string;
^^^^^^^^^^^^^^^ function type expects no arguments. See lib: flow-typed/npm/enzyme_v2.3.x.js:56
```
> Fix enzyme debug method optional parameter

- definitions/npm/helmet_v3.x.x/flow_v0.38.x-/helmet_v3.x.x.js
All these options are optional. The [helmet.hsts](https://github.com/helmetjs/helmet/blob/master/index.js#L62) function just exports the [hsts module](https://github.com/helmetjs/hsts/blob/master/index.js), which treats all options as optional.
> Make options optional in helmet definition

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
This indicates that the input is not mutated.
> Update lodash keyBy/indexBy types to take $ReadOnlyArray

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
This enables the use case of `_.includes("string")(objectWithStringValues)`
> Reorder lodash/fp _.includes() type definitions

- definitions/npm/prosemirror-model_v1.x.x/flow_v0.59.x-/prosemirror-model_v1.x.x.js
Change `DOMOutputSpec` type so that it's more exact and also allows valid values that previous definition did not supported.
Here is the link to the verbal definition of this type http://prosemirror.net/docs/ref/#model.DOMOutputSpec
> Update DOMOutputSpec to match prosemirror API

- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/test_enzyme-v3.x.js
The enzyme_v3 libdef is missing some changes that happened after enzyme upgraded from v2 -> v3.
To quote the migration guide of enzyme:
> With shallow, .getNode() should be replaced with getElement()
> With mount, .getNode() should not be used. .instance() does what it used to.
This PR implements the following:
* `shallow()`
* `getNode()` was replaced by `getElement()`
* `getNodes()` was replaced by `getElements()`
* `mount()`
* `getNode()` was removed
* `getNodes()` was removed
Sources:
[The original commit with initial changes](https://github.com/airbnb/enzyme/commit/568ce8961ecbc55f26359cbfca35ea0300f4cb9f#diff-00a0c52d2a0eac5ec0025c1d32767a95L174)
[The current source-code printing errors for the removed methods](https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/ReactWrap …
> Remove from enzyme_v3 getNodes() and define alternatives where applicable

- definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
We just released 1.0, which included a couple of small API changes from our beta release which was previously on here. There is no reason for anyone to continue to use the beta release and so v1.x.x still applies to the version. Additionally, we formatted the libdef using prettier
> Update react-navigation libdef

- cli/src/commands/install.js
* fixes #801 (it wasn't obvious that the problem may missing libdefs *for the given flow version*).
* brings message in line with elsewhere in same file:
https://github.com/flowtype/flow-typed/blob/41bf41381b9b520e29804ad167145d268e3ff795/cli/src/commands/install.js#L383
> Improves error message when libdef not found for flow version

- cli/src/lib/npm/__tests__/npmLibDefs-test.js
- definitions/npm/react-i18next_v7.x.x/flow_v0.53.x-/react-i18next_v7.x.x.js
- definitions/npm/react-i18next_v7.x.x/test_react-i18next_v7.x.x.js
Mostly, this is just copying over the v6 files to v7 for react-i18next. The only breaking change in that release was to, by default, not render a parent tag around the output of the Trans component. Since the parent prop was being set to a default before, the types didn't change any.
A couple of minor updates were added that I modified the types to handle as well:
1. Add function namespace argument to translate HOC (https://github.com/i18next/react-i18next/commit/28a841b7598855a9049d6d07dbd6d10467b9a5a8)
2. Add usePureComponent to TranslateOptions (https://github.com/i18next/react-i18next/commit/39e9468bd4a716757564176257958c088fa9c22c)
> Copy v6 react-i18next to v7

- cli/src/commands/__tests__/install-test.js
- cli/src/commands/create-stub.js
- cli/src/commands/install.js
* Adds `-rootDir` as an argument for install and create-stub for projects where `.flowconfig` is in a subdirectory relative to `node_modules`
> flowtype/flow-typed#1760 Add root directory option to CLI

- definitions/npm/prop-types_v15.x.x/flow_v0.41.x-/prop-types_v15.x.x.js
Update flow type definitions to include Symbol, so flow is able to recognize PropTypes.symbol.
> Symbol for prop-type definitions

- definitions/npm/react-dropzone_v4.x.x/flow_v0.53.x-/react-dropzone_v4.x.x.js
- definitions/npm/react-dropzone_v4.x.x/test_react-dropzone_v4.x.x.js
I improve react-dropzone definition for the following two points :)
First, react-dropzone has been added a `preview` field to `File` object.
FYI: 
* https://github.com/react-dropzone/react-dropzone/blob/v4.2.8/src/index.js#L165
Second, react-dropzone has a **public** instance method named `open` to invoke programmatically from ref.
FYI:
* https://react-dropzone.js.org/#opening-file-dialog-programmatically
* https://github.com/react-dropzone/react-dropzone/blob/v4.2.8/src/index.js#L265-L274
> Improve react-dropzone definition

- definitions/npm/firebase_v4.x.x/flow_v0.34.x-/firebase_v4.x.x.js
- definitions/npm/firebase_v4.x.x/flow_v0.34.x-/test_firebase.js
Hi, first PR here. And thanks for all previous work!
[firebase.auth().setPersistence](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#setPersistence) was missing in the firebase_v4.x.x libdef. But it's quite easy to add. So instead of opening an issue first I decided to implement it and send a PR. Hope that's okey!
Tests are added and passing.
Have a nice day!
> libdef firebase: Add auth().setPersistence

- definitions/npm/material-ui_v1.x.x/flow_v0.61.x-/material-ui_v1.x.x.js
There have been some API changes in the material-ui 1.x branch: https://material-ui-next.com/
This PR is not a comprehensive set of updates to bring all of the components' types up to date. It only updates a few specific props on some components.
> Update material-ui_v1 types

- definitions/npm/nano-md5_v1.x.x/flow_v0.65.x-/nano-md5_v1.x.x.js
- definitions/npm/nano-md5_v1.x.x/test_nano-md5_v1.x.x.js
Link to library on Github: https://github.com/Holixus/nano-md5
>  Add nano-md5_v1.x.x

- definitions/npm/query-string_v5.1.x/flow_v0.32.x-/query-string_v5.1.x.js
- definitions/npm/query-string_v5.1.x/test_query-string_v5.1.x.js
Same as 5.0.x, but they added `parseUrl`
> Add query-string_v5.1.x definitions

- definitions/npm/ramda_v0.x.x/flow_v0.49.x-v0.61.x/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.49.x-v0.61.x/test_ramda_v0.x.x_object.js
@LoganBarnett 
Per [the docs](http://ramdajs.com/docs/#pathOr). Also refactors the signature using the pattern
```
declare type Foo = ...
declare var foo = Foo
```
per discussion in #1615.
Also, tries out a different spacing structure to better illustrate the nesting of intersected functions, for better reading. I'd really like your opinion on this one, hopefully we could standardize. I like what you started with `Reduce`, and it's impossible for me to keep track of the nested parens.
> Ramda#pathOr accepts numbers for path.

- cli/src/commands/__tests__/runTests-test.js
From the release notes in version 66: `Error message redesign to help you better debug typing issues in your programs.`
> Fix failing regression spec

- definitions/npm/lodash_v4.x.x/flow_v0.55.x-v0.62.x/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
For flow 55.x and over, the lodash typedefs are using $Compose
and $ComposeReverse but it was overrriden by a member type.
This commit actually use function overloading to support both
$Compose, $ComposeReverse, and lodash array variant.
> libdef lodash: Fix flow, flowRight, pipe, and Compose

- definitions/npm/meow_v4.x.x/flow_v0.54.x-/meow_v4.x.x.js
Now that the exported function has two different signatures, `Options` should always be the config object.
> fix Options type for meow_v4

- cli/src/commands/__tests__/runTests-test.js
- definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
The component Header in `react-navigation` has a static HEIGHT property that wasn't in the flow definition.
> react-navigation_v1.x.x: add Header.HEIGHT property

- definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/jest_v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/test_jest-v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
Jest 22.0.5 adds support for using functions and classes as test names (https://github.com/facebook/jest/pull/5154) - https://github.com/facebook/jest/blob/master/CHANGELOG.md#features-6 
This PR adds that to the Jest libdef for v22.x.x
> Add Jest support for using class and function as test name in describe() and test()

- definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
https://github.com/react-navigation/react-navigation/blob/2bb91a6740e2f1ade012906dc03c972ba6375cc3/src/NavigationActions.js#L24
`init` do not required to pass `payload`
> [react-navigation] fix typespec of init function on react-navigation

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
- definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js
Reference: https://redis.io/commands/lrem
Demo:
```js
'use strict';
const client = redis.createClient({
host: '127.0.0.1',
port: 6379
});
const listKey = 'my-list';
client.lpush(listKey, 'test', (error) => {
if (error) {
return;
}
client.lpush(listKey, 'test', (error) => {
if (error) {
return;
}
client.lrem(listKey, 1, 'test', (error, count) => {
if (error) {
return;
}
console.log(count, typeof(count)); // Output "1 'number'"
});
});
});
```
> Redis: fix the type definition of lrem()

- definitions/npm/react-highlight-words_v0.11.x/flow_v0.53.x-/react-highlight-words_v0.11.x.js
- definitions/npm/react-highlight-words_v0.11.x/flow_v0.53.x-/test_react-highlight-words_v0.11.x.js
This might work with earlier versions too, but changelog does not contain info about breaking changes: https://github.com/bvaughn/react-highlight-words
> update react-highlight-words libdefs

- definitions/npm/react-intl-with-data-message-id_v2.x.x/flow_v0.25.x-v0.52.x/react-intl-with-data-message-id_v2.x.x.js
- definitions/npm/react-intl-with-data-message-id_v2.x.x/flow_v0.25.x-v0.52.x/test_react-intl-with-data-message-id_v2.x.x.js
- definitions/npm/react-intl-with-data-message-id_v2.x.x/flow_v0.53.x-v0.56.x/react-intl-with-data-message-id_v2.x.x.js
- definitions/npm/react-intl-with-data-message-id_v2.x.x/flow_v0.53.x-v0.56.x/test_react-intl-with-data-message-id_v2.x.x.js
- definitions/npm/react-intl-with-data-message-id_v2.x.x/flow_v0.57.x-/react-intl-with-data-message-id_v2.x.x.js
- definitions/npm/react-intl-with-data-message-id_v2.x.x/flow_v0.57.x-/test_react-intl-with-data-message-id_v2.x.x.js
Please, we are using react intl but we need to have `data-message-id` in the rendered `HTML` and we want to use types from `react-intl`.
I wanted to introduce change in `react-intl` but my issue is opened without attention for few months.
https://github.com/yahoo/react-intl/issues/1077
> Add type definitions for react-intl-with-message-id_v2.x.x

- definitions/npm/discord.js_v11.2.x/flow_v0.34.x-/discord.js_v11.2.x.js
- definitions/npm/discord.js_v11.2.x/test_discord.js_v11.2.js
Quite a few changes between v11.1.x and v11.2.x. I started with a copy of the v11.1.x libdef and then updated it to match the TypeScript definition that shipped with v11.2.0.
For reference, here are the changes to the TypeScript definition between v11.1.0 and v11.2.0: <https://github.com/discordjs/discord.js-typings/compare/b500eb2...697fc93>
> Add discord.js v11.2.x libdef

- definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
- `back` action doesn't require `payload`. (similar to https://github.com/flowtype/flow-typed/pull/1880)
- `SafeAreaView` doesn't require `children`.
-  Add `lazy` and `removeClippedSubviews` for TabNavigator. (see https://github.com/react-navigation/react-navigation/pull/3538)
> [react-navigation] Small fixes on flow type

- definitions/npm/express_v4.16.x/flow_v0.32.x-/express_v4.16.x.js
- definitions/npm/express_v4.16.x/test_express_v4.16.x.js
Updated the express_v4.16.x type definitions to include the urlencoded
middleware added in express v4.16.
> Add urlencoded Middleware to Express

- definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
The injected type parameter for navigation props was too inspecific and has been corrected.
Thanks!
> [react-navigation] Fix injected type parameter to navigation props 

- definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
As seen here: https://github.com/react-navigation/react-navigation/issues/360#issuecomment-296690849, we need to be able to pass `null` to turn off logging.
> Allow passing null to onNavigationStateChange prop

- cli/src/lib/git.js
Only compare to parent, not grand parent. Not sure why it's previously been ~2.
You can try `git diff HEAD~2 --name-only` and `git diff HEAD~1 --name-only` in master to see that the first one actually returns names for two last merged libdefs instead of one.
Noticed this behaviour here: https://github.com/flowtype/flow-typed/pull/1919 See the travis output where unrelated libdefs fails: https://travis-ci.org/flowtype/flow-typed/jobs/350025576
> Only take the last commit to diff

- cli/src/commands/runTests.js
Fixes #1921, at least temporarily.
> Temporary test runner workaround for broken v0.67 flow build.

- definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/react-bootstrap_v0.32.x.js
- definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/test_react-bootstrap_v0.32.x.js
Better types for inputRefs. based on https://flow.org/en/docs/react/types/#toc-react-ref and https://flow.org/en/docs/react/types/#toc-react-elementref
Pointed out by @dperetti here: https://github.com/flowtype/flow-typed/pull/1889#issuecomment-370586750
fixes this: https://github.com/flowtype/flow-typed/issues/1917
> fix inputRef type annotations for react-bootstrap

- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_object.js
[Review: @LoganBarnett ]
There were a couple tests that were breaking for some versions of flow, which are now fixed. Key changes:
- `omit` tests were rewritten to be more straightforward. The currying isn't always supported in all versions of flow, and I kind of don't care to fix the tests to make it so.
- `propOr` should not use `$Keys` for the prop input, since it shouldn't require that the prop exist on the object; that's the point of `propOr`.
This was done with minimal effort and not more restructuring of the tests, that will come later. I just want the build to work. 😀
> Fix broken Ramda tests.

- CONTRIBUTING.md
- cli/src/commands/runTests.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_object.js
- definitions/tdd_framework.js
Based on #1842. Adds `describe` and `it` as building blocks to test to allow for more familiar TDD test writing, reducing scope, and being more descriptive. Simple enough solution. I'm not wedded to it, but I wanted to see if it'd work out, and get people's feedback.
> Add describe and it verbs as TDD building blocks for tests.

- cli/src/commands/runTests.js
Mostly closes #1331, by only mangling the test file name when a collision is going to occur. This probably covers 99% of use cases, and can re-visit the issue if we hit the edge cases.
> Only mangle test file names when a name collision will occur.

- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_functions.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_object.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_relation.js
Fixes already broken unit tests, allow currying for some functions, and adding some missing ramda definitions, including:
> Missing ramda definitions

- definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
Coming from https://github.com/facebook/jest/pull/5751
cc @SimenB
> Jest: type `objectContaining` and peers as if they returned their described types

- definitions/npm/re-reselect_v1.x.x/flow_v0.66.x-/re-reselect_v1.x.x.js
- definitions/npm/re-reselect_v1.x.x/test_re-reselect_1.x.x.js
`re-reselect` is a simple wrapper on top of `reselect` that adds the ability to have multiple caches per-selector when you provide it a cache key. This definition is copied and pasted from the definition for `reselect` and modified to support the additional function required to generate a cache key.
I hope to have followed the contribution guidelines correctly, please let me know if I didn't understand something correctly. A couple of notes regarding the guidelines:
1. There is an `any` value in here that is copied and pasted from reselect's definition. I wasn't quite confident enough to change it to something else.
2. I'd like for this to support more versions, but flow 0.65 and below didn't much care for the parts I added. So, the range for this is defined as `flow_v0.66.x-`.
Thanks and …
> Add type definition for re-reselect

- definitions/npm/@sendgrid/mail_v6.x.x/flow_v0.30.x-/mail_v6.x.x.js
Hello,
Small fix in `@sendgrid/mail_v6.x.x`.
Right result type is **http$ServerResponse**, not **http$ClientRequest**.
Have a nice day.
Regards, 
Dimitri
> Fix - HTTP result type fixed in @sendgrid/mail_v6.x.x definition.

- definitions/npm/redux_v3.x.x/flow_v0.25.x-v0.27.x/redux_v3.x.x.js
- definitions/npm/redux_v3.x.x/flow_v0.28.x-v0.32.x/redux_v3.x.x.js
- definitions/npm/redux_v3.x.x/flow_v0.28.x-v0.32.x/test_applyMiddleware.js
- definitions/npm/redux_v3.x.x/flow_v0.28.x-v0.32.x/test_createStore.js
- definitions/npm/redux_v3.x.x/flow_v0.33.x-v0.54.x/redux_v3.x.x.js
- definitions/npm/redux_v3.x.x/flow_v0.33.x-v0.54.x/test_applyMiddleware.js
- definitions/npm/redux_v3.x.x/flow_v0.33.x-v0.54.x/test_createStore.js
- definitions/npm/redux_v3.x.x/flow_v0.33.x-v0.54.x/test_custom_dispatch.js
- definitions/npm/redux_v3.x.x/flow_v0.55.x-/redux_v3.x.x.js
- definitions/npm/redux_v3.x.x/flow_v0.55.x-/test_applyMiddleware.js
- definitions/npm/redux_v3.x.x/flow_v0.55.x-/test_combineReducers.js
- definitions/npm/redux_v3.x.x/flow_v0.55.x-/test_createStore.js
- definitions/npm/redux_v3.x.x/flow_v0.55.x-/test_custom_dispatch.js
Closes #1397 
The two definitions go hand-in-hand, as `createStore` takes a `Reducer` as a parameter and has side-effects specifically surrounding how that `Reducer` will be called. 
As described in the official [documentation](https://github.com/reactjs/redux/blob/master/docs/api/createStore.md), `createStore`'s `preloadedState` is optional.
`createStore`'s `preloadedState` is optional (possibly `undefined`/`void`), as above, it is sent directly to a `Reducer`, specifically the `reducer` provided in the same `createStore` call. Redux is a small library so this can be verified in a straight-forward fashion by visual code inspection, as follows:
1. `reducer` and `preloadedState` are set as `currentReducer` and `currentState` respectively: …
> Corrected Redux v3.x.x createStore and Reducer definitions

- definitions/npm/knex_v0.13.x/flow_v0.38.x-/knex_v0.13.x.js
- definitions/npm/knex_v0.13.x/test_knex-v0.13.js
```js
'use strict';
const knex = require('knex');
const db = knex({
client: 'mysql',
connection: {
host: '127.0.0.1',
port: 3306,
user: 'root',
password: 'root',
database: 'test-transaction'
}
});
db.transaction((trx) => {
return trx.rollback();
})
.then((...args) => {
console.log('then()', args);
})
.catch((error) => {
console.error('catch()', error);
});
```
Outputs
```
catch() Error: Transaction rejected with non-error: undefined
<stack trace>
```
However, passing an Error object to `trx.rollback()` such as
```js
'use strict';
const knex = require('knex');
const db = knex({
client: 'mysql',
connection: {
host: '127.0.0.1',
port: 3306,
user: 'root',
password: 'root',
database: 'test-transaction'
}
});
db.transaction((trx) => {
return trx.rollback(new Error('Something went wrong'));
}) …
```
> Fix type of Knex$Transaction.rollback

- cli/src/lib/libDefs.js
- cli/src/lib/npm/__tests__/npmLibDefs-test.js
- cli/src/lib/npm/npmLibDefs.js
No longer throws an error when there are non-test files and non-flow-version-range folders for first-level folders, ie: `definitions/npm/alasql_v1.x.x/`.
Also reverts the test file regex to only match and add test files.
> Allow any file type in first level definition folder

- CONTRIBUTING.md
> Clarify that raw React types can be used in libdefs.

- definitions/npm/bee-queue_v1.x.x/flow_v0.25.0-/bee-queue_v1.x.x.js
Hello! I was using flow-typed with bee-queue and I noticed that it didn't have the `ready` function defined, so I added it locally and the problem was fixed.
Thought it might be useful for others to add it on the remote as well!
> Add 'ready' function to bee-queue_v1.x.x

- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_object.js
`values` in Ramda returns all of the values of an object. This is a natural fit for `$Values<T>`, which this PR changes the `values` definition to use.
There is a close cousin of `values` called `valuesIn`. It looks like the definition for `valuesIn` isn't even in the libdefs yet. I'm not terribly familiar with how differently we should type `valuesIn` so I'm leaving that out of this PR and it can be addressed in a future date.
This also begins using the new testing format per #1928.
@AndrewSouthpaw I'd totally forgotten about our discussion on #1534 but I think this is on the right track and not in conflict with anything we've talked about so far. Please correct me if I'm wrong though!
> ramda: use `$Values` to represent the values function

- definitions/npm/chai_v4.x.x/flow_v0.25.0-/chai_v4.x.x.js
Chai allows specify optional `message` parameter for most of it's check functions. Like here: http://www.chaijs.com/api/bdd/#method_equal
This PR adds that option to definitions.
>  Adding optional message parameter to most functions of expect of Chai

- definitions/npm/underscore_v1.x.x/flow_v0.38.x-v0.49.x/test_underscore.js
- definitions/npm/underscore_v1.x.x/flow_v0.38.x-v0.49.x/underscore_v1.x.x.js
- definitions/npm/underscore_v1.x.x/flow_v0.50.x-/test_underscore.js
- definitions/npm/underscore_v1.x.x/flow_v0.50.x-/underscore_v1.x.x.js
There was a definition for `_.times`, but it didn't account for the fact that it can be used to build up an array with the return values of the iteratee. I tried to imitate the surrounding code style as much as possible, happy to make any additional changes as needed!
> Add typing for return type of underscore's _.times

- cli/src/commands/runTests.js
(before running tests)
Fixes #1976
> Allow a .exe extension so binaries are not deleted on windows 

- definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/react-bootstrap_v0.32.x.js
It's not an arbitrary string what it takes in array: https://react-bootstrap.github.io/components/tooltips/#overlays-trigger-props
> react-bootstrap: OverlayTrigger trigger prop takes array of triggers, not any strings

- definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/redux-actions_v2.x.x.js
- definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/test_createAction.js
see: https://github.com/redux-utilities/redux-actions/blob/master/src/createAction.js#L39
and: https://github.com/redux-utilities/redux-actions/issues/93
it's needed when creating reducers like:
```
import { createAction, handleActions } from 'redux-actions';
const addUpload = createAction('UPLOAD_TYPE');
export default handleActions(
{
[addUpload.toString()]: (state, action) => {
const upload = action.payload;
}
})
```
> proper support for toString in redux-actions

- definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/redux-actions_v2.x.x.js
When toString is read-only, this plays better together with "traditional" function types (there toString is read-only too)
> redux-connect toString is read-only

- definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/jest_v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
Fixes regression in Jest libdef tests introduced by #1981, which didn't include that new method in the actual npm libdef. And because those files weren't changed, the jest tests weren't run.
> Fix Jest libdef to include new method #advanceTimersByTime.

- definitions/npm/eventemitter3_v3.x.x/flow_v0.25.x-/eventemitter3_v3.x.x.js
- definitions/npm/eventemitter3_v3.x.x/test_eventemitter3-v3.js
Adds a libdef for eventemitter3 v3.
There were some breaking changes, outlined [here](https://github.com/primus/eventemitter3/releases/tag/3.0.0). You can also look at thet [ts definitions](https://github.com/primus/eventemitter3/blob/master/index.d.ts) for reference.
> Adding libdef for eventemitter3_v3.x.x

- definitions/npm/fluture_v6.x.x/flow_v0.34.x-/fluture_v6.x.x.js
The Fluture class should not pollute the global namespace without a npm prefix. Scoping to the module for now.
> Fluture: Removed global and renamed export to be less confusing

- cli/src/commands/runTests.js
This is handy if you are working on fixing libdefs for some specific flow version and don't want to be bothered about other versions while developing. `numberOfFlowVersions` already covers the main use case which is to run test suite against latest version of Flow though.
note that `?w=1` makes reviewing easier: https://github.com/flowtype/flow-typed/pull/1992/files?w=1
E: reverted last commit and now this contains only refactorings
> Cleanup runTests a bit

- cli/flow-typed/npm/jest_v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/jest_v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
mockName was added to jest mocked functions as of jest v22 but seems to be missing from the flow type definitions.
> Add mockName type to jest mocked functions

- definitions/npm/react-css-modules_v3.x.x/flow_v0.53.x-/react-css-modules_v3.x.x.js
- definitions/npm/react-css-modules_v3.x.x/flow_v0.53.x-/test_react-css-modules-v3.js
Support stateless functional component style in `react-css-modules` and format code.
> Support stateless in react css modules

- definitions/npm/react-apollo_v2.x.x/flow_v0.50.x-/react-apollo_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.50.x-/test_react-apollo_v2.x.x.js
Based on https://github.com/apollographql/react-apollo/pull/1858 `react-apollo` package doesn't want to maintain flow types anymore, so I've decided to migrate them here.
For now I've added one basic test, but honestly there's a lot to test and add missing items (like new `ApolloConsumer` added in v2.1).
> Add react-apollo definitions

- definitions/npm/jasmine_v2.4.x/flow_v0.25.x-/jasmine_v2.4.x.js
- definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x.js
- definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x_pending.js
- definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x_spies.js
This exposes a bit more of Jasmine.
Unfortunately I haven't been able to run tests locally (Windows). Following the instructions in the README is kind of a non-starter because it immediately complains about an `ENOENT` related to the first definition. There's also a `CONTRIBUTING.md` in the definitions that throws a wrench in the works, which I had to locally delete to confirm structure.
I got a lot farther running `run_def_tests.cmd` but I hit a lot of errors, especially `ENOENT: no such file or directory, scandir 'C:\gitrepos\flow-typed\cli\.flow-bins-cache'`.
If anyone can lend advice, I'd much appreciate it, since I'd also like to submit some fixups for `lodash/fp` at some point.
> Jasmine: Add `.and` for spies, `pending`, `DEFAULT_TIMEOUT_INTERVAL`

- definitions/npm/testcafe_v0.x.x/flow_v0.47.x-/testcafe_v0.x.x.js
* Make some parameters declared optional in the API docs optional
* Rationalize a large amount of repeated unions used to initialize selectors
> Improvements to Testcafe types

- definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-v0.52.x/react-router-dom_v4.x.x.js
- definitions/npm/react-router-dom_v4.x.x/flow_v0.53.x-/react-router-dom_v4.x.x.js
When using the `StaticRouter` the `staticContext` is set on the `ContextRouter` (see: https://reacttraining.com/react-router/web/example/static-router). This change reflects that.
> Add staticContext to ContextRouter

- cli/src/commands/install.js
- cli/src/commands/update-cache.js
Allows to specify path to cache directory with cli argument `cacheDir`. Useful for CI tools like travis.
> Set cache directory with arguments of install and update commands

- definitions/npm/styled-components_v2.x.x/flow_v0.53.x-/test_styled-components_native_v2.x.x.js
- definitions/npm/styled-components_v2.x.x/flow_v0.53.x-/test_styled-components_v2.x.x.js
- definitions/npm/styled-components_v3.x.x/flow_v0.57.x-/styled-components_v3.x.x.js
- definitions/npm/styled-components_v3.x.x/flow_v0.57.x-/test_styled-components_native_v3.x.x.js
- definitions/npm/styled-components_v3.x.x/flow_v0.57.x-/test_styled-components_v3.x.x.js
Build on work started by @saadq at https://github.com/flowtype/flow-typed/pull/1814#issuecomment-376326551.
I just added spec adjustments since `withTheme` and `nativeWithTheme` expects passed React components to have a `theme` prop.
> Styled components

- definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/react-redux_v5.x.x.js
Avoiding any `export` declarations means that all declared modules are available as properties on the default export. The version of this libdef before the [revamp](https://github.com/flowtype/flow-typed/pull/1731) didn't have any `export` keywords, presumably for that reason.
Why not use named imports, you say? I have a specific case where I can't use named imports: the new module support in Node.js 9.3 can't handle named imports on commonjs modules. And since I'm not able to use the ESM version of `react-redux` because it relies on a named import from `react` (which doesn't have an ESM version), I have to use the commonjs version.
Regardless: as `react-redux` does indeed have a default export, the libdef should be declared accordingly.
> [react-redux] Add default export

- definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/react-redux_v5.x.x.js
Context in #1934. This PR parameterizes the `MapStateToProps` function on Redux state so that the first parameter to that function doesn't have to be `Object`. This avoids forcing library users to either `any`-cast the Redux state or to do runtime assertions on it.
> [react-redux] Parameterize MapStateToProps on Redux state

- definitions/npm/pg_v7.x.x/flow_v0.28.x-/pg_v7.x.x.js
- definitions/npm/pg_v7.x.x/test_pg_v7.x.x.js
[Support for `connectionTimeoutMillis`](https://github.com/brianc/node-postgres/blob/be57714f164d3d5c8b82f3e39b75b22cc43f4800/CHANGELOG.md#700)
[Support for `statement_timeout`](https://github.com/brianc/node-postgres/pull/1436)
Copied the definition for v6.x.x and added in properties available in v7.x.x
> Added definition for pg@7.x.x

- definitions/npm/apollo-link-http_v1.2.x/flow_v0.56.x-/apollo-link-http_v1.2.x.js
Using type instead of interface removes string | UriFunction errors
Fixes #2026
> Fix FetchOptions in apollo-link-http

- definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/redux-actions_v2.x.x.js
- definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/test_handleActions.js
Closes https://github.com/flowtype/flow-typed/issues/1963
Referred updated redux definitions are at: https://github.com/flowtype/flow-typed/pull/1958
-----
The semantics of the reducer returned by either `handleAction` or `handleActions` are actually different from the semantics of the reducer that are consumed by either `handleAction` or `handleActions`.
Reducers consumed by either `handleAction` or `handleActions` are assumed to be given the actual `State` type, since internally, `redux-actions` will perform the action type matching for us, and will always provide the expected state.
See the following tests:
- https://github.com/redux-utilities/redux-actions/blob/de4e8f13192d306fff9bb3929a140356d557def0/src/__tests__/handleAction-test.js#L45-L51
- …
> Update redux-actions to match updated redux definitions

- definitions/npm/formik_v0.11.x/flow_v0.53.x-/formik_v0.11.x.js
- definitions/npm/formik_v0.11.x/test_formik.js
I think FormikHOC is wrong
we need to type `withFormik` to make this work fine
right now I'm using FormikProps instead
something like this
```
type Values = { a: string }
type Props = {} & FormikProps<Values>
```
> feat(formik): improve formik types

- CONTRIBUTING.md
Since `./run_def_tests.sh` is not working very well to run tests and
validate libdefs locally, I change the documentation to instead run the
command `flow-typed validate-defs definitions && flow-typed run-tests`.
This works like a charm.
> Modify the contributing guidelines testing steps

- definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/react-redux_v5.x.x.js
- definitions/npm/react-redux_v5.x.x/flow_v0.62.0-/test_connect.js
Fixes issue where non-used components does not type check, see https://github.com/flowtype/flow-typed/issues/1946
> Do not require component usage to type check in react-redux

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
lodash compact seems to have gotten fixed at some point since the fp definitions were added, this ports the same fix into fp. Namely: The input array is currently `Array<T>`, but it must be 
`Array<?T>` for an output of `Array<T>`because the whole point of `compact` is to get rid of nil elements.
`unset/dissoc/dissocPath` returns a `boolean` in normal lodash, reflecting the success of the operation. However `fp` does not mutate the input, so instead it returns an `Object` which is a new object resulting from attempting the operation on the input object. This is simply a case of the original `fp` definition writer not noticing that its return type is different from normal lodash.
> lodash/fp: Fix compact, unset, dissoc, dissocPath

- definitions/npm/reselect_v3.x.x/flow_v0.47.x-/reselect_v3.x.x.js
Looks like the file metadata got committed, so this is just cleaning that up
> Reselect: Remove duplicated file metadata

- definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
Before this change, adding `.catch()` to an observable would obscure any
type errors in the return type of the source observable.
FYI @matthewwithanm
> Observable.catch() returns union type

- definitions/npm/react-toggled_v1.x.x/flow_v0.54.1-/react-toggled_v1.x.x.js
- definitions/npm/react-toggled_v1.x.x/flow_v0.54.1-/test_react-toggled_v1.x.x.js
Describe an optional argument for `getTogglerProps`, `getElementTogglerProps`, and `getInputTogglerProps`
> Improve react-toggled libdefs

- definitions/npm/formik_v0.11.x/flow_v0.53.x-/formik_v0.11.x.js
Missing optional parameter `shouldValidate` in [setFieldValue](https://github.com/jaredpalmer/formik/blob/0b8346d302e71515b8cd987e528908003e0145f6/src/Formik.tsx#L97)  and [setFieldTouched](https://github.com/jaredpalmer/formik/blob/0b8346d302e71515b8cd987e528908003e0145f6/src/Formik.tsx#L107)
> Formik: Add missing shouldValidate parameters

- definitions/npm/react-router-native_v4.x.x/flow_v0.53.x-/react-router-native_v4.x.x.js
This PR adds support for the `BackButton` export in `react-router-native`. The current code only supports `AndroidBackButton` which is the legacy export.
See https://github.com/ReactTraining/react-router/blob/master/packages/react-router-native/main.js#L9 for the source code reference
> Support for `BackButton` in react-router-native

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
If case of error, result object doesn't contain `data` property, please see the original TypeScript typings: https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L97
> [react-apollo] Fix Query component typing

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
Using `$ReadOnlyArray` on functions that don't modify the input, as discussed in #1099
> [Lodash] Use $ReadOnlyArray for some/any/every

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
This allows `TVariables` to be used correctly and adds check on the arguments passed to `mutate`. 
This will break backwards compatibility, but I think the effort for proper typing is beyond backwards compatibility, especially in a static type system. Breaking compatibility will surely be annoying, but it won't cause runtime issues. Having insufficient typing might on the other hand cause issues. 
The current solution creates a situation where we have types but not really enforce them, which renderes them useless.
> [react-apollo] Fix TVariables in OperationComponent

- definitions/__util__/tdd_framework.js
- definitions/npm/algoliasearch_v3.x.x/flow_v0.56.x-/algoliasearch_v3.x.x.js
- definitions/npm/algoliasearch_v3.x.x/test_algoliasearch-v3.x.x.js
`algoliasearch` definition doesn't work when it's imported with an `await import()`. This fixes it.
> [algoliasearch] Fix async import() case

- definitions/npm/react-splitter-layout_v3.x.x/flow_v0.53.x-/react-splitter-layout_v3.x.x.js
- definitions/npm/react-splitter-layout_v3.x.x/flow_v0.53.x-/test_splitter-layout.js
- definitions/npm/react-splitter-layout_v3.x.x/test_splitter-layout.js
This is a new libdef to support [react-splitter-layout](https://github.com/zesik/react-splitter-layout).
> Add libdef for react-splitter-layout

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js
Adding an auto callback to sequelize changes the return signature of `transaction` to be whatever the auto callback resolves with.
There may be a slight issue with this implement in that, if you don't explicitly type the return signature of the passed in auto callback, flow can't seem figure out which method signature to use.
i.e.:
```
s.transaction( () => 'a' ).then( (a:string) => {} )
// Flow can't decide whether () => 'a' is transactionOptions or a callback
```
I think this might be a deficiency in flow's union refinement for overloaded methods, although I could be wrong.
Thoughts?
> Update sequelize transaction auto callback method signature

- definitions/npm/react-helmet_v5.x.x/flow_v0.53.x-/react-helmet_v5.x.x.js
- definitions/npm/react-helmet_v5.x.x/test_react-helmet.js
This PR fixes a bug in the annotations to React Helmet, where the `body` and `html` attributes have the same types as e.g. `title` and `meta` components.
> [react-helmet] Fix wrong typing of toComponent on attributes

- definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
From Jest Docs - 
Since Jest 22.1.0+, the jest.spyOn method takes an optional third argument of accessType that can be either 'get' or 'set', which proves to be useful when you want to spy on a getter or a setter, respectively.
This PR adds accessType as optional with values of either "get" or "set"
> Jest 22.X.X - Chore: Update spyOn type to reflect third optional accessType argument

- definitions/npm/react-dnd_v2.x.x/flow_v0.53.x-/react-dnd_v2.x.x.js
We needed this change in our own codebase, we have a stateless function component that is wrapped with recompose `withHandlers` the following flow error would occur:
```
Cannot call DragSource(...) because:
- Either React.StatelessFunctionalComponent [1] is incompatible with statics of React.Component [2] in type argument C.
- Or React.StatelessFunctionalComponent [1] is incompatible with statics of React.Component [3] in type argument C.
- Or a callable signature is missing in statics of React.Component [4] but exists in
React.StatelessFunctionalComponent [5] in type argument C.
```
potentially addresses #1564 ?
> fix react-dnd connector type to mesh well with recompose

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
By exporting and using type arguments it becomes
very easy to use these components with e.g. apollo-codegen
So given a mutation with vars of type `MVars` and result of type `MData` or a query with data `QData` or vars `QVars`, we can annotate like this:
```jsx
<Mutation>
{(update: MutationFunction<MVars>, result: MutationResult<MData>) => { ... }}
</Mutation>
<Query>
{(props: QueryRenderProps <QData, QVars>) => { ... }}
</Query>
```
Needs tests!
> [react-apollo] Improve usability of Query and Mutation components

- CONTRIBUTING.md
> Clarify usage of ES6 syntax for creating modules.

- definitions/npm/throttle-debounce_v1.x.x/flow_v0.25.x-/throttle-debounce_v1.x.x.js
Add generic type definition for ...args, that can be passed to throttle or debounce function callback
> Make throttle-debounce function accept arguments

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
PR #2086 added types for react-apollo's `<Query>` and `<Mutation>` components, but not `<Subscription>`. This PR adds the `<Subscription>` component, and fixes a small typo in the definition of `<Query>`
> add Subscription component to react-apollo defs

- definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
This update should simply get this repo synchronized with the flow types defined in [`react-navigation`](https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js). Most of the changes are from this recently approved pr: https://github.com/react-navigation/react-navigation/pull/4085. This fixes the following:
- The typedef for [`getParam`](https://reactnavigation.org/docs/navigation-prop.html#getparam-get-a-specific-param-value-with-a-fallback) is missing.
- The return type for `withNavigation` is incorrect per the [flow documentation](https://flow.org/en/docs/react/hoc/#toc-injecting-props-with-a-higher-order-component) for injecting props with an HOC. The injected prop should be removed from the returned component's prop types. I'm not sure why this …
> update to latest from react-navigation/1.x

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js
various method argument type defs weren't allowing `null` or `undefined` where doing so is legal and removes an association.
> fix(sequelize): fix association method argument types

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
This fixes invalid flow errors like the following:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/server/collections/Organization.js:68:5
Cannot instantiate BelongsToMany because:
• property createdAt is missing in UsersOrganizationsJoinInitAttributes [1] but exists in object
type [2] in type argument TInitAttributes [3] of type argument Through.
• property updatedAt is missing in UsersOrganizationsJoinInitAttributes [1] but exists in object
type [2] in type argument TInitAttributes [3] of type argument Through.
src/server/collections/Organization.js
58│   createdAt: Date;
59│   updatedAt: Date;
60│
61│   static Users: Association.BelongsToMany<OrganizationAttributes,
62│     OrganizationInitAttributes,
63│     Organization,
64│     UserAttributes,
65│ …
```
> fix(sequelize): fix invalid errors from BelongsToMany association definitions

- definitions/npm/uuid_v3.x.x/flow_v0.32.x-/uuid_v3.x.x.js
- definitions/npm/uuid_v3.x.x/test_uuid_v3.x.x.js
First PR here, sorry if I do something wrong.
Flow is flagging valid uses like the following:
```
const uuidv5 = require('uuid/v5');
// ... using predefined DNS namespace (for domain names)
uuidv5('hello.example.com', uuidv5.DNS); // ⇨ 'fdda765f-fc57-5604-a269-52a7df8164ec'
// ... using predefined URL namespace (for, well, URLs)
uuidv5('http://example.com/hello', uuidv5.URL); // ⇨ '3bbcee75-cecc-5b56-8031-b6641c1ed1f1'
```
I added defs for DNS and URL as well as defs for v3.
> Fixes for uuid: add v3, predefined namespaces

- definitions/npm/formik_v0.11.x/flow_v0.53.x-/formik_v0.11.x.js
- definitions/npm/formik_v0.11.x/test_formik.js
* Correct FormikHandlers to match v0.11.x, rather than the 1.0.0 alpha
* Add missing validateForm to FormikActions
* Add some tests and use describe/it
The types for FormikHandlers looks to be based of the master Typescript typings, which is v1 alpha. Even so, they will need some corrections when we add the v1 flow-typed types. Changed it to match what's actually in v0.11.x (https://github.com/jaredpalmer/formik/blob/v0.11.11/src/formik.tsx)
> Fix problems with Formik types

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
The mutate function returns the mutation result. This PR reflects that.
> [react-apollo] Add explicit return type on mutate function

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
Add type variable defaults to the `Subscription` and `Query` component props.
> [react-apollo] Add defaults to type-variables on Subscription and Query

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
http://redis.js.org/#extras-clientconnected
RedisClient has property `connected` tracking the state of the connection.
> Add missing libdefs `client.connected` to redis_v2.x.x

- definitions/npm/apollo-client_v2.x.x/flow_v0.57.x-/apollo-client_v2.x.x.js
- definitions/npm/apollo-client_v2.x.x/test_apollo-client_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
It seems that since the react-apollo libdef is importing types from apollo-client (which doesn't have types), even if I include this apollo-client libdef in my project, types that react-apollo imports end up getting clobbered to any. Either need to 
1. stop importing those types in react-apollo libdef or 
2. actually use the types added here.
Actually using the types is definitely the endgame, but might be a large effort that could be split to another PR.
> Apollo Client Libdef (also add to react-apollo)

- definitions/npm/react-navigation_v2.x.x/CONTRIBUTING.md
- definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js
- definitions/npm/react-navigation_v2.x.x/test_react-navigation.js
This includes the libdef from current `react-navigation` master (corresponding to `react-navigation@2.0.1`) plus [my PR](https://github.com/react-navigation/react-navigation/pull/4230) on `react-navigation` that fixes up some issues with the 2.0 libdef.
> [react-navigation] Introduce libdef for react-navigation@2.x.x

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
[Documentation](https://github.com/lodash/lodash/wiki/FP-Guide) says:
> `_.differenceWith` has an order of `(c, a, b)`
Indicating that the comparator should be first. I also tested it and confirmed that the actual library uses the order in the documentation.
> [lodash] Fix argument order for lodash/fp/differenceWith

- definitions/npm/reselect_v3.x.x/flow_v0.47.x-/reselect_v3.x.x.js
- definitions/npm/reselect_v3.x.x/test_reselect_3.x.x.js
This PR adds flow typing for the extra fields placed on selectors.
You can find these extra fields here: https://github.com/reduxjs/reselect/blob/master/src/index.js#L81-L83
They are also mentioned in the documentation.  For example: https://github.com/reduxjs/reselect#q-how-do-i-test-a-selector
> [reselect_v3.x.x] add other fields (recomputations, resultFunc, etc.) to selector types

- definitions/npm/react-loadable_v5.x.x/flow_v0.56.0-/react-loadable_v5.x.x.js
The project's documentation describes it as a `boolean`, which is what was implemented, but it's actually a nullable Error.
I've raised https://github.com/jamiebuilds/react-loadable/pull/122 to fix the documentation.
> Fix react-loadable error prop

- definitions/npm/formik_v0.11.x/flow_v0.53.x-/formik_v0.11.x.js
The `handleSubmit` function in formik isn't always going to be attached to `<form onSubmit/>` element. It might be attached to a button (ie. `<button onClick={handleSubmit} />` or some custom component or whatever else. So we can't assume it's always going to be an `HTMLFormElement` in the event object.
@TLadd Any objections to this change? I noticed you made some large changes to this libdef last.
> Minor fix for formik's `handleSubmit` function

- definitions/npm/raven-js_v3.17.x/flow_v0.38.x-/raven-js_v3.17.x.js
- definitions/npm/raven-js_v3.17.x/test_raven-js.js
The options argument to showReportDialog should be optional. As can be seen [here](https://github.com/getsentry/raven-js/blob/master/src/raven.js#L881), raven-js supplies a default if one is not provided. Can also see in the [docs](https://docs.sentry.io/clients/javascript/usage/#user-feedback) that the method is called without supplying an options argument. Typed out the object shape while I was there.
> raven-js: Fix showReportDialog method to have optional options arg

- definitions/npm/koa-bodyparser_v4.x.x/flow_v0.56.x-/koa-bodyparser_v4.x.x.js
- definitions/npm/koa-bodyparser_v4.x.x/flow_v0.56.x-/test_koa-bodyparser_v4.x.x.js
This matches the codebase here better: https://github.com/koajs/bodyparser/blob/master/index.js#L28
> Export koa-bodyparser as a CommonJS module

- definitions/npm/apollo-client_v2.x.x/flow_v0.57.x-/apollo-client_v2.x.x.js
- definitions/npm/apollo-client_v2.x.x/test_apollo-client_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
Add `extract` and `restore` methods
See https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts#L442
@TLadd
> [apollo-client] Add extract and restore methods on ApolloClient

- definitions/npm/react-transition-group_v2.x.x/flow_v0.60.x-/react-transition-group_v2.x.x.js
- definitions/npm/react-transition-group_v2.x.x/test_react-transition-group.js
Looks like flow doesn't work well with interface and types intersections
> [react-transition-group] Replace an interface with an object type

- definitions/npm/styled-components_v3.x.x/flow_v0.57.x-/styled-components_v3.x.x.js
styled-components had issue with getting full flow coverage, specifically with default exported `style`.
https://github.com/styled-components/styled-components/issues/1321
This PR fixed default exported types for it, helping in achieving full coverage.
> fixed type defs for styled components v3

- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js
Fixes #2242 - Ramda tests no longer pass.
Ramda libdef tests haven't been passing due to `startsWith` and `endsWith`.
`CurriedFunction` wasn't allowing the strictness that we needed so the currying is done manually here. Since `startsWith` and `endsWith` have the same type signature, they have been refactored to use the same type signature as well. Both of these functions work with arrays of any kinds of elements as demonstrated [here](https://ramdajs.com/repl/?v=0.25.0#?%2F%2F%20Works%20with%20more%20than%20just%20strings%3A%0AR.startsWith%28%5B1%5D%2C%20%5B1%2C%202%2C%203%5D%29%20%20%20%20%2F%2F%3D%3E%20true
) and [here](https://ramdajs.com/repl/?v=0.25.0#?%2F%2F%20Works%20with%20more%20than%20just%20strings%3A%0AR.endsWith%28%5B3%5D%2C%20%5B1%2C%202%2C%203%5D%29%20%20%20%20%2F%2F%3D%3E% …
> Fix ramda startsWith and endsWith

- definitions/npm/@sendgrid/mail_v6.x.x/flow_v0.30.x-/mail_v6.x.x.js
I needed to use these types inside of my app, so I figured that it would be a good idea to directly update the type definitions in Flow instead only in my own app.
Hope this helps.
> Export more types in @sendgrid/mail

- definitions/npm/jquery_v3.x.x/flow_v0.28.x-/jquery_v3.x.x.js
According to https://github.com/flowtype/flow-typed/issues/2160#issuecomment-386303024
The `data(key: string, _: void): any;` is more specific than `data(key: string, value: any): JQuery`
But flow is using `data(key: string, value: any): JQuery` anyway since it's on top
This commit reverse their positions to allow `data(key: string, _: void): any;` being used for expression like `$el.data("key")`
> Fix function declaration used with `$el.data("key")`

- definitions/npm/react-color_v2.x.x/flow_v0.56.x-/react-color_v2.x.x.js
- definitions/npm/react-color_v2.x.x/flow_v0.56.x-/test_react-color_v2.x.x.js
I used [this](https://github.com/facebook/flow/issues/4759#issuecomment-327713650) as a guidance in writing the Hoc type annotations.
[This](https://github.com/casesandberg/react-color/blob/befb042d425e89d79c24c6611aa5bff9f2ab06a9/src/helpers/color.js#L30-L37) is what is injected by `CustomPicker`
> Add correct typings for CustomPicker HoC

- definitions/npm/socket.io-client_v2.x.x/flow_v0.34.x-/socket.io-client_v2.x.x.js
> socket.io-client: Add missing id definition

- definitions/npm/@storybook/addon-knobs_v3.x.x/flow_all/addon-knobs_v3.x.x.js
- definitions/npm/@storybook/addon-knobs_v3.x.x/test_addon-knobs_v3.x.x.js
I've added definitions for [storybook/addon-kobs](https://github.com/storybooks/storybook/tree/master/addons/knobs) which allows users to enter react component props at runtime in storybook.
I've used `any` as the return type for the `object` method, as internally storybook calls `JSON.parse()` on whatever the user has typed in, and the return type for `JSON.parse()` is `any`.
> Add storybook/addon-knobs definitions

- definitions/npm/idx_v2.x.x/flow_v0.33.x-/idx_v2.x.x.js
- definitions/npm/idx_v2.x.x/test_idx_v2.x.x.js
Used flow_v0.33.x as the minimum version since `$Facebookism$Idx` has existed since 0.30.0: https://github.com/facebook/flow/commit/e07ff300e61edc93f8e3744acfc07a62c648b070
> Add idx libdef

- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js
From an earlier pass of Ramda's libdefs, many functions have a `...rest: Array<void>` at the end of the argument list. This may have been added as a means of accounting for composition with functions like `Array.forEach` which has "extra" arguments like the index and original array being operated on. It could have also been that earlier versions of Flow didn't play nice with spare arguments.
The original motivation isn't that important here. As a community of Ramda libdef consumers, we've run into frequent issues where Flow can't disambiguate which function signature to use because the `...rest: Array<void>` portion causes a conflict. Sometimes it means that we wind up with runtime errors because Flow assumed some bogus parameters we passed were good simply because they satisfied the …
> Ramda: Remove superfluous rest args

- definitions/npm/underscore_v1.x.x/flow_v0.38.x-v0.49.x/underscore_v1.x.x.js
- definitions/npm/underscore_v1.x.x/flow_v0.50.x-/underscore_v1.x.x.js
http://underscorejs.org/#mapObject
shows that the `iteratee` only need to return new value
But the returned value doesn't need to be `Object`
> Fix underscore#mapObject argument type

- definitions/npm/decimal.js-light_v2.4.x/flow_v0.61.0-/decimal.js-light_v2.4.x.js
- definitions/npm/decimal.js-light_v2.4.x/test_decimal.js-light_v2.4.x.js
Copied from 2.3.x, because there were no API changes introduced: https://github.com/MikeMcl/decimal.js-light/compare/v2.3.1...v2.4.1
> decimal.js-light: add v2.4.x libdefs

- definitions/npm/opentracing_v0.14.x/flow_v0.25.x-/opentracing_v0.14.x.js
- definitions/npm/opentracing_v0.14.x/test_opentracing_v0.14.x.js
Adding definitions and tests for `opentracing` v0.14.x. The definitions are based on `.d.ts` files from the package. v0.14.x has been the latest version since [23 Apr 2017](https://github.com/opentracing/opentracing-javascript/commit/eb768cb00c7d52b2b980947733c832e14096ee80).
The source code of the package is at https://github.com/opentracing/opentracing-javascript. I didn't include `private` and `protected` class fields because they are not meant to be used by package consumers.
> Add opentracing v0.14.x definitions

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
The specific thing missing for me was $ReadOnlyArray but this seems more consistent and correct.
> lodash: isString should accept any like other isX methods

- definitions/npm/history_v4.x.x/flow_v0.25.x-/history_v4.x.x.js
'.replace' should have the same annotation as '.push'
> fix history_4.x.x BrowserHistory.replace def

- definitions/npm/socket.io-client_v2.x.x/flow_v0.34.x-/socket.io-client_v2.x.x.js
- definitions/npm/socket.io-client_v2.x.x/test_socket.io-client_v2.x.x.js
Current types are inconsistent with the [docs](https://socket.io/docs/client-api/#with-extraheaders).
> add transportOptions types and test

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
I changed it to be like the other is functions.. I'm guessing it was missed at some point?
Otherwise at least boolean and Class<any> are missing
> lodash: isNaN should accept any like other isX functions

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
Typing an ORM is hard 😕 
The association create method types incorrectly relied on the type of the attributes once created rather than the type of the attributes required to create a model.
There is still a problem with the `belongsToMany` methods: if you try to pass additional options for the `through` table, it complains that the primary key attributes are missing, because it doesn't have a way to omit them from the through table's initial attributes type.  Fixing this would require a breaking change to the flow types...which is an example of why typedefs should be released in their own packages with their own versioning instead of tracking the version of the package here.
> fix(sequelize): fix association create method types

- definitions/npm/papaparse_v4.x.x/flow_v0.39.x-/papaparse_v4.x.x.js
- definitions/npm/papaparse_v4.x.x/test_papaparse_v4.x.x.js
This change makes it possible for the data property of
the PapaParse$UnparseObject interface respect its union typing of
"string | Array<any>"
> Make data field of PapaParse$UnparseObject covariant

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
In general one gets errors when trying to pass `Array<number>` where an `Array<string | number>` is required.  Using `$ReadOnlyArray<string | number>` fixes this problem.
> fix(sequelize): use  wherever element type is a union

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js
Virtually all lodash functions can take `null`/`undefined` for their input collection; for example, `map` will never run its iterator function and simply return an empty array. However, it's not clear how much of this should be allowed by Flow. Allowing nil on absolutely everything may dramatically lower the overall usefulness of the type-checking because even though those _may_ work with nil inputs, it's very often the case that the programmer never _intended_ that as a possibility and would have preferred an error.
Despite that, there's one case which seems extremely useful to allow `null`/`undefined`, which is `get`/`getOr`. Perhaps the primary use of these functions over simply `accessing.things['directly']` is because it avoids `cannot read property "directly" of undefined` errors …
> lodash and lodash/fp: get/getOr accept nil collections

- definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js
- definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/test_react-router-dom.js
Small PR to relax over-strict type checking on router-react-dom.
react-router-dom `<Link>` accepts any user properties and passes them through to the generated `<a>`. Also `<NavLink>` extends `<Link>`. 
for reference 
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md#others
code 
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L75
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L46
> relax react-router-dom Link constraints

- definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
- definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js
Had to convert JestExpectType to an interface to allow method
overloading. Inspired by https://github.com/flowtype/flow-typed/pull/2171
> jest: Add toMatchSnapshot(name: string) signature

- definitions/npm/chalk_v2.x.x/flow_v0.25.x-/chalk_v2.x.x.js
- definitions/npm/chalk_v2.x.x/test_chalk_v2.x.x.js
https://github.com/chalk/chalk/issues/267#issuecomment-396445028
In `chalk@2.x.x`, supportsColor had changed to be an `object`.
> Use supportsColor as object

- definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js
- definitions/npm/react-router_v4.x.x/flow_v0.53.x-/react-router_v4.x.x.js
There was no possibility to use react-router(-dom) with react-transition-group because of the lack of `location` prop in Switch component.
```js
<TransitionGroup component={null}>
<CSSTransition key={location.key} timeout={2000} classNames="fade">
<Switch location={location}>
<Route exact path="/somepath" component={SomeComponent} />
</Switch>
</CSSTransition>
</TransitionGroup>
```
> Add location prop to Switch in react-router & react-router-dom

- definitions/npm/cors_v2.x.x/flow_v0.53.x-/cors_v2.x.x.js
With the change to `declare export default (options?: CorsOptions) => RequestHandler;` (https://github.com/flowtype/flow-typed/pull/2319) a problem with CommonJS appeared.
This code was throwing an error:
```
const cors = require('cors');
cors(corsOptions) // Cannot call cors because a callable signature is missing in module cors [1].
```
Flow was sure, that cors in that case is an object with a default function inside:
Fixed the problem, made sure that the tests are passing.
> cord: fix export style for cors library definition

- definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
In this pull request we fix a bug where the spacing enum `32` was mistakenly left out.
> Add 32 to Spacing type

- experimental/scripts/sync-definitions.js
`experimental/definitions` will now contain libdefs from _both_ `definitions/browser` and `definitions/npm`.
> Copy libdefs from definitions/browser into experimental/definitions

- definitions/npm/react-router_v4.x.x/flow_v0.30.x-v0.52.x/react-router_v4.x.x.js
See the source code:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L19
> [react-router-v4] Add missing Switch.props.location

- definitions/npm/react-router_v4.x.x/flow_v0.63.x-/react-router_v4.x.x.js
See the source code:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L19
This is not the same PR as #2374
> [react-router-v4] Add missing Switch.props.location (take II)

- definitions/npm/papaparse_v4.x.x/flow_v0.39.x-/papaparse_v4.x.x.js
- definitions/npm/papaparse_v4.x.x/test_papaparse_v4.x.x.js
Fix to UnparseConfig so we can set individual properties, without having to specify every property
> Allow nullable papaparse UnparseConfig properties #2386 

- definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js
- definitions/npm/mongoose_v4.x.x/test_mongoose-v4.js
Added proper types for aggregate method in mongoose, now it's just Promise<any> so things this for example `Model.aggregate(..).allowDiskUse(true).exec(callback)` doesn't work
> libdef for mongoose add propert aggregate type

- definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/rxjs_v6.x.x.js
Some imports are not declared on the 'rxjs' and 'rxjs/operators' modules, `toArray` is now an operator and has a changed syntax, so i fixed that as well
> Add missing types for importing to rxjs_v6

- definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
- definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js
jest 23 has [4 functions](https://facebook.github.io/jest/docs/en/mock-function-api.html#mockfnmockresolvedvaluevalue) the libdefs were missing. Some of the work for #2264.
> Add types for asynchronous jest mocks

- definitions/npm/react-collapsible_v2.0.x/flow_v0.54.x-/react-collapsible_v2.0.x.js
- definitions/npm/react-collapsible_v2.0.x/test_react-collapsible_v2.0.x.js
Use `React$Component` instead.
https://github.com/flowtype/flow-typed/blob/master/CONTRIBUTING.md#dont-import-types-from-other-libdefs
This is generating erros in other projects.
- https://github.com/facebook/flow/issues/5678
- https://github.com/facebook/flow/issues/6014
> Remove `import { Component } from "react";`

- cli/src/commands/runTests.js
> Ignore 0.63 when running travis builds

- definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js
- definitions/npm/winston_v3.x.x/test_winston_v3.x.x.js
Resolves this issue:
```
Cannot call `winston.format.label` because property `label` is missing in `$winstonFormatSubModule` [1].
```
We can see this is part of winston [in this example](https://github.com/winstonjs/winston/blob/5223ab9264a9e93603ecbbd87b334ae6d047b698/examples/custom-timestamp.js#L5)
> Add label to winston format definition

- definitions/npm/moment_v2.x.x/flow_v0.63.x-/moment_v2.x.x.js
In Momentjs `weekday` and `isoWeekday` can accept strings
https://momentjs.com/docs/#/get-set/day/ and  https://momentjs.com/docs/#/get-set/iso-weekday/
here is my quick fix
> Allow momentjs day and weekday to accept string

- definitions/npm/jasmine_v2.4.x/flow_v0.25.x-/jasmine_v2.4.x.js
Currently, a JasmineSpyType cannot be passed in as a parameter where a function is expected.
> Add generic Function type to Jasmine Spy

- definitions/npm/parse_v1.9.x/flow_v0.30.x-/parse_v1.9.x.js
According to the Parse SDK [docs](http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.ACL.html) the constructor for `Parse.ACL` can be called with no arguments:
> Creates a new ACL. **If no argument is given**, the ACL has no permissions for anyone. If the argument is a Parse.User, the ACL will have read and write permission for only that user. If the argument is any other JSON object, that object will be interpretted as a serialized ACL created with toJSON().
But at the moment the constructor is typed as:
```javascript
declare class $npm$parse$ParseACL {
//...
constructor(arg1: $npm$parse$ParseUser | $npm$parse$ByIdMap): $npm$parse$ParseACL
//...
}
```
Making impossible to call it with no arguments:
```
Cannot call Parse.ACL because:
• Either undefined [1] is incompatible with …
```
> Allow Parse.ACL() constructor without arguments

- definitions/npm/styled-components_v3.x.x/flow_v0.57.x-v0.74.x/styled-components_v3.x.x.js
+ Add `SafeAreaView` to NativeComponentList definitions (`flow_v0.57.x-v0.74.x/styled-components_v3.x.x.js`)
Related to https://github.com/styled-components/styled-components/issues/1424#issuecomment-398804828
> Update styled-components-v3.x.x definitions

- definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js
- definitions/npm/winston_v3.x.x/test_winston_v3.x.x.js
`winston.format` exposes a few more properties we'd like to type, namely:
`colorize` -- [docs ref](https://github.com/winstonjs/winston#colorizing-standard-logging-levels), [source ref](https://github.com/winstonjs/logform/blob/master/colorize.js)
`logstash` -- [source ref](https://github.com/winstonjs/logform/blob/master/logstash.js)
`printf` -- [docs ref](https://github.com/winstonjs/winston#formats), [source ref](https://github.com/winstonjs/logform/blob/master/printf.js)
> [winston_v3.x.x] Add colorize, logstash, printf types to winstonFormatSubModule

- definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
- definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js
Jest has some documented matchers under `expect.not` [0]. They're not in the flow-typed libdefs yet. This adds them.
[0] http://jestjs.io/docs/en/expect.html#expectnotarraycontainingarray
> (jest) Update expect.not.*

- definitions/npm/js-joda_v1.8.x/flow_v0.25.x-/js-joda_v1.8.x.js
Flow does not allow classes that inherit from `Object` to implement `static valueOf(arg)`. Unfortunately, that's what `js-joda` does. It might not be safe, but that's the way it is. Consumers will have to add `$FlowFixMe` around any usage of `valueOf()` in their code for the time being.
> remove type for DayOfWeek.valueOf() to prevent error

- definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/rxjs_v6.x.x.js
A very simple `empty()` definition. I'll be making PRs for more and more creation methods for rx shortly, all as individual PRs to ensure these move forward gradually. cc @radex @tobilen
Helps with #2285
> include the definition for empty()

- definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/react-redux_v5.x.x.js
- definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/test_connect.js
react-redux connect does hoist not react statics as per https://github.com/reduxjs/react-redux/blob/master/src/components/connectAdvanced.js#L288
So I added support for that in typing as I needed it.
After digging, this fixes #830.
Cheers.
> [react-redux] Support static properties hoisting in connect

- definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/rxjs_v6.x.x.js
Adds top level definition for `bindNodeCallback()` creation method for rxjs. 
Follow on PR to #2462 and helps with #2285. 😄
> include the definition for bindNodeCallback()

- definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
function is no longer deprecated according to the update since 2017
https://github.com/facebook/jest/pull/3993/files?short_path=c39fe85#diff-c39fe854e3daabd39ee1401ad74bf8ae
> chore: update mockReturnValue comment

- definitions/npm/directory-tree_v2.x.x/flow_v0.71.x-/directory-tree_v2.x.x.js
- definitions/npm/directory-tree_v2.x.x/test_directory-tree_v2.x.x.js
Use RegExp, not string
[ref](https://www.npmjs.com/package/directory-tree#options).
> [directory-tree_v2.x.x] fix options types error

- definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
In material-ui package Modal element should have optional modalManager prop (it was required).
> fix: material-ui Modal definition

- definitions/npm/metalsmith_v2.x.x/flow_v0.75.x-/metalsmith_v2.x.x.js
File object is not always backed by a file on disk, it can be also created by a plugin; such object typically don't have properties stats and mode.
> metalsmith_v2.x.x: Fix File type to be less strict

- definitions/npm/react-transition-group_v2.x.x/flow_v0.60.x-/react-transition-group_v2.x.x.js
- definitions/npm/react-transition-group_v2.x.x/test_react-transition-group.js
> Fix type of react css-transition children to accept a function of transition status

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
Remove $call where it was used. $call was being used as a workaround for a union
of objects and a function (https://github.com/facebook/flow/issues/1948#issuecomment-338440545)
A sealed object also resolves this issue and removes the deprecation error
> react-apollo: Fix $call deprecated error on flow 0.75-

- definitions/npm/lodash-es_v4.x.x/flow_v0.63.x-/lodash-es_v4.x.x.js
- definitions/npm/lodash-es_v4.x.x/flow_v0.63.x-/test_lodash-es-v4.x.x.js
> fix `lodash-es.get` iface to be consistent to `lodash.get` definitions

- definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
- definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js
Adds typings for the `toHaveStyleRule` matcher from https://github.com/styled-components/jest-styled-components
> Add jest styled components `toHaveStyleRule` typing

- definitions/npm/formik_v0.11.x/flow_v0.59.x-/formik_v0.11.x.js
This makes the formik definition more close to the TS one at their repo.
Also changes `React.*` to use `React$*` since the first does not work correctly because imports insides type definitions do not work correctly.
This also types the `withFormik` hoc correctly, to take into consideration the following:
> Note: If foo does not exist in Props you will get an error! $Diff<{}, { foo: number }> will be an error. To work around this use a union with void, see: $Diff<{}, { foo: number | void }>. An optional prop will not completely remove foo. $Diff<{ foo: number }, { foo?: number }> is { foo?: number } instead of {}.
https://flow.org/en/docs/react/hoc/#toc-injecting-props-with-a-higher-order-component
I have a question tho, I've created a `TypeOrVoid` type helper, but have not exported it, …
> type(formik): improve withFormik hoc type hinting

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
`stopPolling()` does not take an argument. For reference:
https://www.apollographql.com/docs/react/essentials/queries.html#render-prop
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/ObservableQuery.ts#L500
> react-apollo: fix stopPolling()

- definitions/npm/@storybook/addon-knobs_v3.x.x/flow_all/addon-knobs_v3.x.x.js
- definitions/npm/@storybook/addon-knobs_v3.x.x/test_addon-knobs_v3.x.x.js
This Storybook knob exposes the date value using `getTime`/`valueOf` methods, ie. number of seconds from 1970, not a Date object.
The default value gets transformed to a number here: https://github.com/storybooks/storybook/blob/master/addons/knobs/src/index.js#L60
When you change the value using the knob, it gets transformed to a number here: https://github.com/storybooks/storybook/blob/master/addons/knobs/src/components/types/Date/index.js#L17
> Fix the return type of date addon-knobs/date

- definitions/npm/firebase_v5.x.x/flow_v0.34.x-/firebase_v5.x.x.js
This builds on #2308 and adds the following changes:
- Adds the `app.firestore()` function to get the associated Firestore instance for an initialized App.
- Fixes argument types for the callback passed to `onSnapshot()` to allow `QuerySnapshot`.
- Changes the `data` parameter to be typed as `Object` instead of `{}`, allowing access to keys (instead of assuming that data is an empty object).
/cc @meafmira @meafmira
> Improvements to Firebase v5 definitions

- definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
This patch resolves an issue with `@material-ui/core/withWidth/withWidth` which caused the following error:
```
Cannot call `withWidth()` because undefined property `width` [1] is incompatible with enum [2].
src/components/Responsive/index.js:45:16
45| export default withWidth()(Responsive)
^^^^^^^^^^^^^^^^^^^^^^^
References:
flow-typed/npm/@material-ui/core_v1.x.x.js:2513:18
2513|   |}) => <Props: {}>(
^^ [1]
flow-typed/npm/@material-ui/core_v1.x.x.js:2515:50
2515|   ) => React$ComponentType<$Diff<Props, { width: Breakpoint }>>;
^^^^^^^^^^ [2]
```
> Resolve @material-ui/core incompatible prop type

- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
- definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js
We can't really do `reject` here since it's an inversion, and I'm not aware of any special `$Not<T>` just yet.
Currently, you can't do this in Ramda with Flow:
``` javascript
import { filter, map } from 'ramda'
const ns = filter(n => n != null, [1, 2, null])
map(n => n.toString(), ns) // n can be null so you can't do .toString()
```
There's a small concession to make it work: You have to indicate that you actually want to do a refinement. This is because refinement predicates are considered a different type than ordinary predicates.
``` javascript
import { type RefineFilter, filter, map } from 'ramda'
const notNull = (x: mixed): bool %checks  => n !=null
const ns = (filter: RefineFilter)(notNull, [1, 2, null])
map(n => n.toString(), ns) // works
```
> add the ability to refine types from Ramda's filter

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
Pretty much copy/pasta from the Query component, but works for me. 
My first contribution here, but I got everything right.
> react-apollo: expose SubscriptionResult and added tests

- definitions/npm/react-modal_v3.1.x/flow_v0.54.1-/react-modal_v3.1.x.js
- definitions/npm/react-modal_v3.1.x/test_react-modal_v3.1.x.js
This PR makes it possible for `props.onRequestClose()` to receive an `Event` object.
`props.onRequestClose()` will be called by `requestClose()` at [here](https://github.com/reactjs/react-modal/blob/master/src/components/ModalPortal.js#L287) and it will be called by handlers of both `onClick` and `onKeyDown`.
Therefore, `props.onRequestClose()` will receive either `SyntheticMouseEvent` or `SyntheticKeyboardEvent`.
> react-modal: Fix signature of props.onRequestClose

- definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/redux-actions_v2.x.x.js
- definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/test_createAction.js
- definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/test_handleAction.js
- definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/test_handleActions.js
In case [redux-actions](https://github.com/redux-utilities/redux-actions) is used in combination with [redux-thunk](https://github.com/reduxjs/redux-thunk), the `payloadCreator` can return a promise (that will be resolved by redux-thunk).  
This case is currently not supported by the actual `redux-actions` definitions.
This PR updates the return type of the `payloadCreator` to be either a payload object or a promise, which now allows to use `ActionType` to type thunks.
```js
const incrementThunk = createAction('INCREMENT', (x: number) => Promise.resolve(x))
handleAction('INCREMENT', (state, action: ActionType<typeof incrementThunk>) => {
// action.payload will have type `number`
}, {})
```
> Make redux-actions support thunks

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
The `updateQuery` property is a function that accepts a map function as a single argument.
Beware that also the [documentation](https://www.apollographql.com/docs/react/api/react-apollo.html#query-render-prop) is not correct.
> react-apollo: Fix QueryRenderProps updateQuery.

- definitions/npm/query-string_v5.1.x/flow_v0.32.x-/query-string_v5.1.x.js
- definitions/npm/query-string_v6.x.x/flow_v0.32.x-/query-string_v6.x.x.js
Per documentation, stringify function accepts a sort option which can either turn off the sorting or accept a custom sorter https://www.npmjs.com/package/query-string#sort
This has been available since 5.1
> query string: add missing sort key to StringifyOptions

- definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
- definitions/npm/rxjs_v5.0.x/test_rxjs.js
I've added type definitions for [`Observable.combineAll`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-combineAll). The type definition is pretty lax - combineAll is supposed to operate on `Observable<Observable<T>>`, but I'm unsure if there's any way to enforce that. Other similar operators like `mergeAll` and `concatAll` don't enforce this currently.
> Add Observable.combineAll to RxJS 5 Type Definitions

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
According to https://github.com/apollographql/react-apollo/blob/master/src/Mutation.tsx#L17
cc @budde377 
Edit: Hm, tests failed for node8, but can't see why. Is there any way to trigger another build?
> Added client to MutationResult

- definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/rxjs_v6.x.x.js
- definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/test_rxjs.js
According to the [official migration guide](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#howto-convert-deprecated-methods) for rxjs v6 static `concat` function should be available for import directly from `rxjs` package.
> [rxjs_v6] Add static concat export to rxjs

- definitions/npm/faker_v4.x.x/flow_v0.25.x-/faker_v4.x.x.js
- definitions/npm/faker_v4.x.x/flow_v0.25.x-/test_faker_v4.x.x.js
I have added a support of some utility methods and properties.
Closes #2577 
This method is defined here: https://github.com/Marak/faker.js/blob/master/lib/index.js#L153-L156
It internally calls these implementations of `random.seed()`: https://github.com/Marak/faker.js/blob/master/vendor/mersenne.js#L273-L285
That's why `seed()` can take a `number` or a list of `number`s.
Is defined here: https://github.com/Marak/faker.js/blob/master/lib/index.js#L155
By default is `undefined`, so that's why it is marked as `void`.
Is defined here: https://github.com/Marak/faker.js/blob/master/lib/index.js#L149-L151
Takes a locale name, which is `string`.
> Fixes prototype method for faker.js

- build_and_test_cli.sh
- quick_run_def_tests.sh
- travis.sh
All three scripts are POSIX-sh compliant, so it's unnecessary to require
specifically bash, they works on any POSIX shell. Not every unix system
comes with bash preinstalled and even less install bash executable into
/bin. /bin/sh is defined by POSIX, so more portable.
> Use /bin/sh instead of /bin/bash for better portability

- definitions/npm/lodash-es_v4.x.x/flow_v0.63.x-/lodash-es_v4.x.x.js
- definitions/npm/lodash-es_v4.x.x/flow_v0.63.x-/test_lodash-es-v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js
Fixes problems like
```
Cannot call `pickBy` because undefined [1] is incompatible with object type [2] in type argument `T`.
```
Somebody constrainted `T: void | null` for the case where the input object is not defined, but that means it won't accept a predicate that takes a defined object.
> fix(lodash_v4.x.x): fix bad types for omitBy/pickBy
