definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js

Whenever I wrap a component with **withStyles** flow just stops identifying any errors with the wrapped components

@material-ui/core: fix withStyles types

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js

since it's not compatible with the one from the apollo-client typedefs, we might as well use this one wherever we're using react-apollo...

fix(react-apollo): export ApolloClient

---

definitions/npm/faker_v4.x.x/flow_v0.25.x-/faker_v4.x.x.js

The return type for faker.random.boolean() is string. It should be boolean.

 Fix random.boolean return type

---

cli/src/commands/runTests.js

Before this commit, the folder was created in runTestGroup (if it did
not exist before). However, it was accessed before that, making the
tests crash if the folder was not manually created.
This commit moves the creation to the first thing in the test run.
This is only a problem when you check out and run the build the first time, but it took me a while to figure out what was wrong.
I'm using OSX, maybe the folder creation works differently on other platforms.

Move creation of .flow-bins-cache to earlier in test cycle

---

definitions/npm/@storybook/react_v3.x.x/flow_v0.28.x-/react_v3.x.x.js
definitions/npm/@storybook/react_v3.x.x/test_react_v3.x.x.js

Downloading the libdefs made my current project crash because it lacked two things:
1. The exported `forceReRender` function
2. A first argument to the `.add`-method of the Story interface.
I've added these.

Update @storybook/react_v3.x.x libdef

---

definitions/npm/bluebird_v3.x.x/flow_v0.70.x-/bluebird_v3.x.x.js

Similar to https://github.com/flow-typed/flow-typed/pull/2509, but will be actively trying to get the travis checks to pass.
This solves an issue with stricter rules on generics introduced in flow 0.76.
Bigger question: Is there any reason why the arg for Bluebird.all is typed as `T | $Promisable<T>` instead of `$Promisable<T>` since `$Promisable` is already a type alias for `Promise<T> | T`?

Fix Bluebird.all for flow 0.76+

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js

According to the official [MUI docs](https://material-ui.com/api/circular-progress/), CircularProgress component should have a different set of allowed values for `color` prop and may have an optional `variant` prop.
I'm not sure about `mode` which seems to be a legacy prop. Maybe it should be removed from a type definition?

[material-ui] Improve CircularProgress definition

---

definitions/npm/js-cookie_v2.x.x/flow_v0.38.x-/js-cookie_v2.x.x.js
definitions/npm/js-cookie_v2.x.x/flow_v0.38.x-/test_js-cookie-v2.x.x.js

It seems that `Object` is a correct return type for js-cookie `.getJSON` method as it will always try to return a parsed JSON object [source](https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.js#L147).
While getting a string with `.getJSON` [might be possible](https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.js#L128) I don't think it is a valid return type as for non JSON cookies `.get` method should be used.
This PR is related to the issue #2478

[js-cookie]: change getJSON type to Object

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js

Until now, `pickBy` and `omitBy` did not support numbers as valid object keys.

fix(lodash): Support number as keys in pickBy and omitBy.

---

definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/react-redux_v5.x.x.js

When I upgraded to `react-redux` to 5, we had a drop in type coverage on `connect`. From some experimentation I found that it's resulting from the type import within the libdef. The types imported from redux aren't overly complex and I understand them to be relatively stable, so I've copied them in directly.
I've tested this on my internal repo and found the coverage is applied again. I don't know how to express that as a test in the `flow-typed` suite, however. I tried adding `flow-strict` to the test files as well as `[strict]` settings to `cli/.flow-config`, but still no joy. I'd love any other suggestions anyone can think of.

fix type coverage on react-redux's connect

---

cli/src/commands/runTests.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js

In response to the next issue #2623

Fix `pickBy` and `omitBy` method definitions from `lodash` so that they correctly accept objects with `string` and `number` typed ids.

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js

Fixes https://github.com/flow-typed/flow-typed/issues/2518
Should not have other side effects, apparently it matters wether you use flow "private" internal types or import from react.
Verified the compatibility with this repo: https://github.com/arekkas/flow-redux
It's a bit tricky to provide good test for this, the whole compatibility error is a bit weird.

fix react-router-dom and react-redux type compatibility

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js

Change lodash_v4.x.x definitions to use $ReadOnlyArray for these functions:
- intersection
- intersectionBy
- intersectionWith
- union
- unionBy
- unionWith
- invokeMap
- reduce
- reduceRight

Change a few lodash_v4.x.x definitions to use $ReadOnlyArray

---

definitions/npm/redux-mock-store_v1.2.x/flow_v0.25.x-/redux-mock-store_v1.2.x.js

After changes in #2530 it appears that Store type generated by previous definition of redux-mock-store is invalid. This PR makes it compatible again.

[redux-mock-store] update Store type

---

definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.47.x-v0.54.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.47.x-v0.54.x/test_lodash-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.55.x-v0.62.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.55.x-v0.62.x/test_lodash-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js

As stated in #924 and in comment in #681, current type definition of lodash `keyBy` is invalid. `fp` version is already valid.
Resolve  #924

[lodash 4.x] 'keyBy': do not return map of maybe types

---

definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/react-bootstrap_v0.32.x.js

According to the [documentation](https://react-bootstrap.github.io/components/alerts/), `onDismiss` is not a required prop on the `Alert` component.
This PR fixes the flow type, and thereby eliminates the flow errors when using `Alert`s without dismiss buttons.
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/containers/LearnVehicleSelectRobot.js:214:15
Cannot create Alert element because property onDismiss is missing in props [1] but exists in object type [2].
src/containers/LearnVehicleSelectRobot.js
211│   renderCompanies = () => {
212│     const { availableCompanies, energyCompany, errorLoadingCompanies } = this.state
213│     if (errorLoadingCompanies) {
[1] 214│       return <Alert bsStyle="danger">Error loading companies</Alert>
215│     }
216│     if …
```

Make onDismiss optional on react-bootstrap Alert component

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js

In this commit we fix an issue with how the higher-order component `withStyles` dealt with default props and properly deal with HOCs per the documentation on injecting props with a higher-order component (`https://flow.org/en/docs/react/hoc/`).

Properly deal with injected props in withStyles function of material-ui

---

definitions/npm/query-string_v6.x.x/flow_v0.32.x-/query-string_v6.x.x.js
definitions/npm/query-string_v6.x.x/test_query-string_v6.x.x.js

Replaced `Object` with better def as per [docs](https://github.com/sindresorhus/query-string)
Tests to show IRL behaviour here:
https://runkit.com/callumlocke/query-string-module-tests

Make query-string definition more accurate

---

definitions/npm/history_v4.x.x/flow_v0.25.x-/history_v4.x.x.js
definitions/npm/history_v4.x.x/flow_v0.25.x-/test_history_v4.x.x.js

Fix #2660 and add more tests
I used interfaces so that I can overload methods.

Add location object support to history_v4.x.x push and replace functions

---

definitions/npm/styled-components_v3.x.x/flow_v0.75.x-/styled-components_v3.x.x.js

as of flow_v0.75, things like: https://flow.org/try/#0C4TwDgpgBA7gFgQ2FAvFA3lA2gawiALgGdgAnASwDsBzAXQIFtyAPCAEwF8AoLgGwmTA4VagViJkaTAjEByAIyyo3LqEjikAZlQYZJCjQA0UAEbEyIlQGMA9pRJQAZgFdKOgBTMC8JAEoUAHzMPLb2yGYawNpSMrIIssZmsiayKi6U7ia+QA
will fail. this happens with styled-components if you try and define a type for your theme e.g.
```
type Theme = {
primaryColor: string | someHexLiteral
...
}
```
adding `$ReadOnly` fixes those errors.

add read only to the theme

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js

Use `$ReadOnlyArray<string | PureQueryOptions>` rather than `string[] | PureQueryOptions[]`.

fix(react-apollo): fix refetchQueries types

---

definitions/npm/metrics_v0.1.x/flow_v0.25.x-/metrics_v0.1.x.js
definitions/npm/metrics_v0.1.x/test_metrics_v0.1.x.js

Making the argument of `Meter#mark()` optional.
Source: https://github.com/mikejihbe/metrics/blob/v0.1.17/metrics/meter.js#L16

[metrics] Fix Meter#mark()

---

definitions/npm/react-test-renderer_v16.x.x/flow_v0.47.x-/react-test-renderer_v16.x.x.js

This enables importing the ReactTestRenderer type directly.
```js
import type { ReactTestRenderer } from 'react-test-renderer';
```
Useful when building libraries that receive a TestRenderer instance as an argument.

[react-test-renderer] Export ReactTestRenderer type

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js

So, I have an eslint rule that requires argument type declarations in most places, so my `update` functions (unless a simple lambda expression) need the `cache` argument typed.  But this is currently impossible to do since `react-apollo` doesn't export the `DataProxy` type it uses for this argument.

fix(react-apollo): export DataProxy interface

---

definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/react-redux_v5.x.x.js
definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/test_connectAdvanced.js

This adds a type definition for the [`connectAdvanced` function in react-redux](https://github.com/reduxjs/react-redux/blob/master/docs/api.md#connectadvancedselectorfactory-connectoptions). 
This PR addresses https://github.com/flow-typed/flow-typed/issues/2651. This is my first time writing a library definition, so I may be doing silly things :)

[react-redux] add type definition for connectAdvanced

---

definitions/npm/react-intl_v2.x.x/flow_v0.63.x-/react-intl_v2.x.x.js
definitions/npm/react-intl_v2.x.x/flow_v0.63.x-/test_react-intl_v2.x.x.js

`FormattedMessage` can be configured to return strings by using the technique described [here](https://github.com/yahoo/react-intl/issues/999#issuecomment-335799491). This change enables you have the correct Flow type using this technique, as in the following example:
```jsx
<FormattedMessage id="id" defaultMessage="Request pricing">
{(msg: string) => <a href={`mailto:email@example.com?subject=${msg}`}>{msg}</a>}
</FormattedMessage>
```

Update FormattedMessage in react-intl_v2.x.x.js

---

definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_object.js

The function `keys` works with `?Object` (aka `Maybe Object`). 
This MR allows for correct Flow types when using `keys` with other functions that return `Maybe` types (such as `path`).

feat: ramda keys works with Maybe as input

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
definitions/npm/react-color_v2.x.x/flow_v0.56.x-/react-color_v2.x.x.js
definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js
definitions/npm/rsuite_v3.x.x/flow_v0.53.x-/rsuite_v3.x.x.js

There's been some inconsistencies between React$ -types and imported react types. I'd prefer to use imported types when ever possible. an example case where importing fixed weird compatibility error: https://github.com/flow-typed/flow-typed/pull/2629
This does not tackle even half of the occurrences so more similar PRs might follow. Would be nice to gain some consistency so that it's easier for people to figure out how react types should look like.

Use imported react types instead of flow internal react types

---

definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js

- [Card](https://ant.design/components/card/#Card), [source code 1](https://github.com/ant-design/ant-design/blob/master/components/card/index.tsx)
- [Steps](https://ant.design/components/steps/#Steps), [source code 1](https://github.com/ant-design/ant-design/blob/master/components/steps/index.tsx), [source code 2](https://github.com/react-component/steps/blob/9e62045c58ce7a9edcfd281db912fa11e28ac920/src/Steps.jsx)
- [Step](https://ant.design/components/steps/#Step), [source code](https://github.com/react-component/steps/blob/9e62045c58ce7a9edcfd281db912fa11e28ac920/src/Step.jsx)

Add `Card` & `Step` component definitions to `antd`

---

definitions/npm/recompose_v0.x.x/flow_v0.47.x-v0.52.x/recompose_v0.x.x.js
definitions/npm/recompose_v0.x.x/flow_v0.53.x-v0.54.x/recompose_v0.x.x.js
definitions/npm/recompose_v0.x.x/flow_v0.55.x-v0.56.x/recompose_v0.x.x.js
definitions/npm/recompose_v0.x.x/flow_v0.57.x-/recompose_v0.x.x.js

Recompose's `branch()` function's first argument is a function that takes the original props of the component and returns a boolean. The current flow-typed definition defines it as a function that takes the enhanced props instead. This is incorrect.
- [`branch()` Docs](https://github.com/acdlite/recompose/blob/master/docs/API.md#branch)
- [`branch()` Implementation](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/branch.js#L10-L11)

[recompose] fix branch() type signature

---

definitions/npm/react-loadable_v5.x.x/flow_v0.56.0-/react-loadable_v5.x.x.js

Introduced in v5.4, the `retry` prop is a `() => void` function that retries loading the module. 
https://github.com/jamiebuilds/react-loadable/pull/82

[react-loadable] Add retry prop

---

definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js

I've added in type definitions for `describe.each, test.each and test.only.each`in the jest repository. This PR is to share the changes from that repo to this one so that both are inline and anyone else using flow will get the benefits. That [PR](https://github.com/facebook/jest/pull/6931#) was merged in already.

Add in type definitions for describe.each, test.each and test.only.each for jest

---

definitions/npm/recompose_v0.x.x/flow_v0.47.x-v0.52.x/recompose_v0.x.x.js
definitions/npm/recompose_v0.x.x/flow_v0.53.x-v0.54.x/recompose_v0.x.x.js
definitions/npm/recompose_v0.x.x/flow_v0.55.x-v0.56.x/recompose_v0.x.x.js
definitions/npm/recompose_v0.x.x/flow_v0.57.x-/recompose_v0.x.x.js

Reverts flow-typed/flow-typed#2684
I misunderstood the generic types used in Recompose's type definitions when writing #2684. This reverts that change, since it was correct in the first place.

Revert "[recompose] fix branch() type signature"

---

definitions/npm/js-joda_v1.8.x/flow_v0.25.x-/js-joda_v1.8.x.js
definitions/npm/js-joda_v1.8.x/flow_v0.25.x-/test_js-joda_v1.8.x.js

Using arrow function syntax to define an overload does not work (not sure if this is a bug in Flow or expected behaviour).
These two functions on `LocalDate` should be overloads:
```js
atTime(time: LocalTime): LocalDateTime;
atTime: (
hour: number,
minute: number,
second?: number,
nanoOfSecond?: number
) => LocalDateTime;
```
However, Flow only accepts the second signature:
```
Error ------------------------------------------------------------------------------------- test_js-joda_v1.8.x.js:10:61
Cannot call `joda.LocalDate.now().atTime` with `joda.LocalTime.MAX` bound to `hour` because `LocalTime` [1] is
incompatible with number [2].
test_js-joda_v1.8.x.js:10:61
10| const endOfDay: LocalDateTime = joda.LocalDate.now().atTime(joda.LocalTime.MAX);
^^^^^^^^^^^^^^^^^^
References: …
```

Fix js-joda overloads

---

definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js

Since v23 of jest, it is possible to add async matchers to jest via the `extend` api. Implementing PR is https://github.com/facebook/jest/pull/5919
Documentation: https://github.com/facebook/jest/blob/master/docs/ExpectAPI.md#async-matchers
This PR modifies the type definitions for v23 to accept a Promise returning a `JestMatcherResult` as return value of any `JestMatcher` function

Add support for jest async matchers

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js
definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/test_react-router-dom.js

`withRouter` is getting rid of the types if is chained to another HOC. I ran into this using `withRouter` with material-ui `withStyles`. For example this currently works:
```
const MyComponent = (props: { a: string }) => {}
withRouter(
withStyles({})(MyComponent)
)
<MyComponent />
```
I used the same solution used in material-ui `withStyles` definitions that allows chaining the HOC functions.

react-router-dom: add support for chaining withRouther with other HOCs

---

definitions/npm/object-assign_v4.x.x/flow_v0.25.x-/object-assign_v4.x.x.js
definitions/npm/object-assign_v4.x.x/test_object-assign_v4.x.x.js

Summary:
Resolves #2705. See that issue for rationale and discussion.
Test Plan:
Running `flow-typed run-tests object-assign` passes.
wchargin-branch: object-assign-native

object-assign: use native `Object$Assign` type

---

definitions/npm/commander_v2.x.x/flow_v0.28.x-/commander_v2.x.x.js
definitions/npm/commander_v2.x.x/test_commander_v2.x.x.js

I want to use `Commander.Command`, but I got this error: 
```js
Cannot call commander.Command because Command [1] is not a function.
packages/configs/src/bin/core/cliOptions.js
8│
9│ import { version } from '../../../package.json';
10│
11│ const program = new commander.Command('name')
12│   .version(version, '-v, --version')
13│   .arguments('[arguments...]')
14│   .usage(chalk`{green [arguments...]} {gray [options]}`)
flow-typed/npm/commander_v2.x.x.js
[1] 278│     Command: Command,
```
This `PR` is used to fix this error.

fix commander: can use `commander.Command`

---

definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js

Often in Sequelize hooks it's necessary to pass through the transaction if any, like this:
```js
User.afterCreate(async (user: User, {transaction}: CreateOptions): Promise<any> => {
await Log.create({message: `created user ${user.id}`}, {transaction})
})
```
But since the type is currently `transaction?: Transaction` this causes an error if `transaction` is `null`.
By changing the type to `transaction?: ?Transaction` we can pass it through without any errors.

fix(sequelize): allow null value to be passed for transaction

---

definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/rxjs_v6.x.x.js

Fix only the import path. Deep import of `TestScheduler` does not work.
https://github.com/ReactiveX/rxjs/blob/master/src/testing/index.ts

[RxJS v6] fix wrong import path for TestScheduler

---

definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js

`instances` and `calls` were typed, but `results` were not.
see documentation here: https://jestjs.io/docs/en/mock-function-api#mockfnmockresults

add mock.results type

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js

`createMuiTheme()` without any options provided should not show an error message. Here is an example from official docs: https://material-ui.com/customization/overrides/#theme-nesting

[material-ui]: support createMuiTheme() without any options

---

cli/src/commands/__tests__/runTests-test.js

closes https://github.com/flow-typed/flow-typed/issues/2723
It's a bit flaky test, so running the test only against latest flow version should make it much faster and much more reliable

fixes 2723 run runTests test only against latest flow

---

definitions/npm/normalizr_v3.x.x/flow_v0.25.x-/normalizr_v3.x.x.js

I believe normalizr does not mutate the input values, so it should be safe to use  `$ReadOnlyArray` here.
Disclaimer: I am a flow typing newbie, so please review carefully :-)

[normalizr] Use $ReadOnlyArray

---

definitions/npm/commander_v2.x.x/flow_v0.28.x-/commander_v2.x.x.js
definitions/npm/commander_v2.x.x/test_commander_v2.x.x.js

- `arguments` in `outputHelp` should be a function
- [api docs](http://tj.github.io/commander.js/#Command.prototype.outputHelp)
- `command.parse` can return `argv`, `rawArgv` and `options`.
- [api docs](http://tj.github.io/commander.js/#Command.prototype.parse)

Fix commander

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js

OptionProps takes properties and functions that are used in places like the `graphql` higher-order-component. One of its properties is `data` which is marked as required, but is in fact optional when querying [as seen here](https://github.com/apollographql/react-apollo/blob/master/src/query-hoc.tsx#L88).
This PR updates OptionProps' structure to denote `data` as optional.

[React-Apollo] Mark `data` as optional in OptionProps

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js

As described in title `mutate()` execution should be valid without any options specified e.g. https://www.apollographql.com/docs/react/essentials/mutations.html#render-prop

fix[react-apollo]: mutate() options should be optional

---

definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/rxjs_v6.x.x.js
definitions/npm/rxjs_v6.x.x/flow_v0.34.x-/test_rxjs.js

- [defer](https://rxjs-dev.firebaseapp.com/api/index/function/defer) (add)
- [combineLatest](https://rxjs-dev.firebaseapp.com/api/index/function/combineLatest) (add, rel. #2616)
- [pipe](https://rxjs-dev.firebaseapp.com/api/index/function/pipe) (improvement: allow to accept unlimited arguments)
- [withLatestFrom](https://rxjs-dev.firebaseapp.com/api/operators/withLatestFrom) (fix)
- [zip](https://rxjs-dev.firebaseapp.com/api/operators/zip) (fix)
- [combineLatest](https://rxjs-dev.firebaseapp.com/api/operators/combineLatest) (fix)
- These operators are broken in case of multiple arguments, and now fixed in this PR
- [map](https://rxjs-dev.firebaseapp.com/api/operators/map) (add test)

[RxJS v6] add some missing defs & fix broken defs

---

definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js

Based on feedback here: https://github.com/facebook/metro/pull/266#discussion_r220581436
This now matches the flow annotations in the Jest source code: https://github.com/facebook/jest/blob/bab6399a89a069273c38cb624236d19be0c98adf/packages/jest-snapshot/src/index.js#L55

Updates Jest 23's toMatchSnapshot to allow 'any' for propertyMatchers.

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js

this commit changes `[id: string]` to `[id: any]` for many
lodash methods. This is needed because keys can be more than just
strings in JavaScript itself and then in Flow, keys can be opaque
types which before this commit would throw errors.
fixes #1330 
A union of some sort allowing `string | number | Symbol | opaque ...` would be ideal here but I don't know of a way to allow opaque types based on the underlying type?

lodash allow any type for object keys

---

definitions/npm/colors_v1.3.x/flow_all/colors_v1.3.x.js
definitions/npm/colors_v1.3.x/test_colors_v1.3.x.js

See https://github.com/Marak/colors.js   
For the `String.prototype` API I'm looking for a way to extends builtin `String` class. But I guess it's not yet possible, right?

Add colors definitions

---

definitions/npm/history_v4.x.x/flow_v0.25.x-/history_v4.x.x.js

Flow released v0.82.0 with what seems to be a breaking change:
> Removed the ability to use functions as type annotations. This ability was originally designed to support ES3-style classes, but in practice causes confusion and missed errors. We found that the vast majority of added errors were detecting legitimate bugs, and the remainder could be easily updated to ES6 classes.
https://github.com/facebook/flow/releases/tag/v0.82.0
After upgrading to flow v0.82.0, I started seeing these errors:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/history_v4.x.x.js:30:29
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
27│     goBack(): void,
28│     goForward(): void,
29│     listen: …
```

fix "cannot use function type as a type" error

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js

Just made minor changes shown below, but I get a huge diff due to eol and don't understand why. Editorconfig says ```end_of_line = lf``` and file is LF. Any ideas on how to fix that?
```
git diff -w
diff --git a/definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js b/definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
index 4010684..b01fb61 100644
--- a/definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
+++ b/definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
@@ -358,7 +358,7 @@ declare module "lodash" {
sortedLastIndexOf<T>(array: Array<T>, value: T): number;
sortedLastIndexOf<T>(array: void | null, value?: ?T): -1;
sortedUniq<T>(array?: ?Array<T>): Array<T>;
-    sortedUniqBy<T>(array?: ?Array<T>, iteratee?: ?(value: T) => mixed): Array<T>;
+ …
```

fix(lodash) type for sortedUniqBy

---

cli/src/commands/runTests.js

This helps to refactor runTests further. 0.53.0 flow version is so old that we don't need to support older versions than that.
fixes: https://github.com/flow-typed/flow-typed/issues/2746

Don't run tests for older Flows

---

definitions/npm/shortid_v2.2.x/flow_v0.25.x-/shortid_v2.2.x.js

ShortIdModule is not needed in global scope. It can also be exact type.

Make ShortIdModule private

---

definitions/npm/papaparse_v4.x.x/flow_v0.39.x-/papaparse_v4.x.x.js
definitions/npm/papaparse_v4.x.x/test_papaparse_v4.x.x.js

Papaparse `skipEmptyLines` config option should have `boolean` or string literal `greedy` value, see: https://www.papaparse.com/docs#config.

[papaparse] Fix skipEmptyLines typing

---

definitions/npm/react-native-simple-store_v1.x.x/flow_v0.25.x-/react-native-simple-store_v1.x.x.js
definitions/npm/react-native-simple-store_v1.x.x/flow_v0.25.x-/test_react-native-simple-store.js

ctx https://github.com/flow-typed/flow-typed/pull/2786
switched to another synthax because `declare function delete` would not pass eslint

Add missing 'delete' method in react-native-simple-store

---

definitions/npm/bluebird_v3.x.x/flow_v0.70.x-/bluebird_v3.x.x.js

I came across this while trying to filter a Bluebird.catch and wasn't sure how to import an internal class def.
Turns out it's much easier / more intuitive to just expose the internal class defs in bluebird for error subtypes.
As an example:
```
Bluebird
.delay(1000) // Normally an error-prone, slow task
.timeout(0)
.catch(Bluebird.TimeoutError, e => ...)
```
Is a common use case to handle timeouts explicitly, but trying to access `Bluebird.TimeoutError` currently throws `Cannot get Bluebird.TimeoutError because property TimeoutError is missing in statics of Bluebird$Promise [1].`

Expose static class definitions for Bluebird Errors

---

definitions/npm/opentok_v2.6.x/flow_v0.61.x-/opentok_v2.6.x.js

Based on the docs the `url` field can be null:
>url  | String | The download URL of the available MP4 file. This is only set for an archive with the status set to "available"; **for other archives, (including archives with the status "uploaded") this property is set to null**. The download URL is obfuscated, and the file is only available from the URL for 10 minutes. To generate a new URL, call the OpenTok.getArchive() or OpenTok.listArchives() method.
Reference: https://tokbox.com/developer/sdks/node/reference/Archive.html

Make Archive.url optional in OpenTok typings

---

definitions/npm/firebase_v5.x.x/flow_v0.34.x-/firebase_v5.x.x.js

TypeScript defs had the same bug (now fixed): https://github.com/firebase/firebase-js-sdk/issues/555
Documentation to back up optional boolean: https://firebase.google.com/docs/reference/js/firebase.database.DataSnapshot#forEach

forEach shouldn't require a boolean return

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js

Without this fix, the following error occurs in flow 0.83:

Add typeof to material-ui handleEvent

---

definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js

Mostly changes to `StackViewConfig`.
Corresponds to:
- https://github.com/react-navigation/react-navigation/commit/ab3e05333863b3706e80b3699aaccdcea6171b1a#diff-ba817d01659141d94b79f150dac176b4
- https://github.com/react-navigation/react-navigation/commit/70a2c3b97c7961b0df1f76474f8d89bb3ff36ab1#diff-ba817d01659141d94b79f150dac176b4

[react-navigation] Update libdef from react-navigation repo

---

definitions/npm/next_v7.x.x/flow_v0.53.x-/next_v7.x.x.js
definitions/npm/next_v7.x.x/test_next_v7.x.x.js

Based on the v4 definitions, with new definitions for the new features added since then.
This is my first PR so let me know if there's anything I've missed!

Add typedefs for next.js v7

---

definitions/npm/apollo-client_v2.x.x/flow_v0.57.x-/apollo-client_v2.x.x.js

Adds `export` for `ApolloClientOptions`.

[apollo-client] Export ApolloClientOptions

---

cli/yarn.lock
definitions/npm/ramda_v0.x.x/flow_v0.25.x-v0.27.x/test_ramda_v0.21.x.js
definitions/npm/ramda_v0.x.x/flow_v0.28.x-v0.30.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.49.x-v0.61.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_list.js

Since Flow 0.71, it seems that Flow tries to validate `map` usage on Objects with the Array definition.
Problem exits only when using curried version.
This, fixes the issue simply by moving Object definition before Array definition

fix(ramda): move object `map` declaration before array ones

---

definitions/npm/@babel/register_v7.x.x/flow_v0.30.x-/register_v7.x.x.js

Adds the `{ configFile }` option.
See https://babeljs.io/docs/en/next/options#configfile.

[@babe/register] Add configFile option

---

definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js

The custom jest matchers for dom-testing-library have been updated in the last few months, here I'm updating their definitions.
Reference: https://github.com/gnapse/jest-dom#custom-matchers

Update jest defs for dom testing library

---

definitions/npm/fs-extra_v7.x.x/flow_all/fs-extra_v7.x.x.js
definitions/npm/fs-extra_v7.x.x/test_fs-extra_v7.x.x.js

fs-extra has all the fs functions. I added some of which our CLI relies on. copied from here: https://github.com/facebook/flow/blob/master/lib/node.js
see: https://github.com/jprichardson/node-fs-extra

Add some missing functions to fs-extra

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js

This improves the types for QueryRenderProps with respect to `props.data`. It correctly handles `props.data` being `null`, an empty object, or `TData`.
See https://github.com/flow-typed/flow-typed/pull/2172#issuecomment-409831959 for more context

[react-apollo] Update type for QueryRenderProps

---

definitions/npm/prettier_v1.x.x/flow_v0.56.x-/prettier_v1.x.x.js
definitions/npm/prettier_v1.x.x/flow_v0.56.x-/test_prettier_v1.x.x.js

Summary:
It is particularly convenient to be able to import the `Options` type,
but before this commit this was not possible.
Test Plan:
Tests fail before this commit and pass after it.
wchargin-branch: prettier-type-exports

prettier: export individual types

---

definitions/npm/moment_v2.x.x/flow_v0.25.x-/moment_v2.x.x.js
definitions/npm/moment_v2.x.x/test_moment-v2.js

Fixes #2867
Looks like `moment` project in GitHub allows `null` and `undefined` to be passed to the `moment()`, `moment.utc()` and `moment.parseZone()` constructors in their TypeScript definitions, so `flow-typed` should allow that, too.
* https://github.com/moment/moment/commit/c891a4fcb0492539184eac73229b7a8053a5bbf8
* https://github.com/moment/moment/blob/2.22.2/moment.d.ts#L400
* https://github.com/moment/moment/blob/2.22.2/moment.d.ts#L622
* https://github.com/moment/moment/blob/2.22.2/moment.d.ts#L650

[moment] Allow null and undefined in constructors

---

definitions/npm/react-copy-to-clipboard_v5.x.x/flow_v0.25.x-/react-copy-to-clipboard_v5.x.x.js
definitions/npm/react-copy-to-clipboard_v5.x.x/test_react-copy-to-clipboard_v5.x.x.js

Add library definitions for `react-copy-to-clipboard`.
- [https://www.npmjs.com/package/react-copy-to-clipboard](https://www.npmjs.com/package/react-copy-to-clipboard)
- [https://github.com/nkbt/react-copy-to-clipboard](https://github.com/nkbt/react-copy-to-clipboard)

[react-copy-to-clipboard] Add definitions

---

definitions/npm/next-routes_v1.x.x/flow_v0.47.x-/next-routes_v1.x.x.js
definitions/npm/next-routes_v1.x.x/test_next-routes.js
definitions/npm/next_v7.x.x/flow_v0.53.x-/next_v7.x.x.js
definitions/npm/next_v7.x.x/test_next_v7.x.x.js

[next.js](https://github.com/zeit/next.js) now uses a property on `Router` called `events` to manage callbacks.
I've updated the definitions in `next.js` and `next-routes` accordingly.
`events` now uses overloads too, so you can be sure that you have a valid event name! 🎉

Improve type definitions for next.js and next-routes Router events

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js

The react-apollo library exports a compose helper which is useful for building applications leveraging react-apollo. This PR adds definitions to the compose methods to avoid flow errors.
https://www.apollographql.com/docs/react/basics/setup#compose
Fixes #2580

Add compose export of react-apollo

---

definitions/npm/io-ts_v1.3.x/flow_v0.72.x-/io-ts_v1.3.x.js
definitions/npm/io-ts_v1.3.x/flow_v0.72.x-/test_io-ts.js

Really excited about the work gcanti has done for Typescript in his [io-ts](https://github.com/gcanti/io-ts) library and want to have the same thing for flow. I've added a libdef I've used for this library in case anyone else wants to use this with flow.

Add io-ts libdef

---

.travis.yml

This should speedup tests as we have a spec that tries to fetch the repo. So instead of cloning the whole repo we can just rebase it -> less data moved -> hopefully faster and more reliable tests 
So from:
```
PASS  src/lib/npm/__tests__/npmLibDefs-test.js (14.414s)
● Console
console.log src/lib/cacheRepoUtils.js:93
• flow-typed cache not found, fetching from GitHub...
```
to:
```
PASS  src/lib/npm/__tests__/npmLibDefs-test.js (11.944s)
● Console
console.log src/lib/cacheRepoUtils.js:108
• rebasing flow-typed cache...
```

cache .flow-typed folder

---

cli/.eslintrc
cli/src/commands/__tests__/runTests-test.js
cli/src/commands/runTests.js

0.84.0 has serious problems on our CI: https://github.com/facebook/flow/issues/7108 and https://github.com/flow-typed/flow-typed/issues/2916
Also `"fb"`preset seems no longer exist for prettier so I wrote the rules open in .eslintrc.

skip 0.84.0 and adjust prettier rules

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js

It is possible to pass `context` to query options as seen in the docs:
https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-context

[React-Apollo] Add context to QueryOpts

---

definitions/npm/isomorphic-unfetch_v3.x.x/flow_v0.25.x-/isomorphic-unfetch_v3.x.x.js
definitions/npm/isomorphic-unfetch_v3.x.x/test_isomorphic-unfetch_v3.js

Source code: https://github.com/developit/unfetch/tree/master/packages/isomorphic-unfetch
Basically copied the definition from `isomorphic-fetch`. Looks like it is not maintained.

[isomorphic-unfetch] Add isomorphic-unfetch_v3

---

definitions/npm/moment_v2.x.x/flow_v0.25.x-/moment_v2.x.x.js
definitions/npm/moment_v2.x.x/test_moment-v2.js

Moment allows for an empty constructor, which was accounted for. But the types did not account for passing a variable that may have an undefined/null value.

fix(moment): allow maybe string types in moment instantiation

---

definitions/npm/react-copy-to-clipboard_v5.x.x/flow_v0.25.x-/react-copy-to-clipboard_v5.x.x.js
definitions/npm/react-copy-to-clipboard_v5.x.x/test_react-copy-to-clipboard_v5.x.x.js

It seems OK to treat `react-copy-to-clipboard` as it publishes own component as named-export
https://github.com/nkbt/react-copy-to-clipboard/blob/master/src/index.js

Enable to export Component as named-export

---

definitions/npm/luxon_v1.x.x/flow_v0.32.0-/luxon_v1.x.x.js
definitions/npm/luxon_v1.x.x/test_luxon.js

`keepCalendarTime` is depreciated in `DateTime.setZone` and `DateTime.toUtc` and will be replaced by `keepLocalTime`.
- Docs: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-setZone
- https://github.com/moment/luxon/blob/master/src/datetime.js#L1144
- https://github.com/moment/luxon/blob/master/src/datetime.js#L1121
`keepCalendarTime` is still supported by `luxon`:
- https://github.com/moment/luxon/blob/master/src/datetime.js#L1152
Changes:
- Add tests to cover deprecated `keepCalendarTime` and new `keepLocalTime`
- Update SetZoneOptions to support both fields

[luxon] fix zone options

---

definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js

React Navigation allows this to return a null value, and in fact this is required for proper functioning of `react-navigation-redux-helpers`.
(The change to `getParam`'s `fallback` parameter is just automatic Prettier formatting. Not sure how the last commit skipped it.)
Corresponding React Navigation PR: https://github.com/react-navigation/react-navigation/pull/5173

[react-navigation] getCurrentNavigation can be null

---

definitions/npm/react-loadable_v5.x.x/flow_v0.56.0-/react-loadable_v5.x.x.js
definitions/npm/react-loadable_v5.x.x/flow_v0.56.0-/test_react-loadable_v5.x.x.js

When a programmer uses [Loadable.Map](https://github.com/jamiebuilds/react-loadable#loading-multiple-resources), he faces a situation where a loaded module hasn't any type-restriction.
(Actually, it may evaluate as `empty`)
Then, the programmer applies its own type arguments into `Loadable.Map` like below.
```js
Loadable.Map<Props, { a: () => Promise<string>, b: () => Promise<number> }>({...})
```
But this application causes type error with a message like `Cannot instantiate `MapOptions` because number [1] is incompatible with string [2] in property `b` of type argument `Loadable.Map`.`.
This causes from a restriction of type argument named `TModules`.
It defined as `MapOptions<TProps, TModules: { [key: string]: * }>`,
When type arguments applied to TModules, It seems Flow may infer …

[react-loadable] Make type application of ReactLoadable.Map more precisely

---

definitions/npm/element-resize-detector_v1.x.x/flow_v0.25.x-/element-resize-detector_v1.x.x.js
definitions/npm/element-resize-detector_v1.x.x/test_element-resize-detector_v1.x.x.js

Add library definitions for `element-resize-detector`.
- [https://www.npmjs.com/package/element-resize-detector](https://www.npmjs.com/package/element-resize-detector)
- [https://github.com/wnr/element-resize-detector](https://github.com/wnr/element-resize-detector)

[element-resize-detector] Add definitions

---

definitions/npm/moment_v2.x.x/flow_v0.25.x-/moment_v2.x.x.js
definitions/npm/moment_v2.x.x/test_moment-v2.js

issue: https://github.com/flow-typed/flow-typed/issues/2903
Allow momentjs constructed using empty array and object. No additional test cased added as we already have the test case here https://github.com/flow-typed/flow-typed/blob/67180766627b6494c5ed464a9aefb3eeb6b9fb68/definitions/npm/moment_v2.x.x/test_moment-v2.js#L9-L10
Btw i found issue committing the PR with GPG activated and got error error .
```shell
error: gpg failed to sign the data
fatal: failed to write commit object
```
Probably because of the pre-hooks commit rule. So this PR is created using commit file that directly updated from GitHub interface.

issue-2903 momentjs support empty array and object

---

.gitignore
definitions/npm/formik_v0.11.x/flow_v0.59.x-/formik_v0.11.x.js

This pull request fixes a typo in `withFormik` HOC definition.
`WithFormikConfig` type and `withFormik` function are polymorphic and expect `Props` and `Values` as type parameters. 
It is expected that `withFormik<Props, Values>` receives argument of type `WithFormikConfig<Props, Values>`.
`withFormik<Props, Values>` expects argument of type `WithFormikConfig<`**`React$ComponentType<Props>`**`, Values>`.
First type parameter of `withFormik` HOC `React$ComponentType<Props>` needs to be replaced with `Props`.

[formik] Fixed typo in `withFormik` HOC definition

---

definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js

`ParamName` should be a string to be compatible with the type `NavigationParams` where key is a string:
```js
declare export type NavigationParams = {
[key: string]: mixed,
};
```
Flow error:
```js
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/react-navigation_v2.x.x.js:539:16
ParamName [1] is incompatible with string [2].
[2]  72│     [key: string]: mixed,
:
536│       eventName: string,
537│       callback: NavigationEventCallback
538│     ) => NavigationEventSubscription,
[1] 539│     getParam: <ParamName>(
540│       paramName: ParamName,
541│       fallback?: $ElementType<
542│         $PropertyType<
```

[react-navigation] - Fix error "ParamName [1] is incompatible with string [2]."

---

cli/src/commands/runTests.js

This should increase the hash table size from 8 megabytes to 32 megabytes and dir table size from 2 megabytes to 8 megabytes for libdef tests. Let's see if this fixes our CI issues.
See
https://flow.org/en/docs/config/options/#toc-sharedmemory-dep-table-pow-unsigned-integer
https://flow.org/en/docs/config/options/#toc-sharedmemory-hash-table-pow-unsigned-integer
E: Ended up reducing worker count so that there is only one flow instance per version. This not only fixes the CI issues but should also speed up tests in most of the cases.

Try to fix CI issues by reducing worker count

---

cli/src/commands/runTests.js

Removes `null` from the end of output, adds a bit of indentation to flow output to make it more distinguishable.

Fix error message

---

definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/test_model.js
definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/test_option.js
definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/test_recorder.js
definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/test_tracer.js
definitions/npm/zipkin_v0.14.x/flow_v0.72.x-/zipkin_v0.14.x.js

Add defs for [zipkin](https://www.npmjs.com/package/zipkin), largely ported from that package's [existing Typescript defs](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/index.d.ts).
Most of the tests so far focus on places that diverged from the TS defs either out of necessity (e.g. Option type) or as a result of fixing a type that was clearly incorrect (e.g. Option flatMap, Endpoint isEmpty).  There are higher level tests in test_tracer.js derived from examples in the zipkin package's README.
Things that may be worth a closer look:
* Looking at other tests for inspiration, it wasn't entirely clear whether I should use the TDD `describe`/`it` style or not.  Happy to update these tests if `describe`/`it` is preferred.
* The nested parametric Option/Some/None export …

Add zipkin defs

---

definitions/npm/react-testing-library_v5.x.x/flow_v0.67.1-/react-testing-library_v5.x.x.js
definitions/npm/react-testing-library_v5.x.x/flow_v0.67.1-/test_react-testing-library_v5.x.x.js

* Removes the nullable option for the return value of waitForElement. That null is not in the typescript typings and the return value is truthy or throws an error.
* Adds getAllByText typings.
* Adds getAllByLabelText typings.

Add additional typings for react-testing-library v5.

---

definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_pipe.js

Сurrently all arguments will passed to first function:
```js
import R from 'ramda';
R.pipe((a,b,c) => {
console.log({a,b,c})
return 69
})(1,2,3,4,5,6,7,9)
// {a: 1, b: 2, c: 3}
// 69
```

[ramda_0.x.x][Issue #1899] Update `pipe()` types and add tests 

---

definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js

I just created a new react native project (0.56) and added react-navigation (2.7.0) and flow libdef `react-navigation_v2.x.x`.
As a result, I get a type error when I try to use the result of `createDrawerNavigator` (or the others).
``` bash
yarn flow status
yarn run v1.7.0
$ /Users/.../.../.../App/node_modules/.bin/flow status
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/app.js:18:13
Cannot instantiate React.Element because in type argument ElementType:
• Either a callable signature is missing in statics of React.Component [1] but exists in
React.StatelessFunctionalComponent [2].
• Or a callable signature is missing in withRouter [3] but exists in
React.StatelessFunctionalComponent [2].
• Or a callable signature is missing in …
```

React-navigation: fixed flow type error with React$

---

definitions/npm/react-select_v1.x.x/flow_v0.53.x-/react-select_v1.x.x.js
definitions/npm/react-select_v1.x.x/flow_v0.53.x-/test_react-select_v1.x.x.js

Accept any type as options in react-select.
The types added in 
https://github.com/flow-typed/flow-typed/pull/2817
break the implementations where a custom optionRenderer and filterOptions are passed

Accepting a type T as options to support custom rendered options

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js
definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/test_react-router-dom.js

Allow arrays in Route path:
```jsx
<Route path={["/login", "/logout"]} />
```
https://reacttraining.com/react-router/web/api/Route/path-string-string

Fix react-router-dom Route path to allow arrays of string

---

definitions/npm/ramda_v0.x.x/flow_v0.25.x-v0.27.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.25.x-v0.27.x/test_ramda_v0.21.x.js
definitions/npm/ramda_v0.x.x/flow_v0.28.x-v0.30.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.28.x-v0.30.x/test_ramda_v0.x.x_misc.js
definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/test_ramda_v0.x.x_misc.js
definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/test_ramda_v0.x.x_misc.js
definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/test_ramda_v0.x.x_misc.js
definitions/npm/ramda_v0.x.x/flow_v0.49.x-v0.61.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.49.x-v0.61.x/test_ramda_v0.x.x_misc.js
definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/test_ramda_v0.x.x_misc.js

Prior to this change, `is` would accept anything for its type in many of the
Flow versions. Now it only accepts a class (`Number`, `String`, etc) which could be
realistically enforced by `is`.
There's also an auxiliary change of `any` -> `mixed` where it applies to `is` and in
many cases more tests for how `is` works as well as negative tests.
As of writing these changes have some broken tests that are unrelated to `is`
and instead seem to be resulting from the problem that https://github.com/flow-typed/flow-typed/pull/2793 is attempting to fix.

enforce 1st param on ramda's is function is a type (Class)

---

definitions/npm/koa_v2.0.x/flow_v0.47.x-/koa_v2.0.x.js

Mark cookies.get options as optional, since it's optional in the cookies library (ref: https://github.com/pillarjs/cookies#cookiesget-name--options--)

Fix cookies.get in Koa v2

---

definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js

This is another take on #2793.
Flow introduces stricter typing in 0.82.0 which causes the definition with `MergeWith` and `MergeWithKey` to fail. These changes should bring the `MergeWith*` definitions into better soundness and also get them to pass again.
One thing of note is that there's no reason the change couldn't be backported to prior versions of Flow, since it should also increase strictness/soundness. This PR also handles that for the last version but I'm not sure how far back I can go with `$ElementType`.
Thanks @Jabher for the initial pass on this! It helped me come to the conclusion I have here.

Fix flow 0.82 ramda MergeWith and MergeWithKey

---

definitions/npm/next_v7.x.x/flow_v0.53.x-/next_v7.x.x.js
definitions/npm/next_v7.x.x/test_next_v7.x.x.js

`Router` components `push` and `replace` have URL as a string, but it can be either string or URL object. The same one as `Link` is using.
`push` and `replace` are using property `change` which accept object or string. [Source code](https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/router/router.js#L146)
`Link` is using `formatUrls` which has the same logic - [Surce code](https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/link.js#L47)

Next.js 7.x.x router push and replace not correct type

---

definitions/npm/firebase_v5.x.x/flow_v0.34.x-/firebase_v5.x.x.js

Regarding the actual firebase implementation, the `getToken` method can return a string
or a null if the `Notification.permission === 'default'`
Link to FCM source: https://github.com/firebase/firebase-js-sdk/blob/master/packages/messaging/src/controllers/base-controller.ts#L77

Update firebase@5.X.X libdef

---

definitions/npm/react-native-video_v3.x.x/flow_v0.68.0-/react-native-video_v3.x.x.js
definitions/npm/react-native-video_v3.x.x/flow_v0.68.0-/test_react-native-video.js

Flow type for setNativeProps method (https://github.com/react-native-community/react-native-video/blob/master/Video.js#L27)
I had to make props not readonly because some versions of flow had a bug and though passing an object was assigning to a readonly property... This should be fine since props are assumed to be immutable by react anyway.

[react-native-video_v3.x.x] Add missing setNativeProps method

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js

@GAntoine there will be a CI build failure due to a bug in Flow 0.88 not producing an expected error in an unrelated test case.

fix(react-apollo): ensure subscriptionData types data the same way as query

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js

Fix a few types related to React components
I am not sure what `$Supertype` achieves (see second commit which adds it back, made it a separate commit for the sake of clarity).
When I remove it, flow complains about a few unused suppression comments. :confounded:

react-router-dom: fix React-related types

---

definitions/npm/react-select_v1.x.x/flow_v0.53.x-/react-select_v1.x.x.js
definitions/npm/react-select_v1.x.x/flow_v0.53.x-/test_react-select_v1.x.x.js

- Adds `Select.Async`
- Makes `Props` exact so that they're actually type-safe
- Fixes faulty autofocus test (as found by exact `Props`)
- Defines `OptionType` in tests [the same way as it is defined in react-select](https://github.com/JedWatson/react-select/blob/c22d296d50917e210836fb011ae3e565895e6440/src/types.js#L4)
- Adds a test for an invalid prop

Update react-select libdef

---

definitions/npm/jquery_v3.x.x/flow_v0.28.x-/jquery_v3.x.x.js

Changed type Object to {} where needed to support the new behavior of flow 0.88 that now handles Object as an alias for any

[jquery_v3.x.x] Changed Object to {} where needed

---

definitions/npm/webpack_v4.x.x/flow_v0.71.x-/webpack_v4.x.x.js

Adds all the possible options for configuring [`{ devtool }`](https://webpack.js.org/configuration/devtool/) with webpack.

Add all webpack devtool variants

---

definitions/npm/react-select_v1.x.x/flow_v0.53.x-/react-select_v1.x.x.js
definitions/npm/react-select_v1.x.x/flow_v0.53.x-/test_react-select_v1.x.x.js

Resolve #3023 
Note: I remove autofocus, because it ise deprecated on code, see: https://github.com/JedWatson/react-select/blob/v1.3.0/src/Select.js#L125

#3023 Add some missing props dans update test

---

definitions/npm/http-errors_v1.x.x/flow_v0.25.x-/http-errors_v1.x.x.js
definitions/npm/http-errors_v1.x.x/test_http-errors_v1.x.x.js

Looks like constructor actually allows custom error message https://github.com/jshttp/http-errors/blob/master/index.js#L135 & https://github.com/jshttp/http-errors/blob/master/index.js#L183

[http-errors] Allow message in constructor

---

definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-/react-navigation_v3.x.x.js

More context: https://github.com/react-navigation/react-navigation/pull/5398
Currently if you wrap a component that uses `defaultProps` with `withNavigation` or `withNavigationFocus` the `defaultProps` will become non-optional.
This PR updates the flow definition for these higher order components to use [`React.ElementConfig`](https://flow.org/en/docs/react/types/#toc-react-elementconfig) which correctly preserves the optionality of `defaultProps`.
These changes aren't required on flow >= 0.89, but most people aren't running the latest version because React Native usually lags behind by a few versions.
Here's a [before/after example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcykArgDt6KWINDwUuABYA5YgDcUAc2K5RggGKxa-UrKrwAPAAUmGUgC5QAbwC+AGlABhZlkFVBu …

Update type definition for `react-nativation`

---

definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js

When running `node cli/dist/cli.js run-tests ramda`, there were a number of failing tests.
Swapping the order of the definitions seem to resolve this.
Want to work on some updates to Ramda over the holidays, and fixing existing broken tests seems to be a good start!

[ramda_v0.x.x] fixed broken ramda tests

---

definitions/npm/webpack_v4.x.x/flow_v0.71.x-/webpack_v4.x.x.js
definitions/npm/webpack_v4.x.x/test_webpack_v4.x.x.js

Add options for the `{ devServer }` configuration. See [documentation](https://webpack.js.org/configuration/dev-server/#devserver).
Extended the simple shape test to make sure all the `{ devServer }` options are optional.

Add webpack devServer configuration options

---

definitions/npm/re-reselect_v2.x.x/flow_v0.67.1-/re-reselect_v2.x.x.js
definitions/npm/reselect_v3.x.x/flow_v0.47.x-/reselect_v3.x.x.js
definitions/npm/reselect_v4.x.x/flow_v0.47.x-/reselect_v4.x.x.js

The `resetRecomputations` methods returns: 0 not: void.
This is wrong both in Reselect and in Re-reselect (as that uses a copy-paste of the same def).
The (official) Typescript defs have this as 'number' as well:
https://github.com/reduxjs/reselect/blob/fda697a5b21959d55123bb8a3fdb6192f9cdc984/src/index.d.ts#L8

Fix return type for a Reselect method

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js

`_.sumBy` should allow SubType of the array it receives as it doesn't mutate the original array.

[lodash_v4.x.x] Allow type variance in _.sumBy

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js

The clearStore method is also available on the ApolloClient. See: https://github.com/apollographql/apollo-client/blob/183c81dbf0da2d8bc905cd2881dcaea9213f18f6/packages/apollo-client/src/ApolloClient.ts#L488

Add clearStore method to ApolloClient in react-apollo.

---

definitions/npm/react-redux_v5.x.x/flow_v0.89.x-/react-redux_v5.x.x.js

Recent context [here](https://github.com/flow-typed/flow-typed/pull/3012#issuecomment-452799153). Original context [here](https://github.com/flow-typed/flow-typed/pull/2018).
Though the default export does not exist in the ESM distro of `react-redux`, it does exist in the CJS distro. Node's ESM support doesn't allow named imports on CJS modules, which means the default import must be used when treating `react-redux` as CJS. Trying to use the ESM distro of `react-redux` with Node doesn't work either, since it attempts a named import on `react`, which only has a CJS distro.

[react-redux] Reintroduce default export

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js

The construct has been removed from Flow 0.89+ so at first I considered forking this into a `flow_v0.89.x-` directory, but then I realized that the `$SuperType<>` wrapper didn't really add anything and should probably just be `T` anyway.

[lodash_v4.x.x] Avoid use of $SuperType<>

---

definitions/npm/cloudinary_v1.x.x/flow_v0.25.x-/cloudinary_v1.x.x.js
definitions/npm/cloudinary_v1.x.x/test_cloudinary.js

Note that this library has only been partially typed.  I did include all the objects that are exported from the top level of this module, but marked them `__TODO__` (alias for `any`).  I'm not interested in typing those APIs out completely, as I don't personally use/need those APIs.  However, someone who's interested in them can easily update this definition later on.
I figured having a partially typed API is better than having no typing at all?  This way, coverage can be incrementally improved upon over time.  Is this considered a good or bad practice?

[cloudinary_v1.x.x] Add libdefs for cloudinary

---

definitions/npm/node-cache_v4.x.x/flow_v0.25.x-/node-cache_v4.x.x.js
definitions/npm/node-cache_v4.x.x/test_node-cache_v4.x.x.js

This PR adds `del()` and `flushAll()` methods for node-cache as in the documentation
https://github.com/mpneuried/nodecache

[node-cache_v4.x.x]Add del and flushAll methods to node-cache

---

definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_lensPath.js

It was not possible to use lensPath with an parameter which had the explicit type `string[]`. The problem is the expected Type `Array<string | number>`. Array has to be replaced with `$ReadOnlyArray`.
You can see an example about this assigning problem in the following flow examples:
[Error Example](https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqNgIYDWApgM4CCAMrpdgPKQDK2ATrugOYByqALYAjchwCq6fOgAU0BtgBcoGYy69QAH1DohojgEoA2gF0DoAN4BfZJgKNQ3SGI7kAJqAC8oIwEYATADMJogkFDT0jCzs6vx6YpLSMk4u7gaIdugO5AAeAA7ymLhKOvEcpl4+AcGhZFR0CtGc3HEiCVIEMrkFuEXY5iCgLrAclIhAA)
[Working Example](https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqNgIYDWApgM4CCAMrpdgPKQDK2ATrugOYByqALYAjchwCq6fOgAU0BtgBcoACQAlcsQAmTdNACe1Dh2L6APIy69QAH1DohojgD4AlKADeAX2SYCjUG5IMQ5yLVAAXlAAbQBGACYAZgBdRBIKGnpGFnYrfkcxSWkZIJCw …

[ramda_v0.x.x] use $ReadOnlyArray for lensPath

---

definitions/npm/axios_v0.11.x/test_axios-v0.11.js
definitions/npm/axios_v0.18.x/flow_v0.75.x-/axios_v0.18.x.js
definitions/npm/axios_v0.18.x/test_axios_v0.18.x.js

(stealing text from my commit):
The object returned from `axios.create` can be called just like the main `axios` export directly. The create function is used to produce default settings in a non-global way for `axios`.
The `Axios` class was marked as callable but only as a static form. I'm not sure what that was doing, but it didn't work in the case of `axios.create`, and removing the static bit didn't break any tests.
The callable signature on `AxiosExport` needs to remain, despite it extending the `Axios` class.
I added a simple callable test to an older `axios` as well.

make axios.create return a callable result

---

definitions/npm/react-testing-library_v5.x.x/flow_v0.67.1-/react-testing-library_v5.x.x.js
definitions/npm/react-testing-library_v5.x.x/flow_v0.67.1-/test_react-testing-library_v5.x.x.js

Current definitions don't include all query helpers defined in [`dom-testing-library`](https://testing-library.com/docs/api-queries). This PR adds the missing ones.
It also adds definition for [`waitForDomChange`](https://testing-library.com/docs/api-async#waitfordomchange) async helper.

[react-testing-library_v5.x.x] Add missing dom-testing-library helpers

---

definitions/npm/next_v7.x.x/flow_v0.53.x-/next_v7.x.x.js
definitions/npm/next_v7.x.x/test_next_v7.x.x.js

- Links to documentation: https://nextjs.org/docs/#exposing-configuration-to-the-server--client-side
- Link to GitHub or NPM: https://github.com/zeit/next.js
Other notes:
Just adds the type definition for the 'next/config' module.

[next_v7.x.x] Added next/config definition to nextjs flow types

---

definitions/npm/react-redux_v5.x.x/flow_v0.89.x-/react-redux_v5.x.x.js
definitions/npm/react-redux_v5.x.x/flow_v0.89.x-/test_connect.js
definitions/npm/react-redux_v5.x.x/flow_v0.89.x-/test_connectHOC.js

Addressing an issue with HOC described in #3072 by making it possible to provide inexact `OwnProps` type parameter and also by adding tests for the basic HOC use cases.
More example are welcome!

[react-redux_v5.x.x] Better support for HOC

---

definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/test_enzyme-v3.x.js

Added def for new `renderProp` method in enzyme 3.8:
- https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/renderProp.md
- https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/renderProp.md
I tried to add a test or two but wasn't able to run them locally? On a fresh clone, `./build_and_test_cli.sh` failed during runTests-test & install-test 🤷‍♂️.

[enzyme] Add new definition - Wrapper.renderProp

---

definitions/npm/validate.js_v0.x.x/flow_v0.25.x-/validate.js_v0.x.x.js

Changes all `any` types to `mixed`.  Tests all still pass, but now this library can safely be used from `@flow strict` modules.

[validate.js_v0.x.x] Use mixeds instead of anys

---

definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js

It has been ported from v5 back to v4.42.0: https://github.com/sequelize/sequelize/commit/d2428dd580c1adb0a4c763a30499da2d87b19b3d
Note that because of the drawbacks of how flow-typed typedef versioning is designed, it will fail to give users of < 4.42.0 an error if they use an `afterCommit` hook, even though it should because it isn't present in earlier versions. ¯\_(ツ)_/¯
@GAntoine once again, there are unrelated buggy flow errors in 0.88 and 0.89 😕

fix(sequelize): add a Transaction.afterCommit typedef

---

definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/test_enzyme-v3.x.js

- Link to GitHub or NPM: https://github.com/airbnb/enzyme
- Type of contribution: new definition fix
Other notes:
Following of #3059, there was several tests failing, mostly due to the Flow 0.88 changes where `Object`, `Function` are becoming aliases of `any`.  
Also React as `any` because imported outside the module.   
I couldn't find a way to test the closure case, hence commented.

[enzyme_v3.x.x] Fixes and updates

---

definitions/npm/apollo-client_v2.x.x/flow_v0.57.x-/apollo-client_v2.x.x.js

We need to export `FetchResult` as it is defined as `MutationOperation` return type from #2438 .
```
declare export type MutationOperation<T = Object> = (options: MutationBaseOptions<T>) => Promise<FetchResult<T>>
```
https://github.com/dudekaa/flow-typed/blob/2f65154d319b89387e3356ff8ab04ef381c1f176/definitions/npm/apollo-client_v2.x.x/flow_v0.57.x-/apollo-client_v2.x.x.js#L302
Not sure how it works for anybody until today?

Added export for FetchResult in apollo-client

---

definitions/npm/@zeit/title_v3.4.x/flow_v0.30.x-/title_v3.4.x.js
definitions/npm/@zeit/title_v3.4.x/test_title_v3.4.x.js

- Links to documentation: https://github.com/zeit/title
- Link to GitHub or NPM: https://github.com/zeit/title

[@zeit/title_v3.4.x] Add definitions

---

definitions/npm/algoliasearch_v3.x.x/flow_v0.56.x-v0.70.x/algoliasearch_v3.x.x.js
definitions/npm/algoliasearch_v3.x.x/flow_v0.71.x-/algoliasearch_v3.x.x.js
definitions/npm/algoliasearch_v3.x.x/test_algoliasearch-v3.x.x.js

- Links to documentation: https://github.com/algolia/algoliasearch-client-javascript#client-options
- Link to GitHub or NPM: https://github.com/algolia/algoliasearch-client-javascript/blob/develop/src/AlgoliaSearchCore.js#L100
Other notes:
Algolia can receive array of hosts for read/write

[algoliasearch_v3.x.x] allow host to be string or array of string

---

definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/redux-saga_v1.x.x.js
definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_createSagaMiddleware.js

- Fix the createSagaMiddleware return type to work correctly with redux applyMiddleware function
- Previous error: `Cannot call applyMiddleware because a callable signature is missing in object type`
- Remove use of deprecated `$Subtype`

[redux-saga_v1.x.x] Fix createSagaMiddleware

---

definitions/npm/query-string_v6.x.x/flow_v0.32.x-/query-string_v6.x.x.js
definitions/npm/query-string_v6.x.x/test_query-string_v6.x.x.js

- Links to documentation: https://github.com/sindresorhus/query-string#falsy-values
- Link to GitHub or NPM: https://github.com/sindresorhus/query-string
Other notes:
This is a followup to https://github.com/flow-typed/flow-typed/pull/2657
According to the query-string docs boolean, number, null, and void are also [valid values into `stringify`](https://github.com/sindresorhus/query-string#falsy-values)
```js
//=> 'foo=false'
queryString.stringify({foo: null});
//=> 'foo'
queryString.stringify({foo: undefined});
//=> ''
```
cc: @callumlocke @villesau

[query-string_v6.x.x] Allow number, boolean, null, and void for stringify values

---

definitions/npm/numeral_v2.x.x/flow_v0.25.x-/numeral_v2.x.x.js

Just fixed a couple small spelling errors I noticed

docs(numeral_v2.x.x): fix spelling errors

---

CONTRIBUTING.md

Best practices gives stronger impression that the instructions should be followed than tips.

Rename tips to best practices

---

definitions/npm/query-string_v6.x.x/flow_v0.32.x-/query-string_v6.x.x.js

- Links to documentation: [$ReadOnlyArray in Flow doc](https://flow.org/en/docs/types/arrays/#toc-readonlyarray)
- Link to GitHub or NPM: [Discussion in previous PR](https://github.com/flow-typed/flow-typed/pull/3114#pullrequestreview-199066242)
Other notes:
Fix Flow error, when you put to `stringify` function object, where key have value with strict type `Array<string>`, or `Array<number>`, or another.
After fixes in code below will no error:
```ts
const arr: Array<string> = ["hello", "world"];
queryString.stringify({ key: arr }); // No more Flow errors in this line
```

[query-string_v6.x.x] fix type for ObjectParameters

---

definitions/npm/react-hot-loader_v4.6.x/flow_v0.53.0-/react-hot-loader_v4.6.x.js
definitions/npm/react-hot-loader_v4.6.x/flow_v0.53.0-/test_react-hot-loader_4.6.x.js

- Links to documentation: [Look at **note** in Getting started](https://github.com/gaearon/react-hot-loader#getting-started)
- Link to GitHub or NPM: https://github.com/gaearon/react-hot-loader
Other notes:
In 4.6 version [was added new `root/hot` API](https://github.com/gaearon/react-hot-loader/releases/tag/4.6.0). I duplicated `react-hot-loader_v4.x.x` folder and added types for new features. And wrote some tests.
I'm new in Flow. Need thorough review, please.

[react-hot-loader_v4.6.x] add types for new API hot function

---

definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-/react-navigation_v3.x.x.js
definitions/npm/react-navigation_v3.x.x/test_react-navigation.js

These were deprecated in 3.0, but I forgot to remove them from the libdef.

[react-navigation] Get rid of deprecated Navigator exports in 3.0

---

definitions/npm/use-dark-mode_v2.2.x/flow_v0.30.x-/test_use-dark-mode_v2.2.x.js
definitions/npm/use-dark-mode_v2.2.x/flow_v0.30.x-/use-dark-mode_v2.2.x.js

- Links to documentation: https://github.com/donavon/use-dark-mode
- Link to GitHub or NPM: https://github.com/donavon/use-dark-mode

[use-dark-mode_v2.2.x] Add definitions

---

definitions/npm/react-redux_v5.x.x/flow_v0.89.x-/react-redux_v5.x.x.js
definitions/npm/react-redux_v5.x.x/flow_v0.89.x-/test_connect.js
definitions/npm/react-redux_v5.x.x/flow_v0.89.x-/test_connectInfer.js

Provides a `dispatch` property when no dispatch function is provided.
Downside is that it requires people to specify a `dispatch` property when they're using exact props on `Props`, but I think that's worth the cost of being able to correctly type the component. We use this pattern throughout our codebase.
Also apparently it makes it no longer possible to infer types in this use case. Didn't seem like a terrible cost.
@peter-leonov @villesau

[react-redux] Pass dispatch prop when no dispatch function provided.

---

cli/src/lib/npm/npmLibDefs.js

Previous PR: https://github.com/flow-typed/flow-typed/pull/3117
this happened right after merging the retrying: https://travis-ci.org/flow-typed/flow-typed/jobs/487150074
Which means the retry was not as successful as thought. Let's try 1s delay to see if it's any better.

add 1s delay for 404 retrying

---

definitions/npm/moment_v2.x.x/flow_v0.25.x-/moment_v2.x.x.js
definitions/npm/moment_v2.x.x/test_moment-v2.js

- Links to documentation: https://momentjs.com/docs/#/customization/now/
- Link to GitHub or NPM: https://github.com/moment/moment/
Other notes:
Noticed the definition for `moment.now()` was missing while working on a project.

Add static now() to moment libdef

---

definitions/npm/@react-navigation/core_v3.x.x/flow_v0.60.x-/core_v3.x.x.js
definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-/react-navigation_v3.x.x.js

This type is used in two separate places in the libdef. I've updated it to use `$Shape` and an exact type.
This is a follow-up from a review comment to #3139.

[react-navigation] Introduce SafeAreaViewInsets type

---

definitions/npm/react-testing-library_v5.x.x/flow_v0.67.1-/react-testing-library_v5.x.x.js
definitions/npm/react-testing-library_v5.x.x/flow_v0.67.1-/test_react-testing-library_v5.x.x.js

The object returned by the `render` function in react-testing-library contains a function called `asFragment`. This change adds types for that, mimicking the library's TypeScript definition:
https://github.com/kentcdodds/react-testing-library/blob/d41366594f55b49cb5ced38d42195af2ac5eddaa/typings/index.d.ts#L19
- Links to documentation: https://github.com/kentcdodds/react-testing-library#example
- Link to GitHub or NPM: https://github.com/kentcdodds/react-testing-library

Add missing asFragment to react-testing-library

---

definitions/npm/semver_v5.6.x/flow_v0.92.x-/semver_v5.6.x.js
definitions/npm/semver_v5.6.x/test_semver.js

- Links to documentation: https://www.npmjs.com/package/semver
- Link to GitHub or NPM: https://github.com/npm/node-semver
Other notes:s
This is just an update to the flowtype definitions for the semver library, bumping from 5.1 to the current 5.6. It builds off of the 5.1 definitions.

Add definitions for semver 5.6

---

definitions/npm/copy-to-clipboard_v3.x.x/flow_v0.25.x-/copy-to-clipboard_v3.x.x.js
definitions/npm/copy-to-clipboard_v3.x.x/test_copy-to-clipboard_v3.x.x.js

- Links to documentation: https://github.com/sudodoki/copy-to-clipboard
- Link to GitHub or NPM: https://github.com/sudodoki/copy-to-clipboard
Other notes: Just scope the `Options` type to the module, prevent global types pollution.

[copy-to-clipboard-v3.x.x] Scope Options type to module

---

definitions/npm/firebase_v5.x.x/flow_v0.34.x-/firebase_v5.x.x.js
definitions/npm/firebase_v5.x.x/flow_v0.34.x-/test_firebase.js

Changelog:
- Make the `FieldValue` definition in sync with official TS definition
- Make the `DocumentChange` definition in sync with official TS definition.
The added test cases are mostly from the official docs of Firebase, whose link is included below..
- [FieldValue](https://firebase.google.com/docs/firestore/manage-data/add-data)
- [DocumentChange](https://firebase.google.com/docs/firestore/query-data/listen)
- [FieldValue](https://github.com/firebase/firebase-js-sdk/blob/548e4a7d235bd96fd8306f2f3490a6c55b923509/packages/firestore-types/index.d.ts#L1245-L1291)
- [DocumentChange](https://github.com/firebase/firebase-js-sdk/blob/4d82d1e6e697d2a3fef09757a7cac3700116c052/packages/firestore-types/index.d.ts#L1166-L1187)
- Type of …

[firebase_v5.x.x] Add missing firestore definitions

---

definitions/npm/firebase_v5.x.x/flow_v0.34.x-/firebase_v5.x.x.js
definitions/npm/firebase_v5.x.x/flow_v0.34.x-/test_firebase.js

Changelog:
- Added `enableNetwork`, `disableNetwork` and `enablePersistence` methods for `firebase.firestore` that currently exist in TS but not in flow-typed.
- https://github.com/firebase/firebase-js-sdk/blob/4d82d1e6e697d2a3fef09757a7cac3700116c052/packages/firestore-types/index.d.ts#L119-L139
- https://github.com/firebase/firebase-js-sdk/blob/4d82d1e6e697d2a3fef09757a7cac3700116c052/packages/firestore-types/index.d.ts#L188-L204
- Added missing type `firebase.firestore.Settings` and `firebase.firestore.PersistanceSettings`.
- https://github.com/firebase/firebase-js-sdk/blob/4d82d1e6e697d2a3fef09757a7cac3700116c052/packages/firestore-types/index.d.ts#L40-L99
- Added many missing `isEqual` methods that exist in TS but not in flow-typed.
- Added the `path` field to …

[firebase_v5.x.x] Add missing firestore definitions and fix incorrect definitions

---

definitions/npm/angular_v1.5.x/flow_v0.47.x-/angular_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_angular_interval_log_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_angular_timeout_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_angular_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_utility_functions_v1.5.x.js

- Links to documentation: https://docs.angularjs.org/api/ng/service/$interval and https://docs.angularjs.org/api/ng/service/$log
- Link to GitHub or NPM: https://www.npmjs.com/package/angular
- Type of contribution: addition (and fix for warnings)
Other notes:
Added types for `$log` and `$interval` (`$Log` and `$Interval` respectively).
Also there were many test warnings due to frequent use of `Object` and `Function` causing `$ExpectedError` not to throw where it should.
My solution was to replace all `Object` with `{}`, and any `Function` that were causing warnings were changed to `(...args: Array<*>) => *`.
All `Object` cases were replaced, not all `Function` were though.
Feedback very welcomed.

Add $Log and $Interval to angular 1.5.x type; fix test warnings

---

definitions/npm/webpack_v4.x.x/flow_v0.71.x-/webpack_v4.x.x.js

- Links to documentation: https://webpack.js.org/api/node/#webpack
Other notes: Docs specifically point out that if a callback isn't provided, then a `Compiler` instance is returned. Since the no-callback case is an explicitly supported input, the callback param should be optional.

callback is optional according to webpack docs 

---

definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/test_enzyme-v3.x.js

- Links to documentation: https://airbnb.io/enzyme/docs/api/selector.html
- Link to GitHub or NPM: https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/ReactWrapper.js
Other notes:
When using Enzyme's `find` methods:
```js
const wrapper = mount(<RootComponent />)
const child = wrapper.find(SomeDeeperComponent)
```
\- prior to this PR, `child` has a type of `Wrapper<RootComponent>`, but it ought to have a type of `Wrapper<SomeDeeperComponent>`.
This PR special-cases the find/parent/closest/children methods so that if you pass a component type to them, the result will be of that component type.
---
Enzyme also supports passing strings or object literals to `find` - eg `wrapper.find(".foo")` - in which case we don't have enough type information to …

Fix typing on enzyme's Wrapper.find(Component)

---

definitions/npm/knex_v0.16.x/flow_v0.75.x-/knex_v0.16.x.js
definitions/npm/knex_v0.16.x/flow_v0.75.x-/test_knex_v0.16.x.js

- Links to documentation: https://knexjs.org/
- Link to GitHub or NPM: https://www.npmjs.com/package/knex
Other notes:
Sorry for the second PR on this so soon -- I started applying the new definition to some more microservices I was refactoring to be fully flow-typed and found a few more inconsistencies between the docs and the defs.
(Out of curiosity -- I'd be lying out of my ass if I didn't say I'm using the TypeScript definitions as a guide -- what's the general thoughts about breaking changes by migrating/transforming the TS defs to Flow format, since those are maintained by the actual project?)

Further improved knex support for Flow

---

definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js

- Links to documentation: https://ant.design/docs/react/introduce
- Link to GitHub or NPM: https://github.com/ant-design/ant-design
In #3196, I erroneously made event arguments in a few event handlers optional. They are always provided and so should be required. 
Sorry for the error, I had a misunderstanding about matching function types.

antd handler fixes

---

definitions/package.json
definitions/yarn.lock

I encountered ESLint syntax errors on function calls with generics, and no param: `useWhatever<Type>()`, which has been fixed in later versions.
So the upgrades.
I bumped into eslint/eslint/issues/11471, but it's not fixed so we can upgrade safely :laughing:

Upgrade ESLint dependencies

---

definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/test_enzyme-v3.x.js

- Links to documentation: https://airbnb.io/enzyme/
- Link to GitHub or NPM: https://github.com/airbnb/enzyme
Other notes: 
Current typing would require to refine the param type. Whereas `React$Node` already allows Arrays.
See https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudACY16MUlzBQArgDtGGONLCEa5QgAoxAcwBc1boQAkAOThCwAHzABBfPlIBPADy0Ghk0IB8ASl0A3OBgC-KjKqmqoYGCOAhi+YMAeqF7BoeoRYADa0bHxHgA0UTFxCQC6SfyRlWDpVahAA

[enzyme_v3.x.x] Simplify contains* helpers type

---

definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js

Links to documentation: https://ant.design/components/layout
Link to GitHub or NPM: https://github.com/ant-design/ant-design
Type of contribution: new definition
Adding missing `Layout.Footer`

[antd] Add Footer static to Layout

---

definitions/npm/verror_v1.10.x/flow_v0.30.x-/test_verror_v1.10.x.js
definitions/npm/verror_v1.10.x/flow_v0.30.x-/verror_v1.10.x.js

- Links to documentation: https://github.com/joyent/node-verror
- Link to GitHub or NPM: https://github.com/joyent/node-verror
- Type of contribution: new definition 
Other notes:
I struggled a bit making it accept commonjs default and named exports as well as constructor and callable signature for classes...
It currently works for commonjs, but named exports for ES modules are not recognized.
`import VError, { WError } from 'verror'; // Error` 
One would need to:
```
import VError from 'verror';
const { WError } = VError;
````
If someone see a better solution.
See https://github.com/joyent/node-verror/blob/master/lib/verror.js#L16-L23

[verror_v1.10.x] Add definitions

---

definitions/npm/@storybook/addon-knobs_v3.x.x/flow_all/addon-knobs_v3.x.x.js
definitions/npm/@storybook/addon-knobs_v3.x.x/test_addon-knobs_v3.x.x.js

Hello!
This pull request makes a fix to the `@storybook/addon-knobs` `array` function to allow non-strings to be returned. The following should not result in an error:
```js
let arrayVal: Array<number> = array("Array assigned to non-string array variable", [1, 2]);
```
The code below is taken from the source code, and it returns `obj` as is if it's `null` or not of type `object`
```js
const escapeStrings = obj => {
if (typeof obj === 'string') {
return escape(obj);
}
if (obj == null || typeof obj !== 'object') {
return obj;
}
if (Array.isArray(obj)) {
const newArray = obj.map(escapeStrings);
const didChange = newArray.some((newValue, key) => newValue !== obj[key]);
return didChange ? newArray : obj;
}
return Object.entries(obj).reduce((acc, [key, oldValue]) => {
const newValue = …
```

Fix addon-knobs array type

---

definitions/npm/@automattic/tree-select_v1.x.x/flow_v0.25.x-/test_tree-select_v1.x.x.js
definitions/npm/@automattic/tree-select_v1.x.x/flow_v0.25.x-/tree-select_v1.x.x.js

- Links to documentation: https://github.com/Automattic/wp-calypso/tree/master/packages/tree-select
- Link to GitHub or NPM: https://www.npmjs.com/package/@automattic/tree-select
These are the definitions we've been using on internal projects.

@automattic/tree-select definitions

---

definitions/npm/lodash-es_v4.x.x/flow_v0.63.x-/lodash-es_v4.x.x.js
definitions/npm/lodash-es_v4.x.x/flow_v0.63.x-/test_modules-lodash-es-v4.x.x.js

Sadly some module bundlers still can't manage to shrink size to a minimum when using named imports from `lodash-es`, see e.g. https://github.com/rollup/rollup/issues/1403 and https://github.com/rollup/rollup/issues/691. Because of this, it makes sense to include standalone module definitions as well.

[lodash-es_v4.x.x] add defs for standalone lodash-es modules

---

definitions/npm/indent-string_v3.2.x/flow_v0.25.x-/indent-string_v3.2.x.js
definitions/npm/indent-string_v3.2.x/test_indent-string_v3.2.x.js

- Links to documentation: https://github.com/sindresorhus/indent-string
- Link to GitHub or NPM: https://github.com/sindresorhus/indent-string
Other notes:
In 3.2.0 the `indent` argument in the 3rd parameter has been replaced by an options object to accommodate further customization of the function's behavior. This is a breaking change from 3.1.0 and requires a new libdef version for `indent-string`.
See the [README for indent-string](https://github.com/sindresorhus/indent-string) for a quick example.

use options argument introduced in indent-string 3.2.0

---

definitions/npm/knex_v0.15.x/flow_v0.38.x-v0.74.x/knex_v0.15.x.js
definitions/npm/knex_v0.15.x/flow_v0.38.x-v0.74.x/test_knex_v0.15.x.js
definitions/npm/knex_v0.15.x/flow_v0.75.x-/knex_v0.15.x.js
definitions/npm/knex_v0.15.x/flow_v0.75.x-/test_knex_v0.15.x.js
definitions/npm/knex_v0.16.x/flow_v0.75.x-/knex_v0.16.x.js
definitions/npm/knex_v0.16.x/flow_v0.75.x-/test_knex_v0.16.x.js

- Links to documentation: https://knexjs.org/#Builder-truncate
- Link to GitHub or NPM: https://github.com/tgriesser/knex
Other notes:
I added `.truncate()` for both knex 0.15 & knex 0.16. 0.15 is the version I was using when I first noticed the missing method definition, but I figured I might as well update the newer 0.16 while I was at it.

Add truncate to knex definition

---

definitions/npm/@storybook/react_v5.x.x/flow_v0.25.x-v0.71.x/react_v5.x.x.js
definitions/npm/@storybook/react_v5.x.x/flow_v0.25.x-v0.71.x/test_react_v5.x.x.js
definitions/npm/@storybook/react_v5.x.x/flow_v0.72.x-/react_v5.x.x.js
definitions/npm/@storybook/react_v5.x.x/flow_v0.72.x-/test_react_v5.x.x.js

The migration from @storybook/react-v4 to @storybook/react-v5 doesn't involve any breaking API changes https://github.com/storybooks/storybook/blob/next/MIGRATION.md#from-version-41x-to-50x so I'm just copying over the existing definitions so they can be used with v5.
- Links to documentation: https://storybook.js.org/docs/basics/introduction/
- Link to GitHub or NPM: https://www.npmjs.com/package/@storybook/react
Other notes:

Clone @storybook/react-v4.x.x to @storybook/react-v5.x.x

---

definitions/npm/@storybook/react_v5.x.x/flow_v0.72.x-/react_v5.x.x.js
definitions/npm/@storybook/react_v5.x.x/flow_v0.72.x-/test_react_v5.x.x.js

Cleaning this up since the bespoke `Renderable` type isn't accurate (it can be any react element, e.g. a string, or a number would be valid). Also gets rid of the existential type, so thats nice.
- Links to documentation: https://storybook.js.org/docs/basics/introduction/
- Link to GitHub or NPM: https://www.npmjs.com/package/@storybook/react
Other notes:

[@storybook/react v5.x.x] Use React$Node instead of a bespoke type

---

definitions/npm/autobind-decorator_v2.x.x/flow_v0.25.x-/autobind-decorator_v2.x.x.js
definitions/npm/autobind-decorator_v2.x.x/test_autobind-decorator_v2.x.x.js

- Links to documentation:  https://github.com/andreypopp/autobind-decorator
- Link to GitHub or NPM: https://github.com/andreypopp/autobind-decorator
Other notes:
Typescript typings - https://github.com/andreypopp/autobind-decorator/blob/master/index.d.ts

Add type-defs autobind-decorator using typescript defs as a baseline

---

definitions/npm/knex_v0.12.x/flow_v0.38.x-v0.74.x/knex_v0.12.x.js
definitions/npm/knex_v0.13.x/flow_v0.38.x-v0.74.x/knex_v0.13.x.js
definitions/npm/knex_v0.14.x/flow_v0.38.x-v0.74.x/knex_v0.14.x.js
definitions/npm/knex_v0.14.x/flow_v0.75.x-/knex_v0.14.x.js
definitions/npm/knex_v0.15.x/flow_v0.38.x-v0.74.x/knex_v0.15.x.js
definitions/npm/knex_v0.15.x/flow_v0.75.x-/knex_v0.15.x.js
definitions/npm/knex_v0.16.x/flow_v0.75.x-/knex_v0.16.x.js

- Links to documentation: https://knexjs.org/#Builder-update
- Link to GitHub or NPM: https://github.com/tgriesser/knex
Knex's `update()` method supports optional `returning` parameter (array of strings) on many SQL-dialects. see https://knexjs.org/#Builder-update
Flow-typed definition missed this. This pull-request adds it to all knex versions.

Knex: add missing "returning" parameter to update()

---

definitions/npm/react-intl_v2.x.x/flow_v0.25.x-v0.52.x/react-intl_v2.x.x.js
definitions/npm/react-intl_v2.x.x/flow_v0.25.x-v0.52.x/test_react-intl_v2.x.x.js
definitions/npm/react-intl_v2.x.x/flow_v0.53.x-v0.56.x/react-intl_v2.x.x.js
definitions/npm/react-intl_v2.x.x/flow_v0.53.x-v0.56.x/test_react-intl_v2.x.x.js
definitions/npm/react-intl_v2.x.x/flow_v0.57.x-v0.62.x/react-intl_v2.x.x.js
definitions/npm/react-intl_v2.x.x/flow_v0.57.x-v0.62.x/test_react-intl_v2.x.x.js
definitions/npm/react-intl_v2.x.x/flow_v0.63.x-/react-intl_v2.x.x.js
definitions/npm/react-intl_v2.x.x/flow_v0.63.x-/test_react-intl_v2.x.x.js

- Links to documentation: https://github.com/yahoo/babel-plugin-react-intl/blob/6d364b01554f80433067202f342d6b516b03daaa/src/index.js#L313-L323
- Link to GitHub or NPM: #3243 
Other notes:
As described in #3243 `defineMessages` used along with `babel-plugin-react-intl` will drop all other fields other than `{ id }` and `{ defaultMessage }`. 
In order to avoid missing interpolation in runtime this PR hardens type passed to `defineMessages` to be `$Exact`

[react-intl_v2.x.x] Pass $Exact type to defineMessages (#3243)

---

definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_logic.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_logic.js

`and` and `or` don’t necessarily return `true` or `false`, instead they return their first or second argument. (The docs are a bit unclear here as well, but the correct behaviour is explained when you click “expand parameters”.)
- Links to documentation: [and](https://ramdajs.com/docs/#and), [or](https://ramdajs.com/docs/#or)
- Link to GitHub or NPM: [and](https://github.com/ramda/ramda/blob/v0.26.1/source/and.js), [or](https://github.com/ramda/ramda/blob/v0.26.1/source/or.js)
Other notes: thanks for maintaining this repository

Changed `and` and `or` to reflect actual behaviour

---

definitions/npm/jsuri_v1.x.x/flow_v0.25.x-/jsuri_v1.x.x.js

Fix the type used for `hasQueryParam` to match the documented signature shown here: 
- https://github.com/derek-watson/jsUri/blame/master/README.md#L117
- https://github.com/derek-watson/jsUri/blob/master/Uri.js#L277
Other notes:
N/A

fix: update hasQueryParam to match documented signature

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js

That definition conflicted with the definition where an array is passed in the first parameter, because an array is Object too, and flow couldn't deside which case to select.

[lodash_v4.x.x] Fix orderBy types for object case

---

definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-/react-navigation_v3.x.x.js

This change corresponds to the following changes from the `react-navigation` repo:
1. `TabBarTop` is now `MaterialTopTapBar`.
2. `TabBarBottom` is now `BottomTabBar`.
3. `BottomTabBar` supports a custom `getButtonComponent` prop, which returns a `React.ComponenType`.
This is covered by the following `react-navigation` Flow libdef PRs:
1. https://github.com/react-navigation/react-navigation/pull/5702
2. https://github.com/react-navigation/react-navigation/pull/5648
3. https://github.com/react-navigation/react-navigation/pull/5800

[react-navigation] Update TabBar definitions

---

definitions/npm/@react-navigation/core_v3.x.x/flow_v0.60.x-/core_v3.x.x.js
definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-/react-navigation_v3.x.x.js

This change corresponds to the following changes from the `react-navigation` repo:
1. Add `isTransitioning` property to `NavigationState` so custom navigators can inspect it.
2. Make `StackNavigatorConfig` a `$Shape`, which is correct since none of the properties are required.
3. Add the `descriptor` property to `NavigationScene` and export `NavigationDescriptor`.
This is covered by the following `react-navigation` Flow libdef PRs:
1. https://github.com/react-navigation/react-navigation/pull/5801

[react-navigation] Support custom navigators using Transitioner

---

definitions/npm/koa_v2.0.x/flow_v0.47.x-v0.92.x/koa_v2.0.x.js
definitions/npm/koa_v2.0.x/flow_v0.93.x/koa_v2.0.x.js
definitions/npm/koa_v2.0.x/flow_v0.94.x-/koa_v2.0.x.js
definitions/npm/koa_v2.x.x/flow_v0.47.x-v0.92.x/koa_v2.x.x.js
definitions/npm/koa_v2.x.x/flow_v0.93.x/koa_v2.x.x.js
definitions/npm/koa_v2.x.x/flow_v0.94.x-/koa_v2.x.x.js

- Links to documentation: https://github.com/pillarjs/cookies#cookiesset-name--value---options--
- Link to GitHub or NPM: https://github.com/koajs/koa
Other notes:
Here's the source-code which shows that both maxAge and domain are optional for cookies.
https://github.com/pillarjs/cookies/blob/master/index.js#L150-L175

[koa] fix ctx.cookies.set() options

---

definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_pipe.js

- Links to documentation: https://ramdajs.com/docs
- Link to GitHub or NPM: https://github.com/ramda/ramda 
Other notes:
Now fist function can get unlimited arguments
[FLOW.JS TRY >](https://flow.org/try/#0FDAmFMGMBsEMCdwAIAuBPADsgqgOwWgGK4A8AggDRIBKAfEgLxIAUsAXEmQJSP3UDcIdFiQBZWAGtwABQCWWYoyTl4AcwDOFauBQBXeLlrNgSUywB0lhBo5k16ng3qxcaKibN4CxEi7c0dfUNgR3pmZktza3Vbe1CAvQMuQRAIGARkADcEJGkASWkAUQ4Abw9TEgAhKgBhKgARKkKqQhaAOQBGDgirDgAqeOqkQjaAVg4veCJSVqQ+2iNys1NYACMOEY73ZeXVyAn8KZ8hmtptndNIUAPvUjqkerOkJeWIG6PSRqRCp5ezcAAZu9piRmsNfhdTADVBsxhQllwOAASGqwaDQEjiKRyBS4dpbYZjM7AAC+IDAUDgiCQ2XgSABuC6LHYSFwugAtqtwPAKOskOoUPBZLhVBR9khVgB7SXQcAuCjXJAAbRKAB9UOABRwpTK5bgkKqSQBdeJszncwRpKlZHIMgBM3VgTLNXPg8QFQpFlspGRpttwAGZHUyPcLVPEdbKXN70tTafTcAAWYPa6VR3DxJWhkVGmPWv10hnjZlMrOCs …

[ramda_0.26.x] Refactor pipe()

---

definitions/npm/@react-navigation/core_v3.x.x/flow_v0.92.x-/core_v3.x.x.js
definitions/npm/react-navigation_v3.x.x/flow_v0.92.x-/react-navigation_v3.x.x.js

In my last PR I flipped the order of these around to fix an error, but turns out that was just crippling the type. The correct solution here, to guarantee that the `$PropertyType` won't error if its type parameter don't have the property, is to use an unsealed object type.

[react-navigation] Fix NavigationScreenProp.getParam type

---

definitions/npm/escape-string-regexp_v2.x.x/flow_v0.28.x-/escape-string-regexp_v2.x.x.js
definitions/npm/escape-string-regexp_v2.x.x/test_escape-string-regexp_v2.x.x.js

- Links to documentation: https://github.com/sindresorhus/escape-string-regexp
- Link to GitHub or NPM: https://www.npmjs.com/package/escape-string-regexp
Other notes:
Basically the same as
https://github.com/flow-typed/flow-typed/tree/master/definitions/npm/escape-string-regexp_v1.x.x

[escape-string-regexp_v2.x.x] Add definition

---

definitions/npm/path-to-regexp_v2.x.x/flow_v0.25.x-/path-to-regexp_v2.x.x.js
definitions/npm/path-to-regexp_v2.x.x/test_path-to-regexp_v2.x.x.js

- Links to documentation: https://github.com/pillarjs/path-to-regexp
- Link to GitHub or NPM: https://github.com/pillarjs/path-to-regexp
Other notes:
via: https://github.com/flow-typed/flow-typed/issues/3274

[path-to-regexp_v2] fix: Convert module path-to-regexp from ESM to CommonJS

---

definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js
definitions/npm/winston_v3.x.x/test_winston_v3.x.x.js

- Links:
https://github.com/winstonjs/logform
https://github.com/winstonjs/winston
- Type of contribution: addition and refactor
Changes:
- All winston types are exported from libdef to make them available in external code
- Callable signature added for winston.format()
- has() method added for winston.Container

Export types from winston libdef

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-v0.52.x/react-router-dom_v4.x.x.js
definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-v0.52.x/test_react-router-dom.js
definitions/npm/react-router-dom_v4.x.x/flow_v0.53.x-v0.62.x/react-router-dom_v4.x.x.js
definitions/npm/react-router-dom_v4.x.x/flow_v0.53.x-v0.62.x/test_react-router-dom.js
definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js
definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/test_react-router-dom.js
definitions/npm/react-router-dom_v5.x.x/flow_v0.63.x-/react-router-dom_v5.x.x.js
definitions/npm/react-router-dom_v5.x.x/flow_v0.63.x-/test_react-router-dom.js
definitions/npm/react-router_v4.x.x/flow_v0.30.x-v0.52.x/react-router_v4.x.x.js
definitions/npm/react-router_v4.x.x/flow_v0.30.x-v0.52.x/test_react-router.js
definitions/npm/react-router_v4.x.x/flow_v0.53.x-v0.62.x/react-router_v4.x.x.js
definitions/npm/react-router_v4.x.x/flow_v0.53.x-v0.62.x/test_react-router.js
definitions/npm/react-router_v4.x.x/flow_v0.63.x-/react-router_v4.x.x.js
definitions/npm/react-router_v4.x.x/flow_v0.63.x-/test_react-router.js
definitions/npm/react-router_v5.x.x/flow_v0.63.x-/react-router_v5.x.x.js

- Links to documentation: https://github.com/ReactTraining/history#blocking-transitions
- Link to GitHub or NPM: https://github.com/ReactTraining/history/blob/5f367d8cbdaf91d7f64e2efdbb9196feb0859f3f/modules/__tests__/TestSequences/TransitionHookArgs.js#L21
Other notes:
There's a bug in all the `react-router-*` types. The `block()` method never supported returning `void` or `boolean` values, it always expects the return to be a `?string` instead. This PR fixes this, and closes #3007

react-router correction which fixes #3007

---

definitions/npm/archiver_v2.x.x/flow_v0.54.x-/archiver_v2.x.x.js
definitions/npm/archiver_v2.x.x/flow_v0.54.x-/test_archiver_v2.x.x.js

- Links to documentation: https://www.archiverjs.com/
- Link to GitHub or NPM: https://github.com/archiverjs/node-archiver
Other notes:
- Convert ESM to CommonJS
- Fix tests for `Function` as `any`
- Add export for all types

[archiver_v2.x.x] Convert ESM to CommonJS

---

definitions/npm/jest_v24.x.x/flow_v0.39.x-/jest_v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.39.x-/test_jest-v24.x.x.js

Update the Flow type for Jest's Matcher object. The current definition is a function accepting two argument but it should take an arbitrary number of parameters which are passed to the matcher.
- Links to documentation: https://jestjs.io/docs/en/expect#custom-matchers-api
- Link to GitHub or NPM: https://github.com/facebook/jest/blob/master/packages/expect/src/jestMatchersObject.ts#L84
- Renamed parameters to received and actual
- Changed actual to a rest parameter

[jest_v24.x.x] Update JestMatcher definition

---

definitions/npm/archiver_v3.x.x/flow_v0.88.x-/archiver_v3.x.x.js
definitions/npm/archiver_v3.x.x/flow_v0.88.x-/test_archiver.js

- Links to documentation: https://www.archiverjs.com/
- Link to GitHub or NPM: https://github.com/archiverjs/node-archiver
Other notes:
This definition based on a previous version [2.x.x](https://github.com/flow-typed/flow-typed/tree/master/definitions/npm/archiver_v2.x.x/flow_v0.54.x-) without changes, because of new [release](https://github.com/archiverjs/node-archiver/releases/tag/3.0.0) 
> remove support for versions under 6

[archiver_v3.x.x] Add new definition

---

definitions/npm/apollo-client_v2.x.x/flow_v0.57.x-/apollo-client_v2.x.x.js
definitions/npm/apollo-client_v2.x.x/test_apollo-client_v2.x.x.js

- Links to documentation: https://www.apollographql.com/docs/react/api/apollo-client#ApolloClient.query
- Link to GitHub or NPM: https://github.com/apollographql/apollo-client/
This fixes an issue where variables could not be passed to query/mutate functions and adds a regression test.
Fixes #2888

[apollo-client] Fix issue with query/mutate functions and passing variables

---

definitions/npm/redux_v3.x.x/flow_v0.89.x-/redux_v3.x.x.js
definitions/npm/redux_v3.x.x/flow_v0.89.x-/test_applyMiddleware.js
definitions/npm/redux_v3.x.x/flow_v0.89.x-/test_combineReducers.js
definitions/npm/redux_v3.x.x/flow_v0.89.x-/test_createStore.js
definitions/npm/redux_v3.x.x/flow_v0.89.x-/test_custom_dispatch.js

- Links to documentation: https://redux.js.org/
- Link to GitHub or NPM: https://github.com/reduxjs/redux
---
Other notes:
- Adding since `$Subtype` is deprecated after 0.89
- Rest annotations follow https://github.com/flow-typed/flow-typed/pull/3223
- This is my first contribution to this repo. I'm not sure if I've done everything correctly: 
My `$ ./build_and_test_cli.sh` failed on a few libraries that are not related. But I expect things should work since most of my definitions follow existing ones 😅

Annotate redux v3 for flow past 0.89

---

definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js

1. Add definition for Input.Password added in v3.12.0 
- [Links to documentation](https://ant.design/components/input/#Input.Password-(Added-in-3.12.0)): 
- [Link to GitHub or NPM](https://github.com/ant-design/ant-design/blob/master/components/input/Password.tsx): 
2. Fix flow error when using Form.create - mixed is not a function
- [Links to documentation](https://ant.design/components/form/#Form.create(options)): 
- [Link to GitHub or NPM](https://github.com/ant-design/ant-design/blob/2d8396bad79a086ae57b3ef462e681e81786f02d/components/form/Form.tsx#L137): 

[antd_v3.x.x] Add definition for Input.Password and Fix definition error for Form.create

---

definitions/npm/history_v4.9.x/flow_v0.25.x-/history_v4.9.x.js
definitions/npm/history_v4.9.x/flow_v0.25.x-/test_history_v4.9.x.js

Update types to work with the new bundling and export format of the history module.
- Links to documentation: https://github.com/ReactTraining/history/releases/tag/v4.9.0
- Link to GitHub or NPM: https://github.com/ReactTraining/history/
- Type of contribution: new definition for 4.9.x version

[history@4.9.x] Update definitions to match new bundling

---

definitions/npm/jest_v24.x.x/flow_v0.39.x-/jest_v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.39.x-/test_jest-v24.x.x.js

Add toBeEnabled definition to dom testing for jest@24.x.x 
- Links to documentation: https://github.com/testing-library/jest-dom#tobeenabled
Other notes:

[jest@24.x.x] add toBeEnabled to dom testing def

---

definitions/npm/react-transition-group_v2.x.x/flow_v0.60.x-/react-transition-group_v2.x.x.js
definitions/npm/react-transition-group_v2.x.x/test_react-transition-group.js

react-transition-group only calls its child-function if the state is one of entering/entered/exiting/exited - not 'unmounted'.  (Transition's render() function bails early if the state is 'unmounted' - https://github.com/reactjs/react-transition-group/blob/65cd9f83309ade93aa9c21d6f6b3c18cbf9e5f27/src/Transition.js#L330-L334)
The documentation example here - http://reactcommunity.org/react-transition-group/transition - would complain with `Cannot get transitionStyles[state] because property unmounted is missing in object literal`.

Remove 'unmounted' from react-transition-group

---

definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js

This PR corrects previous one #3314 
- [Links to documentation](https://ant.design/components/form/#Form.create(options))
- [Link to GitHub or NPM](https://github.com/ant-design/ant-design/blob/2d8396bad79a086ae57b3ef462e681e81786f02d/components/form/interface.ts)
Other notes:
[PR Comment](https://github.com/flow-typed/flow-typed/pull/3314#discussion_r282152527)

[antd_v3.x.x] Fix return type of Form.create()(C)

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js

- Links to documentation: https://lodash.com/docs/4.17.11#flatten https://lodash.com/docs/4.17.11#zip
Other notes:
Both these functions do not mutate there arguments so they should take $ReadOnlyArray

lodash v4 - accept read only array for zip/flatten

---

definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_logic.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_logic.js

- https://ramdajs.com/docs/#ifElse
- #2411
Other notes:
This fixes the issue found in #2411 where `test` could not be used with `ifElse` because `test` is automatically curried, which relies upon variadic arguments.
As another note, I noticed as part of working on this that some of our tests have a lot of cross-dependencies. For example, the `ifElse` test also depended on `is`. I worry that if something happens with `is`, the test for `ifElse` can become invalid. Perhaps instead we can write our tests by only using a single Ramda function at a time, so our test doesn't potentially become a lie built atop another lie. For example, if `is` returns or takes `any` it could invalidate the `ifElse` test entirely. It also conflates what's really being tested. In the …

fix Ramda ifElse to work with variadic arguments

---

definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_math.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/test_ramda_v0.x.x_math.js

- [repl](https://ramdajs.com/repl/#?const%20later%20%3D%20new%20Date%28%29%0Aconst%20now%20%3D%20new%20Date%28%29%0Alater.setSeconds%28later.getSeconds%28%29%20%2B%201%29%0Asubtract%28later%2C%20now%29%0A%2F%2F%20Uncomment%20to%20see%20variations.%0A%2F%2F%20subtract%28later%2C%202%29%0A%2F%2F%20subtract%282%2C%20later%29) and [subtract documentation](https://ramdajs.com/docs/#subtract)
Other notes:
Ramda's `subtract` works with every variation of a `number` and a `Date`, but always returns a `number` (see [this Ramda repl](
https://ramdajs.com/repl/#?const%20later%20%3D%20new%20Date%28%29%0Aconst%20now%20%3D%20new%20Date%28%29%0Alater.setSeconds%28later.getSeconds%28%29%20%2B%201%29%0Asubtract%28later …

add date support to ramda subtract

---

definitions/npm/@react-navigation/core_v3.x.x/flow_v0.60.x-v0.91.x/core_v3.x.x.js
definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-v0.91.x/react-navigation_v3.x.x.js

This pr applies #3266 to the typedef for flow < 0.91.x
Fixes #3346
Other notes:

[react-navigation] Fix NavigationScreenProp.getParam type, flow < v0.91.x

---

definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_relation.js

- Links to documentation: [Ramda gt](https://ramdajs.com/docs/#gt)
- Link to GitHub or NPM: [Ramda github](https://github.com/ramda/ramda)
Other notes:
This restrains the comparison functions (`gt`, `gte`, `lt`, `lte`) to require numbers or strings. These all share the same `RelationComparison` type now, since they all do the same thing type-wise.
I did a [test](https://ramdajs.com/repl/#?gt%28%27bb%27%2C%20%27ba%27%29) and found these functions work with strings as well as numbers:
``` javascript
gt('bb', 'ba') // true
gt('ba', 'bb') // false
```
So `string` is also included as a possible type. However mixing and matching `number` and `string` has been disallowed.

make ramda comparisons (gt, gte, lt, lte) stricter

---

definitions/npm/redux-mock-store_v1.2.x/flow_v0.25.x-/redux-mock-store_v1.2.x.js
definitions/npm/redux-mock-store_v1.2.x/test_redux-mock-store_v1.js

- Link to GitHub or NPM: https://github.com/dmitry-zaets/redux-mock-store

[npm/redux-mock-store] remove usages of deprecated $Subtype<>

---

definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js

The json function have optional parameters: https://github.com/winstonjs/logform#json
- Links to documentation: https://github.com/winstonjs/logform#json
- Link to GitHub or NPM: https://github.com/winstonjs/winston

Winston: Add correct definition for json format parameter

---

definitions/npm/koa_v2.0.x/flow_v0.38.x/koa_v2.0.x.js

- Links to documentation: https://koajs.com/#ctx-cookies-set-name-value-options-
- Link to GitHub or NPM: https://github.com/koajs/koa
Other notes:
Looks like this has already been fixed on the [Koa definitions for newer Flow versions](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/koa_v2.0.x/flow_v0.93.x/koa_v2.0.x.js#L190-L200), but the defintion for old Flow versions (pre-0.93) is still wrong. This PR fixes it.

[koa_v2.x.x] cookies.set() options are optional

---

definitions/npm/react-router_v5.x.x/flow_v0.63.x-/react-router_v5.x.x.js

Same signature as for v4: https://github.com/flow-typed/flow-typed/pull/2492/files
Here is the doc: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/generatePath.md

Add generatePath signature to react router v5

---

definitions/npm/jest_v24.x.x/flow_v0.39.x-/jest_v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.39.x-/test_jest-v24.x.x.js

See here:
https://github.com/facebook/jest/blob/ccea646e76efd73654468ac32b3cb3a88778f7f4/packages/expect/src/types.ts#L257
https://jestjs.io/docs/en/expect.html#tohavepropertykeypath-value
https://github.com/facebook/jest/blob/ccea646e76efd73654468ac32b3cb3a88778f7f4/packages/expect/src/types.ts#L257
Other notes:

expect.toHaveProperty supports Array

---

cli/src/commands/runTests.js

When I run next command:
```js
node cli/dist/cli.js run-tests material-ui/core
```
I always have to wait when RC version will be downloaded
```js
Running definition tests against latest 15 flow versions in /home/i/open-source/flow-typed/definitions/npm...
Fetching all Flow binaries...
Fetching flow-v0.102.0-rc...
flow-v0.102.0-rc finished downloading.
Extracting flow-v0.102.0-rc...
Removing flow-v0.102.0-rc artifacts...
flow-v0.102.0-rc complete!
Finished fetching Flow binaries.
```

[cli] Exclude release candidate version

---

definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js

- Links to documentation: https://github.com/facebook/flow/commit/b95c42f98645183eae26706cd79591474456bf13
- Link to GitHub or NPM: https://www.github.com/ramda/ramda
Other notes:
New versions of Flow have been causing build errors for Ramda. Simply switching `$Enum` to `$Keys` fixes the issue. `$Enum` has been deprecated and subsequently removed in favor of `$Keys` per errors that come up in the build and according to [this commit](https://github.com/facebook/flow/commit/b95c42f98645183eae26706cd79591474456bf13).

remove deprecated $Enum type in favor of $Keys for ramda

---

definitions/npm/object-hash_v1.x.x/flow_v0.25.x-/object-hash_v1.x.x.js

This is also an option provided by the library:
https://github.com/puleos/object-hash/blob/c70080cc88b4b54abffe723659bde530474f1d17/index.js#L57-L58

object-hash: allow "passthrough" as an algorithm option

---

definitions/npm/backbone-collection_v1.x.x/flow_v0.25.x-v0.74.x/backbone-collection_v1.x.x.js
definitions/npm/backbone-collection_v1.x.x/flow_v0.75.x-/backbone-collection_v1.x.x.js
definitions/npm/backbone-model_v1.x.x/flow_v0.25.x-v0.74.x/backbone-model_v1.x.x.js
definitions/npm/backbone-model_v1.x.x/flow_v0.75.x-/backbone-model_v1.x.x.js
definitions/npm/backbone_v1.x.x/flow_v0.25.x-v0.41.x/backbone_v1.x.x.js
definitions/npm/backbone_v1.x.x/flow_v0.42.x-/backbone_v1.x.x.js

Links to documentation:
- returns from `set`: https://backbonejs.org/docs/backbone.html#section-123
- `add`: https://backbonejs.org/docs/backbone.html#section-113
- `reset`: https://backbonejs.org/docs/backbone.html#section-123 
- `remove`: https://backbonejs.org/docs/backbone.html#section-114
Link to GitHub: https://github.com/jashkenas/backbone/

Fix add, set, reset and remove methods for backbone collections

---

definitions/npm/express_v4.16.x/flow_v0.32.x-v0.92.x/express_v4.16.x.js
definitions/npm/express_v4.16.x/flow_v0.93.x-/express_v4.16.x.js
definitions/npm/express_v4.x.x/flow_v0.25.x-v0.27.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.28.x-v0.31.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.32.x-v0.92.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.93.x-/express_v4.x.x.js

- Links to documentation: https://expressjs.com/
- Link to GitHub or NPM: https://github.com/expressjs/express
- Type of contribution: Fix
Other notes:
1. This pr will get error with `Deprecated utility. Using '$Subtype' types is not recommended! ('deprecated-utility')`. #3337 will fix this error.
2. If I use `express`, I can not import `net`. I will get error:
```sh
Cannot get net.Socket because property Socket is missing in module net [1].
packages/configs/src/utils/worker.js
71│    *
72│    * @return {client | null} - a client socket or null
73│    */
74│   +writeCache = (data: cacheType): ?net.Socket => {
75│     const { filePath, pid, using } = data;
76│
77│     if (this.server) {
/private/tmp/flow/flowlib_20d44069/node.js
[1] 1617│ declare module "net" {
1618│
1619│   declare class …
```

[express_v4] Remove import modules

---

definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_relation.js

- Links to documentation: https://ramdajs.com/docs/#ascend https://ramdajs.com/docs/#descend
Other notes:
Returning a curried function makes these functions work with `sort`, which matches usage as well as the documented examples for these functions.

make ramda ascend and descend return curried functions

---

definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_object.js

- https://ramdajs.com/docs/#lens
- https://ramdajs.com/docs/#lensIndex
- https://ramdajs.com/docs/#lensPath (not fixing this one yet)
- https://ramdajs.com/docs/#lensProp
- https://ramdajs.com/docs/#over
- https://ramdajs.com/docs/#set
- https://ramdajs.com/docs/#view
Other notes:
The lens functions (`lens`, `lensProp`, `lensIndex` (excluding `lensPath` for today)) weren't producing a correct type in the output, so some modification was needed. The lens types relate to the lens operation functions: over, set, and view. All of the lens operation functions also needed modification to work with the new lens types.
These types should closely reflect Haskell's lens system, which itself …

fix ramda lenses

---

definitions/npm/xmldom_v0.x.x/flow_v0.53.0-/xmldom_v0.x.x.js
definitions/npm/xmldom_v0.x.x/test_xmldom_v0.x.x.js

Hello,
I'd like to submit xmldom package definition,
A JavaScript implementation of W3C DOM for Node.js
- Links to documentation: https://github.com/jindw/xmldom/blob/master/readme.md
- Link to GitHub or NPM: https://www.npmjs.com/package/xmldom
Thanks

[xmldom_v0.x.x] Add definitions

---

CONTRIBUTING.md
definitions/npm/history_v4.9.x/flow_v0.25.x-/history_v4.9.x.js
definitions/npm/history_v4.9.x/flow_v0.25.x-/test_history_v4.9.x.js

- Link to GitHub or NPM: *Covering [these functions](https://github.com/ReactTraining/history/blob/master/modules/PathUtils.js#L24-L59) from the **history** package*
- Links to documentation: *Unfortunately, these are undocumented*
- Type of contribution: *new definition | **ADDITION** | fix | refactor*
These exported APIs are undocumented and were missed in the previous libdef iteration.
Most of the diff is from prettier (`"` => `'`, `,` => `;`). eslint didn't mind, so I left them in.

[history_v4.9.x] Update types for history

---

definitions/npm/@react-navigation/core_v3.x.x/flow_v0.92.x-/core_v3.x.x.js
definitions/npm/react-navigation_v3.x.x/flow_v0.92.x-/react-navigation_v3.x.x.js

Try to solve the issue - [#6002 (comment)](https://github.com/react-navigation/react-navigation/issues/6002#issuecomment-502908696)

fix flow error for getActiveChildNavigationOptions import

---

definitions/npm/node-fetch_v2.x.x/flow_v0.100.x-/node-fetch_v2.x.x.js
definitions/npm/node-fetch_v2.x.x/test_node-fetch_v2.x.x.js

- Links to documentation: [README.md](https://github.com/bitinn/node-fetch/blob/master/README.md) | [CHANGELOG.md](https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md)
- Link to GitHub or NPM: [GitHub](https://github.com/bitinn/node-fetch) | [NPM](https://www.npmjs.com/package/node-fetch)
- Type of contribution: **new definition** | addition | fix | refactor
Other notes:
**NOTE:** This definition (+ tests) are copied over from the [flow-typed/definitions/npm/node-fetch_v1.x.x](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/node-fetch_v1.x.x/flow_v0.44.x-/node-fetch_v1.x.x.js).
There are some [breaking changes](https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md#v200) documented in the v2.0.0 release, but the biggest factor looked to be dropping …

[node-fetch_v2.x.x] Copy definition from v1.x.x

---

CHANGELOG.md
cli/src/lib/stubUtils.js

This change makes `flow-type install` create stubs for `core-js/stable` and `core-js/es/symbol` rather than just `core-js/stable/index` and `core-js/es/symbol/index`.

Generate stub declarations for directory modules

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js

The functions `flow`, `flowRight`, `pipe` and `compose` from lodash (and lodash/fp) should all accept multiple functions as arguments, not only a list of functions. This is supported by the documentation for lodash:
`flow`: [https://lodash.com/docs/4.17.14#flow](https://lodash.com/docs/4.17.14#flow)
`flowRight`: [https://lodash.com/docs/4.17.14#flowRight](https://lodash.com/docs/4.17.14#flowRight)
In the [Lodash FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide) it says that:
-  `pipe` is an alias of `flow`
-  `compose` is an alias of `flowRight`
This fixes issue #2125

[lodash_v4.x.x] (Fix) flow, flowRight, pipe, compose should accept multiple functions, not only array

---

definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/react-redux_v7.x.x.js
definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_useDispatch.js
definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_useSelector.js
definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_useStore.js

Resolves #3452
- Links to documentation: https://react-redux.js.org/api/hooks
- Link to GitHub or NPM: https://github.com/reduxjs/react-redux
Other notes:
Adds implementations for the hooks added in [react-redux v7.1.0](https://github.com/reduxjs/react-redux/releases/tag/v7.1.0).

Add react-redux hooks, `useDispatch` & `useSelector`

---

definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js
definitions/npm/winston_v3.x.x/test_winston_v3.x.x.js

- Links to documentation: [README.md](https://github.com/winstonjs/winston/blob/master/README.md)
- Link to GitHub or NPM: [GitHub](https://github.com/winstonjs/winston) | [NPM](https://www.npmjs.com/package/winston)
- Type of contribution: new definition | addition | **fix** | refactor
Other notes:
* Resolves https://github.com/flow-typed/flow-typed/issues/2833
* Opted out of `describe` and `it` since this was an existing definition.  Should the new test use these, or do we grandfather in older tests?
---
The proposed exported type would be equivalent to:
```js
{
Container: class $winstonContainer<T>, 
add: ($winstonTransport) => void, 
clear: () => void, 
configure: ($winstonLoggerConfig<$winstonNpmLogLevels>) => void, 
createLogger: <T>($winstonLoggerConfig<T>) => $winstonLogger<T>, …
```

[winston_v3.x.x] Update definition to allow named imports

---

definitions/npm/express_v4.16.x/flow_v0.32.x-v0.92.x/express_v4.16.x.js
definitions/npm/express_v4.16.x/flow_v0.93.x-v0.93.x/express_v4.16.x.js
definitions/npm/express_v4.16.x/flow_v0.94.x-/express_v4.16.x.js
definitions/npm/express_v4.16.x/test_express_v4.16.x.js
definitions/npm/express_v4.x.x/flow_v0.25.x-v0.27.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.28.x-v0.31.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.32.x-v0.92.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.93.x-v0.93.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.94.x-/express_v4.x.x.js
definitions/npm/express_v4.x.x/test_express_v4.x.x.js

* [Link to documentation][1]
* Link to GitHub or npm: [GitHub][2]
* Type of contribution: fix
Other notes: `req.is` returns a string or `false`, but we were saying that it returned a `boolean`, which wasn't quite right.
[1]: https://expressjs.com/en/4x/api.html#req.is
[2]: https://github.com/expressjs/express

[express_{v4.x.x,v4.16.x}]: correct `is` method return type on requests

---

definitions/npm/numeral_v2.x.x/flow_v0.25.x-/numeral_v2.x.x.js

- Links to documentation: [numeraljs.com](http://numeraljs.com/) (doesn't describe it)
- Link to GitHub or NPM: [github.com/adamwdraper/Numeral-js](https://github.com/adamwdraper/Numeral-js)
Other notes:
Numeral comes with bunch of "side-effect only" modules which register predefined locales. 
One cannot use `numeral.locale('pt-br');` without `import 'numeral/locales'` before it (or `import 'numeral/locales/pt-br'`).
There is some info about it in [this issue](https://github.com/adamwdraper/Numeral-js/issues/517).

[numeral_v2.x.x] Describe modules with predefined locales

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js

Reverts flow-typed/flow-typed#3454
See https://github.com/flow-typed/flow-typed/issues/3463
Was causing more harm than good to various users.

Revert "[lodash_v4.x.x] (Fix) flow, flowRight, pipe, compose should accept multiple functions, not only array"

---

definitions/npm/alasql_v0.3.x/flow_v0.25.x-v0.103.x/alasql_v0.3.x.js

Fix conflict with react-dom
```
* alasql_v0.3.x/flow_v0.25.x-v0.103.x (flow-v0.101.0): Unexpected Flow errors (2):
Error ----------------------------------------------------------------------------------- <BUILTINS>/react-dom.js:116:47
Cannot use `Thenable` [1] without 1 type argument.
<BUILTINS>/react-dom.js:116:47
116|   declare function act(callback: () => void | Thenable): Thenable;
^^^^^^^^
References:
alasql_v0.3.x.js:46:19
46| interface Thenable<T> {
^^^ [1]
```

[alasql_v0.3.x] Fix tests errors

---

definitions/npm/angular_v1.5.x/flow_v0.104.x-/test_angular_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-v0.103.x/test_angular_v1.5.x.js

Problem
```
Error --------------------------------------------------------------------------------------- test_angular_v1.5.x.js:8:3
Cannot import the value `AngularResourceFactory` as a type. `import type` only works on type exports like type aliases,
interfaces, and classes. If you intended to import the type of a value use `import typeof` instead.
8|   AngularResourceFactory,
^^^^^^^^^^^^^^^^^^^^^^
```

[angular_v1.5.x] Fix tests errors

---

definitions/npm/phoenix_v1.4.x/flow_v0.104.x-/phoenix_v1.4.x.js
definitions/npm/phoenix_v1.4.x/flow_v0.25.x-v0.103.x/phoenix_v1.4.x.js

- Links to documentation: https://phoenixframework.org/
- Link to GitHub or NPM: https://github.com/phoenixframework/phoenix
Other notes:
syncDiff (and syncState via syncDiff) returns `state` which is always a k/v object
https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L1349

[phoenix_v1.4.x] update syncState/syncDiff return value

---

definitions/npm/lodash-es_v4.x.x/flow_v0.104.x-/lodash-es_v4.x.x.js

- Links to documentation: https://lodash.com
- Link to GitHub or NPM: https://github.com/lodash/lodash/tree/es
Other notes:
Simply removed the reference to `$Supertype<>`, as in https://github.com/flow-typed/flow-typed/pull/3063.
To do:

[lodash-es_v4.x.x] Remove use of deprecated `$Supertype` 

---

definitions/npm/google-protobuf_v3.6.x/flow_v0.83.x-/google-protobuf_v3.6.x.js
definitions/npm/google-protobuf_v3.6.x/test_google-protobuf.js

- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-protobuf
- Link to GitHub or NPM: https://www.npmjs.com/package/google-protobuf
I've written these definitions for use with https://github.com/chrisgervang/flowtype-protoc-gen

Add google-protobuf definitions

---

definitions/npm/source-map_v0.7.x/flow_v0.104.x-/source-map_v0.7.x.js

- Link to GitHub or NPM: https://github.com/mozilla/source-map
Other notes:
When using these typings in Parcel we noticed null mappings aren't allowed in these mappings. Which is pretty important to create correct sourcemaps. This PR adds support for it.

Fix types for `source-map`, add null mappings

---

definitions/npm/rxjs_v5.0.x/flow_v0.34.x-v0.103.x/rxjs_v5.0.x.js

Aligned the definition for RxJS v5.
- Links to documentation: https://rxjs-dev.firebaseapp.com/api/index/class/Subscription

Add missing properties for Subscription

---

definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/react_v9.x.x.js
definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/test_react_v9.x.x.js

- Links to documentation: https://testing-library.com/docs/react-testing-library/api#act
Other notes:
The `act` function should probably be added to the other versions of `@testing-library/react`, too, but I figured I'd start with the latest version first.
I would have liked to import the type of `act` from `react-dom/test-utils`, but that didn't seem to work, so I copied the relevant type information for it instead.

[@testing-library/react_v9.x.x] Add act function

---

definitions/npm/enzyme_v3.x.x/flow_v0.104.x-/enzyme_v3.x.x.js
definitions/npm/enzyme_v3.x.x/flow_v0.104.x-/test_enzyme-v3.x.js

Summary:
The `render` function currently accepts a `React.Component<T>`, but can
actually accept an arbitrary React node, which is sometimes necessary.
This is true of `shallow` and `mount` as well, but the change is easiest
for `render` because there is no component type information to thread
through to the return type.
See discussion:
<https://github.com/flow-typed/flow-typed/pull/3107#issuecomment-523328443>
Test Plan:
Updated tests; the new test fails before this change and passes after
it.
wchargin-branch: enzyme-render-node

[enzyme_v3.x.x] Enable static rendering of arbitrary `React$Node`s

---

definitions/npm/redux-reactors_v1.x.x/flow_v0.104.x-/redux-reactors_v1.x.x.js
definitions/npm/redux-reactors_v1.x.x/flow_v0.104.x-/test_redux-reactors_v1.x.x.js
definitions/npm/redux-reactors_v1.x.x/flow_v0.95.x-v0.103.x/redux-reactors_v1.x.x.js
definitions/npm/redux-reactors_v1.x.x/flow_v0.95.x-v0.103.x/test_redux-reactors_v1.x.x.js

- Type of contribution: new definition | addition | **FIX** | refactor
Other notes:
Added in this PR: https://github.com/flow-typed/flow-typed/pull/3457
It seems that since these types were defined outside a `module`, they were essentially global and would conflict with types of the same name from other libdefs. Specifically, I was seeing that the type `Action` was conflicting with a similarly named `Action` type from `history`

[redux-reactors_v1.x.x.js] Move types so they don't conflict with other libdefs

---

definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/react_v8.x.x.js
definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/test_react_v8.x.x.js
definitions/npm/@testing-library/react_v8.x.x/flow_v0.67.1-v0.103.x/react_v8.x.x.js
definitions/npm/@testing-library/react_v8.x.x/flow_v0.67.1-v0.103.x/test_react_v8.x.x.js

- Links to documentation: https://testing-library.com/docs/react-testing-library/api#act
Other notes:
The `act` method was added to the `@testing-library/react_v9.x.x` type definitions in a previous pull request (#3521), now it's time to add it to the v8.x.x type definitions.

[@testing-library/react_v8.x.x] Add act function

---

definitions/npm/@apollo/react-hooks_v3.x.x/CONTRIBUTING.md
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/test_react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/test_react-hooks_v3.x.x.js

- Links to documentation:https://www.apollographql.com/docs/react/api/react-hooks/
- Link to GitHub or NPM: https://www.npmjs.com/package/@apollo/react-hooks
Other notes: I did my best to adapt the typescript definitions into flow types. There is some usage of any, however I did my best to keep `any` out of all the APIs generally consumed directly.

Add type definitions for @apollo/react-hooks package

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-v0.88.x/core_v1.x.x.js

Adds flow definitions for the `FilledInput` component of Material UI
- Links to documentation: https://material-ui.com/api/filled-input/
- Link to GitHub or NPM: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/FilledInput/FilledInput.js

[@material-ui/core@1.x.x] Add FilledInput defs

---

cli/src/commands/install.js

- Links to documentation: https://github.com/flow-typed/flow-typed/wiki/CLI-Commands-and-Flags
- Link to GitHub or NPM: https://github.com/flow-typed/flow-typed/issues/3340
Other notes:
The following comparison may have the code which accidentally removed the overwrite flag because a colleague claims that it worked in the 2.5.x version, but the 2.6.1 version does not work. I couldn't find the problem, so instead I added the option to the yargs.usage options.
https://github.com/flow-typed/flow-typed/compare/v2.4.0..v2.6.1

Attempted to fix #3340. Added overwrite option to the install file.

---

definitions/npm/lodash-es_v4.x.x/flow_v0.104.x-/lodash-es_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js

`omit` and `pick` doesn't mutate the `path` parameter, should be `$ReadOnlyArray` instead of `Array`
- `lodash` doc: https://lodash.com/docs/4.17.14#omit and https://lodash.com/docs/4.17.14#pick

use `$ReadOnlyArray` for `omit` and `pick` in `lodash`

---

definitions/npm/redux_v3.x.x/flow_v0.104.x-/redux_v3.x.x.js
definitions/npm/redux_v3.x.x/flow_v0.28.x-v0.32.x/redux_v3.x.x.js
definitions/npm/redux_v3.x.x/flow_v0.33.x-v0.54.x/redux_v3.x.x.js
definitions/npm/redux_v3.x.x/flow_v0.55.x-v0.88.x/redux_v3.x.x.js
definitions/npm/redux_v3.x.x/flow_v0.89.x-v0.103.x/redux_v3.x.x.js
definitions/npm/redux_v4.x.x/flow_v0.55.x-v0.88.x/redux_v4.x.x.js

- Links to documentation: https://github.com/reduxjs/redux
- Link to GitHub or NPM: https://redux.js.org/
Other notes:
It is often useful in Redux project to have an action type definition. 
Alack, the older library definitions do not provide it. 
I fixed the inconvenience by extracting an existing type in a separate exported declaration

[redux] Extract the action type in a separate public definition

---

definitions/npm/@apollo/react-components_v3.x.x/flow_v0.104.x-/react-components_v3.x.x.js
definitions/npm/@apollo/react-components_v3.x.x/flow_v0.58.x-v0.103.x/react-components_v3.x.x.js
definitions/npm/@apollo/react-hoc_v3.x.x/flow_v0.104.x-/react-hoc_v3.x.x.js
definitions/npm/@apollo/react-hoc_v3.x.x/flow_v0.58.x-v0.103.x/react-hoc_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/react-hooks_v3.x.x.js

Other notes:
This PR allows for the specification of the `V` generic in `ObservableQuery<T, V>` which describes  the variables in an ObservableQuery in:
- @apollo/react-hooks@3.x.x
- @apollo/react-hoc@3.x.x
- @apollo/react-components@3.x.x
Not accepting this generic caused:
- Worse type coverage than was possible with the generic
- Flow (0.85) to be unable to correctly resolve the types in apollo@v3.x.x packages which supply the variables generic to `ObservableQuery`
e.g. https://github.com/flow-typed/flow-typed/blob/d18ab9e6cbbed915241f286a110fb3e02692d916/definitions/npm/%40apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/react-hooks_v3.x.x.js#L235

@apollo/react-* ObservableQuery Variables generic

---

definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.104.x-/react-native-gesture-handler_v1.x.x.js
definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.104.x-/test_all-gesture-handlers.js
definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-v0.103.x/react-native-gesture-handler_v1.x.x.js
definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-v0.103.x/test_all-gesture-handlers.js

All gesture handlers can have children. [Example 1](https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/panAndScroll/index.js#L52), [example 2](https://github.com/kmagiera/react-native-reanimated/blob/master/Example/imageViewer/index.js#L390)

[react-native-gesture-handler] Allow to have children

---

definitions/npm/redux-devtools-extension_v2.x.x/flow_v0.104.x-/redux-devtools-extension_v2.x.x.js
definitions/npm/redux-devtools-extension_v2.x.x/flow_v0.47.x-v0.103.x/redux-devtools-extension_v2.x.x.js

`$Subtype` is deprecated and newer versions of Flow complain if you use it

[redux-devtools-extension] Get rid of $Subtype usage

---

definitions/npm/promise-retry_v1.1.x/flow_v0.104.x-/promise-retry_v1.1.x.js
definitions/npm/promise-retry_v1.1.x/flow_v0.104.x-/test_promise-retry.js
definitions/npm/promise-retry_v1.1.x/flow_v0.45.x-v0.103.x/promise-retry_v1.1.x.js
definitions/npm/promise-retry_v1.1.x/flow_v0.45.x-v0.103.x/test_promise-retry.js

It was specified as an instance of the `Number` class, which is not compatible with
primitive number types.
- Links to documentation: https://www.npmjs.com/package/promise-retry
- Link to GitHub or NPM: https://github.com/IndigoUnited/node-promise-retry#readme

fix(promise-retry): retryNumber is a primitive number

---

definitions/npm/hoist-non-react-statics_v3.x.x/flow_v0.103.x-/hoist-non-react-statics_v3.x.x.js
definitions/npm/hoist-non-react-statics_v3.x.x/flow_v0.103.x-/test_hoist-non-react-statics_v3.x.x.js
definitions/npm/hoist-non-react-statics_v3.x.x/flow_v0.84.x-v0.102.x/hoist-non-react-statics_v3.x.x.js
definitions/npm/hoist-non-react-statics_v3.x.x/flow_v0.84.x-v0.102.x/test_hoist-non-react-statics_v3.x.x.js

- Link to GitHub or NPM: https://github.com/mridgway/hoist-non-react-statics
Other notes:
The `v2.x.x` definitions for this package were very loose and I tried as much as possible to tighten things up in this updated version, taking inspiration from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hoist-non-react-statics/index.d.ts.
What I was able to do:
- Hoisted statics are no longer just a blanket `$Shape` call over source component statics and are much closer to their actual shape, providing more meaningful typechecks.
What I was not able to do and why:
- React statics that may be present but not always (depending on whether the component has been `memo`'ed or `forwardRef`'ed) are not taken into account with precision like …

[hoist-non-react-statics v3.x.x] Add defs

---

definitions/npm/phoenix_v1.4.x/flow_v0.104.x-/phoenix_v1.4.x.js
definitions/npm/phoenix_v1.4.x/flow_v0.25.x-v0.103.x/phoenix_v1.4.x.js
definitions/npm/phoenix_v1.4.x/test_phoenix_v1.4.x.js

On Phoenix `Socket` initialization, option `transport` is expected by type definitions to be string. This is also found in Phoenix.js official documentation, but it's an error. What the constructor actually expects is either `window.WebSocket` or `Phoenix.LongPoll`. Giving any string as transport option to the constructor will throw an error when `socket.connect()` is called.
The source code for phoenix sockets can be found here: https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js
The initialization of Socket transport happens at row 737 and an error will be thrown at row 836 if the user erroneously gave a string to the constructor.
- Links to documentation: https://hexdocs.pm/phoenix/js/
- Link to GitHub or NPM: https://github.com/phoenixframework/phoenix
- Type …

Fixed wrong type in phoenix socket transport option

---

definitions/npm/luxon_v1.x.x/flow_v0.104.x-/luxon_v1.x.x.js
definitions/npm/luxon_v1.x.x/flow_v0.104.x-/test_luxon.js
definitions/npm/luxon_v1.x.x/flow_v0.32.0-v0.103.x/luxon_v1.x.x.js

Fix of incorrect return type of `DateTime.until` method in [Luxon](https://www.npmjs.com/package/luxon), for reference please [see latest docs](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-until).

Luxon v1.x.x: fix DateTime.until definition

---

definitions/npm/react-router_v5.x.x/flow_v0.104.x-/react-router_v5.x.x.js
definitions/npm/react-router_v5.x.x/flow_v0.63.x-v0.103.x/react-router_v5.x.x.js

The ESM version of `react-router` doesn't actually have a default export.
Node's experimental ESM support does not support destructuring imports from CommonJS modules. Since React Router 5 introduces a destructuring import on `is-react`, which is CJS-only, Node is unable to treat RR5 as ESM.
Instead, it's necessary to treat RR5 as CJS, but this means that a destructuring import on RR5 is impossible, and a "default" import is necessary. Without a default export in the libdef, Flow complains when it sees this.
For context, I've had to do this for `react-redux` in the past as well. Example: #3062

[react-router] Specify default export

---

definitions/npm/supertest_v4.x.x/flow_v0.94.x-/supertest_v4.x.x.js
definitions/npm/supertest_v4.x.x/test_basic-functionality.js

- Links to documentation: https://github.com/visionmedia/supertest#readme and http://visionmedia.github.io/superagent/
- Link to GitHub or NPM:  https://github.com/visionmedia/supertest and https://github.com/visionmedia/superagent
Other notes:
I tried to be exhaustive for the main use cases, but I gave `agent` a miss on purpose, because it's not used a lot (at least not by me).
I reused some autogeneration from typescript but also wrote a lot by hand and reviewed what I copied.
I tried to leave comments on parts that I didn't completely type. For example the library exists for both the browser and node contexts, with slightly different APIs, so I decided to follow mostly the node version because I believe it won't be used much in browsers nowadays, …

Add the supertest library

---

definitions/npm/react-color_v2.x.x/flow_v0.104.x-/react-color_v2.x.x.js
definitions/npm/react-color_v2.x.x/flow_v0.56.x-v0.103.x/react-color_v2.x.x.js

Flow 0.89 and above have a lint that complains about this, and it has been considered "unclear" outside libdefs since 0.72.

[react-color] Remove $Supertype usage

---

definitions/npm/cookie-parser_v1.x.x/flow_v0.104.x-/cookie-parser_v1.x.x.js
definitions/npm/cookie-parser_v1.x.x/flow_v0.93.x-v0.103.x/cookie-parser_v1.x.x.js
definitions/npm/express_v4.16.x/flow_v0.104.x-/express_v4.16.x.js
definitions/npm/express_v4.16.x/flow_v0.104.x-/test_overrideUseMethodClassExtension.js
definitions/npm/express_v4.16.x/flow_v0.104.x-/test_response.js
definitions/npm/express_v4.16.x/flow_v0.94.x-v0.103.x/express_v4.16.x.js
definitions/npm/express_v4.16.x/flow_v0.94.x-v0.103.x/test_overrideUseMethodClassExtension.js
definitions/npm/express_v4.16.x/flow_v0.94.x-v0.103.x/test_response.js
definitions/npm/express_v4.16.x/test_express_v4.16.x.js
definitions/npm/express_v4.17.x/flow_v0.104.x-/express_v4.17.x.js
definitions/npm/express_v4.17.x/flow_v0.104.x-/test_overrideUseMethodClassExtension.js
definitions/npm/express_v4.17.x/flow_v0.104.x-/test_response.js
definitions/npm/express_v4.17.x/flow_v0.32.x-v0.92.x/express_v4.17.x.js
definitions/npm/express_v4.17.x/flow_v0.32.x-v0.92.x/test_overrideUseMethodClassExtension.js
definitions/npm/express_v4.17.x/flow_v0.32.x-v0.92.x/test_response.js
definitions/npm/express_v4.17.x/flow_v0.93.x-v0.93.x/express_v4.17.x.js
definitions/npm/express_v4.17.x/flow_v0.93.x-v0.93.x/test_overrideUseMethodClassExtension.js
definitions/npm/express_v4.17.x/flow_v0.93.x-v0.93.x/test_response.js
definitions/npm/express_v4.17.x/flow_v0.94.x-v0.103.x/express_v4.17.x.js
definitions/npm/express_v4.17.x/flow_v0.94.x-v0.103.x/test_overrideUseMethodClassExtension.js
definitions/npm/express_v4.17.x/flow_v0.94.x-v0.103.x/test_response.js
definitions/npm/express_v4.17.x/test_express_v4.17.x.js
definitions/npm/express_v4.x.x/flow_v0.104.x-/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.104.x-/test_overrideUseMethodClassExtension.js
definitions/npm/express_v4.x.x/flow_v0.104.x-/test_response.js
definitions/npm/express_v4.x.x/flow_v0.94.x-v0.103.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.94.x-v0.103.x/test_overrideUseMethodClassExtension.js
definitions/npm/express_v4.x.x/flow_v0.94.x-v0.103.x/test_response.js
definitions/npm/express_v4.x.x/test_express_v4.x.x.js

Flow 0.89 and above have a lint that complains about this, and it has been considered "unclear" outside libdefs since 0.72.

[express] Remove $Subtype usage in express and cookie-parser

---

definitions/npm/react-native-navigation_v3.x.x/flow_v0.104.x-/react-native-navigation_v3.x.x.js
definitions/npm/react-native-navigation_v3.x.x/flow_v0.104.x-/test_react-native-navigation.js
definitions/npm/react-native-navigation_v3.x.x/flow_v0.91.1-v0.103.x/react-native-navigation_v3.x.x.js
definitions/npm/react-native-navigation_v3.x.x/flow_v0.91.1-v0.103.x/test_react-native-navigation.js

I have added the optional third parameter `concreteComponentProvider` which was missing from `registerComponent`. I have also renamed `getClassComponentFunc` to `componentProvider` to match the TypeScript definition: https://github.com/wix/react-native-navigation/blob/master/lib/src/Navigation.ts#L77

Add missing param in react-native-navigation's registerComponent

---

definitions/npm/winston_v3.x.x/flow_v0.104.x-/winston_v3.x.x.js
definitions/npm/winston_v3.x.x/flow_v0.34.x-v0.103.x/winston_v3.x.x.js
definitions/npm/winston_v3.x.x/test_winston_v3.x.x.js

https://github.com/winstonjs/winston
Winston timestamp format takes options object. The `format` field of this object can be either of type `string` or of type `() => string`.

Type fixed for options of winston timestamp format

---

definitions/npm/ramda_v0.26.x/flow_v0.104.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.104.x-/test_ramda_v0.26.x_logic.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/test_ramda_v0.26.x_logic.js

The current type definition of the `propSatisfies` Ramda function only works properly when using an object with properties of the same type. Otherwise it will complain as seen [here](https://flow.org/try/#0ATAmFMGMBsEMCdzAGYFcB2kAuBLA9usAA7x5EDKsuAzsjuNQDwAqAfABQBQIIkBoALmDsAHkIAkANVjRUDFqwCUwALytgAIzx5o4WOgA03HiTISA0uACeTNkZ7A8Q5scVCtOvegDcxiDAQkNExcAmJSCiocWnpbDmNefiFRCWlZeTZlNU1tXX17EwiLaziCt2EnYGYs9Q88nz8oOEQUDGx8QlNImjoM+Ic+dEFhMWApGTk4mpzPfNdk9i6hMcsbBWn2SurVWtyvZQAyBOFFopBxVdLHZ2m6-d9OTgB6J+AAOTxgcHhSeGAAC2+SFg1GAAHIRGDgPpQOCrFDAjksP9gOhUABbDTfUGcQbULDhMwzeqqQndaK9aiiHbAETAdQABgM4MhzIA3rShABGZlWIQAJmAAF9FA8XsAAKrUHDoADm0MIeA0ACsoASAO44ZFk764BiOZBgHDIZBA9AErBWIjgZnIaB4dXATXQaDAPjoohwGXUXEEfFk-nuPb6UldSg9WLU7J0xnMiFg9mc4A84B88H8hPAABeQiw8DkwtFjyAA).
One solution could be checking the …

[ramda] Improve propSatisfies type definition

---

definitions/npm/reselect_v3.x.x/flow_v0.104.x-/reselect_v3.x.x.js
definitions/npm/reselect_v3.x.x/flow_v0.104.x-/test_reselect_3.x.x.js
definitions/npm/reselect_v3.x.x/flow_v0.47.x-v0.103.x/reselect_v3.x.x.js
definitions/npm/reselect_v4.x.x/flow_v0.104.x-/reselect_v4.x.x.js
definitions/npm/reselect_v4.x.x/flow_v0.104.x-/test_reselect_4.x.x.js
definitions/npm/reselect_v4.x.x/flow_v0.47.x-v0.103.x/reselect_v4.x.x.js

- Links to documentation: https://github.com/reduxjs/reselect#api
- Link to GitHub or NPM: https://github.com/reduxjs/reselect
Other notes:
resultFunc does not receive State and Props these are only passed to input selectors

Fix extra reselect resultFunc args

---

cli/package.json

npm audit identified a vulnerability in https-proxy-agent which is included through octokit/rest. Updating octokit/rest will use a version that does not use the vulnerable https-proxy-agen
https://www.npmjs.com/advisories/1184

Updated octokit/rest to avoid vulnerability

---

cli/package.json
cli/src/commands/install.js
definitions/npm/axios_v0.18.x/flow_v0.104.x-/axios_v0.18.x.js
definitions/npm/axios_v0.18.x/flow_v0.104.x-/test_axios_v0.18.x.js
definitions/npm/axios_v0.18.x/flow_v0.25.x-v0.74.x/axios_v0.18.x.js
definitions/npm/axios_v0.18.x/flow_v0.75.x-v0.79.x/axios_v0.18.x.js
definitions/npm/axios_v0.18.x/flow_v0.80.x-v0.92.x/axios_v0.18.x.js
definitions/npm/axios_v0.18.x/flow_v0.93.x-v0.103.x/axios_v0.18.x.js

Based on the api documentation of the 0.18.1 version, the options method is available
[`axios.options(url[, config])`](https://github.com/axios/axios/tree/release/0.18.X#axiosoptionsurl-config)
Other notes:

Add options method to instance

---

definitions/npm/@react-native-community/netinfo_v4.x.x/flow_v0.69.x-/netinfo_v4.x.x.js

NetInfo packages exports enums to our reuse but are not visible to Flow because are missing in definition.
- https://github.com/react-native-community/react-native-netinfo#netinfostatetype
- https://github.com/react-native-community/react-native-netinfo#netinfocellulargeneration
- https://github.com/react-native-community/react-native-netinfo/blob/master/src/internal/types.ts#L10
- https://github.com/react-native-community/react-native-netinfo/blob/master/src/internal/types.ts#L22
Other notes:
The enums are exported here: https://github.com/react-native-community/react-native-netinfo/blob/master/src/index.ts#L215

Export NetInfo enumerations

---

definitions/npm/mozlog_v2.2.x/flow_v0.84.x-/mozlog_v2.2.x.js
definitions/npm/mozlog_v2.2.x/test_mozlog.js

- Links to documentation: https://github.com/mozilla/mozlog
- Link to GitHub or NPM: https://github.com/mozilla/mozlog
Other notes:
This is a mozilla tool that wraps `intel` with some specifics.

Add a libdef for the mozlog library

---

definitions/npm/puppeteer_v1.20.x/flow_v0.104.x-/puppeteer_v1.20.x.js
definitions/npm/puppeteer_v1.20.x/flow_v0.76.x-v0.103.x/puppeteer_v1.20.x.js

- Links to documentation: https://github.com/GoogleChrome/puppeteer
- Link to GitHub or NPM: https://github.com/GoogleChrome/puppeteer
Other notes:
Before #3595, types were being exported from the module libdef but following the refactor, this was reverted. This PR re-exports all of the types so that any consumer of the puppeteer library can use them.

Export puppeteer types

---

definitions/npm/@koa/router_v8.0.x/flow_v0.84.x-/router_v8.0.x.js
definitions/npm/@koa/router_v8.0.x/test_koa-router.js

- Links to documentation: https://github.com/koajs/router/blob/master/API.md
- Link to GitHub or NPM: https://github.com/koajs/router
Other notes:
I copied most of it from `koa-router`; indeed this npm module has been forked and renamed because the original was unmaintained.
I only kept the version for "v0.104-" but adapted it to make it work with some earlier flow versions, which is simpler if we don't want to support versions of flow earlier than v0.84.
Also I added the newest additions (there's a new parameter in the `url` method).
Lastly I kept most tests but reorganized them with describe and it, as well as added new ones.
Tell me what you think!

Add a lib def for @koa/router

---

definitions/npm/ramda_v0.26.x/flow_v0.104.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.104.x-/test_ramda_v0.26.x_list.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/test_ramda_v0.26.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.104.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.104.x-/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-v0.103.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-v0.103.x/test_ramda_v0.x.x_list.js

- Links to documentation: https://ramdajs.com/docs/
Ramda's `includes` (same as `contains`, but `contains` is deprecated), would not respect `$ReadOnlyArray`. These changes allow for `$ReadOnlyArray` and also enforce a strict case when it comes to using strings (only strings may be compared with strings). Tests have been added to enforce this behavior.
Some tests have been problematic to enforce - namely the all-arity version of `$ReadOnlyArray`. It is not well understood why this is happening, but there are comments noting the expected outcome vs. actual. I don't believe it's a covariance issue, because 1) the curried form works fine, and 2) `string` and `number` shouldn't be covariant.
I also took the …

add $ReadOnlyArray support to ramda includes + contains

---

definitions/npm/three_v0.98.x/flow_v0.107.x-/three_v0.98.x.js

- Links to documentation: https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene
- Link to GitHub or NPM: https://github.com/mrdoob/three.js/
I can explain!
This adds a first pass at Three.js. This libdef is incomplete yet pretty big. There are no accompanying tests as it is a libdef lifted from a personal project that doesn't get very much time as it is. Adding tests has prevented this from entering public view and my desire to add these tests hasn't actually made that happen for... 2 years? Let's say 2 years. Therefore this is a work-in-progress that others might use until it meets the expectations of a given libdef.
I have last tested this against Three.js 0.98.0 and Flow 0.107.0, but it could very well work with many other …

[wip] add three.js support

---

definitions/npm/react-navigation_v4.x.x/flow_v0.104.x-/react-navigation_v4.x.x.js

Other notes: This change fixes typo in `screenProps` property naming

Fix typo in react-navigation_v4.x.x.js

---

cli/src/commands/runTests.js

- Links to documentation: https://octokit.github.io/rest.js/#octokit-routes-repos-list-releases
Other notes:
The `getReleases` method was renamed to `listReleases` in version 16 of
the @octokit/rest package (https://github.com/octokit/rest.js/releases/tag/v16.0.1 first item
of breaking changes). flow-typed upgraded from 15.12.1 to 16.33.1
in [recently](fed266bbb15f7bf75780b573317720fbee497dd8) and that's when the bug was probably introduced.
The bug is not triggered in Travis CI because:
1.  the flow binaries are probably all cached and you don't need to
download them
2.  the code that downloads them is in a try/catch block. If the
download fails, the tests default to using the cached binaries. This
works for people who have run the tests before, but not for …

Fix GH_CLIENT usage in runTests test

---

definitions/npm/react-router-dom_v5.x.x/flow_v0.104.x-/react-router-dom_v5.x.x.js
definitions/npm/react-router-dom_v5.x.x/flow_v0.104.x-/test_react-router-dom.js
definitions/npm/react-router_v5.x.x/flow_v0.104.x-/react-router_v5.x.x.js
definitions/npm/react-router_v5.x.x/flow_v0.104.x-/test_react-router.js

- Links to documentation: https://reacttraining.com/react-router/web/api/Hooks/useroutematch / https://reacttraining.com/blog/react-router-v5-1/#useroutematch
- Link to GitHub or NPM: https://github.com/ReactTraining/react-router/blob/ef60b08d514e1db3354316c303783158f108bd3b/packages/react-router/modules/hooks.js#L54
Other notes:
If you just read the documentation, it would appear that `useRouteMatch` only takes a `string`. However if you read the [accompanying blog post](https://reacttraining.com/blog/react-router-v5-1/#useroutematch), they use an object. I dove into the [source code](https://github.com/ReactTraining/react-router/blob/ef60b08d514e1db3354316c303783158f108bd3b/packages/react-router/modules/hooks.js#L54) and `useRouteMatch` takes the same …

Fix react-router useRouteMatch definitions

---

definitions/npm/@apollo/react-common_v3.x.x/flow_v0.104.x-/react-common_v3.x.x.js
definitions/npm/@apollo/react-components_v3.x.x/flow_v0.104.x-/react-components_v3.x.x.js
definitions/npm/@apollo/react-components_v3.x.x/flow_v0.58.x-v0.103.x/react-components_v3.x.x.js
definitions/npm/@apollo/react-hoc_v3.x.x/flow_v0.104.x-/react-hoc_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/react-hooks_v3.x.x.js

I'm migrating a lot of code that has `import { type ApolloError } from 'react-apollo'` to `@apollo/react-hooks` and `@apollo/react-components`

fix(@apollo/*): export ApolloError type

---

definitions/npm/ramda_v0.26.x/flow_v0.104.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.104.x-/test_ramda_v0.26.x_logic.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/ramda_v0.26.x.js
definitions/npm/ramda_v0.x.x/flow_v0.104.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.104.x-/test_ramda_v0.x.x_logic.js
definitions/npm/ramda_v0.x.x/flow_v0.62.x-v0.81.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.82.x-v0.103.x/ramda_v0.x.x.js

- Links to documentation: https://ramdajs.com/docs/#complement
Ramda's `complement` returns a function whose type is the same as the input function provided. The runtime difference is that the `boolean` value is flipped when the function is called. Flow doesn't handle expressing this very well, and thus doesn't preserve the returned function's type. Until we have some mechanism to do this, we can write a bunch of arity variants - or generate them, as was done here. The libdef and its accompanying test are both generated.
If you want to generate higher arity to support or want to revisit the generation, the original generation was done here: https://github.com/LoganBarnett/typedef-gen

fix ramda complement

---

definitions/npm/qs_v6.5.x/flow_v0.104.x-/qs_v6.5.x.js
definitions/npm/qs_v6.5.x/flow_v0.45.x-v0.103.x/qs_v6.5.x.js
definitions/npm/qs_v6.9.x/flow_v0.104.x-/qs_v6.9.x.js
definitions/npm/qs_v6.9.x/flow_v0.45.x-v0.103.x/qs_v6.9.x.js
definitions/npm/qs_v6.9.x/test_qs.js

- Links to documentation: https://github.com/ljharb/qs
- Link to GitHub or NPM: https://github.com/ljharb/qs
- Type of contribution: new definition & fix
The `qs` libdefs used the only `Function`, `Object`, and sometimes `any` types - some of which cause issues in newer versions of Flow and/or flow-typed. The old `qs` 6.5.x tests have had the bare minimum done to get the tests passing again. Most of the work was done against a new (copied) set of libdefs for 6.9.x. I did not know what versions added which arguments, or if certain arguments were omitted on the original 6.5.x, and perusing the documentation for `qs` did not reveal this in a timely manner. It seemed to make sense make a clean break to 6.9.x. The 6.9.x
version of `qs` should be entirely backwards compatible with 6.5.x, since …

fix qs 6.5.x and add qs 6.9.x

---

definitions/npm/antd_v3.x.x/flow_v0.104.x-/antd_v3.x.x.js
definitions/npm/antd_v3.x.x/flow_v0.104.x-/test_antd_v3.x.x.js

**Ant-design** has added support for a new `type` value in the `<Button />` component in version 3.17 ([see changelog](https://ant.design/changelog#3.17.0)).
This PR adds support for this new `link` type, as well as a test to cover this.
- Links to documentation: https://ant.design/components/button/
- Link to GitHub or NPM: https://github.com/ant-design/ant-design + the [PR implementing this](https://github.com/ant-design/ant-design/pull/16289)
- Type of contribution: addition/fix
Other notes:
I'm unsure if the test is needed, since Flow should cover this - but I see similar tests have been added to the test-suite [in the past](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/antd_v3.x.x/flow_v0.104.x-/test_antd_v3.x.x.js#L512). Also, this is my first contribution, so …

[antd_v3.x.x] Updates enum for "type" in Button (to support new "link" type)

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js

- Links to documentation: https://lodash.com/docs/4.17.15#min and https://lodash.com/docs/4.17.15#max
min and max do not mutate the array so they should accept `$ReadOnlyArray`

lodash - use $ReadOnlyArray for `min` and `max`

---

definitions/npm/dompurify_v1.x.x/flow_v0.104.x-/dompurify_v1.x.x.js
definitions/npm/dompurify_v1.x.x/test_dompurify_v1.x.x.js

- Links to documentation: https://github.com/cure53/DOMPurify
- Link to GitHub or NPM: https://github.com/cure53/DOMPurify

[dompurify_v1.x.x] Remove deprecated $SubType and fix hooks

---

definitions/npm/jest_v24.x.x/flow_v0.39.x-v0.103.x/jest_v24.x.x.js

Part of jest-extended, but missing from `JestExtendedMatchersType` for some reason.
See https://github.com/jest-community/jest-extended#toincludesamemembersmembers.
- Links to documentation: https://github.com/jest-community/jest-extended#toincludesamemembersmembers.
- Link to GitHub or NPM: https://github.com/jest-community/jest
Other notes:
- All the other methods were using `any[]`, so I did that too. Should I use `mixed`?

fix(jest): add missing toIncludeSameMembers

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js

I was trying to use omitBy and pickBy on some properly defined $ReadOnly props, but was unable to due to the definitions of pickBy and omitBy.
Updated the definitions and it works. Figured I'd pass along my findings to the community :)
Other notes: Please enlighten me if you find my PR lacking.

Use readonly for lodash4 pickBy and omitBy

---

definitions/npm/haversine_v1.1.x/flow_v0.104.x-/haversine_v1.1.x.js
definitions/npm/haversine_v1.1.x/flow_v0.25.x-v0.103.x/haversine_v1.1.x.js
definitions/npm/haversine_v1.1.x/test_haversine_v1.1.x.js

- Links to documentation: https://github.com/njj/haversine
- Link to GitHub or NPM: https://github.com/njj/haversine
Other notes:
The previous definition of `ArrayCoordinates` was `Array<number>`, but its only uses expect an array of length 2 exactly. This change refines the type definition so that it is defined as a 2-tuple instead of an array.

[haversine_v1.1.x] ArrayCoordinates as 2-tuple

---

definitions/npm/dotenv_v8.x.x/flow_v0.53.x-/dotenv_v8.x.x.js
definitions/npm/dotenv_v8.x.x/test_dotenv_v8.x.x.js

- Links to documentation: https://github.com/motdotla/dotenv
- Link to GitHub or NPM: https://github.com/motdotla/dotenv
The libdefs for the v4 were already present but aren't accurate for v8 so I rewrote them from scratch, while borrowing and updating the tests.
I also quickly looked at the source code where they use Flow as well. Main differences with my libdefs is my use of `$Shape` over objects with only optional properties.

Add libdefs for dotenv v8

---

definitions/npm/react-navigation-stack_v1.x.x/flow_v0.104.x-/react-navigation-stack_v1.x.x.js
definitions/npm/react-navigation-stack_v1.x.x/flow_v0.92.x-v0.103.x/react-navigation-stack_v1.x.x.js

the `Props` for .a back button do not need to contain the entries I removed - see https://github.com/react-navigation/stack/blob/deb5605be8b1c7ccd27d339ba354923dbe762d3a/src/views/Header/HeaderBackButton.tsx#L19

fix: remove invalid react-navigation-stack back button props

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js

- Links to documentation: https://lodash.com/docs/4.17.15#xorBy
Other notes:
xorBy does not alter the arrays passed in.

Update lodash - xorBy accepts $ReadOnlyArray

---

definitions/npm/semver_v6.2.x/flow_v0.104.x-/semver_v6.2.x.js
definitions/npm/semver_v6.2.x/test_semver.js

- Links to documentation: https://github.com/npm/node-semver
- Link to GitHub or NPM: https://github.com/npm/node-semver
- Type of contribution: addition (add new version for existing package)
Change to previous definition:
```diff
diff --git definitions/npm/semver_v5.6.x/flow_v0.104.x-/semver_v5.6.x.js definitions/npm/semver_v6.2.x/flow_v0.104.x-/semver_v6.2.x.js
index c80ebbf8..ad3490d4 100644
--- definitions/npm/semver_v5.6.x/flow_v0.104.x-/semver_v5.6.x.js
+++ definitions/npm/semver_v6.2.x/flow_v0.104.x-/semver_v6.2.x.js
@@ -36,6 +36,7 @@ declare module "semver" {
compare(other: string | SemVer): -1 | 0 | 1;
compareMain(other: string | SemVer): -1 | 0 | 1;
comparePre(other: string | SemVer): -1 | 0 | 1;
+    compareBuild(other: string | SemVer): -1 | 0 | 1;
format(): string; …
```

Add semver 6.2.x

---

definitions/npm/supertest_v4.x.x/flow_v0.94.x-/supertest_v4.x.x.js
definitions/npm/supertest_v4.x.x/test_basic-functionality.js

- Links to documentation: I don't think this is documented really, but this is set in https://github.com/visionmedia/superagent/blob/477f3c5141cb0f80e593baf477e4b5a172ac1839/src/node/index.js#L854
- Link to GitHub or NPM: https://github.com/visionmedia/supertest
Other notes:

Add the 'called' property to supertest

---

definitions/npm/ramda_v0.26.x/flow_v0.104.x-/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.104.x-/test_ramda_v0.26.x_relation.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/ramda_v0.26.x.js
definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/test_ramda_v0.26.x_relation.js

- Links to documentation: https://ramdajs.com/docs/#intersection
Other notes:
Refactor intersection to take ready only input, $ReadOnlyArray is super type of Array, so it satisfies everything in Array, except it has fewer methods on it.

Intersection readonly refactor

---

definitions/npm/lodash-es_v4.x.x/flow_v0.104.x-/lodash-es_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js

- Links to documentation: https://lodash.com/docs/4.17.15
Other notes:
As documented in `lodash` doc linked above, both `pickBy` and `omitBy` create new objects and leave input arguments untouched. So updated argument types to `$ReadOnly` accordingly.

let `lodash` take input object as `$ReadOnly`

---

definitions/npm/axios_v0.19.x/flow_v0.80.x-/axios_v0.19.x.js
definitions/npm/axios_v0.19.x/flow_v0.80.x-/test_axios_v0.19.x.js

- Links to documentation: https://github.com/axios/axios
- Link to GitHub or NPM: https://github.com/axios/axios
Other notes:
Also did a little bit refactor to remove "any" type in definition and get tests passed

Axios new options definition

---

definitions/npm/react-intl_v2.x.x/flow_v0.104.x-/react-intl_v2.x.x.js
definitions/npm/react-intl_v2.x.x/flow_v0.104.x-/test_react-intl_v2.x.x.js

Hello Flow Typed Team,
this change removes a bug which we experienced with `IntlShape`. In our case, everything except the first of type in the intersection `$npm$ReactIntl$IntlConfig` was missing when we did a spread of the property. This makes me believe that `$npm$ReactIntl$IntlConfig` is treated `exact` in our code base, even though it is not declared as exact.
We do not experience the bug in https://flow.org/try/ unless we make the first type of the intersection `$npm$ReactIntl$IntlShape` exact as you can see below:
[example](https://flow.org/try/#0C4TwDgpgBAJAdmAtjAShAhgY2ASTsAGxj0IGEB7OAMwEsBzKAXigG8AfAKCm6gPM3QEIALigBnYACcacOgBouPKuUmJ0wMaIDyAIwBWEbAp5REEMWPR1zollADaNACaiJ02QF1XUmQwC+CorcThBU6ACuBMAAMvyCEAD83u7yQVAhYZHAAGIqahpJULoG2IpsfgDcHBygkLAIyGhYuPhEALLmltYAIuaY0mDAKkysac7JvsY …

fix: replace intlshape intersection type with spread

---

definitions/npm/url-parse_v1.3.x/flow_v0.104.x-/url-parse_v1.3.x.js
definitions/npm/url-parse_v1.3.x/flow_v0.59.x-v0.103.x/url-parse_v1.3.x.js
definitions/npm/url-parse_v1.3.x/test_url-parse.js

- Links to documentation: https://github.com/unshiftio/url-parse
- Link to GitHub or NPM: https://www.npmjs.com/package/url-parse
Other notes:
Always parses query `"?a=b&c=2"` as  `{ "a" : "b", "c" : "2" }`
https://github.com/unshiftio/url-parse/blob/master/test/test.js

Amended type-defination of url-parser

---

definitions/npm/history_v4.x.x/flow_v0.104.x-/history_v4.x.x.js
definitions/npm/history_v4.x.x/flow_v0.104.x-/test_history_v4.x.x.js
definitions/npm/react-router-dom_v5.x.x/flow_v0.104.x-/react-router-dom_v5.x.x.js
definitions/npm/react-router-native_v4.x.x/flow_v0.104.x-/react-router-native_v4.x.x.js
definitions/npm/react-router_v5.x.x/flow_v0.104.x-/react-router_v5.x.x.js

https://github.com/ReactTraining/history/tree/master/docs
https://github.com/ReactTraining/react-router/tree/master/packages/react-router/docs/api
Other notes:
Should fix #1910.
Making `MemoryHistory.canGo` optional is actually wrong, but I don't see another way to work around flow bugs.
All `history/*` modules can be probably moved to `history`, it would reduce duplication. But I added `history` anyway becase normally everything is exported from `history`.
Properties I removed from `react-router-*` don't belong to the generic Location interface.

Make history interface compatible with react-router

---

definitions/npm/next_v9.x.x/flow_v0.104.x-/next_v9.x.x.js
definitions/npm/next_v9.x.x/flow_v0.104.x-/test_next_v9.x.x.js

Hi 👋 
I would like to add definitions for next 9.x - https://nextjs.org/ 
We use definitions for version 7 in our app built on next 9.x without issues, so I would like to kick it off with simple reuse of these definitions.
- `DocumentContext` - see https://github.com/zeit/next.js/blob/8f662c44c944b46693e666013a83f88e4fcffc5a/examples/with-typescript-styled-components/pages/_document.tsx#L5 and https://github.com/zeit/next.js/blob/58b2d9e208c56cee0dab2eff287d2a19cb0e6de1/packages/next/next-server/lib/utils.ts#L137

[next_v9.x.x] add support for next 9.x

---

definitions/npm/webpack_v4.x.x/flow_v0.104.x-/webpack_v4.x.x.js
definitions/npm/webpack_v4.x.x/flow_v0.71.x-v0.103.x/webpack_v4.x.x.js

- Links to documentation: https://webpack.js.org/
- Link to GitHub or NPM: https://www.npmjs.com/package/webpack
- Type of contribution: Fix
Other notes:
```sh
Error --------------------------------------------------------------------------------------- src/utils/buildJs.js:42:26
Cannot call `stats.toString` with object literal bound to `options` because object type [1] is incompatible with
boolean [2] in property `colors`.
src/utils/buildJs.js:42:26
42|       log(stats.toString({ logStats, colors: true }));
^^^^^^^^^^^^^^^^^^^^^^^^^^
References:
../../flow-typed/npm/webpack_v4.x.x.js:399:9
v
399|       | {
400|       bold?: string,
401|       cyan?: string,
402|       green?: string,
403|       magenta?: string,
404|       red?: string,
405|       yellow?: string,
406|       ...
407| …
```

[webpack_v4.x.x] Fix type error

---

definitions/npm/antd_v3.x.x/flow_v0.104.x-/antd_v3.x.x.js
definitions/npm/antd_v3.x.x/flow_v0.104.x-/test_antd_v3.x.x.js
definitions/npm/antd_v3.x.x/flow_v0.25.x-v0.103.x/antd_v3.x.x.js
definitions/npm/antd_v3.x.x/flow_v0.25.x-v0.103.x/test_antd_v3.x.x.js

`DatePicker` was declared before, which could cause overwriting and losing the declaration of `RangePicker`.
See: [Another Declaration](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/antd_v3.x.x/flow_v0.104.x-/antd_v3.x.x.js#L100)

[antd_v3.x.x] Remove duplicate declaration of DatePicker

---

definitions/npm/query-string_v6.x.x/flow_v0.104.x-/query-string_v6.x.x.js
definitions/npm/query-string_v6.x.x/test_query-string_v6.x.x.js

Update `query-string_v6.x.x.js` definitions with latest options and methods that were missing.
- Type of contribution: update definition
- Links to documentation: https://github.com/sindresorhus/query-string#stringifyobject-options
I updated the tests as well as I could, hope that's sufficient.
closes #3693

Update query-string 6.x definitions

---

definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/react_v8.x.x.js
definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/test_react_v8.x.x.js
definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/react_v9.x.x.js
definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/test_react_v9.x.x.js

- Link to GitHub or NPM: Fixes https://github.com/flow-typed/flow-typed/issues/3520
Other notes:
Fixes https://github.com/flow-typed/flow-typed/issues/3520, that is, `@testing-library/react` types being broken ever since https://github.com/flow-typed/flow-typed/pull/3510 was merged in.
The first commit in this PR shows how the existing types are broken.

[@testing-library/react_v8.x.x] and [@testing-library/react_v9.x.x]: Fix typing regression

---

definitions/npm/throttle-debounce_v2.x.x/flow_v0.104.x-/throttle-debounce_v2.x.x.js
definitions/npm/throttle-debounce_v2.x.x/flow_v0.25.x-v0.103.x/throttle-debounce_v2.x.x.js
definitions/npm/throttle-debounce_v2.x.x/test_throttle-debounce_v2.x.x.js

- Links to documentation: https://github.com/niksy/throttle-debounce
- Link to GitHub or NPM: https://www.npmjs.com/package/throttle-debounce
Other notes:
No difference between the API v1 and v2, so I just copied the libdefs from v1 and update the test cases.

Add libdefs & tests for throttle-debounce@2.x.x

---

definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/react_v9.x.x.js
definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/test_react_v9.x.x.js

- Links to documentation: https://testing-library.com/docs/react-testing-library/api#queries
Other notes:
I meant to do this as part of https://github.com/flow-typed/flow-typed/pull/3704 but after banging my head against the keyboard for an hour, I decided to cut this out from that PR.
EDIT: Oh yess, I think I managed to write out the types so that they pass now! Anyway, as this is a more extensive change than #3704, I'd prefer the other PR to be merged first.

[@testing-library/react_v9.x.x] render() type safety for custom queries

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/test_lodash-v4.x.x.js

Lodash tests currently fail with the latest version of flow.
This should fix it.

Fix lodash tests

---

definitions/npm/react-dom_v16.x.x/flow_v0.117.x-/react-dom_v16.x.x.js
definitions/npm/react-dom_v16.x.x/flow_v0.117.x-/test_react-dom_v16.x.x.js

Other notes:
[This is verbatim the Flow definitions](https://github.com/facebook/flow/blob/90fcd8f83df4c791266f985689ad959a775f8667/lib/react-dom.js#L1-L117). I also moved the relevant tests to flow-typed.
We're keeping the Synthetic*Event types in Flow for now. We will need to keep the $JSXIntrinsics in Flow forever, since we use that type internally in our type checking.
These types will be moved out of Flow as early as 0.118, but might not make the cut until 0.119.
On the Flow side, I added a test where we have a `flow-typed/npm/react-dom_v16.x.x.js` with this exact definition and I ensure that we have access both to types in `react-dom.js` in Flow and `react-dom_v16.x.x.js` from flow-typed.

move react-dom to flow-typed

---

definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/test_react_v8.x.x.js
definitions/npm/@testing-library/react_v8.x.x/flow_v0.67.1-v0.103.x/test_react_v8.x.x.js
definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/react_v9.x.x.js
definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/test_react_v9.x.x.js
definitions/npm/react-testing-library_v3.x.x/flow_v0.104.x-/test_react-testing-library_v3.x.x.js
definitions/npm/react-testing-library_v3.x.x/flow_v0.60.0-v0.103.x/test_react-testing-library_v3.x.x.js
definitions/npm/react-testing-library_v5.x.x/flow_v0.104.x-/test_react-testing-library_v5.x.x.js
definitions/npm/react-testing-library_v5.x.x/flow_v0.67.1-v0.103.x/test_react-testing-library_v5.x.x.js

- Links to documentation: https://testing-library.com/docs/react-testing-library/intro
- Link to GitHub or NPM: https://github.com/flow-typed/flow-typed/pull/3705
Other notes:
Following up from https://github.com/flow-typed/flow-typed/pull/3705, this PR cleans up the existing `@testing-library/react_v9.x.x` types so that there are less confusing parts.
At any point of this PR, this is ready to be merged. When reviewers have time, I will be happy to get this PR merged and then can continue future work on these types in another PR :relaxed:

[@testing-library/react_v9.x.x] refactor: Clean up the types

---

cli/flow-typed/npm/yargs_v4.x.x.js
cli/src/cli.js

- Type of contribution: feature
`yargs` provides out of the box support to help out the users if they mistype a command.

feat(cli): recommend matching commands

---

definitions/npm/moment_v2.x.x/flow_v0.104.x-/moment_v2.x.x.js

docs:
https://momentjs.com/docs/#/customization/relative-time-rounding/
https://momentjs.com/docs/#/customization/relative-time-threshold/

[moment_v2.x.x] Add methods relativeTimeRounding & relativeTimeThreshold

---

definitions/npm/@sentry/browser_v5.x.x/flow_v0.84.x-/browser_v5.x.x.js
definitions/npm/@sentry/browser_v5.x.x/test_browser_v5.x.x.js

https://docs.sentry.io/platforms/javascript/
https://docs.sentry.io/platforms/javascript/advance-settings/
https://docs.sentry.io/error-reporting/configuration/?platform=browser
https://github.com/getsentry/sentry-javascript/blob/5.11.2/packages/browser/src/exports.ts
Documentation isn't 100% comprehensive, so the definitions are a combination of what's documented as well as what I could infer from the TypeScript definitions linked above.
Separately, the tests run by `./build_and_test_cli.sh` fail for me, and none of the CLI commands appear to work, so relying on the CI for actually checking this.

Add libdefs & tests for @sentry/browser@5.x.x

---

definitions/npm/enzyme_v3.x.x/flow_v0.104.x-/enzyme_v3.x.x.js
definitions/npm/enzyme_v3.x.x/flow_v0.104.x-/test_enzyme-v3.x.js
definitions/npm/enzyme_v3.x.x/flow_v0.53.x-v0.103.x/enzyme_v3.x.x.js
definitions/npm/enzyme_v3.x.x/flow_v0.53.x-v0.103.x/test_enzyme-v3.x.js

Fixes #3720
Enzyme 3.10.0 introduced `invoke` function to wrappers. This function
accepts a prop name and returns a function, decorated with enzyme internal magic.
- Links to documentation: [Changelog][1] and [invoke function documentation][3]
- Link to GitHub or NPM:  [function implementation][2]
- Type of contribution: **addition**
[1]: https://github.com/airbnb/enzyme/blob/enzyme%403.10.0/CHANGELOG.md#new-stuff
[2]: https://github.com/airbnb/enzyme/blob/c62cc4114f97f73283b2c1153c6110e574cdbe81/packages/enzyme/src/ReactWrapper.js#L837-L851 "invoke function implementation"
[3]: https://github.com/airbnb/enzyme/blob/e3d6d5effc44be40718729c425205ffffb242ac2/docs/api/ReactWrapper/invoke.md
Other notes:

Add enzyme invoke definition

---

definitions/npm/styled-components_v4.x.x/flow_v0.104.x-/styled-components_v4.x.x.js

Fixes #3666
Allows a styled-component to return either an array of strings, or a function

Allow styled-components to return a function

---

definitions/npm/styled-components_v4.x.x/flow_v0.104.x-/styled-components_v4.x.x.js
definitions/npm/styled-components_v4.x.x/flow_v0.104.x-/test_styled-components_v4.x.x.js

Changes:
1. The return value of `StyleSheetManager.prototype.render`
2. All styled components implicitly support `style`, `className`, and `children`, so reflect that.  
People can still override them if they need to (e.g. wanting to narrow `children` with `children?: React.ChildrenArray<…>`) using `Props`.
**Note**: One big "breaking change" is that strict props are no longer "respected" on components. So, it won't catch typos any longer. This now more aligns with flow's new "only error if there's a runtime error" paradigm (unless I am wrong and this does cause runtime errors, but extra props shouldn't cause runtime errors).
Making it a draft while I still test some of this against our production codebase at work, too. The tests seem to be happy and this seems to work on one of our …

[styled-components v4] Various small improvements to the libdefs

---

definitions/npm/reselect_v4.x.x/flow_v0.104.x-/reselect_v4.x.x.js

- Links to documentation: https://github.com/reduxjs/reselect/blob/master/README.md
- Link to GitHub or NPM: https://github.com/reduxjs/reselect
Other notes: This is a very simple change and is backward compatible so I didn't need to write any new tests. I am just redefining the `OutputSelector` type to a callable object since it achieves a more accurate typing (closer to the real api). The previous definition was an intersection between an `InputSelector` (function) and an object containing the rest of the api.
This also seems to fix [this issue](https://github.com/flow-typed/flow-typed/issues/3127), which happens to be really hard to reproduce. After applying the proposed change locally in one of the projects where I have encountered the issue it was properly …

[reselect_v4.x.x.js] Redefine OutputSelector type as a callable object

---

cli/src/commands/install.js

Other notes:
Fixes https://github.com/flow-typed/flow-typed/issues/3726. We are moving react-dom out of Flow. It is already in flow-typed!

Remove react-dom from built-in flow libdefs

---

definitions/npm/qs_v6.5.x/flow_v0.104.x-/qs_v6.5.x.js
definitions/npm/qs_v6.5.x/flow_v0.45.x-v0.103.x/qs_v6.5.x.js
definitions/npm/qs_v6.9.x/flow_v0.104.x-/qs_v6.9.x.js
definitions/npm/qs_v6.9.x/flow_v0.45.x-v0.103.x/qs_v6.9.x.js
definitions/npm/qs_v6.9.x/test_qs.js

- Make qs.stringify obj param $ReadOnly
https://flow.org/en/docs/types/arrays/#toc-readonlyarray
https://flow.org/en/docs/types/utilities/#toc-readonly
Other notes:
Resolve Flow errors for qs.stringify object param by making obj read only.

qs: Make stringify 'obj' param $ReadOnly

---

definitions/npm/styled-components_v5.x.x/flow_v0.104.x-/styled-components_v5.x.x.js
definitions/npm/styled-components_v5.x.x/flow_v0.104.x-/test_styled-components-native.js
definitions/npm/styled-components_v5.x.x/flow_v0.104.x-/test_styled-components_v5.x.x.js

Adds libdefs for v5 of styled-components. Mostly it's the same as libdefs for v4, but with the following non-breaking changes (copied from the [release notes]):
- adds `useTheme` hook
- adds `stylisPlugins` prop to `StyleSheetManager`
- adds `disableVendorPrefixes` prop to `StyleSheetManager`
- adds `disableCSSOMInjection` prop to `StyleSheetManager`
The *"subfunction" attrs syntax that was deprecated in v4* which is removed in v5 was never supported in v4 libdefs (because it was deprecated), so nothing to do here.
---
I also took the opportunity to fix some type issues I encountered in the v4 libdefs. Interpolations should be more reliable and error in fewer cases (still doesn't support Polished's `Styles`).
In some cases Flow would claim that `React$AbstractComponent` wasn't compatible …

[styled-components v5] add libdefs

---

definitions/npm/styled-components_v5.x.x/flow_v0.104.x-/styled-components_v5.x.x.js

Removed the overload that never worked. It was a leftover from an unfinished experiment. :(
Added a few comments to silence the eslint noise.

[styled-components_v5] remove invalid types

---

definitions/npm/qs_v6.5.x/flow_v0.45.x-v0.103.x/qs_v6.5.x.js
definitions/npm/qs_v6.9.x/flow_v0.45.x-v0.103.x/qs_v6.9.x.js

Other notes:
https://github.com/flow-typed/flow-typed/pull/3737#issuecomment-590247801 Resolves the issue mentioned here

Fix qs compatability with older versions of Flow

---

definitions/npm/luxon_v0.2.x/flow_v0.104.x-/luxon_v0.2.x.js
definitions/npm/luxon_v0.2.x/flow_v0.104.x-/test_luxon.js
definitions/npm/luxon_v0.2.x/flow_v0.32.0-v0.103.x/luxon_v0.2.x.js
definitions/npm/luxon_v0.4.x/flow_v0.104.x-/luxon_v0.4.x.js
definitions/npm/luxon_v0.4.x/flow_v0.104.x-/test_luxon.js
definitions/npm/luxon_v1.x.x/flow_v0.104.x-/luxon_v1.x.x.js
definitions/npm/luxon_v1.x.x/flow_v0.104.x-/test_luxon.js
definitions/npm/luxon_v1.x.x/flow_v0.32.0-v0.103.x/luxon_v1.x.x.js

- Links to documentation: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-diff
- Link to GitHub or NPM: https://github.com/moment/luxon/blob/0.0.18/src/datetime.js#L1450
Other notes:
Luxon methods `diff` and `diffNow` both have default args for the `unit` parameter (looks like since v0.18.0). Fixing the type

Fix luxon diff / diffnow

---

definitions/npm/@koa/router_v8.0.x/flow_v0.84.x-/router_v8.0.x.js
definitions/npm/@koa/router_v8.0.x/test_koa-router.js

I realized that I got it wrong when I implemented it some months ago. Locally I was using an older version of the file that didn't have this problem.
Maybe this sort of issue could be found by automatic tests?

Fix definitions for @koa/router

---

definitions/npm/nanoevents_v4.x.x/flow_v0.104.x-/nanoevents_v4.x.x.js
definitions/npm/nanoevents_v4.x.x/flow_v0.104.x-/test_nanoevents_v4.x.x.js

Api is not class based anymore.
- Link to GitHub or NPM: https://github.com/ai/nanoevents

Add nanoevents v4.x.x definition

---

definitions/npm/styled-components_v4.x.x/flow_v0.104.x-/styled-components_v4.x.x.js
definitions/npm/styled-components_v4.x.x/flow_v0.104.x-/test_styled-components-macro.js
definitions/npm/styled-components_v5.x.x/flow_v0.104.x-/styled-components_v5.x.x.js
definitions/npm/styled-components_v5.x.x/flow_v0.104.x-/test_styled-components-macro.js

add support for styled-components/macro, which exports the same as styled-components
- Links to documentation: https://styled-components.com/docs/tooling#babel-macro
- Link to GitHub or NPM: https://github.com/styled-components/styled-components/tree/master/packages/styled-components/src/macro

add support for styled-components/macro

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.104.x-/test_lodash-v4.x.x.js

- Type of contribution: fix, refactor
This PR should close #1099 as it adds $ReadOnlyArray<> instead of Array<> to all remaining functions, which do not mutate input array.
Other notes:
There were many "partial fix" PRs before this one, as can be seen in #1099 . This PR fixes remaining functions and allows to pass readonly arrays to them.
Was checking with [lodash docs](https://lodash.com/docs/4.17.15) to verify if input array is mutated or not
Change is big, because I thought it is easier to redactor code a bit, especially have tests in sorted order. Therefore, I've split the independent work into separate commits. _It may be easier to check PR commit by commit_

Lodash - replace Array<> with $ReadOnlyArray<> in all remaining functions, which do not mutate arrays in their arguments

---

definitions/npm/@sentry/browser_v5.x.x/flow_v0.84.x-/browser_v5.x.x.js
definitions/npm/@sentry/browser_v5.x.x/test_browser_v5.x.x.js

In #3723, I added libdefs for @sentry/browser. I forgot to add types for two additional exports: Integrations and Transports. This PR adds them.
https://docs.sentry.io/platforms/javascript/#sdk-integrations
https://github.com/getsentry/sentry-javascript/blob/5.12.3/packages/browser/src/index.ts

[@sentry/browser] Add Integrations and Transports, fix extras

---

definitions/npm/express_v4.17.x/flow_v0.104.x-/express_v4.17.x.js
definitions/npm/express_v4.17.x/flow_v0.104.x-/test_useMethod.js

Previously, this would fail to support Router#use function with a single middleware function.
- Links to documentation: [`app.use`](http://expressjs.com/en/4x/api.html#app.use), [`Router#use`](http://expressjs.com/en/4x/api.html#router.use)
- Link to GitHub or npm: https://www.npmjs.com/package/express

feat(express): support more comprehensive types for Router#use

---

definitions/npm/nanoevents_v5.x.x/flow_v0.104.x-/nanoevents_v5.x.x.js
definitions/npm/nanoevents_v5.x.x/flow_v0.104.x-/test_nanoevents_v5.x.x.js

The project is migrated to named export.
- Link to GitHub or NPM: https://github.com/ai/nanoevents

Add nanoevents v5

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.104.x-/test_lodash-fp-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.104.x-/test_lodash-v4.x.x.js

Previous PR #3763 was closed a bit too quickly :) 
This PR is kind of a second part to that one - it adds $ReadOnlyArray<> instead of Array<> to lodash/fp functions arguments (only for functions which do not mutate input arrays according to docs). This PR is also related to closing #1099 .
Also this PR makes types of sample, sampleSize, shuffle more precise (tests added).

[Lodash] add ReadOnlyArray to lodash/fp and some missed functions

---

definitions/npm/styled-components_v4.x.x/flow_v0.104.x-/styled-components_v4.x.x.js

Fixes #3778 
Allows functions to be used and does proper type checking within.
_Thanks go to @dennisoelkers for helping troubleshoot and find a solution for this._

Allow function within styled(..)

---

definitions/npm/zen-observable_v0.8.x/flow_v0.104.x-/test_zen-observable.js
definitions/npm/zen-observable_v0.8.x/flow_v0.104.x-/zen-observable_v0.8.x.js
definitions/npm/zen-observable_v0.8.x/flow_v0.69.0-v0.103.x/test_zen-observable.js
definitions/npm/zen-observable_v0.8.x/flow_v0.69.0-v0.103.x/zen-observable_v0.8.x.js

Other notes: I forgot that the function passed to the Observable constructor can
return a cleanup function or subscription (https://github.com/zenparsing/zen-observable#new-observablesubscribe)
Also `SubscriptionObserver` couldn't be passed as an `Observer`, this is now fixed

fix(zen-observable): fix variance, subscriber return type

---

definitions/npm/firebase_v5.x.x/flow_v0.104.x-/firebase_v5.x.x.js
definitions/npm/firebase_v5.x.x/flow_v0.104.x-/test_firebase.js

From Firebase v5.0.0 changelog: "Merged the includeQueryMetadataChanges and includeDocumentMetadataChanges options passed to Query.onSnapshot() into a single includeMetadataChanges option."
Changes:
- Removed deprecated `includeQueryMetadataChanges` option from the `$npm$firebase$firestore$QueryListenOptions` interface. (Curiously, the other deprecated option, `includeDocumentMetadataChanges` didn't seem to have ever been in the interface.)
- Removed `$npm$firebase$firestore$QueryListenOptions` variant from `observerOrOnNextOrOnError` in the `firebase.firestore.Query.onSnapshot` `firebase.firestore.DocumentReference.onSnapshot`. 
Not sure why the options variant was provided as an option in the second position. Maybe I'm wrong here—does the options variant need to stay?
- Links to …

Fixed signature for `firebase.firestore.Query.onSnapshot` & `firebase.firestore.DocumentReference.onSnapshot`

---

cli/src/lib/npm/__tests__/npmLibDefs-test.js
cli/src/lib/npm/npmLibDefs.js

partial fix for #3363
Other notes:
We should still probably make getInstalledNpmLibDefs tolerate any bad version strings.

fix(getInstalledNpmLibDefs): fix <<STUB>> parsing

---

definitions/npm/cookie_v0.4.x/flow_v0.104.x-/cookie_v0.4.x.js
definitions/npm/cookie_v0.4.x/flow_v0.104.x-/test_cookie_v0.4.x.js
definitions/npm/cookie_v0.4.x/flow_v0.58.x-v0.103.x/cookie_v0.4.x.js

Cookie v0.4.0 added SameSite=None support, I added this to the interface.
- Link to GitHub or NPM: https://github.com/jshttp/cookie/releases

Add cookie_v0.4.x support

---

definitions/npm/credit-card-type_v7.x.x/flow_v0.25.x-/credit-card-type_v7.x.x.js
definitions/npm/credit-card-type_v7.x.x/flow_v0.25.x-/test_credit-card-type_v7.x.x.js
definitions/npm/credit-card-type_v8.x.x/flow_v0.25.x-/credit-card-type_v8.x.x.js
definitions/npm/credit-card-type_v8.x.x/flow_v0.25.x-/test_credit-card-type_v8.x.x.js

- Links to documentation: https://github.com/braintree/credit-card-type
- Link to GitHub or NPM: https://github.com/braintree/credit-card-type

Added credit-card-type v7 & v8

---

definitions/npm/re-reselect_v1.x.x/flow_v0.104.x-/test_re-reselect_1.x.x.js
definitions/npm/re-reselect_v2.x.x/flow_v0.104.x-/test_re-reselect.js
definitions/npm/reselect_v2.x.x/flow_v0.104.x-/test_reselect_2.x.x.js
definitions/npm/reselect_v3.x.x/flow_v0.104.x-/reselect_v3.x.x.js
definitions/npm/reselect_v3.x.x/flow_v0.104.x-/test_reselect_3.x.x.js
definitions/npm/reselect_v4.x.x/flow_v0.104.x-/test_reselect_4.x.x.js
definitions/npm/validator_v7.x.x/test_validator_v7.x.x.js

* Type of contribution: fix
Other notes:
Applying #3732 fix for reselect_v4 to reselect_v3 as well.
This fixes #3127, since the author had problem with reselect_v3.

[reselect_v3.x.x.js] Redefine OutputSelector type as a callable object 

---

definitions/npm/fs-extra_v7.x.x/flow_v0.104.x-/fs-extra_v7.x.x.js
definitions/npm/fs-extra_v7.x.x/test_fs-extra_v7.x.x.js

Right now fs-extra types cover only the new methods that were added to fs-extra. I have added fs library types to cover fs methods that are also available in fs-extra.

fs-extra: inherit fs library types

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.104.x-/test_lodash-fp-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.104.x-/test_lodash-v4.x.x.js

* Type of contribution: fix, refactor, tests
1. Lodash functions should accept $ReadOnly objects as arguments for functions which do not mutate them. Right now it does not.
This is also in line with guides in CONTRIBUTING doc - to prefer $ReadOnly objects over just `{}`;
This fix is similar to #3763 but it is for objects instead of arrays.
1.  This PR also adds some unit tests:
* test for code examples from docs for all Collections functions
* Reusing tests for functions which must have exactly same types according to docs (e.g. `each/eachRight/forEach/forEachRight`) . THis has helped to uncover some inconsistencies in them.
* tests for readonly objects - for functions with non-trivial changes. Can add to more.
* add testing of return types for all existing Collection functions. Adding …

Lodash - use $ReadOnly object for arguments

---

definitions/npm/@apollo/react-common_v3.x.x/flow_v0.104.x-/react-common_v3.x.x.js
definitions/npm/apollo-client_v2.x.x/flow_v0.104.x-/apollo-client_v2.x.x.js
definitions/npm/apollo-client_v2.x.x/flow_v0.57.x-v0.103.x/apollo-client_v2.x.x.js

- Links to documentation: https://www.apollographql.com/docs/react/api/react-apollo/#datanetworkstatus
- Link to GitHub or NPM: https://github.com/apollographql/apollo-client/blob/3d6dc49e7c1c23daf0ac47cc9f91af271fbda2e4/src/core/networkStatus.ts
Other notes:
Apollo exports a NetworkStatus object that is a mapping from
strings to the associated network status number. This was being
hidden by the type export that already existed in the library
definition.

apollo-client - Export the correct NetworkStatus

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js

Other notes:
Removing unused generic type parameter as mentioned in the comment to my previous PR https://github.com/flow-typed/flow-typed/pull/3777#issuecomment-609843093.
Checked - no other method has unused `K` parameter.

lodash - remove unused generic type parameter

---

definitions/npm/redux-mock-store_v1.2.x/flow_v0.104.x-/redux-mock-store_v1.2.x.js
definitions/npm/redux-mock-store_v1.2.x/test_redux-mock-store_v1.js

- Links to documentation: https://github.com/dmitry-zaets/redux-mock-store
- Link to GitHub or NPM: https://github.com/dmitry-zaets/redux-mock-store
Other notes:
Allows to pass subtypes of string to the dispatch()
This change is in line with recommendation in CONTRIBUTING.md.

redux-mock-store - use readonly type for covariance

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.104.x-/react-router-dom_v4.x.x.js
definitions/npm/react-router-dom_v5.x.x/flow_v0.104.x-/react-router-dom_v5.x.x.js

- Links to documentation:https://reacttraining.com/react-router/web/api/Link
- Link to GitHub or NPM: https://github.com/ReactTraining/react-router
Other notes:
Since Link does not change its props (except for `innerRef`), this change is in line with "prefer immutability for input args" recommendation in CONTRIBUTING.md.
This change is needed to allow to conditionally replace <Link> with another component which has `type: string` prop.
```
type Props = {|
type: string
// etc.
|}
(props: Props) => x ? <MyCustomLink {...props} /> : <Link {...props} />;
```
Without the change, there is an error that `type: string` in Props is not compatible with `type: string | LocationShape` in the libdef

react-router-dom - use readonly types for covariance

---

definitions/npm/jest_v17.x.x/test_jest-v17.x.x.js
definitions/npm/jest_v18.x.x/test_jest-v18.x.x.js
definitions/npm/jest_v19.x.x/test_jest-v19.x.x.js
definitions/npm/jest_v20.x.x/flow_v0.104.x-/test_jest-v20.x.x.js
definitions/npm/jest_v20.x.x/flow_v0.25.x-v0.38.x/test_jest-v20.x.x.js
definitions/npm/jest_v20.x.x/flow_v0.39.x-v0.103.x/test_jest-v20.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.104.x-/test_jest-v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.25.x-v0.38.x/test_jest-v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.39.x-v0.103.x/test_jest-v21.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.104.x-/test_jest-v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/test_jest-v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.39.x-v0.103.x/test_jest-v22.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.104.x-/test_jest-v23.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.39.x-v0.103.x/test_jest-v23.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.104.x-/jest_v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.104.x-/test_jest-v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.39.x-v0.103.x/jest_v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.39.x-v0.103.x/test_jest-v24.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.104.x-/jest_v25.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.104.x-/test_jest-v25.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.39.x-v0.103.x/jest_v25.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.39.x-v0.103.x/test_jest-v25.x.x.js

Adds `toMatchDiffSnapshot` to Jest custom matchers
- Link to GitHub or NPM: https://github.com/jest-community/snapshot-diff
[Typescript](https://github.com/jest-community/snapshot-diff/blob/master/index.d.ts#L18)
- Type of contribution: addition | fix
Other notes:
Fix location of $ExpectError for all Jest versions with the issue

Add snapshot diff

---

definitions/npm/@sentry/browser_v5.x.x/flow_v0.84.x-/browser_v5.x.x.js

- Links to documentation: https://docs.sentry.io/enriching-error-data/additional-data/?platform=javascript
- Link to GitHub or NPM: https://github.com/getsentry/sentry-javascript/blob/645ff532941d9a23bb6531c6305e99544b356502/packages/minimal/src/index.ts#L136
This is to match types in the original library. Also unsetting the user context is required and pretty common when logging users out of your application

Allow @sentry/browser setUser to accept null

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js

https://lodash.com/docs/4.17.15#flatMap
```
(() => { const arrays = []; console.log(_.flatMap([1,2], (n) => { arrays[n] = [n]; return arrays[n]; })); console.log(arrays); })();
```
Other notes:
This broke after updating our codebase after this pr: https://github.com/flow-typed/flow-typed/pull/3777
Since quite often we end up returning bits of redux-state from inside a flatMap, that is marked a as read only array. I am fairly sure lodash doesn't modify the arrays coming from a map.

[lodash] Allow flatmap iterator to return a read only array

---

definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/react_v10.x.x.js
definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/test_react_v10.x.x.js

- Links to documentation: https://testing-library.com/docs/dom-testing-library/api-helpers#getnodetext
Other notes: Add missing function to main export

[@testing-library/react_v10.x.x] add missing getNodeText helper function

---

definitions/npm/yargs_v10.x.x/flow_v0.104.x-/yargs_v10.x.x.js
definitions/npm/yargs_v10.x.x/flow_v0.54.x-v0.103.x/yargs_v10.x.x.js

Link to documentation: https://yargs.js.org/docs/#api-versionversionboolean

[yargs_v10.x.x] Fix type definitions: add boolean argument for version

---

definitions/npm/uuid_v8.x.x/flow_v0.104.x-/test_uuid_v8.x.x.js
definitions/npm/uuid_v8.x.x/flow_v0.104.x-/uuid_v8.x.x.js

All is the same. Only deprecated direct imports dropped and added native
node esm support.
- Link to GitHub or NPM: https://github.com/uuidjs/uuid
- Type of contribution: new definition | addition

Add uuid v8

---

definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/test_react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/test_react-hooks_v3.x.x.js

Other notes:
Fix for issue described here
https://github.com/flow-typed/flow-typed/issues/3718
I have made the `DataProxyReadQueryOptions` type accept the generic type that it is being passed, and added a couple of tests for this

Apollo hooks read query fix

---

definitions/npm/chai_v4.x.x/flow_v0.104.x-/chai_v4.x.x.js

https://www.chaijs.com/api/assert/#method_exists
https://www.chaijs.com/api/assert/#method_deepinclude
addition
Other notes:
Added definitions for deepInclude, notDeepInclude, exists, notExists.

Added deepInclude, exists and opposites

---

definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js

- Links to documentation: https://lodash.com/docs/4.17.15#compact
I'd like to discuss the correct fix for _.compact. Currently code like this is common in our code base:
```
const array = [
condition && a,
];
return _.compact<A, A>(array);
```
which fails with the new typings (https://github.com/flow-typed/flow-typed/pull/3777).
As per the docs, the input type can include numbers and strings too, but I think its less common to have a mix of a particular object type and falsey number like `0`.
cc @GAntoine 
Option 1
---------
Don't change the current type definitions.
Users of flow have to write the above code like this instead:
```
const array = [
condition ? a : null,
];
return _.compact<A, A>(array);
```
Option 2
---------
The solution in this PR - its non …

[lodash] _.compact typings

---

definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/test_react-hooks_v3.x.x.js

fix #3745
Other notes:
Flow inexact object type intersections suuuuuuuuuck, you should permaban them from flow-typed.

fix(apollo/react-hooks): use exact object types and object type spread

---

definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/react_v10.x.x.js

- Links to documentation: https://testing-library.com/docs/dom-testing-library/api-queries
Other notes:
Update queries to generics such as `getByTestId` which will remove query from returning `HTMLElement` until brackets are used.
Previous behaviour:
```
const element = getByTestId('test'); // element is HTMLElement
const element: HTMLSelectElement = getByTestId('test'); // errors
```
New behaviour
```
const element = getByTestId('test'); // element is any
const element: HTMLSelectElement = getByTestId('test'); // element is HTMLSelectElement
const element = getByTestId<>('test'); // element is HTMLElement
const element = getByTestId<HTMLSelectElement>('test'); // element is …
```

[@testing-library/react] update GetByBoundAttribute to accept generic

---

definitions/npm/@sentry/browser_v5.x.x/flow_v0.84.x-/browser_v5.x.x.js
definitions/npm/@sentry/browser_v5.x.x/test_browser_v5.x.x.js

With types exported, it is much easier to define correct callbacks
without relying on the existential type.
This also corrects a bug in `beforeBreadcrumb` which should only accept returning `null`, not `void`.
Additionally, `user.id` may be any type, but is, in practice, only going to be a `string` or `number`. The typescript definition also gets this wrong, and [Sentry documentation for this feature](https://docs.sentry.io/enriching-error-data/additional-data/?platform=browser#capturing-the-user) does not specify a type.
* `beforeBreadcrumb` should return null not `void`: https://docs.sentry.io/enriching-error-data/breadcrumbs/?platform=browser#breadcrumb-customization and [typescript definition](https://github.com/getsentry/sentry-javascript/blob/master/package …

[@sentry/browser_5.x.x] Export types and minor corrections

---

definitions/npm/jest_v24.x.x/flow_v0.104.x-/jest_v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.104.x-/test_jest-v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.61.x-v0.103.x/jest_v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.61.x-v0.103.x/test_jest-v24.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.104.x-/jest_v25.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.104.x-/test_jest-v25.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.61.x-v0.103.x/jest_v25.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.61.x-v0.103.x/test_jest-v25.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.104.x-/jest_v26.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.104.x-/test_jest-v26.x.x.js

Since Jest v21 it's possible to call `done` with an Error (implemented in https://github.com/facebook/jest/pull/4016). Before one had to do either `done()` or `done.fail(Error)`.
- Links to documentation: https://jestjs.io/docs/en/asynchronous#callbacks
- Type of contribution: addition & fix
Other notes:
* This is existing since Jest v21 but it was easier to do it only since Jest v24. If others need it they'll be able to change it by following the example.
* I also realized that the libdefs weren't working for some older flow versions, so I changed the directory names accordingly. Because that's from very old flow versions I didn't bother fixing that.
* `done.fail` isn't documented but I noticed it's supported by test cases there, so I decided to leave it. Also I didn't want to bring new …

Jest: add the done(Error) functionality

---

definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/react_v10.x.x.js

This reverts commit 7ad57fc0955eb95b8529b295b7d2b6ae6a488b6d (https://github.com/flow-typed/flow-typed/pull/3837). 
Recommended by the flow-team to revert this PR as although this flow def does not throw any errors, if it were bolted onto the real function it would not be sound because you cannot know ahead of time what T is to be returned so it would error out.
https://flow.org/try/#0MYewdgzgLgBFCm0YF4YB4AqA+AFAQwCcBzASgC4YMUsYBvAKBiZgPigFcCwYByACwCWPANwwA9GJgAzADYgA7jD54IMMCBgCAJvDwx5y2FEGqIfEOxlaYAI3gwIGgbHgECIAqouw8M+XgBPCHoAXyA

Revert "update GetByBoundAttribute to accept generic (#3837)"

---

definitions/npm/@react-navigation/bottom-tabs_v5.x.x/CONTRIBUTING.md
definitions/npm/@react-navigation/bottom-tabs_v5.x.x/flow_v0.104.x-/bottom-tabs_v5.x.x.js
definitions/npm/@react-navigation/bottom-tabs_v5.x.x/test_bottom-tabs.js
definitions/npm/@react-navigation/core_v5.x.x/CONTRIBUTING.md
definitions/npm/@react-navigation/core_v5.x.x/flow_v0.104.x-/core_v5.x.x.js
definitions/npm/@react-navigation/core_v5.x.x/test_core.js
definitions/npm/@react-navigation/drawer_v5.x.x/CONTRIBUTING.md
definitions/npm/@react-navigation/drawer_v5.x.x/flow_v0.104.x-/drawer_v5.x.x.js
definitions/npm/@react-navigation/drawer_v5.x.x/test_drawer.js
definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/CONTRIBUTING.md
definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/flow_v0.104.x-/material-bottom-tabs_v5.x.x.js
definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/test_material-bottom-tabs.js
definitions/npm/@react-navigation/material-top-tabs_v5.x.x/CONTRIBUTING.md
definitions/npm/@react-navigation/material-top-tabs_v5.x.x/flow_v0.104.x-/material-top-tabs_v5.x.x.js
definitions/npm/@react-navigation/material-top-tabs_v5.x.x/test_material-top-tabs.js
definitions/npm/@react-navigation/native_v5.x.x/CONTRIBUTING.md
definitions/npm/@react-navigation/native_v5.x.x/flow_v0.104.x-/native_v5.x.x.js
definitions/npm/@react-navigation/native_v5.x.x/test_native.js
definitions/npm/@react-navigation/stack_v5.x.x/CONTRIBUTING.md
definitions/npm/@react-navigation/stack_v5.x.x/flow_v0.104.x-/stack_v5.x.x.js
definitions/npm/@react-navigation/stack_v5.x.x/test_stack.js

React Nav 5 is a complete rewrite, so I went ahead and completely rewrote the types. A lot more stuff can now be typechecked!
Note that we now have seven different packages users can import from. To make contributing to the libdefs easier I've simplified them into just two sections. This means the libdefs are longer than they need to be sometimes, as Section 1 may have some types not necessarily for a given libdef.

[react-navigation] Libdefs for React Nav 5

---

README.md
cli/src/lib/stubUtils.js

```
flow-typed create-stub ts-package package-not-in-definitely-typed --typescript
```
Will fail catastrophically with `UNCAUGHT ERROR: HTTPError: Response code 404 (Not Found)`

Avoid uncaught error when network fails

---

definitions/npm/@sentry/browser_v5.x.x/flow_v0.90.x-/browser_v5.x.x.js

Unfortunately due to #3825, a few types were referenced in the
@sentry/browser typedef that are undefined. This PR adds them back,
using the TypeScript definition as reference, as well as a few
missing methods.
Have tested this in a real project (to bypass #3825) to ensure
the issue is fixed.
- Links to documentation: [typescript definition](https://github.com/getsentry/sentry-javascript/blob/master/packages/types/src/options.ts#L133)
- Link to GitHub or NPM: https://github.com/getsentry/sentry-javascript/blob/master/packages/types

[@sentry/browser_5.x.x] Add missing types and methods

---

definitions/npm/bluebird_v3.x.x/flow_v0.104.x-/bluebird_v3.x.x.js
definitions/npm/bluebird_v3.x.x/flow_v0.104.x-/test_bluebird_v3.x.x.js

1. Bluebird's `Promise.all` annotation was not inferring the correct type for tuples of promises. Switched to use `$TupleMap` so that the types are correctly inferred whether we use a tuple or an array as the argument. The type annotation is based off of JavaScript's builtin Promise.all annotation: https://github.com/facebook/flow/blob/v0.111.3/lib/core.js#L689
2. Bluebird's Promise.resolve was inferring `empty` as the generic type. Fixed by adding separate annotations for when `resolve` is called without any arguments.
Passes all tests with `quick_run_def_tests.sh`
Links to documentation: http://bluebirdjs.com/docs/api-reference.html
Link to GitHub or NPM: https://www.npmjs.com/package/bluebird

Fixed bluebird's Promise.all and Promise.resolve types

---

definitions/npm/bluebird_v3.x.x/flow_v0.104.x-/test_bluebird_v3.x.x.js

Bluebird's emptyPromise test was previously testing the core Promise type instead of the Bluebird type. This is a fix for @pascalduez's comment on https://github.com/flow-typed/flow-typed/pull/3854
- Links to documentation: http://bluebirdjs.com/docs/api-reference.html
- Link to GitHub or NPM: https://www.npmjs.com/package/bluebird

Minor fix to Bluebird's emptyPromise test

---

definitions/npm/jest_v21.x.x/flow_v0.104.x-/jest_v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.104.x-/test_jest-v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.25.x-v0.38.x/jest_v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.25.x-v0.38.x/test_jest-v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.39.x-v0.103.x/jest_v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.39.x-v0.103.x/test_jest-v21.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.104.x-/jest_v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.104.x-/test_jest-v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/jest_v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/test_jest-v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.39.x-v0.103.x/jest_v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.39.x-v0.103.x/test_jest-v22.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.104.x-/jest_v23.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.104.x-/test_jest-v23.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.39.x-v0.103.x/jest_v23.x.x.js
definitions/npm/jest_v23.x.x/flow_v0.39.x-v0.103.x/test_jest-v23.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.104.x-/jest_v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.104.x-/test_jest-v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.61.x-v0.103.x/jest_v24.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.61.x-v0.103.x/test_jest-v24.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.104.x-/jest_v25.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.104.x-/test_jest-v25.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.61.x-v0.103.x/jest_v25.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.61.x-v0.103.x/test_jest-v25.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.104.x-/jest_v26.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.104.x-/test_jest-v26.x.x.js

- Links to documentation: https://jestjs.io/docs/en/jest-object#jestrequireactualmodulename
- Link to GitHub or NPM: https://github.com/facebook/jest/blob/master/e2e/__tests__/jestRequireActual.test.ts
W.r.t. `requireActual`, here's an example of how to use it with the new generic type argument:
```js
// Assuming you have:
import typeof MyModule from 'MyModule';
// where MyModule is a type like `{}`
// Before
const myModule = requireActual('MyModule');
// Casting myModule to arbitrary types
(myModule: MyModule) // OK, but we're actually not sure
(myModule: 'do not trust me') // Flow says it's ok, but it's not!
// After
const myModule = requireActual<MyModule>('MyModule');
// Casting myModule to arbitrary types
(myModule: MyModule) // OK
(myModule: 'do not …
```

Jest: improve jest.requireActual type

---

cli/src/commands/install.js

Workaround for #3809 
Semver has updated and throws an error with versions of 'v0.x.x'. I'm not sure if this is the best place for this, but it avoids changing the `libDef` definition and the cache.

Fix: Add workaround for semver throwing errors for versions of 'v0.x.x'

---

definitions/npm/ramda_v0.27.x/flow_v0.104.x-/ramda_v0.27.x.js
definitions/npm/ramda_v0.27.x/flow_v0.76.x-v0.103.x/ramda_v0.27.x.js

- Links to documentation: https://ramdajs.com/docs/#andThen
- Link to GitHub or NPM: https://github.com/ramda/ramda/issues/2978
Other notes:
- andThen: https://github.com/ramda/ramda/blob/v0.27.0/source/andThen.js
- then: https://github.com/ramda/ramda/blob/v0.26.1/source/then.js

[ramda_v0.27.x] Rename then in favor of thenAnd

---

definitions/npm/@sentry/browser_v5.x.x/flow_v0.90.x-/browser_v5.x.x.js

Per the change below, Sentry has renamed their props to allowUrls and denyUrls to use inclusive language. Update flow typedef to respect that:
- Links to documentation: https://docs.sentry.io/platforms/javascript/
- Link to GitHub or NPM: https://github.com/getsentry/sentry-javascript/commit/1204302906bbe74edc8a18f8ded047b3041059d7
Other notes:
Thanks for the ongoing work :)

Update @sentry/browser flow types for 5.18

---

definitions/npm/@sentry/browser_v5.x.x/flow_v0.90.x-/browser_v5.x.x.js

See discussion in #3869. Although the older props are deprecated, they will still work so should be re-added.
Links to documentation: https://docs.sentry.io/platforms/javascript/
Link to GitHub or NPM: https://github.com/getsentry/sentry-javascript/commit/1204302906bbe74edc8a18f8ded047b3041059d7

@sentry/browser: Re-add deprecated props still usable in 5.x.x

---

definitions/npm/react-redux_v7.x.x/flow_v0.104.x-/react-redux_v7.x.x.js
definitions/npm/react-redux_v7.x.x/flow_v0.104.x-/test_batch.js
definitions/npm/react-redux_v7.x.x/flow_v0.89.x-v0.103.x/react-redux_v7.x.x.js
definitions/npm/react-redux_v7.x.x/flow_v0.89.x-v0.103.x/test_batch.js

Looks like we are just missing the `batch` function.
- Links to documentation: https://react-redux.js.org/api/batch
- Link to GitHub or NPM: https://github.com/reduxjs/react-redux/blob/master/src/utils/batch.js
Other notes: Thanks for all the hard work y'all do!

[react-redux] Add batch function

---

cli/package.json
cli/src/commands/install.js
cli/src/lib/__tests__/semver-test.js
cli/src/lib/semver.js
cli/yarn.lock

Better fix for #3809 
- added fix in `src/lib/semver.js`
- upgraded semver version in package.json/yarn.lock: when installing `flow-typed` with npm/yarn, the newer version of semver is installed
- added tests for semver issue
- removed prior poor fix in `src/commands/install.js` in favor of a fix in `src/lib/semver.js`

A better fix for the semver issues

---

definitions/npm/idb_v5.x.x/flow_v0.83.x-/idb_v5.x.x.js
definitions/npm/idb_v5.x.x/test_idb-v5.x.x.js
definitions/npm/idb_v5.x.x/test_idb_async-v5.x.x.js

- Links to documentation: https://github.com/jakearchibald/idb
- Link to GitHub or NPM: https://github.com/jakearchibald/idb
Other notes:
~~This PR contains the commits from #3855 so that my use of `$FlowExpectedError` works across all flow versions supported by this libdef.~~ <= Now that #3855 has been merged I rebased on top of latest master and this isn't in this PR anymore.
I started by copying the libdef for idb_v2 but then I heavily rewrote the libdef and also added a lot of new tests. (so there are 2 commits fot these 2 steps)

Add libdefs for idb v5

---

definitions/npm/classnames_v2.x.x/flow_v0.104.x-/classnames_v2.x.x.js
definitions/npm/classnames_v2.x.x/test_classnames_v2.x.x.js

- Links to documentation: https://github.com/JedWatson/classnames
- TypeScript types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/classnames/types.d.ts
Other notes:
- It accepts a nested array of the same types
- It accepts numbers and `true` as well
- It should accept `$ReadOnlyArray`s instead of just `Array`s, since the
values are not modified.
I had to remove the `$FlowExpectError`s now because basically everything
is accepted.

Improve `classnames` types

---

definitions/npm/react-select_v1.x.x/flow_v0.104.x-/react-select_v1.x.x.js
definitions/npm/react-select_v1.x.x/flow_v0.53.x-v0.103.x/react-select_v1.x.x.js

I added the `cache` prop to `react-select` in another PR https://github.com/flow-typed/flow-typed/pull/3873 . However, the type was wrong. According to the documents, `cache` can be any object, or `false` to disable it.
Sorry for the previous mistake.
- Links to documentation: https://github.com/JedWatson/react-select/blob/v1.3.0/README.md?rgh-link-date=2020-08-04T04%3A11%3A08Z#L147
- Link to GitHub or NPM: https://github.com/JedWatson/react-select/blob/v1.3.0/src/Async.js?rgh-link-date=2020-08-04T04%3A11%3A08Z#L9

Fix the type of 'cache' prop for 'react-select_v1.x.x'

---

definitions/npm/yargs_v15.x.x/flow_v0.118.x-/yargs_v15.x.x.js

- Links to documentation: https://yargs.js.org/docs/#api-reference-showhelpconsolelevel-printcallback

[yargs] Add showHelp(printCallback) overload

---

definitions/npm/yargs_v15.x.x/flow_v0.118.x-/yargs_v15.x.x.js

Adds a missing overload of [`demandCommand`](https://yargs.js.org/docs/#api-reference-demandcommandmin1-max-minmsg-maxmsg) to `yargs`.
- Links to documentation: https://yargs.js.org/docs/#api-reference-demandcommandmin1-max-minmsg-maxmsg

[yargs_v15.x.x] Add demandCommand 0-arg overload

---

definitions/npm/react-splitter-layout_v4.x.x/flow_v0.104.x-/react-splitter-layout_v4.x.x.js
definitions/npm/react-splitter-layout_v4.x.x/flow_v0.53.x-v0.103.x/react-splitter-layout_v4.x.x.js
definitions/npm/react-splitter-layout_v4.x.x/test_splitter-layout.js

- Links to documentation: https://github.com/zesik/react-splitter-layout
- Link to GitHub or NPM:  https://github.com/zesik/react-splitter-layout
Other notes:
I copied the libdef for the version 3 and just added the new import, which is empty because this is a CSS file.

Provide a libdef for react-splitter-layout v4

---

definitions/npm/escape-string-regexp_v4.x.x/flow_v0.104.x-/escape-string-regexp_v4.x.x.js
definitions/npm/escape-string-regexp_v4.x.x/flow_v0.28.x-v0.103.x/escape-string-regexp_v4.x.x.js
definitions/npm/escape-string-regexp_v4.x.x/test_escape-string-regexp_v4.x.x.js

- Links to documentation: https://github.com/sindresorhus/escape-string-regexp#readme
- Link to GitHub or NPM: https://github.com/sindresorhus/escape-string-regexp
Other notes:
Just copied over the libdef for v2.

Add the libdef for the newer version of escape-string-regexp

---

definitions/npm/react-router-dom_v5.x.x/flow_v0.104.x-/react-router-dom_v5.x.x.js
definitions/npm/react-router-native_v4.x.x/flow_v0.104.x-/react-router-native_v4.x.x.js
definitions/npm/react-router_v5.x.x/flow_v0.104.x-/react-router_v5.x.x.js

- Links to documentation: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/location.md
I saw that in a previous PR these fields were removed; however, as visible from the documentation, these fields can appear in the react-router location and now whenever I try to access them, Flow shows an error about the missing properties. Would you consider adding them back?

Add state and key back to the Location type of react-router

---

definitions/npm/supertest_v4.x.x/flow_v0.94.x-/supertest_v4.x.x.js
definitions/npm/supertest_v4.x.x/test_basic-functionality.js
definitions/npm/supertest_v5.x.x/flow_v0.94.x-/supertest_v5.x.x.js
definitions/npm/supertest_v5.x.x/test_basic-functionality.js

- Links to documentation: https://github.com/visionmedia/supertest and https://visionmedia.github.io/superagent/#retrying-requests
- Link to GitHub or NPM: https://github.com/visionmedia/supertest and https://github.com/visionmedia/superagent
- Type of contribution: new definition and fix
Other notes:
There's no API change between v4 and v5, so I first fixed the issue in v4, and then copied everything over to a new v5 libdef.

Include libdef for supertest v5 and fix the type for the retry function

---

definitions/npm/yargs_v16.x.x/flow_v0.104.x-/yargs_v16.x.x.js
definitions/npm/yargs_v16.x.x/flow_v0.98.x-v0.103.x/yargs_v16.x.x.js
definitions/npm/yargs_v16.x.x/test_yargs.js

- Links to documentation: https://github.com/yargs/yargs
- Link to GitHub or NPM:  https://github.com/yargs/yargs
- Type of contribution: new definition and fix
Other notes:
I mostly copied over the libdef from the v15 without checking more. From yargs' documentation nothing more happened from the API side. Only a function was removed from the API but it wasn't in the libdef because not in the official API.
I fixed the test and realized that we had some other tests with `$ExpectError` instad of `$FlowExpectedError` so I changed them in a subsequent commit. I didn't run the tests for that ones though.

Add definitions for Yargs v16

---

definitions/npm/webpack_v4.x.x/flow_v0.104.x-/test_webpack_v4.x.x.js
definitions/npm/webpack_v4.x.x/flow_v0.104.x-/webpack_v4.x.x.js

Adds missing infrastructure-level logging options.
- Links to documentation: https://v4.webpack.js.org/configuration/other-options/#infrastructurelogging
- Link to GitHub or NPM: https://github.com/webpack/webpack

[webpack_v4.x.x] Add infrastructure logging options

---

definitions/npm/sinon_v7.x.x/flow_v0.80.x-/sinon_v7.x.x.js
definitions/npm/sinon_v7.x.x/test_sinon_v7.x.x.js

- Links to documentation: See calledOnceWithExactly at [sinon docs](https://sinonjs.org/releases/latest/spies/)
- Link to GitHub or NPM: [Parcel](https://github.com/parcel-bundler/parcel)
- Type of contribution: new definition | __addition__ | fix | refactor
Other notes:  added test in `test_sinon_v7.x.x.js`
Need this change in order to use definition within Parcel

Adding calledOnceWithExactly to definition

---

definitions/npm/sinon_v7.x.x/flow_v0.80.x-/sinon_v7.x.x.js
definitions/npm/sinon_v7.x.x/test_sinon_v7.x.x.js

- Links to documentation: [sinon docs](https://sinonjs.org/releases/latest/spy-call/)
- Type of contribution: new definition | addition | **fix** | refactor
Other notes: LastArg should actually be mixed since it's based on the object it's called on 😥  Fix for parcel

Add last arg to spy call -[FIX]

---

definitions/npm/@react-navigation/bottom-tabs_v5.x.x/test_bottom-tabs.js
definitions/npm/@react-navigation/core_v3.x.x/test_core.js
definitions/npm/@react-navigation/core_v5.x.x/test_core.js
definitions/npm/@react-navigation/drawer_v5.x.x/test_drawer.js
definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/test_material-bottom-tabs.js
definitions/npm/@react-navigation/material-top-tabs_v5.x.x/test_material-top-tabs.js
definitions/npm/@react-navigation/stack_v5.x.x/test_stack.js

Fixing the warnings in tests that started popping of as of Flow 0.132

[react-navigation] Update all suppressions to use error codes

---

definitions/npm/@reduxjs/toolkit_v1.x.x/flow_v0.104.x-/test_toolkit_v1.x.x.js
definitions/npm/@reduxjs/toolkit_v1.x.x/flow_v0.104.x-/toolkit_v1.x.x.js

- Links to documentation: https://redux-toolkit.js.org/api/createReducer https://redux-toolkit.js.org/api/createAction
- Link to GitHub or NPM: https://github.com/reduxjs/redux-toolkit
Other notes: Only typed createAction and createReducer as that are they only ones we have use for, doing the rest is quite a pain. Based of the typescript defs. Impossible to get 100 % right as Immer (which Toolkit uses for state/reducers) cannot be typed in Flow since Flow does not support making ReadOnly-obj writeable - which is how Immer solves immutability (it acts as mutable). This is at least enough to get 100 % coverage in actions.js and reducers.js files. Note that, just like the TypeScript defs, types only cover the whole reducer if the builder callback is …

Add type and test for reduxjs toolkit

---

definitions/npm/luxon_v0.2.x/flow_v0.104.x-/test_luxon.js
definitions/npm/luxon_v0.4.x/flow_v0.104.x-/test_luxon.js
definitions/npm/luxon_v1.9.x/flow_v0.104.x-/luxon_v1.9.x.js
definitions/npm/luxon_v1.9.x/flow_v0.104.x-/test_luxon.js

toRelative: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toRelative
toRelativeCalendar: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toRelativeCalendar
- Link to GitHub or NPM: https://github.com/moment/luxon
Other notes:
The methods I'm adding were not added to the library until [v1.9.0](https://github.com/moment/luxon/blob/master/CHANGELOG.md#190) . I wasn't sure whether there's a remedy for that.

[luxon_v1.9.x] add toRelative and toRelativeCalendar

---

definitions/npm/@ungap/promise-all-settled_v1.1.x/flow_v0.104.x-/promise-all-settled_v1.1.x.js
definitions/npm/@ungap/promise-all-settled_v1.1.x/flow_v0.104.x-/test_promise-all-settled_v1.1.x.js

- Links to documentation: https://github.com/ungap/promise-all-settled
- Link to GitHub or NPM:  https://github.com/ungap/promise-all-settled
Other notes:
Couldn't make `typeof Promise.allSettled` (added in Flow > 0.120) with `call, bind`... So copy/pasta.

[@ungap/promise-all-settled_v1.1.x] Add definitions

---

CONTRIBUTING.md

We want to explicitly use either exact or inexact objects for all new definitions. 
Since the inexact object syntax was added in Flow 0.83.x, it does not make sense to keep scoping new libdef to 0.25.x?
Anyway, we only test the last 15 versions...

Docs: update new libdefs minimum Flow version

---

definitions/npm/react-modal_v3.12.x/flow_v0.104.x-/react-modal_v3.12.x.js

It has a default value in defaultProps.
https://github.com/reactjs/react-modal/blob/master/src/components/Modal.js#L89
- https://github.com/flow-typed/flow-typed/pull/3957

Make the new preventScroll prop of react-modal_v3.12.x optional

---

cli/src/commands/__tests__/install-test.js
cli/src/lib/__mocks__/node.js
cli/src/lib/cacheRepoUtils.js
cli/src/lib/libDefs.js
cli/src/lib/node.js
cli/src/lib/npm/npmLibDefs.js
cli/src/lib/npm/npmProjectUtils.js
cli/src/lib/stubUtils.js

The way `fs.readFile` was being used looked like a code smell, and sure enough, the way it was being mocked would cause surprise errors for anyone who adds idiomatic `fs-extra` calls in new or updated tests.  Pass encoding (`'utf8'`, the default) to get `readFile` to resolve to a string instead of a buffer, and use `readJson` where applicable.  Update fs mocks to behave a bit more like `fs-extra` in this regard (though I'm not sure it would be possible to support all options, but we can at least support encoding string as second argument).

refactor: clean up fs.readFile usage

---

definitions/npm/luxon_v1.9.x/flow_v0.104.x-/luxon_v1.9.x.js

adding export to subtypes to HourCycle, NumericLength, MonthLength, EraLength and UnitLength as well

Add export to IntlDateTimeFormatOptions type

---

definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v1.x.x/flow_v0.30.x-v0.103.x/react-json-schema-form-builder_v1.x.x.js
definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v1.x.x/flow_v0.92.x-/react-json-schema-form-builder_v1.x.x.js
definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v1.x.x/test_react-json-schema-form-builder_v1.x.x.js

- Links to documentation: https://react-json-schema-form-builder.readthedocs.io/en/main/Home/
- Link to GitHub or NPM: https://github.com/ginkgobioworks/react-json-schema-form-builder
Other notes:
First flow type definition contribution for this scoped React component. Mainly would like for users that install the libdef to have flow typed access to some of the props that create the element.

Feature/@ginkgo bioworks/react json schema form builder

---

definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v1.x.x/flow_v0.92.x-/react-json-schema-form-builder_v1.x.x.js
definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v1.x.x/test_react-json-schema-form-builder_v1.x.x.js

Fix several issues with the flow-typed defintiions for react-json-schema-form-builder v1.x.x
- Remove `CardProps`, `SectionProps`, and `ElementProps`, which were vestigal and not currently being used.
- Remove exactness in object definitions with indexer properties, as they they are incompatible.
- Export a props type for `cardBody` and `modalBody` components so that these components can be defined externally.
- Use `React$ComponentType`, as `React$AbstractComponent` was incorrect.
- Links to documentation: https://react-json-schema-form-builder.readthedocs.io/en/main/
- Link to GitHub or NPM: https://github.com/ginkgobioworks/react-json-schema-form-builder
- Type of contribution:  fix 
Other notes:

[@ginkgo-bioworks/react-json-schema-form-builder_v1.x.x] Several buxfixes

---

definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v1.x.x/test_react-json-schema-form-builder_v1.x.x.js

Links to documentation: https://react-json-schema-form-builder.readthedocs.io/en/main/
Link to GitHub or NPM: https://github.com/ginkgobioworks/react-json-schema-form-builder
Other notes: My apologies -- I apparently neglected to add the `it` calls for the `propsWithMods` case.

Bugfix/@ginkgo bioworks/react json schema form builder

---

definitions/npm/luxon_v1.25.x/flow_v0.104.x-/luxon_v1.25.x.js
definitions/npm/luxon_v1.25.x/flow_v0.104.x-/test_luxon.js

- Links to documentation: https://moment.github.io/luxon/index.html
- Link to GitHub or NPM: https://github.com/moment/luxon
Other notes:
I copied the definitions from luxon_v1.9.x and then compared them to the
typescript definitions for luxon_v.25.x. Whereever they differed, I
looked up the actual definitions in the documentation. The typescript
definitions were mostly correct, but I did find a few instances where
they weren't.
I copied the tests from luxon_v1.9.x and made small modifications to
them so that they passed with the new definitions.

Add definitions for luxon_v1.25.x

---

definitions/npm/match-sorter_v5.x.x/flow_v0.104.x-/match-sorter_v5.x.x.js
definitions/npm/match-sorter_v5.x.x/test_match-sorter-v5.x.x.js

- Links to documentation: https://github.com/kentcdodds/match-sorter#usage
- Link to GitHub or NPM: https://github.com/kentcdodds/match-sorter
Other notes:
I based this on match-sorter_v2.3.x and then updated the definitions for the newer version. In particular, the tests are nearly identical.

Add flow-typed definitions for match-sorter_v5.x.x

---

definitions/npm/chance_v1.x.x/flow_v0.104.x-/chance_v1.x.x.js
definitions/npm/chance_v1.x.x/test_chance-v1.x.x.js

- Links to documentation:  https://chancejs.com/
- minute: https://github.com/chancejs/chancejs/blob/93b384673074fe959c9691d02d2a0fec8cd394fa/chance.js#L2128
- syllable: https://github.com/chancejs/chancejs/blob/93b384673074fe959c9691d02d2a0fec8cd394fa/chance.js#L821
- hour: https://github.com/chancejs/chancejs/blob/93b384673074fe959c9691d02d2a0fec8cd394fa/chance.js#L2110-L2113
Other notes:

npm/chance: Add options for syllable, hour, minute

---

definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/react_v10.x.x.js

Because of flow 0.143.0, lib defs now better throw errors. These are the errors caught from react testing library for types that don't exist.
- Links to documentation: https://github.com/testing-library/react-testing-library
Other notes:

[testing-library/react] fix missing types error

---

definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-/react_v11.x.x.js

Because of flow 0.143.0, lib defs now better throw errors. These are the errors caught from react testing library for types that don't exist.
Links to documentation: https://github.com/testing-library/react-testing-library
Link to GitHub or NPM: https://github.com/testing-library/react-testing-library
Other notes:

[testing-library/react] Fix v11 of the library

---

definitions/npm/@react-navigation/bottom-tabs_v5.x.x/flow_v0.104.x-/bottom-tabs_v5.x.x.js
definitions/npm/@react-navigation/core_v5.x.x/flow_v0.104.x-/core_v5.x.x.js
definitions/npm/@react-navigation/devtools_v5.x.x/flow_v0.104.x-/devtools_v5.x.x.js
definitions/npm/@react-navigation/drawer_v5.x.x/flow_v0.104.x-/drawer_v5.x.x.js
definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/flow_v0.104.x-/material-bottom-tabs_v5.x.x.js
definitions/npm/@react-navigation/material-top-tabs_v5.x.x/flow_v0.104.x-/material-top-tabs_v5.x.x.js
definitions/npm/@react-navigation/native_v5.x.x/flow_v0.104.x-/native_v5.x.x.js
definitions/npm/@react-navigation/stack_v5.x.x/flow_v0.104.x-/stack_v5.x.x.js

Putting this PR up to get feedback. Is this a wise change to make? `$Shape` seems to have all sorts of issues, and it appears that the hack using `$Rest` is a good workaround.

[react-navigation] Replace $Shape with $Rest<T, {...}>

---

definitions/npm/webpack_v4.x.x/flow_v0.104.x-/webpack_v4.x.x.js

After updating to 0.143.0 new errors in lib defs are being highlighted. We should not be importing outside of a module declaration.
- Links to documentation: https://github.com/webpack/webpack
- Link to GitHub or NPM: https://github.com/webpack/webpack
Other notes: `OutgoingMessage` doesn't exist in `http` module. Should probably be added in flow but that's probably a different problem to solve. This at least doesn't break the type and keeps it as it was before which would have exposed `any`

[webpack] Fix import errors

---

definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/react-hooks_v3.x.x.js

- Links to documentation: https://www.apollographql.com/docs/react/api/react/hooks/#function-signature-1
- Link to GitHub or NPM: https://github.com/apollographql/apollo-client

Fix the return type for useLazyQuery

---

definitions/npm/styled-components_v5.x.x/flow_v0.104.x-/styled-components_v5.x.x.js
definitions/npm/styled-components_v5.x.x/flow_v0.104.x-/test_styled-components_v5.x.x.js

As described in https://github.com/flow-typed/flow-typed/issues/3880 it looks like the code which got added by @kyleknighted for the styled-components v4 interface (https://github.com/flow-typed/flow-typed/pull/3779) is not part of the v5 interface definition.
This PR reimplements the code for the v5 interface definition and adds a test for the related use case.
I also tried to add a test which includes `// $FlowExpectedError` but didn't find a suitable one.
There are still some other tests which fail when running `flow-typed run-tests styled-components_v5`, but they are not related to this change. I made sure the test is failing with the previous styled-component v5 interface definition.
Fixes: https://github.com/flow-typed/flow-typed/issues/3880

Allow function within styled(..) for styled-components v5

---

definitions/npm/yargs_v15.x.x/flow_v0.118.x-/yargs_v15.x.x.js

The `yargs_v15.x.x.js` typedef had a typo for the `MiddleWareCallback`. Changed the `w` from lowercase to upperwase `W`.
Test plan:
Run `./build_and_test_cli.sh`
```
Test Suites: 9 passed, 9 total
Tests:       112 passed, 112 total
Snapshots:   0 total
Time:        8.836s
Ran all test suites.
$ eslint .
Done in 14.49s.
Done in 31.68s.
All libdefs are named and structured correctly. (Found 1787)
```
- Link to GitHub or NPM: https://github.com/yargs/yargs/blob/7ffb5e8ae4f4f94f94ffd10a3aa8b410b2ed2fe4/lib/middleware.ts
Other notes:
While the source project uses `MiddlewareCallback`, I stuck to the notion of `yargs_v16.x.x.js`, which was using `MiddleWareCallback` throughout.

Fix lowercase MiddlewareCallback to MiddleWareCallback

---

definitions/npm/cypress_v6.x.x/flow_v0.25.x-/cypress_v6.x.x.js
definitions/npm/cypress_v6.x.x/test_cypress_v6.x.x.js

- Links to documentation: https://docs.cypress.io/api/commands/request.html
- Link to GitHub or NPM: /
Other notes: `cy.request` does not actually return a Promise (though it is `then`able). Such as stated in the [examples section](https://docs.cypress.io/api/commands/request.html#Examples), you can chain the result with other Cypress commands
```
cy.request('/admin').its('body');
cy.request('https://jsonplaceholder.cypress.io/comments').as('comments')
```
So it makes more sense for `cy.request` to return `Cypress$Global`, as many other commands. 
Unfortunately, by returning `Cypress$Global` we lose the typing information of what the command actually yields (`Cypress$RequestResponse`). In the future, maybe  `Cypress$Global` should be parametrized ?
@Brianzchen …

Adapted cy.request to return Cypress$Global rather than a promise

---

.github/workflows/main.yml
cli/src/lib/git.js
cli/src/lib/libDefs.js

Fixes #3999. It turns out after moving to github actions, it wasn't able to fetch diffs because the github action `actions/checkout@v2` does a shallow clone of a single commit unless you specify the fetch depth.
I was testing for reference on https://github.com/flow-typed/flow-typed/pull/4009 but that PR starting getting pretty large from fixing `@testing-library/react` so breaking it up to just fix the tests here
Other notes:
Update some of the logging because it took me a bit of trial and error to find out what was happening, it turned out when it fetched git diffs it was silently failing and returning `[]` so these will help people track down issues easier in the future.
```
{
stderr: "fatal: …
```

[cli] Fix tests not running in CI

---

definitions/npm/morgan_v1.x.x/flow_v0.104.x-/morgan_v1.x.x.js

Newer versions of flow-bin don't allow using import outside declare module blocks.
This PR fixes imports for morgan lib type definitions.

fix imports for morgan lib def

---

definitions/npm/next_v2.x.x/flow_v0.104.x-/next_v2.x.x.js
definitions/npm/next_v2.x.x/flow_v0.104.x-/test_next_v2.x.x.js
definitions/npm/next_v2.x.x/flow_v0.53.x-v0.103.x/next_v2.x.x.js
definitions/npm/next_v4.x.x/flow_v0.104.x-/next_v4.x.x.js
definitions/npm/next_v4.x.x/flow_v0.104.x-/test_next_v4.x.x.js
definitions/npm/next_v4.x.x/flow_v0.53.x-v0.103.x/next_v4.x.x.js
definitions/npm/next_v7.x.x/flow_v0.104.x-/next_v7.x.x.js
definitions/npm/next_v7.x.x/flow_v0.104.x-/test_next_v7.x.x.js
definitions/npm/next_v7.x.x/flow_v0.53.x-v0.92.x/next_v7.x.x.js
definitions/npm/next_v7.x.x/flow_v0.93.x-v0.103.x/next_v7.x.x.js
definitions/npm/next_v9.x.x/flow_v0.104.x-/next_v9.x.x.js
definitions/npm/next_v9.x.x/flow_v0.104.x-/test_next_v9.x.x.js

`useRouter` is missing from next/router definition.
https://github.com/vercel/next.js/blob/canary/docs/api-reference/next/router.md#userouter

[next_v9.x.x] Add useRouter definition

---

definitions/npm/formik_v0.11.x/flow_v0.104.x-/test_formik.js
definitions/npm/formik_v0.9.x/test_formik.js
definitions/npm/formik_v2.x.x/flow_v0.104.x-/formik_v2.x.x.js
definitions/npm/formik_v2.x.x/flow_v0.104.x-/test_formik.js
definitions/npm/formik_v2.x.x/flow_v0.69.0-v0.103.x/formik_v2.x.x.js
definitions/npm/formik_v2.x.x/flow_v0.69.0-v0.103.x/test_formik.js

Fix type definition of innerRef.
According to flow types for React, `React$Ref` type is incompatible with `FormikProps <Values>`.
issue with links #4027

Update formik_v2.x.x.js [Fix innerRef type definition in FormikConfig]

---

PULL_REQUEST_TEMPLATE.md
definitions/npm/jest-useragent-mock_v0.1.x/flow_v0.83.x-/jest-useragent-mock_v0.1.x.js
definitions/npm/jest-useragent-mock_v0.1.x/flow_v0.83.x-/test_jest-useragent-mock_v0.1.x.js

- Links to documentation: https://github.com/ariesjia/jest-useragent-mock/blob/master/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/jest-useragent-mock
Other notes: I also added an extra space to `- Links to documentation: ` line because there's always a space after `- Link to GitHub or NPM: ` in the PR template and it's always kind of annoyed me, hope this is fine.

[jest-useragent-mock] Add def

---

definitions/npm/elegant-spinner_v1.x.x/flow_v0.83.x-/elegant-spinner_v1.x.x.js
definitions/npm/elegant-spinner_v1.x.x/flow_v0.83.x-/test_elegant-spinner_v1.x.x.js
definitions/npm/elegant-spinner_v2.x.x/flow_v0.83.x-/elegant-spinner_v2.x.x.js
definitions/npm/elegant-spinner_v2.x.x/flow_v0.83.x-/test_elegant-spinner_v2.x.x.js

Adding both v1 and v2 of `elegant-spinner` since they're quite small in their defs
V1 has no type TS defs so it's based on the source code at the time of the tag: https://github.com/sindresorhus/elegant-spinner/blob/669a9813b4ee7d459b982dd623e72672d9f4f114/index.js though they actually both have the same definition
- Links to documentation: https://github.com/sindresorhus/elegant-spinner/blob/main/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/elegant-spinner
Other notes:

[elegant-spinner] Add v1/v2 defs

---

definitions/npm/formik_v2.x.x/flow_v0.104.x-/formik_v2.x.x.js
definitions/npm/formik_v2.x.x/flow_v0.104.x-/test_formik.js
definitions/npm/formik_v2.x.x/flow_v0.69.0-v0.103.x/formik_v2.x.x.js
definitions/npm/formik_v2.x.x/flow_v0.69.0-v0.103.x/test_formik.js

Hi, some typing were missing in Formik.
- `onSubmit` return `void | Promise<any>`
- `useField` return an array of 3 objects including `FieldHelperProps`.
Links to documentation: 
- https://formik.org/docs/api/useField#usefieldvalue--anyname-string--fieldhookconfigvalue-fieldinputpropsvalue-fieldmetapropsvalue-fieldhelperprops
- https://formik.org/docs/api/formik#onsubmit-values-values-formikbag-formikbag--void--promiseany

formik_v2.X.X missing type

---

README.md

Someone raised in this [issue](https://github.com/flow-typed/flow-typed/issues/3982) asking if this project is abandoned. It's not but I found this fancy dashboard from Snyk that also provides a package health badge which is pretty cool so users can see at a glimpse that this is a maintained project.
- Type of contribution: N/A
Other notes:
Comes from here: https://snyk.io/advisor/npm-package/flow-typed

[README] Add package health badge

---

definitions/npm/react-query_v3.x.x/flow_v0.104.x-/react-query_v3.x.x.js
definitions/npm/react-query_v3.x.x/flow_v0.104.x-/test_react-query.js

- Links to documentation: react-query.tanstack.com
- Link to GitHub or NPM: https://github.com/tannerlinsley/react-query
Other notes:
This fix a few issues.
- Infer data type from query function instead of reverse. See https://github.com/tannerlinsley/react-query/pull/1470
- Default generics to `mixed` like TypeScript does with `unknown`
- Use `$ReadOnlyArray` for query keys. See https://github.com/tannerlinsley/react-query/pull/1854
- Remove impossible null states (`void | T` instead of `?T`)
- Attempt to fix infinite query types
- Export all types

react-query_v3.x.x updates

---

definitions/npm/debounce_v1.x.x/flow_v0.83.x-/debounce_v1.x.x.js
definitions/npm/debounce_v1.x.x/flow_v0.83.x-/test_debounce_v1.x.x.js

- Links to documentation: https://github.com/component/debounce#readme
- Link to GitHub or NPM: https://github.com/component/debounce#readme
Other notes:
Initial commit incorrectly called this function cancel. It's clear in their docs and code linked above

Update debounce_v1.x.x to fix clear function

---

definitions/npm/jest_v26.x.x/flow_v0.134.x-/jest_v26.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.134.x-/test_jest-v26.x.x.js

See: https://jestjs.io/docs/jest-object#jestcreatemockfrommodulemodulename

Jest v26: add missing `createMockFromModule`

---

definitions/npm/koa-json-body_v5.x.x/flow_v0.53.x-/koa-json-body_v5.x.x.js
definitions/npm/koa-json-body_v5.x.x/test_koa-json-body_v5.js
definitions/npm/koa-send_v4.x.x/flow_v0.104.x-/koa-send_v4.x.x.js
definitions/npm/koa-send_v4.x.x/flow_v0.104.x-/test_koa-send_v4.x.x.js
definitions/npm/koa-send_v4.x.x/flow_v0.56.x-v0.103.x/koa-send_v4.x.x.js
definitions/npm/koa-send_v4.x.x/flow_v0.56.x-v0.103.x/test_koa-send_v4.x.x.js
definitions/npm/koa-static_v4.x.x/flow_v0.104.x-/koa-static_v4.x.x.js
definitions/npm/koa-static_v4.x.x/flow_v0.104.x-/test_koa-static_v4.x.x.js
definitions/npm/koa-static_v4.x.x/flow_v0.56.x-v0.103.x/koa-static_v4.x.x.js
definitions/npm/koa-static_v4.x.x/flow_v0.56.x-v0.103.x/test_koa-static_v4.x.x.js

Code written in node generally uses `require()` syntax instead of `import`. But some of the koa libraries were written with `declare export default` which isn't compatible with `require()` instead of `declare modules.export`.
Other notes:

[koa-] update supporting libs to module.exports

---

definitions/npm/@apollo/react-common_v3.x.x/flow_v0.104.x-/react-common_v3.x.x.js
definitions/npm/@apollo/react-components_v3.x.x/flow_v0.104.x-/react-components_v3.x.x.js
definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js

This is for Apollo client v3.  I'm still not using/don't have defs for v4.
Note: changes to `@apollo/react-hoc` are missing from this...hopefully not many people are using `@apollo/react-hoc` at this point, HoCs are gross
Anyone using `eslint-plugin-flow` will need a lot of these types to satisfy missing function argument warnings, etc.
I also fixed a few other issues I was having.
I know these are working on Flow 0.131.0, we'll see about newer versions...

Export a bunch of types from @apollo/react-{common,components,hooks}, fix a few other issues

---

definitions/npm/react-media_v1.x.x/flow_v0.104.x-/react-media_v1.x.x.js
definitions/npm/react-media_v1.x.x/flow_v0.104.x-/test_react-media_v1.x.x.js

Update react-media with new definitions that previously made the library unusable with flow.
- Links to documentation: https://github.com/ReactTraining/react-media
- Link to GitHub or NPM: https://github.com/ReactTraining/react-media
Other notes:
Added
- `queries` prop
- ability to use children render func arg as an object instead of just a boolean
- type the `onChange` function

[react-media] Update props

---

.github/workflows/main.yml

Node 10 being out of the game, just use the two LTS (maintenance and current). 
See https://nodejs.org/en/about/releases

Update CI node versions

---

definitions/npm/jest_v26.x.x/flow_v0.104.x-v0.133.x/jest_v26.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.104.x-v0.133.x/test_jest-v26.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.134.x-/jest_v26.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.134.x-/test_jest-v26.x.x.js

- Links to documentation: https://github.com/testing-library/jest-dom#jest-dom
Other notes:
Adding typedefs for three new functions in `@testing-library/jest-dom`: `toBeEmptyDOMElement()`,  `toBePartiallyChecked()`,  `toHaveDescription(text: string | RegExp)`

feat(jest): update jest-dom custom matcher typedefs for jest v26

---

definitions/npm/jest_v27.x.x/flow_v0.104.x-v0.133.x/jest_v27.x.x.js
definitions/npm/jest_v27.x.x/flow_v0.104.x-v0.133.x/test_jest-v27.x.x.js
definitions/npm/jest_v27.x.x/flow_v0.134.x-/jest_v27.x.x.js
definitions/npm/jest_v27.x.x/flow_v0.134.x-/test_jest-v27.x.x.js

- Links to documentation: https://jestjs.io/blog/2021/05/25/jest-27#miscellaneous-breaking-changes

[jest_27.x.x] Remove deprecated runTimersToTime method

---

definitions/npm/ramda_v0.27.x/flow_v0.104.x-/ramda_v0.27.x.js

- Links to documentation: https://ramdajs.com/docs
Other notes:
A few of the ramda definitions seem to use Generics that aren't defined. I' m not sure why the available tests don't fail, I've got an error as soon as I installed the definition.

Fix non existing ramda generics

---

CONTRIBUTING.md
definitions/npm/next_v10.x.x/flow_v0.104.x-/next_v10.x.x.js
definitions/npm/next_v10.x.x/flow_v0.104.x-/test_next_v10.x.x.js

Derived from the previous version 9 + updated `Router` type.
- Links to documentation: https://nextjs.org/docs/api-reference/next/router#router-object
- Link to GitHub or NPM: https://www.npmjs.com/package/next
- Type of contribution: new definition | addition

Add support for Next.js version 10

---

definitions/npm/next_v10.x.x/flow_v0.104.x-/next_v10.x.x.js
definitions/npm/next_v10.x.x/flow_v0.104.x-/test_next_v10.x.x.js

I incorrectly removed this property in a9cb5131e41a177e3b3c07ae634afcf5690b0716 because it was not documented (see: https://nextjs.org/docs/api-reference/next/router#router-object). However, I can confirm it actually exists in Next.js version 10.
- Links to documentation: https://nextjs.org/docs/api-reference/next/router#router-object
- Link to GitHub or NPM: https://www.npmjs.com/package/next

Next.js: add missing `Router.route`

---

definitions/npm/jest_v26.x.x/flow_v0.134.x-/jest_v26.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.134.x-/test_jest-v26.x.x.js
definitions/npm/jest_v27.x.x/flow_v0.134.x-/jest_v27.x.x.js
definitions/npm/jest_v27.x.x/flow_v0.134.x-/test_jest-v27.x.x.js

- Links to documentation: https://jestjs.io/docs/api#testskipeachtablename-fn
Other notes:

Jest: add missing `test.skip.each`

---

definitions/npm/typescript_v3.3.x/flow_v0.104.x-/typescript_v3.3.x.js

- Type of contribution: fix/refactor
This changes some object types in the typescript defs to be interfaces instead. Flow 0.153.0 requires this to
- be able to pass subclasses of `ParseConfigHost` to funtions that have `ParseConfigHost` as a parameter
- to be able to say `class Something implements ParseConfigHost`, `ParseConfigHost` needs to be an interface

Use more interface types for Typescript

---

definitions/npm/local-storage-es5_v2.x.x/test_local-storage-es5_v2.x.x.js
definitions/npm/local-storage_v2.x.x/flow_v0.25.x-/local-storage_v2.x.x.js
definitions/npm/local-storage_v2.x.x/test_local-storage_v2.x.x.js

`local-storage-es5` is a direct replica of `local-storage` that I forked myself for use with ie11. Though `local-storage` was never typed so I'm adding now for those that use the more popular `local-storage`
- Links to documentation: https://www.npmjs.com/package/local-storage
- Link to GitHub or NPM: https://www.npmjs.com/package/local-storage
Other notes: Also fix `local-storage-es5` suppression code errors

[local-storage] Add definition

---

definitions/npm/@react-navigation/bottom-tabs_v5.x.x/flow_v0.104.x-/bottom-tabs_v5.x.x.js
definitions/npm/@react-navigation/core_v5.x.x/flow_v0.104.x-/core_v5.x.x.js
definitions/npm/@react-navigation/devtools_v5.x.x/flow_v0.104.x-/devtools_v5.x.x.js
definitions/npm/@react-navigation/drawer_v5.x.x/flow_v0.104.x-/drawer_v5.x.x.js
definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/flow_v0.104.x-/material-bottom-tabs_v5.x.x.js
definitions/npm/@react-navigation/material-top-tabs_v5.x.x/flow_v0.104.x-/material-top-tabs_v5.x.x.js
definitions/npm/@react-navigation/native_v5.x.x/flow_v0.104.x-/native_v5.x.x.js
definitions/npm/@react-navigation/stack_v5.x.x/flow_v0.104.x-/stack_v5.x.x.js

Newer versions of Flow revealed a lot of issues with these libdefs. This PR fixes all of them so `run-tests` is clean.

[react-navigation] Fix issues exposed by newer versions of Flow

---

definitions/npm/@react-navigation/bottom-tabs_v5.x.x/flow_v0.104.x-/bottom-tabs_v5.x.x.js
definitions/npm/@react-navigation/core_v5.x.x/flow_v0.104.x-/core_v5.x.x.js
definitions/npm/@react-navigation/devtools_v5.x.x/flow_v0.104.x-/devtools_v5.x.x.js
definitions/npm/@react-navigation/drawer_v5.x.x/flow_v0.104.x-/drawer_v5.x.x.js
definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/flow_v0.104.x-/material-bottom-tabs_v5.x.x.js
definitions/npm/@react-navigation/material-top-tabs_v5.x.x/flow_v0.104.x-/material-top-tabs_v5.x.x.js
definitions/npm/@react-navigation/native_v5.x.x/flow_v0.104.x-/native_v5.x.x.js
definitions/npm/@react-navigation/stack_v5.x.x/flow_v0.104.x-/stack_v5.x.x.js

This should be `$ReadOnly` – it's a parameter that's passed in and not mutated.
Note: there are currently issues with the tests that should be solved in #4103, so they will be failing on this PR. I can rebase it after #4103 is merged, or you can take my word that I ran the tests locally :)

[react-navigation] Make route param to Navigate function $ReadOnly

---

definitions/npm/cypress_v5.x.x/flow_v0.25.x-/cypress_v5.x.x.js
definitions/npm/cypress_v6.x.x/flow_v0.25.x-/cypress_v6.x.x.js
definitions/npm/cypress_v6.x.x/test_cypress_v6.x.x.js

In our own use case we've found that cypress invoke function actually returns a chainable object as opposed to void. This fixes that.
- Links to documentation: https://docs.cypress.io/api/commands/invoke#Arguments
- Link to GitHub or NPM: https://www.npmjs.com/package/cypress
Other notes:

[cypress] Update invoke function to return chainable

---

definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/react_v10.x.x.js
definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-/react_v11.x.x.js
definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/react_v12.x.x.js
definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/react_v8.x.x.js
definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/react_v9.x.x.js
definitions/npm/react-dom_v16.x.x/flow_v0.117.x-/react-dom_v16.x.x.js
definitions/npm/react-dom_v16.x.x/flow_v0.117.x-/test_react-dom_v16.x.x.js
definitions/npm/react-dom_v17.x.x/flow_v0.127.x-/react-dom_v17.x.x.js

This fixes this issue when trying to use react testing library `act()` with async functions in flow 0.153:
This new error is caused by these new changes in flow: https://medium.com/flow-type/sound-typing-for-this-in-flow-d62db2af969e
Other notes:

fix react testing library act() to work fine in flow >=0.153

---

definitions/npm/koa_v2.0.x/flow_v0.104.x-v0.152.0/koa_v2.0.x.js
definitions/npm/koa_v2.0.x/flow_v0.104.x-v0.152.0/test_koa_v2.0.x.js
definitions/npm/koa_v2.0.x/flow_v0.153.x-/koa_v2.0.x.js
definitions/npm/koa_v2.0.x/flow_v0.153.x-/test_koa_v2.0.x.js

When using `koa` with `koa-body` you can access the request body through the ctx, in koa-body docs you can look for `ctx.request.body` for reference.
- Links to documentation: https://www.npmjs.com/package/koa-body
- Link to GitHub or NPM: https://www.npmjs.com/package/koa
Other notes:

[koa] Add body into request object

---

definitions/npm/@testing-library/user-event_v13.x.x/flow_v0.104.x-/test_user-event_v13.x.x.js
definitions/npm/@testing-library/user-event_v13.x.x/flow_v0.104.x-/user-event_v13.x.x.js

Update definitions for v13 of `@testing-library/user-event`.
Added: [`.keyboard()`](https://testing-library.com/docs/ecosystem-user-event/#keyboardtext-options) definition.
Modified: [`.type()`](https://testing-library.com/docs/ecosystem-user-event/#typeelement-text-options) returns an empty promise when the option `delay` is given with a value superior to `0`. Otherwise it returns immediately `void`.
NOTE: To do so, I had to rewrite the definition file using separate `declare function` instead of a object type.
- Links to documentation: https://testing-library.com/docs/ecosystem-user-event/
- Link to GitHub or NPM: https://github.com/testing-library/user-event
- Type of contribution:  addition & fix & refactor

[@testing-library/user-event] Add definitions for v13

---

definitions/npm/typescript_v3.3.x/flow_v0.104.x-/typescript_v3.3.x.js
definitions/npm/typescript_v3.3.x/test_typescript_v3.3.x.js

The definitions for the typescript package don't seem to have any tests, so this broke silently with Flow's addition of unbinding checks.
From https://github.com/parcel-bundler/parcel/pull/6718#discussion_r688793140:
> The "methods" for this interface are a mix of methods and properties whose values are arrow functions. Methods cannot be unbound, but properties can, making them incompatible — unfortunately this means that our subclass can't use entirely methods nor properties.
> 
> I think the reasoning for this is the interfaces these inherit from have optional properties, something that can't be done with methods, and since they're incompatible, they must stay consistent. That's the case with getCurrentDirectory, which is a property in the parent interface but was a method here.
@gkz …

typescript: unbreak unbinding checks for LanguageServiceHost

---

definitions/npm/remarkable_v1.x.x/test_remarkable_v1.x.x.js
definitions/npm/remarkable_v2.x.x/flow_v0.104.x-/remarkable_v2.x.x.js
definitions/npm/remarkable_v2.x.x/test_remarkable_v2.x.x.js

- Links to documentation: https://github.com/jonschlinkert/remarkable
- Link to GitHub or NPM: https://github.com/jonschlinkert/remarkable
Other notes:
- The `RemarkablePlugin` type was not exported and as used by the `linkify` plugin produced an error
- The `linkify` pllugin does not accept options https://github.com/jonschlinkert/remarkable/blob/58b6945f203ca7a0bb5a0785df90a3a6a8b9e59c/lib/linkify.js#L157
- Added suppression codes to 1.x as well

[remarkable_v2.x.x] Fix and update linkify plugin

---

definitions/npm/rxjs_v6.x.x/flow_v0.104.x-/rxjs_v6.x.x.js
definitions/npm/rxjs_v6.x.x/flow_v0.72.x-v0.103.x/rxjs_v6.x.x.js

Other notes:
Fix inconsistent/incorrect type for `retryWhen`.
I'm not sure why but flow treats `(rxjs$Observable<T>) => rxjs$Observable<T>` as a different type to `rxjs$MonoTypeOperatorFunction<T>` although they look like they should be compatible to me. As a consequence without this change it is a type error to use `retryWhen` in a `.pipe(...)`, which is how it is intended to be used. For this reason, this change fixes three failing tests.

rxjs: Fix incorrect type for retryWhen.

---

definitions/npm/rxjs_v6.x.x/flow_v0.104.x-/test_operator_retryWhen.js
definitions/npm/rxjs_v6.x.x/flow_v0.72.x-v0.103.x/test_operator_retryWhen.js

Other notes:
This fixes a failing test.
It looks like someone typoed a duplicate `retryWhen` nested inside another `retryWhen`, but it's also possible they did it deliberately for some reason. Nevertheless it causes the test to fail.

rxjs: Fix faulty test for retryWhen.

---

CONTRIBUTING.md
cli/src/cli.js
cli/src/commands/create-def.js
create_def.sh

Create a handy script inspired from #4042 that will create a basic structure for new type def configured to an appropriate lowest supported version as recommended in contribution guide.
Comes built with a lib def file plus a test file with base structure
Usage: `./create_def.sh lib-name 1.x.x`
*sample when running `./create_def.sh test 1.x.x`*

Create def script for easier lib def creation

---

cli/src/commands/__tests__/install-test.js
cli/src/commands/install.js
cli/src/lib/npm/npmProjectUtils.js
cli/src/lib/stubUtils.js

Closes #4127.
This PR supports a new `.ignore` file that can be added to the root `flow-typed` dir of a project where your lib defs currently live. ie: `./flow-typed/.ignore`
Here you can add lines of exclusions separated by new lines supporting explicit dependencies or scopes
eg the file may look like
```
@babel
@babel/
@testing-library/react
eslint
```
Other notes: Tested locally and works pretty well

[cli] .ignore file support

---

definitions/npm/history_v5.x.x/flow_v0.104.x-/history_v5.x.x.js

https://github.com/remix-run/history/blob/8bef6f4d50548f46ab7c97e171b3d8634093e7a7/packages/history/index.ts#L131
Other notes:

Fix history.listen to have an object as a parameter

---

definitions/npm/history_v5.x.x/flow_v0.104.x-/history_v5.x.x.js

- https://github.com/remix-run/history/blob/main/docs/api-reference.md#historyforward
https://github.com/remix-run/history/blob/main/docs/api-reference.md#historyforward
https://github.com/remix-run/history
Other notes:
`goBack` -> `back` in V5
`goForward` -> `forward` in V5
Maybe V4 types were copied over by accident

Fix history@5 back() and forward() type definitions

---

definitions/npm/redux-saga_v1.x.x/flow_v0.104.x-/redux-saga_v1.x.x.js
definitions/npm/redux-saga_v1.x.x/flow_v0.104.x-/test_redux-saga_1.x.x_take.js
definitions/npm/redux-saga_v1.x.x/flow_v0.104.x-/test_redux-saga_1.x.x_takeMaybe.js
definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-v0.103.x/redux-saga_v1.x.x.js
definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-v0.103.x/test_redux-saga_1.x.x_take.js
definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-v0.103.x/test_redux-saga_1.x.x_takeMaybe.js

- Links to documentation: https://redux-saga.js.org/docs/api/#takepattern
- Link to GitHub or NPM: https://github.com/redux-saga/redux-saga/blob/1ecb1bed867eeafc69757df8acf1024b438a79e0/packages/types/types/index.d.ts#L12
Other notes:
Function patterns don't require returning a boolean, but instead just returning _any_ value, which is checked for "thruthiness" or "falsiness."
> If `pattern` is a function, the action is matched if `pattern(action)` is true (e.g. `take(action => action.entities)` will match all actions having a (truthy) `entities` field.)

[redux-saga_v1.x.x] Allow for any return value on Subpattern functions

---

definitions/npm/react-addons-test-utils_v15.x.x/flow_v0.104.x-/react-addons-test-utils_v15.x.x.js
definitions/npm/react-addons-test-utils_v15.x.x/flow_v0.25.x-v0.103.x/react-addons-test-utils_v15.x.x.js
definitions/npm/react-addons-test-utils_v15.x.x/test_react-addons-test-utils.js

Fix definition which throws errors because of undefined type var
- Links to documentation: https://reactjs.org/docs/test-utils.html
- Link to GitHub or NPM: https://www.npmjs.com/package/react-addons-test-utils
Other notes:

[react-addons-test-utils] Fix broken definition

---

cli/src/commands/runTests.js

Closes #2752. When making a change to a libdef of a particular version it sometimes becomes overwhelming when a single change on one library version requires changes to all versions of the same library name.
This change will target the particular version changes only.
Example:
Tests only run on a single version of redux-saga that was modified
Other notes: I don't mind it most of the time, but I can see the struggle when trying to maintain `styled-component` for example and the older versions are completely broken so your tests will never pass.
cc @villesau

[cli] Only run changed version on only-changed option

---

cli/flow-typed/npm/lodash_v4.x.x.js
cli/src/commands/__tests__/install-test.js
cli/src/commands/install.js

Closes #4184.
User when running `flow-typed install` will now also have flow stop and start which will have more guarantee of a stable install process.
Added an option `skipFlowRestart` that will tell flow-typed to not run this post install process but it being false by default seems better for every day user.
This does slow down install by a bit, so will need to look into performance of flow-typed install later anyways as mentioned here #2881

[cli] Install will restart flow bin

---

definitions/npm/mocha_v8.x.x/flow_v0.104.x-/mocha_v8.x.x.js

Other notes:
This seems like a typo, with Flow 0.168 this actually throws an error:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/mocha_v8.x.x.js:209:26
Unexpected token ;, expected the token :
206│ declare var setup: Setup;
207│ declare var teardown: Teardown;
208│ declare var suiteSetup: SuiteSetup;
209│ declare var suiteTeardown;
^
210│ declare var before: Before
211│ declare var after: After;
212│ declare var beforeEach: BeforeEach;
```

Add missing type for mocha global variable

---

definitions/npm/react-test-renderer_v16.x.x/flow_v0.104.x-/react-test-renderer_v16.x.x.js

Fix return type of `getMountedInstance()` (see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7ec78508c6797e42f87a4390735bc2c650a1bfd/types/react-test-renderer/v16/shallow/index.d.ts) and [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/afd309b4193c1f448386bf8fe09e512e4422e69e/types/react/index.d.ts#L435))

[react-test-renderer] fix getMountedInstance type

---

definitions/npm/redux-devtools-extension_v2.x.x/flow_v0.104.x-/redux-devtools-extension_v2.x.x.js
definitions/npm/redux-devtools-extension_v2.x.x/test_redux-devtools-extension_v2.x.x.js

Move the imports and type declarations into the `declare module 'redux-devtools-extension'` block, and duplicate the type declarations into the other module blocks.

[redux-devtools-extension] fix toplevel-library-import errors

---

definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/react-redux_v7.x.x.js

Export the `ConnectedComponent` class to allow for connected component exports to be annotated.

[react-redux] export ConnectedComponent

---

definitions/npm/react-redux_v5.x.x/flow_v0.142.x-/test_connect.js
definitions/npm/react-redux_v6.x.x/flow_v0.142.x-/test_connect.js
definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connect.js

Solves an error with test naming found from #4203
Other notes:

[react-redux] Fix test names

---

CONTRIBUTING.md

[docs] Fix some link issues in contributing docs

---

definitions/npm/mocha_v3.1.x/flow_v0.104.x-/mocha_v3.1.x.js
definitions/npm/mocha_v4.x.x/flow_v0.104.x-/mocha_v4.x.x.js
definitions/npm/mocha_v5.x.x/flow_v0.104.x-/mocha_v5.x.x.js
definitions/npm/mocha_v6.x.x/flow_v0.104.x-/mocha_v6.x.x.js
definitions/npm/mocha_v7.x.x/flow_v0.104.x-/mocha_v7.x.x.js

The definitions of mocha v4-7 contains a line that the latest version of flow cannot process.
```
Error ---------------------------------------------------------------------------- flow-typed/npm/mocha_v4.x.x.js:208:26
Unexpected token `;`, expected the token `:`
208| declare var suiteTeardown;
^
```

Fix the definitions of old versions of mocha

---

cli/src/lib/libDefs.js

In https://github.com/flow-typed/flow-typed/pull/4210 a contributor was unable to run tests when create a new lib def because they may have made a mistake when initially trying to create the dir structure. This throws an error but it's not one that's descriptive enough to help them pinpoint where to go to solve the issue.
Other notes, when I was building this fix I opened the `definitions/npm` dir in my finder and then it started throwing a lot of errors related to `DS_Store` I think instead of throwing we should just exit in that case so I've added that also.

[cli] Provide better logs related to dir structure when running tests

---

cli/src/lib/npm/npmLibDefs.js

Closes #1723 @GAntoine can you believe there was already an issue asking for this to be fixed 😈.
Tested with additional `.DS_Store` added to `definitions/npm/package/.DS_Store` and `definitions/npm/@scope/.DS_Store`

[cli] Allow DS_Store in definitions nested directories

---

docs/faq.md

Fix the docs I added in FAQ regarding where to add the `eslintrc.js` file.

[docs] Fix the documented pathing for an ignoring eslint

---

definitions/npm/jsonwebtoken_v8.4.x/flow_v0.56.x-v0.103.x/jsonwebtoken_v8.4.x.js
definitions/npm/jsonwebtoken_v8.5.x/flow_v0.56.x-v0.103.x/jsonwebtoken_v8.5.x.js

This fix is for a definition that was added earlier today and breaks our production builds as we are using flow-bin < 0.103.
Your automated tests only cover the last 15 flow-bin versions published to npm.

Add missing trailing comma from VerifyOptions type in jsonwebtoken definition

---

cli/src/lib/npm/__tests__/npmLibDefs-test.js
cli/src/lib/npm/npmLibDefs.js

Closes #4222
Other notes: I added a giant comment block because I got confused, I hope it's fine and helps future contributors. The tests should help but I think it was still appropriate with some explanation

[cli] Fix minor libdef install

---

cli/package.json

A Security Vuln was identified in the Colors package for >1.4.0, offending packages being `1.4.1`, `1.4.44-liberty`
- [source1](https://twitter.com/snyksec/status/1480286811482206216?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet)
- [source2](https://twitter.com/snyksec/status/1480286811482206216?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet)
- [source3](https://security.snyk.io/vuln/SNYK-JS-COLORS-2331906)
This PR pins the color package to `1.4.0` as advised on the [snyk page](https://snyk.io/blog/open-source-maintainer-pulls-the-plug-on-npm-packages-colors-and-faker-now-what/)
Other notes:

fix: pin colors@1.4.0 to fix security vuln

---

definitions/npm/koa_v2.x.x/flow_v0.153.x-/koa_v2.x.x.js

Add props available in koa context when app uses `koa-useragent`
- Links to documentation: https://github.com/rvboris/koa-useragent/blob/master/README.md?plain=1#L51
- Link to GitHub or NPM: https://www.npmjs.com/package/koa-useragent
Other notes:

[koa] Add context props from `koa-useragent`

---

cli/src/commands/create-def.js

When using `./create_def.sh` with a scoped package such as `@octokit/rest` it didn't work because the command wasn't configured to handle this and would try to created nested directories immediately.

[cli] fix create def with scopes 

---

definitions/npm/humps_v2.x.x/flow_v0.104.x-/humps_v2.x.x.js
definitions/npm/humps_v2.x.x/flow_v0.104.x-/test_humps_v2.x.x.js

Co-authored-by: David Coelho <davidcoelho02@outlook.com>
- Links to documentation: https://github.com/domchristie/humps/tree/050b1fd852cf0847bed9513655b2afbb20d89859#converting-object-keys
- Link to GitHub or NPM: https://github.com/domchristie/humps
Other notes:
We were working with hump's `camelizeKeys` and hitting an error due to its definition.
We got it to work properly with this change, but feel free to tell us if we should have done this differently.
Thanks for your review 🙇

Update humps v2.x.x camelizeKeys function definition

---

cli/src/commands/__tests__/install-test.js
cli/src/lib/npm/__tests__/npmLibDefs-test.js
cli/src/lib/npm/npmLibDefs.js

Closes #4245. Previously there was no way for alpha versions of a library to match a libdef.

[cli] Install can match with alpha versions now

---

cli/src/lib/npm/npmLibDefs.js
docs/validate.md

Hear me out, this is the beginning of a series of changes. After having a read of #87 and then testing `validate-def` I found that the testing against npmjs doesn't actually work. It uses `got` to ping npmjs.com but because it's hitting a website even if the website says 404 the website itself it a 200 response. Furthermore hitting a website like crazy reaches a `HTTPError: Response code 429 (Too Many Requests)` error. I've changed this to use `api.npms.io/v2/` instead which can support the load and will reliably return with whether the request succeeds or fails.
But the code using a mix of then/catch + async/await doesn't actually work properly, even if the `got` reaches a 404 it still ends saying `All libdefs are named and structured correctly`.
Finally there is one library called …

[cli] Turn off validate-def checks against npm

---

definitions/npm/jest_v23.x.x/flow_v0.134.x-/test_jest-v23.x.x.js
definitions/npm/jest_v24.x.x/flow_v0.134.x-/test_jest-v24.x.x.js
definitions/npm/jest_v25.x.x/flow_v0.134.x-/test_jest-v25.x.x.js
definitions/npm/jest_v26.x.x/flow_v0.134.x-/test_jest-v26.x.x.js
definitions/npm/jest_v27.x.x/flow_v0.134.x-/test_jest-v27.x.x.js

Closes #3836. Adding tests against `it` jest global opbject.
- Links to documentation: https://jestjs.io/docs/api#2-describeeachtablename-fn-timeout
- Link to GitHub or NPM: https://npmjs.com/package/jest
Other notes: @hadron-mhchu looks like this has worked for a while on versions 23+ but I'm adding some tests since there are zero tests on `it` in general.

[jest] Add tests against it.each

---

definitions/npm/react-testing-library_v5.x.x/flow_v0.104.x-/react-testing-library_v5.x.x.js
definitions/npm/react-testing-library_v5.x.x/flow_v0.104.x-/test_react-testing-library_v5.x.x.js

Closes #3692
- Links to documentation: https://www.npmjs.com/package/react-testing-library
- Link to GitHub or NPM: https://www.npmjs.com/package/react-testing-library
Other notes: Following the spread syntax from latest version of [@testing-library/react](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/%40testing-library/react_v12.x.x/flow_v0.104.x-/react_v12.x.x.js#L444) which is shown to be the correct implementation. Although this library is deprecated.

[react-testing-library] Fix `RenderResult` type to spread it's parent

---

docs/tests.md

Ref: https://github.com/flow-typed/flow-typed/blob/master/cli/src/commands/runTests.js#L701

[docs] Add missing flag in run-tests docs

---

definitions/npm/chalk_v4.x.x/flow_v0.104.x-/chalk_v4.x.x.js
definitions/npm/chalk_v4.x.x/flow_v0.104.x-/test_chalk_v4.x.x.js

Follow patterns from TS definition to expose list of possible colors and modifiers so that consumers can build appropriate wrapper functions that accept only a subset of values instead of `string` which is unsafe.
- Links to documentation: https://github.com/chalk/chalk/blob/v4.1.2/index.d.ts#L6
- Link to GitHub or NPM: https://www.npmjs.com/package/chalk
Other notes:

[chalk] Export list of modifier and color types

---

.gitignore
CONTRIBUTING.md
docs/_sidebar.md
docs/harness.md
test_harness.sh

Closes #4267
Run a sh script that will create the test harness for faster local development of definitions
Other notes:
@meandmax @GAntoine @AndrewSouthpaw

[cli] Create test harness

---

definitions/npm/react-router_v5.x.x/flow_v0.104.x-/react-router_v5.x.x.js
definitions/npm/react-router_v5.x.x/flow_v0.104.x-/test_react-router.js

I made an update to the `useParams` types after opening #4272. I tried to add a bound to the type to require that the provided type has string values only, but ran into issues with making that work with the default type that is provided since it has the values as `?string`. If there is a quick fix for this I'd love to add it, but these types would work for me!

[react-router] Update type for useParams to allow for generics

---

definitions/npm/react-router-dom_v5.x.x/flow_v0.104.x-/react-router-dom_v5.x.x.js
definitions/npm/react-router-dom_v5.x.x/flow_v0.104.x-/test_react-router-dom.js

Hello, sorry for the near duplicate PR. I realized this morning I only updated the type in `react-router` but forgot `react-router-dom` 😅. This is the same changes from #4273 applied to the `react-router-dom` types.

[react-router-dom] Update type for useParams to allow for generics

---

definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/react_v12.x.x.js

Adding to `UnionHTMLElement` and `IntersectionHTMLElement` to allow usage with `<label />` elements for the use case of checking for the value of `htmlFor`
- Links to documentation: https://www.npmjs.com/package/@testing-library/react
Other notes:

[@testing-library/react] Add HTMLLabelElement to intersection type

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js
definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/test_react-router-dom.js

- https://gist.github.com/mjackson/b5748add2795ce7448a366ae8f8ae3bb#notes-on-the-navigate-api
- https://reactrouter.com/docs/en/v6/api#usenavigate
- https://reactrouter.com/docs/en/v6/api#navigate
- Link to GitHub or NPM: https://www.npmjs.com/package/react-router
Other notes:

[react-router-dom] Replace `Redirect` with `Navigate`

---

definitions/npm/base64-arraybuffer_v1.x.x/flow_v0.83.x-/base64-arraybuffer_v1.x.x.js
definitions/npm/base64-arraybuffer_v1.x.x/flow_v0.83.x-/test_base64-arraybuffer_v1.x.x.js

- Links to documentation: https://github.com/niklasvh/base64-arraybuffer/blob/5339d8f0abed59c893e87116a785bf52acdc17aa/src/index.ts
- Link to GitHub or NPM: https://github.com/niklasvh/base64-arraybuffer

[base64-arraybuffer] Add base64-arraybuffer v1

---

cli/src/commands/install.js
cli/src/lib/__tests__/logger.js
cli/src/lib/logger.js
cli/src/lib/stubUtils.js

Improving some of the console logs, particularly whenever there are usages of `└>` to display listed items to a reusable func to make the overall cli usage cleaner and make it easier for other areas to use the same format

[cli]: Consistent list logging

---

cli/src/commands/__tests__/install-test.js
cli/src/commands/install.js
cli/src/lib/ftConfig.js
docs/flow-typed-config.md
docs/install.md

Ignored libs for install can now read from both `.ignore` or `flow-typed.config.js` under the `ignore` property.
This is aimed to use the config module for any future config but also continue to allow usage of `.ignore` so that we're non-breaking

[cli]: Make use of flow-typed.config.js for ignored

---

cli/src/lib/cacheRepoUtils.js
cli/src/lib/libDefs.js

Other notes:
Trying to get a prerelease ready @ `3.8.0-0`, I encounter this error: `Please upgrade your flow-typed CLI! This CLI is version 3.8.0-0, but the latest flow-typed definitions are only compatible with flow-typed@>=*.*.*`. This fix coerces that version to `3.8.0`, allowing it to pass the tests.

Coerce cli version with semver to allow for prerelease tags

---

definitions/environments/react/flow_v0.83.x-/react.js
definitions/environments/react/flow_v0.83.x-/test_react.js

React components actually allow for extra properties in the react component once defined, there are many real world cases where this occurs but flow libs don't allow for this.
I'm adding a new flow-typed `environment` that overrides right now a single piece of the react definitions that doesn't require users to upgrade to the latest flow version to take advantage of this. I believe def can have future use cases where commonly flow libs are not backwards compatible.
- Link to GitHub or NPM: https://www.npmjs.com/package/react
Other notes: This use case came from @meandmax when we were pairing and found that flow blocked adding extra properties to a higher order component.

[react] Add new environment to override react definitions

---

definitions/npm/bn.js_v2.x.x/flow_v0.83.x-/bn.js_v2.x.x.js
definitions/npm/bn.js_v2.x.x/flow_v0.83.x-/test_bn.js_v2.x.x.js
definitions/npm/bn.js_v3.x.x/flow_v0.83.x-/bn.js_v3.x.x.js
definitions/npm/bn.js_v3.x.x/flow_v0.83.x-/test_bn.js_v3.x.x.js
definitions/npm/bn.js_v4.x.x/flow_v0.83.x-/bn.js_v4.x.x.js
definitions/npm/bn.js_v4.x.x/flow_v0.83.x-/test_bn.js_v4.x.x.js
definitions/npm/bn.js_v5.x.x/flow_v0.83.x-/bn.js_v5.x.x.js
definitions/npm/bn.js_v5.x.x/flow_v0.83.x-/test_bn.js_v5.x.x.js

- [v5](https://github.com/indutny/bn.js/blob/v5.2.0/README.md)
- [v4](https://github.com/indutny/bn.js/blob/v4.12.0/README.md)
- [v3](https://github.com/indutny/bn.js/blob/v3.3.0/README.md)
- [v2](https://github.com/indutny/bn.js/blob/v2.2.0/README.md)
- Link to GitHub or NPM: [GitHub](https://github.com/indutny/bn.js)
Other notes:
- v5 and v4 are exactly the same
- v3 is missing some util functions compared to v4
- v2 is missing unsigned operations

feat: add bn.js libdefs (v2, v3, v4, v5)

---

cli/src/lib/npm/__tests__/npmProjectUtils-test.js
cli/src/lib/npm/npmProjectUtils.js

If an npm package has a value that resolves to a different dependency the value does not work with `semver` and crashes when using the CLI with monorepos.
Tests showcase what is being fixed
cc: @meandmax

[cli] Fix if dependency is resolved npm package

---

definitions/npm/has-ansi_v4.x.x/flow_v0.83.x-/has-ansi_v4.x.x.js
definitions/npm/has-ansi_v4.x.x/flow_v0.83.x-/test_has-ansi_v4.x.x.js
definitions/npm/has-ansi_v5.x.x/flow_v0.83.x-/has-ansi_v5.x.x.js
definitions/npm/has-ansi_v5.x.x/flow_v0.83.x-/test_has-ansi_v5.x.x.js

Add `has-ansi` v5 which is latest and v4 that will still be commonly used because it accepts native node require syntax
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/has-ansi/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/has-ansi
Other notes:

[has-ansi] Add v4/5 

---

definitions/npm/jwt-decode_v3.x.x/flow_v0.83.x-/jwt-decode_v3.x.x.js
definitions/npm/jwt-decode_v3.x.x/flow_v0.83.x-/test_jwt-decode_v3.x.x.js

Adding jwt-decode using the `.d.ts` file in the package's node_modules
- Links to documentation: Referenced below
- Link to GitHub or NPM: https://www.npmjs.com/package/jwt-decode
Other notes: if you install `jwt-decode` you will `index.d.ts` that looks like this
```
export class InvalidTokenError extends Error {}
export interface JwtDecodeOptions {
header?: boolean;
}
export interface JwtHeader {
type?: string;
alg?: string;
}
export interface JwtPayload {
iss?: string;
sub?: string;
aud?: string[] | string;
exp?: number;
nbf?: number;
iat?: number;
jti?: string;
}
export default function jwtDecode<T = unknown>(
token: string,
options?: JwtDecodeOptions
): T;
```

[jwt-decode] Add definition

---

definitions/npm/redux_v4.x.x/flow_v0.134.x-/redux_v4.x.x.js
definitions/npm/redux_v4.x.x/flow_v0.134.x-/test_createStore.js

As unfortunate as adding `legacy_createStore` is it's already been shipped so this adds the type definition for it for those that want to use it
- Links to documentation: https://github.com/reduxjs/redux/releases/tag/v4.2.0
- Link to GitHub or NPM: https://www.npmjs.com/package/redux
Other notes: Open to feedback for whether I should add this as `4.2.x` instead of `4.x.x`

[redux] Add `legacy_createStore`

---

definitions/npm/is-dark-color_v1.x.x/flow_v0.83.x-/is-dark-color_v1.x.x.js
definitions/npm/is-dark-color_v1.x.x/flow_v0.83.x-/test_is-dark-color_v1.x.x.js

- Links to documentation: https://github.com/gion/is-dark-color/blob/master/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/is-dark-color
Other notes:

[is-dark-color] New definition 

---

definitions/npm/jest_v28.x.x/flow_v0.134.x-/jest_v28.x.x.js
definitions/npm/jest_v28.x.x/flow_v0.134.x-/test_jest_v28.x.x.js

- Links to documentation: https://github.com/facebook/jest/tree/main/packages/jest-types
- Link to GitHub or NPM: https://www.npmjs.com/package/jest
Other notes:
copied from the v27 definition with a jest.useFakeTimers() signature change https://jestjs.io/docs/upgrading-to-jest28#jestusefaketimers

[jest] add v28

---

definitions/__util__/tdd_framework.js
definitions/npm/react-twemoji_v0.5.x/flow_v0.83.x-/react-twemoji_v0.5.x.js
definitions/npm/react-twemoji_v0.5.x/flow_v0.83.x-/test_react-twemoji_v0.5.x.js

- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-twemoji/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/react-twemoji
Other notes: Additional props for typeof `options` are from https://github.com/twitter/twemoji/blob/master/index.d.ts#L87
- I've also added new `test` function to test utils so that test cases can read better depending on test. This exists in basic unit test frameworks too https://jestjs.io/docs/api#testname-fn-timeout

[react-twemoji] Add definition

---

definitions/npm/timezones-list_v3.x.x/flow_v0.83.x-/test_timezones-list_v3.x.x.js
definitions/npm/timezones-list_v3.x.x/flow_v0.83.x-/timezones-list_v3.x.x.js

- Links to documentation: https://www.npmjs.com/package/timezones-list
- Link to GitHub or NPM: https://www.npmjs.com/package/timezones-list
Other notes:

[timezones-list] Add definition

---

definitions/environments/jsx/flow_v0.83.x-/jsx.js
definitions/environments/jsx/flow_v0.83.x-/test_jsx.js

- Links to documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attributes
Other notes:

[jsx] Add `jsx$HTMLTextAreaElement` type

---

docs/update.md

The docs are not correct, `flow-typed update package-name` will throw an error, only `flow-typed update` works.

docs: `update` command doesn't take positional arguments

---

docs/stub.md

Added docs for the `--typescript` flag, I had to add some non-breaking-spaces because otherwise the table column would be too narrow and would have wrapped `--typescript` on two lines.

docs: document `create-stub --typescript` flag

---

definitions/npm/express_v4.x.x/flow_v0.104.x-/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.104.x-/test_overrideUseMethodClassExtension.js
definitions/npm/express_v4.x.x/flow_v0.104.x-/test_response.js
definitions/npm/express_v4.x.x/test_express_v4.x.x.js

Closes #3879. Express flow types were basically only compatible with 'http' but not 'https' because they accepted different types.
- Notice https://github.com/facebook/flow/blob/main/lib/node.js#L1638 takes `net$Socket`
- While https://github.com/facebook/flow/blob/main/lib/node.js#L1684 takes `tls$TLSSocket`
- Link to GitHub or NPM: https://www.npmjs.com/package/express
Other notes: Also fix existing flow test errors
cc: @drumbsd @AndrewSouthpaw

[express] express request compat with https

---

definitions/npm/@reduxjs/toolkit_v1.x.x/flow_v0.104.x-/test_toolkit_v1.x.x.js
definitions/npm/@reduxjs/toolkit_v1.x.x/flow_v0.104.x-/toolkit_v1.x.x.js

Closes #4326. Add `configureStore` types
- Links to documentation: https://redux-toolkit.js.org/api/configureStore
- Link to GitHub or NPM: https://www.npmjs.com/package/@reduxjs/toolkit
Other notes: I don't personally use this package so if things don't work as expected, I can improve it. More concerned about adding some types as opposed to making it exactly correct as keeping redux types and these types in sync are a pain 🥲 [Shameless plug](https://github.com/flow-typed/flow-typed/discussions/4242#discussioncomment-2838850)
cc: @michaelmior

[@redux/toolkit] Add configure store

---

definitions/npm/@reduxjs/toolkit_v1.x.x/flow_v0.104.x-/test_toolkit_v1.x.x.js
definitions/npm/@reduxjs/toolkit_v1.x.x/flow_v0.104.x-/toolkit_v1.x.x.js

Apply a fix to #4326
Other notes:

[@redux/toolkit] Fix configure store reducers

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js

New flow version highlights that there was a duplicate of a type that now throws errors
- Links to documentation: https://www.npmjs.com/package/react-router-dom
Other notes:

[react-router-dom] Duplicate type on definition

---

definitions/npm/react-helmet_v6.x.x/flow_v0.134.x-/react-helmet_v6.x.x.js

- Links to documentation: https://github.com/facebook/flow/blob/main/Changelog.md#01820
- Link to GitHub or NPM: https://github.com/nfl/react-helmet
Other notes:
The re-declaration of var Helmet causes the following error in flow 0.182.0:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/react-helmet_v6.x.x.js:42:22
Cannot declare Helmet [1] because var redeclaration is not supported. [name-already-bound]
[1] 36│   declare class Helmet mixins React$Component<HelmetProps> {
37│     static rewind(): HelmetData;
38│     static renderStatic(): HelmetData;
39│     static canUseDOM: boolean;
40│   }
41│   declare var HelmetExport: typeof Helmet;
42│   declare export var Helmet: typeof HelmetExport;
43│   declare export …
```

[react-helmet] remove var re-declaration of Helmet

---

definitions/npm/deep-freeze_v0.0.1/flow_v0.104.x-/deep-freeze_v0.0.1.js
definitions/npm/deep-freeze_v0.0.1/flow_v0.104.x-/test_deep-freeze-v0.0.1.js

- Github repo: https://github.com/substack/deep-freeze
- Example of it on flow playground: https://flow.org/try/#0CYUwxgNghgTiAEBbA9sArhEA6EAPADsjAC4DOAXPKCPgGJwgBeItAdgCoCe+IA3AFD9QkWAmLcE1Og2ZsuPeAF54AbwA+-ePAA87AHwAKKJQAkAJRBRgAeVYROAQRgwonXXoCUpi1dv2nLm4AIiA0PjZ2bvp6ADSaOvpGlOwA2gC6XvDmlhH+zq7aIWE5flF6sfG6lABGyMiYUKxqpMQwAJasAOZqrGiI1SAwhvjJmexxWu4GyKPeJZHa8VoA9MtZ1tUAVgCyUPi6MVSh0qGyHBJ6S+tbu-htBzoACoaPHkp68EX44aXaJgCimEQIFYxHkIAez3K8QqagAvgJ+OIFF8fgt9EosgBhKAQCDaKT0U4sc48Q76QRCcDQODwABusCONCJTBAlEJMhJ4MRHOJBhSKgARMA2qQoNVMMBBZRWmgQHCMikAAxpLAisUSkDATEAM1xpD4-CAA
Other notes:
This is a new type definition for the deep freeze library. It acts pretty much the same as https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/type …

Add new type for deep freeze

---

definitions/npm/@faker-js/faker_v6.x.x/flow_v0.104.x-/faker_v6.x.x.js
definitions/npm/@faker-js/faker_v6.x.x/flow_v0.104.x-/test_faker_v6.x.x.js
definitions/npm/@faker-js/faker_v6.x.x/flow_v0.25.x-v0.103.x/faker_v6.x.x.js
definitions/npm/@faker-js/faker_v6.x.x/flow_v0.25.x-v0.103.x/test_faker_v6.x.x.js

Faker from v5 to v6 has been changed to instead now expose just a single named export which contains all categories
- Links to documentation: https://www.npmjs.com/package/@faker-js/faker/v/6.3.1
- Link to GitHub or NPM: https://www.npmjs.com/package/@faker-js/faker/v/6.3.1
Other notes:

[@faker-js/faker] Fix faker export

---

definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/react_v12.x.x.js
definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/test_react_v12.x.x.js

Type of contribution: **fix**
The change below changed the `Matcher` function type to what it is today from the following
```
export type MatcherFunction = (content: string, element: HTMLElement) => boolean
```
> https://github.com/testing-library/dom-testing-library/commit/accb6cc60628cb6b5bd4d9be2ead41724995e5ae
The previous type above seems more correct since the matcher function is not called with `null` elements as far as I can tell? The type being `HTMLElement` also allows the match function to correctly interact with the DOM properties of the element, whereas `Element` is too general and throws an error when you try to access fields such as `element.style`.
== Tests
Confirmed tests failed without my changes and now pass with my changes via `./quick_run_def_tests.sh`
> ![Screen Shot …

fix: HTMLElement for element passed to MatcherFunction

---

CHANGELOG.md
CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md
README.md
cli/package.json
cli/src/commands/__tests__/install-test.js
cli/src/commands/__tests__/outdated-test.js
cli/src/commands/__tests__/runTests-test.js
cli/src/commands/install.js
cli/src/commands/runTests.js
cli/src/lib/__tests__/cacheRepoUtils-test.js
cli/src/lib/__tests__/libDefs-test.js
cli/src/lib/cacheRepoUtils.js
cli/src/lib/git.js
cli/src/lib/libDefs.js
cli/yarn.lock
docs/faq.md
docs/flow-typed-config.md
docs/index.html
docs/index.md

Targeting `main` update references to master
Also fixing an issue when there are more than one dep in config.json that caused running tests to not configure `.flowconfig` correctly in test runner.

[cli] Rename references to future main branch

---

definitions/npm/rxjs_v6.x.x/flow_v0.104.x-/rxjs_v6.x.x.js

- Links to documentation: https://github.com/ReactiveX/rxjs/blob/6.x/src/internal/operators/multicast.ts#L38
- Type of contribution:  fix  | refactor
Other notes:
Modified the rest of the multicast typing to follow the official code. You are always allowed to pass in a function that returns a subject or just a subject.

Removed dup typing. Modified the typing for the rest of multicast

---

definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/react_v12.x.x.js
definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/test_react_v12.x.x.js

Type of contribution: **fix**
The type returned as a maybe `IntersectionHTMLElement` is `?IntersectionHTMLElement` however this is imprecise and includes `undefined` so the full type is `undefined | null | IntersectionHTMLElement`, this breaks when used with a very common scenario such as the type on the `JSDOM` `toContainElement` matcher which requires a `HTMLElement | SVGElement | null`. 
Something worth noting is #4135 introduced this union type (`IntersectionHTMLElement`) which is handling the fact that various HTML elements have different properties we may want to access during testing but we cannot use `HTMLElement` and refine into a more specific shape so we use a union to accomplish that.
We can confirm the type is `HTMLElement | null` here in `dom-testing-library`
> …

[dom-testing-library] MaybeIntersectionHTMLElement

---

README.md
docs/quickstart.md

Add docs to encourage users to try out v4 and `main` branch.
@GAntoine when you publish can you tag the alpha with `next` in npm?

[docs] Add v4 announcement to readme

---

definitions/npm/knex_v0.14.x/flow_v0.104.x-/knex_v0.14.x.js
definitions/npm/knex_v0.14.x/flow_v0.104.x-/test_knex-v0.14.js
definitions/npm/knex_v0.15.x/flow_v0.104.x-/knex_v0.15.x.js
definitions/npm/knex_v0.15.x/flow_v0.104.x-/test_knex_v0.15.x.js
definitions/npm/knex_v0.16.x/flow_v0.104.x-/knex_v0.16.x.js
definitions/npm/knex_v0.16.x/flow_v0.104.x-/test_knex_v0.16.x.js

Closes #2261. For each knex version expose the `Transaction` type
- Links to documentation: https://www.npmjs.com/package/knex
- Link to GitHub or NPM: https://www.npmjs.com/package/knex
Other notes: Fix flow suppression code errors

[knex] Expose `Transaction` type

---

definitions/environments/json-api/flow_v0.83.x-/json-api.js
definitions/environments/json-api/flow_v0.83.x-/test_json-api.js
docs/env-definitions.md
docs/flow-typed-config.md

Closes #693 with environment definitions
- Links to documentation: https://jsonapi.org/
- Link to GitHub or NPM: https://github.com/json-api/json-api
Other notes: usage https://flow-typed.github.io/flow-typed/#/env-definitions
In https://flow-typed.github.io/flow-typed/#/flow-typed-config
```
{
env: ['json-api', ...],
...
}
```
- Improve some docs on how to use env's

[json-api] New env definition

---

definitions/npm/braces_v3.x.x/flow_v0.83.x-/braces_v3.x.x.js
definitions/npm/braces_v3.x.x/flow_v0.83.x-/test_braces_v3.x.x.js

- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/braces/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/braces
Other notes: braces actually accepts `string | Array<string>` instead of `string` as documented in TS defs. The examples from the npm project showcase this.

[braces] New definition

---

definitions/npm/jest_v29.x.x/flow_v0.134.x-/jest_v29.x.x.js
definitions/npm/jest_v29.x.x/flow_v0.134.x-/test_jest_v29.x.x.js

- Links to documentation: https://github.com/facebook/jest/releases/tag/v29.0.0
- Link to GitHub or NPM: https://www.npmjs.com/package/jest
Other notes:

[jest] Copy v29 defs from v28

---

definitions/npm/yargs_v16.x.x/flow_v0.104.x-/yargs_v16.x.x.js
definitions/npm/yargs_v16.x.x/flow_v0.98.x-v0.103.x/yargs_v16.x.x.js
definitions/npm/yargs_v16.x.x/test_yargs.js

- https://github.com/yargs/yargs/blob/f91d9b334ad9cfce79a89c08ff210c622b7c528f/lib/yargs-factory.ts#L2331
- https://github.com/yargs/yargs/blame/f91d9b334ad9cfce79a89c08ff210c622b7c528f/lib/yargs-factory.ts#L1351-L1360
Other notes:
The `hidden` property seems to have existed either forever or since a very long time ago, and can be seen in the TypeScript types of the `yargs` implementation. Similar deal (but less far back) for `strictCommands()` and `strictOptions()`.

[yargs] Add `hidden` option property

---

definitions/npm/yargs_v17.x.x/flow_v0.104.x-/yargs_v17.x.x.js
definitions/npm/yargs_v17.x.x/flow_v0.98.x-v0.103.x/yargs_v17.x.x.js
definitions/npm/yargs_v17.x.x/test_yargs.js

- Links to documentation: https://github.com/yargs/yargs/blob/561fc7a787228b226e0ba76ab674456cbd30cd37/lib/yargs-factory.ts
- Link to GitHub or NPM: https://github.com/yargs/yargs/releases/tag/v17.0.0
Other notes:
These are the notable differences from `yargs-v16.x.x`:
- Changed `yargs.argv` and `yargs.parse()` to potentially return a promise
- Changed `yargs.getCompletion()` to receive callback arguments and return a promise
- Changed `yargs.check()` callback to return `mixed` (which permits promises)
- Added `yargs.showVerison()`
- Removed `yargs.onFinishCommand()`
- Removed `yargs.reset()`
- Added `yargs.commands()` alias (for `yargs.command()`)
- Added `yargs.parseAsync()` and `yargs.parseSync()`
- Added `yargs.showVerison()`

[yargs] Create definition for v17.x.x

---

definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connect.js
definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connectAdvanced.js
definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connectInfer.js
definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connectMergeProps.js
definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connectThunk.js
definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_useDispatch.js
definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_connect.js
definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_connectInfer.js
definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_connectMergeProps.js
definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_connectThunk.js
definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_useDispatch.js

To support https://github.com/flow-typed/flow-typed/pull/4392 newer flow versions are throwing a new error type `[missing-local-annot]`. Preventing the pull request from being properly testable and passable.
Luckily the fixes are just adding annotations to test files
Other notes:

[react-redux] Fix missing-local-annot errors

---

definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/react-redux_v7.x.x.js
definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_useDispatch.js
definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/react-redux_v8.x.x.js
definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_useDispatch.js

As part of the local type inference project of Flow, we will require all the type arguments to be inferable from local context. In the react-redux libdef, `useDispatch` has an under-constrained type argument D, that will require a lot of annotation burden for users.
In this PR, I added default and bound to useDispatch so that:
1. You will now actually get a dispatch function instead of anything you want, and only can dispatch an action instead of arbitrary stuff.
2. If you don't care about limiting the actions you can dispatch, you don't need to annotate anything. This is necessary to upgrading Meta's internal codebase.
@jbrown215 first created this fix and tested it our internal codebase, which works extremely well. …

Add type argument default and bound to useDispatch

---

definitions/environments/node/flow_v0.155.x-/node.js
definitions/environments/node/flow_v0.155.x-/test_node.js

- Links to documentation: https://nodejs.org/api/esm.html#node-imports
Other notes:
Following a discussion on Discord, adding a few common prefixed node core libs aliases. 
More will be added as needed I guess? Or should we dump the whole thing at once?
`flow_v0155.x-` because of indexed access.

[environments] Add a few prefixed node core libs

---

definitions/environments/jsx/flow_v0.83.x-/jsx.js
definitions/environments/jsx/flow_v0.83.x-/test_jsx.js

- Links to documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#list_of_global_attributes
Other notes:
Add a few more `HTMLElement` attributes.
Would have been nice to be able to use `csstype` for the style prop but did not seemed to work in my tests.   
Same for the `role` prop and `aria-query`.   
NB: those files does not seem to be using prettier, which makes it quite tedious to contribute to.

[environments:jsx] Add a few more HTMLElement attributes

---

docs/env-definitions.md

Other notes:
Within the `jsx` environment there's no `$Attributes`  type associated with `jsx$HTMLElement`. 
Depending on the initial implementation idea should we:
- remove it from the docs?
- Add it to the env?

[docs] Fix jsx env code sample

---

definitions/npm/@octokit/rest_v18.x.x/flow_v0.83.x-/rest_v18.x.x.js
definitions/npm/@octokit/rest_v18.x.x/flow_v0.83.x-/test_rest_v18.x.x.js

Minor incremental improvements to the octokit rest definitions to better serve end users.
These are directly derived from the TS shipped definitions and I'll be slowly adding them hopefully over the next few weeks in small PRs
- Links to documentation: https://octokit.github.io/rest.js/
- Link to GitHub or NPM: https://www.npmjs.com/package/@octokit/rest
Other notes:

[@octokit/rest] Add constructor and listRepo

---

cli/yarn.lock
definitions/npm/@octokit/rest_v19.x.x/flow_v0.83.x-/rest_v19.x.x.js
definitions/npm/@octokit/rest_v19.x.x/flow_v0.83.x-/test_rest_v19.x.x.js

Copy v18 to v19 which was published to drop node support
- Links to documentation: https://github.com/octokit/rest.js/releases/tag/v19.0.0
- Link to GitHub or NPM: https://www.npmjs.com/package/@octokit/rest
Other notes:

[@octoki/rest] Add v19

---

definitions/npm/yargs_v17.x.x/flow_v0.104.x-/yargs_v17.x.x.js
definitions/npm/yargs_v17.x.x/flow_v0.98.x-v0.103.x/yargs_v17.x.x.js
definitions/npm/yargs_v17.x.x/test_yargs.js

- Links to documentation: https://yargs.js.org/docs/#api-reference-examplecmd1-desc1-cmd2-desc2
- Link to GitHub or NPM: https://github.com/yargs/yargs/blob/2e0ef3c965dd788ec4af0735ce96d66ed9f91cc0/lib/usage.ts#L111

[yargs] .example(): allow array arguments

---

cli/src/commands/__tests__/__install-fixtures__/workspace/flow-config-workspaces/flow-typed.config.json
cli/src/commands/__tests__/__install-fixtures__/workspace/flow-config-workspaces/package.json
cli/src/commands/__tests__/__install-fixtures__/workspace/flow-config-workspaces/packages/a/package.json
cli/src/commands/__tests__/__install-fixtures__/workspace/flow-config-workspaces/packages/b/package.json
cli/src/commands/__tests__/__install-fixtures__/workspace/flow-config-workspaces/packages/c/package.json
cli/src/commands/__tests__/install-test.js
cli/src/commands/install.js
cli/src/lib/ftConfig.js
cli/src/lib/npm/npmProjectUtils.js
docs/flow-typed-config.md

Creating feature for my own use case. I'm creating a project where I have a monorepo but the root doesn't use yarn workspaces, instead it has a package.json that only has `flow-bin` atm. So I need a way of specifying where it search for definitions, I'm opting to use `flow-typed.config.json` for this.
I believe this is a valuable feature as the JS ecosystem evolves and root level tooling eventually shifts to run off rust instead of JS.
Usage and docs added in the PR itself
**note** I'm merging this into `main`, I hope this can be included in that Christmas release you promised me @GAntoine 😈

[cli] workspaces in flow-typed.config.json

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js
definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/test_react-router-dom.js

- https://reactrouter.com/en/main/hooks/use-matches
- https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L154
- https://github.com/remix-run/react-router/blob/main/packages/react-router/lib/hooks.tsx#L739-L760
- https://github.com/remix-run/react-router/blob/main/packages/router/router.ts#L249
- https://github.com/remix-run/react-router/blob/main/packages/router/utils.ts#L245-L265
- Type of contribution: addition & fix 
Other notes:
Actually `useMatches` is a re-export from `react-router` that uses the router's state from `@remix-run/router`

[react-router-dom] fix & add missing hook definition

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js
definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/test_react-router-dom.js

- RouteObject: https://reactrouter.com/en/main/route/route#type-declaration
-  RouteObject: https://github.com/remix-run/react-router/blob/0ce0e4c728129efe214521a22fb902fa652bac70/packages/router/utils.ts#L145
- Type of contribution:  addition
Other notes:
I've provided two versions in order to improve react-router-dom's Route Props
- current is the advanced PR for Route component
- https://github.com/flow-typed/flow-typed/pull/4419 is the simple PR for Route component
This PR:
- Add missing props to Route component.
- Import types from source code then adapt to flow.
- update and fix Route component tests according to the changes
This PR is more complete and should provides more precise types but it's not yet fully tested

[react-router-dom] update Route component type (complete)

---

cli/src/commands/runTests.js

from 0.200.0, `exact_by_default` option is required in flowconfig and from 0.202.0, this option is set to `true` by default
cf. https://flow.org/en/docs/config/options/#toc-exact-by-default-boolean
Fixes #4422

Fix runTests command for flow@^0.200.0 set `exact_by_default` option

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js
definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/test_react-router-dom.js

fix test after migrating flow to ^0.200.0
also improve test saying testing `useOutlet` and test `useOutletContext`
- https://reactrouter.com/en/main/hooks/use-outlet
- https://reactrouter.com/en/main/hooks/use-outlet-context
Other notes:
It ~~probably~~ requires #4423 in order to pass CI

[react-router-dom] fix test after migrating flow to ^0.200.0

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js
definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/test_react-router-dom.js

- Links to documentation: https://reactrouter.com/en/main
Other notes:
reviewing commit by commit should be easier:
- drop outdated support of Navlink props `activeClassName` & `activeStyle`
also improve type className & style then add tests
cf. https://reactrouter.com/en/main/upgrading/v5#remove-activeclassname-and-activestyle-props-from-navlink-
- Navlink prop `exact` renamed to `end`
cf. https://reactrouter.com/en/main/upgrading/v5#rename-navlink-exact-to-navlink-end
- Navlink's `isActive` has been removed between versions 5 & 6 without notice:
v5: https://v5.reactrouter.com/web/api/NavLink/isactive-func
latest: https://reactrouter.com/en/main/components/nav-link#navlink
- Navlink …

[react-router-dom]  navlink, renderMatches & matchRoutes

---

definitions/npm/lodash-es_v4.x.x/flow_v0.104.x-/lodash-es_v4.x.x.js

In current versions of Flow this duplicate cause flow to crash with "Should have been excluded: .$module__lodash-es/create"
I found the log entry when running flow server with --temp-dir flag and looking at the log file generated in this temp dir:
Unhandled exception: (Failure "Should have been excluded: .$module__lodash-es/create") Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33 Called from Env.init_builtins_from_libdef.(fun) in file "src/typing/env.ml", line 917, characters 6-35

Drop duplicate declaration of lodash-es/create module

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js
definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/test_react-router-dom.js

As I'm going through the tutorial right now the definition is missing basically every function the tutorial recommends using.
- Links to documentation: https://reactrouter.com/en/main/start/tutorial
Other notes: As I keep going I may add more but this should be enough for most people to get started.

[react-router-dom] Add missing functions from tutorial

---

cli/src/commands/runTests.js

If you look at the list of [releases](https://github.com/facebook/flow/releases), previously up to version [v0.200.1](https://github.com/facebook/flow/releases/tag/v0.200.1) flow used to release only a x86 binary
After this, from [v0.201.0](https://github.com/facebook/flow/releases/tag/v0.201.0) onward flow started releasing osx arm binaries.
The original flow-typed fetching binary logic never anticipated arm, so the logic was never handled and when it found 2 binaries for macos it crashed silently.
- More logic to binary selection
- Refined regex expression so that it will never find multiple binaries

[cli] Fix running definition tests locally on MacOS

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/react-router-dom_v6.x.x.js
definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/test_react-router-dom.js

- Links to documentation: https://reactrouter.com/en/main/routers/create-memory-router#creatememoryrouter
- Link to GitHub or NPM: https://github.com/remix-run/react-router
Other notes:
- embed related internal types from typescript definition
- prettier files

[react-router-dom] add `createMemoryRouter` function

---

cli/src/commands/create-def.js
definitions/npm/tua-body-scroll_v1.x.x/flow_v0.83.x-/test_tua-body-scroll_v1.x.x.js
definitions/npm/tua-body-scroll_v1.x.x/flow_v0.83.x-/tua-body-scroll_v1.x.x.js

- Links to documentation: https://www.npmjs.com/package/tua-body-scroll-lock
- Link to GitHub or NPM: https://www.npmjs.com/package/tua-body-scroll-lock
Other notes: Made an improvement to the create-def script because I always forget whether I need to add `v`

[tua-body-scroll] Add definition

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/react-router-dom_v6.x.x.js
definitions/npm/webpack_v4.x.x/flow_v0.104.x-/webpack_v4.x.x.js
definitions/npm/webpack_v5.x.x/flow_v0.104.x-/webpack_v5.x.x.js

Fix errors appearing for `webpack` and `react-router-dom` in version `0.208.0`

[webpack] Fix 0.208.x errors

---

definitions/npm/react-redux_v8.x.x/flow_v0.201.x-/react-redux_v8.x.x.js

```
declare export type Action<T> = {
type: T,
...
}
```
`Action` is declared as an inexact object which means when spread over `AnyAction` they must both be of the same type constraint. Though there is no usability difference with indexer objects flow sees these as incompatible. 
Other notes: The tests are throwing lots of errors mainly around unconstrained generic usage that I don't have the effort to fix at this stage

[react-redux] Definition fix matching action inexact type

---

definitions/environments/jsx/flow_v0.83.x-/jsx.js
definitions/environments/jsx/flow_v0.83.x-/test_jsx.js

- Links to documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea https://react.dev/reference/react-dom/components/textarea#props

[env:jsx] Update HTMLTextAreaElement

---

cli/src/commands/runTests.js

I was wondering why in #4462 the tests passed just fine while there was many errors run locally.
See a6edf4ac0bb30f7daa6d4fcc79d62585c137b0f4 and 49a0defa9cbc27ca19b3a53a32d90891db39bc2a.

[cli:test] Fix CI tests for environments

---

definitions/npm/jest_v29.x.x/flow_v0.201.x-/jest_v29.x.x.js
definitions/npm/jest_v29.x.x/flow_v0.201.x-/test_jest_v29.x.x.js

These functions pairs should match in their type restrictions and semantics (they are just inversions of each other):
expect.arrayContaining, expect.not.arrayContaining
expect.objectContaining, expect.not.objectContaining
The Flow types for the 'not' versions were already correct: allowing typed instances of objects to be passed into the methods, not just inlined literal objects.
This pull request updates the normal versions of the functions to match.

match semantics for expect methods

---

cli/package.json
cli/src/lib/__tests__/semver-test.js
cli/src/lib/semver.js
cli/yarn.lock

Closes #4460 by fixing the lower and upper bound semver functions which previously relied on logic from `semver` where it's lower bound was returned as an undefined object if the lower bound was anything but in newer versions the lower bound is simply missing.
This allows us to now update semver and keep it updated.

[cli] Bump semver solves VULN

---

definitions/npm/copy-dir_v1.x.x/flow_v0.83.x-/copy-dir_v1.x.x.js
definitions/npm/copy-dir_v1.x.x/flow_v0.83.x-/test_copy-dir_v1.x.x.js

Closes #4494
- Links to documentation: https://www.npmjs.com/package/copy-dir
- Link to GitHub or NPM: https://www.npmjs.com/package/copy-dir
Other notes:

[copy-dir] Add definition

---

.gitattributes

When my colleagues machine installs definitions they have a different hash to me.
I'm fairly certain this is because of the cloning behaviour they have set by default which on windows is CRLF and the way that flow-typed updates the flow-typed cache is to have a copy of flow-typed cloned and pulled in the root dir of someones machine `~/.flow-typed`.
By fixing the clone behaviour of `*.js` files to LF on the repo config it ensures consistency regardless of someone's local environment and fortunately it doesn't need a CLI release.

[cli] Add .gitattributes to root

---

definitions/npm/yargs_v17.x.x/flow_v0.201.x-/yargs_v17.x.x.js
definitions/npm/yargs_v17.x.x/test_yargs.js

Improve `yargs.example` and `yargs.middleware` where they now accept more than it used to
http://yargs.js.org/docs/#api-reference-examplecmd-desc
http://yargs.js.org/docs/#api-reference-middlewarecallbacks-applybeforevalidation
- Links to documentation: https://yargs.js.org/docs/
- Link to GitHub or NPM: https://www.npmjs.com/package/yargs
Other notes:

[yargs] Fix example and middleware types

---

docs/env-definitions.md
docs/flow-typed-config.md

Hi! I spotted that the docs for `flow-typed.config.json` had invalid JSON in them and that caused them to render in red in GitHub.
It seems like valid JSON is required if I understood the code correctly:
https://github.com/flow-typed/flow-typed/blob/f9f840d2893c461e1b150dfb8b279e7ddf97f28b/cli/src/lib/ftConfig.js#L9-L15
> **Note**
>
> I also opened a pull request against `main` branch here:
>
> * #4516
>
> I don't know which pull request you'd want to have, if either, so feel free to close the other one if it is redundant ☺️

Fix some invalid JSON regarding flow-typed.config.json docs [master branch]

---

docs/env-definitions.md
docs/flow-typed-config.md

Hi! I spotted that the docs for `flow-typed.config.json` had invalid JSON in them and that caused them to render in red in GitHub.
It seems like valid JSON is required if I understood the code correctly:
https://github.com/flow-typed/flow-typed/blob/b41d67274167022725058132122c853d5c0533c5/cli/src/lib/ftConfig.js#L10-L16
> **Note**
>
> I also opened a pull request against `master` branch here:
>
> * #4515
>
> I don't know which pull request you'd want to have, if either, so feel free to close the other one if it is redundant ☺️

Fix some invalid JSON regarding flow-typed.config.json docs [main branch]

---

cli/src/commands/__tests__/install-test.js
cli/src/commands/install.js
cli/src/lib/npm/npmProjectUtils.js

[cli] Ignore non-prod definitions when installing defs of depepndecies

---

cli/package.json
definitions/package.json

The current repo is using Yarn 1, which is the legacy version or Yarn.
Current Yarn version is Yarn berry 3, with 4 around the corner.
Those are totally different beasts, and if a contributor tries to run yarn with a recent version, Yarn will try to upgrade to Yarn berry, and applies a lot of modifications.
By using the packageManager key, we can enforce the desired Yarn version, which will be used automatically by corepack.
See https://nodejs.org/docs/latest-v18.x/api/corepack.html#corepack_configuring_a_package
I choose the 1.22.19 version which is the latest of the 1.x branch.

[cli][defs] Enforce Yarn version

---

definitions/npm/react-native-vision-camera_v2.x.x/flow_v0.142.x-/react-native-vision-camera_v2.x.x.js
definitions/npm/react-native-vision-camera_v2.x.x/flow_v0.142.x-/test_react-native-vision-camera_v2.x.x.js

- Links to documentation: https://react-native-vision-camera.com/
- Link to GitHub or NPM: https://github.com/mrousavy/react-native-vision-camera

[react-native-vision-camera] Add definition

---

definitions/npm/webpack_v5.x.x/flow_v0.104.x-/test_webpack_v5.x.x.js
definitions/npm/webpack_v5.x.x/flow_v0.104.x-/webpack_v5.x.x.js

Closes #4528
- Links to documentation: https://webpack.js.org/plugins/progress-plugin/
- Link to GitHub or NPM: https://npmjs.com/package/webpack
Other notes:

[webpack] Add ProgressPlugin

---

cli/src/commands/__tests__/__install-fixtures__/end-to-end/fakeCacheRepo/definitions/environments/react/flow_v0.83.x-/react.js
cli/src/commands/__tests__/install-test.js
cli/src/commands/install.js
cli/src/lib/ftConfig.js
cli/src/lib/stubUtils.js

Closes #4445. For any dependency that ships flow type definitions check if they have a `flow-typed.config.json` and if so, read their `env` to check if they depend on any environment definitions.
If so install them along side any environment definitions the project installing might need. This allows a library to be developed with flow-typed knowing it will behave the same when consumed by a consumer using flow.
Not very common for open source, but very useful when developing a stack of internal npm libraries all shipping flow types.

[cli] Install a dependency's environment definitions

---

definitions/npm/use-debounce_v9.x.x/flow_v0.83.x-/test_use-debounce_v9.x.x.js
definitions/npm/use-debounce_v9.x.x/flow_v0.83.x-/use-debounce_v9.x.x.js

Closes #4542
- Links to documentation: https://www.npmjs.com/package/use-debounce
- Link to GitHub or NPM: https://www.npmjs.com/package/use-debounce
Other notes:

[use-debounce] Fix debounce returned function

---

definitions/npm/react-native-vision-camera_v3.x.x/flow_v0.142.x-/react-native-vision-camera_v3.x.x.js
definitions/npm/react-native-vision-camera_v3.x.x/flow_v0.142.x-/test_react-native-vision-camera_v3.x.x.js

- Links to documentation: https://react-native-vision-camera.com/
- Link to GitHub or NPM: https://github.com/mrousavy/react-native-vision-camera
- We added a libdef for v2 of the library in #4533 
- It would be nice if #4535 worked, so that the react-native types could be referenced. As I understand, this is currently impossible because of limitations in the flow type-checker.

[react-native-vision-camera] Add definition for v3

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/react-router-dom_v6.x.x.js
definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/test_react-router-dom.js

I need these for some unique infra code I'm writing so I need to expose various `UNSAFE_xxxContext` components. These are typed in TS so they are public definitions
- Links to documentation: https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L212
Other notes:

[react-router-dom] Expose UNSAFE context components

---

definitions/npm/rimraf_v5.x.x/flow_v0.104.x-/rimraf_v5.x.x.js
definitions/npm/rimraf_v5.x.x/flow_v0.25.0-v0.103.x/rimraf_v5.x.x.js
definitions/npm/rimraf_v5.x.x/test_rimraf_v3.x.x.js

- https://unpkg.com/browse/rimraf@5.0.5/dist/esm/index.js
- https://unpkg.com/browse/rimraf@5.0.5/dist/esm/opt-arg.d.ts
- Link to GitHub or NPM: https://github.com/isaacs/rimraf
- Type of contribution: add new version of existing definition
Other notes:
Changes I did compared to v3:
```patch
diff --git definitions/npm/rimraf_v3.x.x/flow_v0.104.x-/rimraf_v3.x.x.js definitions/npm/rimraf_v5.x.x/flow_v0.104.x-/rimraf_v5.x.x.js
index 23b03d2b..c29437f9 100644
--- definitions/npm/rimraf_v3.x.x/flow_v0.104.x-/rimraf_v3.x.x.js
+++ definitions/npm/rimraf_v5.x.x/flow_v0.104.x-/rimraf_v5.x.x.js
@@ -1,17 +1,13 @@
declare module 'rimraf' {
declare type Options = {
-    maxBusyTries?: number,
-    emfileWait?: number,
+    maxRetries?: number,
glob?: boolean,
- …
```

[rimraf] Add definition v5

---

definitions/npm/axios_v0.22.x/flow_v0.83.x-/axios_v0.22.x.js
definitions/npm/axios_v0.22.x/flow_v0.83.x-/test_axios_v0.22.x.js
definitions/npm/axios_v0.23.x/flow_v0.83.x-/axios_v0.23.x.js
definitions/npm/axios_v0.23.x/flow_v0.83.x-/test_axios_v0.23.x.js
definitions/npm/axios_v0.24.x/flow_v0.83.x-/axios_v0.24.x.js
definitions/npm/axios_v0.24.x/flow_v0.83.x-/test_axios_v0.24.x.js
definitions/npm/axios_v0.25.x/flow_v0.83.x-/axios_v0.25.x.js
definitions/npm/axios_v0.25.x/flow_v0.83.x-/test_axios_v0.25.x.js
definitions/npm/axios_v0.26.x/flow_v0.201.x-/axios_v0.26.x.js
definitions/npm/axios_v0.26.x/flow_v0.201.x-/test_axios_v0.26.x.js
definitions/npm/axios_v0.26.x/flow_v0.83.x-v0.200.x/axios_v0.26.x.js
definitions/npm/axios_v0.26.x/flow_v0.83.x-v0.200.x/test_axios_v0.26.x.js
definitions/npm/axios_v0.27.x/flow_v0.201.x-/axios_v0.27.x.js
definitions/npm/axios_v0.27.x/flow_v0.201.x-/test_axios_v0.27.x.js
definitions/npm/axios_v0.27.x/flow_v0.83.x-v0.200.x/axios_v0.27.x.js
definitions/npm/axios_v0.27.x/flow_v0.83.x-v0.200.x/test_axios_v0.27.x.js
definitions/npm/axios_v1.x.x/flow_v0.201.x-/axios_v1.x.x.js
definitions/npm/axios_v1.x.x/flow_v0.201.x-/test_axios_v1.x.x.js
definitions/npm/axios_v1.x.x/flow_v0.83.x-v0.200.x/axios_v1.x.x.js
definitions/npm/axios_v1.x.x/flow_v0.83.x-v0.200.x/test_axios_v1.x.x.js

- Links to documentation: https://github.com/axios/axios?tab=readme-ov-file#abortcontroller
- Link to GitHub or NPM: https://www.npmjs.com/package/axios
- Type of contribution: **addition**
This adds the `signal` field to Axios request configuration. I added it from versions 0.22.x to 1.x.x. Closes #4546.

Add `signal` property to Axios request config

---

definitions/npm/@babel/polyfill_v7.x.x/flow_v0.104.x-/test_polyfill_v7.x.x.js
definitions/npm/@babel/polyfill_v7.x.x/flow_v0.30.x-v0.103.x/test_polyfill_v7.x.x.js
definitions/npm/@babel/register_v7.x.x/flow_v0.104.x-/test_register_v7.x.x.js

- Links to documentation: [N/A](https://babeljs.io/)
This improves the placement of various `$FlowExpectedError`s so they actually apply. Error id's were also added
<details>
<summary>BEFORE</summary>
```console
$ node cli/dist/cli.js run-tests @babel/'*' --numberOfFlowVersions 1
Running definition tests against latest 1 flow versions in /home/edwin/Documents/Repositories/fox-forks/flow-typed/definitions...
Fetching all Flow binaries...
Finished fetching Flow binaries.
Testing @babel/code-frame_v7.x.x/flow_v0.104.x- (flow-v0.224.0)...
Testing @babel/polyfill_v7.x.x/flow_v0.104.x- (flow-v0.224.0)...
Testing @babel/register_v7.x.x/flow_v0.104.x- (flow-v0.224.0)...
ERROR: @babel/polyfill_v7.x.x/flow_v0.104.x-
* …
```

refactor: Improve placement of `$FlowExpectedError`s in `@babel/*` packages

---

definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/react-router-dom_v6.x.x.js
definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/test_react-router-dom.js

- Links to documentation: https://reactrouter.com/en/main/routers/create-browser-router#future
Other notes:

[react-router-dom] Add future object to NavigatorProvider object

---

definitions/npm/react-dom_v18.x.x/flow_v0.127.x-/react-dom_v18.x.x.js
definitions/npm/react-dom_v18.x.x/flow_v0.127.x-/test_react-dom_v18.x.x.js

- Links to documentation: https://react.dev/reference/react-dom/flushSync
Edit: I don't know what those test failures are. `./quick_run_def_tests.sh` passes for me locally.

[react-dom] Add flushSync

---

definitions/npm/flow-enums-runtime_v0.x.x/flow_v0.83.x-/flow-enums-runtime_v0.x.x.js
definitions/npm/flow-enums-runtime_v0.x.x/flow_v0.83.x-/test_flow-enums-runtime_v0.x.x.js

Makes sense a core flow library to be typed, though is probably never expected to be used directly :) 
- Links to documentation: https://www.npmjs.com/package/flow-enums-runtime
- Link to GitHub or NPM: https://www.npmjs.com/package/flow-enums-runtime
Other notes:

[flow-enums-runtime] Add definition

---

cli/package.json
cli/yarn.lock

- Links to documentation: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

Update semver dependency at security risk

---

definitions/environments/indexeddb/flow_v0.261.x-/indexeddb.js
definitions/environments/indexeddb/flow_v0.261.x-/test_indexeddb.js

This is the second PR in a series to implement the proposal in https://github.com/flow-typed/flow-typed/issues/4588. This PR focuses on the `indexeddb.js` libdef. I also copied over the same test in the Flow repo
- Link to GitHub or NPM: Copied from https://github.com/facebook/flow/tree/main/lib/indexeddb.js

Add builtin indexeddb from flow into environment

---

definitions/environments/intl/flow_v0.261.x-/intl.js
definitions/environments/intl/flow_v0.261.x-/test_intl.js
definitions/environments/intl/flow_v0.261.x-/test_intl_collator.js
definitions/environments/intl/flow_v0.261.x-/test_intl_date_time_format.js
definitions/environments/intl/flow_v0.261.x-/test_intl_locale.js
definitions/environments/intl/flow_v0.261.x-/test_intl_number_format.js
definitions/environments/intl/flow_v0.261.x-/test_intl_plural_rules.js

This is the third PR in a series to implement the proposal in https://github.com/flow-typed/flow-typed/issues/4588. This PR focuses on the `intl.js` libdef. I also copied over the same test in the Flow repo
- Link to GitHub or NPM: Copied from https://github.com/facebook/flow/tree/main/lib/intl.js

Add builtin intl libdef from flow into environment

---

definitions/environments/intl/flow_v0.261.x-/intl.js

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange
should be supported by most browsers
Other notes:

Add support for format Range

---

definitions/environments/intl/flow_v0.261.x-/intl.js

These types are still available in Flow because they are referenced in core libdefs. e.g. https://github.com/facebook/flow/blob/5b688ab78398b1d9840c0c2655df4d84abfd822f/lib/core.js#L1244
This diff removes them to avoid triggering `libdef-override` error in the next release.
- Link to GitHub or NPM: https://github.com/facebook/flow/blob/main/lib/intl.js

Remove types in intl environment that are still available in flow

---

definitions/environments/dom/flow_v0.261.x-/dom.js
definitions/environments/dom/flow_v0.261.x-/test_dom_popover.js

- https://developer.mozilla.org/en-US/docs/Web/API/Popover_API
- Link to GitHub or NPM:  
- https://html.spec.whatwg.org/multipage/popover.html
- https://html.spec.whatwg.org/multipage/interaction.html#the-toggleevent-interfac
This PR adds type definitions for the Popover API to the DOM environment definitions. The Popover API is part of the WHATWG HTML Living Standard and provides a standardized way to build popup UI elements.
Key additions:
- Added popover attribute and methods (showPopover, hidePopover, togglePopover) to HTMLElement
- Added popoverTargetElement and popoverTargetAction to HTMLButtonElement and HTMLInputElement
- Added ToggleEvent interface for events fired during popover state changes
- Added comprehensive test …

Add Popover API to DOM environment definitions

---

cli/src/lib/envDefs.js

https://github.com/flow-typed/flow-typed/commit/bb4cb83b7ad16d5c60a60c16760af299a63980f8 introduces support for dependency config files for environments for testing. Unfortunately, it breaks the assumption of the validation that the environment directory only contains definition file and test files. It has caused breakages like https://github.com/flow-typed/flow-typed/issues/4608
This PR allows it during validation.
Fixes: https://github.com/flow-typed/flow-typed/issues/4608
Other notes:

Unbreak environment definition install

---

definitions/environments/cssom/flow_v0.261.x-/cssom.js

…
This is just a hack to get `Partial` before Flow supported `Partial`. Now that Flow has `Partial` for a long time, we should just replace it. This enables Flow to eventually remove the legacy `$Rest`
Other notes:

Replace `$Rest<EffectTiming, {...}>` with `Partial<EffectTiming>` in cssom

---

cli/src/lib/envDefs.js

While #4609 tried to fix a breakage, it unfortunately introduces another one, where installing bom.js as environment libdef, it copies the `config.json` instead of `bom.js`. It only breaks for `bom.js` because it's the only one that's alphabetically before `config.json`.
Since the intention of the early return is not to fail the validation error, we don't need to set libDefFilePath in this case.
I have tested locally that with this fix, all the builtin env files can be installed correctly.
Other notes:

Do not consider config file to be environment libdef file

---

definitions/environments/dom/flow_v0.261.x-/dom.js
definitions/environments/dom/flow_v0.261.x-/test_dom_Document.js
definitions/environments/dom/flow_v0.261.x-/test_dom_HTMLElement.js

Rather than list out every tag name and element for every method, we can do it once with an object type. This is more flexible / reusable for other methods, and can be extended in the future for things like SVG. This also changes a few instances of `HTMLElement` to the more generic `Element`, which is all the spec guarantees.
Test Plan:
- `./quick_run_def_tests.sh`
- https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement
- https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS
- https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByTagName
- https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByTagNameNS
- https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector
- …

[flow|environment] Use mapping instead of overrides for createElement

---

cli/src/commands/runTests.js
definitions/environments/bom/flow_v0.261.x-/config.json

Summary:
- We are only including environment tests when using the "only changed" option. This makes them always run instead.
- There is another release with no attached assets, which causes the script to silently run no tests: https://api.github.com/repos/facebook/flow/releases/223729443
Test Plan:
- `./build.sh`
- `node cli/dist/cli.js run-tests ^dom_`
- Observe that `dom` environment tests get run
- Observe that we make it past flow binary step
- Add an intentional flow error into dom test, re-run above command
- Observe test correctly fails
Other notes:

[flow-typed] Fix environment tests

---

definitions/environments/dom/flow_v0.261.x-/dom.js

This is not defined anywhere
Other notes:

Remove undefined `AbortSignalReason` in `dom.js`
