- definitions/npm/normalizr_v3.x.x/flow_v0.25.x-/normalizr_v3.x.x.js
- definitions/npm/normalizr_v3.x.x/test_normalizr-v3.js
Adapted copy of https://github.com/paularmstrong/normalizr/blob/master/index.d.ts
> Add flow declaration for normalizr v3

- definitions/npm/firebase_v5.x.x/flow_v0.34.x-/firebase_v5.x.x.js
- definitions/npm/firebase_v5.x.x/flow_v0.34.x-/test_firebase.js
method documented here: 
https://cloud.google.com/nodejs/docs/reference/firestore/0.15.x/Firestore#getAll
> add getAll method

- definitions/npm/storybook-host_v4.x.x/flow_v0.54.1-/storybook-host_v4.x.x.js
- definitions/npm/storybook-host_v4.x.x/flow_v0.54.1-/test_storybook-host_v4.x.x.js
Following of #2645 where we unify and fix storybook ecosystem (plugins etc.) definitions.   
Also updated and completed a bit.
> Update storybook-host definitions

- definitions/npm/storybook-router_v0.x.x/flow_v0.25.x-/storybook-router_v0.x.x.js
- definitions/npm/storybook-router_v0.x.x/flow_v0.25.x-/test_storybook-router_v0.x.x.js
Following of #2645 where we unify and fix storybook ecosystem (plugins etc.) definitions.
> Update storybook-router definitions

- definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
- definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js
Update jest-enzyme definitions to the latest versions.  
Keep removed matchers for retro-compat.
> Update jest-enzyme definitions

- definitions/npm/a11y-dialog_v5.x.x/flow_v0.25.x-v0.67.1/a11y-dialog_v5.x.x.js
- definitions/npm/a11y-dialog_v5.x.x/flow_v0.68.x-/a11y-dialog_v5.x.x.js
- definitions/npm/a11y-dialog_v5.x.x/flow_v0.68.x-/test_a11y-dialog_v5.x.x.js
- definitions/npm/a11y-dialog_v5.x.x/test_a11y-dialog_v5.x.x.js
See https://github.com/edenspiekermann/a11y-dialog
> Add a11y-dialog definitions

- definitions/npm/nock_v10.x.x/flow_v0.75.x-/nock_v10.x.x.js
- definitions/npm/nock_v10.x.x/test_nock-v10.js
Mainly copy pasted v9
But I removed the $npm$ prefixing by moving everything inside the package.
And I changed the import of EventEmitter (that was resolved to any and didn't work) with events$EventEmitter.
> Add nock v10

- definitions/npm/fs-extra_v7.x.x/flow_all/fs-extra_v7.x.x.js
- definitions/npm/fs-extra_v7.x.x/test_fs-extra_v7.x.x.js
See https://github.com/jprichardson/node-fs-extra
> Add fs-extra definitions

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
if an array, the elements will be model attribute names
> fix(sequelize): fix return type of changed()

- definitions/npm/react-a11y-dialog_v4.1.x/flow_v0.53.x-v0.67.1/react-a11y-dialog_v4.1.x.js
- definitions/npm/react-a11y-dialog_v4.1.x/flow_v0.53.x-v0.67.1/test_react-a11y-dialog_v4.1.x.js
- definitions/npm/react-a11y-dialog_v4.1.x/flow_v0.68.x-/react-a11y-dialog_v4.1.x.js
- definitions/npm/react-a11y-dialog_v4.1.x/flow_v0.68.x-/test_react-a11y-dialog_v4.1.x.js
- definitions/npm/react-a11y-dialog_v4.1.x/test_react-a11y-dialog_v4.1.x.js
See https://github.com/HugoGiraudel/react-a11y-dialog
> Add react-a11y-dialog definitions

- definitions/npm/react-native-simple-store_v1.x.x/flow_v0.25.x-/react-native-simple-store_v1.x.x.js
- definitions/npm/react-native-simple-store_v1.x.x/flow_v0.25.x-/test_react-native-simple-store.js
Add support for react-native-simple-store: https://github.com/jasonmerino/react-native-simple-store
> Add react-native-simple-store definitions

- definitions/npm/glob_v7.1.x/flow_v0.42.x-/glob_v7.1.x.js
- definitions/npm/glob_v7.1.x/test_glob_v7.1.x.js
See https://github.com/isaacs/node-glob
> Add glob definitions

- definitions/npm/sponge_v0.1.x/flow_all/sponge_v0.1.x.js
- definitions/npm/sponge_v0.1.x/test_sponge_v0.1.x.js
See https://github.com/eush77/node-sponge
> Add sponge definitions

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
https://redis.io/commands/incr
https://redis.io/commands/incrby
https://redis.io/commands/incrbyfloat
https://redis.io/commands/decr
https://redis.io/commands/decrby
> [redis] add redis incr/decr commands

- definitions/npm/lolex_v2.x.x/flow_v0.64.x-/lolex_v2.x.x.js
A few tweaks from trying to use this definition.
/cc @marudor @fatso83 @benjamingr
> Tweak Lolex definitions

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
https://redis.io/commands/hincrby
https://redis.io/commands/hincrbyfloat
> [redis] add redis hincrby/hincrbyfloat commands

- definitions/npm/angular_v1.5.x/flow_v0.47.x-/angular_v1.5.x.js
- definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_angular_stateProvider_v1.5.x.js
- definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_angular_v1.5.x.js
- definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_utility_functions_v1.5.x.js
Slightly enhanced angular 1.5 types. E.g fixed forEach, and added $stateProvider.
> Enhance angular 1.5 types

- definitions/npm/moment_v2.x.x/flow_v0.25.x-/moment_v2.x.x.js
- definitions/npm/moment_v2.x.x/test_moment-v2.js
Original PR by @MarcoPolo here https://github.com/flow-typed/flow-typed/pull/2767
> same type as updateLocale (https://momentjs.com/docs/#/customization/)
This PR also includes tests for this new addition.
However, see my question in the original PR before merging this PR: https://github.com/flow-typed/flow-typed/pull/2767#issuecomment-426230438 — please answer my question in there, and I'll then reconsider what I'll do with this PR.
> Update moment js to add defineLocale function (take 2)

- definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
> Add textPrimary as a color option

- definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
Documented here: https://ant.design/components/list/#List.Item.Meta
> Add the missing List.Item.Meta in antd types

- definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js
- definitions/npm/winston_v3.x.x/test_winston_v3.x.x.js
> [winston] add transport level and silent properties

- definitions/npm/file-saver_v2.x.x/flow_v0.25.x-v0.74.x/file-saver_v2.x.x.js
- definitions/npm/file-saver_v2.x.x/flow_v0.75.x-/file-saver_v2.x.x.js
- definitions/npm/file-saver_v2.x.x/test_file-saver_v2.x.x.js
See https://github.com/eligrey/FileSaver.js
> Add file-saver definitions

- definitions/npm/opentok_v2.6.x/flow_v0.61.x-/opentok_v2.6.x.js
For mocking (and not only) purposes it's beneficial to have all of the types available for `import`
> Export all of the OpenTok types

- definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js
[Source](https://github.com/winstonjs/logform/blob/master/metadata.js)
> [winston_v3.x.x] Add 'metadata' type to winstonFormatSubModule

- definitions/npm/slash_v2.x.x/flow_v0.37.x-/slash_v2.x.x.js
- definitions/npm/slash_v2.x.x/test_slash_v2.x.x.js
Add library definitions for `slash`.
See:
- https://github.com/sindresorhus/slash
- https://www.npmjs.com/package/slash
> Add slash definitions

- definitions/npm/multimatch_v2.x.x/flow_v0.37.x-/multimatch_v2.x.x.js
- definitions/npm/multimatch_v2.x.x/test_multimatch_v2.x.x.js
Add library definitions for `multimatch`.
See:
- https://github.com/sindresorhus/multimatch
- https://www.npmjs.com/package/multimatch
> Add multimatch definitions

- definitions/npm/jest_v23.x.x/flow_v0.39.x-/jest_v23.x.x.js
- definitions/npm/jest_v23.x.x/flow_v0.39.x-/test_jest-v23.x.x.js
See https://github.com/FormidableLabs/enzyme-matchers/blob/master/CHANGELOG.md#700
> Update jest-enzyme definitions for version 7.x

- definitions/npm/firebase_v5.x.x/flow_v0.34.x-/firebase_v5.x.x.js
- definitions/npm/firebase_v5.x.x/flow_v0.34.x-/test_firebase.js
add https://firebase.google.com/docs/firestore/query-data/queries#array_membership (array contains) query operator
> add array contains

- definitions/npm/dompurify_v1.x.x/flow_v0.69.x-/dompurify_v1.x.x.js
- definitions/npm/dompurify_v1.x.x/test_dompurify_v1.x.x.js
See https://github.com/cure53/DOMPurify
>  Add typings for DOMPurify

- definitions/npm/moment_v2.x.x/flow_v0.25.x-/moment_v2.x.x.js
- definitions/npm/moment_v2.x.x/test_moment-v2.js
This PR adds all the missing ways to create new moment objects as per https://momentjs.com/docs/#/parsing/ section.
Closes #1673
**This PR is ready for review**
> [moment] Add all the ways to create new moment objects

- definitions/npm/punycode_v2.1.x/flow_v0.30.x-/punycode_v2.1.x.js
- definitions/npm/punycode_v2.1.x/test_punycode_v2.1.x.js
See https://github.com/bestiejs/punycode.js
> Add punycode v2.1.x definitions

- definitions/npm/p-all_v1.x.x/flow_v0.70.x-/p-all_v1.x.x.js
- definitions/npm/p-all_v1.x.x/test_p-all_v1.x.x.js
https://www.npmjs.com/package/p-all
https://github.com/sindresorhus/p-all
> [p-all] Add definitions

- definitions/npm/p-do-whilst_v1.x.x/flow_v0.70.x-/p-do-whilst_v1.x.x.js
- definitions/npm/p-do-whilst_v1.x.x/test_p-do-whilst_v1.x.x.js
https://www.npmjs.com/package/p-do-whilst
https://github.com/sindresorhus/p-do-whilst
> [p-do-whilst] Add definitions

- definitions/npm/p-each-series_v1.x.x/flow_v0.70.x-/p-each-series_v1.x.x.js
- definitions/npm/p-each-series_v1.x.x/test_p-each-series_v1.x.x.js
https://www.npmjs.com/package/p-each-series
https://github.com/sindresorhus/p-each-series
> [p-each-series] Add definitions

- definitions/npm/p-filter_v1.x.x/flow_v0.70.x-/p-filter_v1.x.x.js
- definitions/npm/p-filter_v1.x.x/test_p-filter_v1.x.x.js
https://www.npmjs.com/package/p-filter
https://github.com/sindresorhus/p-filter
> [p-filter] Add definitions

- definitions/npm/p-reduce_v1.x.x/flow_v0.70.x-/p-reduce_v1.x.x.js
- definitions/npm/p-reduce_v1.x.x/test_p-reduce_v1.x.x.js
https://www.npmjs.com/package/p-reduce
https://github.com/sindresorhus/p-reduce
> [p-reduce] Add definitions

- definitions/npm/p-series_v1.x.x/flow_v0.70.x-/p-series_v1.x.x.js
- definitions/npm/p-series_v1.x.x/test_p-series_v1.x.x.js
https://www.npmjs.com/package/p-series
https://github.com/sindresorhus/p-series
> [p-series] Add definitions

- definitions/npm/react-credit-cards_v0.x.x/flow_v0.25.x-/react-credit-cards_v0.x.x.js
- definitions/npm/react-credit-cards_v0.x.x/test_react-credit-cards_v0.x.x.js
Add library definitions for `react-credit-cards`.
- [https://www.npmjs.com/package/react-credit-cards](https://www.npmjs.com/package/react-credit-cards)
- [https://github.com/amarofashion/react-credit-cards](https://github.com/amarofashion/react-credit-cards)
> [react-credit-cards] Add definitions

- definitions/npm/react-truncate_v2.x.x/flow_v0.25.x-/react-truncate_v2.x.x.js
- definitions/npm/react-truncate_v2.x.x/test_react-truncate_v2.x.x.js
Add library definitions for `react-truncate`.
- [https://www.npmjs.com/package/react-truncate](https://www.npmjs.com/package/react-truncate)
- [https://github.com/One-com/react-truncate](https://github.com/One-com/react-truncate)
> [react-truncate] Add definitions

- definitions/npm/react-visibility-sensor_v5.x.x/flow_v0.25.x-/react-visibility-sensor_v5.x.x.js
- definitions/npm/react-visibility-sensor_v5.x.x/test_react-visibility-sensor_v5.x.x.js
Add library definitions for `react-visibility-sensor`.
- [https://www.npmjs.com/package/react-visibility-sensor](https://www.npmjs.com/package/react-visibility-sensor)
- [https://github.com/joshwnj/react-visibility-sensor](https://github.com/joshwnj/react-visibility-sensor)
> [react-visibility-sensor] Add definitions

- definitions/npm/@storybook/addon-links_v3.x.x/flow_v0.25.x-v0.52.x/addon-links_v3.x.x.js
- definitions/npm/@storybook/addon-links_v3.x.x/flow_v0.53.x-/addon-links_v3.x.x.js
- definitions/npm/@storybook/addon-links_v3.x.x/test_addon-links_v3.x.x.js
Following of storybooks/storybook/issues/4104
See https://github.com/storybooks/storybook/blob/release/3.4/addons/links/src/preview.js#L8
> [@storybook/addon-links] Fix linkTo return type

- definitions/npm/react-portal_v4.1.x/flow_v0.30.x-v0.52.x/react-portal_v4.1.x.js
- definitions/npm/react-portal_v4.1.x/flow_v0.53.x-/react-portal_v4.1.x.js
- definitions/npm/react-portal_v4.1.x/test_react-portal_v4.1.x.js
See https://github.com/tajo/react-portal
> Add react-portal definitions

- definitions/npm/nprogress_v0.2.0/flow_v0.25.x-/nprogress_v0.2.0.js
- definitions/npm/nprogress_v0.2.0/test_nprogress.v0.2.0.js
This adds some definitions for [nprogress](https://github.com/rstacruz/nprogress) 🙂
> Add nprogress defs

- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
This PR add required `selector` argument to exists method of Wrapper.
> Add selector argument to exists method (enzyme_v3.x.x.js)

- definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js
Thanks to @Klathmon [here](https://github.com/react-navigation/react-navigation/pull/5074)!
> [react-navigation] Type NavigationScreenProp.getParam

- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/test_enzyme-v3.x.js
Updated def to match docs + implementation (https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/setProps.md)
> [enzyme] Updated definition - Wrapper.setProps

- definitions/npm/match-sorter_v2.3.x/flow_v0.54.1-/match-sorter_v2.3.x.js
- definitions/npm/match-sorter_v2.3.x/test_match-sorter_v2.3.x.js
Changes: https://github.com/kentcdodds/match-sorter/compare/v2.2.3...v2.3.0
> Upgrade match-sorter definitions

- definitions/npm/trim-left_v1.x.x/flow_v0.25.x-/trim-left_v1.x.x.js
- definitions/npm/trim-left_v1.x.x/test_trim-left_v1.x.x.js
- definitions/npm/trim-right_v1.x.x/flow_v0.25.x-/trim-right_v1.x.x.js
- definitions/npm/trim-right_v1.x.x/test_trim-right_v1.x.x.js
1. https://www.npmjs.com/package/trim-left
https://github.com/sindresorhus/trim-left
1. https://www.npmjs.com/package/trim-right
https://github.com/sindresorhus/trim-right
> [trim-left/trim-right]: Add libdefs

- definitions/npm/statuses_v1.5.x/flow_v0.82.x-/statuses_v1.5.x.js
- definitions/npm/statuses_v1.5.x/test_statuses_v1.5.x.js
https://github.com/jshttp/statuses
https://www.npmjs.com/package/statuses
> [statuses] Add libdefs for statuses lib

- definitions/npm/react-modal_v3.6.x/flow_v0.54.1-/react-modal_v3.6.x.js
- definitions/npm/react-modal_v3.6.x/test_react-modal_v3.6.x.js
- Remove `appElement` property
- Add `overlayRef` and `containerRef` ref callbacks
Changes: https://github.com/reactjs/react-modal/compare/v3.1.13...v3.6.1
> Added new react-modal definitions

- definitions/npm/webpack_v4.x.x/flow_v0.71.x-/webpack_v4.x.x.js
- definitions/npm/webpack_v4.x.x/test_webpack_v4.x.x.js
It may be still in WIP, while heavily inspired from the TypeScript declarations
Anyone is welcome to contribute and/or write tests in order to answer to https://github.com/flow-typed/flow-typed/issues/165
> Add flow-typed definitions for Webpack4

- definitions/npm/hoist-non-react-statics_v2.x.x/flow_v0.54.1-/hoist-non-react-statics_v2.x.x.js
- definitions/npm/hoist-non-react-statics_v2.x.x/test_hoist-non-react-statics_v2.x.x.js
See this issue https://github.com/mridgway/hoist-non-react-statics/issues/47
> source and target props do not need to be related

- definitions/npm/react-native-orientation-locker_v1.x.x/flow_v0.72.0-/react-native-orientation-locker_v1.x.x.js
- definitions/npm/react-native-orientation-locker_v1.x.x/flow_v0.72.0-/test_react-native-orientation-locker.js
[react-native-orientation-locker](https://github.com/wonday/react-native-orientation-locker/blob/master/index.js)
> Add react-native-orientation-locker

- definitions/npm/react-with-separator_v1.x.x/flow_v0.72.x-/react-with-separator_v1.x.x.js
- definitions/npm/react-with-separator_v1.x.x/flow_v0.72.x-/test_react-with-separator_v1.x.x.js
Based on https://github.com/LinusU/react-with-separator/blob/v1.1.0/index.d.ts
> [react-with-separator] Add definitions

- definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
- definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js
`Checkbox.Group` is missed in current definition
https://ant.design/components/checkbox/#Checkbox-Group
> add Checkbox.Group in antd types

- definitions/npm/@storybook/react_v4.x.x/flow_v0.25.x-v0.71.x/react_v4.x.x.js
- definitions/npm/@storybook/react_v4.x.x/flow_v0.25.x-v0.71.x/test_react_v4.x.x.js
- definitions/npm/@storybook/react_v4.x.x/flow_v0.72.x-/react_v4.x.x.js
- definitions/npm/@storybook/react_v4.x.x/flow_v0.72.x-/test_react_v4.x.x.js
See https://github.com/storybooks/storybook/blob/next/CHANGELOG.md#400
> Add @storybook/react v4 definitions

- definitions/npm/@storybook/addon-options_v3.x.x/flow_v0.25.x-/addon-options_v3.x.x.js
- definitions/npm/@storybook/addon-options_v3.x.x/test_addon-options_v3.x.x.js
- definitions/npm/@storybook/addon-options_v4.x.x/flow_v0.25.x-/addon-options_v4.x.x.js
- definitions/npm/@storybook/addon-options_v4.x.x/test_addon-options_v4.x.x.js
See 
https://github.com/storybooks/storybook/tree/next/addons/options  
https://storybook.js.org/configurations/theming
> Add  @storybook/addon-options 3x, 4x definitions

- definitions/npm/react-navigation_v3.x.x/CONTRIBUTING.md
- definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-/react-navigation_v3.x.x.js
- definitions/npm/react-navigation_v3.x.x/test_react-navigation.js
You can see just the diff from 2.0 [here](https://github.com/react-navigation/react-navigation/pull/5234)
> [react-navigation] libdef for react-navigation@3.0

- definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
- definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js
Added a definition for Pagination and PaginationProps as found here:
https://ant.design/components/pagination/
> [antd_v3.x.x] Added definition for antd Pagination.

- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js
- definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/test_react-apollo_v2.x.x.js
and make children optional
https://github.com/apollographql/react-apollo/blob/master/src/Subscriptions.tsx#L31
> fix(react-apollo): add onSubscriptionData prop to Subscription (test failures are unrelated)

- definitions/npm/markdown-table_v1.x.x/flow_v0.76.x-/markdown-table_v1.x.x.js
- definitions/npm/markdown-table_v1.x.x/test_markdown-table_v1.x.x.js
Add library definitions for `markdown-table`.
See:
- https://github.com/wooorm/markdown-table
- https://www.npmjs.com/package/markdown-table
> Add markdown-table definitions

- definitions/npm/luxon_v1.x.x/flow_v0.32.0-/luxon_v1.x.x.js
- definitions/npm/luxon_v1.x.x/test_luxon.js
https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromSeconds
> [luxon_v1.x.x] Add DateTime.fromSeconds

- definitions/npm/jquery_v3.x.x/flow_v0.28.x-/jquery_v3.x.x.js
- definitions/npm/jquery_v3.x.x/flow_v0.28.x-/test_jquery.js
Docs: http://api.jquery.com/deferred.catch/
> Add missing jQuery deferred.catch method.

- definitions/npm/koa-bunyan-logger_v2.x.x/flow_v0.39.x-/koa-bunyan-logger_v2.x.x.js
- definitions/npm/koa-bunyan-logger_v2.x.x/test_koa_bunyan_logger_v2.x.x.js
Ref: https://github.com/koajs/bunyan-logger/blob/f8c95ae718dc472eb4ea68f6f055a8839d7d5a70/index.js#L113
> [koa-bunyan-logger_v2.x.x] Make requestLogger options optional

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js
> [sequelize] Add findByPk function to Model (#3033)

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
> [lodash_v4.x.x] use $ReadOnlyArray for uniq*, partition

- definitions/npm/ramda_v0.26.x/CONTRIBUTING.md
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_cjs_modules.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_es_modules.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_filter.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_functions.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_list.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_logic.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_map.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_misc.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_object.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_partial.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_pipe.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_relation.js
- definitions/npm/ramda_v0.x.x/flow_v0.82.x-/ramda_v0.x.x.js
This PR contains a number of items:
- Copying files from 0.x.x to 0.26.x
- Adding a number of new definitions that have been added
- Updated a number of definitions that have changed
- Removed a few definitions that have been removed
Obviously there's a lot going on in this PR, but hopefully, the individual commits will help.
Not all of the items introduced from 0.26 are in here (thunkify, then, otherwise, composeWith, pipeWith are all missing right now).
> [ramda_v0.26.x] Created Ramda 0.26.x defs

- definitions/npm/phoenix_v1.x.x/flow_v0.25.x-/phoenix_v1.x.x.js
- definitions/npm/phoenix_v1.x.x/test_phoenix_v1.x.x.js
This includes definitions for classes documented on
https://hexdocs.pm/phoenix/js/ as well as the undocumented but exported
`LongPoll` class from
https://github.com/phoenixframework/phoenix/blob/v1.4/assets/js/phoenix.js
> [phoenix_v1.x.x] Add initial definitions for Phoenix JS client

- definitions/npm/clsx_v1.x.x/flow_v0.30.x-/clsx_v1.x.x.js
- definitions/npm/clsx_v1.x.x/test_clsx_v1.x.x.js
See https://github.com/lukeed/clsx
> [clsx_v1.x.x] Add definitions

- definitions/npm/testcafe_v0.x.x/flow_v0.63.x-/testcafe_v0.x.x.js
Addresses https://github.com/flow-typed/flow-typed/issues/2827
> [testcafe_v0.x.x] Fix 0.82+ errors

- definitions/npm/ua-parser-js_v0.7.x/flow_v0.42.x-/ua-parser-js_v0.7.x.js
- definitions/npm/ua-parser-js_v0.7.x/test_ua-parser-js_v0.7.x.js
- Links to documentation: https://www.npmjs.com/package/ua-parser-js#constructor
- Link to GitHub or NPM: https://github.com/faisalman/ua-parser-js
- Type of contribution: fix/addition
> [ua-parser-js_v0.7.x] Fix libdefs for missing ua-parser-js API

- definitions/npm/read-last-lines_v1.x.x/flow_v0.25.x-/read-last-lines_v1.x.x.js
- definitions/npm/read-last-lines_v1.x.x/flow_v0.25.x-/test_read-last-lines_v1.x.x.js
Please consider this type definition for read-last-lines. Apologies in advance for missing any details - this is my first pull request.
> libdef and tests for read-last-lines npm module

- definitions/npm/enzyme_v2.3.x/flow_v0.53.x-/enzyme_v2.3.x.js
- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/test_enzyme-v3.x.js
- Links to documentation: https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/instance.md
- Link to GitHub or NPM: https://github.com/airbnb/enzyme
Other notes:
Fix #925
> [enzyme_v3.x.x] Fix instance error

- definitions/npm/react-hot-loader_v4.x.x/flow_v0.53.0-/react-hot-loader_v4.x.x.js
- definitions/npm/react-hot-loader_v4.x.x/flow_v0.53.0-/test_react-hot-loader_4.x.x.js
- Links to documentation: https://github.com/gaearon/react-hot-loader#-hot-labs-
- Link to GitHub or NPM: https://github.com/gaearon/react-hot-loader
Other notes:
https://github.com/gaearon/react-hot-loader/blob/master/src/configuration.js
> [react-hot-loader_v4.x.x]: can use setConfig

- definitions/npm/react-native-video_v4.x.x/flow_v0.77.0-/react-native-video_v4.x.x.js
- definitions/npm/react-native-video_v4.x.x/flow_v0.77.0-/test_react-native-video.js
- Links to documentation: [github/README.md](https://github.com/react-native-community/react-native-video#configurable-props)
- Link to GitHub or NPM: [github](https://github.com/react-native-community/react-native-video/blob/master/Video.js)
- Type of contribution: New definition
> Add new version rn-video

- cli/src/lib/npm/npmLibDefs.js
This attempts to tackle following:
```
$ flow
Launching Flow server for /home/travis/build/flow-typed/flow-typed/cli
Spawned flow server (pid=7028)
Logs will go to /tmp/flow/zShomezStraviszSbuildzSflow-typedzSflow-typedzScli.log
Monitor logs will go to /tmp/flow/zShomezStraviszSbuildzSflow-typedzSflow-typedzScli.monitor_log
No errors!
• Package does not exist on npm!
The command "./travis.sh" exited with 1.
cache.2
store build cache
0.00s32.39schange detected (content changed, file is created, or file is deleted):
/home/travis/.flow-typed/repo/.git/index
/home/travis/.flow-typed/repo/.git/logs/HEAD
/home/travis/.flow-typed/repo/lastUpdated
changes detected, packing new archive
.
.
.
.
.
uploading PR.3109/cache-linux-trusty-fb0a0396fe0487e4eca9a0ba43d3ff58801086c9b57020e080cda1228f0fd9a2--n …
```
> retry once if npm returns 404

- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js
- definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/test_enzyme-v3.x.js
- Links to documentation: https://github.com/airbnb/enzyme/blob/944f9e098bb1978c750525416a18a58c80fbe126/docs/api/ReactWrapper/simulateError.md
- Link to GitHub or NPM: https://github.com/airbnb/enzyme
> [enzyme_v3.x.x]: add simulateError to enzyme_v3.x.x

- definitions/npm/diskusage_v1.x.x/flow_v0.25.x-/diskusage_v1.x.x.js
- definitions/npm/diskusage_v1.x.x/test_diskusage_v1.x.x.js
https://www.npmjs.com/package/diskusage
https://github.com/jduncanator/node-diskusage
> Libdef added for diskusage v1.0.0

- definitions/npm/is-number_v1.x.x/flow_v0.25.x-/is-number_v1.x.x.js
- definitions/npm/is-number_v1.x.x/test_is-number_v1.x.x.js
- Link to GitHub or NPM:  npmjs.com/is-number
> [is-number] Add definitions

- definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/redux-saga_v1.x.x.js
- definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_flush.js
- definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_put.js
- definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_putResolve.js
- definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_take.js
- definitions/npm/redux-saga_v1.x.x/flow_v0.76.0-/test_redux-saga_1.x.x_takeMaybe.js
- Links to documentation: https://github.com/redux-saga/redux-saga/blob/master/packages/core/effects.d.ts
- Link to GitHub or NPM: https://github.com/redux-saga/redux-saga
- Type of contribution:  fix via https://github.com/flow-typed/flow-typed/issues/3111
> redux-saga@1.x.x better support with channels

- definitions/npm/ansi-regex_v4.x.x/flow_v0.25.x-/ansi-regex_v4.x.x.js
- definitions/npm/ansi-regex_v4.x.x/test_ansi-regex.js
- Links to documentation: https://www.npmjs.com/package/ansi-regex#usage
- Link to GitHub or NPM: https://npmjs.com/ansi-regex
> [ansi-regex] Add definitions

- definitions/npm/zxcvbn_v4.x.x/flow_v0.25.x-/zxcvbn_v4.x.x.js
- definitions/npm/zxcvbn_v4.x.x/test_zxcvbn.js
- Links to documentation: https://github.com/dropbox/zxcvbn#usage
- Link to GitHub or NPM: https://github.com/dropbox/zxcvbn
> [zxcvbn] Add definitions

- definitions/npm/source-map_v0.7.x/flow_v0.25.x-/source-map_v0.7.x.js
- definitions/npm/source-map_v0.7.x/test_source-map.js
- Links to documentation: https://github.com/mozilla/source-map#examples
- Link to GitHub or NPM: https://github.com/mozilla/source-map
> [source-map] Add definition

- definitions/npm/@react-navigation/core_v3.x.x/flow_v0.60.x-/core_v3.x.x.js
- definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-/react-navigation_v3.x.x.js
Lots of copy-pasting going on here, unfortunately. Can't wait for #2842 to be resolved.
This is a follow-up from a review comment to #3139.
> [react-navigation] Refine AnimatedValue type

- definitions/npm/@react-navigation/core_v3.x.x/test_core.js
- definitions/npm/react-navigation_v3.x.x/test_react-navigation.js
These tests cover the "core" router functionality.
This is a follow-up from a review comment to #3139.
> [react-navigation] Add tests for routers

- cli/src/lib/npm/npmLibDefs.js
Fixed a couple of linting errors, it was just a matter of `yarn eslint . --fix`.
> Fix broken build

- definitions/npm/node-fetch_v1.x.x/flow_v0.44.x-/node-fetch_v1.x.x.js
- definitions/npm/node-fetch_v1.x.x/test_node-fetch_v1.js
- Links to documentation: n/a
- Link to GitHub or NPM: https://github.com/facebook/flow/pull/7215
Other notes:
Fixes `node-fetch` definition for changes to `http`/`https` modules from facebook/flow#7215.
> Fix node-fetch for flow 0.93.x

- definitions/npm/cssbeautify_v0.3.x/flow_v0.30.x-/cssbeautify_v0.3.x.js
- definitions/npm/cssbeautify_v0.3.x/flow_v0.30.x-/test_cssbeautify_v0.3.x.js
- Links to documentation: https://github.com/senchalabs/cssbeautify
- Link to GitHub or NPM:  https://github.com/senchalabs/cssbeautify
> [cssbeautify_v0.3.x] Add definitions

- definitions/npm/react-test-renderer_v16.x.x/flow_v0.47.x-/react-test-renderer_v16.x.x.js
- definitions/npm/react-test-renderer_v16.x.x/test_react-test-renderer-v16.x.x.js
- Links to documentation: This method is not yet documented but is present in the code: https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactTestRenderer.js#L556
- Link to GitHub or NPM: https://github.com/facebook/react/tree/master/packages/react-test-renderer
> Add act fucntion to react-test-renderer

- definitions/npm/knex_v0.16.x/flow_v0.75.x-/knex_v0.16.x.js
- definitions/npm/knex_v0.16.x/flow_v0.75.x-/test_knex_v0.16.x.js
- Links to documentation: https://knexjs.org/
- Link to GitHub or NPM: https://github.com/tgriesser/knex
Other notes:
I have copied the definitions from v0.15 and added some outstanding changes present in Knex's changelog
> Add knex 0.16

- definitions/npm/mocha_v6.x.x/flow_v0.28.x-/mocha_v6.x.x.js
- definitions/npm/mocha_v6.x.x/test_mocha_v6.x.x_context.js
- definitions/npm/mocha_v6.x.x/test_mocha_v6.x.x_describe.js
- definitions/npm/mocha_v6.x.x/test_mocha_v6.x.x_hooks.js
- definitions/npm/mocha_v6.x.x/test_mocha_v6.x.x_it.js
- Links to documentation: https://github.com/mochajs/mocha
- Link to GitHub or NPM: https://github.com/mochajs/mocha
> [mocha_v6.x] Add definitions for mocha v6 (taken from mocha_v5.x)

- definitions/npm/webpack_v4.x.x/flow_v0.71.x-/webpack_v4.x.x.js
- definitions/npm/webpack_v4.x.x/test_webpack_v4.x.x.js
See https://webpack.js.org/api/node/
- Links to documentation: See https://webpack.js.org/api/node/
- Type of contribution:  addition
> Add more type definitions for node.js api of webpack

- definitions/npm/query-string_v6.x.x/flow_v0.32.x-/query-string_v6.x.x.js
- definitions/npm/query-string_v6.x.x/test_query-string_v6.x.x.js
This fixes a problem with #3114. I think the added test clearly shows the problem, but please ask if you need more information.
> [query-string] Fix a problem with typed query objects

- definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
- definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js
- Links to documentation: https://ant.design/docs/react/introduce
- Link to GitHub or NPM: https://github.com/ant-design/ant-design
Other notes: This PR adds a few missing `antd` components, as well as props for some of them.
> Antd updates

- definitions/npm/use-resize-observer_v3.1.x/flow_v0.90.x-/test_use-resize-observer_v3.1.x.js
- definitions/npm/use-resize-observer_v3.1.x/flow_v0.90.x-/use-resize-observer_v3.1.x.js
- Links to documentation: https://github.com/ZeeCoder/use-resize-observer
- Link to GitHub or NPM: https://github.com/ZeeCoder/use-resize-observer
> [use-resize-observer_v3.1.x] Add definitions

- definitions/npm/remarkable_v1.x.x/flow_v0.28.x-/remarkable_v1.x.x.js
- Link to GitHub or NPM: https://github.com/jonschlinkert/remarkable
> [remarkable_v1.x.x] Export Options type

- definitions/npm/use-react-router_v1.x.x/flow_v0.63.x-/test_use-react-router.js
- definitions/npm/use-react-router_v1.x.x/flow_v0.63.x-/use-react-router_v1.x.x.js
- Links to documentation: n/a
- Link to GitHub or NPM: [use-react-router](https://github.com/CharlesStover/use-react-router)
Other notes:
> Add use-react-router definitions

- definitions/npm/bluebird_v3.x.x/flow_v0.70.x-/bluebird_v3.x.x.js
- Links to documentation: See http://bluebirdjs.com/docs/api/cancellation.html for documentation on his feature.
- Link to GitHub or NPM: https://github.com/petkaantonov/bluebird/blob/master/docs/docs/api/cancellation.md
> Update bluebird def to include `onCancel`

- definitions/npm/react-native-navigation_v2.x.x/flow_v0.91.1-/react-native-navigation_v2.x.x.js
- definitions/npm/react-native-navigation_v2.x.x/flow_v0.91.1-/test_react-native-navigation.js
> [2.x.x] react-native-navigation add types

- definitions/npm/use-debounce_v1.1.x/flow_v0.90.x-/test_use-debounce_v1.1.x.js
- definitions/npm/use-debounce_v1.1.x/flow_v0.90.x-/use-debounce_v1.1.x.js
- Links to documentation: https://github.com/xnimorz/use-debounce
- Link to GitHub or NPM: https://github.com/xnimorz/use-debounce
> [use-debounce_v1.1.x] Add definitions

- definitions/npm/use-onclickoutside_v0.3.x/flow_v0.90.x-/test_use-onclickoutside_v0.3.x.js
- definitions/npm/use-onclickoutside_v0.3.x/flow_v0.90.x-/use-onclickoutside_v0.3.x.js
- Links to documentation: https://github.com/Andarist/use-onclickoutside
- Link to GitHub or NPM: https://github.com/Andarist/use-onclickoutside
> [use-onclickoutside_v0.3.x] Add definitions

- definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
- definitions/npm/antd_v3.x.x/flow_v0.25.x-/test_antd_v3.x.x.js
- Links to documentation: https://ant.design/components/select/
- Link to GitHub or NPM: https://github.com/ant-design/ant-design
Other notes:
> [antd_v3.x.x] Added definitions for Select, SelectOption, SelectOptGroup and AutoComplete.

- definitions/npm/opentok_v2.8.x/flow_v0.61.x-/opentok_v2.8.x.js
- definitions/npm/opentok_v2.8.x/flow_v0.61.x-/test_opentok.js
- Links to documentation: https://tokbox.com/developer/sdks/node/reference/OpenTok.html
- Link to GitHub or NPM: https://github.com/opentok/opentok-node
Other notes:
This is mainly a fork of  `definitions/npm/opentok_v2.6.x` which adds missing and newly added features in OpenTok v2.7 and v2.8.
> [opentok-node] Add OpenTok v2.8 typings and tests

- definitions/npm/clickable-box_v0.1.x/flow_v0.70.x-/clickable-box_v0.1.x.js
- definitions/npm/clickable-box_v0.1.x/flow_v0.70.x-/test_clickable-box_v0.1.x.js
- Links to documentation: https://github.com/danoc/clickable-box
- Link to GitHub or NPM: https://github.com/danoc/clickable-box
> [clickable-box_v0.1.x] Add definitions

- definitions/npm/pell_v1.x.x/flow_v0.69.x-/pell_v1.x.x.js
- definitions/npm/pell_v1.x.x/test_pell_v1.x.x.js
See https://github.com/jaredreich/pell
> [pell_v1.x.x] Add definitions

- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_list.js
- Links to documentation: https://ramdajs.com/docs/
Other notes:
> Improve ramda pluck definition

- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_list.js
Links to documentation: https://ramdajs.com/docs/
Link to GitHub or NPM: https://github.com/ramda/ramda
Other notes:
> Improve ramda head definition

- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_logic.js
Links to documentation: https://ramdajs.com/docs/
Link to GitHub or NPM: https://github.com/ramda/ramda
Other notes:
> Improve ramda propSatisfies definition

- definitions/npm/redux-starter-kit_v0.x.x/flow_v0.89.x-/redux-starter-kit_v0.x.x.js
- definitions/npm/redux-starter-kit_v0.x.x/flow_v0.89.x-/test_action.js
- definitions/npm/redux_v4.x.x/flow_v0.89.x-/redux_v4.x.x.js
- definitions/npm/redux_v4.x.x/flow_v0.89.x-/test_action.js
*[redux_v4.x.x]*
- Links to documentation: https://redux.js.org/
- Link to GitHub or NPM: https://www.npmjs.com/package/redux
[Corresponding type-script definition by redux](https://github.com/reduxjs/redux/blob/fe0ace21910bc596cd8f3ec8ccc78bccdae7d426/index.d.ts#L20)
*[redux-starter-kit_v0.x.x]*
- Links to documentation: https://redux-starter-kit.js.org/
- Link to GitHub or NPM: https://www.npmjs.com/package/redux-starter-kit
[Corresponding type-script definition by redux-starter-kit](https://github.com/reduxjs/redux-starter-kit/blob/6d1f04aa1093df8f9b0133eba9ba73e0c7ed0645/src/createAction.ts#L10)
> [redux_v4.x.x] [redux-starter-kit_v0.x.x] Adds definition for redux and redux-starter-kit actions

- definitions/npm/react-native-navigation_v2.x.x/flow_v0.91.1-/react-native-navigation_v2.x.x.js
> [react-native-navigation_v2] Update defenition to latest version

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js
- Links to documentation: https://lodash.com/docs/4.17.11#take
> take and takeRight can accept $ReadOnlyArray<T>

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js
- Links to documentation: https://github.com/sequelize/sequelize/tree/v4/docs
- Link to GitHub or NPM: https://github.com/sequelize/sequelize
- Type of contribution: fix | refactor
Other notes:
via: https://github.com/flow-typed/flow-typed/issues/3237
> [sequelize_v4] fix: Convert module from ESM to CommonJS

- definitions/npm/react-native-navigation_v2.x.x/flow_v0.91.1-/react-native-navigation_v2.x.x.js
> [react-native-navigation_v2.x.x]: Add new prop `topMargin`

- definitions/npm/mobile-detect_v1.x.x/flow_v0.25.x-/mobile-detect_v1.x.x.js
- Link to GitHub or NPM: https://github.com/hgoebl/mobile-detect.js/blob/master/mobile-detect.d.ts
- Type of contribution: addition 
Other notes:
> [mobile-detect] Add is, match, mobileGrade function definition

- definitions/npm/storeon_v0.x.x/flow_v0.63.x-/storeon_v0.x.x.js
- definitions/npm/storeon_v0.x.x/flow_v0.63.x-/test_storeon.js
- Links to documentation: [Storeon](https://evilmartians.com/chronicles/storeon-redux-in-173-bytes)
- Link to GitHub or NPM: [storeon/storeon](https://github.com/storeon/storeon)
Other notes:
> Add storeon definitions

- definitions/npm/react-native-video_v4.x.x/flow_v0.77.0-/react-native-video_v4.x.x.js
- definitions/npm/react-native-video_v4.x.x/flow_v0.77.0-/test_react-native-video.js
- Links to documentation: https://github.com/react-native-community/react-native-video
- Link to GitHub or NPM: https://github.com/react-native-community/react-native-video
Other notes:
- [controls](https://github.com/react-native-community/react-native-video/pull/1414)
- [pictureInPicture](https://github.com/react-native-community/react-native-video/pull/1325)
- [minLoadRetryCount](https://github.com/react-native-community/react-native-video/commit/420d88d5834eccc69a88e1412b9b57383ba62b39)
> [react-native-video_v4.x.x] Update types

- definitions/npm/react-native-webview_v5.x.x/flow_v0.88.x-/react-native-webview_v5.x.x.js
- definitions/npm/react-native-webview_v5.x.x/flow_v0.88.x-/test_react-native-webview.js
- Links to documentation: https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md
- Link to GitHub or NPM: https://github.com/react-native-community/react-native-webview
Other notes:
Since it was [rewritten to TS](https://github.com/react-native-community/react-native-webview/pull/425), we have lost flow types on the new versions
> [react-native-webview_v5.x.x] Add defenition

- definitions/npm/eventemitter3_v2.x.x/flow_v0.25.x-/eventemitter3_v2.x.x.js
- definitions/npm/eventemitter3_v2.x.x/test_eventemitter3-v2.js
- definitions/npm/eventemitter3_v3.x.x/flow_v0.25.x-/eventemitter3_v3.x.x.js
- definitions/npm/eventemitter3_v3.x.x/test_eventemitter3-v3.js
- Links to documentation: https://github.com/primus/eventemitter3#usage
- Link to GitHub or NPM: https://www.npmjs.com/package/eventemitter3
Other notes:
Problem with `async () => { }` functions https://github.com/flow-typed/flow-typed/issues/3242
> [eventemitter3] Update ListenerFn return type

- definitions/npm/react-native-navigation_v2.x.x/flow_v0.91.1-/react-native-navigation_v2.x.x.js
> [react-native-navigation_v2.x.x]: Add new props leftButtonDisabledColor, rightButtonDisabledColor

- definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
Source code: https://github.com/NodeRedis/node_redis/blob/27bb93ac19157bdc7b7958bef012e4b266d156ae/lib/extendedApi.js#L75-L85
Docs: https://github.com/NodeRedis/node_redis#clientunref
> [redis] Add unref

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js
Reverts flow-typed/flow-typed#3276
> Revert "[sequelize_v4] fix: Convert module from ESM to CommonJS"

- definitions/npm/react-apollo_v2.x.x/CONTRIBUTING.md
- definitions/npm/sequelize_v4.x.x/CONTRIBUTING.md
> docs: add myself as a reviewer to react-apollo and sequelize [ci skip]

- definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
https://github.com/sequelize/sequelize/blob/v4/docs/scopes.md#usage
> fix(sequelize): fix flow errors (remove $Subtype, fix scope function type defs)

- definitions/npm/@reach/router_v1.1.x/flow_v0.63.x-/router_v1.1.x.js
- definitions/npm/@reach/router_v1.1.x/flow_v0.63.x-/test_router_v1.1.x.js
- Links to documentation: https://reach.tech/router
- Link to GitHub or NPM: https://github.com/reach/router/
Other notes:
Rewrote types according to the [source code](https://github.com/reach/router/blob/master/src/index.js)
```js
Router: Class => StatelessFunction
LinkProps: Class => StatelessFunction
Redirect: Class => StatelessFunction
Location: Class => StatelessFunction
ServerLocation: Class => StatelessFunction
```
via: https://github.com/flow-typed/flow-typed/issues/3278
> [@reach/router] Fix class components

- cli/src/commands/__tests__/install-test.js
- cli/src/commands/install.js
- cli/src/lib/cacheRepoUtils.js
- cli/src/lib/npm/npmLibDefs.js
useCacheUntil option to install command, since it is 1 minute by hard coded which isn't good
> useCacheUntil option in install command 

- definitions/npm/expo-camera_v4.x.x/flow_v0.69.0-/expo-camera_v4.x.x.js
- definitions/npm/expo-camera_v4.x.x/flow_v0.69.0-/test_expo-camera.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/camera/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-camera
> [expo-camera_v4.x.x] Add new definition

- definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-/react-native-gesture-handler_v1.x.x.js
- definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-/test_all-gesture-handlers.js
- definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-/test_buttons.js
- definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-/test_drawer-layout.js
- definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-/test_import.js
- definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-/test_swipeable.js
- Links to documentation: https://kmagiera.github.io/react-native-gesture-handler/
- Link to GitHub or NPM: https://github.com/kmagiera/react-native-gesture-handler
> [react-native-gesture-handler_v1.x.x] Add new defenition

- definitions/npm/expo-secure-store_v4.x.x/flow_v0.69.0-/expo-secure-store_v4.x.x.js
- definitions/npm/expo-secure-store_v4.x.x/flow_v0.69.0-/test_expo-secure-store.js
- Links to documentation: https://docs.expo.io/versions/v32.0.0/sdk/securestore/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-secure-store
> [expo-secure-store_v4.x.x] Add new definition

- definitions/npm/expo-file-system_v4.x.x/flow_v0.69.0-/expo-file-system_v4.x.x.js
- definitions/npm/expo-file-system_v4.x.x/flow_v0.69.0-/test_expo-file-system.js
- Links to documentation: https://docs.expo.io/versions/v32.0.0/sdk/filesystem/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-file-system
> [expo-file-system_v4.x.x] Add new definition

- definitions/npm/expo-permissions_v4.x.x/flow_v0.69.0-/expo-permissions_v4.x.x.js
- definitions/npm/expo-permissions_v4.x.x/flow_v0.69.0-/test_expo-permissions.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/permissions/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-permissions
> [expo-permissions_v4.x.x] Add new definition

- definitions/npm/expo-image-picker_v4.x.x/flow_v0.69.0-/expo-image-picker_v4.x.x.js
- definitions/npm/expo-image-picker_v4.x.x/flow_v0.69.0-/test_expo-image-picker.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/imagepicker/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-image-picker
> [expo-image-picker_v4.x.x] Add new definition

- definitions/npm/expo-camera_v4.x.x/flow_v0.69.0-/test_expo-camera.js
- definitions/npm/expo-constants_v4.x.x/flow_v0.69.0-/expo-constants_v4.x.x.js
- definitions/npm/expo-constants_v4.x.x/flow_v0.69.0-/test_expo-constants.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/constants/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-constants
> [expo-constants_v4.x.x] Add new definition

- definitions/npm/expo-asset_v4.x.x/flow_v0.98.0/expo-asset_v4.x.x.js
- definitions/npm/expo-asset_v4.x.x/flow_v0.98.0/test_expo-asset.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/asset/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-asset
> [expo-asset_v4.x.x] Add new definition

- definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-v0.91.x/react-navigation_v3.x.x.js
- definitions/npm/react-navigation_v3.x.x/flow_v0.92.x-/react-navigation_v3.x.x.js
- definitions/npm/react-navigation_v3.x.x/test_react-navigation.js
Corresponding PR in source repo: https://github.com/react-navigation/react-navigation/pull/5918
cc @Ashoat
> [react-navigation_v3.x.x] Update definition for NavigationStackViewConfig

- definitions/npm/react-native-navigation_v2.x.x/flow_v0.91.1-/react-native-navigation_v2.x.x.js
Other notes:
Via: https://github.com/wix/react-native-navigation/pull/5085
> [react-native-navigation_v2.x.x] Update OptionsTopBarBackground

- definitions/npm/react-native-webview_v5.x.x/flow_v0.88.x-/react-native-webview_v5.x.x.js
- definitions/npm/react-native-webview_v5.x.x/flow_v0.88.x-/test_react-native-webview.js
- Links to documentation: https://github.com/react-native-community/react-native-webview/tree/master/docs
- Link to GitHub or NPM: https://www.npmjs.com/package/react-native-webview
- Type of contribution: addition | refactor
Other notes:
> [react-native-webview_v5.x.x] Update types

- definitions/npm/fbt_v0.x.x/flow_v0.69.x-/fbt_v0.x.x.js
- definitions/npm/fbt_v0.x.x/flow_v0.69.x-/test_fbt.js
- Links to documentation: https://facebookincubator.github.io/fbt/docs/api_intro
- Link to GitHub or NPM: https://www.npmjs.com/package/fbt
> [fbt_v0.x.x] Add new definition

- definitions/npm/react-native-navigation_v2.x.x/flow_v0.91.1-/react-native-navigation_v2.x.x.js
Other notes:
Diff: [2.21.0...2.20.0](https://github.com/wix/react-native-navigation/compare/0720bda6...9deb61a)
> [react-native-navigation_v2.x.x] Update types to the latest version

- definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-/react-native-gesture-handler_v1.x.x.js
- Links to documentation: https://kmagiera.github.io/react-native-gesture-handler/
- Link to GitHub or NPM: https://github.com/kmagiera/react-native-gesture-handler
> [react-native-gesture-handler_v1.x.x] Replace any type by component type

- definitions/npm/expo-image-picker_v5.x.x/flow_v0.69.0-/expo-image-picker_v5.x.x.js
- definitions/npm/expo-image-picker_v5.x.x/flow_v0.69.0-/test_expo-image-picker.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/imagepicker/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-image-picker
> [expo-image-picker_v5.x.x] Add new definition

- definitions/npm/@testing-library/react_v8.x.x/flow_v0.67.1-/react_v8.x.x.js
- definitions/npm/@testing-library/react_v8.x.x/flow_v0.67.1-/test_react_v8.x.x.js
- Links to documentation: https://github.com/testing-library/react-testing-library/releases/tag/v8.0.0
Other notes: 
Just a copy of the current `react-testing-library`.
> [@testing-library/react] Add definitions

- definitions/npm/expo-secure-store_v5.x.x/flow_v0.69.0-/expo-secure-store_v5.x.x.js
- definitions/npm/expo-secure-store_v5.x.x/flow_v0.69.0-/test_expo-secure-store.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/securestore/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-secure-store
> [expo-secure-store_v5.x.x] Add new definition

- definitions/npm/expo-file-system_v5.x.x/flow_v0.69.0-/expo-file-system_v5.x.x.js
- definitions/npm/expo-file-system_v5.x.x/flow_v0.69.0-/test_expo-file-system.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/filesystem/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-file-system
> [expo-file-system_v5.x.x] Add new definition

- definitions/npm/expo-constants_v5.x.x/flow_v0.69.0-/expo-constants_v5.x.x.js
- definitions/npm/expo-constants_v5.x.x/flow_v0.69.0-/test_expo-constants.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/constants/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-constants
> [expo-constants_v5.x.x] Add new definition

- definitions/npm/expo-camera_v5.x.x/flow_v0.69.0-/expo-camera_v5.x.x.js
- definitions/npm/expo-camera_v5.x.x/flow_v0.69.0-/test_expo-camera.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/camera/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-camera
> [expo-camera_v5.x.x] Add new definition

- definitions/npm/expo-permissions_v5.x.x/flow_v0.69.0-/expo-permissions_v5.x.x.js
- definitions/npm/expo-permissions_v5.x.x/flow_v0.69.0-/test_expo-permissions.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/permissions/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-permissions
> [expo-permissions_v5.x.x] Add new definition

- definitions/npm/fbt_v0.x.x/flow_v0.69.x-/fbt_v0.x.x.js
- definitions/npm/fbt_v0.x.x/flow_v0.69.x-/test_fbt.js
- Links to documentation: https://facebookincubator.github.io/fbt/docs/api_intro
- Link to GitHub or NPM: https://www.npmjs.com/package/fbt
> [fbt_v0.x.x] Update declaration

- definitions/npm/bem-cn_v3.x.x/flow_v0.90.x-/bem-cn_v3.x.x.js
- definitions/npm/bem-cn_v3.x.x/flow_v0.90.x-/test_bem-cn_v3.x.x.js
- Links to documentation: https://github.com/albburtsev/bem-cn#api
- Link to GitHub or NPM: https://www.npmjs.com/package/bem-cn
> [bem-cn_v3.x.x] Add new definition

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js
* `pick` accepts a string
* change `Array<string>` to `$ReadOnlyArray<string>`
> pick accepts a string for 1 property only

- CONTRIBUTING.md
> Fix read-only array type name

- README.md
> Add Discord server badge

- definitions/npm/downshift_v3.x.x/flow_v0.69.0-/downshift_v3.x.x.js
- definitions/npm/downshift_v3.x.x/flow_v0.69.0-/test_downshift.js
- Links to documentation: https://github.com/downshift-js/downshift
- Link to GitHub or NPM: https://www.npmjs.com/package/downshift
> [downshift_v3.x.x] Add new definition

- definitions/npm/webpack_v4.x.x/flow_v0.71.x-/webpack_v4.x.x.js
- definitions/npm/webpack_v4.x.x/test_webpack_v4.x.x.js
- Links to documentation: https://webpack.js.org/plugins/environment-plugin/
- Link to GitHub or NPM: https://github.com/webpack/webpack
Other notes:
> [webpack] Add EnvironmentPlugin

- definitions/npm/url-join_v4.x.x/flow_v0.25.x-/url-join_v4.x.x.js
- definitions/npm/url-join_v4.x.x/test_url-join_v4.x.x.js
- Links to documentation: https://www.npmjs.com/package/url-join
- Link to GitHub or NPM: https://www.npmjs.com/package/url-join
Other notes:
> ✨ add libdef for url-join_v4.x.x

- definitions/npm/antd_v3.x.x/flow_v0.25.x-/antd_v3.x.x.js
Add [notification](https://ant.design/components/notification/) types. 
Antd doc: https://ant.design/components/notification/
Mostly c/p from ts sources: https://github.com/ant-design/ant-design/blob/master/components/notification/index.tsx
Checked by local apply to `flow-typed/antd_v3.x.x.x.js`
> Update antd_v3.x.x.js add notification

- definitions/npm/redux-handlers_v1.x.x/flow_v0.82.x-/redux-handlers_v1.x.x.js
- definitions/npm/redux-handlers_v1.x.x/flow_v0.82.x-/test_redux-handlers_v1.x.x.js
- Links to documentation: https://github.com/AndrewSouthpaw/redux-handlers
- Link to GitHub or NPM: https://github.com/AndrewSouthpaw/redux-handlers
Other notes:
It's for a library I wrote! 🙌
> Add new redux-handlers library.

- definitions/npm/fbemitter_v2.x.x/flow_v0.25.x-/fbemitter_v2.x.x.js
- definitions/npm/fbemitter_v2.x.x/flow_v0.25.x-/test_fbemitter.js
- Links to documentation: https://github.com/facebook/emitter
- https://www.npmjs.com/package/fbemitter
- https://github.com/facebook/emitter
> Add fbemitter types

- definitions/npm/lockfile_v1.x.x/flow_v0.47.x-/lockfile_v1.x.x.js
- definitions/npm/lockfile_v1.x.x/flow_v0.47.x-/test_lockfile_v1.x.x.js
- Links to documentation: https://github.com/npm/lockfile#methods
- Link to GitHub or NPM: https://github.com/npm/lockfile
- Type of contribution: addition && fix
**Other notes**: 
Looks like when these were first added, some methods and signatures were omitted (hence this is more of a fix than an addition). I based these on the types in the README + the existing (up-to-date) `DefinitelyTyped` TS types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lockfile/index.d.ts
First time contributing to flow-typed, so please let me know if there's anything I missed. Thanks!
> Update lockfile definitions

- definitions/npm/which_v1.x.x/flow_v0.75.x-/which_v1.x.x.js
> [which_v1.x.x] Fix indentation

- definitions/npm/rxjs_v6.x.x/flow_v0.34.x-v0.71.x/rxjs_v6.x.x.js
- definitions/npm/rxjs_v6.x.x/flow_v0.72.x-/rxjs_v6.x.x.js
- definitions/npm/rxjs_v6.x.x/flow_v0.72.x-/test_operator_takeWhile.js
- Links to documentation: https://www.learnrxjs.io/operators/filtering/takewhile.html
- Link to GitHub or NPM: https://github.com/ReactiveX/rxjs/pull/4115/files
> Add inclusive paramter to takeWhile predicate

- cli/src/commands/install.js
- cli/src/commands/runTests.js
> Use plural messages

- cli/src/commands/install.js
> Add choices to ignoreDeps option

- definitions/npm/chai_v3.5.x/flow_v0.25.0-/chai_v3.5.x.js
- definitions/npm/chai_v4.x.x/flow_v0.53.0-/chai_v4.x.x.js
- definitions/npm/chai_v4.x.x/test_chai_v4.x.x.js
Hello,
I'd like to submit some minor fixes and additions on chai libdef:
- Add expect.fail and expect().instanceOf()
- length is similar to contain/include (tests were previously failing on that one)
- Type of contribution: addition | fix
Thanks
> [chai_v4.x.x] Update definitions

- definitions/npm/parsehttpdate_v1.x.x/flow_v0.25.x-/parsehttpdate_v1.x.x.js
- definitions/npm/parsehttpdate_v1.x.x/test_parsehttpdate_v1.x.x.js
- Links to documentation: https://github.com/Pimm/parseHttpDate#usage
- Link to GitHub or NPM: https://github.com/Pimm/parseHttpDate
Other notes: please let me know if anything can be improved.
> [parsehttpdate_v1.x.x] Added definition.

- definitions/npm/mapsort_v1.x.x/flow_v0.25.x-/mapsort_v1.x.x.js
- definitions/npm/mapsort_v1.x.x/test_mapsort_v.1.x.x.js
- Links to documentation: https://github.com/Pimm/mapsort#usage
- Link to GitHub or NPM: https://github.com/Pimm/mapsort
> [mapsort_v1.x.x] Added definition.

- definitions/npm/use-clipboard-copy_v0.1.x/flow_v0.90.x-/test_use-clipboard-copy_v0.1.x.js
- definitions/npm/use-clipboard-copy_v0.1.x/flow_v0.90.x-/use-clipboard-copy_v0.1.x.js
- Links to documentation: https://github.com/wsmd/use-clipboard-copy/blob/master/README.md
- Link to GitHub or NPM: https://github.com/wsmd/use-clipboard-copy
> [use-clipboard-copy_v0.1.x] Add definitions

- definitions/npm/jest_v24.x.x/flow_v0.39.x-/jest_v24.x.x.js
- Links to documentation: https://github.com/testing-library/jest-dom/blob/master/extend-expect.d.ts
> [jest_v24.x.x][jest-dom_v4.x.x] Update definitions

- definitions/npm/@testing-library/jest-dom_v4.x.x/flow_v0.80.x-/jest-dom_v4.x.x.js
- definitions/npm/@testing-library/jest-dom_v4.x.x/flow_v0.80.x-/test_jest-dom_v4.x.x.js
* https://github.com/testing-library/jest-dom/blob/master/extend-expect.d.ts
* https://github.com/testing-library/jest-dom/blob/master/README.md#usage
> [@testing-library/jest-dom_v4.x.x] Add definitions

- definitions/npm/just-safe-get_v1.3.x/flow_v0.98.x-/just-safe-get_v1.3.x.js
- definitions/npm/just-safe-get_v1.3.x/test_just-safe-get_v1.3.x.js
- Links to documentation: [README.md](https://github.com/angus-c/just/blob/master/packages/object-safe-get/README.md)
- Link to GitHub or NPM: [GitHub](https://github.com/angus-c/just) | [NPM](https://www.npmjs.com/package/just-safe-get)
- Type of contribution: **new definition** | addition | fix | refactor
> [just-safe-get_v1.3.x] Add new type definitions

- definitions/npm/locale_v0.1.x/flow_v0.74.x-/locale_v0.1.x.js
- Links to documentation: [README.md](https://github.com/florrain/locale/blob/master/README.md)
- Link to GitHub or NPM: [GitHub](https://github.com/florrain/locale) | [NPM](https://www.npmjs.com/package/locale)
- Type of contribution: new definition | addition | **fix** | refactor
Other notes:
Existing type definition doesn't take into account the case where a collection of supported `Locales` is provided in determining the "best" `Locale` to use.  See [lib/index.js](https://github.com/florrain/locale/blob/master/lib/index.js#L104) for more details.
> [locale_v0.1.x] Update definition

- definitions/npm/just-safe-set_v2.1.x/flow_v0.98.x-/just-safe-set_v2.1.x.js
- definitions/npm/just-safe-set_v2.1.x/test_just-safe-set_v2.1.x.js
- Links to documentation: [README.md](https://github.com/angus-c/just/blob/master/packages/object-safe-set/README.md)
- Link to GitHub or NPM: [GitHub](https://github.com/angus-c/just) | [NPM](https://www.npmjs.com/package/just-safe-set)
- Type of contribution: **new definition** | addition | fix | refactor
> [just-safe-set_v2.1.x] Add new type definitions

- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/react-redux_v6.x.x.js
- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/test_Provider.js
- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/test_connect.js
- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/test_connectAdvanced.js
- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/test_connectDispatch.js
- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/test_connectHOC.js
- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/test_connectInfer.js
- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/test_connectMergeProps.js
- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/test_connectState.js
- definitions/npm/react-redux_v6.x.x/flow_v0.89.x-/test_connectThunk.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/react-redux_v7.x.x.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_Provider.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_connect.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_connectAdvanced.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_connectDispatch.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_connectHOC.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_connectInfer.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_connectMergeProps.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_connectState.js
- definitions/npm/react-redux_v7.x.x/flow_v0.89.x-/test_connectThunk.js
- Links to documentation: https://github.com/reduxjs/react-redux
- Link to GitHub or NPM: https://github.com/reduxjs/react-redux
Other notes:
Doesn't address some of the new hooks support, just wanted to get something out there to support the majority of use cases. Can be refined later.
Closes #3439
> Add react-redux v6 and v7 libdefs.

- definitions/npm/expo-constants_v4.x.x/flow_v0.69.0-/expo-constants_v4.x.x.js
- definitions/npm/expo-constants_v5.x.x/flow_v0.69.0-/expo-constants_v5.x.x.js
- Links to documentation: https://docs.expo.io/versions/latest/sdk/constants/
- Link to GitHub or NPM: https://www.npmjs.com/package/expo-constants
Other notes:
Docs: https://github.com/expo/expo/blob/15a6137ec46d840e53d1d98b03637f829b4d44dc/docs/pages/versions/v33.0.0/distribution/release-channels.md#access-channel-from-code
Issue: https://github.com/flow-typed/flow-typed/issues/3441
> [expo-constants_v5.x.x] Add releaseChannel prop to manifest

- definitions/npm/formik_v2.x.x/flow_v0.69.0-/formik_v2.x.x.js
- Links to documentation: https://github.com/jaredpalmer/formik/tree/next/docs/api
- Link to GitHub or NPM: https://www.npmjs.com/package/formik
> [formik_v2.x.x] Update definition to the latest version (2.0.1-rc.11)

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js
https://lodash.com/docs/4.17.14#debounce
https://lodash.com/docs/4.17.14#throttle
Other notes:
> [lodash_v4.x.x] Debounced functions missing cancel and flush methods (#3336)

- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/ramda_v0.26.x.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-/test_ramda_v0.26.x_list.js
Links to documentation: https://ramdajs.com/docs/
Link to GitHub or NPM: https://github.com/ramda/ramda
Type of contribution: FIX
> [ramda] improve append function

- ISSUE_TEMPLATE.md
Related #3413
Follow up of #3418
> feat(chore): create issue template

- definitions/npm/redux-reactors_v1.x.x/flow_v0.95.x-/redux-reactors_v1.x.x.js
- definitions/npm/redux-reactors_v1.x.x/flow_v0.95.x-/test_redux-reactors_v1.x.x.js
- definitions/npm/redux-reactors_v1.x.x/test_redux-reactors_v1.x.x.js
- Links to documentation: [README.md](https://github.com/ganemone/redux-reactors/blob/master/README.md)
- Link to GitHub or NPM: [GitHub](https://github.com/ganemone/redux-reactors) | [NPM](https://www.npmjs.com/package/redux-reactors)
- Type of contribution: **new definition** | addition | fix | refactor
FYI @ganemone
> [redux-reactors_v1.x.x] Add type definitions 

- definitions/npm/koa_v2.x.x/flow_v0.94.x-/koa_v2.x.x.js
- Links to documentation: [README](https://github.com/koajs/koa/blob/master/Readme.md)
- Link to GitHub or NPM: [GitHub](https://github.com/koajs/koa) | [NPM](https://www.npmjs.com/package/koa)
- Type of contribution: new definition | addition | **FIX** | refactor
Other notes:
Give more appropriate object types to Koa
> [koa_v2.x.x.js] Update object types

- definitions/npm/phoenix_v1.4.x/flow_v0.25.x-/phoenix_v1.4.x.js
- definitions/npm/phoenix_v1.4.x/test_phoenix_v1.4.x.js
- Links to documentation: https://phoenixframework.org
- Link to GitHub or NPM: https://github.com/phoenixframework/phoenix
Other notes:
flowgen Typescript conversion
> [phoenix_v1.4.x] add new type definitions

- cli/src/commands/runTests.js
> [CLI] Fix runTests on Windows

- definitions/npm/universal-router_v8.x.x/flow_v0.90.x-/test_universal-router_v8.x.x.js
- definitions/npm/universal-router_v8.x.x/flow_v0.90.x-/universal-router_v8.x.x.js
- Links to documentation: [README.md](https://github.com/kriasoft/universal-router/blob/master/README.md) [api](https://github.com/kriasoft/universal-router/blob/master/docs/api.md)
- Link to GitHub or NPM: https://github.com/kriasoft/universal-router/
> [universal-router_v8.x.x] Add new type definitions

- definitions/npm/jest_v24.x.x/flow_v0.39.x-/jest_v24.x.x.js
- definitions/npm/jest_v24.x.x/flow_v0.39.x-/test_jest-v24.x.x.js
- Links to documentation: https://github.com/facebook/jest/blob/4a7b28c9ecc26736de680c21cd1f783543ca4be9/packages/jest-jasmine2/src/jasmineAsyncInstall.ts#L21-L24
> [jest_v24.x.x] Add done.fail() method

- definitions/npm/jest_v24.x.x/flow_v0.104.x-/jest_v24.x.x.js
- definitions/npm/jest_v24.x.x/flow_v0.104.x-/test_jest-v24.x.x.js
- definitions/npm/jest_v24.x.x/flow_v0.39.x-v0.103.x/jest_v24.x.x.js
- definitions/npm/jest_v24.x.x/flow_v0.39.x-v0.103.x/test_jest-v24.x.x.js
- Links to documentation: https://jestjs.io/docs/en
- Link to GitHub or NPM: https://www.npmjs.com/package/jest
> [jest_v24.x.x] Fix tests errors

- definitions/npm/react-native-webview_v6.x.x/flow_v0.104.x-/react-native-webview_v6.x.x.js
- definitions/npm/react-native-webview_v6.x.x/flow_v0.104.x-/test_react-native-webview.js
- definitions/npm/react-native-webview_v6.x.x/flow_v0.88.x-v0.103.x/react-native-webview_v6.x.x.js
- definitions/npm/react-native-webview_v6.x.x/flow_v0.88.x-v0.103.x/test_react-native-webview.js
- Links to documentation: https://github.com/react-native-community/react-native-webview/tree/master/docs
- Link to GitHub or NPM: https://www.npmjs.com/package/react-native-webview
> [react-native-webview_v6.x.x] Add new definition

- definitions/npm/bson_v1.x.x/flow_v0.104.x-/bson_v1.x.x.js
- definitions/npm/bson_v1.x.x/flow_v0.50.x-v0.103.x/bson_v1.x.x.js
Fix `Object` is `any` problems
> [bson_v1.x.x] Fix tests errors 

- definitions/npm/mysql_v2.x.x/flow_v0.104.x-/mysql_v2.x.x.js
- definitions/npm/mysql_v2.x.x/flow_v0.28.x-v0.103.x/mysql_v2.x.x.js
> [mysql_v2.x.x] Fix tests errors 

- definitions/npm/moment_v2.x.x/flow_v0.104.x-/moment_v2.x.x.js
- definitions/npm/moment_v2.x.x/flow_v0.25.x-v0.103.x/moment_v2.x.x.js
> [moment_v2.x.x] Fix tests errors 

- definitions/npm/history_v4.9.x/flow_v0.25.x-v0.103.x/history_v4.9.x.js
- definitions/npm/history_v4.9.x/flow_v0.25.x-v0.103.x/test_history_v4.9.x.js
- Links to documentation:[Docs](https://reacttraining.com/react-router/web/api/history)
- Link to GitHub or NPM: [GitHub](https://github.com/ReactTraining/history)
- Type of contribution: new definition | addition | **FIX** | refactor
> [history_v4.9.x] Convert to Maybe types

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-v0.103.x/lodash_v4.x.x.js
These methods do not modify the input array.
> lodash: More methods that take $ReadOnlyArray instead of Array

- definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.104.x-/test_lodash-v4.x.x.js
- Links to documentation: https://lodash.com/docs/4.17.15#chunk
> chunk can accept $ReadOnlyArray<T>

- definitions/npm/remarkable_v2.x.x/flow_v0.104.x-/remarkable_v2.x.x.js
- definitions/npm/remarkable_v2.x.x/test_remarkable_v2.x.x.js
- Link to GitHub or NPM: https://github.com/jonschlinkert/remarkable
Other notes:
Copy from 1.x plus minor updates/additions.
> [remarkable_v2.x.x] Update definitions for v2.x.x

- definitions/npm/react-native-webview_v6.x.x/flow_v0.104.x-/react-native-webview_v6.x.x.js
- definitions/npm/react-native-webview_v6.x.x/flow_v0.88.x-v0.103.x/react-native-webview_v6.x.x.js
- Links to documentation: https://github.com/react-native-community/react-native-webview/tree/master/docs
- Link to GitHub or NPM: https://www.npmjs.com/package/react-native-webview
Other notes:
https://github.com/react-native-community/react-native-webview/pull/567
https://github.com/react-native-community/react-native-webview/pull/730
> [react-native-webview_v6.x.x] Update types

- definitions/npm/parse-decimal-number_v1.x.x/flow_v0.25.x-/parse-decimal-number_v1.x.x.js
- definitions/npm/parse-decimal-number_v1.x.x/flow_v0.25.x-/test_parse-decimal-number_v1.x.x.js
> [parse-decimal-number] Add definition

- definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-v0.88.x/core_v1.x.x.js
> [meterial-ui] Updating refs

- definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/react_v8.x.x.js
- Links to documentation: https://github.com/testing-library/react-testing-library/blob/master/typings/index.d.ts
> [@testing-library/react_v8.x.x] Update render function definitions

- definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/react_v9.x.x.js
- definitions/npm/@testing-library/react_v9.x.x/flow_v0.104.x-/test_react_v9.x.x.js
- Links to documentation: https://github.com/testing-library/react-testing-library
Other notes:
Just a copy for now
> [@testing-library/react_v9.x.x] Copy from v8.x.x

- definitions/npm/react-native-navigation_v3.x.x/flow_v0.104.x-/react-native-navigation_v3.x.x.js
- definitions/npm/react-native-navigation_v3.x.x/flow_v0.104.x-/test_react-native-navigation.js
- definitions/npm/react-native-navigation_v3.x.x/flow_v0.91.1-v0.103.x/react-native-navigation_v3.x.x.js
- definitions/npm/react-native-navigation_v3.x.x/flow_v0.91.1-v0.103.x/test_react-native-navigation.js
Other notes:
via: https://github.com/wix/react-native-navigation/pull/5372
> [react-native-navigation_v3.x.x] Add new definition

- definitions/npm/backbone-collection_v1.x.x/flow_v0.104.x-/backbone-collection_v1.x.x.js
- definitions/npm/backbone-collection_v1.x.x/flow_v0.25.x-v0.74.x/backbone-collection_v1.x.x.js
- definitions/npm/backbone-collection_v1.x.x/flow_v0.75.x-v0.103.x/backbone-collection_v1.x.x.js
- definitions/npm/backbone-model_v1.x.x/flow_v0.104.x-/backbone-model_v1.x.x.js
- definitions/npm/backbone-model_v1.x.x/flow_v0.25.x-v0.74.x/backbone-model_v1.x.x.js
- definitions/npm/backbone-model_v1.x.x/flow_v0.75.x-v0.103.x/backbone-model_v1.x.x.js
- definitions/npm/backbone_v1.x.x/flow_v0.104.x-/backbone_v1.x.x.js
- definitions/npm/backbone_v1.x.x/flow_v0.25.x-v0.41.x/backbone_v1.x.x.js
- definitions/npm/backbone_v1.x.x/flow_v0.42.x-v0.103.x/backbone_v1.x.x.js
Links to documentation:
- returns from set: https://backbonejs.org/docs/backbone.html#section-123
- add: https://backbonejs.org/docs/backbone.html#section-113
- reset: https://backbonejs.org/docs/backbone.html#section-123
- remove: https://backbonejs.org/docs/backbone.html#section-114
Link to GitHub: https://github.com/jashkenas/backbone/
> Fix Backbone Collection methods

- definitions/npm/react-native-onesignal_v3.x.x/flow_v0.104.x-/react-native-onesignal_v3.x.x.js
- definitions/npm/react-native-onesignal_v3.x.x/flow_v0.104.x-/test_react-native-onesignal.js
- definitions/npm/react-native-onesignal_v3.x.x/flow_v0.69.0-v0.103.x/react-native-onesignal_v3.x.x.js
- definitions/npm/react-native-onesignal_v3.x.x/flow_v0.69.0-v0.103.x/test_react-native-onesignal.js
- Links to documentation: https://documentation.onesignal.com/docs/react-native-sdk
- Link to GitHub or NPM: https://github.com/geektimecoil/react-native-onesignal
- Type of contribution: addition | refactor
> [react-native-onesignal_3.x.x] Update types

- definitions/npm/sinon_v7.x.x/flow_v0.28.x/sinon_v7.x.x.js
- definitions/npm/sinon_v7.x.x/test_sinon_v7.x.x.js
- Links to documentation: https://github.com/sinonjs/sinon
Other notes:
> [sinon_v7.x.x] Adds type definitions

- definitions/npm/sinon_v7.x.x/flow_v0.80.x-/sinon_v7.x.x.js
- definitions/npm/sinon_v7.x.x/test_sinon_v7.x.x.js
Other notes:
- Still fixing errors
> [sinon_v7.x.x] Changes to support Flow >= 0.80.x for sinon types

- CONTRIBUTING.md
> Adds some minor clarifications to Contribution guide

- definitions/npm/tape-cup_v4.7.x/flow_v0.104.x-/tape-cup_v4.7.x.js
- definitions/npm/tape-cup_v4.7.x/flow_v0.74.x-v0.103.x/tape-cup_v4.7.x.js
- Link to GitHub or NPM: [npm](https://www.npmjs.com/package/tape-cup)
- Type of contribution: new definition | **ADDITION** | fix | refactor
Other notes:
This package is inactive, but this is a nice type to have exported for test helpers
> [tape-cup_v4.7.x] Expose TestCb type

- definitions/npm/formik_v2.x.x/flow_v0.104.x-/formik_v2.x.x.js
- definitions/npm/formik_v2.x.x/flow_v0.69.0-v0.103.x/formik_v2.x.x.js
- Links to documentation: https://github.com/jaredpalmer/formik/tree/next/docs/api
- Link to GitHub or NPM: https://www.npmjs.com/package/formik
> [formik_v2.x.x] Update definition to the latest version (2.0.1-rc.13)

- definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.104.x-/react-native-gesture-handler_v1.x.x.js
- definitions/npm/react-native-gesture-handler_v1.x.x/flow_v0.88.0-v0.103.x/react-native-gesture-handler_v1.x.x.js
- Links to documentation: https://kmagiera.github.io/react-native-gesture-handler/
- Link to GitHub or NPM: https://github.com/kmagiera/react-native-gesture-handler
> [react-native-gesture-handler_v1.x.x] Update definition to the latest version (1.4.0) 

- definitions/npm/@apollo/react-hoc_v3.x.x/CONTRIBUTING.md
- definitions/npm/@apollo/react-hoc_v3.x.x/flow_v0.104.x-/react-hoc_v3.x.x.js
- definitions/npm/@apollo/react-hoc_v3.x.x/flow_v0.104.x-/test_react-hoc_v3.x.x.js
- definitions/npm/@apollo/react-hoc_v3.x.x/flow_v0.58.x-v0.103.x/react-hoc_v3.x.x.js
- definitions/npm/@apollo/react-hoc_v3.x.x/flow_v0.58.x-v0.103.x/test_react-hoc_v3.x.x.js
- Links to documentation: https://www.apollographql.com/docs/react/api/react-hoc/
- Link to GitHub or NPM: https://www.npmjs.com/package/@apollo/react-hoc
Other notes:
> Add types for @apollo/react-hoc

- definitions/npm/ajv_v6.x.x/flow_v0.75.x-/ajv_v6.x.x.js
- definitions/npm/ajv_v6.x.x/test_ajv_v6.x.x.js
> [ajv_v6] Add definition for ajv v6

- definitions/npm/lodash_v4.x.x/flow_v0.63.x-v0.103.x/lodash_v4.x.x.js
> Lodash: Changes to XOR that take $ReadOnlyArray instead of Array

- definitions/npm/@apollo/react-components_v3.x.x/CONTRIBUTING.md
- definitions/npm/@apollo/react-components_v3.x.x/flow_v0.104.x-/react-components_v3.x.x.js
- definitions/npm/@apollo/react-components_v3.x.x/flow_v0.104.x-/test_react-components_v3.x.x.js
- definitions/npm/@apollo/react-components_v3.x.x/flow_v0.58.x-v0.103.x/react-components_v3.x.x.js
- definitions/npm/@apollo/react-components_v3.x.x/flow_v0.58.x-v0.103.x/test_react-components_v3.x.x.js
- Links to documentation: https://www.apollographql.com/docs/react/api/react-components/
- Link to GitHub or NPM: https://www.npmjs.com/package/@apollo/react-components
Other notes:
> Add type definitions for @apollo/react-components

- definitions/npm/pem-jwk_v2.x.x/flow_v0.104.x-/pem-jwk_v2.x.x.js
- definitions/npm/pem-jwk_v2.x.x/flow_v0.99.x-/pem-jwk_v2.x.x.js
- definitions/npm/pem-jwk_v2.x.x/test_pem-jwk_v2.x.x.js
> [pem-jkw_v2] Add defintion for pem-jwk v2

- definitions/npm/memory-cache_v0.x.x/flow_v0.104.x-/memory-cache_v0.x.x.js
- definitions/npm/memory-cache_v0.x.x/flow_v0.99.x-/memory-cache_v0.x.x.js
- definitions/npm/memory-cache_v0.x.x/test_memeroy-cache_v0.x.x.js
> [memory-cache_v0] Add definitions for memory-cache

- definitions/npm/execa_v2.x.x/flow_v0.104.x-/execa_v2.x.x.js
- definitions/npm/execa_v2.x.x/test_execa_v2.x.x.js
> [execa_v2] Add definition for execa_v2

- definitions/npm/blue-tape_v1.x.x/flow_v0.104.x-/blue-tape_v1.x.x.js
- definitions/npm/blue-tape_v1.x.x/test_blue-tape_v1.x.x.js
> [blue-tape_v1] Add definition for blue-tape

- definitions/npm/react-jss_v7.x.x/flow_v0.53.x-/react-jss_v7.x.x.js
- definitions/npm/react-jss_v7.x.x/test_react-jss_v7.x.x.js
> [react-jss_v7] Update react-jss for new flow versions

- definitions/npm/react-router_v5.x.x/flow_v0.104.x-/react-router_v5.x.x.js
- definitions/npm/react-router_v5.x.x/flow_v0.104.x-/test_react-router.js
- definitions/npm/react-router_v5.x.x/flow_v0.63.x-v0.103.x/react-router_v5.x.x.js
- definitions/npm/react-router_v5.x.x/flow_v0.63.x-v0.103.x/test_react-router.js
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/matchPath.md 
https://github.com/ReactTraining/react-router/pull/6809
- Link to GitHub or NPM: https://github.com/ReactTraining/react-router
> [react-router_v5.x.x.js] Update matchPath to accept path array

- definitions/npm/execa_v2.x.x/flow_v0.104.x-/execa_v2.x.x.js
- definitions/npm/execa_v2.x.x/test_execa_v2.x.x.js
- Links to documentation: https://github.com/sindresorhus/execa#cancel
- Link to GitHub or NPM: https://github.com/sindresorhus/execa
> [execa_v2.x.x] Add cancel to execa

- definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-v0.88.x/core_v1.x.x.js
Adds flow definitions for the `OutlinedInput` component of Material UI (very similar to #3551, sorry for the duplicate 😬)
- Links to documentation: https://material-ui.com/api/outlined-input/
- Link to GitHub or NPM: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/OutlinedInput/OutlinedInput.js
> [@material-ui/core@1.x.x] Add OutlinedInput defs

- definitions/npm/webpack_v4.x.x/flow_v0.104.x-/webpack_v4.x.x.js
- definitions/npm/webpack_v4.x.x/flow_v0.71.x-v0.103.x/webpack_v4.x.x.js
- definitions/npm/webpack_v4.x.x/test_webpack_v4.x.x.js
- Links to documentation: https://webpack.js.org/api/node/#error-handling
- Link to GitHub or NPM: https://github.com/webpack/webpack
> [webpack_v4.x.x] fix webpack type error with WebpackError

- definitions/npm/react-use_v10.x.x/flow_v0.101.x-/react-use_v10.x.x.js
- definitions/npm/react-use_v10.x.x/test_react-use_v10.x.x.js
Following of https://github.com/flow-typed/flow-typed/pull/3487 (stalled).
> [react-use_v10.x.x] Init with few supported hooks

- definitions/npm/tabbable_v3.x.x/flow_v0.104.x-/tabbable_v3.x.x.js
- definitions/npm/tabbable_v3.x.x/flow_v0.54.x-v0.103.x/tabbable_v3.x.x.js
- definitions/npm/tabbable_v3.x.x/test_tabbable_v3.x.x.js
Following of https://github.com/flow-typed/flow-typed/pull/3320
> [tabbable_v3.x.x] Change tabbable types from Node to HTMLElement 

- definitions/npm/sinon_v7.x.x/flow_v0.80.x-/sinon_v7.x.x.js
- definitions/npm/sinon_v7.x.x/test_sinon_v7.x.x.js
- Links to documentation: https://sinonjs.org/releases/v7.4.2/
- Link to GitHub or NPM: https://github.com/sinonjs/sinon
Other notes:
Fixes https://github.com/flow-typed/flow-typed/issues/3547.
> Add more sinon 7 definitions

- definitions/npm/react-router-dom_v5.x.x/flow_v0.104.x-/react-router-dom_v5.x.x.js
- definitions/npm/react-router-dom_v5.x.x/flow_v0.104.x-/test_react-router-dom.js
- definitions/npm/react-router-dom_v5.x.x/flow_v0.63.x-v0.97.x/react-router-dom_v5.x.x.js
- definitions/npm/react-router-dom_v5.x.x/flow_v0.63.x-v0.97.x/test_react-router-dom.js
- definitions/npm/react-router-dom_v5.x.x/flow_v0.98.x-v0.103.x/react-router-dom_v5.x.x.js
- definitions/npm/react-router-dom_v5.x.x/flow_v0.98.x-v0.103.x/test_react-router-dom.js
react-router-dom: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/matchPath.md
react-router: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/matchPath.md 
- Link to GitHub or NPM: https://github.com/ReactTraining/react-router
Other notes:
This PR simply extends https://github.com/flow-typed/flow-typed/pull/3545.
> [react-router-dom_v5.x.x.js] Update matchPath to accept path array

- definitions/npm/styled-components_v4.x.x/flow_v0.104.x-/styled-components_v4.x.x.js
- definitions/npm/styled-components_v4.x.x/flow_v0.104.x-/test_styled-components_v4.x.x.js
- Links to documentation: https://www.styled-components.com/docs/api#attrs
- Link to GitHub or NPM: https://github.com/styled-components/styled-components
/cc @omninonsense
> [styled-components_4.x.x] add `.attrs` support

- definitions/npm/history_v4.10.x/flow_v0.104.x-/history_v4.10.x.js
- definitions/npm/history_v4.10.x/flow_v0.104.x-/test_history_v4.10.x.js
- Link to GitHub: https://github.com/ReactTraining/history/tree/v4.10.1
> [history_v4.10.x] Add type definitions

- definitions/npm/@reach/dialog_v0.2.x/flow_v0.84.x-/dialog_v0.2.x.js
- definitions/npm/@reach/dialog_v0.2.x/flow_v0.84.x-/test_dialog_v0.2.x.js
- definitions/npm/@reach/portal_v0.2.x/flow_v0.84.x-/portal_v0.2.x.js
- definitions/npm/@reach/portal_v0.2.x/flow_v0.84.x-/test_portal_v0.2.x.js
- definitions/npm/@reach/rect_v0.2.x/flow_v0.84.x-/rect_v0.2.x.js
- definitions/npm/@reach/rect_v0.2.x/flow_v0.84.x-/test_rect_v0.2.x.js
- Links to documentation: https://ui.reach.tech/rect
- Link to GitHub or NPM: https://github.com/reach/reach-ui/tree/master/packages/rect
- Links to documentation: https://ui.reach.tech/portal
- Link to GitHub or NPM: https://github.com/reach/reach-ui/tree/master/packages/portal
- Links to documentation: https://ui.reach.tech/dialog
- Link to GitHub or NPM: https://github.com/reach/reach-ui/tree/master/packages/dialog
> Add definitions for a few reach-ui packages

- definitions/npm/@apollo/react-common_v3.x.x/flow_v0.104.x-/react-common_v3.x.x.js
- definitions/npm/@apollo/react-common_v3.x.x/flow_v0.104.x-/test_react-common_v3.x.x.js
- Links to documentation: https://www.apollographql.com/docs/react/api/react-common/
- Link to GitHub or NPM: https://github.com/apollographql/react-apollo/tree/master/packages/common
> [@apollo/react-common_v3.x.x] add type definitions

- definitions/npm/antd_v3.x.x/flow_v0.104.x-/antd_v3.x.x.js
- definitions/npm/antd_v3.x.x/flow_v0.104.x-/test_antd_v3.x.x.js
- Links to documentation: https://ant.design/components/message/#Global-static-methods
- Link to GitHub or NPM: https://github.com/ant-design/ant-design/blob/master/components/message/index.tsx#L148
> [antd_v3.x.x] Add message.destroy

- definitions/npm/winston_v3.x.x/flow_v0.104.x-/winston_v3.x.x.js
- definitions/npm/winston_v3.x.x/flow_v0.34.x-v0.103.x/winston_v3.x.x.js
- definitions/npm/winston_v3.x.x/test_winston_v3.x.x.js
- Links
https://github.com/winstonjs/winston
- Type of contribution: addition and fix
Changes:
- close() method added to winston logger and container
- return type fixed for winston logger methods log(), add(), remove(), clear()
> Winston methods definition updated

- cli/package.json
- cli/src/lib/npm/__tests__/npmLibDefs-test.js
- cli/src/lib/npm/npmLibDefs.js
Signed-off-by: Kirill Danshin <kirill@danshin.pro>
- Links to documentation: –
- Link to GitHub or NPM: –
Other notes:
> fix git package support; fixes #3363

- definitions/npm/color-string_v1.x.x/flow_v0.84.x-/color-string_v1.x.x.js
- definitions/npm/color-string_v1.x.x/flow_v0.84.x-/test_color-string_v1.x.x.js
- Links to documentation: https://www.npmjs.com/package/color-string#usage
- Link to GitHub or NPM: https://www.npmjs.com/package/color-string
> Add definitions for color-string@1.x.x

- definitions/npm/@react-navigation/core_v3.x.x/flow_v0.104.x-/core_v3.x.x.js
- definitions/npm/@react-navigation/core_v3.x.x/flow_v0.60.x-v0.91.x/core_v3.x.x.js
- definitions/npm/@react-navigation/core_v3.x.x/flow_v0.92.x-v0.103.x/core_v3.x.x.js
- definitions/npm/react-navigation-stack_v1.x.x/flow_v0.104.x-/react-navigation-stack_v1.x.x.js
- definitions/npm/react-navigation-stack_v1.x.x/flow_v0.92.x-v0.103.x/react-navigation-stack_v1.x.x.js
- definitions/npm/react-navigation_v1.x.x/flow_v0.104.x-/react-navigation_v1.x.x.js
- definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-v0.103.x/react-navigation_v1.x.x.js
- definitions/npm/react-navigation_v2.x.x/flow_v0.104.x-/react-navigation_v2.x.x.js
- definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-v0.103.x/react-navigation_v2.x.x.js
- definitions/npm/react-navigation_v3.x.x/flow_v0.104.x-/react-navigation_v3.x.x.js
- definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-v0.91.x/react-navigation_v3.x.x.js
- definitions/npm/react-navigation_v3.x.x/flow_v0.92.x-v0.103.x/react-navigation_v3.x.x.js
- definitions/npm/react-navigation_v4.x.x/flow_v0.104.x-/react-navigation_v4.x.x.js
- definitions/npm/react-navigation_v4.x.x/flow_v0.92.x-v0.103.x/react-navigation_v4.x.x.js
- Links to documentation: https://reactnavigation.org/docs/en/stack-navigator.html
- Link to GitHub or NPM: https://github.com/react-navigation/react-navigation
Other notes:
Fix the issue https://github.com/react-navigation/react-navigation/issues/6384
[Sandbox link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgByAhgG4CWA5sRuXAHYDKGxAxgNaOsBOee9AeRy0GAZzABeMAG9UYeWAAWeYgBM83AEJt2AFXIYYeAPwAuMMdEZu5epQA0CuWAC+AbnSsxGMPTJUaOkFhIPEpAApZBV9-ahF6e2cXcyiFPwo4oPMBACMAKzxWDET5FwBKcxIMwIZmHS5efiF4sIA+GWd5XgwAV256Duj5ZTUNbQ59Qzxzeh6YGEcwTtcPUrcgA)
> fix error for headerBackTitle type in NavigationStackScreenOptions

- definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js
- definitions/npm/lodash_v4.x.x/flow_v0.63.x-v0.103.x/lodash_v4.x.x.js
- Links to documentation: N/A (all current libdefs)
- Link to GitHub or NPM: N/A (all current libdefs)
> [lodash_v4.x.x] make fromPairs definitions stricter

- definitions/npm/koa-logger_v3.2.x/flow_v0.53.x-/koa-logger_v3.2.x.js
- definitions/npm/koa-logger_v3.2.x/test_koa-logger.js
- Links to documentation: https://github.com/koajs/logger
- Link to GitHub or NPM: https://github.com/koajs/logger
> Add koa-logger libdef

- definitions/npm/http-status-codes_v1.x.x/flow_v0.25.0-/http-status-codes_v1.x.x.js
- definitions/npm/http-status-codes_v1.x.x/flow_v0.25.0-/test_http-status-codes_v1.x.x.js
- Links to documentation: [Update of library](https://github.com/prettymuchbryce/http-status-codes/compare/edd12d38580538ad890316e02459a23ca2019cd8...32a4c30c557e8e820e321c25b701f35e9fc22eb6)
- Link to GitHub or NPM: https://github.com/prettymuchbryce/http-status-codes
Other notes:
> [http-status-codes] Add new function definition

- cli/yarn.lock
Reverts flow-typed/flow-typed#3619
Looks like this may have broken the build...
> Revert "Bump fstream from 1.0.11 to 1.0.12 in /cli"

- definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js
> Update Lodash for Pull Methods

- definitions/npm/long_v4.x.x/flow_v0.104.x-/long_v4.x.x.js
- definitions/npm/long_v4.x.x/test_long_v4.x.x.js
- Links to documentation: https://www.npmjs.com/package/long
- Link to GitHub or NPM: https://www.npmjs.com/package/long
Other notes:
> Add long package definitions

- definitions/npm/@reach/router_v1.1.x/flow_v0.104.x-/router_v1.1.x.js
- definitions/npm/@reach/router_v1.1.x/flow_v0.104.x-/test_router_v1.1.x.js
- definitions/npm/@reach/router_v1.1.x/flow_v0.63.x-v0.103.x/router_v1.1.x.js
- definitions/npm/@reach/router_v1.1.x/flow_v0.63.x-v0.103.x/test_router_v1.1.x.js
- Links to documentation: https://reach.tech/router/api/navigate
- Link to GitHub or NPM: https://www.npmjs.com/package/@reach/router
- Type of contribution:  addition
Other notes:
https://github.com/flow-typed/flow-typed/issues/3646
> @reach/router added state to DomLocation and Redirect props

- definitions/npm/ramda_v0.26.x/flow_v0.104.x-/ramda_v0.26.x.js
- definitions/npm/ramda_v0.26.x/flow_v0.104.x-/test_ramda_v0.26.x_list.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/ramda_v0.26.x.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/test_ramda_v0.26.x_list.js
- Links to documentation: https://ramdajs.com/docs#uniq
Other notes:
* change input of uniq to be read only array
> change input of uniq to be read only array (#1)

- definitions/npm/@koa/cors_v3.x.x/flow_v0.53.x-/cors_v3.x.x.js
- definitions/npm/@koa/cors_v3.x.x/test_cors_v3.js
- Links to documentation: https://github.com/koajs/cors
- Link to GitHub or NPM: https://github.com/koajs/cors
> Add the libdef for @koa/cors

- definitions/npm/koa-json-body_v5.x.x/flow_v0.53.x-/koa-json-body_v5.x.x.js
- definitions/npm/koa-json-body_v5.x.x/test_koa-json-body_v5.js
- Links to documentation: https://github.com/venables/koa-json-body
- Link to GitHub or NPM: https://github.com/venables/koa-json-body
> Add libdefs for koa-json-body

- definitions/npm/content-type_v1.x.x/flow_v0.84.x-/content-type_v1.x.x.js
- definitions/npm/content-type_v1.x.x/test_content-type.js
- Links to documentation: https://www.npmjs.com/package/content-type
- Link to GitHub or NPM: https://www.npmjs.com/package/content-type
> Add the content-type libdef

- definitions/npm/query-string_v6.x.x/flow_v0.104.x-/query-string_v6.x.x.js
- definitions/npm/query-string_v6.x.x/flow_v0.32.x-v0.103.x/query-string_v6.x.x.js
**- Links to documentation:** https://github.com/sindresorhus/query-string#readme
**- Link to GitHub or NPM**: https://github.com/sindresorhus/query-string
**- Type of contribution:** addition/fix
> Add 'comma' array format support to query-string

- definitions/npm/ramda_v0.26.x/flow_v0.104.x-/ramda_v0.26.x.js
- definitions/npm/ramda_v0.26.x/flow_v0.104.x-/test_ramda_v0.26.x_list.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/ramda_v0.26.x.js
- definitions/npm/ramda_v0.26.x/flow_v0.76.x-v0.103.x/test_ramda_v0.26.x_list.js
- Links to documentation: https://ramdajs.com/docs/#adjust
Other notes:
> Allow 'adjust' to accept read only input array

- definitions/npm/jasmine_v2.4.x/flow_v0.104.x-/jasmine_v2.4.x.js
see https://jasmine.github.io/api/2.6/matchers.html#toContain
> [jasmine_v2.4.x] Fix toContain matcher

- definitions/npm/@sinonjs/fake-timers_v6.x.x/flow_v0.104.x-/fake-timers_v6.x.x.js
- definitions/npm/@sinonjs/fake-timers_v6.x.x/flow_v0.104.x-/test_fake-timers_v6.x.x.js
- Links to documentation: https://github.com/sinonjs/fake-timers
- Link to GitHub or NPM: https://github.com/sinonjs/fake-timers
Other notes: Essentially a copy of `lolex_v2.x.x` plus several additions and fixes.
https://github.com/sinonjs/fake-timers/blob/master/CHANGELOG.md#600--2020-02-04
> [@sinonjs/fake-timers] Add definitions

- definitions/npm/winston_v3.x.x/flow_v0.104.x-/test_winston_v3.x.x_format.js
- definitions/npm/winston_v3.x.x/flow_v0.104.x-/test_winston_v3.x.x_profiler.js
- definitions/npm/winston_v3.x.x/flow_v0.104.x-/winston_v3.x.x.js
- Link to GitHub or NPM: https://github.com/winstonjs/winston & https://github.com/winstonjs/logform
> [winston] add profiler definitions

- definitions/npm/node-fetch_v2.x.x/flow_v0.104.x-/node-fetch_v2.x.x.js
- definitions/npm/node-fetch_v2.x.x/flow_v0.104.x-/test_node-fetch_v2.x.x_init.js
- [Options](https://github.com/node-fetch/node-fetch#options)
- [Custom Agent](https://github.com/node-fetch/node-fetch#custom-agent)
- [FetchError](https://github.com/node-fetch/node-fetch/blob/master/src/fetch-error.js)
- [AbortError](https://github.com/node-fetch/node-fetch/blob/master/src/abort-error.js)
- [AbortController](https://www.npmjs.com/package/abort-controller) implementing [WHATWG AbortController interface](https://dom.spec.whatwg.org/#interface-abortcontroller)
- Link to GitHub or NPM: https://github.com/node-fetch/node-fetch
> [node-fetch] Fix init options

- definitions/npm/mongodb_v3.5.x/flow_v0.114.x-/mongodb_v3.5.x.js
- definitions/npm/mongodb_v3.5.x/flow_v0.114.x-/test_mongodb_v3.5.x_docs_quick_start.js
- Links to documentation: http://mongodb.github.io/node-mongodb-native/3.5/
- Link to GitHub or NPM: https://github.com/mongodb/node-mongodb-native
> [mongodb_v3.5.x] Initial definition

- definitions/npm/jest_v20.x.x/flow_v0.104.x-/jest_v20.x.x.js
- definitions/npm/jest_v22.x.x/flow_v0.104.x-/jest_v22.x.x.js
- definitions/npm/jest_v23.x.x/flow_v0.104.x-/jest_v23.x.x.js
- definitions/npm/jest_v25.x.x/flow_v0.104.x-/jest_v25.x.x.js
- definitions/npm/jest_v25.x.x/flow_v0.104.x-/test_jest-v25.x.x.js
- definitions/npm/jest_v25.x.x/flow_v0.39.x-v0.103.x/jest_v25.x.x.js
- definitions/npm/jest_v25.x.x/flow_v0.39.x-v0.103.x/test_jest-v25.x.x.js
- Links to documentation: https://jestjs.io/docs/en
- Link to GitHub or NPM:  https://www.npmjs.com/package/jest
Other notes:
Fix previous version error, too.
> [jest_v25.x.x] Add new version

- cli/src/commands/install.js
To support just `--overwrite` instead of `--overwrite true`
> Fix --overwrite option type

- definitions/npm/mongodb_v3.5.x/flow_v0.114.x-/mongodb_v3.5.x.js
- definitions/npm/mongodb_v3.5.x/flow_v0.114.x-/test_mongodb_v3.5.x_client.js
- Links to documentation: http://mongodb.github.io/node-mongodb-native/3.5/api/MongoClient.html#.connect
Other notes:
> [mongodb] type connect method

- definitions/npm/uuid_v7.x.x/flow_v0.104.x-/test_uuid_v7.x.x.js
- definitions/npm/uuid_v7.x.x/flow_v0.104.x-/uuid_v7.x.x.js
- Link to GitHub or NPM: https://github.com/uuidjs/uuid
> Add uuid v7.x.x definition

- definitions/npm/@reach/tooltip_v0.8.x/flow_v0.84.x-/test_tooltip_v0.8.x.js
- definitions/npm/@reach/tooltip_v0.8.x/flow_v0.84.x-/tooltip_v0.8.x.js
> @reach/tooltip_v0.8.x added

- definitions/npm/@sentry/integrations_v5.x.x/flow_v0.84-/integrations_v5.x.x.js
- definitions/npm/@sentry/integrations_v5.x.x/test_integrations_v5.x.x.js
https://docs.sentry.io/platforms/javascript/#pluggable-integrations
https://github.com/getsentry/sentry-javascript/blob/5.12.3/packages/integrations/src/index.ts
The documentation is incomplete, so this is largely based on the TypeScript definitions linked above.
> Add libdefs & tests for @sentry/integrations@5.x.x

- definitions/npm/twitter-text_v3.x.x/flow_v0.104.x-/twitter-text_v3.x.x.js
- definitions/npm/twitter-text_v3.x.x/test_twitter-text_v3.js
- Links to documentation: https://developer.twitter.com/en/docs/developer-utilities/twitter-text
- Link to GitHub or NPM: https://www.npmjs.com/package/twitter-text
Other notes:
~I haven't gotten around to writing tests but I figured it would be better to get feedback of the type definitions first.~ Added tests for the primary functions.
> Add twitter-text_v3.x.x

- definitions/npm/ramda_v0.x.x/flow_v0.104.x-/ramda_v0.x.x.js
- Links to documentation: https://ramdajs.com/docs/#includes
- Type of contribution: **addition**
> Add includes function to Ramda

- definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/react_v10.x.x.js
- definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/test_react_v10.x.x.js
https://github.com/testing-library/react-testing-library/releases/tag/v10.0.0  
https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0
https://github.com/testing-library/dom-testing-library/blob/98e5bb320d8c9d3532ef9d8f8f1e1152fee38acb/src/wait-for.js#L11-L23  
https://github.com/testing-library/dom-testing-library/blob/98e5bb320d8c9d3532ef9d8f8f1e1152fee38acb/src/wait-for-element-to-be-removed.js#L44
Other notes:
Separated in two commit: clone, updates.
> [@testing-library/react_v10.x.x] Add definitions

- definitions/npm/zen-observable_v0.8.x/flow_v0.104.x-/test_zen-observable.js
- definitions/npm/zen-observable_v0.8.x/flow_v0.104.x-/zen-observable_v0.8.x.js
- definitions/npm/zen-observable_v0.8.x/flow_v0.69.0-v0.103.x/test_zen-observable.js
- definitions/npm/zen-observable_v0.8.x/flow_v0.69.0-v0.103.x/zen-observable_v0.8.x.js
- Links to documentation: https://github.com/zenparsing/zen-observable 
- Link to GitHub or NPM: https://github.com/zenparsing/zen-observable
> feat: add zen-observable defs

- cli/.eslintrc
- cli/.prettierrc
- cli/package.json
- cli/yarn.lock
> build: fix eslint/prettier integration

- definitions/npm/big.js_v4.x.x/flow_v0.104.x-/big.js_v4.x.x.js
- definitions/npm/big.js_v4.x.x/flow_v0.25.x-v0.103.x/big.js_v4.x.x.js
- definitions/npm/big.js_v4.x.x/test_big.js_v4.x.x.js
- definitions/npm/big.js_v5.x.x/flow_v0.104.x-/big.js_v5.x.x.js
- definitions/npm/big.js_v5.x.x/flow_v0.25.x-v0.103.x/big.js_v5.x.x.js
- definitions/npm/big.js_v5.x.x/test_big.js_v5.x.x.js
- Links to documentation:  https://github.com/MikeMcl/big.js
- Link to GitHub or NPM: https://github.com/MikeMcl/big.js
> [big.js] Add definitions for v4 and v5

- definitions/npm/dayjs_v1.x.x/flow_v0.104.x-/dayjs_v1.x.x.js
- definitions/npm/dayjs_v1.x.x/test_dayjs_v1.x.x.js
> Add dayjs definition

- definitions/npm/ava_v2.x.x/flow_v0.104.x-/ava_v2.x.x.js
- definitions/npm/ava_v2.x.x/flow_v0.104.x-/test_ava.js
Continuation of https://github.com/flow-typed/flow-typed/pull/3629
> [ava_v2] Add definition for ava

- definitions/npm/compression_v1.x.x/flow_v0.100.x-/compression_v1.x.x.js
- definitions/npm/compression_v1.x.x/flow_v0.100.x-/test_compression.js
Updated version of https://github.com/flow-typed/flow-typed/pull/3379
> [compression_v1] Add types for compression

- definitions/npm/firebase-functions_v1.x.x/flow_v0.104.x-/firebase-functions_v1.x.x.js
- definitions/npm/firebase-functions_v1.x.x/test_https_trigger.js
> [firebase-functions] Add defs for firebase-functions_v1

- definitions/npm/prettier_v1.x.x/flow_v0.104.x-/prettier_v1.x.x.js
- Link to GitHub or NPM:  https://prettier.io/docs/en/api.html#prettiergetfileinfofilepath--options
- Type of contribution:  addition
Other notes:
> add prettier.getFileInfo

- definitions/npm/hex-to-rgb_v1.x.x/flow_v0.25.x-/hex-to-rgb_v1.x.x.js
- definitions/npm/hex-to-rgb_v1.x.x/test_hex-to-rgb_v1.x.x.js
- Link to GitHub or NPM: https://www.npmjs.com/package/hex-to-rgb
Other notes:
> Add defs for hex-to-rgb

- definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/react_v10.x.x.js
- definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/test_react_v10.x.x.js
Clean up a few other things to reflect more closely to the public Type Definitions
- Links to documentation: https://testing-library.com/docs/dom-testing-library/api-queries#findby
- Link to GitHub or NPM: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__dom
- Type of contribution: fix | refactor
> [@testing-library/react_v10.x.x] Add missing find* queries

- definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/react_v10.x.x.js
- definitions/npm/@testing-library/react_v10.x.x/flow_v0.104.x-/test_react_v10.x.x.js
- definitions/npm/@testing-library/react_v8.x.x/flow_v0.104.x-/react_v8.x.x.js
- definitions/npm/@testing-library/react_v8.x.x/flow_v0.67.1-v0.103.x/react_v8.x.x.js
- Links to documentation: https://testing-library.com/docs/dom-testing-library/api-queries#screen
[`screen`](https://github.com/testing-library/dom-testing-library/blob/master/src/screen.js)
see [Typescript `screen.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__dom/screen.d.ts)
[`waitForElementToBeRemoved`](https://testing-library.com/docs/dom-testing-library/api-async#waitforelementtoberemoved)
see [Typescript `wait-for-element-to-be-removed.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/testing-library__dom/wait-for-element-to-be-removed.d.ts)
- Type of contribution: addition | fix
Other notes:
Backported fixes to previous versions for accuracy and passing tests.
> Add missing exports @testing library/react

- definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js
- Links to documentation: [here](https://gist.github.com/jfmengels/6b973b69c491375117dc#_differencewithcomparator-array-values)
Other notes:
> fix typos in lodash/fp libdef

- definitions/npm/react-test-renderer_v16.x.x/flow_v0.104.x-/react-test-renderer_v16.x.x.js
Closes flow-typed/flow-typed/issues/3814
> react-test-renderer act can return promise void

- definitions/npm/jest_v25.x.x/flow_v0.39.x-v0.103.x/jest_v25.x.x.js
Other notes:
The previous edit was confirmed without testing it before.
> Fix jest type definitions for 0.39.x - 0.103.x

- definitions/npm/local-storage-es5_v2.x.x/flow_v0.25.x-/local-storage-es5_v2.x.x.js
- definitions/npm/local-storage-es5_v2.x.x/test_local-storage-es5_v2.x.x.js
- Link to GitHub or NPM: https://www.npmjs.com/package/local-storage-es5
Other notes:
> add local-storage-es5

- definitions/npm/jest_v25.x.x/flow_v0.104.x-/jest_v25.x.x.js
- definitions/npm/jest_v25.x.x/flow_v0.104.x-/test_jest-v25.x.x.js
- Links to documentation: https://github.com/testing-library/jest-dom/releases
Other notes: See #3817
> [jest_v25.x.x] Update @testing-library/jest-dom matchers

- definitions/npm/jest_v26.x.x/flow_v0.104.x-/jest_v26.x.x.js
- definitions/npm/jest_v26.x.x/flow_v0.104.x-/test_jest-v26.x.x.js
https://github.com/facebook/jest/blob/master/CHANGELOG.md  
https://jestjs.io/blog/2020/05/05/jest-26
Other notes:
Split into two commits, clone from 25.x, additions.
> [jest_26.x.x] Add definitions

- definitions/npm/nanoid_v3.x.x/flow_v0.104.x-/nanoid_v3.x.x.js
- definitions/npm/nanoid_v3.x.x/test_nanoid_v3.x.x.js
- definitions/npm/nanoid_v3.x.x/test_nanoid_v3.x.x_async.js
- definitions/npm/nanoid_v3.x.x/test_nanoid_v3.x.x_non-secure.js
- Links to documentation: https://github.com/ai/nanoid#api
- Link to GitHub or npm: https://github.com/ai/nanoid
> [nanoid_v3.x.x] Add definitions

- definitions/npm/confetti-js_v0.0.x/flow_v0.25.x-/confetti-js_v0.0.x.js
- definitions/npm/confetti-js_v0.0.x/flow_v0.25.x-/test_confetti-js_v0.0.x.js
- Links to documentation: https://github.com/Agezao/confetti-js
- Link to GitHub or NPM: https://www.npmjs.com/package/confetti-js
Other notes:
> add confetti-js types

- definitions/npm/yargs_v15.x.x/flow_v0.118.x-/yargs_v15.x.x.js
- definitions/npm/yargs_v15.x.x/test_yargs.js
- Links to documentation: https://yargs.js.org/docs/
- Link to GitHub or NPM: https://github.com/yargs/yargs
Other notes:
This is based off the existing yargs v10 library definitions, but has corrections and additions.
> add yargs v15.x.x

- definitions/npm/react-select_v1.x.x/flow_v0.104.x-/react-select_v1.x.x.js
- definitions/npm/react-select_v1.x.x/flow_v0.53.x-v0.103.x/react-select_v1.x.x.js
- Links to documentation: https://github.com/JedWatson/react-select/blob/v1.3.0/README.md#L147
- Link to GitHub or NPM: https://github.com/JedWatson/react-select/blob/v1.3.0/src/Async.js#L9
> Add 'cache' prop for 'react-select_v1.x.x'

- definitions/npm/chroma-js_v2.x.x/flow_v0.104.x-/chroma-js_v2.x.x.js
- definitions/npm/chroma-js_v2.x.x/flow_v0.104.x-/test_chroma-js.js
Based on TypeScript definitions.
- Links to documentation: https://gka.github.io/chroma.js/#api
- Link to GitHub or NPM: https://github.com/gka/chroma.js
> Add libdefs for chroma-js 2.x.x

- definitions/npm/prosemirror-model_v1.x.x/flow_v0.104.x-/prosemirror-model_v1.x.x.js
- definitions/npm/prosemirror-model_v1.x.x/flow_v0.59.x-v0.103.x/prosemirror-model_v1.x.x.js
- Links to documentation: https://prosemirror.net/docs/ref/#model.Node.descendants
- Link to GitHub or NPM: https://github.com/ProseMirror/prosemirror-model/blob/0a1decebf98c4c3cb4926b848d569ce4b7dfa2ff/src/node.js#L87
> fix(prosemirror-model): Spelling mistake descendents -> descendants

- definitions/npm/binary-search_v1.3.x/flow_v0.59.0-/binary-search_v1.3.x.js
- definitions/npm/binary-search_v1.3.x/test_binary-search_v1.3.x.js
- Links to documentation: https://github.com/darkskyapp/binary-search#binary-search
- Link to GitHub or NPM: https://github.com/darkskyapp/binary-search
> [binary-search_v1.3.x] Add definitions

- definitions/npm/bluebird_v3.x.x/flow_v0.104.x-/test_bluebird_v3.x.x.js
I just fixed the error suppression pragmas and made the tests pass.
> Fix error suppression pragmas in bluebird libdefs

- definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-/react_v11.x.x.js
- definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-/test_react_v11.x.x.js
- Links to documentation: https://github.com/testing-library/react-testing-library/releases/tag/v11.0.0
Other notes:
- Split into two commits, clone from previous version and update.  
- Updated tests suppression comments for the 11.x version
> [@testing-library/react_v11.x.x] Add definitions 

- definitions/npm/@react-navigation/core_v3.x.x/flow_v0.104.x-/core_v3.x.x.js
- definitions/npm/@react-navigation/core_v3.x.x/flow_v0.60.x-v0.91.x/core_v3.x.x.js
- definitions/npm/@react-navigation/core_v3.x.x/flow_v0.92.x-v0.103.x/core_v3.x.x.js
- definitions/npm/react-navigation-drawer_v2.x.x/flow_v0.104.x-/react-navigation-drawer_v2.x.x.js
- definitions/npm/react-navigation-drawer_v2.x.x/flow_v0.92.x-v0.103.x/react-navigation-drawer_v2.x.x.js
- definitions/npm/react-navigation-stack_v1.x.x/flow_v0.104.x-/react-navigation-stack_v1.x.x.js
- definitions/npm/react-navigation-stack_v1.x.x/flow_v0.92.x-v0.103.x/react-navigation-stack_v1.x.x.js
- definitions/npm/react-navigation-tabs_v2.x.x/flow_v0.104.x-/react-navigation-tabs_v2.x.x.js
- definitions/npm/react-navigation-tabs_v2.x.x/flow_v0.92.x-v0.103.x/react-navigation-tabs_v2.x.x.js
- definitions/npm/react-navigation_v1.x.x/flow_v0.104.x-/react-navigation_v1.x.x.js
- definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-v0.103.x/react-navigation_v1.x.x.js
- definitions/npm/react-navigation_v2.x.x/flow_v0.104.x-/react-navigation_v2.x.x.js
- definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-v0.103.x/react-navigation_v2.x.x.js
- definitions/npm/react-navigation_v3.x.x/flow_v0.104.x-/react-navigation_v3.x.x.js
- definitions/npm/react-navigation_v3.x.x/flow_v0.60.x-v0.91.x/react-navigation_v3.x.x.js
- definitions/npm/react-navigation_v3.x.x/flow_v0.92.x-v0.103.x/react-navigation_v3.x.x.js
- definitions/npm/react-navigation_v4.x.x/flow_v0.104.x-/react-navigation_v4.x.x.js
- definitions/npm/react-navigation_v4.x.x/flow_v0.92.x-v0.103.x/react-navigation_v4.x.x.js
Fixes #3900 
- Links to documentation: https://reactnavigation.org/docs/4.x/getting-started
- Link to GitHub or NPM: https://github.com/react-navigation/react-navigation
> [react-navigation] Fix StackActions.popToTop

- definitions/npm/@testing-library/user-event_v12.x.x/flow_v0.104.x-/test_user-event_v12.x.x.js
- definitions/npm/@testing-library/user-event_v12.x.x/flow_v0.104.x-/user-event_v12.x.x.js
- Links to documentation: https://github.com/testing-library/user-event
- Link to GitHub or NPM: https://github.com/testing-library/user-event
> [@testing-library/user-event_v12.x.x] Add definitions

- definitions/npm/snarkdown_v2.x.x/flow_v0.104.x-/snarkdown_v2.x.x.js
- definitions/npm/snarkdown_v2.x.x/flow_v0.104.x-/test_snarkdown_v2.x.x.js
- Links to documentation: https://github.com/developit/snarkdown
- Link to GitHub or NPM: https://github.com/developit/snarkdown
> [snarkdown_v2.x.x] Add definitions

- definitions/npm/yargs_v10.x.x/test_yargs.js
- definitions/npm/yargs_v15.x.x/flow_v0.118.x-/yargs_v15.x.x.js
- definitions/npm/yargs_v15.x.x/test_yargs.js
- definitions/npm/yargs_v4.x.x/test_yargs_v4.x.x.js
- definitions/npm/yargs_v5.x.x/test_yargs.js
- definitions/npm/yargs_v7.x.x/test_yargs.js
- definitions/npm/yargs_v8.x.x/test_yargs.js
- definitions/npm/yargs_v9.x.x/test_yargs.js
- Links to documentation:https://github.com/yargs/yargs/blob/v15.x.x/docs/advanced.md#command-finish-hook
- Link to GitHub or NPM: https://github.com/yargs/yargs
Other notes:
> [yargs] add missing onFinishCommand

- definitions/npm/react-modal_v1.x.x/test_react-modal-v1.js
- definitions/npm/react-modal_v3.1.x/test_react-modal_v3.1.x.js
- definitions/npm/react-modal_v3.11.x/flow_v0.104.x-/react-modal_v3.11.x.js
- definitions/npm/react-modal_v3.11.x/flow_v0.54.1-v0.103.x/react-modal_v3.11.x.js
- definitions/npm/react-modal_v3.11.x/test_react-modal_v3.11.x.js
- definitions/npm/react-modal_v3.6.x/test_react-modal_v3.6.x.js
- Links to documentation: http://reactcommunity.org/react-modal/
- Link to GitHub or NPM: https://github.com/reactjs/react-modal
- Type of contribution: new definition for a new version
> Add a definition for react-modal-v3.11.x

- definitions/npm/cypress_v5.x.x/flow_v0.25.x-/cypress_v5.x.x.js
- definitions/npm/cypress_v5.x.x/test_cypress_v5.x.x.js
- Links to documentation: https://docs.cypress.io/guides/overview/why-cypress.html
- Link to GitHub or NPM: https://github.com/cypress-io/cypress
Other notes: Thanks to @lukeapage for #3028 which was a great starting base
> Add cypress v5 definitions

- definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js
- definitions/npm/@apollo/react-hooks_v3.x.x/flow_v0.58.x-v0.103.x/react-hooks_v3.x.x.js
Other notes:
I have raised https://github.com/flow-typed/flow-typed/issues/3863 and this is a tentative pr to solve that issue. 
Not sure if adding an export needs to be tested so any feedback in that regard would be appreciated
> [@apollo/react-hooks] export DataProxy

- definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-/react_v11.x.x.js
https://github.com/testing-library/react-testing-library/releases  
https://github.com/testing-library/dom-testing-library/releases  
- Type of contribution: addition 
Other notes:
Just trying to bring the definition a bit more up to date...
> [@testing-library/react_v11.x.x] Update definitions

- definitions/npm/password-validator_v4.x.x/flow_v0.134.x-/password-validator_v4.x.x.js
- definitions/npm/password-validator_v4.x.x/flow_v0.134.x-/test_password-validator_v4.x.x.js
Using flow v0.134 and password-validator v4.1.1.
- Links to documentation: https://github.com/tarunbatra/password-validator/wiki
- Link to GitHub or NPM: https://github.com/tarunbatra/password-validator
> feat(password-validator): add types

- definitions/npm/@testing-library/react-hooks_v3.x.x/flow_v0.104.x-/react-hooks_v3.x.x.js
- definitions/npm/@testing-library/react-hooks_v3.x.x/flow_v0.104.x-/test_react-hooks_v3.x.x.js
Adds definitions for `@testing-library/react-hooks`.
- Links to documentation: https://react-hooks-testing-library.com/reference/api
- Link to GitHub or NPM:  https://github.com/testing-library/react-hooks-testing-library
> [@testing-library/react-hooks_v3.x.x] Add definitions

- definitions/npm/@react-navigation/core_v3.x.x/flow_v0.104.x-/core_v3.x.x.js
- definitions/npm/react-navigation-drawer_v2.x.x/flow_v0.104.x-/react-navigation-drawer_v2.x.x.js
- definitions/npm/react-navigation-stack_v1.x.x/flow_v0.104.x-/react-navigation-stack_v1.x.x.js
- definitions/npm/react-navigation-tabs_v2.x.x/flow_v0.104.x-/react-navigation-tabs_v2.x.x.js
- definitions/npm/react-navigation_v4.x.x/flow_v0.104.x-/react-navigation_v4.x.x.js
Reverts flow-typed/flow-typed#3920
> Revert "react-navigation fix: Replace NavigationNavigateAction with NavigationAction"

- definitions/npm/sinon_v7.x.x/flow_v0.80.x-/sinon_v7.x.x.js
- definitions/npm/sinon_v7.x.x/test_sinon_v7.x.x.js
- Links to documentation: [LastArg](https://sinonjs.org/releases/latest/spy-call/)
- Type of contribution: new definition | **addition** | fix | refactor
Other notes:
Also need this for parcel 😄
> add lastArg to spy call and test

- definitions/npm/sinon_v7.x.x/flow_v0.80.x-/sinon_v7.x.x.js
- definitions/npm/sinon_v7.x.x/test_sinon_v7.x.x.js
- Type of contribution: new definition | addition | **fix** | refactor
Other notes: Fixing my previous PR where lastArg was a function, it's a property. Thank you
> Add last arg to spy call

- definitions/npm/@react-navigation/bottom-tabs_v5.x.x/flow_v0.104.x-/bottom-tabs_v5.x.x.js
- definitions/npm/@react-navigation/bottom-tabs_v5.x.x/test_bottom-tabs.js
- definitions/npm/@react-navigation/core_v5.x.x/flow_v0.104.x-/core_v5.x.x.js
- definitions/npm/@react-navigation/devtools_v5.x.x/flow_v0.104.x-/devtools_v5.x.x.js
- definitions/npm/@react-navigation/drawer_v5.x.x/flow_v0.104.x-/drawer_v5.x.x.js
- definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/flow_v0.104.x-/material-bottom-tabs_v5.x.x.js
- definitions/npm/@react-navigation/material-top-tabs_v5.x.x/flow_v0.104.x-/material-top-tabs_v5.x.x.js
- definitions/npm/@react-navigation/native_v5.x.x/flow_v0.104.x-/native_v5.x.x.js
- definitions/npm/@react-navigation/stack_v5.x.x/flow_v0.104.x-/stack_v5.x.x.js
- Links to documentation: https://reactnavigation.org/docs/bottom-tab-navigator#tabbarbadge
- Link to GitHub or NPM: [1](https://github.com/react-navigation/react-navigation/commit/96c7b688ce773b3dd1f1cf7775367cd7080c94a2), [2](https://github.com/react-navigation/react-navigation/commit/6ac4d40140189a29d857c4d1203bced6929f7baf)
> [react-navigation] Type new tabBarBadge/tabBarBadgeStyle options for bottom-tabs

- definitions/npm/validate-currency-code_v0.x.x/flow_v0.104.x-/test_validate-currency-code_v0.x.x.js
- definitions/npm/validate-currency-code_v0.x.x/flow_v0.104.x-/validate-currency-code_v0.x.x.js
- Links to documentation: https://github.com/Boelensman1/validate-currency-code#readme
- Link to GitHub or NPM: https://www.npmjs.com/package/validate-currency-code
> [validate-currency-code_v0.x.x]: Add type definition

- definitions/npm/lambda-log_v2.x.x/flow_v0.112.x-/lambda-log_v2.x.x.js
- definitions/npm/lambda-log_v2.x.x/flow_v0.112.x-/test_lambda-log_v2.x.x.js
- Links to documentation: https://github.com/KyleRoss/node-lambda-log#readme
- Link to GitHub or NPM: https://github.com/KyleRoss/node-lambda-log#readme
> [lambda-log_v2.x.x] Add definitions

- definitions/npm/valtio_v0.2.x/flow_v0.127.x-/test_valtio_v0.2.x.js
- definitions/npm/valtio_v0.2.x/flow_v0.127.x-/valtio_v0.2.x.js
- Links to documentation: https://github.com/pmndrs/valtio
- Link to GitHub or NPM: https://github.com/pmndrs/valtio
> [valtio_v0.2.x] Add defintitions

- definitions/npm/@react-navigation/bottom-tabs_v5.x.x/flow_v0.104.x-/bottom-tabs_v5.x.x.js
- definitions/npm/@react-navigation/core_v5.x.x/flow_v0.104.x-/core_v5.x.x.js
- definitions/npm/@react-navigation/devtools_v5.x.x/flow_v0.104.x-/devtools_v5.x.x.js
- definitions/npm/@react-navigation/drawer_v5.x.x/flow_v0.104.x-/drawer_v5.x.x.js
- definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/flow_v0.104.x-/material-bottom-tabs_v5.x.x.js
- definitions/npm/@react-navigation/material-top-tabs_v5.x.x/flow_v0.104.x-/material-top-tabs_v5.x.x.js
- definitions/npm/@react-navigation/native_v5.x.x/flow_v0.104.x-/native_v5.x.x.js
- definitions/npm/@react-navigation/stack_v5.x.x/flow_v0.104.x-/stack_v5.x.x.js
- Links to documentation: These new events aren't documented yet
- Link to GitHub or NPM: [1](https://github.com/react-navigation/react-navigation/commit/6925e92dc3e9885e3f552ca5e5eb51ae1521e54e), [2](https://github.com/react-navigation/react-navigation/pull/8524/)
> [react-navigation] Type new events

- definitions/npm/@react-navigation/bottom-tabs_v5.x.x/flow_v0.104.x-/bottom-tabs_v5.x.x.js
- definitions/npm/@react-navigation/core_v5.x.x/flow_v0.104.x-/core_v5.x.x.js
- definitions/npm/@react-navigation/devtools_v5.x.x/flow_v0.104.x-/devtools_v5.x.x.js
- definitions/npm/@react-navigation/drawer_v5.x.x/flow_v0.104.x-/drawer_v5.x.x.js
- definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/flow_v0.104.x-/material-bottom-tabs_v5.x.x.js
- definitions/npm/@react-navigation/material-top-tabs_v5.x.x/flow_v0.104.x-/material-top-tabs_v5.x.x.js
- definitions/npm/@react-navigation/native_v5.x.x/flow_v0.104.x-/native_v5.x.x.js
- definitions/npm/@react-navigation/stack_v5.x.x/flow_v0.104.x-/stack_v5.x.x.js
- Links to documentation: [1](https://reactnavigation.org/docs/stack-navigator#detachinactivescreens), [2](https://reactnavigation.org/docs/bottom-tab-navigator#detachinactivescreens), [3](https://reactnavigation.org/docs/drawer-navigator#detachinactivescreens)
- Link to GitHub or NPM: https://github.com/react-navigation/react-navigation/pull/8805
> [react-navigation] Type detachInactiveScreens

- definitions/npm/@react-navigation/bottom-tabs_v5.x.x/flow_v0.104.x-/bottom-tabs_v5.x.x.js
- definitions/npm/@react-navigation/core_v5.x.x/flow_v0.104.x-/core_v5.x.x.js
- definitions/npm/@react-navigation/devtools_v5.x.x/flow_v0.104.x-/devtools_v5.x.x.js
- definitions/npm/@react-navigation/drawer_v5.x.x/flow_v0.104.x-/drawer_v5.x.x.js
- definitions/npm/@react-navigation/material-bottom-tabs_v5.x.x/flow_v0.104.x-/material-bottom-tabs_v5.x.x.js
- definitions/npm/@react-navigation/material-top-tabs_v5.x.x/flow_v0.104.x-/material-top-tabs_v5.x.x.js
- definitions/npm/@react-navigation/native_v5.x.x/flow_v0.104.x-/native_v5.x.x.js
- definitions/npm/@react-navigation/stack_v5.x.x/flow_v0.104.x-/stack_v5.x.x.js
- Links to documentation: isn't documented yet
- Link to GitHub or NPM: https://github.com/react-navigation/react-navigation/commit/0b627304aa9fbb48de7a674ff8dfbbc495f5efe6
> [react-navigation] Type tabBarVisibilityAnimationConfig

- definitions/npm/valtio_v0.4.x/flow_v0.127.x-/test_valtio_v0.4.x.js
- definitions/npm/valtio_v0.4.x/flow_v0.127.x-/valtio_v0.4.x.js
- Links to documentation: https://github.com/pmndrs/valtio
- Link to GitHub or NPM: https://github.com/pmndrs/valtio
> [valtio_v0.4.x] Add snapshot utility

- definitions/npm/@reach/auto-id_v0.11.x/flow_v0.104.x-/auto-id_v0.11.x.js
- definitions/npm/@reach/auto-id_v0.11.x/flow_v0.104.x-/test_auto-id_v0.11.x.js
- Links to documentation: https://reach.tech/auto-id
- Link to GitHub or NPM: https://github.com/reach/reach-ui/blob/main/packages/auto-id/src/index.tsx
Other notes:
> [@reach/auto-id_v0.11.x] Add definitions

- .github/workflows/main.yml
Addresses followup work in #3951: [link](https://github.com/flow-typed/flow-typed/pull/3951#pullrequestreview-538430138).
Not really sure what email to give, since we don't have a flow-typed email... so I just put `noemail@example.com`, open to other suggestions. 🤷‍♂️
> Update git author information for Github Action.

- definitions/npm/react-modal_v3.12.x/flow_v0.104.x-/react-modal_v3.12.x.js
- definitions/npm/react-modal_v3.12.x/test_react-modal_v3.12.x.js
- Links to documentation: https://github.com/reactjs/react-modal/blob/master/CHANGELOG.md#3121---sun-22-nov-2020-225112-utc
- Link to GitHub or NPM: https://www.npmjs.com/package/react-modal
> Add definitions for react-modal-v3.12.x

- definitions/npm/prop-types_v15.x.x/flow_v0.104.x-/prop-types_v15.x.x.js
- Links to documentation: https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes
- Link to GitHub or NPM: https://www.npmjs.com/package/prop-types
Other notes: Closes #3958
> Add elementType to prop-types

- definitions/npm/aphrodite_v2.x.x/flow_v0.83.x-/aphrodite_v2.x.x.js
Function was missing from original definition
- Links to documentation: https://github.com/Khan/aphrodite/blob/master/src/exports.js#L163
- Link to GitHub or NPM: https://github.com/Khan/aphrodite
Other notes:
> [Aphrodite] Add missing extend function

- definitions/npm/mqtt-packet_v6.6.x/flow_v0.84.x-/mqtt-packet_v6.6.x.js
- definitions/npm/mqtt-packet_v6.6.x/test_mqtt-packet_v6.6.x.js
- Links to documentation: https://github.com/mqttjs/mqtt-packet/blob/master/types/index.d.ts
- Link to GitHub or NPM: https://github.com/mqttjs/mqtt-packet
Other notes:
I did correct a few of the types from TS by inspecting the JS code
> feat: add mqtt-packet defs

- definitions/npm/mqtt_v4.2.x/flow_v0.84.x-/mqtt_v4.2.x.js
- definitions/npm/mqtt_v4.2.x/test_mqtt_v4.2.x.js
- Links to documentation: https://github.com/mqttjs/MQTT.js
- Link to GitHub or NPM: https://github.com/mqttjs/MQTT.js 
Other notes: based on the project's own janky TypeScript types, with a lot of careful corrections
Also, I inlined type defs for `mqtt-packet`, because of the sharing types between packages problem.
Also inlined a cool typed event emitter class
> feat: add mqtt definitions

- definitions/npm/@koa/cors_v3.x.x/flow_v0.53.x-/cors_v3.x.x.js
Same issue as https://github.com/flow-typed/flow-typed/pull/3976, fixing the export otherwise it's unusable
- Links to documentation: https://www.npmjs.com/package/@koa/cors
- Link to GitHub or NPM: https://www.npmjs.com/package/@koa/cors
Other notes:
> [@koa/cors] Fix the export

- definitions/npm/chalk_v4.x.x/flow_v0.104.x-/chalk_v4.x.x.js
- definitions/npm/chalk_v4.x.x/flow_v0.104.x-/test_chalk_v4.x.x.js
- Links to documentation: https://github.com/chalk/chalk/blob/master/index.d.ts, https://github.com/chalk/chalk
- Link to GitHub or NPM:  https://github.com/chalk/chalk
- Type of contribution: new definition (add new version for existing package)
Changes between v2 and v4:
```diff
--- definitions/npm/chalk_v2.x.x/flow_v0.104.x-/chalk_v2.x.x.js
+++ definitions/npm/chalk_v4.x.x/flow_v0.104.x-/chalk_v4.x.x.js
@@ -1,4 +1,4 @@
-// From: https://github.com/chalk/chalk/blob/master/index.js.flow
+// From: https://github.com/chalk/chalk/blob/master/index.d.ts
declare module "chalk" {
declare type TemplateStringsArray = $ReadOnlyArray<string>;
@@ -12,7 +12,6 @@ declare module "chalk" {
}>;
declare type ChalkOptions = {|
-    enabled?: boolean,
level?: Level
|};
@@ -26,8 +25,7 @@ declare module …
```
> Add chalk v4

- definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-/react_v11.x.x.js
- definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-/test_react_v11.x.x.js
- Links to documentation: https://github.com/testing-library/dom-testing-library/tree/master/types
- Link to GitHub or NPM: https://github.com/testing-library/dom-testing-library
Other notes: 
Following #3996, improve "by role" queries (only allow actual roles, and not random strings or regex), fix and update matchers and options types.
/cc @Brianzchen
> [@testing-library/react_v11.x.x] Improve by role queries

- cli/src/cli.js
Fixes https://github.com/flow-typed/flow-typed/issues/4022
> Unbreak CLI

- definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v1.x.x/flow_v0.92.x-/react-json-schema-form-builder_v1.x.x.js
- definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v1.x.x/test_react-json-schema-form-builder_v1.x.x.js
- Links to documentation: https://react-json-schema-form-builder.readthedocs.io/en/main/
- Link to GitHub or NPM: https://github.com/ginkgobioworks/react-json-schema-form-builder
> [@ginkgo-bioworks/react-json-schema-form] Add additional configurations to Mods

- definitions/npm/webpack_v5.x.x/flow_v0.104.x-/test_webpack_v5.x.x.js
- definitions/npm/webpack_v5.x.x/flow_v0.104.x-/webpack_v5.x.x.js
- definitions/npm/webpack_v5.x.x/flow_v0.71.x-v0.103.x/test_webpack_v5.x.x.js
- definitions/npm/webpack_v5.x.x/flow_v0.71.x-v0.103.x/webpack_v5.x.x.js
- Links to documentation: https://github.com/webpack/webpack/releases/tag/v5.0.0
- Link to GitHub or NPM: https://www.npmjs.com/package/webpack
Other notes: This for now is a straight copy from webpack-4. Generally when new major versions come out it's easier for us to just port the old version to the new one if there are no easily noticeable differences so we can get the version into users hands faster and slowly tweak the defs afterwards.
> [webpack-v5] Add definitions

- cli/src/commands/runTests.js
- definitions/npm/mongodb_v3.5.x/flow_v0.114.x-/mongodb_v3.5.x.js
- definitions/npm/mongodb_v3.6.x/flow_v0.114.x-/mongodb_v3.6.x.js
- definitions/npm/mongodb_v3.6.x/flow_v0.114.x-/test_mongodb_v3.6.x_client.js
- definitions/npm/mongodb_v3.6.x/flow_v0.114.x-/test_mongodb_v3.6.x_docs_quick_start.js
Fix mongodb v3.5
Add mongodb v3.6
Fix Cli in Mac Rosetta
> Fix: mongo definitions

- definitions/npm/mongodb_v3.6.x/flow_v0.114.x-/mongodb_v3.6.x.js
- definitions/npm/mongodb_v3.6.x/flow_v0.114.x-/test_mongodb_v3.6.x_client.js
- Start to type Collection (I give up for today, and end up using a lot of `any` but at least interface shape is defined.
- Missing tests, but this would be too much of work
> [mongo_v3.6.x]: Improve types

- definitions/npm/bunyan_v1.x.x/flow_v0.104.x-/bunyan_v1.x.x.js
- definitions/npm/bunyan_v1.x.x/flow_v0.25.x-v0.79.x/bunyan_v1.x.x.js
- definitions/npm/bunyan_v1.x.x/flow_v0.80.x-v0.103.x/bunyan_v1.x.x.js
- definitions/npm/bunyan_v1.x.x/test_bunyan_v1.x.x.js
Adding `fields: any` in the same way as https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bunyan/index.d.ts 
- Links to documentation: https://github.com/trentm/node-bunyan#core-fields
- Link to GitHub or NPM: https://www.npmjs.com/package/bunyan 
Other notes: Updated tests to add error codes to fix warnings.
> [bunyan] Add fields property

- definitions/npm/koa-static-cache_v5.x.x/flow_v0.83.x-/koa-static-cache_v5.x.x.js
- definitions/npm/koa-static-cache_v5.x.x/flow_v0.83.x-/test_koa-static-cache_v5.x.x.js
- Links to documentation: https://www.npmjs.com/package/koa-static-cache
- Link to GitHub or NPM: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa-static-cache/index.d.ts
Other notes:
> [koa-static-cache] Add definition

- definitions/npm/aphrodite_v2.x.x/flow_v0.83.x-/aphrodite_v2.x.x.js
- Links to documentation: https://developer.mozilla.org/en-US/docs/Web/CSS/box-flex#formal_definition
- Link to GitHub or NPM: https://www.npmjs.com/package/aphrodite
Other notes:
In the docs it mentions -moz-box or -moz-inline-box but these don't work in firefox so I'm not adding them
> [aphrodite] Add display webkit value

- definitions/npm/redux-thunk_v2.x.x/flow_v0.83.x-/redux-thunk_v2.x.x.js
- definitions/npm/redux-thunk_v2.x.x/flow_v0.83.x-/test_redux-thunk_v2.x.x.js
- Links to documentation: https://www.npmjs.com/package/redux-thunk#injecting-a-custom-argument
- Link to GitHub or NPM: https://www.npmjs.com/package/redux-thunk
Other notes: At long last it exists
> [redux-thunk] Add definition

- definitions/npm/node-fetch_v1.x.x/test_node-fetch_v1.js
- definitions/npm/node-fetch_v2.x.x/flow_v0.100.x-v0.103.x/node-fetch_v2.x.x.js
- definitions/npm/node-fetch_v2.x.x/flow_v0.104.x-/node-fetch_v2.x.x.js
- definitions/npm/node-fetch_v2.x.x/flow_v0.104.x-/test_node-fetch_v2.x.x_headers.js
- definitions/npm/node-fetch_v2.x.x/flow_v0.104.x-/test_node-fetch_v2.x.x_init.js
- definitions/npm/node-fetch_v2.x.x/test_node-fetch_v2.x.x.js
- quick_run_def_tests.sh
- Links to documentation: https://github.com/node-fetch/node-fetch#class-headers
- Link to GitHub or NPM: https://github.com/node-fetch/node-fetch
Other notes:
Pass arguments to cli when using `./quick_run_def_tests.sh` so we can do `./quick_run_def_tests.sh --numberOfFlowVersions=1` or even `./quick_run_def_tests.sh --help`
> [node-fetch] fix Headers

- definitions/npm/sessionstorage_v0.1.x/flow_v0.83.x-/sessionstorage_v0.1.x.js
- definitions/npm/sessionstorage_v0.1.x/flow_v0.83.x-/test_sessionstorage_v0.1.x.js
- Links to documentation: https://www.npmjs.com/package/sessionstorage#usage
- Link to GitHub or NPM: https://www.npmjs.com/package/sessionstorage
Other notes:
> [sessionstorage] New definition

- definitions/npm/ioredis_v4.x.x/flow_v0.104.x-/ioredis_v4.x.x.js
- definitions/npm/ioredis_v4.x.x/flow_v0.46.x-v0.103.x/ioredis_v4.x.x.js
- definitions/npm/ioredis_v4.x.x/test_ioredis_v4.x.x.js
- Links to documentation: https://github.com/luin/ioredis/releases/tag/v4.0.0
- Link to GitHub or NPM: https://github.com/luin/ioredis
Other notes:
none of the breaking changes in v4 affect the existing type signatures,
so I copied the v3 defs verbatim
> feat(ioredis): add v4 defs

- definitions/npm/express_v4.16.x/flow_v0.104.x-/express_v4.16.x.js
- definitions/npm/express_v4.17.x/flow_v0.104.x-/express_v4.17.x.js
- definitions/npm/express_v4.x.x/flow_v0.104.x-/express_v4.x.x.js
- Links to documentation: https://expressjs.com/en/4x/api.html#req.range
- Link to GitHub or NPM: https://github.com/expressjs/express/blob/508936853a6e311099c9985d4c11a4b1b8f6af07/lib/request.js#L212
> [express_v4.x.x] add `req.range(size[, options])`

- definitions/npm/ioredis_v3.x.x/test_ioredis_v3.x.x.js
- definitions/npm/ioredis_v4.x.x/test_ioredis_v4.x.x.js
- definitions/npm/url-template_v2.x.x/flow_v0.83.x-/test_url-template_v2.x.x.js
- definitions/npm/url-template_v2.x.x/flow_v0.83.x-/url-template_v2.x.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/url-template/index.d.ts
- Link to GitHub or NPM: https://github.com/bramstein/url-template
Other notes: Also clean up suppression errors from #4070
> [url-template] Add definition

- definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v2.x.x/flow_v0.92.x-/react-json-schema-form-builder_v2.x.x.js
- definitions/npm/@ginkgo-bioworks/react-json-schema-form-builder_v2.x.x/test_react-json-schema-form-builder_v2.x.x.js
Links to documentation: https://react-json-schema-form-builder.readthedocs.io/en/main/
Link to GitHub or NPM: https://github.com/ginkgobioworks/react-json-schema-form-builder
Type of contribution: addition
> [@ginkgo-bioworks/react-json-schema-form] Add v2.x.x definitions

- definitions/npm/deepmerge_v1.x.x/test_deepmerge_v1.x.x.js
- definitions/npm/deepmerge_v2.1.x/flow_v0.104.x-/test_deepmerge_v2.1.x.js
- definitions/npm/deepmerge_v3.x.x/flow_v0.104.x-/test_deepmerge_v3.x.x.js
- definitions/npm/deepmerge_v4.x.x/flow_v0.83.x-/deepmerge_v4.x.x.js
- definitions/npm/deepmerge_v4.x.x/flow_v0.83.x-/test_deepmerge_v4.x.x.js
- Links to documentation: https://github.com/TehShrike/deepmerge
- Link to GitHub or NPM: https://www.npmjs.com/package/deepmerge
Other notes:
> [deepmerge] Add v4 defs

- definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/react_v12.x.x.js
- definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/test_react_v12.x.x.js
- https://github.com/testing-library/react-testing-library/releases/tag/v12.0.0
- https://github.com/testing-library/dom-testing-library/releases/tag/v8.0.0
- https://github.com/testing-library/dom-testing-library/commit/d347302d6b17280b71505d55d0cb9cda376b95cc#diff-8d8460221bf4eb295f964884b40a9ba6302a9c2af2f9b1997cbed42fda139de8
Notes:
- Added a fix for Flow >= 0.153
- Failing tests for older versions
> [@testing-library/react_v12.x.x] Update definitions

- definitions/npm/faker_v4.x.x/flow_v0.104.x-/faker_v4.x.x.js
- definitions/npm/faker_v4.x.x/flow_v0.104.x-/test_faker_v4.x.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/faker/index.d.ts#L84
- Link to GitHub or NPM: https://github.com/marak/Faker.js/
Other notes:
> [faker] add datatype object

- definitions/npm/prismic-dom_v2.x.x/flow_v0.83.x-/prismic-dom_v2.x.x.js
- definitions/npm/prismic-dom_v2.x.x/flow_v0.83.x-/test_prismic-dom_v2.x.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prismic-dom/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/prismic-dom
Other notes:
> [prismic-dom] new def

- cli/.eslintrc
- cli/package.json
- cli/yarn.lock
- definitions/.eslintrc
- definitions/package.json
- definitions/yarn.lock
https://www.npmjs.com/package/eslint-plugin-fb-flow  
https://medium.com/flow-type/introducing-flow-indexed-access-types-b27175251fd0
> Add eslint-plugin-fb-flow ESLint plugin

- definitions/npm/cypress_v7.x.x/flow_v0.25.x-/cypress_v7.x.x.js
- definitions/npm/cypress_v7.x.x/test_cypress_v7.x.x.js
- Links to documentation: https://www.npmjs.com/package/cypress
- Link to GitHub or NPM: https://www.npmjs.com/package/cypress
Other notes: Copied from v6 and will tweak later as necessary
> [cypress] Add v7 definitions

- definitions/npm/faker_v5.x.x/flow_v0.104.x-/faker_v5.x.x.js
- definitions/npm/faker_v5.x.x/flow_v0.104.x-/test_faker_v5.x.x.js
- definitions/npm/faker_v5.x.x/flow_v0.25.x-v0.103.x/faker_v5.x.x.js
- definitions/npm/faker_v5.x.x/flow_v0.25.x-v0.103.x/test_faker_v5.x.x.js
- Links to documentation: https://github.com/Marak/Faker.js#readme
- Link to GitHub or NPM: https://www.npmjs.com/package/faker
Other notes: Copied from v4
> [faker] Add v5 definitions

- definitions/npm/jspdf_v2.x.x/flow_v0.83.x-/jspdf_v2.x.x.js
- definitions/npm/jspdf_v2.x.x/flow_v0.83.x-/test_jspdf_v2.x.x.js
- Links to documentation: http://raw.githack.com/MrRio/jsPDF/master/docs/
- Link to GitHub or NPM: https://www.npmjs.com/package/jspdf
Other notes: Incomplete def and works for my use case but creating start for others to add to.
> [jspdf] Add new def

- .github/workflows/main.yml
Node 16 is the current LTS now
See https://nodejs.org/en/about/releases/
> Update CI Node.js versions

- CONTRIBUTING.md
The docs don't really mention about a common issue with git untracked files. Just adding a line of explanation for that.
Other notes: Sorry I made a branch in `flow-typed/flow-typed` itself. Won't happen again in future 🙏
> [docs] Minor improvements to help with test running

- cli/src/commands/__tests__/install-test.js
- cli/src/commands/install.js
- cli/src/lib/npm/__tests__/npmLibDefs-test.js
- cli/src/lib/npm/npmLibDefs.js
Closes #2581
Other notes:
cc: @jirutka
> [cli] install --skipCache option

- cli/src/commands/__tests__/install-test.js
- cli/src/commands/install.js
Closes #2537
Other notes: I preferred to create a new if block for the check so that I could document what that block specifically was for
cc @AndrewSouthpaw @rocketraman @ssvgaddam
> [cli] Allow slash comments in dependencies

- definitions/npm/react-measure_v2.x.x/flow_v0.83.x-/react-measure_v2.x.x.js
- definitions/npm/react-measure_v2.x.x/flow_v0.83.x-/test_react-measure_v2.x.x.js
Closes #2015
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-measure/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/react-measure
Other notes:
> [react-measure] Add definition

- definitions/npm/universal-cookie_v4.x.x/flow_v0.83.x-/test_universal-cookie_v4.x.x.js
- definitions/npm/universal-cookie_v4.x.x/flow_v0.83.x-/universal-cookie_v4.x.x.js
- Links to documentation: https://github.com/reactivestack/cookies/blob/master/packages/universal-cookie/src/Cookies.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/universal-cookie
Other notes:
> [universal-cookie] Add def

- .gitignore
- cli/README.md
- cli/package.json
When the cli is published it's currently a little barren right now
https://www.npmjs.com/package/flow-typed
other notes:
- Should I add anything else?
> [cli] Add a published readme

- definitions/npm/js-cookie_v2.x.x/flow_v0.104.x-/js-cookie_v2.x.x.js
- definitions/npm/js-cookie_v2.x.x/flow_v0.104.x-/test_js-cookie-v2.x.x.js
Closes #2439
- Links to documentation: https://www.npmjs.com/package/js-cookie/v/2.2.1#basic-usage
- Link to GitHub or NPM: https://www.npmjs.com/package/js-cookie/v/2.2.1
Other notes:
> [js-cookies] Fixes get definition

- docs/install.md
> [docs] Add missing install options

- docs/faq.md
Closes #4183, #779, #929
Give insight into best way to solve eslint errors thrown in flow-typed/npm dir
ref: https://github.com/flow-typed/flow-typed/pull/4183#issuecomment-985109763
> [docs] faq for eslint errors

- .github/workflows/main.yml
- cli/src/commands/runTests.js
- cli/src/lib/git.js
- definitions/npm/js-cookie_v2.x.x/flow_v0.104.x-/js-cookie_v2.x.x.js
- definitions/yarn.lock
For some reason the tests stopped working in ci. This is related how the checkout action only pulls a minimal clone of the repo and then can't diff between the current changes vs master/previous commit.
As part of this I found that if you made a commit and try to run tests with `onlyChanged` it won't find any tests kind of like how `jest --watch` works. But since we're always interested in comparing to master it will now always find tests to run if there are changes regardless if they're committed or not.
Please check out this build [c907934](https://github.com/flow-typed/flow-typed/runs/4401191310?check_suite_focus=true) to prove that tests run as expected when there was a change
> [cli] Fix definitions not running in ci env

- definitions/npm/express_v4.17.x/flow_v0.104.x-/express_v4.17.x.js
- definitions/npm/express_v4.17.x/flow_v0.104.x-/test_overrideUseMethodClassExtension.js
- definitions/npm/express_v4.17.x/flow_v0.104.x-/test_response.js
- definitions/npm/express_v4.17.x/flow_v0.104.x-/test_useMethod.js
- definitions/npm/express_v4.17.x/test_express_v4.17.x.js
- Links to documentation: http://expressjs.com/en/5x/api.html#app.render
- Link to GitHub or NPM: https://www.npmjs.com/package/express
Other notes: Helps #4190 get started
> [express] suppression errors for express 4.17.x

- definitions/npm/express_v4.17.x/flow_v0.104.x-/express_v4.17.x.js
> Add  `res` to express$Request

- definitions/npm/string-natural-compare_v3.x.x/flow_v0.83.x-/string-natural-compare_v3.x.x.js
- definitions/npm/string-natural-compare_v3.x.x/flow_v0.83.x-/test_string-natural-compare_v3.x.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/string-natural-compare/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/string-natural-compare
Other notes:
> [string-natural-compare] New definition

- definitions/npm/react-native-splash-screen_v3.x.x/flow_v0.83.x-/react-native-splash-screen_v3.x.x.js
- definitions/npm/react-native-splash-screen_v3.x.x/flow_v0.83.x-/test_react-native-splash-screen_v3.x.x.js
- Links to documentation: https://github.com/crazycodeboy/react-native-splash-screen/blob/master/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/react-native-splash-screen
Other notes:
> [react-native-splash-screen] New definition

- definitions/npm/react-test-renderer_v16.x.x/test_react-test-renderer-v16.x.x.js
- Links to documentation: https://www.npmjs.com/package/react-test-renderer
- Link to GitHub or NPM: https://www.npmjs.com/package/react-test-renderer
Other notes:
> [react-test-renderer] Fix suppression 

- definitions/npm/redux_v4.x.x/flow_v0.134.x-/redux_v4.x.x.js
Fix the state argument type in the reducer type
> [redux] fix Reducer state type

- definitions/npm/koa_v2.x.x/flow_v0.153.x-/koa_v2.x.x.js
- definitions/npm/koa_v2.x.x/flow_v0.153.x-/test_koa_v2.x.x.js
Add same body property to the request object that's from koa_v2.0.x https://github.com/flow-typed/flow-typed/pull/4107
- Links to documentation: https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/koa_v2.0.x/flow_v0.153.x-/koa_v2.0.x.js#L27
- Link to GitHub or NPM: https://www.npmjs.com/package/koa
Other notes:
> [koa] Add body object to request object

- definitions/npm/heroku-logger_v0.3.x/flow_v0.83.x-/heroku-logger_v0.3.x.js
- definitions/npm/heroku-logger_v0.3.x/flow_v0.83.x-/test_heroku-logger_v0.3.x.js
- Links to documentation: https://github.com/ianstormtaylor/heroku-logger#heroku-logger & https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/heroku-logger/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/heroku-logger
Other notes:
The TS type def isn't too accurate based on what I found so I've based it more around the readme
> [heroku-logger] New definition

- definitions/npm/app-root-dir_v1.x.x/flow_v0.83.x-/app-root-dir_v1.x.x.js
- definitions/npm/app-root-dir_v1.x.x/flow_v0.83.x-/test_app-root-dir_v1.x.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/app-root-dir/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/app-root-dir
Other notes:
> [app-root-dir] New definition

- definitions/npm/browser-interaction-time_v3.x.x/flow_v0.83.x-/browser-interaction-time_v3.x.x.js
- definitions/npm/browser-interaction-time_v3.x.x/flow_v0.83.x-/test_browser-interaction-time_v3.x.x.js
- Links to documentation: https://github.com/atlassian/browser-interaction-time/blob/master/src/browser-interaction-time.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/browser-interaction-time
Other notes:
> [browser-interaction-time] New definition

- definitions/npm/jsonwebtoken_v8.1.x/test_jsonwebtoken_v8.1.x.js
- definitions/npm/jsonwebtoken_v8.2.x/test_jsonwebtoken_v8.2.x.js
- definitions/npm/jsonwebtoken_v8.3.x/test_jsonwebtoken_v8.3.x.js
- definitions/npm/jsonwebtoken_v8.4.x/flow_v0.104.x-/jsonwebtoken_v8.4.x.js
- definitions/npm/jsonwebtoken_v8.4.x/flow_v0.56.x-v0.103.x/jsonwebtoken_v8.4.x.js
- definitions/npm/jsonwebtoken_v8.4.x/test_jsonwebtoken_v8.4.x.js
- definitions/npm/jsonwebtoken_v8.5.x/flow_v0.104.x-/jsonwebtoken_v8.5.x.js
- definitions/npm/jsonwebtoken_v8.5.x/flow_v0.56.x-v0.103.x/jsonwebtoken_v8.5.x.js
- definitions/npm/jsonwebtoken_v8.5.x/test_jsonwebtoken_v8.5.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsonwebtoken/index.d.ts#L76
- Link to GitHub or NPM: https://www.npmjs.com/package/jsonwebtoken
Other notes:
> [jsonwebtoken] Add version 8.4.x & 8.5.x

- definitions/npm/bcrypt_v5.x.x/flow_v0.83.x-/bcrypt_v5.x.x.js
- definitions/npm/bcrypt_v5.x.x/flow_v0.83.x-/test_bcrypt_v5.x.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bcrypt/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/bcrypt
Other notes:
> [bcrypt] New definition

- definitions/npm/email-validator_v2.x.x/flow_v0.83.x-/email-validator_v2.x.x.js
- definitions/npm/email-validator_v2.x.x/flow_v0.83.x-/test_email-validator_v2.x.x.js
- Links to documentation: https://github.com/manishsaraan/email-validator/blob/master/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/email-validator
Other notes:
> [email-validator] New definition

- definitions/npm/email-validator_v2.x.x/flow_v0.83.x-/email-validator_v2.x.x.js
- definitions/npm/email-validator_v2.x.x/flow_v0.83.x-/test_email-validator_v2.x.x.js
Fix #4225 where it actually exposes an object with a function instead of a function itself.
Other notes: Sorry @GAntoine found this when I actually used it
> [email-validator] Fix definition

- definitions/npm/password-validator_v5.x.x/flow_v0.134.x-/password-validator_v5.x.x.js
- definitions/npm/password-validator_v5.x.x/flow_v0.134.x-/test_password-validator_v5.x.x.js
- Links to documentation: https://github.com/tarunbatra/password-validator/blob/master/typings/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/password-validator
Other notes:
Copied initially from v4 but then converted to class definition and adjusted tests to work
> [password-validator] Add v5 definition

- definitions/npm/puppeteer_v1.20.x/flow_v0.104.x-/puppeteer_v1.20.x.js
- definitions/npm/puppeteer_v1.20.x/flow_v0.104.x-/test_puppeteer_v1.20.x_connect.js
- definitions/npm/puppeteer_v1.20.x/flow_v0.104.x-/test_puppeteer_v1.20.x_defaultArgs.js
- definitions/npm/puppeteer_v1.20.x/flow_v0.104.x-/test_puppeteer_v1.20.x_executablePath.js
- definitions/npm/puppeteer_v1.20.x/flow_v0.104.x-/test_puppeteer_v1.20.x_launch.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.104.x-/puppeteer_v13.x.x.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.104.x-/test_puppeteer_v13.x.x_connect.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.104.x-/test_puppeteer_v13.x.x_defaultArgs.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.104.x-/test_puppeteer_v13.x.x_executablePath.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.104.x-/test_puppeteer_v13.x.x_launch.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.76.x-v0.103.x/puppeteer_v13.x.x.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.76.x-v0.103.x/test_puppeteer_v13.x.x_connect.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.76.x-v0.103.x/test_puppeteer_v13.x.x_defaultArgs.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.76.x-v0.103.x/test_puppeteer_v13.x.x_executablePath.js
- definitions/npm/puppeteer_v13.x.x/flow_v0.76.x-v0.103.x/test_puppeteer_v13.x.x_launch.js
- Links to documentation: https://github.com/puppeteer/puppeteer
- Link to GitHub or NPM: https://www.npmjs.com/package/puppeteer
Other notes: Copied from v1.2.x which is fairly old but mostly everything seems to work and is the same
> [puppeteer] Add v13 definitions

- definitions/npm/faker_v6.x.x/flow_v0.83.x-/faker_v6.x.x.js
- definitions/npm/faker_v6.x.x/flow_v0.83.x-/test_faker_v6.x.x.js
It's very sad that the maintainer of faker has decided to delete all the code, but it's an easy one to type so thought we might as well to give prospective consumers a heads up.
- Links to documentation: https://github.com/marak/Faker.js/
- Link to GitHub or NPM: https://www.npmjs.com/package/faker
Other notes:
Some links for context
- https://www.youtube.com/watch?v=R6S-b_k-ZKY&ab_channel=Fireship
- https://www.reddit.com/r/javascript/comments/rwdu3h/fakerjs_gets_erased/?utm_medium=android_app&utm_source=share
> [faker] Add empty v6 definitions

- definitions/npm/jest-fetch-mock_v3.x.x/flow_v0.83.x-/jest-fetch-mock_v3.x.x.js
- definitions/npm/jest-fetch-mock_v3.x.x/flow_v0.83.x-/test_jest-fetch-mock_v3.x.x.js
- Links to documentation: https://github.com/jefflau/jest-fetch-mock/blob/master/types/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/jest-fetch-mock
Other notes:
> [jest-fetch-mock] Add definition

- definitions/npm/cli-table_v0.3.x/flow_v0.83.x-/cli-table_v0.3.x.js
- definitions/npm/cli-table_v0.3.x/flow_v0.83.x-/test_cli-table_v0.3.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cli-table/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/cli-table
Other notes:
> [cli-table] New definition

- CONTRIBUTING.md
> [docs] Add information regarding how types in modules are declared

- definitions/npm/@faker-js/faker_v4.x.x/flow_v0.104.x-/faker_v4.x.x.js
- definitions/npm/@faker-js/faker_v4.x.x/flow_v0.104.x-/test_faker_v4.x.x.js
- definitions/npm/@faker-js/faker_v4.x.x/flow_v0.25.x-v0.103.x/faker_v4.x.x.js
- definitions/npm/@faker-js/faker_v4.x.x/flow_v0.25.x-v0.103.x/test_faker_v4.x.x.js
This is a complete copy of faker@4 with only the module name changed
- Links to documentation: https://www.npmjs.com/package/@faker-js/faker/v/4.1.0
- Link to GitHub or NPM: https://github.com/faker-js/faker
Other notes:
Ref of faker story: https://fakerjs.dev/update.html
> [@faker-js/faker] Add v4 definition

- definitions/npm/@faker-js/faker_v5.x.x/flow_v0.104.x-/faker_v5.x.x.js
- definitions/npm/@faker-js/faker_v5.x.x/flow_v0.104.x-/test_faker_v5.x.x.js
- definitions/npm/@faker-js/faker_v5.x.x/flow_v0.25.x-v0.103.x/faker_v5.x.x.js
- definitions/npm/@faker-js/faker_v5.x.x/flow_v0.25.x-v0.103.x/test_faker_v5.x.x.js
This is a complete copy of faker@5 with only the module name changed
- Links to documentation: https://www.npmjs.com/package/@faker-js/faker/v/5.5.3
- Link to GitHub or NPM: https://github.com/faker-js/faker
Other notes:
Ref of faker story: https://fakerjs.dev/update.html
> [@faker-js/faker] Add v5 definition

- definitions/npm/@faker-js/faker_v6.x.x/flow_v0.104.x-/faker_v6.x.x.js
- definitions/npm/@faker-js/faker_v6.x.x/flow_v0.104.x-/test_faker_v6.x.x.js
- definitions/npm/@faker-js/faker_v6.x.x/flow_v0.25.x-v0.103.x/faker_v6.x.x.js
- definitions/npm/@faker-js/faker_v6.x.x/flow_v0.25.x-v0.103.x/test_faker_v6.x.x.js
This is a complete copy of faker@5 with only the module name changed
- Links to documentation: https://github.com/faker-js/faker/releases
- Link to GitHub or NPM: https://www.npmjs.com/package/@faker-js/faker
Other notes:
v6 is a mostly rewrite to TS with minor implementation detail changes unrelated to library interface
> [@faker-js/faker] Add v6 definition

- definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/react-redux_v7.x.x.js
- definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connect.js
Other notes:
As discussed in https://github.com/flow-typed/flow-typed/pull/4203 the type definition for ConnectedComponent needed to be polymorphic and tests needed adding.
> [react-redux] - fix ConnectedComponent type

- definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-/react_v11.x.x.js
- definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-/test_react_v11.x.x.js
- definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/react_v12.x.x.js
- definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-/test_react_v12.x.x.js
Closes #4117.
- Links to documentation: https://testing-library.com/docs/react-testing-library/intro/
Other notes: There are two types created to support this feature. `IntersectionHTMLElement` and `UnionHTMLElement` which are necessary for what is returned from RTL and then accepted into a function from RTL or any custom func someone has created.
@pascalduez @AndrewSouthpaw
> [@testing-library/react] Returned union

- definitions/npm/key-mirror_v1.x.x/flow_v0.83.x-/key-mirror_v1.x.x.js
- definitions/npm/key-mirror_v1.x.x/flow_v0.83.x-/test_key-mirror_v1.x.x.js
- definitions/npm/keymirror_v0.1.x/test_keymirror_v0.1.x.js
- Links to documentation: https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/keymirror_v0.1.x/flow_v0.33.x-v0.103.x/keymirror_v0.1.x.js
- Link to GitHub or NPM: https://www.npmjs.com/package/key-mirror
Other notes: Same API and copied from `keymirror`
> [key-mirror] New definition

- docs/faq.md
> [docs] Add faq on history of `$` used in types

- definitions/npm/react-native-url-polyfill_v1.x.x/flow_v0.83.x-/react-native-url-polyfill_v1.x.x.js
- definitions/npm/react-native-url-polyfill_v1.x.x/flow_v0.83.x-/test_react-native-url-polyfill_v1.x.x.js
- Links to documentation: https://github.com/charpeni/react-native-url-polyfill/blob/main/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/react-native-url-polyfill
Other notes:
> [react-native-url-polyfill] New definition

- definitions/npm/copy-pkg_v1.x.x/flow_v0.83.x-/copy-pkg_v1.x.x.js
- definitions/npm/copy-pkg_v1.x.x/flow_v0.83.x-/test_copy-pkg_v1.x.x.js
- Links to documentation: https://www.npmjs.com/package/copy-pkg#usage
- Link to GitHub or NPM: https://www.npmjs.com/package/copy-pkg
Other notes:
> [copy-pkg] New definition

- definitions/npm/chalk_v4.x.x/flow_v0.104.x-/chalk_v4.x.x.js
- definitions/npm/chalk_v4.x.x/flow_v0.104.x-/test_chalk_v4.x.x.js
- Links to documentation: https://github.com/chalk/chalk
- Link to GitHub or NPM: https://github.com/chalk/chalk
Other notes:
> [chalk] Fix bgWhiteBright spelling mistake

- definitions/npm/pretty-bytes_v5.x.x/flow_v0.83.x-/pretty-bytes_v5.x.x.js
- definitions/npm/pretty-bytes_v5.x.x/flow_v0.83.x-/test_pretty-bytes_v5.x.x.js
- Links to documentation: https://github.com/sindresorhus/pretty-bytes/blob/main/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/pretty-bytes
Other notes:
> [pretty-bytes] Add v5

- cli/src/lib/node.js
> [cli] Fix buffer deprecation error

- definitions/npm/ora_v6.x.x/flow_v0.83.x-/ora_v6.x.x.js
- definitions/npm/ora_v6.x.x/flow_v0.83.x-/test_ora_v6.x.x.js
- Links to documentation: https://github.com/sindresorhus/ora/blob/main/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/ora
Other notes: Looks like another use case for base-defs
> [ora] Add v6

- definitions/npm/body-scroll-lock_v4.x.x/flow_v0.83.x-/body-scroll-lock_v4.x.x.js
- definitions/npm/body-scroll-lock_v4.x.x/flow_v0.83.x-/test_body-scroll-lock_v4.x.x.js
- Links to documentation: https://github.com/willmcpo/body-scroll-lock/releases/tag/v4.0.0-beta.0
- Link to GitHub or NPM: https://www.npmjs.com/package/body-scroll-lock
Other notes:
> [body-scroll-lock] Add v4

- definitions/npm/color_v4.x.x/flow_v0.83.x-/color_v4.x.x.js
- definitions/npm/color_v4.x.x/flow_v0.83.x-/test_color_v4.x.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/color/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/color
Other notes: Tests mostly copied from TS https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/color/color-tests.ts
> [color] Add v4

- definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/test_react-router-dom.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.63.x-v0.97.x/react-router-dom_v6.x.x.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.63.x-v0.97.x/test_react-router-dom.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.98.x-v0.103.x/react-router-dom_v6.x.x.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.98.x-v0.103.x/test_react-router-dom.js
Closes #4277
- Links to documentation: https://reactrouter.com/docs/en/v6/api#api-reference
Other notes:
> [react-router-dom] Add v6

- definitions/npm/react-query_v3.x.x/flow_v0.104.x-/react-query_v3.x.x.js
- definitions/npm/react-query_v3.x.x/flow_v0.104.x-/test_react-query.js
- Links to documentation: https://react-query.tanstack.com/reference/useQuery
Other notes:
I also fixed the errors in react-query tests related to method-unbinding.
> react-query_v3: add 'tracked' to notifyOnChangeProps and fix tests

- definitions/npm/axios_v0.26.x/flow_v0.83.x-/axios_v0.26.x.js
- definitions/npm/axios_v0.26.x/flow_v0.83.x-/test_axios_v0.26.x.js
- Links to documentation: https://github.com/axios/axios/releases/tag/v0.26.0
- Link to GitHub or NPM: https://www.npmjs.com/package/axios
Other notes:
> [axios] copy axios 25 to 26

- definitions/npm/react-dom_v18.x.x/flow_v0.127.x-/react-dom_v18.x.x.js
- definitions/npm/react-dom_v18.x.x/flow_v0.127.x-/test_react-dom_v18.x.x.js
Copying 17 to 18 without changes to the API interface
- Links to documentation: https://github.com/facebook/react/releases/tag/v18.0.0
- Link to GitHub or NPM: https://www.npmjs.com/package/react-dom
Other notes:
> [react-dom] Copy 17 to 18 defs

- definitions/npm/@testing-library/react_v13.x.x/flow_v0.104.x-/react_v13.x.x.js
- definitions/npm/@testing-library/react_v13.x.x/flow_v0.104.x-/test_react_v13.x.x.js
Copied from v12
- Links to documentation: https://github.com/testing-library/react-testing-library/releases/tag/v13.0.0
Other notes:
> [@testing-library/react] Add v13

- definitions/npm/axios_v0.27.x/flow_v0.83.x-/axios_v0.27.x.js
- definitions/npm/axios_v0.27.x/flow_v0.83.x-/test_axios_v0.27.x.js
The PR has commits broken down for easier review
- Links to documentation: https://github.com/axios/axios/releases
- Link to GitHub or NPM: https://www.npmjs.com/package/axios
Other notes:
> [axios] Add v0.27 defs

- definitions/npm/react-dom_v18.x.x/flow_v0.127.x-/react-dom_v18.x.x.js
- definitions/npm/react-dom_v18.x.x/flow_v0.127.x-/test_react-dom_v18.x.x.js
Add type defs for `react-dom/client`
- Links to documentation: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html
- Link to GitHub or NPM: https://www.npmjs.com/package/react-dom
Other notes:
> [react-dom] Add client exports

- definitions/npm/fast-deep-equal_v3.x.x/flow_v0.83.x-/fast-deep-equal_v3.x.x.js
- definitions/npm/fast-deep-equal_v3.x.x/flow_v0.83.x-/test_fast-deep-equal_v3.x.x.js
- Links to documentation: https://github.com/epoberezkin/fast-deep-equal/blob/master/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/fast-deep-equal
Other notes: Just showing that current shipped type of TS does not have generics
> [fast-deep-equal] Add definition

- definitions/npm/jest_v28.x.x/flow_v0.134.x-/jest_v28.x.x.js
- definitions/npm/jest_v28.x.x/flow_v0.134.x-/test_jest_v28.x.x.js
- Links to documentation: https://jestjs.io/docs/mock-function-api#mockfnmocklastcall
EDIT: Failing tests, the dreaded missing React stuff... :woman_shrugging:
> [jest_28.x.x] Add mockFn.mock.lastCall property

- definitions/npm/react-query_v3.x.x/flow_v0.104.x-/react-query_v3.x.x.js
- definitions/npm/react-query_v3.x.x/flow_v0.104.x-/test_react-query.js
- Links to documentation: https://react-query.tanstack.com/
- Link to GitHub or NPM: https://github.com/tannerlinsley/react-query
Other notes:
This adds a generic for query keys which the typescript types also do (see [TkDodo's blog post](https://tkdodo.eu/blog/react-query-and-type-script#the-four-generics)). I also fixed tests that weren't actually working as intended.
> react-query: Add generic for query keys

- definitions/npm/spawndamnit_v2.x.x/flow_v0.83.x-/spawndamnit_v2.x.x.js
- definitions/npm/spawndamnit_v2.x.x/flow_v0.83.x-/test_spawndamnit_v2.x.x.js
- Links to documentation: https://github.com/jamiebuilds/spawndamnit/blob/master/index.js & https://github.com/jamiebuilds/spawndamnit/blob/master/promise.js.flow
- Link to GitHub or NPM: https://www.npmjs.com/package/spawndamnit
Other notes:
> [spawndamnit] Add definition

- definitions/npm/throttle-debounce_v4.x.x/flow_v0.83.x-/test_throttle-debounce_v4.x.x.js
- definitions/npm/throttle-debounce_v4.x.x/flow_v0.83.x-/throttle-debounce_v4.x.x.js
- definitions/npm/throttle-debounce_v5.x.x/flow_v0.83.x-/test_throttle-debounce_v5.x.x.js
- definitions/npm/throttle-debounce_v5.x.x/flow_v0.83.x-/throttle-debounce_v5.x.x.js
- v4: [def](https://github.com/seiyab/DefinitelyTyped/blob/4480bcf39c78e6a74d36b87571fa0cfbe5cf0654/types/throttle-debounce/index.d.ts) [tests](https://github.com/seiyab/DefinitelyTyped/blob/4480bcf39c78e6a74d36b87571fa0cfbe5cf0654/types/throttle-debounce/throttle-debounce-tests.ts)
- v5: [def](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/throttle-debounce/index.d.ts) [tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/throttle-debounce/throttle-debounce-tests.ts)
- Link to GitHub or NPM: https://www.npmjs.com/package/throttle-debounce
Other notes:
> [throttle-debounce] Add v4/5 definitions

- .github/ISSUE_TEMPLATE/question.yml
Suggested from #4332
Other notes: @GAntoine @ItsAleph
> [github] Add question issue template

- definitions/npm/human-id_v4.x.x/flow_v0.83.x-/human-id_v4.x.x.js
- definitions/npm/human-id_v4.x.x/flow_v0.83.x-/test_human-id_v4.x.x.js
- Links to documentation: https://www.npmjs.com/package/human-id
- Link to GitHub or NPM: https://www.npmjs.com/package/human-id
Other notes:
> [human-id] New definition

- definitions/npm/@yarnpkg/lockfile_v1.x.x/flow_v0.83.x-/lockfile_v1.x.x.js
- definitions/npm/@yarnpkg/lockfile_v1.x.x/flow_v0.83.x-/test_lockfile_v1.x.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yarnpkg__lockfile/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/@yarnpkg/lockfile
Other notes:
> [@yarnpkg/lockfile] Add definition

- definitions/npm/glob-to-regexp_v0.4.x/flow_v0.83.x-/glob-to-regexp_v0.4.x.js
- definitions/npm/glob-to-regexp_v0.4.x/flow_v0.83.x-/test_glob-to-regexp_v0.4.x.js
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/glob-to-regexp/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/glob-to-regexp
Other notes:
> [glob-to-regexp] Add definition

- definitions/npm/query-string_v5.1.x/flow_v0.104.x-/query-string_v5.1.x.js
- definitions/npm/query-string_v5.1.x/flow_v0.104.x-/test_query-string_v5.1.x.js
- definitions/npm/query-string_v5.x.x/flow_v0.104.x-/query-string_v5.x.x.js
- definitions/npm/query-string_v5.x.x/test_query-string_v5.x.x.js
Closes #2145
- Links to documentation: https://www.npmjs.com/package/query-string
- Link to GitHub or NPM: https://www.npmjs.com/package/query-string
Other notes:
> [query-string] Resolve parse into stringify v5

- definitions/npm/aria-query_v5.x.x/flow_v0.83.x-/aria-query_v5.x.x.js
- definitions/npm/aria-query_v5.x.x/flow_v0.83.x-/test_aria-query_v5.x.x.js
To support future dependency of RTL mentioned in #4344
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aria-query/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/aria-query
Other notes:
> [aria-query]: Add definition

- cli/src/__tests__/cli-test.js
- cli/src/cli.js
- cli/src/commands/install.js
Closes #3122. Seems like a legit request
> [cli] Expose a public api to execute commands

- definitions/npm/outdent_v0.8.x/flow_v0.83.x-/outdent_v0.8.x.js
- definitions/npm/outdent_v0.8.x/flow_v0.83.x-/test_outdent_v0.8.x.js
- Links to documentation: https://www.npmjs.com/package/outdent
- Link to GitHub or NPM: https://www.npmjs.com/package/outdent
Other notes:
> [outdent] New definition

- definitions/npm/tempy_v3.x.x/flow_v0.83.x-/tempy_v3.x.x.js
- definitions/npm/tempy_v3.x.x/test_tempy.js
- Links to documentation: https://github.com/sindresorhus/tempy/blob/main/index.d.ts
Other notes:
Created these by referencing the latest TypeScript definitions for `tempy@3.0.0` and added tests.
> [tempy] Create definitions for v3.x.x

- definitions/npm/axios_v1.x.x/flow_v0.83.x-/axios_v1.x.x.js
- definitions/npm/axios_v1.x.x/flow_v0.83.x-/test_axios_v1.x.x.js
- Links to documentation: https://github.com/axios/axios/releases/tag/v1.0.0
- Link to GitHub or NPM: https://github.com/axios/axios
Other notes:
> [axios] Add v1 copied from 0.27.x

- definitions/npm/json-beautify_v1.x.x/flow_v0.83.x-/json-beautify_v1.x.x.js
- definitions/npm/json-beautify_v1.x.x/flow_v0.83.x-/test_json-beautify_v1.x.x.js
- Links to documentation: https://github.com/gre/json-beautify/blob/master/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/json-beautify
Other notes:
> [json-beautify] Add definition

- definitions/npm/react-dom_v18.x.x/flow_v0.127.x-/react-dom_v18.x.x.js
- definitions/npm/react-dom_v18.x.x/flow_v0.127.x-/test_react-dom_v18.x.x.js
Closes #4390
- Links to documentation: https://www.npmjs.com/package/react-dom
- Link to GitHub or NPM: https://www.npmjs.com/package/react-dom
Other notes:
> [react-dom] Export RootType

- definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/react-redux_v7.x.x.js
- definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connect.js
- definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connectAdvanced.js
- definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connectInfer.js
- definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connectMergeProps.js
- definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_connectThunk.js
- definitions/npm/react-redux_v7.x.x/flow_v0.142.x-/test_useDispatch.js
- definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/react-redux_v8.x.x.js
- definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_connect.js
- definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_connectInfer.js
- definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_connectMergeProps.js
- definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_connectThunk.js
- definitions/npm/react-redux_v8.x.x/flow_v0.142.x-/test_useDispatch.js
Merging https://github.com/flow-typed/flow-typed/pull/4392 from master branch into main.
Having it as a separate PR as dependent definitions could be affected
Other notes:
> [react-redux] Add type argument default and bound to useDispatch

- definitions/npm/base-x_v3.x.x/flow_v0.83.x-/base-x_v3.x.x.js
- definitions/npm/base-x_v3.x.x/flow_v0.83.x-/test_base-x_v3.x.x.js
- definitions/npm/base-x_v4.x.x/flow_v0.83.x-/base-x_v4.x.x.js
- definitions/npm/base-x_v4.x.x/flow_v0.83.x-/test_base-x_v4.x.x.js
- Links to documentation: https://github.com/parcel-bundler/parcel/blob/v2/flow-libs/base-x.js.flow
- Link to GitHub or NPM: https://www.npmjs.com/package/base-x
Other notes:
> [base-x] New definition v3/4

- definitions/npm/backbone_v1.x.x/flow_v0.104.x-/backbone_v1.x.x.js
- definitions/npm/backbone_v1.x.x/test_backbone-v1.x.x.js
Closes #2712
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/backbone/index.d.ts#L237
- Link to GitHub or NPM: https://www.npmjs.com/package/backbone
Other notes:
> [backbone] Fix defaults() func

- definitions/npm/counterpart_v0.18.x/flow_v0.83.x-/counterpart_v0.18.x.js
- definitions/npm/counterpart_v0.18.x/flow_v0.83.x-/test_counterpart_v0.18.x.js
- Links to documentation: https://github.com/martinandert/counterpart/blob/master/README.md
- Link to GitHub or NPM: https://github.com/martinandert/counterpart
Other notes:
This definition was ported from TypeScript. All original comments were kept as-is.
> Add counterpart 0.18

- definitions/npm/glob_v8.x.x/flow_v0.104.x-/glob_v8.x.x.js
- definitions/npm/glob_v8.x.x/flow_v0.42.x-v0.103.x/glob_v8.x.x.js
- definitions/npm/glob_v8.x.x/test_glob_v8.x.x.js
- Links to documentation: https://github.com/isaacs/node-glob/blob/main/README.md
- Link to GitHub or NPM: https://github.com/isaacs/node-glob
Other notes:
- Changelog: https://github.com/isaacs/node-glob/blob/main/changelog.md#80
- Simple copy/paste/rename of the v7 libdef
- Add type import in test to fix error since flow 0.189 (`missing-local-annot`).
> Add Glob v8 libdef

- definitions/npm/@apollo/client_v3.x.x/flow_v0.142.x-/client_v3.x.x.js
- definitions/npm/@apollo/client_v3.x.x/flow_v0.142.x-/test_client_v3.x.x.js
- Links to documentation: https://www.apollographql.com/docs/react/
- Link to GitHub or NPM: https://www.npmjs.com/package/@apollo/client
Other notes:
Closes #4061
> Add @apollo/client libdef

- definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/test_react-router-dom.js
- Link to GitHub or NPM: https://github.com/remix-run/react-router
Other notes:
No changes in type definitions, only move types according to their original package.
This PR will fix https://github.com/flow-typed/flow-typed/issues/4421
> React router dom/reorganize

- definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/react-router-dom_v6.x.x.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.104.x-/test_react-router-dom.js
- Links to documentation: https://reactrouter.com/en/main/hooks/use-search-params
Other notes:
> [react-router-dom] setSearchParams can be passed a function

- definitions/npm/@testing-library/react_v11.x.x/flow_v0.104.x-v0.200.x/test_react_v11.x.x.js
- definitions/npm/@testing-library/react_v11.x.x/flow_v0.201.x-/test_react_v11.x.x.js
- definitions/npm/@testing-library/react_v12.x.x/flow_v0.104.x-v0.200.x/test_react_v12.x.x.js
- definitions/npm/@testing-library/react_v12.x.x/flow_v0.201.x-/test_react_v12.x.x.js
- definitions/npm/@testing-library/react_v13.x.x/flow_v0.104.x-v0.200.x/test_react_v13.x.x.js
- definitions/npm/@testing-library/react_v13.x.x/flow_v0.201.x-/test_react_v13.x.x.js
- definitions/npm/@testing-library/react_v14.x.x/flow_v0.104.x-v0.200.x/react_v14.x.x.js
- definitions/npm/@testing-library/react_v14.x.x/flow_v0.104.x-v0.200.x/test_react_v14.x.x.js
- definitions/npm/@testing-library/react_v14.x.x/flow_v0.201.x-/react_v14.x.x.js
- definitions/npm/@testing-library/react_v14.x.x/flow_v0.201.x-/test_react_v14.x.x.js
Copied from v13, definition is just dropping node versions
- Links to documentation: https://github.com/testing-library/react-testing-library/releases/tag/v14.0.0
Other notes:
> [@testing-library/react] Add v14

- cli/src/commands/__tests__/runTests-test.js
- cli/src/commands/runTests.js
- cli/yarn.lock
Apply changes from https://github.com/flow-typed/flow-typed/pull/4448 into `main` while additionally adding test coverage to validate the change working.
> [cli] Fix a bug from flow that stopped testing for ambiguous obj exactness

- definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/react-router-dom_v6.x.x.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/test_react-router-dom.js
- Links to documentation: https://reactrouter.com/en/main/utils/location
- Link to GitHub or NPM: https://github.com/remix-run/react-router
- Type of contribution:  fix & refactor
> [react-router-dom] refactor LocationShape and fix usage of Link with `useLocation`

- definitions/npm/use-local-storage_v3.x.x/flow_v0.201.x-/test_use-local-storage_v3.x.x.js
- definitions/npm/use-local-storage_v3.x.x/flow_v0.201.x-/use-local-storage_v3.x.x.js
- definitions/npm/use-local-storage_v3.x.x/flow_v0.83.x-v0.200.x/test_use-local-storage_v3.x.x.js
- definitions/npm/use-local-storage_v3.x.x/flow_v0.83.x-v0.200.x/use-local-storage_v3.x.x.js
- Links to documentation: https://www.npmjs.com/package/use-local-storage
- Link to GitHub or NPM: https://www.npmjs.com/package/use-local-storage
Other notes:
> [use-local-storage] Add definition

- definitions/npm/redux_v4.x.x/flow_v0.134.x-v0.200.x/test_createStore.js
- definitions/npm/redux_v4.x.x/flow_v0.201.x-/redux_v4.x.x.js
- definitions/npm/redux_v4.x.x/flow_v0.201.x-/test_applyMiddleware.js
- definitions/npm/redux_v4.x.x/flow_v0.201.x-/test_combineReducers.js
- definitions/npm/redux_v4.x.x/flow_v0.201.x-/test_createStore.js
- definitions/npm/redux_v4.x.x/flow_v0.201.x-/test_custom_dispatch.js
- Links to documentation: https://redux.js.org/api/combinereducers - where a lot of the fixing refactor occurred
- Link to GitHub or NPM: https://www.npmjs.com/package/redux
Other notes:
> [redux] Fix Partial error on newer flow versions

- definitions/npm/jest_v29.x.x/flow_v0.201.x-/test_jest_v29.x.x.js
- Links to documentation: https://npmjs.com/package/jest
- Link to GitHub or NPM: https://npmjs.com/package/jest
Other notes:
> [jest] Fix v29 flow errors in tests

- definitions/npm/chai_v4.x.x/flow_v0.201.x-/chai_v4.x.x.js
- definitions/npm/chai_v4.x.x/test_chai_v4.x.x.js
Closes #4473
- Links to documentation: https://www.npmjs.com/package/chai
- Link to GitHub or NPM: https://www.npmjs.com/package/chai
Other notes:
There was one error I couldn't solve but it's preexisting and only errors on the test so I'll leave it alone for now so I can ship the fix
> [chai] Fix errors on v201+

- definitions/npm/lodash-es_v4.x.x/flow_v0.201.x-/lodash-es_v4.x.x.js
Contributes to https://github.com/flow-typed/flow-typed/issues/4471
- Links to documentation: https://www.npmjs.com/package/lodash-es
- Link to GitHub or NPM: https://www.npmjs.com/package/lodash-es
Other notes: There are lots of errors but trying to simply unblock @simkessy
Before adding my fix the error shows
```
... 23 more warnings (only 50 out of 24 errors and 49 warnings displayed)
To see all errors, re-run Flow with --show-all-errors
```
After adding my fix
```
... 22 more warnings (only 50 out of 23 errors and 49 warnings displayed)
To see all errors, re-run Flow with --show-all-errors
```
> [lodash-es] Fix curry issue

- definitions/npm/@apollo/client_v3.x.x/flow_v0.142.x-/client_v3.x.x.js
- definitions/npm/@apollo/client_v3.x.x/flow_v0.142.x-/test_client_v3.x.x.js
Contributes to #4471
- Links to documentation: https://www.npmjs.com/package/@apollo/client
- Link to GitHub or NPM: https://www.npmjs.com/package/@apollo/client
Other notes:
> [apollo/client] Fix errors on latest version

- definitions/npm/@testing-library/react_v14.x.x/flow_v0.201.x-/react_v14.x.x.js
- definitions/npm/@testing-library/react_v14.x.x/flow_v0.201.x-/test_react_v14.x.x.js
Closes #4489.
- Links to documentation: https://testing-library.com/docs/react-testing-library/api/#renderhook
Other notes:
> [@testing-library/react] Add renderHook function

- definitions/environments/node/flow_v0.155.x-/node.js
- definitions/environments/node/flow_v0.155.x-/test_node.js
- Links to documentation: https://nodejs.org/api/process.html
- Link to GitHub or NPM: https://nodejs.org/api/process.html
Other notes:
> [node] Add process module definitions

- definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/react-router-dom_v6.x.x.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/test_react-router-dom.js
Closes #4492
- Links to documentation: https://reactrouter.com/en/main/components/scroll-restoration
Other notes:
> [react-router-dom] Add ScrollRestoration and future

- definitions/npm/query-string_v6.x.x/test_query-string_v6.x.x.js
- definitions/npm/query-string_v7.x.x/flow_v0.104.x-/query-string_v7.x.x.js
- definitions/npm/query-string_v7.x.x/test_query-string_v7.x.x.js
- Links to documentation: https://github.com/sindresorhus/query-string#parseurlstring-options
- Link to GitHub or NPM: https://github.com/sindresorhus/query-string/commit/ce0609566f64ad6a5bc495ea48ea492265de45bf
> [query-string] Support parseFragmentIdentifier option for parseURL

- definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/react-router-dom_v6.x.x.js
- definitions/npm/react-router-dom_v6.x.x/flow_v0.201.x-/test_react-router-dom.js
Closes #4499
- Links to documentation: https://www.npmjs.com/package/react-router-dom
- Link to GitHub or NPM: https://reactrouter.com/en/main/routers/create-hash-router
Other notes:
> [react-router-dom]: Add missing createHashRouter

- definitions/npm/deepmerge_v4.x.x/flow_v0.201.x-/deepmerge_v4.x.x.js
- definitions/npm/deepmerge_v4.x.x/flow_v0.201.x-/test_deepmerge_v4.x.x.js
Closes #4500
- Links to documentation: https://github.com/TehShrike/deepmerge/blob/master/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/deepmerge
Other notes:
> [deepmerge] Fix arrayMerge options

- definitions/npm/@apollo/client_v3.x.x/flow_v0.142.x-/client_v3.x.x.js
- definitions/npm/@apollo/client_v3.x.x/flow_v0.142.x-/test_client_v3.x.x.js
- definitions/npm/aws-appsync-subscription-link_v3.x.x/flow_v0.142.x-/aws-appsync-subscription-link_v3.x.x.js
- definitions/npm/aws-appsync-subscription-link_v3.x.x/flow_v0.142.x-/config.json
- definitions/npm/aws-appsync-subscription-link_v3.x.x/flow_v0.142.x-/test_aws-appsync-subscription-link_v3.x.x.js
- Links to documentation: https://github.com/awslabs/aws-mobile-appsync-sdk-js#readme
- Link to GitHub or NPM: https://github.com/awslabs/aws-mobile-appsync-sdk-js
Other notes: includes fix to `@apollo/client`
> Add aws-appsync-subscription-link

- definitions/npm/base-64_v1.x.x/flow_v0.83.x-/base-64_v1.x.x.js
- definitions/npm/base-64_v1.x.x/flow_v0.83.x-/test_base-64_v1.x.x.js
Closes #4512
- Links to documentation: https://www.npmjs.com/package/base-64
- Link to GitHub or NPM: https://www.npmjs.com/package/base-64
Other notes:
> [base-64] new definition

- .github/workflows/main.yml
- Links to documentation: https://github.com/actions/setup-node#supported-version-syntax
Other notes: This should hopefully self update the node versions, always testing against the current LTS and current version. As of today 18 and 20.
> [ci] Use dynamic node versions matrix

- definitions/environments/node/flow_v0.155.x-/node.js
- definitions/environments/node/flow_v0.155.x-/test_node.js
- Links to documentation: https://nodejs.org/api/assert.html
Notes: reordered the modules alphabetically in the definition file.
> [env:node] Add assert module

- definitions/npm/body-scroll-lock-upgrade_v1.x.x/flow_v0.83.x-/body-scroll-lock-upgrade_v1.x.x.js
- definitions/npm/body-scroll-lock-upgrade_v1.x.x/flow_v0.83.x-/test_body-scroll-lock-upgrade_v1.x.x.js
Closes #4519
- Links to documentation: https://www.npmjs.com/package/body-scroll-lock-upgrade
- Link to GitHub or NPM: https://www.npmjs.com/package/body-scroll-lock-upgrade
Other notes:
> [body-scroll-lock-upgrade] Add definition

- definitions/npm/use-debounce_v9.x.x/flow_v0.83.x-/test_use-debounce_v9.x.x.js
- definitions/npm/use-debounce_v9.x.x/flow_v0.83.x-/use-debounce_v9.x.x.js
Closes #4526
- Links to documentation: https://www.npmjs.com/package/use-debounce
- Link to GitHub or NPM: https://www.npmjs.com/package/use-debounce
Other notes:
> [use-debounce] Add definition

- definitions/npm/body-scroll-lock-upgrade_v1.x.x/flow_v0.83.x-/body-scroll-lock-upgrade_v1.x.x.js
- definitions/npm/body-scroll-lock-upgrade_v1.x.x/flow_v0.83.x-/test_body-scroll-lock-upgrade_v1.x.x.js
Closes #4543
- Links to documentation: https://www.npmjs.com/package/body-scroll-lock-upgrade
- Link to GitHub or NPM: https://www.npmjs.com/package/body-scroll-lock-upgrade
Other notes:
> [body-scroll-lock-upgrade] Fix module naming

- definitions/environments/node/flow_v0.155.x-/node.js
- definitions/environments/node/flow_v0.155.x-/test_node.js
Closes #4551. This doesn't contain all of worker_threads API, looking at [node docs](https://nodejs.org/api/worker_threads.html) there's some bits missing but as a start this copies exactly from https://github.com/parcel-bundler/parcel/blob/v2/flow-libs/worker_threads.js.flow which hasn't been updated in 4 years it seems. 
- Links to documentation: https://nodejs.org/api/worker_threads.html
Other notes: cc @mischnic
> [worker_threads] Add definition

- definitions/npm/module-alias_v2.x.x/flow_v0.83.x-/module-alias_v2.x.x.js
- definitions/npm/module-alias_v2.x.x/flow_v0.83.x-/test_module-alias_v2.x.x.js
Closes #4548
- Links to documentation: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/module-alias/index.d.ts
- Link to GitHub or NPM: https://www.npmjs.com/package/module-alias
Other notes:
> [module-alias] New definition

- definitions/npm/axios_v1.x.x/flow_v0.201.x-/axios_v1.x.x.js
- definitions/npm/axios_v1.x.x/flow_v0.201.x-/test_axios_v1.x.x.js
- definitions/npm/axios_v1.x.x/flow_v0.83.x-v0.200.x/axios_v1.x.x.js
- definitions/npm/axios_v1.x.x/flow_v0.83.x-v0.200.x/test_axios_v1.x.x.js
- Links to documentation: https://github.com/axios/axios/pull/5010
- Link to GitHub or NPM: https://www.npmjs.com/package/axios
`.clear` was added to axios in [v1.0.0](https://github.com/axios/axios/blob/v1.x/CHANGELOG.md#100---2022-10-04) (PR https://github.com/axios/axios/pull/4248)
Closes #4560
> [axios]: Add definition for interceptor `.clear()`

- definitions/environments/cssom/flow_v0.261.x-/cssom.js
- definitions/environments/serviceworkers/flow_v0.261.x-/serviceworkers.js
- definitions/environments/streams/flow_v0.261.x-/streams.js
- definitions/environments/webassembly/flow_v0.261.x-/webassembly.js
This is the first PR in a series to implement the proposal in https://github.com/flow-typed/flow-typed/issues/4588. This PR focuses on some of the simpler files, that also unfortunately don't have tests in Flow repo itself.
- Link to GitHub or NPM: Copied from https://github.com/facebook/flow/tree/main/lib
> Add some of the flow builtin libdefs to flow-typed

- definitions/environments/dom/flow_v0.261.x-/dom.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_CanvasRenderingContext2D.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_ClipboardEvent.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_CustomEvent.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_DOMTokenList.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_Document.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_Element.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_ErrorEvent.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_HTMLCanvasElement.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_HTMLCollection.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_HTMLElement.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_HTMLFormElement.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_HTMLInputElement.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_HTMLSelectElement.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_MediaSource.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_NamedNodeMap.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_ShadowRoot.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_URL.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_USBConnectionEvent.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_eventtarget.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_path2d.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_registerElement.js
- definitions/environments/dom/flow_v0.261.x-/test_dom_traversal.js
This is the fourth PR in a series to implement the proposal in https://github.com/flow-typed/flow-typed/issues/4588. This PR focuses on the `dom.js` libdef. I also copied over the same test in the Flow repo
- Link to GitHub or NPM: Copied from https://github.com/facebook/flow/tree/main/lib/dom.js
> Add builtin dom libdef from flow into environment

- definitions/environments/bom/flow_v0.261.x-/bom.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_FormData.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_MediaDevices.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_MutationObserver.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_StorageManager.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_URLSearchParams.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_WebUSB.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_crypto.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_fetch.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_headers.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_request.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_response.js
- definitions/environments/bom/flow_v0.261.x-/test_bom_trustedTypes.js
This is the fifth PR in a series to implement the proposal in https://github.com/flow-typed/flow-typed/issues/4588. This PR focuses on the `bom.js` libdef. I also copied over the same test in the Flow repo
- Link to GitHub or NPM: Copied from https://github.com/facebook/flow/tree/main/lib/bom.js
> Add builtin bom libdef from flow into environment

- definitions/environments/jsx/flow_v0.262.x-/jsx.js
- Links to documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel
> Add `rel` to `ReactDOM$linkProps`

- definitions/environments/dom/flow_v0.261.x-/dom.js
- https://url.spec.whatwg.org/#dom-url-parse
- https://github.com/flow-typed/flow-typed/issues/4601
- Type of contribution: addition | fix
> [flow|environment] Add URL.parse

- cli/src/commands/runTests.js
Summary:
It would be helpful to have an option to only run the `environments` definition tests, so this adds one. I don't know if there's a better way to detect "environment" tests outside of inspecting the path, however.
Test Plan:
- `node cli/dist/cli.js run-tests --environmentOnly`
Other notes:
> [flow-typed|cli] Add environmentOnly option to run-tests

- definitions/environments/dom/flow_v0.261.x-/dom.js
- Links to documentation: https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone
Other notes:
https://github.com/flow-typed/flow-typed/issues/4628
> Add structuredClone definition to dom

- definitions/environments/dom/flow_v0.261.x-/dom.js
> Fix ts-syntax issue in dom.js
