flow-typed/flow-typed

underscore/test.js

A bug in the declaration of `_.zip`, caught by a test!

More tests for _

---

mori/.flowconfig
mori/mori.js
mori/test.js
package.json

Glad to see that this repository exists!

Add type definitions for Mori

---

definitions/mori/v0.3/flow-all/mori-v0.3.js
definitions/mori/v0.3/test-mori-v0.3.js

I switched a project from Immutable to Mori, and fixed a lot of type errors that cropped up during the process. During that process I made a number of fixes and improvements to the Mori type definitions.

Updates to Mori definitions

---

README.md

Responding to #19.
If you'd rather word or format this differently, please don't hesitate to close this pull request -- I won't mind, _really_! :smile:

Add a notice to readme.md

---

definitions/mocha_v2.4.x/flow_>=v0.22.x/mocha_v2.4.x.js
definitions/mocha_v2.4.x/test_mocha_v2.4.x_describe.js
definitions/mocha_v2.4.x/test_mocha_v2.4.x_hooks.js
definitions/mocha_v2.4.x/test_mocha_v2.4.x_it.js

Definitions for https://mochajs.org/

mocha definition

---

npm/.eslintrc
npm/package.json
npm/src/cli.js
npm/src/commands/install.js
npm/src/lib/github.js
npm/src/lib/libDef.js

Finished @splodingsocks install command... it's downloading the file and puts it in the CWD's `flow-typed` directory

Install command

---

definitions/redux-form_v5.x.x/flow_>=v0.22.1/redux-form_v5.x.x.js
definitions/redux-form_v5.x.x/test_redux-form_v5.js

- Add a basic redux-form declaration to the library with a basic test

Add redux-form declaration

---

.travis.yml
CONTRIBUTING.md
run_def_tests.sh
runtests.sh
travis.sh

Explains the structure of the repository and the steps needed to write one before sending a pull request.
(cc @nmn -- and of course anyone else -- for feedback)

CONTRIBUTING.md

---

definitions/ramda_v0.21.x/flow_>=v0.23.x/ramda_v0.21.x.js
definitions/ramda_v0.21.x/test_ramda_v0.21.x.js

It's still lacking quite a bit of definitions but is already quite useful. I use mocha to test that what I'm using to type check actually make sense as code. I removed all calls to `expect` and provided fake `it`s and `describe`s so it can be used without mocha.
I planning on finishing the rest of definitions/test within a week

Adds ramda definitions

---

cli/src/cli.js
cli/src/commands/install.js
cli/src/commands/version.js

Useful for seeing which version of the CLI is running

Adds a `flow-typed version` command

---

definitions/npm/ramda_v0.21.x/flow_>=v0.23.x/ramda_v0.21.x.js
definitions/npm/ramda_v0.21.x/test_ramda_v0.21.x.js

This adds lacking List methods. Fantasy land and transducers are left out. Transducers are crazy to write declarations for.

Base list methods are done

---

definitions/npm/rxjs_v5.0.x/flow_>=v0.25.0/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/test_rxjs.js

We've been using these in Nuclide for some time. Thanks to @samwgoldman who contributed the initial version of these.

rxjs 5 declarations

---

definitions/webfontloader_v1.x.x/flow_>=v0.23.x/webfontloader_v1.x.x.js
definitions/webfontloader_v1.x.x/test_webfontloader_v1.x.x.js

For [webfontloader](https://github.com/typekit/webfontloader/).
Wasn't sure how much to test because the config is all optionals.

Add webfontloader definition

---

definitions/npm/big.js_v3.x.x/flow_>=v0.17.x/big.js_v3.x.x.js
definitions/npm/big.js_v3.x.x/test_big.js_v3.x.x.js

http://mikemcl.github.io/big.js/

Add big.js flow definitions

---

README.md

Complementary documentation for update-cache

Add update-cache command documentation to README

---

definitions/npm/react-recaptcha_v2.x.x/flow_>=v0.23.x/react-recaptcha_v2.x.x.js
definitions/npm/react-recaptcha_v2.x.x/flow_>=v0.26.x/react-recaptcha_v2.x.x.js
definitions/npm/react-recaptcha_v2.x.x/test_react-recaptcha-v2.js

Really simple library definition for [react-recaptcha](https://github.com/appleboy/react-recaptcha)

Add libdef for react-recaptcha library

---

definitions/npm/bunyan_v1.x.x/flow_>=v0.21.x/bunyan_v1.x.x.js
definitions/npm/bunyan_v1.x.x/flow_>=v0.21.x/bunyan_v1.x.x.js.flow
definitions/npm/bunyan_v1.x.x/test_bunyan_v1.x.x.js

This should add lib def for bunyan.

Bunyan definition

---

definitions/npm/axios_v0.11.x/flow_>=v0.23.x/axios_v0.11.x.js

Due to new flow version * is needed.

axios add <*>

---

definitions/npm/jasmine_v2.4.x/flow_all/jasmine_v2.4.x.js
definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x_describe.js
definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x_hooks.js
definitions/npm/jasmine_v2.4.x/test_jasmine_v2.4.x_it.js

Following http://jasmine.github.io/2.4/introduction.html and the guidelines for contributing.

support for Jasmine 2.4

---

definitions/npm/chalk_v1.x.x/flow_>=v0.21.x/chalk_v1.x.x.js
definitions/npm/chalk_v1.x.x/test_chalk_v1.x.x.js

This was adapted from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/chalk/chalk.d.ts

Chalk 1.x definitions

---

definitions/npm/object-assign_v4.x.x/flow_>=v0.28.x/object-assign_v4.x.x.js
definitions/npm/object-assign_v4.x.x/test_object-assign_v4.x.x.js

Polyfill for `Object.assign` so it's the same type signature

Support object-assign 4.x

---

definitions/npm/rxjs_v5.0.x/flow_>=v0.25.0/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/test_rxjs.js

Workaround for https://github.com/facebook/flow/issues/2041

Fix rxjs combineLatest

---

definitions/npm/mocha_v2.4.x/flow_>=v0.22.x/mocha_v2.4.x.js
definitions/npm/mocha_v2.4.x/test_mocha_v2.4.x_it.js

As noted in http://mochajs.org/#pending-tests

Expand mocha coverage to include body-less it()

---

definitions/npm/enzyme_v2.3.x/flow_>=v0.23.x_<=v0.27.x/enzyme_v2.3.x.js
definitions/npm/enzyme_v2.3.x/flow_>=v0.28.x/enzyme_v2.3.x.js
definitions/npm/enzyme_v2.3.x/test_enzyme-v2.3.js

https://github.com/flowtype/flow-typed/pull/172#issuecomment-231155706

include .length property on Enzyme's Wrapper

---

.editorconfig

- Add a simple editor editorconfig

Add an editor config for easier colaboration

---

definitions/npm/platform_v1.x.x/flow_>=v0.21.x/platform_v1.x.x.js
definitions/npm/platform_v1.x.x/test_platform_v1.x.x.js

- Add libdef for [platform](https://github.com/bestiejs/platform.js/blob/master/doc/README.md#readme)
- Add tests for it.

[libdef] platform v1.x

---

definitions/npm/bcrypt_v0.8.x/flow_>=v0.29.x/bcrypt_v0.8.x.js
definitions/npm/bcrypt_v0.8.x/test_bcrypt_v0.8.x.js

Add types for `bcrypt` module.
refs. https://github.com/ncb000gt/node.bcrypt.js#api

Add bcrypt module definitions

---

definitions/npm/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js

The route parameter "path" can be also a RegExp (look here: https://expressjs.com/en/guide/routing.html)

Added type RegExp to route methods

---

definitions/npm/shelljs_v0.7.x/flow_>=v0.28.x/shelljs_v0.7.x.js
definitions/npm/shelljs_v0.7.x/test_shelljs_v0.7.x.js

This PR just includes some fixes and a bit of cleanup for the `shelljs` declarations.

Shelljs fixes; change types for Shell{Array,String}

---

definitions/npm/bigi_v1.x.x/flow_all/bigi_v1.x.x.js
definitions/npm/bigi_v1.x.x/test_bigi_v1.x.x.js

Bigi is "just another" big integer implementation.
https://github.com/cryptocoinjs/bigi
I just went through all the bigi tests and added them to the definitions, since bigi seems to have OK test coverage

Bigi definitions

---

definitions/npm/node-hid_v0.x.x/flow_>=v0.17.x/node-hid_v0.x.x.js
definitions/npm/node-hid_v0.x.x/test_node-hid-v0.js

Adding definitions for https://github.com/node-hid/node-hid

Add node-hid definition

---

definitions/npm/bitcoinjs-lib_v2.x.x/flow_>=v0.17.x/bitcoinjs-lib_v2.x.x.js
definitions/npm/bitcoinjs-lib_v2.x.x/test_bitcoinjs-lib_v2.x.x.js

I have added SOME definitions for `bitcoinjs-lib`.
Bitcoin.js is a rather large library, I have made only a part of all the classes. The classes I have defined should be complete though.
Again this library depends on `bigi` and `ecurve`, and because I didn't know how to do that, I just copy-pasted the definitions. It seems to work, even when it's icky.

[WIP] Add part of bitcoinjs-lib

---

definitions/npm/moment_v2.x.x/flow_>=v0.28.x/moment_v2.x.x.js

Fix return type of calendar mémoment_v2.x.x.js

Fix moment_v2.x.x.js

---

definitions/npm/meow_v3.x.x/flow_>=v0.28.x/meow_v3.x.x.js
definitions/npm/meow_v3.x.x/test_meow_v3.x.x.js

Update Meow type definition

---

definitions/npm/axios_v0.13.x/flow_>=v0.28.x/axios_v0.13.x.js
definitions/npm/axios_v0.13.x/test_axios-v0.13.js

1. Updated the library defition to include all the [configuration options](https://github.com/mzabriskie/axios#request-config).
2. Added the [actual exports](https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L1).

libdef: Axios v0.13.x Updates and Improvements

---

definitions/npm/moment_v2.x.x/flow_>=v0.28.x/moment_v2.x.x.js

relevant documentation:
set: http://momentjs.com/docs/#/get-set/set/ (addresses #222)
local: http://momentjs.com/docs/#/manipulating/local/
utc: http://momentjs.com/docs/#/manipulating/utc/
utcOffset: http://momentjs.com/docs/#/manipulating/utc-offset/

Fixes to Moment

---

definitions/npm/map-obj_v1.x.x/flow_>=v0.28.x/map-obj_v1.x.x.js

Not sure how much it'll actually help in practice, but I read an article by @thejameskyle and this kept bugging me in my head.

Slightly improve types of map-obj

---

definitions/npm/http-errors_v1.x.x/flow_>=v0.28.x/http-errors_v1.x.x.js
definitions/npm/http-errors_v1.x.x/test_http-errors_v1.x.x.js

https://www.npmjs.com/package/http-errors

initial http-errors

---

definitions/npm/he_v1.x.x/flow_>=v0.28.x/he_v1.x.x.js
definitions/npm/he_v1.x.x/test_he_v1.js

https://github.com/mathiasbynens/he

Initial he libdefs

---

definitions/npm/file-type_v3.x.x/flow_>=v0.28.x/file-type_v3.x.x.js
definitions/npm/file-type_v3.x.x/test_file-type_v3.x.x.js

https://www.npmjs.com/package/file-type

initial file-type

---

definitions/npm/multi-typeof_v1.x.x/flow_>=v0.25.x/multi-typeof_v1.x.x.js
definitions/npm/multi-typeof_v1.x.x/test_multi-typeof_v1.x.x.js

I think I followed the contributing guidelines correctly. (Thanks for the thorough walkthrough!)
Please let me know if I can do anything else.

Add multi-typeof

---

definitions/npm/twit_v2.x.x/flow_>=v0.28.x/twit_v2.x.x.js
definitions/npm/twit_v2.x.x/test_twit_v2.x.x.js

https://www.npmjs.com/package/twit

initial twit

---

definitions/npm/random-js_v1.x.x/flow_>=v0.28.x/random-js_v1.x.x.js
definitions/npm/random-js_v1.x.x/test_random-js_v1.x.x.js

https://www.npmjs.com/package/random-js

initial random-js

---

definitions/npm/redux-saga_v0.11.x/flow_>=v0.28.x/redux-saga_v0.11.x.js
definitions/npm/redux-saga_v0.11.x/test_redux-saga_0.11.x.js

This took me a while,... but I got something useful.
Would be happy if someone could review it!
@thejameskyle @marudor @yelouafi

Add redux-saga libdefs

---

definitions/npm/in-range_v1.x.x/flow_>=v0.25.x/in-range_v1.x.x.js
definitions/npm/in-range_v1.x.x/test_in-range_v1.x.x.js

https://www.npmjs.com/package/in-range

Add libdef for in-range

---

definitions/npm/checkstyle-formatter_v1.x.x/flow_>=v0.25.x/checkstyle-formatter_v1.x.x.js
definitions/npm/checkstyle-formatter_v1.x.x/test_checkstyle-formatter_v1.x.x.js

https://www.npmjs.com/package/checkstyle-formatter

Add libdef for checkstyle-formatter

---

definitions/npm/redux-saga_v0.11.x/flow_>=v0.28.x/redux-saga_v0.11.x.js
definitions/npm/redux-saga_v0.11.x/test_redux-saga_0.11.x.js

There were some minor problems with redux libdefs e.g.
applyMiddleware. Also fixed the @@iterator problem with `takeLatest` /
`takeEvery`.
Credit goes to @aaronjensen

Fix problems with redux interop

---

definitions/npm/deep-freeze-strict_v1.x.x/flow_>=v0.25.x/deep-freeze-strict_v1.x.x.js
definitions/npm/deep-freeze-strict_v1.x.x/test_deep-freeze-strict_v1.x.x.js

https://www.npmjs.com/package/deep-freeze-strict

Add libdef for deep-freeze-strict

---

definitions/npm/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js

fix: add static callable for Router

---

definitions/npm/redux-form_v5.x.x/flow_>=v0.22.1/redux-form_v5.x.x.js
definitions/npm/redux-form_v5.x.x/test_redux-form_v5.js

Just wanted to add some of the missing input props.

Update: add improved defs for redux-form@v5

---

definitions/npm/vscode_v0.11.x/flow_>=v0.32.x/vscode_v0.11.x.js
definitions/npm/vscode_v0.11.x/test_vscode_v0.11.x.js

I'm cleaning up https://github.com/flowtype/flow-for-vscode before publishing it, and for v0.32.0 I needed a better definition for vscode. So I converted https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts by hand.

Add definition for vscode 0.11.x

---

definitions/npm/marked_v0.3.x/flow_>=v0.28.x/marked_v0.3.x.js
definitions/npm/marked_v0.3.x/flow_v0.28.x-/marked_v0.3.x.js
definitions/npm/marked_v0.3.x/test_marked_v0.3.x.js

This PR add libdefs for [Marked](https://www.npmjs.com/package/marked) NPM package.

Implement libdefs for Marked

---

definitions/npm/semver_v5.1.x/flow_v0.27.0-/semver_v5.1.x.js
definitions/npm/semver_v5.1.x/test_semver.js

Adds the `semver.Range` class to the libdef

Update semver with Range class

---

definitions/npm/react-redux_v4.x.x/flow_v0.30.x-/react-redux_v4.x.x.js
definitions/npm/react-redux_v4.x.x/test_react-redux_v4.x.x.js

This is in response to my comment on #116. I got this working in my project and added some tests for the specific cases that I changed. Would be good for @nmn to take a look at it.

Fix react redux types

---

definitions/npm/flow-bin_v0.x.x/flow_v0.25.x-/flow-bin_v0.x.x.js
definitions/npm/flow-bin_v0.x.x/test_flow-bin.js

The `flow-bin` package is pretty straightforward. Here's a libdef for it

Add libdef for `flow-bin` package

---

definitions/npm/blacklist_v1.x.x/flow_v0.28.x-/blacklist_v1.x.x.js
definitions/npm/blacklist_v1.x.x/test_blacklist_v1.x.x.js

Adding a basic library definition for the blacklist module. It would be good to be able to replace the `Object` types, and use something like $Diff advanced type, but I am not sure exactly how that works, open to suggestions.

Library Definition for blacklist v1 

---

definitions/npm/isomorphic-fetch_v2.x.x/flow_v0.25.x-/isomorphic-fetch_v2.x.x.js
definitions/npm/isomorphic-fetch_v2.x.x/flow_v0.27.x-/isomorphic-fetch_v2.x.x.js
definitions/npm/isomorphic-fetch_v2.x.x/test_isomorphic-fetch_v2.js

Refactored isomorphic interfact to use the types defined in:
https://github.com/facebook/flow/blob/v0.32.0/lib/bom.js
Also increase the supported flow version from 0.27.x to 0.25.x

Improved isomorphic-fetch definitions to be inline with the spec

---

definitions/npm/marked_v0.3.x/flow_v0.28.x-/marked_v0.3.x.js

This  PR makes all libdefs for marked global under `marked$[...]`.

make libdefs for marked global under marked$*

---

definitions/npm/underscore_v1.x.x/flow_v0.13.x-/underscore_v1.x.x.js

Add declaration for `keys`

---

definitions/npm/react-helmet_v3.x.x/flow_v0.26.x-/react-helmet_v3.x.x.js
definitions/npm/react-helmet_v3.x.x/test_react-helmet.js

Adding a library definition from [`react-helmet`](https://github.com/nfl/react-helmet).

Update: add basic libdef for react-helmet

---

definitions/npm/jasmine_v2.4.x/flow_all/jasmine_v2.4.x.js

This just fixes a small thing I noticed that was missing.

Jasmine: add missing toHaveBeenCalledTimes method

---

definitions/npm/i18next_v2.x.x/flow_v0.23.x-/i18next_v2.x.x.js
definitions/npm/i18next_v2.x.x/test_i18next-v2.js

Fixed an issue where the resources was not the correct type, added a better definition.

i18next init resources was not correct type

---

definitions/npm/safe-regex_v1.x.x/flow_all/safe-regex_v1.x.x.js
definitions/npm/safe-regex_v1.x.x/test_safe-regex-v1.js

Simply adding the safe-regex library definition

Update: add safe-regex libdef

---

definitions/npm/enzyme_v2.3.x/flow_v0.23.x-v0.27.x/enzyme_v2.3.x.js
definitions/npm/enzyme_v2.3.x/flow_v0.28.x-/enzyme_v2.3.x.js

I've already added this to my local def to fix flow from breaking, but I'm sure others would like to see this added to this lib def.
If there are any others I can add while I'm here or that you'd like to add, let me know.

Add isEmpty to Wrapper def for enzyme

---

definitions/npm/axios_v0.15.x/flow_v0.28.x-/axios_v0.15.x.js
definitions/npm/axios_v0.15.x/test_axios-v0.15.js

add Cancellation & proxy settings

add axios v0.15

---

definitions/npm/react-addons-css-transition-group_v15.x.x/flow_v0.26.x-/react-addons-css-transition-group_v15.x.x.js
definitions/npm/react-addons-css-transition-group_v15.x.x/test_react-addons-css-transition-group.js

Library defition for the react-addons-css-transition-group

Add react-addons-css-transition-group library defintion

---

definitions/npm/left-pad_v1.x.x/flow_v0.25.x-/left-pad_v1.x.x.js
definitions/npm/left-pad_v1.x.x/test_left-pad_v1.x.x.js

As per https://twitter.com/lbljeffmo/status/788055941073731584

Add left-pad definition file

---

definitions/.eslintrc
definitions/package.json

Add flowtype/no-weak-types lint rule in definitions

---

definitions/npm/@kadira/storybook_v1.x.x/flow_v0.30.x-/storybook_v1.x.x.js
definitions/npm/@kadira/storybook_v1.x.x/test_storybook_v1.x.x.js

Hey.  I put this together for my own project, and thought it might be useful for others.
I tried to follow the definition and test style from other packages.  Am I missing anything?

Add react-storybook module definition

---

definitions/npm/graceful-fs_v4.1.x/flow_v0.28.x-/graceful-fs_v4.1.x.js
definitions/npm/graceful-fs_v4.1.x/test_graceful-fs_v4.1.x.js

graceful-fs is the node fs api, with the addition of the method `graceful-fs.gracefulify()`.

Add graceful-fs definition

---

definitions/npm/ical-generator_v0.2.x/flow_v0.28.x-/ical-generator_v0.2.x.js
definitions/npm/ical-generator_v0.2.x/test_ical-generator-v0.2.js

https://github.com/sebbo2002/ical-generator

ical-generator

---

definitions/npm/cat-names_v1.x.x/flow_v0.34.x-/cat-names_v1.x.x.js
definitions/npm/cat-names_v1.x.x/test_cat-names_v1.x.x.js

Declaration for  `cat-names`
https://github.com/sindresorhus/cat-names

Add declaration for `cat-names`

---

definitions/npm/rivets_v0.9.x/flow_v0.33.x-/rivets_v0.9.x.js
definitions/npm/rivets_v0.9.x/test_rivets-v0.9.x.js

Libdef for [Rivets.js](http://rivetsjs.com/)

[libdef] add rivets libdef and tests

---

definitions/npm/bunyan_v1.x.x/flow_v0.21.x-/bunyan_v1.x.x.js
definitions/npm/bunyan_v1.x.x/test_bunyan_v1.x.x.js

https://github.com/trentm/node-bunyan#streams as reference

type is optional for streams

---

definitions/npm/xstream_v7.x.x/flow_v0.33.0-/xstream_v7.x.x.js
definitions/npm/xstream_v7.x.x/test_xstream.js

Just copy version 6 files, because there are no breaking changes
See xstream changelog: https://github.com/staltz/xstream/blob/master/CHANGELOG.md

Add xstream@7

---

definitions/npm/normalizr_v2.x.x/flow_v0.23.x-/normalizr_v2.x.x.js
definitions/npm/normalizr_v2.x.x/test_normalizr-v2.js

e.g. the TS definition https://github.com/paularmstrong/normalizr/blob/102630015d5f1ebea3cf02c470a27aba891f3a7a/index.d.ts#L30

normalizr: can take an array of objects

---

definitions/npm/lodash_v4.x.x/flow_v0.28.x-/lodash_v4.x.x.js

union does not work atm., this fixes it.

splat signature require an additional array container

---

.travis.yml
cli/src/lib/fileUtils.js

Node 7 has arrived!
https://nodejs.org/en/blog/release/v7.0.0/

Use node v6.1 and v7.0 in travis

---

definitions/npm/jest_v16.x.x/flow_v0.33.x-/jest_v16.x.x.js
definitions/npm/jest_v16.x.x/test_jest-v16.x.x.js
definitions/npm/jest_v17.x.x/flow_v0.33.x-/jest_v17.x.x.js
definitions/npm/jest_v17.x.x/test_jest-v17.x.x.js

This closes #449
Please review @marudor @jeffmo

Update Jest definition for toThrowError

---

definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/test_rxjs.js

Add distinct type and tests

---

definitions/npm/continuation-local-storage_v3.x.x/flow_v0.25.x-/continuation-local-storage_v3.x.x.js
definitions/npm/continuation-local-storage_v3.x.x/test_continuation-local-storage_v3.x.x.js

added type definitions for continuation-local-storage. let me know if it looks okay

Add definition for continuation-local-storage.v3.x.x

---

definitions/npm/pg_v6.x.x/flow_v0.32.x-/pg_v6.x.x.js
definitions/npm/pg_v6.x.x/test_pg_v6.x.x.js

`any` types exised in this file, cause of currently `mixed` did not work well in Function Overloading.
`Function` types exised in this file, cause of they come from another untyped npm lib.

Typed pg(node_postgres).

---

definitions/npm/intl-messageformat_v1.x.x/flow_v0.32.x-/intl-messageformat_v1.x.x.js
definitions/npm/intl-messageformat_v1.x.x/test_intl-messageformat.js

See package here: https://www.npmjs.com/package/intl-messageformat

add definitions for intl-messageformat

---

definitions/npm/flux-standard-action_v1.x.x/flow_v0.28.x-/flux-standard-action_v1.x.x.js
definitions/npm/flux-standard-action_v1.x.x/test_flux-standard-action_v1.js

Adding definitions from flux standard actions

flux-standard-action v1

---

definitions/npm/pg_v6.x.x/flow_v0.32.x-/pg_v6.x.x.js
definitions/npm/pg_v6.x.x/test_pg_v6.x.x.js

Although the format was specified as optional flow can not handle it being absent without explicit definition

pg TypeParser tests & fix for optional format

---

definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js
definitions/npm/chai_v3.5.x/test_chai_v3.5.x.js

This is to add definitons for `chai.assert` and associated functions (http://chaijs.com/api/assert/)

Chai's assert style api

---

definitions/npm/express_v4.x.x/flow_v0.28.x-/test_overrideUseMethodClassExtension.js

Bug Fix: Adding correct constructor definition in test

Adding constructor & the expected misuse error

---

definitions/npm/cpy_v5.x.x/flow_v0.36.x-/cpy_v5.x.x.js
definitions/npm/cpy_v5.x.x/test_cpy_v5.x.x.js

Had to hijack PR #487 because the original branch was still on a very old flow-typed version ... thanks for the contribution @thejameskyle

Add thejameskyles cpy libdef

---

definitions/npm/moment_v2.x.x/flow_v0.28.x-/moment_v2.x.x.js
definitions/npm/moment_v2.x.x/test_moment-v2.js

I slightly organized the test file, following the categorisation used in moment's docs. It's possible to create a test file for each category, but it might be a bit premature.

Allow Moment#Subract(Object)

---

definitions/npm/inquirer_v2.x.x/flow_v0.25.x-/inquirer_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_bottom_bar_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_checkbox_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_editor_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_expand_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_hierarchical_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_input_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_list_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_long_list_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_nested_call_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_password_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_pizza_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_rawlist_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_recursive_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_rx_observable_array_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_rx_observable_create_v2.x.x.js
definitions/npm/inquirer_v2.x.x/test_when_v2.x.x.js

See https://github.com/SBoudrias/Inquirer.js
Tests are all original examples of inquirer.js (slightly adapted for type safetiness).
Rx API currently not supported, since I don't know how to define dependencies to RxJS libdefs in a seamless manner

Add inquirer libdefs

---

definitions/npm/jest_v16.x.x/flow_v0.33.x-/jest_v16.x.x.js
definitions/npm/jest_v16.x.x/test_jest-v16.x.x.js
definitions/npm/jest_v17.x.x/flow_v0.33.x-/jest_v17.x.x.js
definitions/npm/jest_v17.x.x/test_jest-v17.x.x.js
definitions/npm/jest_v18.x.x/flow_v0.33.x-/jest_v18.x.x.js
definitions/npm/jest_v18.x.x/test_jest-v18.x.x.js

https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-1600
@cpojer pretty bad description, any idea for a better one?

Add test.concurrent to jest 16, 17 and 18

---

definitions/npm/bluebird_v3.x.x/flow_v0.32.x-/bluebird_v3.x.x.js
definitions/npm/bluebird_v3.x.x/test_bluebird-v3.x.x.js

http://bluebirdjs.com/docs/api/spread.html

Add bluebird spread

---

definitions/npm/parse_v1.9.x/flow_v0.37.x-/parse_v1.9.x.js
definitions/npm/parse_v1.9.x/test_parse.v1.9.x.js

Added definition for [Parse JS SDK](https://github.com/ParsePlatform/Parse-SDK-JS). 
Some less used modules are still not defined (and marked as TODO).

Added parse definition

---

definitions/npm/mersenne-twister_v1.x.x/flow_v0.33.x-/mersenne-twister_v1.x.x.js
definitions/npm/mersenne-twister_v1.x.x/test_mersenne-twister_v1.x.x.js

Adds types for https://github.com/boo1ean/mersenne-twister.

mersenne-twister types

---

definitions/npm/jest_v17.x.x/flow_v0.33.x-/jest_v17.x.x.js
definitions/npm/jest_v17.x.x/test_jest-v17.x.x.js
definitions/npm/jest_v18.x.x/flow_v0.33.x-/jest_v18.x.x.js
definitions/npm/jest_v18.x.x/test_jest-v18.x.x.js

https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-1703

Add toHaveLength matcher to jest 17 and 18

---

definitions/npm/react-native-audio-toolkit_v1.x.x/flow_v0.32.x-/react-native-audio-toolkit_v1.x.x.js
definitions/npm/react-native-audio-toolkit_v1.x.x/test_react-native-audio-toolkit-v1.js

This is my first attempt at writing a Flow binding, so please tell me where to improve.

Add definition for react-native-audio-toolkit

---

definitions/npm/moment_v2.x.x/flow_v0.28.x-/moment_v2.x.x.js

Add moment's updateLocale method

---

definitions/npm/chalk_v1.x.x/flow_v0.21.x-/chalk_v1.x.x.js
definitions/npm/chalk_v1.x.x/test_chalk_v1.x.x.js

chalk_v1.x.x was failing in react-native project due to missing method/property (dim).

fix chalk_v1.x.x failing in react-native project

---

definitions/npm/xorshift_v1.x.x/flow_v0.32.0-/xorshift_v1.x.x.js
definitions/npm/xorshift_v1.x.x/test_xorshift_v1.x.x.js

https://github.com/AndreasMadsen/xorshift

Definition for xorshift

---

definitions/npm/mkdirp_v0.5.x/flow_v0.25.0-/mkdirp_v0.5.x.js
definitions/npm/mkdirp_v0.5.x/test_mkdirp_v0.5.x.js

https://www.npmjs.com/package/mkdirp

Definition for mkdirp

---

definitions/npm/isemail_v2.2.x/flow_v0.31.1-/isemail_v2.2.x.js
definitions/npm/isemail_v2.2.x/test_isemail_v2.2.x.js

https://github.com/hapijs/isemail

Definition for module isemail

---

definitions/npm/checkdigit_v1.1.x/flow_v0.25.0-/checkdigit_v1.1.x.js
definitions/npm/checkdigit_v1.1.x/test_checkdigit_v1.1.x.js

https://www.npmjs.com/package/checkdigit

Definition for module checkdigit

---

definitions/npm/reselect_v2.x.x/flow_v0.37.x-/reselect_v2.x.x.js
definitions/npm/reselect_v2.x.x/test_reselect_2.x.x.js

Based on @RiddleMan’s work in https://github.com/reactjs/reselect/pull/164.

Add libdef for reselect 2.x

---

definitions/npm/imurmurhash_v0.1.x/flow_v0.25.0-/imurmurhash_v0.1.x.js
definitions/npm/imurmurhash_v0.1.x/test_imurmurhash_v0.1.x.js

https://www.npmjs.com/package/imurmurhash

Definition for module imurmurhash

---

definitions/npm/moment_v2.x.x/flow_v0.28.x-/moment_v2.x.x.js

References:
duration: https://github.com/moment/moment/blob/develop/src/lib/duration/prototype.js
toISOString: https://github.com/moment/moment/blob/develop/src/lib/duration/iso-string.js

Add toISOString to moment$Duration

---

definitions/npm/react-redux_v5.x.x/flow_v0.30.x-/react-redux_v5.x.x.js
definitions/npm/react-redux_v5.x.x/flow_v0.30.x-/test_Provider.js
definitions/npm/react-redux_v5.x.x/flow_v0.30.x-/test_connect.js

Even though the major version bumped, the API didn't change
https://github.com/reactjs/react-redux/releases/tag/v5.0.0

add react-redux v5 (same as v4)

---

definitions/npm/koa_v2.x.x/flow_v0.37.x-v0.37.x/koa_v2.x.x.js
definitions/npm/koa_v2.x.x/flow_v0.37.x-v0.37.x/test_koa_v2.x.x.js
definitions/npm/koa_v2.x.x/flow_v0.38.x-/koa_v2.x.x.js
definitions/npm/koa_v2.x.x/flow_v0.38.x-/test_koa_v2.x.x.js

Fix koa callback (#636)

---

definitions/npm/next_v2.x.x/flow_v0.38.x-/next_v2.x.x.js
definitions/npm/next_v2.x.x/test_next_v2.x.x.js

I wrote next.js definition.
ref. https://github.com/zeit/next.js/pull/973

Add next v2.x.x def

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.38-/react-router-dom_v4.x.x.js
definitions/npm/react-router-dom_v4.x.x/test_react-router-dom.js
definitions/npm/react-router-native_v4.x.x/flow_v0.38.x-/react-router-native_v4.x.x.js
definitions/npm/react-router-native_v4.x.x/test_react-router-native.js
definitions/npm/react-router_v4.x.x/flow_v0.38.x-/react-router_v4.x.x.js
definitions/npm/react-router_v4.x.x/test_react-router.js

Now that the API is meant to be stable, here are some flowtype definitions for v4.
I'm not sure what the policy on betas are, but these should be good to go.

Add react router v4

---

definitions/npm/flatbuffers_v1.5.x/flow_v0.38.x-/flatbuffers_v1.5.x.js
definitions/npm/flatbuffers_v1.5.x/flow_v0.38.x-/test_flatbuffers_v1.5.x.js

This PR is to add the definition of FlatBuffers.
FlatBuffers: http://google.github.io/flatbuffers/
NPM package: https://www.npmjs.com/package/flatbuffers
Thank you.

FlatBuffers: add flatbuffers_v1.5.x

---

CONTRIBUTING.md

Let people know not to rename the repo folder

---

definitions/npm/alasql_v0.3.x/flow_v0.25.x-/alasql_v0.3.x.js
definitions/npm/alasql_v0.3.x/test_alasql_v0.3.x.js

Add AlaSQL

---

cli/src/commands/runTests.js
cli/src/lib/git.js
cli/src/lib/libDefs.js
travis.sh

This is my attempt on Testing only the libDefs that got changed.
Please have a look. It is pretty simple.
@jeffmo @ryyppy

Test only changed defs

---

definitions/npm/jest_v18.x.x/flow_v0.33.x-/jest_v18.x.x.js
definitions/npm/jest_v19.x.x/flow_v0.33.x-/jest_v19.x.x.js
definitions/npm/jest_v19.x.x/test_jest-v19.x.x.js

Introduce jest_v19.x.x

---

definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.33.x/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/test_rxjs.js

Ported from the TS defs in the RxJS repo.

RxJS: Add bindCallback and bindNodeCallback

---

definitions/npm/underscore_v1.x.x/flow_v0.13.x-v0.37.x/underscore_v1.x.x.js
definitions/npm/underscore_v1.x.x/flow_v0.38.x-/test_underscore.js
definitions/npm/underscore_v1.x.x/flow_v0.38.x-/underscore_v1.x.x.js
definitions/npm/underscore_v1.x.x/test_underscore-v1.js

add underscore bind and bindAll definition
Referencing underscore documentation and existing lodash flowtype definition

add underscore bind bindAll

---

cli/src/commands/runTests.js

I came across issue #542 when I was hitting a similar problem to @AgentME so decided to have a look at providing a simple implementation that addressed the need as described.  It doesn't implement the solution as per what I described in my comment on that issue, but I think it's a pretty good way to go.
Thoughts?

[cli] support offline and github failures for run-tests command

---

definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js

RxJS: Add miscellaneous missing arguments

---

definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js

RxJS: Add delay arguments type

---

definitions/npm/getit_v1.x.x/flow_v0.34.x-/getit_v1.x.x.js
definitions/npm/getit_v1.x.x/test_getit_v1.x.x.js

Another simple package of mine (again not widely used), but pretty useful for things I've done in the past.  First attempt at using namespaced types so hopefully I've done it right :)

implement getit libdef for flow_v0.34.x-

---

definitions/npm/bluebird_v3.x.x/flow_v0.32.x-v0.32.x/bluebird_v3.x.x.js
definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js
definitions/npm/bluebird_v3.x.x/test_bluebird-v3.x.x.js

Just adding an alias for thenReturn. I also added tests for return and thenReturn

adding an alias for bluebird's return -> thenReturn

---

cli/src/commands/runTests.js
cli/src/lib/isInFlowTypedRepo.js
run_def_tests.cmd

- Added a windows shell script to run tests
- Fixed #728
- Fixed #567

Some initial changes needed to run tests in widnows environment

---

cli/src/lib/__tests__/npmLibDefs-test.js
definitions/npm/selenium-webdriver_v3.x.x/flow_v0.42.x-/selenium-webdriver_v3.x.x.js
definitions/npm/selenium-webdriver_v3.x.x/flow_v0.42.x-/test_selenium-webdriver_v3.x.x.js

Fixes https://github.com/flowtype/flow-typed/issues/733

Add "selenium-webdriver"

---

definitions/npm/jest_v19.x.x/flow_v0.33.x-/jest_v19.x.x.js
definitions/npm/jest_v19.x.x/test_jest-v19.x.x.js

Documented here: https://facebook.github.io/jest/docs/jest-object.html#jestclearallmocks
And functionally tested against jest 19.0.2.

Add jest.clearAllMocks()

---

definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js

See http://chaijs.com/api/assert/#method_throws.

Add assert.throws to chai definitions

---

definitions/npm/mixpanel-browser_v2.11.x/flow_v0.25.x-/mixpanel-browser_v2.11.x.js
definitions/npm/mixpanel-browser_v2.11.x/test_mixpanel-browser_v2.11.x.js
definitions/npm/mixpanel_v0.6.x/flow_v0.25.x-/mixpanel_v0.6.x.js
definitions/npm/mixpanel_v0.6.x/test_mixpanel_v0.6.x.js
definitions/npm/react-mixpanel_v0.0.x/flow_v0.26.x-/react-mixpanel_v0.0.x.js
definitions/npm/react-mixpanel_v0.0.x/test_react-mixpanel_v0.0.x.js

Including the server-side node library, client-side browser library, and React wrapper.

Add libdef for Mixpanel Libraries

---

definitions/npm/redux_v3.x.x/flow_v0.33.x-/redux_v3.x.x.js

Updates to redux flow based on conversation [here](https://github.com/reactjs/redux/pull/2115)

define CombinedReducer type for redux_v3.x.x

---

definitions/npm/awaiting_v2.x.x/flow_v0.33.x-/awaiting_v2.x.x.js
definitions/npm/awaiting_v2.x.x/flow_v0.33.x-/test_awaiting.js

https://github.com/hunterloftis/awaiting

Add libdefs for awaiting

---

definitions/npm/underscore_v1.x.x/flow_v0.38.x-/test_underscore.js
definitions/npm/underscore_v1.x.x/flow_v0.38.x-/underscore_v1.x.x.js

Let me know if that `any` annotation is problematic!

Add definition for `_.toArray`

---

definitions/npm/validator_v7.x.x/flow_v0.38.x-/validator_v7.x.x.js
definitions/npm/validator_v7.x.x/test_validator_v7.x.x.js

https://www.npmjs.com/package/validator

Libdefs for 'validator'

---

definitions/npm/graphql-server-module-graphiql_v0.7.x/flow_v0.34.x-/graphql-server-module-graphiql_v0.7.x.js
definitions/npm/graphql-server-module-graphiql_v0.7.x/test_graphql-server-module-graphiql_v0.7.x.js

Based on the upstream TypeScript definitions
https://github.com/apollographql/graphql-server/tree/master/packages/graphql-server-module-graphiql

Libdefs for graphql-server-module-graphiql

---

definitions/npm/ramda_v0.21.x/flow_v0.31.x-/ramda_v0.21.x.js
definitions/npm/ramda_v0.21.x/flow_v0.31.x-/test_ramda_v0.21.x_cjs_modules.js
definitions/npm/ramda_v0.21.x/flow_v0.31.x-/test_ramda_v0.21.x_es_modules.js
definitions/npm/ramda_v0.21.x/flow_v0.31.x-/test_ramda_v0.21.x_functions.js
definitions/npm/ramda_v0.21.x/flow_v0.31.x-/test_ramda_v0.21.x_list.js
definitions/npm/ramda_v0.21.x/flow_v0.31.x-/test_ramda_v0.21.x_logic.js
definitions/npm/ramda_v0.21.x/flow_v0.31.x-/test_ramda_v0.21.x_misc.js
definitions/npm/ramda_v0.21.x/flow_v0.31.x-/test_ramda_v0.21.x_object.js
definitions/npm/ramda_v0.21.x/flow_v0.31.x-/test_ramda_v0.21.x_relation.js

Duplicated "flow_v0.28.x-v0.30.x" and commented out a few that were failing. Follow-up PR needed to fix functions and tests that started failing in v31 (only a few) + clean up.

Ramda: Adding support for Flow v0.31.x-

---

definitions/npm/styled-components_v1.4.x/flow_v0.25.x-/styled-components_v1.4.x.js
definitions/npm/styled-components_v1.4.x/test_styled-components_v1.4.x.js

https://github.com/styled-components/styled-components/issues/686

styled-components: Fix keyframes definition

---

definitions/npm/next_v2.x.x/flow_v0.37.x-/next_v2.x.x.js

Fix next.js libdef issues and strengthen render typings

---

definitions/npm/underscore_v1.x.x/flow_v0.38.x-/test_underscore.js
definitions/npm/underscore_v1.x.x/flow_v0.38.x-/underscore_v1.x.x.js

Update the flow types for underscore, so that developers can now correctly type wrapped underscore types.

Update underscore bindings

---

definitions/npm/firebase_v2.4.2/flow_v0.34.x-/firebase_v2.4.2.js
definitions/npm/firebase_v2.4.2/test_firebase_v2.4.2.js

Add definitions for firebase

---

definitions/npm/rxjs_v5.0.x/flow_v0.29.0-v0.33.x/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/test_rxjs.js

rxjs: Add index to predicate functions; thisArg to filer

---

definitions/npm/fantasy-options_v0.0.1/flow_v0.44.x-/fantasy-options_v0.0.1.js
definitions/npm/fantasy-options_v0.0.1/flow_v0.44.x-/test_options.js

There are a couple of test cases that I think should cause errors (they do at runtime) but fail to type check. They are noted in the test file with comments.
I'm not sure how to solve those right now, help would be appreciated.

Add fantasy-options definition

---

definitions/npm/log4js_v1.x.x/flow_v0.34.x-/log4js_v1.x.x.js
definitions/npm/log4js_v1.x.x/flow_v0.34.x-/test_log4js.js

Add definitions for log4js_v1.x.x

---

definitions/npm/jasmine_v2.4.x/flow_all/jasmine_v2.4.x.js

jasmine.createSpy can called without argument

jasmine.createSpy can called without argument

---

definitions/npm/redux-mock-store_v1.2.x/flow_v0.34.x-/redux-mock-store_v1.2.x.js
definitions/npm/redux-mock-store_v1.2.x/test_redux-mock-store_v1.js

First time submitting a type-def, please feel free to give feedback as I'm not sure if I'm doing this 100% right.

Add redux-mock-store type definitions

---

definitions/npm/base-64_v0.1.x/flow_v0.30.x-/base-64_v0.1.x.js
definitions/npm/base-64_v0.1.x/test_base-64_v0.1.x.js

https://www.npmjs.com/package/base-64

Added flow types for base-64

---

definitions/npm/papaparse_v4.x.x/flow_v0.39.x-/papaparse_v4.x.x.js
definitions/npm/papaparse_v4.x.x/test_papaparse_v4.x.x.js

Definitions for PapaParse.js

---

definitions/npm/type-is_v1.x.x/flow_v0.40.x-/type-is_v1.x.x.js
definitions/npm/type-is_v1.x.x/test_type-is_v1.x.x.js

I need help to improve `mixed` types

add definition for type-is

---

definitions/npm/react-flip-move_v2.9.x/flow_v0.31.x-/react-flip-move_v2.9.x.js
definitions/npm/react-flip-move_v2.9.x/test_react-flip-move_v2.9.x.js

This is basically a slightly modified version of [`typings.js`](https://github.com/joshwcomeau/react-flip-move/blob/213673fd58bf0925fc796cfe52d2a17f597ebe6c/src/typings.js) from library sources

react-flip-move

---

definitions/npm/redux-loop_v2.2.x/flow_v0.33.x-/redux-loop_v2.2.x.js
definitions/npm/redux-loop_v2.2.x/flow_v0.33.x-/test_combineReducers.js
definitions/npm/redux-loop_v2.2.x/flow_v0.33.x-/test_effects.js
definitions/npm/redux-loop_v2.2.x/flow_v0.33.x-/test_loop.js

redux-loop is "A library that ports Elm's effect system to Redux"
https://github.com/redux-loop/redux-loop

Add redux-loop v2.2.x libdef

---

definitions/npm/express_v4.x.x/flow_v0.25.x-v0.27.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.28.x-v0.31.x/express_v4.x.x.js
definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js

Hi, `Response#set()` should be able to take an array as `val`.
https://github.com/expressjs/express/blob/4.14.1/lib/response.js#L701

express: pass an array value to Response#set()

---

definitions/npm/react-redux_v4.x.x/flow_v0.30.x-/react-redux_v4.x.x.js

Wrapped react component this.props was unable to infer types for properties defined in SP

Remove recursive definition

---

definitions/npm/redux-actions_v1.x.x/flow_v0.23.x-/redux-actions_v1.x.x.js
definitions/npm/redux-actions_v1.x.x/test_redux-actions-v1.x.x.js

- still would like to improve the types here a bit more, but added the new functions and the changes in requiring defaultState

redux-actions v1 simple upgrades

---

definitions/npm/chai_v3.5.x/flow_v0.24.0-/chai_v3.5.x.js

Added missing extensible, sealed and frozen property.

Added missing properties to chai definition

---

definitions/npm/redux-form_v5.x.x/flow_v0.22.1-/redux-form_v5.x.x.js

I got this error: Component. Application of polymorphic type needs <list of 3 arguments>. (Can use `*` for inferrable ones)

redux-form: Fix react component type

---

definitions/npm/angular_v1.4.7/flow_v0.37.x/angular_v1.4.7.js
definitions/npm/angular_v1.4.7/flow_v0.37.x/test_angular_v1.4.7.js

This is a start on #361.
These are some types I've put together as a result of working with Angular 1.4.7. Generally Angular's types seem fairly grounded but I've yet to test them against other minor versions. There are definitely some gaps. Some of them are even in the declared types.
Also if someone has a better suggestion for how to define Angular's dependency injection, that would be awesome. The current pattern is an Array with strings (arg names) and a function as a last element whose arg count matches the number of strings. I'd be super happy for just something that declared the last element needs to be a function.

Angular 1.x

---

definitions/npm/enzyme_v2.3.x/flow_v0.28.x-/enzyme_v2.3.x.js

https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/setState.md#setstatestate-callback--self

enzyme setState takes an optional callback

---

definitions/npm/moment_v2.x.x/flow_v0.34.x-/moment_v2.x.x.js

Updates the moment isSame definition to fix issue #888

Fixes #888

---

definitions/npm/moment_v2.x.x/flow_v0.34.x-/moment_v2.x.x.js
definitions/npm/moment_v2.x.x/test_moment-v2.js

Fixes signature of utcOffset() for moment_v2.x.x.js.

Fix moment_v2.x.x.js typedef for utcOffset()'s setter part

---

definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js
definitions/npm/moment_v2.x.x/flow_v0.34.x-/moment_v2.x.x.js

The `isBetween` method of moment has a from/to combo, not just from.

Update the moment definition for `isBetween`

---

definitions/npm/redux-forms-react_v0.10.x/flow_v0.38.x-/redux-forms-react_v0.10.x.js
definitions/npm/redux-forms-react_v0.10.x/flow_v0.38.x-/test_redux-forms-react_v0.10.x.js
definitions/npm/redux-forms-react_v0.11.x/flow_v0.38.x-/redux-forms-react_v0.11.x.js
definitions/npm/redux-forms-react_v0.11.x/flow_v0.38.x-/test_redux-forms-react_v0.11.x.js
definitions/npm/redux-forms_v0.10.x/flow_v0.38.x-/redux-forms_v0.10.x.js
definitions/npm/redux-forms_v0.10.x/flow_v0.38.x-/test_redux-forms_v0.10.x.js
definitions/npm/redux-forms_v0.11.x/flow_v0.38.x-/redux-forms_v0.11.x.js
definitions/npm/redux-forms_v0.11.x/flow_v0.38.x-/test_redux-forms_v0.11.x.js

https://github.com/oreqizer/redux-forms

Add libdef for Redux Forms and Redux Forms React

---

definitions/npm/fluture_v6.x.x/flow_v0.34.x-/fluture_v6.x.x.js
definitions/npm/fluture_v6.x.x/flow_v0.34.x-/test_fluture_v6.x.x.js

The flow types for https://github.com/fluture-js/Fluture

Add fluture v6 types

---

definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js

Reference:
http://facebook.github.io/jest/docs/en/expect.html#tohavebeenlastcalledwitharg1-arg2-

Add Jest toHaveBeenLastCalledWith assert method

---

definitions/npm/styled-components_v2.x.x/flow_v0.25.x-/styled-components_v2.x.x.js
definitions/npm/styled-components_v2.x.x/test_styled-components_native_v2.x.x.js
definitions/npm/styled-components_v2.x.x/test_styled-components_v2.x.x.js

https://github.com/styled-components/styled-components/issues/843
cc @ryyppy

Add libdef for styled-components v2

---

definitions/npm/balanced-match_v0.x.x/flow_v0.40.x-/balanced-match_v0.x.x.js
definitions/npm/balanced-match_v0.x.x/test_balanced-match_v0.x.x.js

https://github.com/juliangruber/balanced-match

Add balanced-match 0.x definition

---

definitions/npm/reduce-function-call_v1.x.x/flow_v0.40.x-/reduce-function-call_v1.x.x.js
definitions/npm/reduce-function-call_v1.x.x/test_reduce-function-call_v1.x.x.js

https://github.com/MoOx/reduce-function-call

Add reduce-function-call declaration

---

definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js

as you can see at http://expressjs.com/en/4x/api.html#express.router this method is allowed to have options.

allow using optional options in express-router

---

definitions/npm/dateformat_v2.x.x/flow_v0.41.x-/dateformat_v2.x.x.js
definitions/npm/dateformat_v2.x.x/test_dateformat_v2.x.x.js

Add type definition for [dateformat](https://github.com/felixge/node-dateformat)

Add dateformat definitions

---

definitions/npm/flyd_v0.x.x/flow_v0.34.x-/flyd_v0.x.x.js
definitions/npm/flyd_v0.x.x/flow_v0.34.x-/test_flyd_v0.x.x.js

I'm using these already by manually including them in my project, I'm
just looking to pay it forward.  :)
I initially thought the tests were failing but I was using the globally-installed `flow-typed` cmd.  Seems fine when running with the local util.
Happy to handle any feedback, ~~and I'd love some suggestions on how to handle generics. (I've wasted a bunch of time trying to make it work...)~~
Generics work and the tests should pass now. (Famous last words.)

Adding initial types for flyd

---

definitions/npm/ramda_v0.x.x/flow_v0.23.x-v0.27.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.28.x-v0.30.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.34.x-/ramda_v0.x.x.js

R.T only returns true and R.F only returns false
so their return type should not be a boolean
but a true/false iteral

Fix typing for R.T and R.F

---

definitions/npm/fixed-data-table-2_v7.x.x/flow_v0.47.x-/fixed-data-table-2_v7.x.x.js
definitions/npm/fixed-data-table-2_v7.x.x/test_fixed-data-table-2_v7.x.x.js

Hi there,
This adds a libdef for https://github.com/schrodinger/fixed-data-table-2/. 
Please let me know if anything should be changed!

Add libdef for fixed-data-table-2

---

definitions/npm/jest_v20.x.x/flow_v0.33.x-/jest_v20.x.x.js
definitions/npm/jest_v20.x.x/test_jest-v20.x.x.js

Hi,
add `jest-enzyme` plugin `toMatchElement()` new assertion declaration.
Also add tests for the plugin.

Add jest-enzyme toMatchElement new assertion

---

definitions/npm/react-select_v1.x.x/flow_v0.48.x-/react-select_v1.x.x.js
definitions/npm/react-select_v1.x.x/test_react-select_v1.x.x.js

This PR provides initial type definitions for the nice [React-Select](https://github.com/JedWatson/react-select) library.
I don't expect these to be even nearly perfect. But maybe we can improve together now that they are available.

Initial type definitions for react-select

---

definitions/npm/react-select_v1.x.x/flow_v0.48.x-/react-select_v1.x.x.js
definitions/npm/react-select_v1.x.x/test_react-select_v1.x.x.js

- filterOption and wrapperStyle should be optional
- Select should be a default export

Fix filterOption and wrapperStyle definitions and to use default export

---

definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/test_lodash-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/test_lodash-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.47.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.47.x-/test_lodash-v4.x.x.js

Lodash: isString should accept boolean value

---

definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/test_lodash-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/test_lodash-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.47.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.47.x-/test_lodash-v4.x.x.js

[lodash_v4.x.x] Adds fromIndex to find and findLast

---

definitions/npm/ramda_v0.x.x/flow_v0.34.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.34.x-/test_ramda_v0.x.x_list.js

http://ramdajs.com/0.19.1/docs/#scan

Fix definition for ramda scan

---

definitions/npm/reselect_v2.x.x/flow_v0.37.x-/reselect_v2.x.x.js
definitions/npm/reselect_v3.x.x/flow_v0.37.x-/reselect_v3.x.x.js

Hey,
I would like to add a T16 struct to the reselect files in order to support an additional parameter in SelectorCreator type.

Added T16 option to reselect/SelectorCreator definitions.

---

definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js

this property is missing from the typedef

adds a `connection` property to express$Request

---

definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/recompose_v0.24.x-.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_branch.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_defaultProps.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_getContext.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_mapProps.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_mapPropsStream.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_onlyUpdateForKeys.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_onlyUpdateForPropTypes.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_pure.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_shouldUpdate.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_statics.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_toClass.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_utils.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_voodoo.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_withContext.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_withHandlers.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_withProps.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_withPropsOnChange.js
definitions/npm/recompose_v0.24.x-/flow_v0.49.x-/test_withStateHandlers.js

definitions for [recompose](https://github.com/acdlite/recompose)
PS:
travis check seems like broken as error I see have nothing with this PR

Add recompose definitions

---

definitions/npm/koa-bunyan-logger_v2.x.x/flow_v0.46.x-/koa-bunyan-logger_v2.x.x.js
definitions/npm/koa-bunyan-logger_v2.x.x/test_koa_bunyan_logger_v2.x.x.js

Hi, please accept this PR for koa-bunyan-logger v2

Add koa-bunyan-logger v2.x.x definitions

---

definitions/npm/normalize-styled_v1.x.x/flow_v0.49.x-/normalize-styled_v1.x.x.js

I am not actually sure what types of tests to add for this, but I am open for suggestions if anyone has an idea.

Add basic support normalize-styled

---

definitions/npm/body-parser_v1.x.x/flow_v0.30.x-/body-parser_v1.x.x.js

[body-parser_v1] Fix typo in revival method

---

definitions/npm/promise-retry_v1.1.x/flow_v0.45.x-/promise-retry_v1.1.x.js
definitions/npm/promise-retry_v1.1.x/flow_v0.45.x-/test_promise-retry.js

https://www.npmjs.com/package/promise-retry

Add flow types for promise-retry

---

definitions/npm/popper.js_v1.1.x/flow_v0.50.x-/popper.js_v1.1.x.js
definitions/npm/popper.js_v1.1.x/test_popper.js-v1.js

I tried to run the tests locally but it's stuck on the download of the Flow versions...

Add Popper.js defs

---

definitions/npm/recompose_v0.24.x/flow_v0.47.x-/recompose_v0.24.x.js
definitions/npm/recompose_v0.24.x/flow_v0.47.x-/test_withProps.js

- export Component type
- fix withProps definition

Fix recompose libdef

---

definitions/npm/bluebird_v3.x.x/flow_v0.32.x-v0.32.x/bluebird_v3.x.x.js
definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js
definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/test_bluebird_v3.x.x.js
definitions/npm/bluebird_v3.x.x/test_bluebird_v3.x.x.js

Fixes #1082 
Changes mirror the current API at http://bluebirdjs.com/docs/api-reference.html
I'm no pro with this lib, so I'll reach out to the issue's OP, and have him check that my changes are accurate.

[bluebird_v3.x.x] Promisable type option to Promise/input param on some methods

---

definitions/npm/lodash_v4.x.x/flow_v0.47.x-/lodash_v4.x.x.js

see lodash docs [findIndex](https://lodash.com/docs/4.17.4#findIndex) and [findLastIndex](https://lodash.com/docs/4.17.4#findLastIndex)

Fix lodash findIndex and findLastIndex definitions

---

definitions/npm/is-url-superb_v2.x.x/flow_all/is-url-superb_v2.x.x.js
definitions/npm/is-url-superb_v2.x.x/test_is-url-superb_v2.x.x.js

This patch adds a libdef for [`is-url-superb`](https://github.com/sindresorhus/is-url-superb).

Add is-url-superb

---

definitions/npm/koa-bunyan-logger_v2.x.x/flow_v0.39.x-/koa-bunyan-logger_v2.x.x.js
definitions/npm/koa-bunyan-logger_v2.x.x/test_koa_bunyan_logger_v2.x.x.js

<https://github.com/koajs/bunyan-logger/blob/2x/index.js#L33>

Fix koa-bunyan-logger 2.x primary export

---

definitions/npm/react-typekit_v1.x.x/flow_v0.30.x/react-typekit_v1.x.x.js
definitions/npm/react-typekit_v1.x.x/test_react-typekit_v1.x.x.js

https://github.com/coreyleelarson/react-typekit

adding support for react-typekit

---

definitions/npm/react-typekit_v1.x.x/test_react-typekit_v1.x.x.js
definitions/npm/styled-components_v2.x.x/flow_v0.25.x-v0.33.x/styled-components_v2.x.x.js
definitions/npm/styled-components_v2.x.x/flow_v0.25.x-v0.33.x/test_styled-components_native_v2.x.x.js
definitions/npm/styled-components_v2.x.x/flow_v0.25.x-v0.33.x/test_styled-components_v2.x.x.js
definitions/npm/styled-components_v2.x.x/flow_v0.34.x-/styled-components_v2.x.x.js
definitions/npm/styled-components_v2.x.x/flow_v0.34.x-/test_styled-components_native_v2.x.x.js
definitions/npm/styled-components_v2.x.x/flow_v0.34.x-/test_styled-components_v2.x.x.js

Addressing https://github.com/flowtype/flow-typed/issues/1110

Fixing tests for styled-components

---

definitions/npm/dog-ceo_v1.x.x/flow_v0.28.x-/dog-ceo_v1.x.x.js
definitions/npm/dog-ceo_v1.x.x/test_dog-ceo.js

This patch adds a libdef for [dog-ceo](https://github.com/Aehmlo/node-dog-ceo).

Add dog-ceo libdef

---

definitions/npm/discord.js_v11.1.x/flow_v0.47.x-/discord.js_v11.1.x.js
definitions/npm/discord.js_v11.1.x/test_discord.js_v11.1.js

This patch rewrites the discord.js tests and also fixes a couple of issues regarding inheritance of `Channel` and `GuildChannel`.

Redo discord.js tests

---

definitions/npm/sanitize-html_v1.x.x/flow_v0.16.x-/sanitize-html_v1.x.x.js

this is even in the docs: https://www.npmjs.com/package/sanitize-html#node-recommended

sanitize-html-allow arbitrary object as allowedAttributes

---

definitions/npm/react-redux_v4.x.x/flow_v0.53.x-/react-redux_v4.x.x.js
definitions/npm/react-redux_v4.x.x/flow_v0.53.x-/test_Provider.js
definitions/npm/react-redux_v4.x.x/flow_v0.53.x-/test_connect.js
definitions/npm/react-redux_v5.x.x/flow_v0.30.x-v0.52.x/test_connect.js
definitions/npm/react-redux_v5.x.x/flow_v0.53.x-/react-redux_v5.x.x.js
definitions/npm/react-redux_v5.x.x/flow_v0.53.x-/test_Provider.js
definitions/npm/react-redux_v5.x.x/flow_v0.53.x-/test_connect.js

just an FYI: prettier doesn't like the `test_Provider.js`, but if I change the parser to flow, it is fine. I don't know if you want to do that or not.

fix react-redux for flow v0.53

---

definitions/npm/react-jss_v7.x.x/flow_v0.30.x-v0.52.x/react-jss_v7.x.x.js
definitions/npm/react-jss_v7.x.x/test_react-jss_v7.x.x.js

@kof could you please take a look?

Add typings for react-jss@7.x.x

---

definitions/npm/react-redux_v5.x.x/flow_v0.53.x-/react-redux_v5.x.x.js
definitions/npm/react-redux_v5.x.x/flow_v0.53.x-/test_Provider.js
definitions/npm/react-redux_v5.x.x/flow_v0.53.x-/test_connect.js

Fixes https://github.com/flowtype/flow-typed/issues/1154

Adding createProvider

---

definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.47.x-/lodash_v4.x.x.js

- Fixes "SyntaxError: default is a reserved word" from eslint
- Commit hook has also reformatted this file

Rename parameter so that it does not conflict with a reserved word

---

definitions/npm/quill-delta_v3.5.x/flow_v0.47.x-/quill-delta_v3.5.x.js
definitions/npm/quill-delta_v3.5.x/test_quill-delta_v3.5.x.js

https://www.npmjs.com/package/quill-delta
https://github.com/quilljs/delta

Add quill-delta v3.5.x

---

definitions/npm/node-version_v1.1.x/flow_v0.25.x-/node-version_v1.1.x.js
definitions/npm/node-version_v1.1.x/test_node-version_v1.1.x.js

[![Sponsored by Immowelt](https://img.shields.io/badge/sponsored%20by-immowelt-yellow.svg?colorB=ffb200)](https://stackshare.io/immowelt-group/)
This PR adds library definitions for the [node-version](https://github.com/srod/node-version) package.
/cc @marudor

Add lib defs for node-version@1.1.x

---

definitions/npm/is-lts_v1.0.x/flow_v0.25.x-/is-lts_v1.0.x.js
definitions/npm/is-lts_v1.0.x/test_is-lts_v1.0.x.js

[![Sponsored by Immowelt](https://img.shields.io/badge/sponsored%20by-immowelt-yellow.svg?colorB=ffb200)](https://stackshare.io/immowelt-group/)
This PR adds library definitions for the [is-lts](https://github.com/evanlucas/is-lts) package.
/cc @marudor

Add lib defs for is-lts@1.0.x

---

definitions/npm/axios_v0.16.x/flow_v0.25.x-/axios_v0.16.x.js

Fixed broken definition for AxiosXHR type.

Fix $AxiosXHR type for axios_v0.16.x

---

definitions/npm/classnames_v2.x.x/flow_v0.25.x-/classnames_v2.x.x.js

https://github.com/JedWatson/classnames#alternate-dedupe-version

Include dedupe in exported modules

---

definitions/npm/node-polyglot_v2.x.x/flow_v0.25.0-/node-polyglot_v2.x.x.js
definitions/npm/node-polyglot_v2.x.x/test_node-polyglot_v2.x.x.js

[![Sponsored by Immowelt](https://img.shields.io/badge/sponsored%20by-immowelt-yellow.svg?colorB=ffb200)](https://stackshare.io/immowelt-group/)
This PR adds library definitions for the [node-polyglot](https://github.com/airbnb/polyglot.js) package.
/cc @marudor

Add library definitions for node-polyglot

---

definitions/npm/bee-queue_v1.x.x/flow_v0.25.0-/bee-queue_v1.x.x.js
definitions/npm/bee-queue_v1.x.x/test_bee-queue.js

Definitions for https://github.com/bee-queue/bee-queue

Add definitions for bee-queue

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.53.x-/react-router-dom_v4.x.x.js
definitions/npm/react-router_v4.x.x/flow_v0.53.x-/react-router_v4.x.x.js
definitions/npm/react-router_v4.x.x/flow_v0.53.x-/test_react-router.js

https://github.com/ReactTraining/react-router/blob/d24dd2085d932c1ab03ce54db1f0f7a9f5bbbfe6/packages/react-router/modules/Route.js#L22-L25
`Route` children allow `React$Node`.

Implove react-router/react-router-dom definition

---

definitions/npm/deepmerge_v1.x.x/flow_v0.25.x-/deepmerge_v1.x.x.js
definitions/npm/deepmerge_v1.x.x/test_deepmerge_v1.x.x.js

Add definitions for https://github.com/KyleAMathews/deepmerge

Add definitions for deepmerge

---

definitions/npm/underscore_v1.x.x/flow_v0.50.x-/test_underscore.js
definitions/npm/underscore_v1.x.x/flow_v0.50.x-/underscore_v1.x.x.js

- _.defaults is quite flexible according to its implementation
- add more test cases

Fix type definition for defaults

---

definitions/npm/underscore_v1.x.x/flow_v0.50.x-/test_underscore.js
definitions/npm/underscore_v1.x.x/flow_v0.50.x-/underscore_v1.x.x.js
definitions/npm/underscore_v1.x.x/test_underscore-v1.js

- update definition for filter
- add/update test cases for filter
- add test cases for union

More explicit definition for filter

---

definitions/npm/chai_v4.x.x/flow_v0.15.0-/chai_v4.x.x.js
definitions/npm/chai_v4.x.x/test_chai_v4.x.x.js

All I did was add `definitions/npm/chai_v4.x.x/flow_v0.15.0-/chai_v4.x.x.js#41` and `feature/chai-nested#60`... the `nested.property` chain.
Could your `lint-staged` precommit hook be changing the entire file?

feat(chai): add nested property chain

---

definitions/npm/axios_v0.16.x/flow_v0.25.x-/axios_v0.16.x.js

this was showing me errors in my project when I tried to access any of the AxiosError properties

fixes AxiosResponseInterceptor

---

definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js
definitions/npm/mongoose_v4.x.x/test_mongoose-v4.js

Timestamps in Mongoose can be boolean or an object with alternative created/updated names: http://mongoosejs.com/docs/guide.html#timestamps

Fixed mongoose Schema timestamp

---

definitions/npm/react-router_v4.x.x/flow_v0.53.x-/react-router_v4.x.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/test_rxjs.js

Per the [API](https://reacttraining.com/react-router/web/api/StaticRouter/context-object) this POJO can contain anything

Fixed StaticRouterContext definition in react-router v4.x.x

---

definitions/npm/jquery_v3.x.x/flow_v0.28.x-/jquery_v3.x.x.js

Fields present per http://api.jquery.com/jQuery.ajax/#jqXHR

fix: added responseText and status to jqXHR

---

definitions/browser/doubleclick-gpt_150.x.x/flow_v0.51.x-/doubeclick-gpt_150.x.x.js
definitions/browser/test_doubleclick-gpt_150.x.x.js
definitions/package.json

Add doubleclick-gpt definitions. There a few complications as this is the first non NPM module
added. Please see related ticket: #1259

Feature: Doubleclick GPT

---

cli/src/lib/npm/__tests__/__npmLibDefs-fixtures__/getInstalledNpmLibDefs/unscopedLibDefs/flow-typed/npm/react-redux_v5.x.x.js
cli/src/lib/npm/__tests__/npmLibDefs-test.js
cli/src/lib/npm/npmLibDefs.js

Handle installed libDefs with an upper-bound in the flow-typed version.

---

definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.55.x-/test_lodash-v4.x.x.js

Looks like prettier did its thing on the test file, but the new tests are at the bottom.

Make lodash memoize retain type information

---

definitions/npm/lockfile_v1.x.x/flow_v0.47.x-/lockfile_v1.x.x.js
definitions/npm/lockfile_v1.x.x/flow_v0.47.x-/test_lockfile_v1.x.x.js

Add type definitions for `lockfile`. 
https://www.npmjs.com/package/lockfile

Add libdef for lockfile v0.1.x for flow >= 0.47.x

---

definitions/npm/chai_v4.x.x/flow_v0.15.0-/chai_v4.x.x.js

* http://chaijs.com/api/assert/#method_closeto
* http://chaijs.com/api/assert/#method_approximately

Add closeTo and approximately to chai types

---

cli/package.json
cli/src/lib/npm/__tests__/npmLibDefs-test.js

Strengthen builds from failing

---

definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js

I saw that express missed express$Router.param (http://expressjs.com/en/api.html#app.param). I'm not sure if I typed it 100% correct, but it works in my project.
Best Regards,
Kenneth

Adds express$Router.param

---

definitions/npm/reselect_v3.x.x/flow_v0.34.x-/reselect_v3.x.x.js
definitions/npm/reselect_v3.x.x/test_reselect_3.x.x.js

This fixes the error found in https://github.com/facebook/flow/issues/4959. This is _likely_ a Flow bug that can be fixed by a libdef change. Or this is a libdef bug that's got exposed by Flow's higher strictness.

reselect for flow v0.54

---

definitions/npm/ioredis_v3.x.x/flow_v0.46.x-/ioredis_v3.x.x.js
definitions/npm/ioredis_v3.x.x/test_ioredis_v3.x.x.js

Add ioredis definition

---

definitions/npm/react-collapsible_v2.0.x/flow_v0.54.x-/react-collapsible_v2.0.x.js
definitions/npm/react-collapsible_v2.0.x/test_react-collapsible_v2.0.x.js

It adds flow definitions for [react-collapsible](https://github.com/glennflanagan/react-collapsible) package

Add flow definitions for react-collapsible package

---

definitions/npm/rmdir-sync_v1.x.x/flow_v0.47.x-/rmdir-sync_v1.x.x.js
definitions/npm/rmdir-sync_v1.x.x/flow_v0.47.x-/test_rmdir-sync_v1.x.x.js

Add type definition for `rmdir-sync`
https://www.npmjs.com/package/rmdir-sync

Add libdef for rmdir-sync v0.1.x for flow >= 0.47.x

---

cli/src/commands/runTests.js

Skip testing flow versions 0.57 before 0.57.3 on the Windows platform

Fix for issue #1371

---

definitions/npm/pino_v3.x.x/flow_v0.54.0-/pino_v3.x.x.js
definitions/npm/pino_v3.x.x/test_pino_v3.js

This patch adds typings for the [`pino`](https://www.npmjs.com/package/pino) package.

Add pino v3 typings

---

cli/src/lib/flowVersion.js
cli/src/lib/npm/__tests__/npmLibDefs-test.js

Fixes rebasing cache when an installed libdef is flow_all

---

definitions/npm/sockjs-client_v1.x.x/flow_v0.25.x-/sockjs-client_v1.x.x.js
definitions/npm/sockjs-client_v1.x.x/flow_v0.25.x-/test_sockjs-client-v1.js

Here's libdef for https://github.com/sockjs/sockjs-client

Add library definition for sockjs-client_v1.x.x

---

definitions/npm/jsverify_v0.8.x/flow_v0.34.x-/jsverify_v0.8.x.js
definitions/npm/jsverify_v0.8.x/flow_v0.34.x-/test_example.js
definitions/npm/jsverify_v0.8.x/flow_v0.34.x-/test_oneof.js
definitions/npm/jsverify_v0.8.x/flow_v0.34.x-/test_record.js

These are translated directly from the TypeScript definitions in `jsverify`: https://github.com/jsverify/jsverify/blob/master/lib/jsverify.d.ts

Add type defs for jsverify@0.8.x

---

definitions/npm/md5_v1.0.x/flow_v0.25.x-/md5_v1.0.x.js
definitions/npm/md5_v1.0.x/test_md5_v1.0.x.js

Here's libdef for https://github.com/pvorb/node-md5

Add library definition md_v1.0.x

---

definitions/npm/redux-saga-thunk_v0.5.x/flow_v0.25.x-/redux-saga-thunk_v0.5.x.js
definitions/npm/redux-saga-thunk_v0.5.x/test_redux-saga-thunk_v0.5.x.js

For https://github.com/diegohaz/redux-saga-thunk

Add library definition redux-saga-thunk_v0.5.x

---

definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/test_rxjs.js

RXjs observable buffer methods

---

definitions/npm/chai_v3.5.x/flow_v0.15.0-/chai_v3.5.x.js
definitions/npm/chai_v3.5.x/test_chai_v3.5.x.js
definitions/npm/chai_v4.x.x/flow_v0.15.0-/chai_v4.x.x.js
definitions/npm/chai_v4.x.x/test_chai_v4.x.x.js

Adds chai-redux-mock-store to chai definitions

---

definitions/npm/koa-route_v3.2.x/flow_v0.25.x-/koa-route_v3.2.x.js
definitions/npm/koa-route_v3.2.x/test_koa-route_v3.2.x.js

Adds definitions for koa-route

---

cli/flow-typed/npm/jest_v20.x.x.js
definitions/npm/jest_v17.x.x/flow_v0.16.x-/jest_v17.x.x.js
definitions/npm/jest_v18.x.x/flow_v0.16.x-/jest_v18.x.x.js
definitions/npm/jest_v19.x.x/flow_v0.16.x-/jest_v19.x.x.js
definitions/npm/jest_v20.x.x/flow_v0.22.x-v0.38.x/jest_v20.x.x.js
definitions/npm/jest_v20.x.x/flow_v0.39.x-/jest_v20.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.22.x-v0.38.x/jest_v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.39.x-/jest_v21.x.x.js

Jamine should be Jasmine
changed it in all versions

Jest: fix typo

---

definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/test_rxjs.js

Add type definitions for RxJS last

---

definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js

Hello
Here's the relevant section in mongoose source:
https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L1320-L1329

Fix wrong return value for index() of Mongoose$Schema

---

definitions/npm/chai_v4.x.x/flow_v0.15.0-/chai_v4.x.x.js
definitions/npm/chai_v4.x.x/test_chai_v4.x.x.js

Add `chai-enzyme`.
Add possibility to provide fail message.
Add `NaN` check.
Add `eq` check.

[chai] add missing typings

---

definitions/npm/firebase_v4.x.x/flow_v0.34.x-/firebase_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.28.x-v0.37.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.38.x-v0.46.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.47.x-v0.54.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js

```javascript
fromPairs: fromPairs(Array<[A,B]>) => { [A]: B }
zipObject: zipObject(Array<A>, Array<B>) => { [A]: B }
partition: returns an array of arity 2
keys: given an object with keys K, will return an Array<K>
```
======
FirebaseReference.onDisconnect.cancel() and FirebaseReference.onDisconnect.remove() have optional callback params [1]; they were previously typed as required
[1] https://firebase.google.com/docs/reference/node/firebase.database.OnDisconnect

Firebase lodash improvements

---

definitions/npm/helmet_v3.x.x/flow_v0.38.x-/helmet_v3.x.x.js
definitions/npm/helmet_v3.x.x/test_helmet_v3.x.x.js

This PR adds library definitions for the [helmet](https://github.com/helmetjs/helmet) package.
This is my first contribution to flow-typed so please let me know if I can adjust/adhere to anything.

Add library definition helmet_v3.x.x

---

definitions/npm/storybook-router_v0.x.x/flow_v0.25.x-/storybook-router_v0.x.x.js
definitions/npm/storybook-router_v0.x.x/flow_v0.25.x-/test_storybook-router_v0.x.x.js

Credit to @pascalduez for the work

Add storybook-router (replaces #1000)

---

definitions/npm/backbone-collection_v1.x.x/flow_v0.20.x-/backbone-collection_v1.x.x.js
definitions/npm/backbone-collection_v1.x.x/test_backbone-collection_v1.x.x.js
definitions/npm/backbone-model_v1.x.x/flow_v0.20.x-/backbone-model_v1.x.x.js
definitions/npm/backbone-model_v1.x.x/test_backbone-model_v1.x.x.js
definitions/npm/backbone_v1.x.x/flow_v0.20.x-/backbone_v1.x.x.js
definitions/npm/backbone_v1.x.x/test_backbone-v1.x.x.js

Backbone Partial Modules

---

definitions/npm/combine-section-reducers_v1.x.x/flow_v0.33.x-/combine-section-reducers_v1.x.x.js
definitions/npm/combine-section-reducers_v1.x.x/flow_v0.33.x-/test_combine-section-reducers.js

https://github.com/ryo33/combine-section-reducers

Add definitions for combine-section-reducers

---

definitions/npm/redux-actions_v2.x.x/flow_v0.34.x-v0.38.x/redux-actions_v2.x.x.js
definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/redux-actions_v2.x.x.js

Replaces #1267
All credit to @xMihai

Add support for nested reducers

---

definitions/npm/aphrodite_v0.5.x/flow_v0.28.x-/aphrodite_v0.5.x.js

Replaces #1092 
All credit to @ohad-coursera

Adding another export for the no-important module of Aphrodite

---

definitions/npm/koa-router_v7.2.x/flow_v0.25.x-/koa-router_v7.2.x.js
definitions/npm/koa-router_v7.2.x/test_koa-router_v7.2.x.js

This is my first attempt at contributing library definitions, so if anyone who's familiar with Koa could give this a review, I'd be thankful. I used [this](https://github.com/alexmingoia/koa-router/blob/master/lib/router.js) and [this](https://github.com/maichong/flow-koa-router/blob/master/flow/index.js) as a reference. Let me know if there are any changes that need to be made.

add type definitions for koa-router

---

definitions/npm/nanoid_v1.0.x/flow_v0.50.x-/nanoid_v1.0.x.js
definitions/npm/nanoid_v1.0.x/test_nanoid_v1.0.x.js

Was made internal changes. I just copied previous version

Add nanoid_v1.0.x

---

definitions/npm/formik_v0.9.x/flow_v0.53.x-/formik_v0.9.x.js

Formik actually supports ANY response from its event handler methods. Updating the flow types accordingly.

Update formik to allow any function response

---

definitions/npm/resolve-from_v4.x.x/flow_v0.25.x-/resolve-from_v4.x.x.js
definitions/npm/resolve-from_v4.x.x/test_resolve-from_v4.x.x.js

Adds module definition for [sindresorhus/resolve-from](https://github.com/sindresorhus/resolve-from)

Add definition for resolve-from

---

definitions/npm/filesize-parser_v1.x.x/flow_v0.25.x-/filesize-parser_v1.x.x.js
definitions/npm/filesize-parser_v1.x.x/test_filesize-parser_v1.x.x.js

[patrickkettner/filesize-parser](https://github.com/patrickkettner/filesize-parser)

Add definition for filesize-parser

---

definitions/npm/minimatch_v3.x.x/flow_v0.25.x-/minimatch_v3.x.x.js
definitions/npm/minimatch_v3.x.x/test_minimatch_v3.x.x.js

[isaacs/minimatch](https://github.com/isaacs/minimatch)

Add definition for minimatch

---

definitions/npm/pretty-bytes_v4.x.x/flow_v0.25.x-/pretty-bytes_v4.x.x.js
definitions/npm/pretty-bytes_v4.x.x/test_pretty-bytes_v4.x.x.js

https://github.com/sindresorhus/pretty-bytes

Add definition for pretty-bytes

---

definitions/npm/tempy_v0.x.x/flow_v0.47.x-/tempy_v0.x.x.js
definitions/npm/tempy_v0.x.x/test_tempy_v0.x.x.js

https://github.com/sindresorhus/tempy

Add definition for tempy

---

definitions/npm/del_v3.x.x/flow_v0.25.x-/del_v3.x.x.js
definitions/npm/del_v3.x.x/test_del_v3.x.x.js

https://github.com/sindresorhus/del

Add definition for del

---

definitions/npm/chai_v4.x.x/flow_v0.15.0-/chai_v4.x.x.js

https://github.com/astorije/chai-immutable#sizeofcollection-length

add chai-immutable tdd "sizeOf" method

---

definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/test_rxjs.js

Rxjs: add zip function

---

cli/yarn.lock
definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_object.js

Based on changes discussed in #1450, this improves `#props`.

Improve Ramda #props.

---

definitions/npm/jest_v21.x.x/flow_v0.22.x-v0.38.x/jest_v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.22.x-v0.38.x/test_jest-v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.39.x-/jest_v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.39.x-/test_jest-v21.x.x.js

Add setTimeout as available method

---

definitions/npm/ramda_v0.x.x/flow_v0.28.x-v0.30.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.28.x-v0.30.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/test_ramda_v0.x.x_list.js
definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_list.js

Adds forEachObjIndexed to ramda definition

---

definitions/npm/component-emitter_v1.x.x/flow_v0.34.x-/component-emitter_v1.x.x.js
definitions/npm/component-emitter_v1.x.x/test_component-emitter_v1.x.x.js

Add library definition for [component-emitter](https://github.com/component/emitter)

Add library definition for component-emitter

---

definitions/npm/socket.io-client_v2.x.x/flow_v0.34.x-/socket.io-client_v2.x.x.js
definitions/npm/socket.io-client_v2.x.x/test_socket.io-client_v2.x.x.js

Add library definition for [socket.io-client](https://socket.io/docs/client-api/)

Add library definition for socket.io-client

---

definitions/npm/localforage_v1.5.x/flow_v0.25.x-/localforage_v1.5.x.js
definitions/npm/localforage_v1.5.x/test_localforage.js

The documentation (http://localforage.github.io/localForage/) has a
series of excellent examples of nearly the entire api surface, so those
were used as tests.

Add libdefs for localforage 1.5.x

---

definitions/npm/react-router-native_v4.x.x/flow_v0.53.x-/react-router-native_v4.x.x.js
definitions/npm/react-router-native_v4.x.x/flow_v0.53.x-/test_react-router-native.js

Update libdef for 'react-router-native v4.x.x'

---

definitions/npm/redux-oidc_v3.x.x/flow_v0.55.x-/redux-oidc_v3.x.x.js
definitions/npm/redux-oidc_v3.x.x/flow_v0.55.x-/test_redux-oidc.js

Add more fields to the User type based on the typescript definition
in  oidc-client-js

redux-oidc - add more fields to User type

---

definitions/npm/redux-oidc_v3.x.x/flow_v0.55.x-/redux-oidc_v3.x.x.js
definitions/npm/redux-oidc_v3.x.x/flow_v0.55.x-/test_redux-oidc.js

Update optional params for signinRedirect, successCallback, and more fields to the User type.

redux-oidc: Update optional params for signinRedirect, successCallback, and fields..

---

definitions/npm/u2f-api_v0.x.x/flow_v0.42.x-/u2f-api_v0.x.x.js
definitions/npm/u2f-api_v0.x.x/test_u2f-api.js

https://www.npmjs.com/package/u2f-api

add u2f-api flowtypes

---

definitions/npm/koa-router_v7.2.x/flow_v0.25.x-/koa-router_v7.2.x.js
definitions/npm/koa-router_v7.2.x/test_koa-router_v7.2.x.js

Each http method can accept multiple endpoints

fix(koa-router): add multiple endpoints

---

definitions/npm/klasa_v0.3.x/flow_v0.39.0-/klasa_v0.3.x.js
definitions/npm/klasa_v0.3.x/test_klasa_v0.3.js

Based on <https://github.com/dirigeants/klasa/blob/master/typings/index.d.ts>.

Add klasa v0.3 libdef

---

definitions/npm/socket.io-client_v2.x.x/flow_v0.34.x-/socket.io-client_v2.x.x.js
definitions/npm/socket.io-client_v2.x.x/test_socket.io-client_v2.x.x.js

This fixes a number of problems with the library definition of socket.io-client.

Fix a bunch of problems with socket.io-client

---

definitions/browser/doubleclick-gpt_150.x.x/flow_v0.51.x-/doubeclick-gpt_150.x.x.js
definitions/browser/doubleclick-gpt_150.x.x/test_doubleclick-gpt_150.x.x.js

* Move doubleclick-gpt tests into the right folder
* Fix global type pollution

Fix doubleclick-gpt 150.x

---

definitions/npm/classnames_v2.x.x/flow_v0.25.x-/classnames_v2.x.x.js
definitions/npm/react-css-modules_v3.x.x/flow_v0.32.x-v0.52.x/react-css-modules_v3.x.x.js
definitions/npm/redux-mock-store_v1.2.x/flow_v0.25.x-/redux-mock-store_v1.2.x.js
definitions/npm/unified_v6.x.x/flow_v0.47.x-/unified_v6.x.x.js

In addition to #184, I tweaked some libdefs' module.exports 🙂

Tweak libdefs' module.exports

---

definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.31.x-v0.33.x/test_ramda_v0.x.x_logic.js
definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.34.x-v0.38.x/test_ramda_v0.x.x_logic.js
definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.39.x-v0.48.x/test_ramda_v0.x.x_logic.js
definitions/npm/ramda_v0.x.x/flow_v0.49.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.49.x-/test_ramda_v0.x.x_logic.js

A few files here have been heavily modified by the "prettier" package. I've only attempted to add the `pathSatisfies` ramda export definition.

feat(ramda): add pathSatisfies function

---

definitions/npm/mongodb_v2.x.x/flow_v0.25.x-/mongodb_v2.x.x.js
definitions/npm/mongodb_v2.x.x/test_mongodb-v2.js

See https://github.com/flowtype/flow-typed/pull/1473#issuecomment-345252760

Added temporary stubs for mongodb to avoid errors

---

definitions/npm/enzyme_v3.x.x/flow_v0.53.x-/enzyme_v3.x.x.js

https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/isEmptyRender.md

Add isEmptyRender to enzyme

---

definitions/npm/prosemirror-model_v1.x.x/flow_v0.59.x-/prosemirror-model_v1.x.x.js
definitions/npm/prosemirror-model_v1.x.x/test_prosemirror-model.js
definitions/package-lock.json

This probably needs more exhaustive tests, but I've been using these definitions on a moderately complex side project for a little bit now and I'm finally happy enough with them to open a PR. Stay tuned for PRs for `prosemirror-state`, `prosemirror-view`, etc.

Add defs for prosemirror-model v1.x.x

---

definitions/npm/react-native-google-analytics-bridge_v5.3.x/flow_v0.56-/react-native-google-analytics-bridge_v5.3.x.js
definitions/npm/react-native-google-analytics-bridge_v5.3.x/flow_v0.56.x-/react-native-google-analytics-bridge_v5.3.x.js
definitions/npm/react-native-google-analytics-bridge_v5.3.x/test_react-native-google-analytics-bridge_v5.3.x.js

This is mostly a straight conversion of the library's TypeScript definitions.

add react-native-google-analytics-bridge 5.3.x

---

definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js

Methods implemented:
```
lpush: (key: string, value: any) => void;
hset: (topic: string, key: string, value: string) => number;
hget: (topic: string, key: string, value: string) => string;
hgetall: (topic: string, key: string) => Array<string>;
```
Associated redis documentation: 
[lpush](https://redis.io/commands/lpush)
[hset](https://redis.io/commands/hset)
[hget](https://redis.io/commands/hget)
[hgetall](https://redis.io/commands/hgetall)
Have a nice day.

feat(npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js) new methods added

---

definitions/npm/glob-promise_v3.3.x/flow_v0.47.x-/glob-promise_v3.3.x.js
definitions/npm/glob-promise_v3.3.x/test_glob-promise_v3.3.x.js

Hey there!
I've got a library definition written up for glob-promise v3.3.x (latest).  It's tested too!
Let me know if there's anything I need to do if this isn't ready for merging.

Add type definition for glob-promise v3.3.x

---

definitions/npm/angular_v1.5.x/flow_v0.47.x-/angular_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_angular_component_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_angular_scope_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_angular_timeout_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_angular_v1.5.x.js
definitions/npm/angular_v1.5.x/flow_v0.47.x-/test_utility_functions_v1.5.x.js

angular 1.5 introduced type definitions for components: https://docs.angularjs.org/guide/component
Component is the only interface change/addition compared to angular 1.4.x
first commit copies over angular 1.4 libdefs, second commit introduces component

Angular 1.5.x types

---

cli/src/commands/runTests.js

If user hasn't `unzip` util on Linux or MacOS then flow-typed run-tests failed. I replace native call to unzip module.
I filter files in bin dir, if we have trash in bin folder.
#1519 should be solved

remove call native `unzip` on non-windows

---

definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js

Replaces #1624 
All credit to @rimiti

Redis rpoplpush() and rpoplpushAsync()

---

definitions/npm/mysql_v2.x.x/flow_v0.28.x-/mysql_v2.x.x.js

Add signature for raw() function
Fix signature of optional escape() args
Fix signature of typeCast param
Fix signature of getConnection()
Replaces #1618 
All credit to @nvie

Fixed for mysql signatures

---

definitions/npm/latlon-geohash_v1.x.x/flow_v0.25.x-/latlon-geohash_v1.x.x.js
definitions/npm/latlon-geohash_v1.x.x/test_latlon-geohash_v1.x.x.js

- ✨ Add libdef for latlon-geohash_v1.x.x
- ✅ Add tests for latlon-geohash_v1.x.x

✨ Add libdef for latlon-geohash_v1.x.x

---

definitions/npm/temp_v0.8.x/flow_v0.58.x-/temp_v0.8.x.js
definitions/npm/temp_v0.8.x/test_temp_v0.8.x.js

Definitions for https://github.com/bruce/node-temp

Add temp_v0.8.x

---

definitions/npm/shell-escape_v0.2.x/flow_v0.58.x-/shell-escape_v0.2.x.js
definitions/npm/shell-escape_v0.2.x/test_shell-escape_v0.2.x.js

Definitions for https://github.com/xxorax/node-shell-escape

Add shell-escape_v0.2.x

---

definitions/npm/awilix_v2.x.x/flow_v0.56.x-/awilix_v2.x.x.js
definitions/npm/awilix_v2.x.x/test_awilix_v2.x.x.js

There's a bug in how I was defining a few things in this awilix libdef that I've since fixed.  Thanks for your time!

Awilix fix

---

definitions/npm/knex_v0.12.x/flow_v0.38.x-/knex_v0.12.x.js
definitions/npm/knex_v0.13.x/flow_v0.38.x-/knex_v0.13.x.js

knex: fix first signature

---

definitions/npm/luxon_v0.2.x/flow_v0.32.0-/luxon_v0.2.x.js
definitions/npm/luxon_v0.2.x/test_luxon.js

This is complete as far as I know, and pretty thoroughly tested.

add defs for luxon_v0.2.x

---

definitions/npm/formik_v0.9.x/flow_v0.53.x-/formik_v0.9.x.js

adding missing field name for FieldProps matching

adding missing field name for FieldProps

---

definitions/npm/express_v4.16.x/flow_v0.32.x-/express_v4.16.x.js

This seems to have been forgotten / accidentally removed?

Adding express$RequestResponseBase to express$Request and express$Response

---

definitions/npm/cookie-dough_v0.x.x/flow_v0.25.x-/cookie-dough_v0.x.x.js
definitions/npm/cookie-dough_v0.x.x/test_cookie-dough_v0.x.x.js

* add defs for cookie-dough_v0.x.x

feat(npm/cookie-dough_v0.x.x.js): add defs for cookie-dough_v0.x.x

---

definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/test_rxjs.js

http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-map

Rxjs fix a signature for 'map'

---

definitions/npm/formik_v0.9.x/flow_v0.53.x-/formik_v0.9.x.js

declaring a type for HOC

---

definitions/npm/yamljs_v0.x.x/flow_v0.28.0-/yamljs_v0.x.x.js
definitions/npm/yamljs_v0.x.x/test_yamljs_v0.x.x.js

Initial incomplete definition for yamljs, adds definitions for parse and stringify

yamljs: create definition

---

definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.55.x-/test_lodash-v4.x.x.js

Fix the incorrect type signature of `zipWith`.

Fix lodash/zipWith types

---

definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.55.x-/test_lodash-v4.x.x.js

Lodash map allows mapping over tuples.

Allow tuple types for lodash map

---

definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/jest_v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.25.x-v0.38.x/test_jest-v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js

https://facebook.github.io/jest/docs/en/jest-object.html#jestrestoreallmocks

Add definition for jest.restoreAllMocks().

---

definitions/npm/react-test-renderer_v16.x.x/flow_v0.47.x-/react-test-renderer_v16.x.x.js
definitions/npm/react-test-renderer_v16.x.x/flow_v0.53.x-/react-test-renderer_v16.x.x.js
definitions/npm/react-test-renderer_v16.x.x/test_react-test-renderer-v16.x.x.js

I updated definitions according to https://github.com/flowtype/flow-typed/pull/1697#issuecomment-355319067

Update react-test-renderer definitions.

---

definitions/npm/knex_v0.13.x/flow_v0.38.x-/knex_v0.13.x.js
definitions/npm/knex_v0.13.x/test_knex-v0.13.js

Reference: http://knexjs.org/#Migrations-API

Add type for the Knex.migrate object

---

definitions/npm/react-helmet_v5.x.x/flow_v0.53.x-/react-helmet_v5.x.x.js
definitions/npm/react-helmet_v5.x.x/test_react-helmet.js

Library link: https://github.com/nfl/react-helmet

react-helmet_v5_x_x libdef + test

---

definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js

def: https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/delayWhen.ts
rebuilt and travis errors are gone

add delayWhen operator to rxjs definitions

---

definitions/npm/icepick_v1.x.x/flow_v0.47.x-/icepick_v1.x.x.js
definitions/npm/icepick_v1.x.x/test_icepick_v1.x.x.js

Added optional resolver to merge

---

definitions/npm/icepick_v1.x.x/flow_v0.47.x-/icepick_v1.x.x.js
definitions/npm/icepick_v1.x.x/test_icepick_v1.x.x.js

Hello again, I've made more improvements to the icepick flow-typing. These types were missing before and now I've added them with accompanying tests.

More updates to icepick

---

definitions/npm/lodash_v4.x.x/flow_v0.55.x-v0.62.x/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.55.x-v0.62.x/test_lodash-v4.x.x.js

(lodash) Update pick method to accept $ReadOnlyArray<T>

---

cli/src/commands/runTests.js

Fixes #1759 
Fixes #1724 
@AndrewSouthpaw 
@KenanY I ended up going for a very similar fix to yours, try it out and let me know if it does the trick. If this works I'll release a patch for flow-typed.

Fixes fetching and unzipping latest versions of flow [0.62+]

---

definitions/npm/mocha_v5.x.x/flow_v0.28.x-/mocha_v5.x.x.js
definitions/npm/mocha_v5.x.x/test_mocha_v5.x.x_context.js
definitions/npm/mocha_v5.x.x/test_mocha_v5.x.x_describe.js
definitions/npm/mocha_v5.x.x/test_mocha_v5.x.x_hooks.js
definitions/npm/mocha_v5.x.x/test_mocha_v5.x.x_it.js

There were no breaking changes to the Node.js API: https://github.com/mochajs/mocha/releases/tag/v5.0.0
So I just copied over the v4 defs.

add mocha v5

---

definitions/npm/match-sorter_v2.2.x/flow_v0.54.1-/match-sorter_v2.2.x.js
definitions/npm/match-sorter_v2.2.x/test_match-sorter_v2.2.x.js

Definitions for https://github.com/kentcdodds/match-sorter

Add match sorter definitions

---

definitions/npm/react-relay_v1.x.x/flow_v0.47.x-/react-relay_v1.x.x.js

[react-relay] Replace FlowFixMe with *

---

definitions/npm/decimal.js-light_v2.3.x/flow_v0.54.1-/decimal.js-light_v2.3.x.js
definitions/npm/decimal.js-light_v2.3.x/test_decimal.js-light_v2.3.x.js

Definitions for https://github.com/MikeMcl/decimal.js-light, mostly taken from typescript ones.

Add decimal.js-light definitions

---

definitions/npm/hoist-non-react-statics_v2.4.x/flow_v0.54.1-/hoist-non-react-statics_v2.4.x.js
definitions/npm/hoist-non-react-statics_v2.4.x/test_hoist-non-react-statics_v2.4.x.js

Definitions for https://github.com/mridgway/hoist-non-react-statics

Add hoist non react statics definitions

---

definitions/npm/react-modal_v3.1.x/flow_v0.54.1-/react-modal_v3.1.x.js
definitions/npm/react-modal_v3.1.x/test_react-modal_v3.1.x.js

Definitions for https://github.com/reactjs/react-modal v3.1.x

Add new react modal definitions

---

definitions/npm/react-toastify_v3.2.x/flow_v0.54.x-/react-toastify_v3.2.x.js

fix https://github.com/flowtype/flow-typed/issues/1787

ToastOptions not required

---

definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js
definitions/npm/react-navigation_v1.x.x/test_react-navigation.js

We (`react-navigation` maintainers) are switching from in-package types to hosting our types on `flow-typed` :)

Introduce react-navigation libdef

---

definitions/npm/react-relay_v1.x.x/flow_v0.47.x-/react-relay_v1.x.x.js

Currently, setting arrays as variables doesn't work.
Also, for instance passing function won't trigger any error
I thought this could be done as a recursive type, I think this covers every type of variable?, but perhaps I am missing something

React relay variables

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-fp-v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js

This indicates that the input is not mutated.

Update lodash/fp difference types to take $ReadOnlyArray

---

definitions/npm/react-intl_v2.x.x/flow_v0.57.x-/react-intl_v2.x.x.js

As per suggestion from @TomiS at https://github.com/flowtype/flow-typed/issues/1529#issuecomment-353566828

Fix react-intl definition

---

definitions/npm/react-dropzone_v4.x.x/flow_v0.53.x-/react-dropzone_v4.x.x.js
definitions/npm/react-dropzone_v4.x.x/test_react-dropzone_v4.x.x.js

Add a libdef for react-dropzone. https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L423

libdefs: Add react-dropzone type definition

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js

Changes made for: differenceWith, flatmap, groupBy, orderBy, sortBy, and transform.
This is one more step towards resolving: https://github.com/flowtype/flow-typed/issues/1099

[Lodash] Use $ReadOnlyArray when an array parameter is not modified

---

cli/package.json
cli/yarn.lock

Add babel-core peer dependency, fix Jest breaking

---

definitions/npm/react-flip-move_v2.9.x/test_react-flip-move_v2.9.x.js
definitions/npm/sha3_v1.2.x/flow_v0.56.x-/sha3_v1.2.x.js
definitions/npm/sha3_v1.2.x/test_sha3_v1.2.x.js

Add a definition for the SHA3 library here: https://github.com/phusion/node-sha3

sha3 definition (fixes eslint error in master)

---

definitions/npm/jsonwebtoken_v8.1.x/flow_v0.56.x-/jsonwebtoken_v8.1.x.js
definitions/npm/jsonwebtoken_v8.1.x/test_jsonwebtoken_v8.1.x.js

Adds a definition for jsonwebtoken from here: https://github.com/auth0/node-jsonwebtoken

jsonwebtoken definition

---

definitions/npm/react-color_v2.x.x/flow_v0.56.x-/react-color_v2.x.x.js
definitions/npm/react-color_v2.x.x/flow_v0.56.x-/test_react-color_v2.x.x.js

Edit: Am I doing something wrong to make Travis fail? Tests seem to pass for me.

add react-color

---

definitions/npm/rxjs_v5.0.x/flow_v0.25.0-v0.33.x/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/test_rxjs.js
definitions/npm/rxjs_v5.0.x/test_rxjs.js

Replaces  #1616
@rgbkrk Can you give this a look over and let me know if it makes sense?

[rxjs] Mixin Observer with Observable for Subject

---

definitions/npm/next-routes_v1.x.x/flow_v0.47.x-/next-routes_v1.x.x.js
definitions/npm/next-routes_v1.x.x/test_next-routes.js
definitions/npm/next_v2.x.x/flow_v0.53.x-/next_v2.x.x.js
definitions/npm/next_v2.x.x/test_next_v2.x.x.js
definitions/npm/next_v4.x.x/flow_v0.53.x-/next_v4.x.x.js
definitions/npm/next_v4.x.x/test_next_v4.x.x.js

Updates and fixed the great work done by @Jarlakxen on #1659
- Adds a definition for next_v4
- Updates the definition for next_v2, and increases lowest flow version
- Updates the definitions for next-routes

[next][next-routes] New and Updated definitions

---

definitions/npm/escape-html_v1.x.x/flow_v0.25.x-/escape-html_v1.x.x.js
definitions/npm/escape-html_v1.x.x/test_escape-html_v1.x.x.js

Definitions for https://github.com/component/escape-html , pretty straightforward...

Add escape-html_v1.x.x

---

definitions/npm/history_v4.x.x/flow_v0.25.x-/history_v4.x.x.js

Fixes #1877 
@mrm007 Could I get your eyes on this?

[history] Remove Action from global scope

---

definitions/npm/hoist-non-react-statics_v2.4.x/flow_v0.54.1-/hoist-non-react-statics_v2.4.x.js
definitions/npm/hoist-non-react-statics_v2.x.x/flow_v0.54.1-/hoist-non-react-statics_v2.x.x.js
definitions/npm/hoist-non-react-statics_v2.x.x/test_hoist-non-react-statics_v2.x.x.js

- Add support for hoisted statics (https://github.com/flowtype/flow-typed/pull/1783#issuecomment-362682624)
- Expand library version to 2.x.x

Improve hoist non react statics defs

---

definitions/npm/axios_v0.13.x/flow_v0.25.x-/axios_v0.13.x.js
definitions/npm/axios_v0.15.x/flow_v0.25.x-/axios_v0.15.x.js
definitions/npm/axios_v0.15.x/test_axios-v0.15.js
definitions/npm/axios_v0.16.x/flow_v0.25.x-/axios_v0.16.x.js
definitions/npm/axios_v0.16.x/test_axios-v0.16.js
definitions/npm/axios_v0.17.x/flow_v0.25.x-/axios_v0.17.x.js
definitions/npm/axios_v0.17.x/test_axios-v0.17.js

[axios] Fix maxRedirects type

---

definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js

Update all the callback annotations so the result argument isn't a maybe type when it doesn't need to.
Please see https://github.com/flowtype/flow-typed/pull/1755#discussion_r169025106 for the discussion that lead to this pull request.
cc @jedwards1211

Redis: update callback type annotations

---

definitions/npm/pluralize_v5.1.x/flow_v0.25.x-/pluralize_v5.1.x.js
definitions/npm/pluralize_v5.1.x/test_pluralize_v5.1.x.js
definitions/npm/pluralize_v6.x.x/flow_v0.25.x-/pluralize_v6.x.x.js
definitions/npm/pluralize_v6.x.x/test_pluralize_v6.x.x.js
definitions/npm/pluralize_v7.x.x/flow_v0.25.x-/pluralize_v7.x.x.js
definitions/npm/pluralize_v7.x.x/test_pluralize_v7.x.x.js

5.1, 6 and 7 have identical interfaces. isSingular and isPlural were added in 5.1: https://github.com/blakeembrey/pluralize/releases
Otherwise this is just a copy from previous pluralize.

libdefs for pluralize 5.1, 6 and 7

---

definitions/npm/storybook-host_v4.x.x/flow_v0.54.1-/storybook-host_v4.x.x.js
definitions/npm/storybook-host_v4.x.x/flow_v0.54.1-/test_storybook-host_v4.x.x.js

libdefs for storybook host: https://github.com/philcockfield/storybook-host

storybook-host

---

definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/react-bootstrap_v0.32.x.js
definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/test_react-bootstrap_v0.32.x.js

Types derived from here: https://react-bootstrap.github.io/components/alerts/

Libdefs for React bootstrap

---

definitions/npm/jsonwebtoken_v8.1.x/flow_v0.56.x-/jsonwebtoken_v8.1.x.js
definitions/npm/jsonwebtoken_v8.1.x/test_jsonwebtoken_v8.1.x.js

In this case:
https://github.com/auth0/node-jsonwebtoken/blob/master/verify.js#L10

[jsonwebtoken.verify]add missing type

---

definitions/npm/react-css-collapse_v3.x.x/flow_v0.54.1-/react-css-collapse_v3.x.x.js
definitions/npm/react-css-collapse_v3.x.x/flow_v0.54.1-/test_react-css-collapse_v3.x.x.js
definitions/npm/react-media_v1.x.x/flow_v0.54.1-/react-media_v1.x.x.js
definitions/npm/react-media_v1.x.x/flow_v0.54.1-/test_react-media_v1.x.x.js
definitions/npm/react-onclickoutside_v6.x.x/flow_v0.54.1-/react-onclickoutside_v6.x.x.js
definitions/npm/react-onclickoutside_v6.x.x/flow_v0.54.1-/test_react-onclickoutside_v6.x.x.js
definitions/npm/react-toggled_v1.x.x/flow_v0.54.1-/react-toggled_v1.x.x.js
definitions/npm/react-toggled_v1.x.x/flow_v0.54.1-/test_react-toggled_v1.x.x.js

New definitions for:
* https://github.com/SparebankenVest/react-css-collapse
* https://github.com/ReactTraining/react-media
* https://github.com/Pomax/react-onclickoutside
* https://github.com/kentcdodds/react-toggled

Add libdefs for a bunch of small react libs

---

definitions/npm/apollo-link-http_v1.2.x/flow_v0.56.x-/apollo-link-http_v1.2.x.js
definitions/npm/apollo-link-http_v1.2.x/test_apollo-link-http_v1.2.x.js

[apollo-link-http] Partial definition for apollo-link-http

---

definitions/npm/discord.js_v11.3.x/flow_v0.34.x-/discord.js_v11.3.x.js
definitions/npm/discord.js_v11.3.x/test_discord.js_v11.3.js

For reference, the TypeScript changes from v11.2.0 to v11.3.0: <https://github.com/discordjs/discord.js-typings/compare/697fc93...249c4b9>

Add discord.js v11.3.x libdef

---

definitions/npm/react-loadable_v5.x.x/flow_v0.56.0-/react-loadable_v5.x.x.js
definitions/npm/react-loadable_v5.x.x/flow_v0.56.0-/test_react-loadable_v5.x.x.js

https://github.com/jamiebuilds/react-loadable

Add initial react-loadable libdefs

---

definitions/npm/jest_v20.x.x/flow_v0.39.x-/jest_v20.x.x.js
definitions/npm/jest_v20.x.x/flow_v0.39.x-/test_jest-v20.x.x.js

See [release notes](https://github.com/FormidableLabs/enzyme-matchers/blob/master/CHANGELOG.md#500).

Update jest-enzyme@5 definitions

---

cli/src/lib/libDefs.js
cli/src/lib/npm/npmLibDefs.js
definitions/npm/ramda_v0.x.x/CONTRIBUTING.md

Closes #1926, allows #1925 to work.

Allow CONTRIBUTING.md files in libdefs.

---

cli/src/lib/libDefs.js
cli/src/lib/npm/npmLibDefs.js
definitions/npm/ramda_v0.x.x/CONTRIBUTING.md

This reverts commit c454f267eb1e0e8deb7f672dd1c92bf2a395159c. More on #1930.

Revert allowing CONTRIBUTING in sub folders.

---

cli/src/lib/libDefs.js
cli/src/lib/npm/npmLibDefs.js

Per discussion with @GAntoine. Related to #1930.

Allow any .md file in libdef folders.

---

definitions/npm/knex_v0.13.x/flow_v0.38.x-/knex_v0.13.x.js

Was initially spelled "intenral"!

Spelling error on "internal"

---

definitions/npm/ua-parser-js_v0.7.x/flow_v0.42.x-/ua-parser-js_v0.7.x.js
definitions/npm/ua-parser-js_v0.7.x/test_ua-parser-js_v0.7.x.js

Adds Flow definitions to https://github.com/faisalman/ua-parser-js

[new-def] Adds definitions and tests to `ua-parser-js`

---

README.md

So people know who to ping when they have questions, issues or want a review on a PR.

Adds a list of active maintainers to README

---

definitions/npm/@sendgrid/mail_v6.x.x/flow_v0.30.x-/mail_v6.x.x.js
definitions/npm/@sendgrid/mail_v6.x.x/flow_v0.30.x-/test_mail_v6.x.x.js

Hello everybody,
I've added the `@sendgrid/mail` definition.
Have a nice day.
Dimitri,

Adding @sengrid/mail definition

---

definitions/npm/amplitude-js_v4.x.x/flow_v0.47.x-/amplitude-js_v4.x.x.js
definitions/npm/amplitude-js_v4.x.x/flow_v0.47.x-/test_amplitude-js_v4.x.x.js

Added typings for [`amplitude-js`](https://github.com/amplitude/Amplitude-Javascript), taken from their code/documentation.

Add amplitude-js types

---

definitions/browser/chromecast-caf-receiver_v3.x.x/flow_v0.25.x-/chromecast-caf-receiver_v3.x.x.js
definitions/browser/chromecast-caf-receiver_v3.x.x/test_chromecast-caf-receiver_v3.x.x.js

Hi
This is a simple change that incorporates some missing enums that were lurking in the CAF Framework documentation.

Enhancement: Add missing enums and minor cleanup.

---

definitions/npm/setprototypeof_v1.x.x/flow_v0.25.x-/setprototypeof_v1.x.x.js
definitions/npm/setprototypeof_v1.x.x/flow_v0.25.x-/test_setprototypeof_v1.x.x.js

Library definition for [setptototypeof](https://www.npmjs.com/package/setprototypeof).

add setprototypeof definitions

---

definitions/npm/firebase_v4.x.x/flow_v0.34.x-/firebase_v4.x.x.js
definitions/npm/firebase_v4.x.x/flow_v0.34.x-/test_firebase.js

**Problem:** Firebase is missing Firestore definitions (gh-1657).
**Solution:** Add them. Followed the official [Firestore reference documentation](https://firebase.google.com/docs/reference/js/firebase.firestore)

Add firestore to firebase. Fixes gh-1657

---

definitions/npm/chai_v4.x.x/flow_v0.25.0-/chai_v4.x.x.js

Add 'className' and 'text' assertions for chai-enzyme

Add 'className' and 'text' check definitions

---

definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/react-bootstrap_v0.32.x.js

* Add Media component type
* Add NavDropdown component type
* Correct type for Button bsStyle prop
* Correct type for Col (xs|sm|md|lg)Hidden props

Update react-bootstrap libdef

---

definitions/npm/testcafe_v0.x.x/flow_v0.47.x-/testcafe_v0.x.x.js

Replaces #1885 
@jacobwgillespie Could I get your eyes on this?

Require specifying <*> for generics

---

cli/src/commands/__tests__/install-test.js
cli/src/commands/install.js

closes https://github.com/flowtype/flow-typed/issues/1505
Normally user wants to install same version as he have in package.json.

Look package version from package.json if not provided in package name

---

CONTRIBUTING.md

Pretty straightforward. Ironically, I can't tell from this md file if I need to do anything else to submit a docs PR. Hope it's enough. :)

Fix `return` typo in CONTRIBUTING.md

---

definitions/npm/deepmerge_v2.1.x/flow_v0.57.3-/deepmerge_v2.1.x.js
definitions/npm/deepmerge_v2.1.x/test_deepmerge_v2.1.x.js

Library definition for [deepmerge](https://github.com/KyleAMathews/deepmerge).

Add libdef for deepmerge

---

definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/sequelize_v4.x.x.js
definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js

See http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-addIndex

fix(sequelize): correct QueryInterface.addIndex arguments

---

definitions/npm/react-helmet_v5.x.x/flow_v0.53.x-/react-helmet_v5.x.x.js

Don't import React definitions globally in react-helmet

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.53.x-/react-router-dom_v4.x.x.js

https://reacttraining.com/react-router/web/api/Link/others
> You can also pass props you’d like to be on the <a> such as a title, id, className, etc.

Add className prop to react-router-dom Link component

---

definitions/npm/xterm_v3.x.x/flow_v0.56.x-/test_xterm_v3.x.x.js
definitions/npm/xterm_v3.x.x/flow_v0.56.x-/xterm_v3.x.x.js

References
---
* TS Definition: https://github.com/xtermjs/xterm.js/blob/master/typings/xterm.d.ts
* TS Test File: https://github.com/xtermjs/xterm.js/blob/master/fixtures/typings-test/typings-test.ts

add xterm libdef

---

definitions/npm/firebase_v4.x.x/flow_v0.34.x-/firebase_v4.x.x.js

Added actionCodeSettings type
Added parameter for sendEmailVerificationMethod
Changed onAuthStateChanged handler signature
Prettified

Firebase libdef update

---

definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/react-bootstrap_v0.32.x.js

`Pagination.Last` and `Pagination.Next` according to https://react-bootstrap.github.io/components/pagination/

Add two missing exports to `react-bootstrap`

---

definitions/npm/winston_v3.x.x/flow_all/winston_v3.x.x.js
definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js
definitions/npm/winston_v3.x.x/test_winston_v3.x.x.js

Added a libdef and test for the winston logging package.

Adding libdef for Winston Logging Package

---

definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/puppeteer_v1.2.x.js
definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_connect.js
definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_defaultArgs.js
definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_executablePath.js
definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_launch.js

This adds definitions for [puppeteer](https://github.com/GoogleChrome/puppeteer)

add puppeteer v1.2.x definitions

---

definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js
definitions/npm/redis_v2.x.x/flow_v0.34.x-/test_redis_v2.x.x.js

* Add support for options on set
* Add support for rest arguments on del

Update redis set and delete

---

definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/puppeteer_v1.2.x.js
definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_connect.js
definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_defaultArgs.js
definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_executablePath.js
definitions/npm/puppeteer_v1.2.x/flow_v0.58.x-/test_puppeteer_v1.2.x_launch.js

@saadq This updates the typedef taking your comments into consideration and adds more extensive tests. Please let me know if you have any other comments/suggestions. cc @AndrewSouthpaw

update puppeteer typedef and tests

---

definitions/npm/jest_v20.x.x/flow_v0.39.x-/jest_v20.x.x.js
definitions/npm/jest_v20.x.x/flow_v0.39.x-/test_jest-v20.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js
definitions/npm/react-testing-library_v2.x.x/flow_v0.58.0-/react-testing-library_v2.x.x.js
definitions/npm/react-testing-library_v2.x.x/flow_v0.58.0-/test_react-testing-library_v2.x.x.js

Added libdefs for https://github.com/kentcdodds/react-testing-library
Also included custom jest matchers provided by https://github.com/kentcdodds/dom-testing-library#custom-jest-matchers which is being used under the hood by react-testing-library

React testing library libdefs

---

definitions/npm/algoliasearch_v3.x.x/flow_v0.56.x-/algoliasearch_v3.x.x.js
definitions/npm/algoliasearch_v3.x.x/test_algoliasearch-v3.x.x.js

Add new algoliasearch definition (reboot from new clean fork)

Add algoliasearch definition

---

definitions/npm/pretty-error_v2.x.x/flow_v0.25.x-/pretty-error_v2.x.x.js
definitions/npm/pretty-error_v2.x.x/test_pretty-error-v2.js

[pretty-error] Improve return values

---

definitions/npm/koa-send_v4.x.x/flow_v0.56.x-/koa-send_v4.x.x.js
definitions/npm/koa-send_v4.x.x/flow_v0.56.x-/test_koa-send_v4.x.x.js

export type Options from koa-send_v4.x.x

---

definitions/npm/react-router_v4.x.x/flow_v0.30.x-v0.52.x/react-router_v4.x.x.js
definitions/npm/react-router_v4.x.x/flow_v0.53.x-/react-router_v4.x.x.js
definitions/npm/react-router_v4.x.x/flow_v0.53.x-/test_react-router.js

Added this to `react-router-dom` in #2053

Add staticContext to ContextRouter

---

definitions/npm/envalid_v4.x.x/flow_v0.56.x-/envalid_v4.x.x.js
definitions/npm/envalid_v4.x.x/test_envalid_v4.x.x.js

This is a new libdef to support [envalid](https://github.com/af/envalid)

Add libdef for Envalid

---

definitions/npm/react-toggled_v1.x.x/flow_v0.54.1-/react-toggled_v1.x.x.js

Docs ref: https://github.com/kentcdodds/react-toggled#ontoggle

Fix react-toggled onToggle type.

---

cli/flow-typed/npm/jest_v22.x.x.js
definitions/npm/jest_v20.x.x/flow_v0.39.x-/jest_v20.x.x.js
definitions/npm/jest_v20.x.x/flow_v0.39.x-/test_jest-v20.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.39.x-/jest_v21.x.x.js
definitions/npm/jest_v21.x.x/flow_v0.39.x-/test_jest-v21.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js
definitions/npm/jest_v22.x.x/flow_v0.39.x-/test_jest-v22.x.x.js

Use proper types for addSnapshotSerializer

---

definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js

Issue 2106 Add missing libdefs to redis_v2.x.x

---

definitions/npm/react-intl_v2.x.x/flow_v0.57.x-/react-intl_v2.x.x.js

InjectIntlOtions -> InjectIntlOptions

Fix typo in InjectIntlOtions type

---

cli/src/commands/create-stub.js
cli/src/lib/stubUtils.js

New method of generating stubs, based on module properties. It's looking for one (can be changed with --maxDepth) layer of properties and checks their types. Mostly created for modules that exports object filled with functions (i.e. Lodash) or statics.
Ps. I am asking for patience, the first PR I made so I could make some mistakes of a novice

Add new stub generation with guessed properties

---

definitions/npm/luxon_v0.2.x/flow_v0.32.0-/luxon_v0.2.x.js
definitions/npm/luxon_v0.4.x/flow_v0.32.0-/luxon_v0.4.x.js
definitions/npm/luxon_v1.x.x/flow_v0.32.0-/luxon_v1.x.x.js

these fields need to be implemented with getters so the type defs need to be covariant

fix(luxon): make zone fields covariant

---

definitions/npm/react-apollo_v2.x.x/flow_v0.58.x-/react-apollo_v2.x.x.js

Add missing API
https://www.apollographql.com/docs/react/api/react-apollo.html#apollo-consumer

Export ApolloConsumer component with react-apollo

---

definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js

- Added [descriminator](http://mongoosejs.com/docs/discriminators.html) method definitions.
- Add `_indexes` property to `Mongoose$SchemaField` it keeps info about indexes over particular field.
- Changed `declare export type` to `declare type` due eslint error.

Some additions to mongoose@4.0.0

---

CONTRIBUTING.md

Adding more words, because it's confusing otherwise.

Further clarify nuances of importing from other libdefs.

---

definitions/npm/chalk_v2.x.x/flow_v0.25.x-/chalk_v2.x.x.js
definitions/npm/chalk_v2.x.x/test_chalk_v2.x.x.js

I changed branch in my repo. So, I pull request again, sorry.
#2122

Support to use string template for chalk 

---

definitions/npm/directory-tree_v2.x.x/flow_v0.71.x-/directory-tree_v2.x.x.js
definitions/npm/directory-tree_v2.x.x/test_directory-tree_v2.x.x.js

Add [directory-tree](https://github.com/mihneadb/node-directory-tree) to flow-typed

add directory-tree

---

definitions/npm/react-transition-group_v2.x.x/flow_v0.60.x-/react-transition-group_v2.x.x.js
definitions/npm/react-transition-group_v2.x.x/test_react-transition-group.js

Add flow definitions for [react-transition-group](https://github.com/reactjs/react-transition-group)
Works fine, though according to the API some props could be a little more strict

Add react-transition-group definitions

---

definitions/npm/stringify-object_v3.x.x/flow_v0.50.x-/stringify-object_v3.x.x.js
definitions/npm/stringify-object_v3.x.x/test_stringify-object_3.x.x.js

See https://github.com/yeoman/stringify-object

Add stringify-object declaration

---

definitions/npm/rxjs_v5.0.x/flow_v0.34.x-/rxjs_v5.0.x.js
definitions/npm/rxjs_v5.0.x/test_rxjs.js

This uses the same logic as Array.

RxJS: Allow filtering maybe types with Boolean

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js

Fixes up a couple cases left over from #1845.

[lodash] lodash/fp/map and lodash/fp/filter should take $ReadOnlyArray

---

definitions/npm/react-testing-library_v3.x.x/flow_v0.60.0-/react-testing-library_v3.x.x.js
definitions/npm/react-testing-library_v3.x.x/flow_v0.60.0-/test_react-testing-library_v3.x.x.js

New definitions were exported from https://github.com/kentcdodds/react-testing-library/blob/master/typings/index.d.ts
Release info: https://github.com/kentcdodds/react-testing-library/releases

Add new libdefs for react-testing-library@3

---

definitions/npm/@storybook/addon-actions_v3.x.x/flow_v0.25.x-/addon-actions_v3.x.x.js

Improve typing for Action type in the storybook/addon-actions

[storybook] improve typing for Action type in the storybook

---

definitions/npm/react-onclickoutside_v6.x.x/flow_v0.54.1-/react-onclickoutside_v6.x.x.js
definitions/npm/react-onclickoutside_v6.x.x/flow_v0.54.1-/test_react-onclickoutside_v6.x.x.js

[react-onclickoutside] Add missing IGNORE_CLASS_NAME export

---

definitions/npm/apollo-client_v2.x.x/flow_v0.57.x-/apollo-client_v2.x.x.js
definitions/npm/apollo-client_v2.x.x/test_apollo-client_v2.x.x.js

See https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/index.ts#L28
@TLadd

[apollo-client] Add default export of ApolloClient

---

definitions/npm/chai_v4.x.x/flow_v0.25.0-/chai_v4.x.x.js
definitions/npm/chai_v4.x.x/test_chai_v4.x.x.js

Add `matchSnapshot` from [`chai-karma-snapshot`](https://github.com/localvoid/chai-karma-snapshot/blob/master/lib/index.d.ts#L6) to ExpectChain

Add matchSnapshot to chai ExpectChain

---

definitions/npm/chance_v1.x.x/flow_v0.25.x-/chance_v1.x.x.js

Quick review of [chancejs](http://chancejs.com) type definition.

[npm/chance] Add missing property and update old ones

---

definitions/npm/redis_v2.x.x/flow_v0.34.x-/redis_v2.x.x.js

Hello,
Small update on redis definition file.
Regards,

Adding Redis flushallAsync() definition

---

definitions/npm/styled-components_v3.x.x/flow_v0.57.x-/styled-components_v3.x.x.js
definitions/npm/styled-components_v3.x.x/flow_v0.57.x-/test_styled-components_v3.x.x.js

Fixes.
https://github.com/flowtype/flow-typed/pull/2190#issuecomment-391615925

added css as an export and wrote test for checking it

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js
definitions/npm/lodash_v4.x.x/flow_v0.63.x-/test_lodash-v4.x.x.js

lodash supports more than 1 additional argument for difference

lodash: support more than 1 array in difference

---

definitions/npm/@storybook/addon-links_v3.x.x/flow_v0.25.x-v0.52.x/addon-links_v3.x.x.js
definitions/npm/@storybook/addon-links_v3.x.x/flow_v0.53.x-/addon-links_v3.x.x.js
definitions/npm/@storybook/addon-links_v3.x.x/test_addon-links_v3.x.x.js

See https://github.com/storybooks/storybook/tree/master/addons/links

Add storybook/addon-links definitions

---

definitions/npm/backbone_v1.x.x/flow_v0.25.x-/backbone_v1.x.x.js
definitions/npm/backbone_v1.x.x/test_backbone-v1.x.x.js

View constructor now accepts options and does not require to return

backbone: fixed view constructor

---

definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js

Note to self: this includes my most recent `react-navigation` [PR](https://github.com/react-navigation/react-navigation/pull/4345/).

[react-navigation] Updates from our repo, mostly changes to actions

---

definitions/npm/opentok_v2.6.x/flow_v0.61.x-/opentok_v2.6.x.js
definitions/npm/opentok_v2.6.x/flow_v0.61.x-/test_opentok.js

ps: I define types inside of `declare module`, although the guidelines state to move them outside and prefix. If that's still the case let me know and I'll prefix types but I think that works very well with recent Flow.

Add opentok 2.6.2 defs

---

definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js

lodash: allow undefined to be passed as additional arguments to defaults

---

definitions/npm/metrics_v0.1.x/flow_v0.25.x-/metrics_v0.1.x.js
definitions/npm/metrics_v0.1.x/test_metrics_v0.1.x.js

Adding definitions and tests for [metrics](https://github.com/mikejihbe/metrics) v0.1.x. The definitions are based on the package's `index.d.ts` file and manually adjusted.

Add metrics v0.1.x definitions

---

definitions/npm/jquery_v3.x.x/flow_v0.28.x-/test_jquery.js

Tests for changes in #2286 
Tested locally with `node ./cli/dist/cli.js run-tests jquery_v3.x.x/flow_v0.28.x-`

* Update test for jquery for pattern `$el.data("key")`

---

definitions/npm/react-navigation_v1.x.x/flow_v0.60.x-/react-navigation_v1.x.x.js

This PR updates type definitions for React Navigation 1.x.x

Update react-navigation_v1.x.x from the lastest of react-navigation repo

---

definitions/npm/react-modal_v3.1.x/flow_v0.54.1-/react-modal_v3.1.x.js
definitions/npm/react-modal_v3.1.x/test_react-modal_v3.1.x.js

I wanna use async function for onAfterOpen function in react-modal package.
I thought these codes can fix this.
Please review or comments 🙏

react-modal: able to use promise for onAfterOpen

---

definitions/npm/url-join_v3.x.x/flow_v0.25.x-/url-join_v3.x.x.js
definitions/npm/url-join_v3.x.x/test_url-join_v3.x.x.js

✨libdef for url-join_v3.x.x

---

definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js

Includes https://github.com/react-navigation/react-navigation/pull/4495 and https://github.com/react-navigation/react-navigation/pull/4505

[react-navigation] Update libdef

---

definitions/npm/preposisjon_v0.x.x/flow_v0.25.0-/preposisjon_v0.x.x.js
definitions/npm/preposisjon_v0.x.x/test_preposisjon_v0.x.x.js

Adds a library definition for https://github.com/draperunner/preposisjon

Add definition for preposisjon

---

definitions/npm/react-native-communications_v2.2.x/flow_v0.25.x-/react-native-communications_v2.2.x.js
definitions/npm/react-native-communications_v2.2.x/test_react-native-communications_v2.2.x.js

Here is a library definition for this library: https://github.com/anarchicknight/react-native-communications

Add definition for react-native-communications

---

definitions/npm/haversine_v1.0.x/flow_v0.25.x-/haversine_v1.0.x.js
definitions/npm/haversine_v1.0.x/test_haversine_v1.0.x.js
definitions/npm/haversine_v1.1.x/flow_v0.25.x-/haversine_v1.1.x.js
definitions/npm/haversine_v1.1.x/test_haversine_v1.1.x.js

Adds library definition for https://github.com/njj/haversine

Add definition for haversine

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js

[@material-ui] Typography.Color - add textSecondary and remove accent

---

definitions/npm/backbone_v1.x.x/flow_v0.25.x-/backbone_v1.x.x.js

Backbone itself extends Events.
https://github.com/jashkenas/backbone/blob/master/backbone.js#L386

Update backbone_1.x.x: Backbone extends Events

---

definitions/npm/formik_v0.11.x/flow_v0.53.x-/formik_v0.11.x.js

According to https://github.com/jaredpalmer/formik#the-gist

[formik] improve types for withFormik function

---

definitions/npm/luxon_v1.x.x/flow_v0.32.0-/luxon_v1.x.x.js
definitions/npm/luxon_v1.x.x/test_luxon.js

Based on the changelog
https://github.com/moment/luxon/blob/master/changelog.md#130

Add new luxon methods

---

definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js

Added curried version for array map function for use in `pipe` for example

Ramda: Array map definition update

---

definitions/npm/js-joda_v1.8.x/flow_v0.25.x-/js-joda_v1.8.x.js
definitions/npm/js-joda_v1.8.x/flow_v0.25.x-/test_js-joda_v1.8.x.js

Weak tests, but this is a large lib and I'm eager to share types across a few projects at Meetup sooner rather than later.

New libdef: js-joda 1.8.x

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_all_imports_core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_module_imports_core_v1.x.x.js

Make material-ui Badge require correct colors

---

definitions/npm/chance_v1.x.x/flow_v0.25.x-/chance_v1.x.x.js
definitions/npm/chance_v1.x.x/test_chance-v1.x.x.js

The definition was missing the constructor.

[#2453]: Fixes chance js constructor

---

definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js

https://ramdajs.com/docs/#chain

[ramda] add types for chain function

---

definitions/npm/vcf_v2.0.1/flow_v0.55.x-/vcf_v2.0.1.js
definitions/npm/vcf_v2.0.1/test_vcf_v2.0.1.js

the vcard property constructor needed updating

add vcard property constructor

---

definitions/npm/metalsmith_v2.x.x/flow_v0.75.x-/metalsmith_v2.x.x.js
definitions/npm/metalsmith_v2.x.x/flow_v0.75.x-/test_metalsmith.js

https://github.com/segmentio/metalsmith

Add libdef for metalsmith 2.x.x

---

definitions/npm/jsonwebtoken_v8.3.x/flow_v0.56.x-/jsonwebtoken_v8.3.x.js
definitions/npm/jsonwebtoken_v8.3.x/test_jsonwebtoken_v8.3.x.js

Version 8.3 introduces a new way to retrieve secrets. This PR reflects this.

Add additional signature for jsonwebtoken verification

---

definitions/npm/moment_v2.3.x/flow_v0.63.x-/moment_v2.3.x.js

http://momentjs.com/docs/#/durations/weeks/

Add asWeeks()/weeks() to moment duration object

---

definitions/npm/chai_v4.x.x/flow_v0.25.0-/chai_v4.x.x.js

Was just adding these to my project and realized they weren't included, so I thought I'd go ahead and try opening a PR. The typings are pretty straightforward I think, lmk if there's anything else I need to add.
Thanks!

add typings for empty / isEmpty / notEmpty / isNotEmpty in chaijs assert

---

definitions/npm/@storybook/addon-a11y_v3.x.x/flow_v0.25.x-0.52.x/addon-a11y_v3.x.x.js
definitions/npm/@storybook/addon-a11y_v3.x.x/flow_v0.53.x-/addon-a11y_v3.x.x.js
definitions/npm/@storybook/addon-a11y_v3.x.x/test_addon-a11y_v3.x.x.js

See https://github.com/storybooks/storybook/tree/master/addons/a11y

Add storybook-addon-a11y definitions

---

definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js

v4.3.1 introduced another potential argument to matchPath as well as a new exposed generatePath function.

Update react-router-dom_v4.x.x.js for v4.3.1

---

cli/src/lib/stubUtils.js
definitions/npm/redux-saga_v0.16.x/flow_v0.56.0-/redux-saga_v0.16.x.js

Redux saga update delay signature

---

definitions/npm/bignumber.js_v7.x.x/flow_v0.55.x-/bignumber.js_v7.x.x.js
definitions/npm/bignumber.js_v7.x.x/flow_v0.55.x-/test_bignumber.js_v7.x.x.js

types ported from https://github.com/MikeMcl/bignumber.js/blob/master/bignumber.d.ts and required some manual adaptation (static fields, function style call of BigNumber,..) which i think was not covered by the other PR
test code coming from README of bignumber.js https://www.npmjs.com/package/bignumber.js

Add BigNumber.js support

---

definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js

Includes https://github.com/react-navigation/react-navigation/pull/4188 and https://github.com/react-navigation/react-navigation/pull/4667

[react-navigation] Update libdef from source repo

---

definitions/npm/mongoose_v5.x.x/flow_v0.50.x-/mongoose_v5.x.x.js

Also made an alphabetical order for easy sync in the future with http://mongoosejs.com/docs/api.html#Model

mongoose(5.x.x): add missing Model methods

---

definitions/npm/react-relay_v1.x.x/flow_v0.47.x-/react-relay_v1.x.x.js
definitions/npm/react-relay_v1.x.x/flow_v0.47.x-/test_Variables.js

Also add basic test to verify behavior.
Kept the same test style as the other test in `react-relay`.

react-relay: Fix Variables signature

---

definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js

Actual [R.length](https://ramdajs.com/docs/#length) works well also for string or any object that has `.length` property.

ramda: improved declaration of R.length

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js

I was recently using the incorrect **variant** option and flow never told me :(

@material-ui/core: update definitions of Type to Variant

---

definitions/npm/faker_v4.x.x/flow_v0.25.x-/faker_v4.x.x.js
definitions/npm/faker_v4.x.x/flow_v0.25.x-/test_faker_v4.x.x.js

Creates a new definition for [faker.js](https://github.com/Marak/faker.js)

Add definition for Faker.js

---

definitions/npm/js-yaml_v3.x.x/flow_v0.75.x-/js-yaml_v3.x.x.js
definitions/npm/js-yaml_v3.x.x/test_js-yaml.js

This libdef is based on [TS type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/js-yaml/index.d.ts).
I'm not sure where to use `mixed` and where `any` (I know the difference between them, but I don't know js-yaml library so well).

Add libdef for js-yaml

---

definitions/npm/ramda_v0.x.x/flow_v0.62.x-/ramda_v0.x.x.js
definitions/npm/ramda_v0.x.x/flow_v0.62.x-/test_ramda_v0.x.x_list.js

https://ramdajs.com/docs/#reduced

ramda: Add support for R.reduced

---

definitions/npm/mocha_v5.x.x/flow_v0.28.x-/mocha_v5.x.x.js

According to https://github.com/mochajs/mocha/issues/779#issuecomment-311882627

Missing mocha_v5.x.x.js timeout() definition

---

definitions/npm/koa_v2.0.x/flow_v0.47.x-/koa_v2.0.x.js
definitions/npm/koa_v2.x.x/flow_v0.47.x-/koa_v2.x.x.js

the properties on `CookiesSetOptions` that come with defaults should be optional

Make CookiesSetOptions with defaults optional

---

definitions/npm/winston_v3.x.x/flow_v0.34.x-/winston_v3.x.x.js

For https://github.com/flow-typed/flow-typed/issues/2561
Practically lifted from https://github.com/winstonjs/winston/blob/master/index.d.ts#L51-L71 but could use some additional eyes/verification.

[Winston] Add extra parameters to log methods

---

definitions/npm/ignore_v4.x.x/flow_v0.25.0-/ignore_v4.x.x.js
definitions/npm/ignore_v4.x.x/test_ignore.js

https://github.com/kaelzhang/node-ignore

Add libdef for ignore v4.x.x

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js

I would like to export prop definitions of components as well. 
I used Grid as an example.
Any one interested?

material-ui export props proposal

---

definitions/npm/angular_v1.5.x/flow_v0.47.x-/angular_v1.5.x.js

Reverts flow-typed/flow-typed#2626
Oh, CI was failing. @ruyasan would you mind fixing the angular tests and resubmitting the pr?

Revert "Fill out some missing details for angular 1.5"

---

definitions/npm/@babel/polyfill_v7.x.x/flow_v0.30.x-/polyfill_v7.x.x.js
definitions/npm/@babel/polyfill_v7.x.x/flow_v0.30.x-/test_polyfill_v7.x.x.js
definitions/npm/babel-polyfill_v6.x.x/flow_v0.30.x-/babel-polyfill_v6.x.x.js
definitions/npm/babel-polyfill_v6.x.x/flow_v0.30.x-/test_babel-polyfill_v6.x.x.js

Simplest libdefs ever.
Unfortunately I couldn't figure out how to prevent default export, maybe it's not possible?
https://babeljs.io/docs/en/babel-polyfill/
https://babeljs.io/docs/en/next/babel-polyfill.html

babel polyfill libdefs

---

definitions/npm/is-plain-object_v2.x.x/flow_v0.25.x-/is-plain-object_v2.x.x.js
definitions/npm/is-plain-object_v2.x.x/test_is-plain-object_v2.x.x.js

* [d.ts](https://github.com/jonschlinkert/is-plain-object/blob/master/index.d.ts) for [is-plain-object](https://github.com/jonschlinkert/is-plain-object)

Add is-plain-object

---

definitions/npm/simple-query-string_v1.x.x/flow_v0.25.x-/simple-query-string_v1.x.x.js
definitions/npm/simple-query-string_v1.x.x/flow_v0.25.x-/test_simple-query-string_v1.x.x.js

Add simple-query-string definitions:
(https://www.npmjs.com/package/simple-query-string)

Add definitions for simple-query-string

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js
definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/test_core_v1.x.x.js

Added and improved a bunch of @material-ui/core styling related types. Also added in a few tests to make sure everything is working as expected.
Thanks to @wcandillon for getting me started in the right direction with his existing (on hold) PR (#2152).

Added @material-ui/core Theme & refined withStyles, withTheme etc.

---

definitions/npm/react-dnd_v2.x.x/flow_v0.53.x-/react-dnd_v2.x.x.js
definitions/npm/react-dnd_v2.x.x/flow_v0.53.x-/test_react-dnd-v2.js

A duplicate of this: https://github.com/flow-typed/flow-typed/pull/1666 but rebased

react-dnd definition: Add DragDropContextProvider

---

definitions/npm/string-occurrence_v1.2.x/flow_v0.25.x-/string-occurrence_v1.2.x.js
definitions/npm/string-occurrence_v1.2.x/test_string-occurrence_v1.2.x.js

Definitions for https://github.com/SamVerschueren/string-occurrence

Add string-occurrence_v1.2.x

---

definitions/npm/axios_v0.15.x/flow_v0.25.x-v0.74.x/axios_v0.15.x.js
definitions/npm/axios_v0.16.x/flow_v0.25.x-v0.74.x/axios_v0.16.x.js
definitions/npm/axios_v0.16.x/flow_v0.75.x-/axios_v0.16.x.js
definitions/npm/axios_v0.17.x/flow_v0.25.x-v0.74.x/axios_v0.17.x.js
definitions/npm/axios_v0.17.x/flow_v0.75.x-/axios_v0.17.x.js
definitions/npm/axios_v0.18.x/flow_v0.25.x-v0.74.x/axios_v0.18.x.js
definitions/npm/axios_v0.18.x/flow_v0.75.x-/axios_v0.18.x.js

https://github.com/axios/axios/blob/master/UPGRADE_GUIDE.md#progress-config-option
https://github.com/axios/axios/blob/master/CHANGELOG.md#0140-aug-27-2016

axios split progress config option into onUploadProgress and onDownloadProgress in v0.14

---

definitions/npm/firebase_v5.x.x/flow_v0.34.x-/firebase_v5.x.x.js

signInWithEmailAndPassword should return Promise<$npm$firebase$auth$UserCredential>
see https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithEmailAndPassword

signInWithEmailAndPassword should return Promise<UserCredential>

---

definitions/npm/react-navigation_v2.x.x/flow_v0.60.x-/react-navigation_v2.x.x.js

Includes react-navigation/react-navigation#4917 & react-navigation/react-navigation#4836

[react-navigation] Update libdef from upstream

---

definitions/npm/@storybook/addon-knobs_v3.x.x/flow_all/addon-knobs_v3.x.x.js

Fix and improve storybook/addon-knobs definitions

---

definitions/npm/@material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js

The AppBar position attribute allows "relative" as a value.
https://material-ui.com/api/app-bar/

[material-ui] Update AppBar position attribute type
